### ISSUE TITLE
Vi key bindings

### ISSUE THREAD

**Issue by snoblenet** [jesseduffield/lazygit#10]
hi there,

Is there a settings files so I can add vi key bindings?

Thanks

**Comment by jesseduffield** [comment]
Letting users configure they own keybindings is next on my todo list :)

**Comment by snoblenet** [comment]
Awesome. I'd also like to configure some aspects of the UI. For example, stronger bolding of the selected item.

**Comment by jesseduffield** [comment]
the library I'm using for colours only supports a boolean of bold/not-bold, so it might be a little tricky to implement, but I will look into it

**Comment by snoblenet** [comment]
Ah, cool. I think I can change this in my terminal actually.

**Comment by jesseduffield** [comment]
@snoblenet https://github.com/jesseduffield/lazygit/commit/b1e6735d8dec036c486ae80b5cdffef86cec2396 adds better contrast for selected panels. Still not configurable, but as I had a second request about this, I thought it was worth making it standard

**Comment by snoblenet** [comment]
Thanks for this. I've updated lazygit but `j`, `k`, etc do nothing for me...?

```
brew info lazygit
jesseduffield/lazygit/lazygit: stable 0.1.61
A simple terminal UI for git commands, written in Go
https://github.com/jesseduffield/lazygit/
/usr/local/Cellar/lazygit/0.1.61 (5 files, 7.6MB) *
  Built from source on 2018-08-15 at 10:40:17
From: https://github.com/jesseduffield/homebrew-lazygit/blob/master/lazygit.rb

```

**Comment by jesseduffield** [comment]
hmm. If you open lazygit, what version number is shown at the bottom right of the UI? Perhaps you're using a different binary to what homebrew has downloaded

**Comment by snoblenet** [comment]
thanks it was using the binary initially installed via go

**Comment by khatchad** [comment]
Is there a sample file for vi key bindings?
