### ISSUE TITLE
files with space in the name send the wrong arguments to diff

### ISSUE THREAD

**Issue by fiendish** [jesseduffield/lazygit#100]
v0.1.48

```
git init test
cd test
touch foo\ bar
lazygit
```
👀  at the Diff pane

file name arguments to diff aren't being quoted, I guess?

<img width="931" alt="screen shot 2018-08-09 at 1 03 09 pm" src="https://user-images.githubusercontent.com/201996/43913999-99293dd2-9bd4-11e8-9461-1ee548d76227.png">

https://github.com/jesseduffield/lazygit/blob/9537645d0cfdac87addd4c9a5eb0e7df3bac8ee8/gitcommands.go#L404

**Comment by jesseduffield** [comment]
@fiendish I've pushed a fix based on @dawidd6's PR. Please see if that fixes the issue :)

**Comment by fiendish** [comment]
👍 lgtm
