### ISSUE TITLE
How do I turn off the welcome message?

### ISSUE THREAD

**Issue by brandoncc** [jesseduffield/lazygit#1003]
**Topic**
Welcome message ("Thanks for using lazygit" popup)

**Your thoughts**
I found the message helpful the first time I saw it, but now I don't enjoy seeing it each time. How can I turn it off? I would rather open to the files panel by default.

**Comment by jesseduffield** [comment]
That message should turn off automatically after you've viewed it for the first time. This suggests that the config file isn't being written to. If you navigate to the 'status' panel and press 'o' it should open your config file with at least:
```
reporting: "off"
startupPopupVersion: 1
```
What do you get when you hit 'o' on the status panel?

**Comment by brandoncc** [comment]
My config opens, which contains:

```
confirmOnQuit: true
```

I set that up earlier today, and I had to create the file manually.

**Comment by jesseduffield** [comment]
weird that it wasn't created automatically. Chuck 
```
reporting: "off"
startupPopupVersion: 1
```
in that file and you should be fine

**Comment by brandoncc** [comment]
Perfect, thank you!

**Comment by vyorkin** [comment]
I had to put `disableStartupPopups: false` to disable it

**Comment by ricardo-rp** [comment]
File also wasn't created automatically for me. I'm on M1 MBP, macOS Ventura 13.1 and installed through homebrew

**Comment by stefanhaller** [comment]
The above information is outdated, lazygit isn't supposed to store a `startupPopupVersion` property in the config file any more (or auto-create that file if it doesn't exist, for that matter). As of October 2020 this has changed to store it in a file called `state.yml` instead, in the same directory as the config file (`~/Library/Application Support/lazygit/` on Mac).

Could you check if that file exists, and what it contains? If you execute a shell command (try `: echo`), is that recorded in that file?

**Comment by konomichael** [comment]
> 

I had the same issue and solved it by putting `disableStartupPopups: true` in `config.yml(~/.config/lazygit/config.yml)`.

**Comment by konomichael** [comment]
> File also wasn't created automatically for me. I'm on M1 MBP, macOS Ventura 13.1 and installed through homebrew.
> 
> EDIT: @vyorkin 's solution works for me


I had the same issue and solved it by putting disableStartupPopups: true in `config.yml(~/.config/lazygit/config.yml)`.

**Comment by stefanhaller** [comment]
@konomichael Well, same questions for you then 😄: does `~/.config/lazygit/state.yml` exists? When was it last written, what does it contain?

**Comment by konomichael** [comment]
> @konomichael Well, same questions for you then 😄: does `~/.config/lazygit/state.yml` exists? When was it last written, what does it contain?

Nah, I don't think it first existed. I created a new file.

**Comment by stefanhaller** [comment]
I'm talking about `state.yml`, not `config.yml`.

**Comment by konomichael** [comment]
> I'm talking about `state.yml`, not `config.yml`.

well, I checked all backups of this file for the past half hour:
```yml
lastupdatecheck: 0
recentrepos:
- repo
startuppopupversion: 0
customcommandshistory: []
hidecommandlog: true
`

**Comment by stefanhaller** [comment]
OK, thanks. Could you now please remove (or comment out) the `disableStartupPopups` setting from `config.yml`, and start lazygit again; you should see the welcome message once, then the `startuppopupversion` setting in `state.yml` should go to 5, and on the next start you shouldn't see the welcome message again.

If this is not what happens, we should try to figure out why.

**Comment by konomichael** [comment]
The welcome msg did show again, but the `startuppopupversion` still keeps 0.

**Comment by stefanhaller** [comment]
That's strange, I can't explain why this would happen from reading the code. Can you tell from the modification date of `state.yml` whether the file was rewritten at all?

**Comment by duncanam** [comment]
Followed the above, still getting the welcome message every time on an Arch Linux machine installed through pacman.

**Comment by duncanam** [comment]
Installing `lazygit-git` through AUR + manually setting `disableStartupPopups: true` fixed this for me.

**Comment by hakunin** [comment]
I added this to my dockerfile since I am virtualizing my environment:

```
RUN mkdir -p /root/.config/lazygit
RUN echo "startuppopupversion: 5" > /root/.config/lazygit/state.yml
```
