### ISSUE TITLE
Lazygit doesn't start on macOS

### ISSUE THREAD

**Issue by pyrooka** [jesseduffield/lazygit#1005]
**Describe the bug**
Lazygit fails to start on macOS Catalina due to minVersionError error. The problem is here: https://github.com/jesseduffield/lazygit/blob/5611d9a3ef442bfa162ee604b94af3639db73a09/pkg/app/app.go#L144 because on macOS this is the output of the cmd:
```
$ git --version
git version 2.24.3 (Apple Git-128)
```

**To Reproduce**
1. Start the latest Lazygit on macOS

**Expected behavior**
Starts like before.

**Desktop (please complete the following information):**
 - OS: macOS Catalina 10.15.6
 - Lazygit Version 0.22.7

**Comment by jesseduffield** [comment]
DAMN

**Comment by V1RE** [comment]
For anyone looking for a quick fix, install a newer version of git via homebrew with `brew install git`

**Comment by jesseduffield** [comment]
fixed in https://github.com/jesseduffield/lazygit/pull/1006 (cutting a new release now: version v0.22.8)

**Comment by pyrooka** [comment]
That was fast, thank you!
