### ISSUE TITLE
Not using $EDITOR in zsh iTerm2

### ISSUE THREAD

**Issue by jrzhang12** [jesseduffield/lazygit#1007]
**Describe the bug**
When trying to edit a file at file panel in lazygit, it does not open with default editor. In my case, the default editor is nvim, but instead it opens with vim.

**To Reproduce**
1.  open lazygit
2. press e to edit a file in the file panel
3. opened with vim(not default nvim)

**Expected behavior**
open the file with nvim

**Screenshots**
![image](https://user-images.githubusercontent.com/41531801/93655521-ddb0af80-f9f1-11ea-9320-367db55394ba.png)

**Desktop (please complete the following information):** 
 - OS: MacOS
 - Lazygit Version 0.22.8

**Additional context**
the other weird thing is, it's showing bash in the screenshots while I am using zsh

**Comment by lordlycastle** [comment]
It's `GIT_EDITOR` and is it set properly in the gitconfig?

**Comment by jrzhang12** [comment]
> It's `GIT_EDITOR` and is it set properly in the gitconfig?

Thanks!
