### ISSUE TITLE
branches list showing phantom branches on case-insensitive file system

### ISSUE THREAD

**Issue by fiendish** [jesseduffield/lazygit#101]
v0.1.48

The branches pane should really be using the output from `branch -a` and not `git reflog -n100 --pretty='%cr|%gs' --grep-reflog='checkout: moving' HEAD` 

as used in https://github.com/jesseduffield/lazygit/blob/9537645d0cfdac87addd4c9a5eb0e7df3bac8ee8/gitcommands.go#L577 

for the list of what branches to show.

Currently you will pick up all kinds of things that aren't real branches if you're on a case insensitive file system (default setting for macOS HFS+ volumes).

```
$ git init test
$ cd test
$ touch foo
$ git add foo
$ git commit -m "init"
[master (root-commit) 00a9331] init
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 foo
$ git branch -a
* master
$ git branch test
$ git branch TEST
fatal: A branch named 'TEST' already exists.
$ git checkout TEST
Switched to branch 'TEST'
$ git checkout TeST
Switched to branch 'TeST'
$ git checkout TesT
Switched to branch 'TesT'
$ git checkout TEsT
Switched to branch 'TEsT'
$ git branch -a
  master
  test
```

meanwhile...
```
$ git reflog -n100 --pretty='%cr|%gs'
22 minutes ago|checkout: moving from TesT to TEsT
22 minutes ago|checkout: moving from TeST to TesT
22 minutes ago|checkout: moving from TEST to TeST
22 minutes ago|checkout: moving from master to TEST
22 minutes ago|commit (initial): init
```

<img width="137" alt="screen shot 2018-08-09 at 1 51 33 pm" src="https://user-images.githubusercontent.com/201996/43916374-66e06808-9bdb-11e8-8ca7-a0d252a1e9d9.png">

**Comment by fiendish** [comment]
@dawidd6 That seems to work for local branches.
@jesseduffield Is there a plan/desire to list remote branches too?

**Comment by dawidd6** [comment]
Yes i know. If one wants to also list remote branches, then `refs/head` needs to be removed.

**Comment by jesseduffield** [comment]
the reason behind using git reflog is so that you can see how recently you last checked out the branch. I agree that it's a semi-crappy solution for now. Does anybody know of a way of getting the branches not via `git reflog` but then obtaining the 'recency' as a second step?

**Comment by jesseduffield** [comment]
@fiendish I've just merged https://github.com/jesseduffield/lazygit/pull/112 which will resolve this issue. I've also recently merged https://github.com/jesseduffield/lazygit/pull/110 which changes how we obtain branches in general (reflog is now just used for the recency values, `git branch -a` does the rest). Let me know if this works on your end :)

Regarding the plan/desire to list remote branches, I certainly have the desire to! I'm just not sure how best to do it, as I imagine it could create a lot of clutter. Perhaps some way of switching between local/origin/etc

**Comment by fiendish** [comment]
It's better now, but I think not technically correct yet.

With that merge you won't see the entire history of names, but you will see whatever capitalization was used most recently regardless of the official branch capitalization.

e.g.

```
$ git checkout TEST
Switched to branch 'TEST'
$ lazygit
```

You'll see "TEST" in the branch list

```
$ git checkout test
Switched to branch 'test'
$ lazygit
```

Then you'll see "test" in the branch list

**Comment by jesseduffield** [comment]
Good pickup. I've pushed https://github.com/jesseduffield/lazygit/commit/2dba6f6733c4b4bcc1e4173200846f16616b469d which addresses those concerns, and adds a test repo script for easy verification

'r' is currently being used for a few different things in different panels, but I agree that it wouldn't be too hard to have a keybinding for toggling the panel

**Comment by fiendish** [comment]
👍  looks good
