### ISSUE TITLE
Issue when a merge.tool is defined

### ISSUE THREAD

**Issue by eric-bentley** [jesseduffield/lazygit#1010]
I'm using beyond compare as my merge tool with git.  (see https://www.scootersoftware.com/support.php?zz=kb_vcs_osx#git )
the 'git diff' command opens a bcompare gui window for the diff/merge.

When I try and use lazygit, it also opens the bcompare window rather than capturing the output, and gives the window focus to the called application.
To get a standard git diff, I use the --no-ext-diff option to git.  Can this be an option (or default) for lazygit?

**To Reproduce**
start lazygit with an external merge tool enabled.

**Expected behavior**
lazygit showing diff in ncurses frame

Ubuntu 18.04
$ lazygit -v
commit=, build date=2020-08-26, build source=debian, version=0.22.1, os=linux, arch=amd64
(installed from package - no built locally)

**Comment by jesseduffield** [comment]
@eric-bentley could you give https://github.com/jesseduffield/lazygit/pull/1012 a try and see if it resolves your issue?

**Comment by eric-bentley** [comment]
issue resolved.  Thanks.
