### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by fcdml** [jesseduffield/lazygit#1020]
**Describe the bug**

  client  will  crash when I  open client and type y or n

**To Reproduce**
2. Click on 'client'
4. crash

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/17615663/94337837-1539e000-0020-11eb-85f8-6e9f74cb17bc.png)
**Desktop (please complete the following information):**
 - OS: [Windows]
 - Lazygit Version [v0.2.2.8]
 - The last commit id if you built project from sources (run : ```git-rev parse HEAD```)
**Additional context**

**Comment by jesseduffield** [comment]
@fcdml  Is there a stack trace you're able to include here?

**Comment by fcdml** [comment]
sorry ,  I  don't know where the stack trace is . could you tell me how to find it in disk?  thank you
 And it just run in a git  
repository ?. I want to open  client  in other place and   go to repository by command

**Comment by jesseduffield** [comment]
The stack trace will display in the terminal itself after the program crashes. If you're not seeing that then I suppose it's failing gracefully without one. Hmm, not sure how to investigate this

**Comment by fcdml** [comment]
Today, it didn't flash back again. But it won't create  a new repository  in this folder when I type y. it will open a recent repository.
