### ISSUE TITLE
Slice bounds out of range

### ISSUE THREAD

**Issue by mewejo** [jesseduffield/lazygit#1028]
**Describe the bug**
Not sure if this is the error I keep getting but I've been having panics and finally had a chance to report one. This happened after a fetch of master when I was on another branch. That usually works fine. The computer was resumed from sleep though, if that could have any impact. Lazygit was running, PC slept, woken and then used Lazygit, and then panic.

**To Reproduce**
Steps to reproduce the behaviour:
1. Intermittent, but this time caused by fetching another branch after OS resumed from sleep.

**Expected behaviour**
Fetch the branch and not panic. It did fetch the branch successfully, but panicked after.

**Desktop:**
 - OS: Pop_OS! (Ubuntu 20.04)
 - Lazygit Version 0.22.6 (have since upgraded to 0.22.8 but didn't see any code changes which could be related to fix this)

**Additional context**

I used to run an older version of LG and it was solid. I updated a month or so ago and it's been buggy since. I can't remember what version I was previously running though, sorry.

```
panic: runtime error: slice bounds out of range [17:16]

goroutine 1 [running]:
github.com/jesseduffield/gocui.(*Gui).SetViewOnBottom(0xc00038a000, 0xc33d33, 0xc, 0xc0001864e0, 0xc0001c1b48, 0xc0007fe600)
	/home/runner/work/lazygit/lazygit/vendor/github.com/jesseduffield/gocui/gui.go:230 +0x3d5
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).deactivateContext(0xc0000da6c0, 0xdd63a0, 0xc0000b4320, 0x10, 0x11)
	/home/runner/work/lazygit/lazygit/pkg/gui/context.go:423 +0xb4
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).returnFromContext.func1(0xc00038a000, 0xc0001c1b10, 0x2)
	/home/runner/work/lazygit/lazygit/pkg/gui/context.go:410 +0xa1
github.com/jesseduffield/gocui.(*Gui).MainLoop(0xc00038a000, 0xc000000003, 0xc0000efc98)
	/home/runner/work/lazygit/lazygit/vendor/github.com/jesseduffield/gocui/gui.go:461 +0x2f3
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).Run(0xc0000da6c0, 0x0, 0x0)
	/home/runner/work/lazygit/lazygit/pkg/gui/gui.go:455 +0x507
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).RunWithSubprocesses(0xc0000da6c0, 0x0, 0xc000122980)
	/home/runner/work/lazygit/lazygit/pkg/gui/gui.go:465 +0x74
github.com/jesseduffield/lazygit/pkg/app.(*App).Run(0xc000290770, 0xc000122980, 0x0)
	/home/runner/work/lazygit/lazygit/pkg/app/app.go:207 +0x6b
main.main()
	/home/runner/work/lazygit/lazygit/main.go:70 +0x7f3
```

**Comment by jesseduffield** [comment]
good job catching the error. Looks like we must be deleting views and reading views at the same time, and the race condition causes issues. Two solutions come to mind: the first is to never delete views and instead just hide them (which I'm currently leaning towards: the unknown view error shows up all the time) or introduce a mutex that would apply whenever reading or mutating the array of views.

**Comment by mewejo** [comment]
I don't know any Go but that makes some sense! :) I had another panic on 0.22.8 just now, range numbers are different, but this time it happened after merging and then pushing a branch. Again, it pushed successfully but panicked after:

```
panic: runtime error: slice bounds out of range [16:15]

goroutine 1 [running]:
github.com/jesseduffield/gocui.(*Gui).SetViewOnBottom(0xc0002781e0, 0xc33d33, 0xc, 0xc0000aa660, 0xc000247b48, 0xc00059e780)
	/home/runner/work/lazygit/lazygit/vendor/github.com/jesseduffield/gocui/gui.go:230 +0x3d5
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).deactivateContext(0xc0003506c0, 0xdd63a0, 0xc0001a5590, 0xf, 0x10)
	/home/runner/work/lazygit/lazygit/pkg/gui/context.go:423 +0xb4
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).returnFromContext.func1(0xc0002781e0, 0xc000247b10, 0x2)
	/home/runner/work/lazygit/lazygit/pkg/gui/context.go:410 +0xa1
github.com/jesseduffield/gocui.(*Gui).MainLoop(0xc0002781e0, 0xc000000003, 0xc0000efc98)
	/home/runner/work/lazygit/lazygit/vendor/github.com/jesseduffield/gocui/gui.go:461 +0x2f3
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).Run(0xc0003506c0, 0x0, 0x0)
	/home/runner/work/lazygit/lazygit/pkg/gui/gui.go:455 +0x507
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).RunWithSubprocesses(0xc0003506c0, 0x0, 0xc00018e900)
	/home/runner/work/lazygit/lazygit/pkg/gui/gui.go:465 +0x74
github.com/jesseduffield/lazygit/pkg/app.(*App).Run(0xc000282770, 0xc00018e900, 0x0)
	/home/runner/work/lazygit/lazygit/pkg/app/app.go:222 +0x6b
main.main()
	/home/runner/work/lazygit/lazygit/main.go:70 +0x7f3
```

**Comment by jesseduffield** [comment]
https://github.com/jesseduffield/lazygit/pull/1030 should fix the issue, are you able to try out the master branch and see if you get any more panics?

**Comment by jesseduffield** [comment]
No worries :) I've added a `manual` installation guide to the [readme](https://github.com/jesseduffield/lazygit/blob/master/README.md#manual)

**Comment by mewejo** [comment]
Good pun ;) lazygit is now running from master, I'll let you know how it goes over the next week. Thanks for the speedy help and great work you do!

**Comment by mewejo** [comment]
I tried to click 'remotes' to check out another branch and it was selecting 'submodules' in the box above it instead. Then it panicked again but with a different error:

I was using `--path` to run it from this directory but use a different repo path.

```
anic: runtime error: index out of range [2] with length 2

goroutine 1 [running]:
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).onViewTabClick(...)
	/home/josh/Apps/lazygit/pkg/gui/view_helpers.go:416
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).keybindings.func1(0x2, 0xca937e, 0x8)
	/home/josh/Apps/lazygit/pkg/gui/keybindings.go:1648 +0xd3
github.com/jesseduffield/gocui.(*Gui).onKey(0xc000334000, 0xc000671af0, 0x2, 0x0)
	/home/josh/go/pkg/mod/github.com/jesseduffield/gocui@v0.3.1-0.20200930205305-1b445b9bd5da/gui.go:863 +0x17c
github.com/jesseduffield/gocui.(*Gui).handleEvent(...)
	/home/josh/go/pkg/mod/github.com/jesseduffield/gocui@v0.3.1-0.20200930205305-1b445b9bd5da/gui.go:529
github.com/jesseduffield/gocui.(*Gui).MainLoop(0xc000334000, 0xc000000004, 0xc000131c48)
	/home/josh/go/pkg/mod/github.com/jesseduffield/gocui@v0.3.1-0.20200930205305-1b445b9bd5da/gui.go:489 +0x1f2
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).Run(0xc000326000, 0x0, 0x0)
	/home/josh/Apps/lazygit/pkg/gui/gui.go:471 +0x528
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).RunWithSubprocesses(0xc000326000, 0x0, 0xc000124a00)
	/home/josh/Apps/lazygit/pkg/gui/gui.go:481 +0x74
github.com/jesseduffield/lazygit/pkg/app.(*App).Run(0xc0001ff6c0, 0xc000124a00, 0x0)
	/home/josh/Apps/lazygit/pkg/app/app.go:226 +0x6b
main.main()
	/home/josh/Apps/lazygit/main.go:103 +0xab9
exit status 2
```

**Comment by jesseduffield** [comment]
Good catch. Classic closures over loop variables. I've just pushed a fix for that :)

**Comment by mewejo** [comment]
So fast. Running it now and that remote one is fixed.

**Comment by mewejo** [comment]
Been running this for a couple of days now and not had a panic yet @jesseduffield :100:

**Comment by jesseduffield** [comment]
awesome :) closing
