### ISSUE TITLE
Feature Request - Delete branch

### ISSUE THREAD

**Issue by as14** [jesseduffield/lazygit#103]
Great work on this!  Would be great to have the ability to delete a branch.

**Comment by jesseduffield** [comment]
This would be fairly simple to implement, would you (or anybody else) be up for submitting a PR? I can give pointers if needed

**Comment by qJkee** [comment]
I'll do

**Comment by ponsfrilus** [comment]
@qJkee watch out #101 because right now, deleted branches are still showed up in the Branches pane because the branch list is taken from the ref log.

**Comment by jesseduffield** [comment]
I'm doing a refactor of the 'obtain branches' code now @ponsfrilus

**Comment by jesseduffield** [comment]
FYI the general algorithm will be:
```
get the currently checked out branch and add it to the final list
get the branches from `git branch -a`
get the branches from the reflog
for each reflog branch:
   if it has a matching branch in `git branch -a`
      add it to the final list and remove it from the `git branch -a` list
add the remaining branches from `git branch -a` to the final list
```
This means we get to keep the recency values but only use valid branches. Does that sound like a reasonable approach?

**Comment by jbialy** [comment]
@jesseduffield So your upcoming changes should also list the remote branches and not just the local ones?

**Comment by jesseduffield** [comment]
@jbialy my comment above relates to merging reflog data with your local branches. Having said that, I have begun scoping the remote-branches feature. The first part of that feature is listing remotes branches alongside the other branches. For origin remote branches, checking out will create a local branch tracking the remote branch, and for non-origin remote branches, you'll just checkout in a detached state. Does that sound like a reasonable approach?

**Comment by hubertba** [comment]
IMHO... everything on remote branches .. like a delete branch on remote would need a different UI ... like a prompt with the list of remote branches and selection there and then delete ... this is what I think .. thats why I would close that feature request ... deletion of local branches is already implemented ..

**Comment by jesseduffield** [comment]
Agreed. I'll close this now

**Comment by hubertba** [comment]
and it somehow correlates to the branch -a request ..
