### ISSUE TITLE
config.yml only works if it's readable and writable

### ISSUE THREAD

**Issue by timsofteng** [jesseduffield/lazygit#1040]
Hey. I use nixos. I'm trying to set lazygit config in nixos home-manager. But it could be read-only. 
Why lazygit don't work with read only config file?
Is it bug or feature&
![image](https://user-images.githubusercontent.com/51912173/95662251-3c270480-0b3e-11eb-8feb-426dfe060ff0.png)

**Comment by jesseduffield** [comment]
@timsofteng can you give this PR a go to see if it fixes your issue? https://github.com/jesseduffield/lazygit/pull/1041

**Comment by timsofteng** [comment]
@jesseduffield sorry for delay. It works in last release. Thanks!

**Comment by jesseduffield** [comment]
sweet :) closing
