### ISSUE TITLE
Incorrect config.yml path for macOS

### ISSUE THREAD

**Issue by aint** [jesseduffield/lazygit#1043]
Hi there,

I just upgraded to the latest release and noticed that my custom configs does not work. I navigate to the `Status Panel` then press `E` and it opens the wrong file: `"~/Library/Application"`

![image](https://user-images.githubusercontent.com/3179252/95683281-dcd6fc00-0bf2-11eb-8b1e-ba163f9ed5ae.png)

It looks like a bug, because it supposed to open `~/Library/Application Support/jesseduffield/lazygit/config.yml`. 

```
macOS 10.14.6
Lazygit: commit=, build date=, build source=homebrew, version=0.23.1, os=darwin, arch=amd64
```

**Comment by jesseduffield** [comment]
reproduced the issue and fixed with https://github.com/jesseduffield/lazygit/pull/1044. Does your config file still work though? As in, does lazygit correctly read it?

**Comment by peppy** [comment]
Just ran into this one. Can confirm fixed on master. Also it did not break my config at all, just wouldn't open it for editing.

**Comment by jesseduffield** [comment]
Awesome, closing :)
