### ISSUE TITLE
Shorter releases on Ubuntu PPA

### ISSUE THREAD

**Issue by MuratUrsavas** [jesseduffield/lazygit#1048]
Hi,

I'm using the Ubuntu PPA for installation and the latest release is 0.22.1. This version looks tagged in Aug 26. I personally know that a lot of improvements has been done, but I'm missing them right now. Could we have shorter release cycles like weekly? Is it too much to ask?

Or like other software, you can have an another PPA with CI to build and release daily.

Hope this is not too much to ask :)

Regards,

**Comment by jesseduffield** [comment]
forgive my shocking memory @dawidd6 is the PPA something you're familiar with?

**Comment by MuratUrsavas** [comment]
Should be. He's the owner of the PPA :)

https://launchpad.net/~lazygit-team

**Comment by dawidd6** [comment]
Imma look at automating this process soon.
