### ISSUE TITLE
Getting stuck with no response

### ISSUE THREAD

**Issue by skeept** [jesseduffield/lazygit#1052]
**Describe the bug**
lazygit gets stuck, no key press has any effect.

**To Reproduce**
Simply open the program often it works just fine. Other times it just freezes and no key press has any effect, not even `ctrl-c`.
This can either happen at the start before doing anything or after pressing some keys.

**Expected behavior**
The tool should not freeze.

**Desktop (please complete the following information):**
 - OS: Windows
 - Lazygit Version 0.23.2

**Additional context**
I am a relatively new user to lazigit I have been using it more from about a week ago.
Thanks for this program it's a quite nice work.

By looking at Task Manager it seems lazygit is actually taking a lot of CPU. The machine I use has 6 cores 12/logical and lazygit is showing 15% use so it seems its using 2 cores at 100%
The only way is for me to kill lazygit from task explorer.
Once I will it all they keys that I have send to lazygit are then sent to the console where lazygit was running.

**Comment by ecmrauh** [comment]
Same here on Debian with the current version after updating from an older version (about half a year old). It happens after pressing "space" on a file. After killing and restarting lazygit the file is green, which means that something happens after adding a file to the index.

**Comment by makky55** [comment]
I'm facing it, too.

* macos Catalina 10.15.7
* iterm2 3.3.12

```
$ lazygit -v
commit=, build date=, build source=homebrew, version=0.23.6, os=darwin, arch=amd64
```

**To Reproduce**

when some files are modified(not staged), push space key for staging , lazygit gets stuck.
I have to open another terminal(shell) and kill lazygit pid.

**Comment by jesseduffield** [comment]
@makky55 @ecmrauh @skeept are you guys still facing this issue on the latest version?

**Comment by skeept** [comment]
@jesseduffield personally I have not experienced this bug in a while.
Fell free to close based on feedback from other commenters.

Thank you.

**Comment by jesseduffield** [comment]
I'm closing this issue but if anybody gets the issue again on the latest release let me know

**Comment by makky55** [comment]
@jesseduffield 
I updated lazygit to v 0.27 and confirmed this bug, this bug was not occured (resolved).

Thank you.

**Comment by LemonJuicer96** [comment]
I am having this issue. `lazygit -v`: sudo git clone https://github.com/paroj/xpad.git /usr/src/xpad-0.4
sudo dkms install -m xpad -v 0.4

**Comment by Ramilito** [comment]
A little late to the party but setting 'showUntrackedFiles no' worked for me
```
git --git-dir=$HOME/.dotfiles/ config --local status.showUntrackedFiles no
```

**Comment by JordanllHarper** [comment]
I waited longest for a 5 minutes and had no response so closed the terminal process. The project is big but other git tools are working okay (such as the one in android studio).

**Comment by JordanllHarper** [comment]
Realised what I said above wasn't particularly helpful.

**Platform:** Macos Ventura

Found that lazygit for a specific repository,  which is an Android project, stopped working a day ago. This is a private repository.
I tested on other repositories such as deno, and though that repository is huge, it still managed to checkout and use other branches. 
I tested on other android projects of equal size, and also private, and that also works too. 
I can make new branches, pull from/push to remote, stage and make commits, and view the top of the git graph (in terms of the preview). I can also look at remote branches and make local branches from the 

The problems come when I try to checkout a different branch, or I press enter on a branch.
Android Studio indicates the branch has been changed to the selected branch. 
Lazygit freezes and the checking out spinner in the bottom left stops moving. It then becomes unresponsive and the terminal needs to be killed.

**Comment by Dom324** [comment]
@jesseduffield I had the same issue. Lazygit was laggy and kept randomly freezing.
I noticed comment from @Ramilito and added `showUntrackedFiles = no` to my .gitconfig file and the lagging is gone.

My working dir had huge amount of untracked files (lazygit says 150k). Seems like there is some perf bug that causes freezes every couple seconds when you have many untracked files.
