### ISSUE TITLE
Project logo

### ISSUE THREAD

**Issue by breisfeld** [jesseduffield/lazygit#1054]
Hi, I am a recent convert to lazygit, but am very impressed so far. I wonder if you would be receptive to another project logo. Here is an idea:
https://imgur.com/XqK14bJ

**Comment by mjarkk** [comment]
Hmmm don't know about this logo,  
How about making the letters of lazgit git commits with lines between them?

**Comment by breisfeld** [comment]
Sounds promising. Give it a try.

**Comment by jesseduffield** [comment]
I can't recall if I whipped up a logo in the readme before or after this issue was raised, but I'm satisfied with the current logo. Closing :)
