### ISSUE TITLE
-p / --path parameter crashes.

### ISSUE THREAD

**Issue by adam-wolski** [jesseduffield/lazygit#1057]
When running lazygit with path parameter program crashes on correct paths.
> *errors.errorString repository does not exist
> /home/runner/work/lazygit/lazygit/main.go:133 (0x9f3a7a)
> /opt/hostedtoolcache/go/1.14.9/x64/src/runtime/proc.go:203 (0x438f7a)
> /opt/hostedtoolcache/go/1.14.9/x64/src/runtime/asm_amd64.s:1373 (0x463c41)

Given incorrect path it return more correct:
> chdir dd: The system cannot find the file specified.

or

> Error: must be run inside a git repository

1. Run lazygit -p "path_to_some_repo"

System Info:
 - OS: Windows
 - Lazygit commit=7c1889cd70b81d9f8438c197c3d2fc89e5695160, build date=2020-10-14T10:55:09Z, build source=binaryRelease, version=0.23.6, os=windows, arch=amd64

**Comment by jesseduffield** [comment]
@adam-wolski I'm not able to replicate locally (on mac). Are you passing the full path?

**Comment by adam-wolski** [comment]
Interesting, I have saved .exe from when I reported the issue and now I cannot reproduce it either on same machine with same binary! 
Must have been something wrong on my end. Sorry.

**Comment by jesseduffield** [comment]
all good :)
