### ISSUE TITLE
Change the default lazygit configuration folder to .config/lazygit

### ISSUE THREAD

**Issue by benruijl** [jesseduffield/lazygit#1059]
The current default path for the lazygit settings is:

* Linux: `~/.config/jesseduffield/lazygit/config.yml`
* MacOS: `~/Library/Application Support/jesseduffield/lazygit/config.yml`
* Windows: `%APPDATA%\jesseduffield\lazygit\config.yml`

It follows the directory structure convention: author/project.

If I look in the `.config` folder, I see that all other programs (git, kitty, google-chrome, inkscape, etc) directly have the name of the program and do not have a folder with the name of the author/ developer group.

I would therefore suggest that the default folder for lazygit, is also moved to .config/lazygit.

**Comment by Liberatys** [comment]
This issue is also discussed in #913 and a change is in the pipeline #1095

**Comment by jesseduffield** [comment]
This is now resolved thanks to @Liberatys ! If you move your config folder up on directory it'll all work fine (we're maintaining backwards compatibility for people with the old config location, but all new lazygit uses will have the config directory created without the jesseduffield/ parent directory. Let me know if you have any issues :)
