### ISSUE TITLE
Github CLI Pull Request

### ISSUE THREAD

**Issue by joshmedeski** [jesseduffield/lazygit#1061]
**Is your feature request related to a problem? Please describe.**
I have to quit lazygit, open up a fresh terminal, and run `gh pr create` to open a pull request.

**Describe the solution you'd like**
I'd like to bind `gh pr create` to a keybinding in lazygit

**Describe alternatives you've considered**
This could be done running a custom command, but I don't want to have to type the command every time.

**Comment by jesseduffield** [comment]
I reckon you'd be able to do this with a custom command keybinding :)

Take a look [here](https://github.com/jesseduffield/lazygit/wiki/Custom-Commands-Compendium) and [here](https://github.com/jesseduffield/lazygit/blob/master/docs/Custom_Command_Keybindings.md). Lemme know if you need any pointers.

**Comment by joshmedeski** [comment]
Thanks, @jesseduffield!

It works like magic, I bound it to `<c-r>` (for pull **request**) and my browser opens right up with everything I need.

I added it to the [custom commands compendium wiki page](https://github.com/jesseduffield/lazygit/wiki/Custom-Commands-Compendium#open-github-pull-request) 😄

**Comment by joshmedeski** [comment]
The `createPullRequest` command is already built into lazygit. That was what I was looking for. :)

Type `o` in the branches context.

**Comment by jesseduffield** [comment]
Whoops, I had assumed that the `gh` command did more than what was built into lazygit. At any rate, thanks for adding that custom command to the wiki :)
