### ISSUE TITLE
Revert a file from an old commit

### ISSUE THREAD

**Issue by hakunin** [jesseduffield/lazygit#1065]
**Is your feature request related to a problem? Please describe.**
I often have to carve out files from commits so I can properly commit those changes as their own commits.
I run `git show [commit] -- [filename] | git apply -R`,  and then create a fixup commit that removes those files.
Then I create a commit that properly adds those files using the command above but this time on HEAD.
I always end up copying and pasting the filenames and the commit name. 

**Describe the solution you'd like**
Using lazygit, I would like to be able to press some command, similarly to how fixups on commits work, but on files from old commits. So I select a file from an old commit and press Shift-R, to revert that file using the command above.

**Describe alternatives you've considered**
I also used to use rebase to achive this, it requires less copy paste, but I'm trying to revert files, not rebase so I use the method above.

**Additional context**
Maybe I could add a custom command to do this, is there a way to add custom commands on specific items in the UI like files, commits, commited diffs etc?

**Comment by jesseduffield** [comment]
If I understand your request correctly, this feature is already enabled: you can go to a commit, press enter to view it's files, and then press 'd' to delete the file from that commit. This does an interactive rebase in the background. Is that what you're suggesting?

**Comment by hakunin** [comment]
The goal is to extract the files into a different commit.
Does it create a fixup commit with the files removed, or something I can re-revert to get a standalone commit that adds those files?

What would work as well is to have a bit of UI sugar around reverting, which normally involves a bunch of copy and pasting, is there any way to do a revert at the moment?

**Comment by jesseduffield** [comment]
to revert a commit you can press 't' on a commit (only works on a per-commit basis though).

To pull out files into a separate commit you can press space on each file and then go ctrl+p and select the option for pulling out into a separate commit). I'm not on my mac right now so can't quite recall the wording but let me know how that goes :)

**Comment by hakunin** [comment]
Wow, never knew this was a possibility, I'm going to play with that, looks very powerfull.

**Comment by danielo515** [comment]
The proposed workaround is not as ergonomic as creating a revert of a single file commit. Is this still not possible?
The suggested workaround is:

1. Isolate the changes you want to rever into a new commit?
2. Revert that commit?

**Comment by cgrebeld** [comment]
> The proposed workaround is not as ergonomic as creating a revert of a single file commit. Is this still not possible? The suggested workaround is:
> 
> 1. Isolate the changes you want to rever into a new commit?
> 2. Revert that commit?

Maybe there is a quicker way, but what I do is:
ctrl-s, select the file
select commit prior to the one in question
enter, select the file, c to check out

**Comment by danielo515** [comment]
And that reverts that file?

**Comment by danielo515** [comment]
> > The proposed workaround is not as ergonomic as creating a revert of a single file commit. Is this still not possible? The suggested workaround is:
> > 
> > 1. Isolate the changes you want to rever into a new commit?
> > 2. Revert that commit?
> 
> Maybe there is a quicker way, but what I do is: ctrl-s, select the file select commit prior to the one in question enter, select the file, c to check out

I tested your proposed solution, and it is very nice. I was not understanding what you were suggesting because I didn't know what each step was doing.

- ctrl-s -> makes a search across all commits for that file
- select the commit you want, then the file -> self explanatory
- C to checkout -> copies the content of the file at that specific commit to "the present"

So yes, your solution is exactly what I was looking for, thanks

**Comment by l3d00m** [comment]
> C to checkout -> copies the content of the file at that specific commit to "the present"

This doesn't seem to work in newer lazyvim. capital C is now binded to cherry pick commit. How would you do that know?

**Comment by mark2185** [comment]
Based on the `help` menu under `?`, I think you're looking for lowercase `c` to run `git checkout <hash> -- <filepath>`?

<img width="333" height="374" alt="Image" src="https://github.com/user-attachments/assets/1708d0df-dec9-4f5b-b943-5a0cae514b7d" />

**Comment by stefanhaller** [comment]
@l3d00m You are talking about the commits panel. Press enter to see the commit's files, `c` works there.
