### ISSUE TITLE
tmux unsupported terminal

### ISSUE THREAD

**Issue by bradyslot** [jesseduffield/lazygit#1066]
**Error:**
*errors.errorString termbox: error while reading terminfo data: termbox: unsupported terminal
github.com/jesseduffield/lazygit/main.go:133 (0x562491773ff7)
runtime/proc.go:204 (0x5624911aa609)
runtime/asm_amd64.s:1374 (0x5624911dd961)

**Reproduce:**
Launch lazygit from within a tmux pane
TERM=tmux-256color
TERMINAL=kitty
commit=7c1889cd70b81d9f8438c197c3d2fc89e5695160, build date=2020-10-30T00:37:43Z, build source=binaryRelease, version=0.23.6, os=linux, arch=amd64

Lazygit works fine in Kitty without tmux

**Comment by xunoaib** [comment]
I've also noticed this under tmux. Running lazygit with `TERM=xterm-256color lazygit` fixes it for me, also as described in #570. For reference, I'm on lazygit commit 4b55b2e7fca96dcdf2a25c6d66e4545a4f184db1

**Comment by guildem** [comment]
I think this is a termbox bug, probably related to the version used by lazygit.
Maybe this PR can help : https://github.com/jesseduffield/termbox-go/pull/1

**Comment by timsofteng** [comment]
same here

**Comment by jdelkins** [comment]
same issue here

**Comment by mjarkk** [comment]
In the awesome gocui fork we migrated to tcell and that should fix the issue.  
Jesse said he wanted to try getting it to work in lazygit but i don't know his status of that.
https://github.com/awesome-gocui/gocui/pull/73#issuecomment-749801742

**Comment by jesseduffield** [comment]
I'm making progress! Let me know if this branch resolves the issue: https://github.com/jesseduffield/lazygit/pull/1217

**Comment by jesseduffield** [comment]
as of release v0.27 we are now using tcell so I believe this problem is resolved, however let me know if I'm wrong about that!
