### ISSUE TITLE
Q: Does pulling via lazygit respect my config?

### ISSUE THREAD

**Issue by grossjohann** [jesseduffield/lazygit#1069]
First of all: Thank you for lazygit!  I won't claim that it is a dream come true, but I expect that I will migrate to it over time, as I learn it better, because it's just nicer than the other options.  I haven't found any GUI that does what I want.  `tig` is pretty nice, but does less than lazygit.

I've tried to understand what "pull" does in lazygit, but I haven't found it.  Specifically, I have the following in my `~/.gitconfig`, and I suspect that these settings are not respected:

```ini
[pull]
    rebase = true
[rebase]
    autostash = true
```

I have three questions: a question, a meta question, and a meta meta question.

* The question: Are the above settings respected when lazygit does "pull"?  If not, can I make it so?
* The meta question: WIBNI the documentation would explain so I don't have to ask here?
* The meta meta question: It's not clear to me where to ask such questions, please direct me to some other place if this is the wrong place.

**Comment by mjarkk** [comment]
First of all in lazygit we just run terminal commands so it should respect your gitconfig.  
Though there are some exceptions to this..  
In the case of pull rebase, merge or ff-only there is a lazygit config you'll have to change that can be found here: [/docs/Config.md](https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md)  
For the rebase autostash i'm not sure if there is a lazygit config for that, @jesseduffield probably knows that.

**Comment by grossjohann** [comment]
I had forgotten about that, but I have `git.pull.mode = rebase` in my config.  (Actually, that this option exists made me suspect that it might not just use whatever I have configured for the git command line tool.)

Will wait for further info on `rebase.autostash = true`...

**Comment by jesseduffield** [comment]
@grossjohann hey there :) we currently don't respect the git config with respect to pulling, but there's no good reason why we can't add support for it (for people interested the relevant line is `pkg/gui/files_panel.go:512`. We _do_ currently allow the user to set the pull mode (e.g. 'rebase') in the lazygit config e.g.:
```
git:
  pull:
    mode: 'rebase'
```

As for rebase, we pass the `--autostash` flag unconditionally so we would be ignoring the user config there, but again there's no good reason (that I can think of) that we couldn't read from the user's config here.

**Comment by grossjohann** [comment]
Thank you @jesseduffield.  It's great that lazygit has baked in my own favorite behavior :-)

So now I need to figure out what was happening on my end.  Let me close this thread; I can always come back once I have a concrete description that explains what I experience.

**Comment by Saafo** [comment]
> As for rebase, we pass the --autostash flag unconditionally so we would be ignoring the user config there, but again there's no good reason (that I can think of) that we couldn't read from the user's config here.

Hi @jesseduffield ,sorry to bother in this historical issue, but I found that currently when I want to pull current branch (with rebase) with changes unstaged or uncommited, it will notify that `Please commit or stash them`.

However, when I directly using `git pull --autostash` in terminal, it works as expected(doesn't need to stash manually).

I'm wondering whether the `--autostash` behavior still works as expected

**Comment by mark2185** [comment]
Are you using the latest version?

Could you please post your `.gitconfig`?

And just to confirm, you're not in a `rebase` context, you're just in the` Local branches` panel and press `p`?

**Comment by Saafo** [comment]
> you're not in a rebase context, you're just in the Local branches panel and press p?

Yes!

> Could you please post your .gitconfig?

I checked that I haven't set `rebase.autoStash` in gitconfig. I only set `pull.rebase`. After setting `rebase.autoStash`, `autoStash` works!
