### ISSUE TITLE
Work with multiple repositories without the need to leave lazygit and cd to each

### ISSUE THREAD

**Issue by amitlevy21** [jesseduffield/lazygit#1071]
**Is your feature request related to a problem? Please describe.**
Here is the use case, I have multiple repositories, each repository represents a microservice.

```sh
ls ~/Dev/
repo1 repo2 repo3
```

It would be awesome if i can just `cd ~/Dev` and then just work with lazygit from there.
Currently I need to cd to each repo dir, start lazygit, get out of lazygit, cd to other dir, start lazygit again.. which is cumbersome.

**Describe the solution you'd like**
VScode has something similar to what i'm asking, If i start vscode from a root folder that contains several folders where is folder is a git repo I get this:
![image](https://user-images.githubusercontent.com/28672915/98405695-62748d00-2075-11eb-8291-ea7454f7f49a.png)

As you can see, I can update each repo with latest of a branch, change a branch and commit per repo.

**Describe alternatives you've considered**
I know that if i start lazygit from a root dir that is not a git repo lazygit will ask me if I would like to create one, and if I choose not to, it will show a list of latest git repos. Which is nice, but is still cumbersome since there is no easy way (that I am aware of) to alternate between repositories easily. Also, I still need to say no to the prompt of "not a git repo..."

By the way, I would love if you can share your thoughs on whats the best approach in `lazydocker` to address multiple repositories?

Thanks!

**Comment by jesseduffield** [comment]
hey there @amitlevy21 , if you press 'enter' on the status panel you'll get a list of recent repos. I use this to navigate between repos easily. Does that satisfy your requirement?

As for lazydocker that would be a good feature request, but currently it's not possible

**Comment by amitlevy21** [comment]
Awesome, that works for me!

Thank you for the quick response!

**Comment by JunJianX** [comment]
> hey there @amitlevy21 , if you press 'enter' on the status panel you'll get a list of recent repos. I use this to navigate between repos easily. Does that satisfy your requirement?
> 
> As for lazydocker that would be a good feature request, but currently it's not possible

Excuse me, What if the sub repositories  in a deep path, it seems not able to show all the repos.But vscode could set max scan depth.Is lazygit have the seem setting? [image](https://github.com/user-attachments/assets/6522869f-b706-4b6f-aeb3-0af824dd7ecf)

**Comment by thuanpham582002** [comment]
> > hey there [@amitlevy21](https://github.com/amitlevy21) , if you press 'enter' on the status panel you'll get a list of recent repos. I use this to navigate between repos easily. Does that satisfy your requirement?
> > As for lazydocker that would be a good feature request, but currently it's not possible
> 
> [@jesseduffield](https://github.com/jesseduffield) Excuse me, What if the sub repositories in a deep path, it seems not able to show all the repos.But vscode could set max scan depth.Is lazygit have the same setting? [image](https://github.com/user-attachments/assets/6522869f-b706-4b6f-aeb3-0af824dd7ecf)

same question
