### ISSUE TITLE
Wandering with arrow keys in commit message causes shift to the left of the actual cursor

### ISSUE THREAD

**Issue by MuratUrsavas** [jesseduffield/lazygit#1075]
Hi,

I don't know if I can express correctly what I'm seeing for a long time. Let's say you are writing a commit message. And saw a problem what you've just written and moved with left arrow key to fix the typo. To continue where you've left, you press right arrow key to come to the end of the message.

Displayed cursor shows you are at the end, no problem. But if you start to write again, you see that actually (CURSOR_POS - 3) is edited. My humble brain is educated to expect changes on CURSOR_POS therefore it becomes really difficult to fix the rest of the message. Cancelling commit and restarting it fixes the issue.

Interestingly if you use backspace, correct letters are erased as expected but letters still inserted at CURSOR_POS - 3.

Hope I was able to explain the problem.

Regards,

$ lg --version
commit=, build date=2020-10-14, build source=debian, version=0.23.6, os=linux, arch=amd64

OS: Ubuntu 20.04

**Comment by jesseduffield** [comment]
@MuratUrsavas could you re-test this on the latest version? I suspect it may be resolved

**Comment by MuratUrsavas** [comment]
I have waited to receive the latest version of Lazygit and then forgot to report back. Was pretty busy with hardware design, not software development :) Since I've returned to software development recently I was able to check it again.

It looks like the issue has been fixed but we've lost HOME / END key functionality. Not a big problem but you may not be intended to remove this functionality.

By the way, Ubuntu PPA releases are pretty slow as you can see I still have the version below.

```
commit=, build date=2021-04-11, build source=debian, version=0.27.4, os=linux, arch=amd64
```

I leave the decision of whether to close or not the issue. I'm OK with the current status.

Cheers,

**Comment by jesseduffield** [comment]
home/end keys have been restored in https://github.com/jesseduffield/lazygit/pull/1523, so I'll close this issue
