### ISSUE TITLE
minor: please support keybinding <s-tab>

### ISSUE THREAD

**Issue by fluffynuts** [jesseduffield/lazygit#1076]
**Is your feature request related to a problem? Please describe.**
I'd like to use Tab (`<tab>`) to go to the next block and Shift+Tab (`<s-tab>` probably?) to cycle back, but I don't seem to be able to bind that particular sequence. The presence of `<s-space>` suggests that I have the correct syntax, so I guess it's simply not supported.

**Describe the solution you'd like**
I'd like to bind shift-tab with `<s-tab>`

**Describe alternatives you've considered**
just pressing `<tab>` until I cycle back to the start?

**Comment by jesseduffield** [comment]
this is unfortunately a limitation of termbox, one of our underlying libraries. I believe we can resolve this by switching from termbox to tcell but that is quite a challenge

**Comment by fluffynuts** [comment]
fair enough; no need to keep an issue open for this minor request (:
