### ISSUE TITLE
Lazygit deletes itself when asked to update

### ISSUE THREAD

**Issue by Odaeus** [jesseduffield/lazygit#1077]
**Describe the bug**
When I tried the auto-update option, it found an update and asked me to confirm downloading it. I did that but nothing seemed to happen. After quitting I discovered that Lazygit had unfortunately committed seppuku and deleted itself 😮 . Turns out I was on the latest version already anyway.

**To Reproduce**
1. Go to top left "status" panel.
2. Open menu with 'x'
3. Select "check for updates"
4. Press enter to confirm download
5. Quit lazygit
6. Try to run lazygit

**Expected behavior**
Lazygit only shows an update if there is a new version, and then updates instead of deleting itself.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.10
 - Lazygit Version: 0.23.7

**Additional context**
I normally install by downloading the binary from the releases page and extracting it to `~/bin`, which is in my $PATH.

**Comment by jesseduffield** [comment]
Good pickup. Should be fixed by https://github.com/jesseduffield/lazygit/pull/1094

**Comment by jesseduffield** [comment]
Closing, but lemme know if the issue persists :)
