### ISSUE TITLE
Shorter status names

### ISSUE THREAD

**Issue by eruizc-dev** [jesseduffield/lazygit#1078]
**Is your feature request related to a problem? Please describe.**

Where I work we have a strong naming scheme resulting in long directory names. Ex:
```
~/repos/<Company.Project.Key>/<Company>.Sources/<Company.Project>/<Company.Project.Web>/..
```
So when I look at the "files" square, all I see is the company and project name repeated 2 or 3 times in all modified files.

**Describe the solution you'd like**

I'd like to see the filename.

**Describe alternatives you've considered**

 - Show filename then the path to it
  `file.txt: <Company.Project.Key>/<Company>.Sources/<Company.Project>/<Company.Project.Web>/...`
 - Show only filename
  `file.txt`
 - Show as much as it fits from right (filename) to left and `...` the rest
  `.../<Company.Project>/<Company.Project.Web>/file.txt | <- End of box`

**Additional context**

I feel like this should be an existing feature, but I've seen nothing in the docs or tutorials.

**Comment by jesseduffield** [comment]
@eruizc-dev I'm currently working on the ability to switch to a mode where files are displayed in a tree format so that you'd see:
```
<Company.Project.Key>/
  <Company>.Sources/
    <Company.Project>/
      <Company.Project.Web>/
        file.txt
```
Is that something that might resolve this issue? Or would you prefer just showing the filename?

**Comment by eruizc-dev** [comment]
@jesseduffield as long as I get to see the filename it's a fix for me.
From a preference pov I'm not entirely sure. I like the simplicity of only filenames but js projects tend to have lots of index.js files and readme.md that may cause confusion...
I leave you decide wether you want a single tree view or one from many in a config file.

**Comment by jesseduffield** [comment]
@eruizc-dev the latest release lets you view the files as a tree (defaults to flat view but you can toggle it from within the app with the backtick key, and you can configure it in your config). Let me know how that goes for you

**Comment by eruizc-dev** [comment]
@jeffhertzler I just checked and it's amazing. Way more clear!
