### ISSUE TITLE
Request: add an option to default to staging all when attempting to commit and nothing is staged

### ISSUE THREAD

**Issue by fluffynuts** [jesseduffield/lazygit#1079]
**Is your feature request related to a problem? Please describe.**
the most common flow I have (and, I think, a lot of people have this flow) is to do some work, commit it all, lather-rinse-repeat. So 'c' is smart in that it can ask me if I want to stage all when none are staged, but in the spirit of being a lazy-ass dev, I'd really like to have a config point where I could say "yes, I'm super-lazy, so if I 'c' without staging anything, assume I mean _everything_ and stage the lot"

**Describe the solution you'd like**
a config option to stage all when committing with nothing staged, eg:
```yaml
gui:
	skipNoStagedFilesWarning: true
```

**Describe alternatives you've considered**
pressing 'a' and then 'c', forever, but this is twice as much work as I want to do. Did I mention how lazy I am?

**Additional context**
I'm so lazy, this will save me so much time and effort 😛

**Comment by jesseduffield** [comment]
This is a very reasonable request. I'm going to chuck a good-first-issue label on this in case somebody (perhaps you!) wants to pick it up cos it should be fairly straightforward to do. Happy to give pointers

**Comment by fluffynuts** [comment]
I actually did consider forking and adding -- my go-fu is minimal, but perhaps I'll give it a _go_ tonight.

**Comment by jesseduffield** [comment]
I see what you did there

**Comment by jesseduffield** [comment]
This is now implemented on master, thanks @fluffynuts !
