### ISSUE TITLE
When I want to edit somthing, and click <code> e </code>, it take an error as followings.

### ISSUE THREAD

**Issue by lxl0928** [jesseduffield/lazygit#108]
![image](https://user-images.githubusercontent.com/12816246/43949180-5796e8f6-9cbf-11e8-854b-ad5286f93382.png)

And also, I found that it support not very good for the commit message format, as picture shows.

So, are there any help documents to solve this error? Thank you.

**Comment by dawidd6** [comment]
Set EDITOR variable in your shell config.

**Comment by glvr182** [comment]
@dawidd6 Maybe you could check that at start up, to ensure that there is an editor available. Also if this is what went wrong, a little entry for trouble shooting might help?

( I would implement it but I'm still learning go)
