### ISSUE TITLE
Setting to disable "Not in a git repository" prompt

### ISSUE THREAD

**Issue by sportshead** [jesseduffield/lazygit#1091]
**Is your feature request related to a problem? Please describe.**
As a lazygit user, I want to be able to set a default for the `Not in a git repository. Create a new git repository? (y/n):` prompt, so that I don't need to press `n` every time.

**Describe the solution you'd like**
A `notInRepo` setting that can be the following values:
- `prompt` (default) Uses the current prompt
- `create` Creates a repo if one does not exist
- `skip` Does not create a repo

**Describe alternatives you've considered**
A CLI flag (e.g. `--skipRepoPrompt`, or `--alwaysCreateRepo`)

**Additional context**
When you open lazygit in a folder without a git repo, you git the `Not in a git repository. Create a new git repository? (y/n):` prompt as shown in this screenshot: 
![image](https://user-images.githubusercontent.com/32637656/99752629-a197e900-2b1f-11eb-83b1-d9811d0b2770.png)

**Comment by jesseduffield** [comment]
This makes sense. I'll chuck a good-first-issue label on this because it will be quite easy to implement. Our config code is in `pkg/config/user_config.go` and our code for showing this prompt and handling the responses is in `setupRepo` in `pkg/app/app.go`

**Comment by kalvinpearce** [comment]
Hey I love this tool and would love to contribute. I am new to go but I would love to give this a crack if thats all good?

**Comment by jesseduffield** [comment]
@kalvinpearce go right ahead! Lemme know if you need any pointers
