### ISSUE TITLE
Selective checkout of a file from a commit

### ISSUE THREAD

**Issue by felixkreuk** [jesseduffield/lazygit#1096]
**Topic**
Restoring a chunk of code from a file in a past commit

**Your thoughts**
Say I have a _piece of code_ in `a.py` (say, lines 100-105) I want to restore from a past commit (let's call it `commit_X`). Note, `a.py` wasn't necessarily modified in `commit_X` (so `a.py` doesn't appear in the commit files window).

Ideally, I would like to:
1. navigate to `commit_X`
2. see all files in the repository at this commit (not just files changed in `commit_X`)
3. select `a.py`
4. select a range of lines 100-105
5. and "paste" them into the current `a.py`.

Is there a way to do that?

Thanks a lot for this awesome project! I feel sorry that it took me so long to find it :)

**Comment by jesseduffield** [comment]
@felixkreuk this sounds like a good feature. I'm currently working on a way to render a tree of files (compared to the flat file structure you see currently) so this feature would be blocked until that work is done. But once that work is done I think this feature should be fairly straightforward to implement

**Comment by felixkreuk** [comment]
Awesome, thanks!
