### ISSUE TITLE
New SSH connection every minutes, why ?

### ISSUE THREAD

**Issue by trent30** [jesseduffield/lazygit#1101]
**Topic**
I'm using lazygit 0.23.6-1~ubuntu18.04.1 (installation from ppa) on Xubuntu 18.04 and lazygit make a new SSH connection on the server repo every minutes. On my server ~/.ssh/rc send me an email at new connection. Since I have several repo, if I run 10 lazygit, I have 10 emails per minutes, it's very annoying.

**Your thoughts**
Is it possible to configure this or just make a connection when it's really necessary (push/pull/...) ?

**Comment by fluffynuts** [comment]
you probably want to turn `autoFetch` off in your configuration; see: https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md

**Comment by trent30** [comment]
Nice !
