### ISSUE TITLE
minor feature request: ability not to exit the app when pressing Escape

### ISSUE THREAD

**Issue by fluffynuts** [jesseduffield/lazygit#1102]
**Is your feature request related to a problem? Please describe.**
I'm a lazy git. And I use VIM. A lot. So I tend to hit Escape a lot. And then I exit lazygit, and that makes me sad. I understand that a lot of people probably like this behavior because they aren't broken VIMmers like me. `q` exits quite nicely, and it makes sense (to me) to have `Escape` back out of menus. I'd really like a configuration option to _not_ quit on `Escape` -- only when I press `q`

**Describe the solution you'd like**
I'd like a new configuration point: `gui.shouldCloseOnTopLevelBackout`, or something with a better name that explains that the feature is to stop closing the app when reaching the top level of menus, which defaults to `true`, keeping the existing behavior, and, when configured to `false`, doesn't exit the app when pressing `Escape`

**Describe alternatives you've considered**
Switching from 20 years of using VIM to using Emacs. Only kidding -- I'm far too lazy for that. Which is why I use `lazygit`!

**Comment by jesseduffield** [comment]
it's your lucky day because there is already a config key for that! I think it's 'gui.quitOnTopLevelReturn'

**Comment by fluffynuts** [comment]
yes! I just found this by trawling the source, because I was going to make (yet another) ham-fisted attempt at a PR!

WIN!
