### ISSUE TITLE
Autocomplete branch name for checking out from pop up panel

### ISSUE THREAD

**Issue by Yuuki77** [jesseduffield/lazygit#1103]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I change the branch, the autocomplete for branch is not working.
What i want is that clicking on a tab should autocomplete the branch name

**Describe the solution you'd like**
.
**Describe alternatives you've considered**
.
**Additional context**
.

**Comment by jesseduffield** [comment]
I've got a PR up for this now: https://github.com/jesseduffield/lazygit/pull/1107

It's fully functional but needs some refactoring. Feel free to give it a try :)

**Comment by Yuuki77** [comment]
Thanks for the quick response! 😄 
I'll try to find the time next week and will give it a shot!!

**Comment by Yuuki77** [comment]
@jesseduffield test it locally!
this is exactly I was looking for 😄 
Thank you very much!!

**Comment by jesseduffield** [comment]
No worries :) glad you like it. I'm gonna do another read through the code before merging

**Comment by Yuuki77** [comment]
this was implemented in #1107
