### ISSUE TITLE
Branch list has old delete branches

### ISSUE THREAD

**Issue by jdguzman** [jesseduffield/lazygit#111]
My branch lists has branches that I have long since deleted both locally and upstream. Reading the code it seems that it's giving me the full list from the reflog. Is this expected behavior? I would expect to only see the output from `git branch`.

**Comment by jesseduffield** [comment]
I've just merged a PR https://github.com/jesseduffield/lazygit/pull/110 to master which resolves this issue

**Comment by jdguzman** [comment]
Sorry this took a bit, I'm not a go user so I had to figure out where stuff was. I've pulled and built the master branch and now I only see `master` no other branches.

**Comment by jdguzman** [comment]
@jesseduffield correction it is working, I was in the wrong repo, doh!

**Comment by jesseduffield** [comment]
haha you had me scared for a second!

**Comment by jdguzman** [comment]
@jesseduffield as a side note on macOS go is putting things in `~/Projects/go/bin` and not `~/go/bin` not sure if that's something unique to me or if it's a macOS thing. I'm a go noob so anything is possible.

**Comment by jesseduffield** [comment]
~go/bin is the default value of $GOPATH but not necessarily. Have a look at what `echo $GOPATH` returns

**Comment by jdguzman** [comment]
yeah it shows `~/Projects/go` I messed around a bit with go a while back, maybe I set that and just don't remember.

**Comment by jdguzman** [comment]
Closing this.

**Comment by hubertba** [comment]
same problem here ... I try to add delete branch functionality ... I works but it is not reflected in the branches panel ... so .. when this is fixed, I will continue and provide the delete branch functionality as a pull-request

**Comment by jdguzman** [comment]
@hubertba there is a fix in master for this already, I've tested it locally and everything seems to be working now. I don't think there has been a build added to releases with this change yet so you would have to pull and build to test it yourself.
