### ISSUE TITLE
Launchpad PPA once again behind current release

### ISSUE THREAD

**Issue by jbrains** [jesseduffield/lazygit#1123]
**Describe the bug**
Recurrence of https://github.com/jesseduffield/lazygit/issues/897. The Launchpad PPA has lazygit v0.23.6.

**To Reproduce**
1. `sudo add-apt-repository ppa:lazygit-team/release`
2. `sudo apt-get update`
3. `sudo apt-get upgrade`

**Expected behavior**
Install (as of today) v0.23.7.

**Desktop (please complete the following information):**
 - Pop! OS 20.10

**Additional context**
Since publishing to the PPA is likely still not yet automated, I presume that someone merely needs to publish the latest release. I genuinely don't know whether opening an issue like this is helpful as a reminder or annoying. Let me know.

**Comment by jesseduffield** [comment]
I know I should know how this all works by now but I still don't haha. @dawidd6 are you able to once again remind me how this all works?

**Comment by dawidd6** [comment]
Releasing to PPA is automated now. This issue can be closed.

Process is like this:
git tag -> CD workflow trigger -> clone

**Comment by jesseduffield** [comment]
@dawidd6 nice :) Is this a process I can follow on my own computer? I'm not familiar with the gbp command

**Comment by dawidd6** [comment]
Yes, just look at how the steps are defined in the workflow job and it should work locally too.

**Comment by jesseduffield** [comment]
sweet, thanks
