### ISSUE TITLE
Too many cache files and squared out fonts in the cmd.

### ISSUE THREAD

**Issue by hypo-thesis** [jesseduffield/lazygit#1126]
**Describe the bug**
The fonts are all squared out and I see a lot of cache files in the directory.

**Expected behavior**

**Screenshots**
![dgdfgdfg](https://user-images.githubusercontent.com/28728305/102709789-940c8500-42be-11eb-8465-9502e140d6ee.jpg)

**Desktop (please complete the following information):**
 - OS: windows 10
 - Lazygit Version v0.23.7

**Comment by jesseduffield** [comment]
I recommend invoking lazygit from powershell if you're on a PC. the raw cmd prompt seems to have issues. Could you give that a try?

**Comment by jesseduffield** [comment]
Closing due to staleness
