### ISSUE TITLE
Missing webpage on documentation.

### ISSUE THREAD

**Issue by chedieck** [jesseduffield/lazygit#1127]
On the Custom [CommandKeybinds](https://github.com/jesseduffield/lazygit/blob/master/docs/Custom_Command_Keybindings.md) page, there is a broken link on the "Placeholder values" section: it points to `https://github.com/jesseduffield/lazygit/blob/master/pkg/commands/file.go`, which does not exists anymore

**Comment by jesseduffield** [comment]
Fixed in https://github.com/jesseduffield/lazygit/commit/106fce26b504d875384d5cae08e9e36d66b29337 :)
