### ISSUE TITLE
selectable staged/unstaged files list [check attached gif]

### ISSUE THREAD

**Issue by mohitmun** [jesseduffield/lazygit#113]
I don't know what should I call it, but gitk makes it easier to jump around files in diff area as shown in gif. something like this(or similar) on roadmap for lazygit? if no one working on this, I can possibly hack this feature this weekend. 

![output](https://user-images.githubusercontent.com/1572770/43959417-66f467ee-9ccc-11e8-8294-488c328baf1d.gif)

Thanks a lot for awesome project.

**Comment by jesseduffield** [comment]
the more PRs the merrier! However I'm not quite sure what that gif is demonstrating. It looks to me like you're just flicking through files. What does this gif show that you can't currently do in lazygit?

**Comment by mohitmun** [comment]
when browsing history, gitk has commments section(bottom left) where you can quickly jump through diff by clicking on filename. consider it similar to files panel in lazygit

**Comment by jesseduffield** [comment]
ah I see. That is a good feature. Part of me thinks it would be cool to utilise the existing file panel to show those files but a stronger part of me thinks maybe we could do a thing where if you hit a keybinding on a selected commit, the commits panel is swapped out for a file panel so you can flick through the files to see the diffs, and then it swaps back upon hitting esc.

**Comment by jesseduffield** [comment]
This has been implemented :) closing
