### ISSUE TITLE
error while reading terminfo data: termbox: unsupported terminal

### ISSUE THREAD

**Issue by mckellygit** [jesseduffield/lazygit#1134]
Hi,

2021/01/02 16:59:01 An error occurred! Please create an issue at https://github.com/jesseduffield/lazygit/issues
*errors.errorString termbox: error while reading terminfo data: termbox: unsupported terminal
/home/<username>/go/src/github.com/jesseduffield/lazygit/main.go:133 (0xa03297)
        main: newErr := errors.Wrap(err, 0)
/usr/local/go/src/runtime/proc.go:204 (0x439f09)
        main: fn()
/usr/local/go/src/runtime/asm_amd64.s:1374 (0x46cc81)
        goexit: BYTE    $0x90   // NOP

just run lazygit in any git dir

Ubuntu 18.04
kitty 0.19.3
tmux 3.2
lazygit v0.24.1 latest version + commit d7c92438

go version go1.15 linux/amd64

my TERM inside tmux is tmux-256color.
Outside of tmux TERM is xterm-kitty.
lazygit works fine inside tmux with other terminals.

This may be a kitty issue but thought I should report it in case it helps any.

thx,
-m

**Comment by jesseduffield** [comment]
I think this is just a matter of whitelisting the terminal from within termbox. This might actually be easier to solve by just migrating from termbox to tcell which is a work in progress at the moment

**Comment by mckellygit** [comment]
ok, thanks.  Closing for now.
