### ISSUE TITLE
Is there a way to unmap a key (or map it to none etc) ?

### ISSUE THREAD

**Issue by mckellygit** [jesseduffield/lazygit#1141]
Thank you for lazygit, it is awesome.
I really just have a question if this is possible and if so how to do it -
Suppose I wanted to not have \<esc\> quit - do I have to map <esc> to something else I seldom use ?
Or can I 'unmap' it, or map it to a no-op / none method etc. ?

thx,
-m

**Comment by jesseduffield** [comment]
In this case, you would indeed need to map to a key you seldom use. We probably should allow for 'unmapping' keys.
