### ISSUE TITLE
--ignore-space-change support in diff panel

### ISSUE THREAD

**Issue by pirafrank** [jesseduffield/lazygit#1143]
For files with modifications, in the right pane we can currently stage edits line by line.
In this view, all the differences are shown (as per `git diff`).

Currently there is no option to view differences filtering space changes out, so that I can choose lines to stage among actual code changes.

The app should support a setting (specified in the config.yml) or some kind of toggle, to view differences as per `git diff --ignore-space-change`. Thank you.

**Comment by Ryooooooga** [comment]
@pirafrank `<c-w>` keybinding was added in a9f04d3 .

**Comment by jesseduffield** [comment]
closing as this is now implemented
