### ISSUE TITLE
Execute commands when the help menu is shown

### ISSUE THREAD

**Issue by lkuoch** [jesseduffield/lazygit#1144]
I'm not sure if this is enabled by a setting in the config but I would like to be able to execute commands when the help screen is shown.

Currently the workflow is like follows:
   - Open help screen to check for command I want to execute
   - Close help screen
   - Press key that I had to remember from help screen

Somewhat similar to magit where there is a option to see all commands available I would like to be able to
  - Open help screen to check for command I want to execute
  - While on the help screen, enter a command (eg: Pull) and lazy git will run that command

I hope that made sense! Please let me know if you would like more details

**Comment by jesseduffield** [comment]
Should be fixed in https://github.com/jesseduffield/lazygit/pull/1491

**Comment by jesseduffield** [comment]
Pre-emptively closing but lemme know if I need to re-open
