### ISSUE TITLE
commit amend (reword) does not work properly when commit message is longer than box width and wraps

### ISSUE THREAD

**Issue by mckellygit** [jesseduffield/lazygit#1145]
Hi,

Thank you for lazygit, it is awesome.
I am using the latest version built from source.
If I want to re-word a commit msg, and the msg happens to be longer than the box width (so it appears as multi-line) then the cursor is not in the correct place for editing and moving the cursor around does not seem correct.

thx,
-m

**Comment by mark2185** [comment]
Could you test this out with `v0.35` to see if it still happens?

**Comment by mckellygit** [comment]
I tested the latest -
commit=3ec0c589d054ef64d7782a074b457445afe71a3e, build date=2022-08-08T12:54:03Z, build source=unknown, version=3ec0c589, os=linux, arch=amd64
and it works correctly on a long commit message.
Thank you!
Do you want me to close this ?
-m

**Comment by mark2185** [comment]
Great! Feel free to reopen it if it pops up again.

> Do you want me to close this ?

That's okay, it's already closed! :)
