### ISSUE TITLE
config.yml generated in cwd, not read from default location?

### ISSUE THREAD

**Issue by levouh** [jesseduffield/lazygit#1150]
## Describe the bug

The default `config.yml` file located in `~/.config/jesseduffield/lazygit` is not read by default, and when on the _Status_ menu, pressing the default `e` key binding opens up a `config.yml` in the current working directory.

## To Reproduce
1. Fresh install of `lazygit` with a binary from the `releases` page, specifically:
```
$ lazygit --version
commit=d7c9243880b973c137378569dec7d408b695f36f, build date=2020-12-24T09:36:21Z, build source=binaryRelease, version=0.24.2, os=linux, arch=amd64
```
2. Change directory into a `git` repository
3. Navigate to the _Status_ pane
4. Press `e` to edit the configuration file, note that it is empty
5. Exit `lazygit`
6. `ls` and observe a `state.yml` and a `config.yml` in the current working directory, which is _not_ the configuration directory.
7. Re-open `lazygit`, edit the config file again with `e`, but actually make changes this time.
8. Observe that changes to `$(pwd)/config.yml` change `lazygit`, but the default configuration file location does not.

One thing to note here, I use `stow`, so the actual directory under `~/.config`, specifically `~/.config/jesseduffield` is a symbolic link to my `~/dots/config/.config/jesseduffield` directory. Note though that I've tried this _without_ using the symbolic links, and the same thing happens.

Some more information:
```
$ cat /etc/os-release
NAME=Fedora
VERSION="32 (Thirty Two)"
ID=fedora
VERSION_ID=32
VERSION_CODENAME=""
...
$ ls -lA ~/.config/jesseduffield/lazygit/
total 4
-rw-r--r--. 1 amasquelier amasquelier 137 Jan 27 08:58 config.yml
$ cat ~/.config/jesseduffield/lazygit/config.yml 
gui:
  theme:
    lightTheme: false
    selectedLineBgColor:
      - red
      - bold
    selectedRangeBgColor:
      - red
      - bold
```

## Expected behavior

The configuration file is read from the right location.

## Desktop

 - OS: _Linux_, see just above for dist. information
 - Lazygit Version: `commit=d7c9243880b973c137378569dec7d408b695f36f, build date=2020-12-24T09:36:21Z`

## Additional context

Never used `lazygit` before; this is my first time installing it, and my terminal theme is absolutely illegible by default. I'm trying to change some of the colors, but can't, at least not by editing what _should_ be the default configuration file.

Assuming we respect `XDG_*` variables, I don't have anything setup special in that regard either:
```
$  printenv | grep -i XDG
XDG_RUNTIME_DIR=/run/user/1000
XDG_DATA_DIRS=/home/amasquelier/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share
```

## Update

So it seems that no matter where I am, the configuration file gets set to `~/dots/config.yml`, I can remove that file, remove my entire `~/.config/jesseduffield` directory, change into a _completely_ different `git` repository, and no matter what, it always ends up being `~/dots/config.yml`. I feel like this _has_ to with my linking somehow, but like I said above, I removed every single hint of a symbolic link for anything that `lazygit` is concerned with, but still nothing.

## Update 2

I've "unstowed" everything related to my own configuration, and it seems that only then `lazygit` is able to find the right configuration file/location. Not entirely sure what is going on here, but I'll close this issue once I find out. Doesn't _appear_ to be a `lazygit` problem, but we'll see.

**Comment by levouh** [comment]
So can you explain the reasoning behind [this](https://github.com/jesseduffield/lazygit/blob/922c0887f11da78242482811f011c84e4e82ffc9/pkg/config/app_config.go#L93)?

Are you aware of [this](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html)?

**Comment by jesseduffield** [comment]
@levouh that code is there for legacy purposes: I started off storing the directory under jesseduffield/lazygit but turns out the vendor name (jesseduffield) isn't actually required, so anybody installing lazygit now will have the config in a path with `jesseduffield` removed.

That method also accepts an env var to override the config directory if the user wants that.
