### ISSUE TITLE
Respect git configuration over defaults in lazygit

### ISSUE THREAD

**Issue by smh** [jesseduffield/lazygit#1151]
**Respect git configuration over defaults in lazygit**
I was caught by surprise today. Did a pull through lazygit, and ended up with a merge commit even though my git config says to do a rebase.

I have no lazygit config file, but the following in my `$HOME/.config/git/config:
```
[pull]
  rebase = true
```
Would it be possible/desirable to let git configuration (either global or repository specific) take precedence over the lazygit defaults? Only explicit user configuration in lazygit would take precedence.

**Comment by eruizc-dev** [comment]
It happened to me today too. I'd like for it to follow what's in my  `.gitconfig`

**Comment by band-a-prend** [comment]
The same issue for several new releases.
As I could remember some early lazygit respects this option.
Now on pull with creeated commits it offers to merge fetched commits from origin instead of rebase.
