### ISSUE TITLE
Commit messages are not escaped properly.

### ISSUE THREAD

**Issue by Ryooooooga** [jesseduffield/lazygit#1168]
**Describe the bug**

Commit messages containing special characters (`$` / <code>`</code>) are not escaped properly.

**To Reproduce**

1. Setup GPG, and enable GPG signing (`git config commit.gpgSign true`)
2. Stage some changes
3. Press `c` to open commit input-box
4. Type messages like `$(echo Hello)`, and press enter
5. The command `git commit -m "$(echo Hello)"` is executed, and committed with message `Hello`

**Expected behavior**
The commit message should be `$(echo Hello)` (`git commit -m "\$(echo Hello)"` or `git commit -m '$(echo Hello)'`)

**Screenshots**
<img width="553" alt="commit-message" src="https://user-images.githubusercontent.com/10097437/108475662-58993180-72d4-11eb-9931-501dd2e847c9.png">
<img width="370" alt="commands" src="https://user-images.githubusercontent.com/10097437/108475685-618a0300-72d4-11eb-85b6-1a50b5a03fcb.png">
<img width="262" alt="logs" src="https://user-images.githubusercontent.com/10097437/108475696-651d8a00-72d4-11eb-8ea2-4daf6908bc22.png">

**Desktop (please complete the following information):**
 - OS: macOS Big Sur (11.2.1)
 - Lazygit Version: HEAD
 - The last commit id if you built project from sources: 9df133ed8c3b1fc813dbee09a34455ef6be51680

---

https://github.com/jesseduffield/lazygit/blob/9df133ed8c3b1fc813dbee09a34455ef6be51680/pkg/commands/commits.go#L24-L37

`strconv.Quote()` and `c.OSCommand.Quote()` do not escape `$` / <code>`</code>, so I think you should use https://github.com/alessio/shellescape package or so (but I'm not sure it works on Windows as well).

**Comment by fsmiamoto** [comment]
I think this is a more complete version of #1152.
@jesseduffield I'd be willing to tackle this one, maybe we can close #1152 and keep this one since it's better described.

**Comment by jesseduffield** [comment]
fixed by @Ryooooooga :)
@fsmiamoto do you mean that we can close https://github.com/jesseduffield/lazygit/issues/1152 if this issue is fixed?

**Comment by fsmiamoto** [comment]
That's right @jesseduffield, just verified that it solves #1152 :)
