### ISSUE TITLE
Pushing the limits of custom commands

### ISSUE THREAD

**Issue by ristillu** [jesseduffield/lazygit#1184]
**Topic**
As the title said, I wanted to implement a custom command but I think I'm overstepping the mark - can you smack me back down to earth

**Your thoughts**
- I don't know go
- I wanted to choose a way to delete remote branches associated with a local branch via a custom command
- I can maybe do this through the 'Remotes' pane but we have literally 10,000 remotes because people forget to clean up and scrolling through them is tedious at best

So I came up with the basic scenario of:
```
  - key: '<c-d>'
    command: 'git push origin :{{.SelectedLocalBranch.Name}}'
    context: 'localBranches'
    description: 'delete remote branch of this local branch'
```
which is fine but a bit dangerous. I just want to delete branches that I am responsible for and have a list of protected branches. And also a dummies prompt which may annoy me in time but may also save me from accidentally destroying something.

Promise not to laugh, but here's the pseudocode I wanted to kinda work:
```
  - key: '<c-d>'
    command: '
      {{$response := index .PromptResponses 0}}
      {{$lowercase_delete := eq $response "y"}}
      {{$uppercase_delete := eq $response "Y"}}
      {{$delete := or $lowercase_delete $uppercase_delete}}
      {{if $delete}}
        {{$protected_branches := []string{"protected_branch_1", "protected_branch_2", "protected_branch_3"}}}
        {{$dont_delete := true}}
        {{
          for i := 0; i < $protected_branches.Len(); i++ {
            if eq $protected_branches.Index(i) .SelectedLocalBranch.Name {
              $dont_delete := true
            }
          }
        }}
        {{if not $dont_delete}}
          git push origin :{{.SelectedLocalBranch.Name}}
        {{end}}
      {{end}}'
    context: 'localBranches'
    description: 'delete remote branch of this local branch'
    prompts:
      - type: 'input'
        title: 'Are you sure?'
        initialValue: 'n'
```
I worked out that lg's templating doesn't allow me to chain things so I have to be careful with my usage of lots of temporary variables rather than being able to chain things together. It's the middle loop part that I guess I need guidance on - I presume it's impossible to use full fledged go like this?

If you can suggest another way to achieve functionality like this I'm all ears.

**Comment by mjarkk** [comment]
interesting use case but i sadly don't think a lot of what you are doing is possible as you cannot just run Go code in your template.  
It has been some time since i used go templates but as far as i know the go templates != go code they are 2 different programming languages if i may call them that.

### What definitely doesn't work:
I don't think it's possible to create an array in a template.
```go
$protected_branches := []string{"protected_branch_1", "protected_branch_2", "protected_branch_3"}
```

This is mostly just pure go code so this will not work.  
```go
for i := 0; i < $protected_branches.Len(); i++ {
    if eq $protected_branches.Index(i) .SelectedLocalBranch.Name { // This line should kinda work though
        $dont_delete := true // := is assigning to a new variable, = is re-assigning a variable so you have to use = here
    }
}
```

You could try something like this:
```
{{ range $i, $protected_branch := $protected_branches.Len }}
  {{ if eq $protected_branch .SelectedLocalBranch.Name}}
    {{ $dont_delete = true }}
  {{ end }}
{{ end }}
```

But as this uses the above you might have to brute force your code a bit:
```
{{ if eq "protected_branch_1" .SelectedLocalBranch.Name}}
    {{ $dont_delete = true }}
{{ else if eq "protected_branch_2" .SelectedLocalBranch.Name}}
    {{ $dont_delete = true }}
{{ else if eq "protected_branch_3" .SelectedLocalBranch.Name}}
    {{ $dont_delete = true }}
{{ end }}
```

A few site notes here:
- As far as i know you cannot use go type functions in a template so no `.Len()` or `.Index()`
- The code i typed is not checked so it might not be completely equal to https://golang.org/pkg/text/template/

**Comment by jesseduffield** [comment]
@ristillu another option here, if using go templates proves too difficult, is to create a bash script which does what you want, and then invoke that from the custom command, passing in the arguments that it needs (i.e. `~/my_push_script.sh {{.SelectedLocalBranch.Name}}`)

**Comment by ristillu** [comment]
Hey, thank you both very much. Derp, for some reason I had fixated on thinking I could only use git commands as custom commands. Before Jesse's answer I was going to try Mark's excellent reply but I can grok bash much easier than go (or a plethora of other commands/languages, once I remove my blinkers) so I came up with something like:
```
  - key: '<c-d>'
    command: '/the/path/to/git_remote_branch_deleter.sh {{.SelectedLocalBranch.Name}}'
    context: 'localBranches'
    description: 'delete remote branch of this local branch'
    subprocess: true
    prompts:
      - type: 'input'
        title: 'Delete remote branch'
        initialValue: 'Are you sure you want to delete the remote branch "{{.SelectedLocalBranch.Name}}"?'
```
and:
```
#!/bin/bash

if [[ $1 =~ $ACCEPTABLE_BRANCH_REGEX_GOES_HERE ]]; then
    echo "Deleting remote branch with 'git push origin :$1'"
    git push origin :$1
else
    echo "Not deleting remote branch $1 because it doesn't meet acceptable auto-deletion name criteria"
fi
```
Works like a charm! Thanks both of you!

**Comment by jesseduffield** [comment]
No worries, happy to help!
