### ISSUE TITLE
read git.pull.mode from git config

### ISSUE THREAD

**Issue by SuperSandro2000** [jesseduffield/lazygit#1188]
**Is your feature request related to a problem? Please describe.**
Lazygit does not read my git config for ``git.pull.mode``.

**Describe the solution you'd like**
It should read the value from my gitconfig if unset. This can be done with ``git config --get pull.rebase``.

**Describe alternatives you've considered**
Setting it manually.

**Additional context**

**Comment by eruizc-dev** [comment]
This seems related to #1151
