### ISSUE TITLE
GIT_EDITOR is not used, always open in vi.

### ISSUE THREAD

**Issue by lkhphuc** [jesseduffield/lazygit#1189]
**Describe the bug**
Not respecting GIT_EDITOR.

**To Reproduce**
1. Set $GIT_EDITOR
1. Open lazygit
2. Press `e` to edit
3. File open in `vi`, not $GIT_EDITOR

**Expected behavior**
Open using $GIT_EDITOR

**Screenshots**
![Screenshot 2021-03-15 at 13 57 30](https://user-images.githubusercontent.com/12573521/111164914-63bf4480-8596-11eb-8985-ee4fd77d6f4d.png)
- The first command is using custom command to show $GIT_EDITOR value.
- The second command is when press `e`. 

**Desktop (please complete the following information):**
 - OS: MacOS Big Sur
- `lazygit -v`: `commit=058bcddc53cff6360583cd575fe64da76b53f94b, build date=2021-03-14T02:25:47Z, build source=binaryRelease, version=0.26.1, os=darwin, arch=amd64`

**Comment by fsmiamoto** [comment]
For the example you gave, you should set the variable `$EDITOR`.
That one should be respected in this case.

**Comment by jesseduffield** [comment]
GIT_EDITOR is supported in https://github.com/jesseduffield/lazygit/pull/1214 :)
