### ISSUE TITLE
Q: Commit message GUI

### ISSUE THREAD

**Issue by MiroslavMikus** [jesseduffield/lazygit#1190]
First things first, huge thanks to the author and all contributors. :pray:

**Topic**
Commit message GUI.

![image](https://user-images.githubusercontent.com/29312172/111283175-206ce080-863f-11eb-861f-4e57b769a023.png)

**Your thoughts**
- Is there a way to enter a multiline commit message?
- It would be nice to have some more editing features like 
  - **Home:** navigate to the start
  - **End:** navigate to the end
  -  **Ctrl:** with the combination of **Left** or **Right** arrow: Skip whole word

Are these features possible with the console GUI library?

Thanks in Advice

**Comment by danielfalbo** [comment]
- Press `tab` to go to the next line
- Press `ctrl+a` to jump at the beginning of the current line the message
- Press `ctrl+e` to jump at the end of the current line of the message

**Comment by MiroslavMikus** [comment]
Works like a charm :tada:
Many thanks, @danielfalbo!

Did I miss it in the docu?

**Comment by danielfalbo** [comment]
`ctrl+a` and `ctrl+e` work pretty much everywhere in the shell 👍 but yeah I didn't find `tab` in the documentation either, I remember asking it under an issue myself in the past

**Comment by thislooksfun** [comment]
@jesseduffield Just updated to 0.27.1 and I can't enter newlines because `alt-enter` doesn't work on macOS since we have no alt key (yes I tried all the modifier keys, they all just committed).

My suggestions, in order would be:
1. `shift+enter`
2. `meta+enter` (would need an alternate on Windows/Linux)
3. `ctrl+enter`

**Comment by jesseduffield** [comment]
@thislooksfun it says alt but on mac it's actually your cmd key (I'm also on mac). Using iterm you can enable it by following these instructions:

https://github.com/Canop/broot/issues/86#issuecomment-801877468

I'm not actually sure if the other options you listed work, or if it's possible to make them work, with the rendering library we're now using (tcell). In fact it may not be possible at all, but I haven't looked into it very far

**Comment by thislooksfun** [comment]
I'm using Terminal.app, but I was able to get it working by checking "Use Option as Meta key".

**Comment by jesseduffield** [comment]
Using home/end is now supported with https://github.com/jesseduffield/lazygit/pull/1523

Jumping word by word is yet to come

**Comment by jesseduffield** [comment]
Given that https://github.com/jesseduffield/lazygit/issues/795 is more specific to the issue of jumping word by word, I'll close this ticket in favour of that
