### ISSUE TITLE
Hard crash while typing commit message

### ISSUE THREAD

**Issue by peppy** [jesseduffield/lazygit#1205]
Was typing a commit message, lazygit exploded.

```
Press enter to return to lazygit
panic: runtime error: index out of range [9] with length 9

goroutine 1 [running]:
github.com/jesseduffield/gocui.(*View).writeRune(0xc00015d1e0, 0x9, 0x0, 0xc000000000, 0xc000177778, 0x1047d0c)
        /home/runner/work/lazygit/lazygit/vendor/github.com/jesseduffield/gocui/edit.go:359 +0x6d8
github.com/jesseduffield/gocui.(*View).EditWrite(0xc00015d1e0, 0x0)
        /home/runner/work/lazygit/lazygit/vendor/github.com/jesseduffield/gocui/edit.go:68 +0x6b
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).commitMessageEditor(0xc0001cc000, 0xc00015d1e0, 0x20000f, 0x0)
        /home/runner/work/lazygit/lazygit/pkg/gui/editors.go:41 +0x16f
github.com/jesseduffield/gocui.EditorFunc.Edit(0xc0009d9790, 0xc00015d1e0, 0x79000f, 0x16df500)
        /home/runner/work/lazygit/lazygit/vendor/github.com/jesseduffield/gocui/edit.go:27 +0x4b
github.com/jesseduffield/gocui.(*Gui).onKey(0xc0000f86c0, 0xc000799680, 0x16df520, 0xc0006fe301)
        /home/runner/work/lazygit/lazygit/vendor/github.com/jesseduffield/gocui/gui.go:871 +0x344
github.com/jesseduffield/gocui.(*Gui).handleEvent(0xc0000f86c0, 0xc000799680, 0x0, 0x0)
        /home/runner/work/lazygit/lazygit/vendor/github.com/jesseduffield/gocui/gui.go:551 +0x46
github.com/jesseduffield/gocui.(*Gui).MainLoop(0xc0000f86c0, 0xc000000004, 0xc0001ffa90)
        /home/runner/work/lazygit/lazygit/vendor/github.com/jesseduffield/gocui/gui.go:499 +0x269
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).Run(0xc0001cc000, 0x0, 0x0)
        /home/runner/work/lazygit/lazygit/pkg/gui/gui.go:507 +0x525
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).RunWithSubprocesses(0xc0001cc000, 0x0, 0x100000001708456)
        /home/runner/work/lazygit/lazygit/pkg/gui/gui.go:520 +0x108
github.com/jesseduffield/lazygit/pkg/app.(*App).Run(0xc000263ce0, 0xc0000f26c0, 0x0)
        /home/runner/work/lazygit/lazygit/pkg/app/app.go:240 +0x6b
main.main()
        /home/runner/work/lazygit/lazygit/main.go:126 +0xb3b
```

**Comment by jesseduffield** [comment]
@peppy was there something peculiar about what you were typing that might have triggered this? I'm not able to replicate locally by spamming keys but it looks like there's two possible causes:
1) the width of the character you were attempting to write was zero. I've fixed this by adding an early return in that case
2) there was a race condition. I've fixed this up with mutexes.

Fixes in https://github.com/jesseduffield/lazygit/pull/1206

**Comment by peppy** [comment]
I'm honestly not sure. I managed to get it again today, but as far as I can tell I was just typing away when it happened. Hard to test if you've got it fixed, but I think it's safe to close this until it comes up again. I'll switch to a local build and see if I can reproduce in the mean time.

Thanks!

**Comment by jesseduffield** [comment]
no worries @peppy ! Also as a lazygit power-user you might be interested in this PR: https://github.com/jesseduffield/lazygit/pull/1197
It's basically ready to merge but I haven't really vetted the approach through anybody. If you have the time, I'd love to know your thoughts on it!

**Comment by peppy** [comment]
Pretty cool, will give it a try!

Usually I'm not making enough concurrent changes to make a tree view worthwhile. I think my main issue with the file view is finding conflicted files during a merge failure (where the conflicting file may be 200 files down the list).

**Comment by jesseduffield** [comment]
@peppy conveniently, that PR also bubbles merge conflict files to to the top of the list (when not in file tree view) so that should make life a little easier for you :)

**Comment by peppy** [comment]
Amazing!
