### ISSUE TITLE
Using `$()` in custom command

### ISSUE THREAD

**Issue by kristijanhusak** [jesseduffield/lazygit#1209]
**Describe the bug**
I'm not sure if it's a bug or I just don't know how to use it.
I'm trying to create a custom command that will open my Jira ticket from branch name. I try to do that by parsing the ticket name from branch name via `cut` (`echo "hotfix/AB-123" | cut -d "/" -f2`) and then piping it to the other commands.
Since it didn't work I tried just simple cases but for some reason those didn't work also. 

**To Reproduce**
1. Add this custom command to config:
```yml
  - key: '<c-j>'
    context: 'localBranches'
    descrition: 'Open Jira ticket'
    command: 'xdg-open $(echo "https://google.com")'
```
2. Open lazygit
3. Go to branches panel
4. Press `<C-j>`

**Expected behavior**
I expect to get google opened in browser, but instead I get this error:
```
xdg-open: unexpected argument 'https://google.com'
Try 'xdg-open --help' for more information.
```

I tried the same command directly in sh/bash/zsh and it works everywhere just fine

**Desktop (please complete the following information):**
 - OS: Linux
 - Lazygit Version: Installed via go get, on commit d7c9243880b973c137378569dec7d408b695f36f

**Additional context**
If there is a way to do this somehow through go template syntax, please let me know. I'm trying to do something like this at this moment:

```
echo "hotfix/AB-123" | cut -d "/" -f2 | xargs -I{} xdg-open "https://my.jira.com/{}" 
```

**Comment by jesseduffield** [comment]
Hmm, I'd try wrapping it in `bash -c "<your command>"`

**Comment by jesseduffield** [comment]
nice! I'm happy to leave this ticket open for the sake of making that the default behaviour

**Comment by kristijanhusak** [comment]
Great! I think the quickfix is to document this into the custom command docs as an example, until it gets fixed.
