### ISSUE TITLE
Default commit command to "commit -v"?

### ISSUE THREAD

**Issue by jbrains** [jesseduffield/lazygit#1210]
I have grown very fond of using the `-v` switch by default for commits, courtesy of the **zsh** plugin for git. I would love to be able to do this with lazygit also. Is this something I can configure in git that lazygit would merely use or would this require a new feature in lazygit?

**Comment by jesseduffield** [comment]
@jbrains if you're happy doing it through a submodule you can add a custom command with the 'C' keybinding in the files context. See https://github.com/jesseduffield/lazygit/wiki/Custom-Commands-Compendium for examples.

But doing it from within lazygit would be a little trickier

**Comment by jbrains** [comment]
That was perfect. Thank you.
