### ISSUE TITLE
Maintain cursor position in menu after exiting submodule

### ISSUE THREAD

**Issue by takelley1** [jesseduffield/lazygit#1212]
**Is your feature request related to a problem? Please describe.**
If you enter and exit a submodule from the Files menu, the file selection cursor jumps back to the top of the file list, forcing you to scroll back down to where the cursor was previously. This can be frustrating, especially if the repo has a large number of submodules, as lots of unnecessary scrolling will be necessary.

The cursor position is maintained when using the enter/exit keybindings on regular files in the Files menu (i. e. to enter and exit staging specific hunks). I think this behavior should carry over to submodules as well, as it would make things much more consistent.

**Describe the solution you'd like**
Remember the cursor position in the Files menu of the parent repo when entering a submodule and return to the same location after exiting the submodule.

Also, thank you for writing this tool -- it's by far the best git UI I've used.

**Comment by jesseduffield** [comment]
I've got this implemented in https://github.com/jesseduffield/lazygit/pull/1217 but that PR has become a bit of a monster so it will take me some time to get it merged :)

And thanks for the kind words!

**Comment by jesseduffield** [comment]
this is now implemented in v0.27
