### ISSUE TITLE
Crash if ESC is pressed in commit window

### ISSUE THREAD

**Issue by takelley1** [jesseduffield/lazygit#1221]
**Describe the bug**
Lazygit crashes if ESC is pressed at any point while the commit pop-up window is open.

**To Reproduce**
1. Stage a file
2. Open the commit window
3. Press ESC

**Expected behavior**
Commit window should close if ESC is pressed.

 - OS:  CentOS 7 (Also tested on Arch)
 - Lazygit Version: 26.1

**Additional Information**
If the commit window is empty when ESC is pressed, the panic will read:
```
panic: runtime error: index out of range [0] with length 0
```

If 4 letters have been typed in the commit window when ESC is pressed (for example), the message will be:
```
panic: runtime error: index out of range [4] with length 4
```
The rest of the stack trace appears to be the same in both cases:
```
goroutine 1 [running]:
github.com/jesseduffield/gocui.(*View).writeRune(0xc00039eb00, 0x0, 0x0, 0xc000000000, 0x10000000e, 0x4483ac)
        /home/runner/work/lazygit/lazygit/vendor/github.com/jesseduffield/gocui/edit.go:359 +0x6d8
github.com/jesseduffield/gocui.(*View).EditWrite(0xc00039eb00, 0xc000000000)
        /home/runner/work/lazygit/lazygit/vendor/github.com/jesseduffield/gocui/edit.go:68 +0x6b
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).commitMessageEditor(0xc00027cdc0, 0xc00039eb00, 0x20001b, 0x203000)
        /home/runner/work/lazygit/lazygit/pkg/gui/editors.go:41 +0x16f
github.com/jesseduffield/gocui.EditorFunc.Edit(0xc00033b780, 0xc00039eb00, 0x50001b, 0xadd000)
        /home/runner/work/lazygit/lazygit/vendor/github.com/jesseduffield/gocui/edit.go:27 +0x4b
github.com/jesseduffield/gocui.(*Gui).onKey(0xc0000fbe60, 0xc000502000, 0xadd000, 0xc000340201)
        /home/runner/work/lazygit/lazygit/vendor/github.com/jesseduffield/gocui/gui.go:871 +0x344
github.com/jesseduffield/gocui.(*Gui).handleEvent(0xc0000fbe60, 0xc000502000, 0x0, 0x0)
        /home/runner/work/lazygit/lazygit/vendor/github.com/jesseduffield/gocui/gui.go:551 +0x46
github.com/jesseduffield/gocui.(*Gui).MainLoop(0xc0000fbe60, 0xc000000004, 0xc000299a90)
        /home/runner/work/lazygit/lazygit/vendor/github.com/jesseduffield/gocui/gui.go:499 +0x269
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).Run(0xc00027cdc0, 0x0, 0x0)
        /home/runner/work/lazygit/lazygit/pkg/gui/gui.go:507 +0x525
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).RunWithSubprocesses(0xc00027cdc0, 0x0, 0xb06097)
        /home/runner/work/lazygit/lazygit/pkg/gui/gui.go:520 +0x108
github.com/jesseduffield/lazygit/pkg/app.(*App).Run(0xc00025b6c0, 0xc0000f4750, 0x0)
        /home/runner/work/lazygit/lazygit/pkg/app/app.go:240 +0x6b
main.main()
        /home/runner/work/lazygit/lazygit/main.go:126 +0xb3b
```

**Comment by jesseduffield** [comment]
@takelley1 are you able to test if the issue exists on https://github.com/jesseduffield/lazygit/pull/1217? I'm soon to merge that branch and it contains quite a few fixes

**Comment by takelley1** [comment]
I realized I originally had `q` bound to `quit` instead of `<esc>`. With the default bindings (i.e. `quit` mapped to `<esc>`) on 26.1, Lazygit simply exits if I press `<esc>` in the commit window. The crash above only occurs if `quit` is rebound to something else it seems.

Additionally, in both cases, the hint text at the bottom reading `esc: close, tab: new line, enter: confirm` is incorrect (or at least a little misleading), as `<esc>` closes Lazygit entirely, rather than simply closing the commit window. Are the keys in the hint text intended to be universal bindings or are they meant to display the user's specific bindings? If the commit window isn't open, it appears the hints at the bottom reflect my current keybindings. I can open a separate issue for this if you'd like of course.

When using HEAD, if `quit` is rebound to `q`, pressing `<esc>` with the commit window open doesn't do anything, which is better than crashing, but probably still not ideal. If the default binding for `quit` is kept, Lazygit exits instead of doing nothing - same as 26.1.

In any case, no matter what `quit` is bound to, without pressing `CTRL-C` and closing the whole application, it appears there's no way to close only the commit window and keep Lazygit running (without actually making a commit, of course).

Hope this feedback was helpful. I can only imagine how difficult it must be to test some of Lazygit's functionality when users are able to rebind their own keys.

**Comment by jesseduffield** [comment]
@takelley1 I'm not quite following your explanation: by default, q is bound to quit and esc is bound to 'return'. Those bindings persist in version 0.27, but now when hitting the 'return' (default: escape) key at the top level, it doesn't quit the application

**Comment by takelley1** [comment]
Apologies! I should have done more testing and validation using the default configuration. I think I had mixed up the `quit` and `return` bindings. It looks like the main issue fixed though.
