### ISSUE TITLE
No remote appears in the directories created with `worktree`

### ISSUE THREAD

**Issue by gburger11** [jesseduffield/lazygit#1224]
**Describe the bug**
When launching `lazygit` from a repo which has been created with the `worktree add` command, no `Remotes` appears. However, the `git branch -r` or `git remote` commands give the expected outputs.

**To Reproduce**
1. Go to any git repository (which has at least one remote)
2. Create a clone of the repository with `git worktree add <path-to-new-folder>`
3. Go to this new folder
4. Launch lazygit and go to the `Remotes` block
5. No remote appears when one would expect the same remote list as in the original folder

When launched with the debug argument, no error is visible. And manually launching all the commands seems to give the expected behaviour :
```
Apr  7 11:42:55 |INFO| language: en
Apr  7 11:42:55 |INFO| RunCommand command="git --version"
Apr  7 11:42:55 |INFO| RunCommand command="git rev-parse --git-dir"
Apr  7 11:42:55 |INFO| RunCommand command="git config --get push.default"
Apr  7 11:42:55 |INFO| starting main loop
Apr  7 11:42:55 |INFO| Binary is not built with the buildBinary flag so we won't check for an update cont
ext="updates"
Apr  7 11:42:55 |INFO| RunCommand command="git fetch"
Apr  7 11:42:55 |INFO| refreshing all scopes in async mode
Apr  7 11:42:55 |INFO| RunCommand command="git stash list --pretty='%gs'"
Apr  7 11:42:55 |INFO| RunCommand command="git merge-base HEAD HEAD@{u}"
Apr  7 11:42:55 |INFO| RunCommand command="git tag --list"
Apr  7 11:42:55 |INFO| RunCommand command="git for-each-ref --sort=-committerdate --format=\"%(HEAD)|%(re
fname:short)|%(upstream:short)|%(upstream:track)\" refs/heads"
Apr  7 11:42:55 |INFO| RunCommand command="git status --untracked-files=all --porcelain -z "
Apr  7 11:42:55 |INFO| RunCommand command="git branch -r"
Apr  7 11:42:55 |INFO| RunCommand command="git for-each-ref --sort=-committerdate --format=\"%(HEAD)|%(re
fname:short)|%(upstream:short)|%(upstream:track)\" refs/heads"
Apr  7 11:42:55 |ERRO| fatal: no upstream configured for branch 'CloneRepo'
 command="git merge-base HEAD HEAD@{u}"
Apr  7 11:42:55 |INFO| RunCommand command="git symbolic-ref --short HEAD"
Apr  7 11:42:55 |INFO| RunCommand command="git merge-base HEAD master"
Apr  7 11:42:56 |INFO| refreshing the following scopes in async mode: branches,commits,remotes,tags
Apr  7 11:42:56 |INFO| RunCommand command="git tag --list"
Apr  7 11:42:56 |INFO| RunCommand command="git merge-base HEAD HEAD@{u}"
Apr  7 11:42:56 |INFO| RunCommand command="git branch -r"
Apr  7 11:42:56 |ERRO| fatal: no upstream configured for branch 'CloneRepo'
 command="git merge-base HEAD HEAD@{u}"
Apr  7 11:42:56 |INFO| RunCommand command="git for-each-ref --sort=-committerdate --format=\"%(HEAD)|%(re
fname:short)|%(upstream:short)|%(upstream:track)\" refs/heads"
Apr  7 11:42:56 |INFO| RunCommand command="git symbolic-ref --short HEAD"
Apr  7 11:42:56 |INFO| RunCommand command="git merge-base HEAD master"
```

**Expected behavior**
When launching lazygit from a git repository created with `git worktree` the list of remotes appears as in the original folders.

**Screenshots**
In repo created with `worktree` where there exists one remote repository `origin`:
```
$ git remote
origin
```
Nothing appears in the `Remotes` window
![image](https://user-images.githubusercontent.com/22468256/113848086-688fa680-9798-11eb-9dc3-1f8e7e2666e1.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Lazygit Version `commit=, build date=2021-04-06, build source=debian, version=0.27, os=linux, arch=amd64`
 - The last commit id if you built project from sources: N/A, installed through apt-get

**Additional context**

**Comment by parnmatt** [comment]
Just started to use lazygit; I too noticed this issue.
Lazygit doesn't seem to behave well with worktrees; #1280 asks for it as a feature.
