### ISSUE TITLE
lazygit do not work

### ISSUE THREAD

**Issue by iviarcio** [jesseduffield/lazygit#1225]
>lazygit
*errors.errorString unknown view
/home/runner/work/lazygit/lazygit/vendor/github.com/jesseduffield/gocui/gui.go:287 (0x127ddad)
/home/runner/work/lazygit/lazygit/pkg/gui/confirmation_panel.go:177 (0x15a9736)
/home/runner/work/lazygit/lazygit/pkg/gui/confirmation_panel.go:213 (0x15fe14f)
/home/runner/work/lazygit/lazygit/vendor/github.com/jesseduffield/gocui/gui.go:629 (0x1280b8c)
/home/runner/work/lazygit/lazygit/vendor/github.com/jesseduffield/gocui/gui.go:611 (0x128081a)
/home/runner/work/lazygit/lazygit/pkg/gui/gui.go:538 (0x15bc83e)
/home/runner/work/lazygit/lazygit/pkg/gui/gui.go:546 (0x1603305)
/home/runner/work/lazygit/lazygit/pkg/utils/utils.go:380 (0x128c962)
/home/runner/work/lazygit/lazygit/pkg/gui/gui.go:545 (0x15bccdd)
/home/runner/work/lazygit/lazygit/pkg/app/app.go:242 (0x161b3cb)
/home/runner/work/lazygit/lazygit/main.go:126 (0x161ccdb)
/opt/hostedtoolcache/go/1.16.3/x64/src/runtime/proc.go:225 (0x10383b6)
/opt/hostedtoolcache/go/1.16.3/x64/src/runtime/asm_amd64.s:1371 (0x106c201)
❯ lazygit -v
commit=cd1d1996df3ddc31b26ef468debc2c13790aac4c, build date=2021-04-06T09:36:44Z, build source=binaryRelease, version=0.27, os=darwin, arch=amd64
❯

 - OS: MacOS Big Sur 11.2.3
-  terminal: iTerm2 3.4.4 + tmux 3.1c

**Comment by FredrikOlofsson** [comment]
> lazygit
```
2021/04/07 14:49:18 An error occurred! Please create an issue at https://github.com/jesseduffield/lazygit/issues

*errors.errorString unknown view
/home/runner/work/lazygit/lazygit/vendor/github.com/jesseduffield/gocui/gui.go:287 (0xf1d292)
/home/runner/work/lazygit/lazygit/pkg/gui/confirmation_panel.go:177 (0x1257e3d)
/home/runner/work/lazygit/lazygit/pkg/gui/confirmation_panel.go:213 (0x12ad096)
/home/runner/work/lazygit/lazygit/vendor/github.com/jesseduffield/gocui/gui.go:629 (0xf20154)
/home/runner/work/lazygit/lazygit/vendor/github.com/jesseduffield/gocui/gui.go:611 (0xf1fde9)
/home/runner/work/lazygit/lazygit/pkg/gui/gui.go:538 (0x126b365)
/home/runner/work/lazygit/lazygit/pkg/gui/gui.go:546 (0x12b22c8)
/home/runner/work/lazygit/lazygit/pkg/utils/utils.go:380 (0xf2bea7)
/home/runner/work/lazygit/lazygit/pkg/gui/gui.go:545 (0x126b828)
/home/runner/work/lazygit/lazygit/pkg/app/app.go:242 (0x12ca893)
/home/runner/work/lazygit/lazygit/main.go:126 (0x12cc1fb)
/opt/hostedtoolcache/go/1.16.3/x64/src/runtime/proc.go:225 (0xcdbfd6)
/opt/hostedtoolcache/go/1.16.3/x64/src/runtime/asm_amd64.s:1371 (0xd0d701)
```
> lazygit -v
`commit=cd1d1996df3ddc31b26ef468debc2c13790aac4c, build date=2021-04-06T09:36:44Z, build source=binaryRelease, version=0.27, os=windows, arch=amd64`

**Comment by jesseduffield** [comment]
Thanks for raising this issue :) 

fixed in https://github.com/jesseduffield/lazygit/pull/1226 (release v0.27.1)
