### ISSUE TITLE
Tree view doesn't seem to be working

### ISSUE THREAD

**Issue by kalvinpearce** [jesseduffield/lazygit#1227]
**Describe the bug**
I just saw #1197 got merged in 0.27 (been suuuuuuper keen for this feature) and updated to try it out but pressing \` key doesn't seem to do anything. I have also tried to select the `toggle file tree view` menu option and it also doesn't change anything. I have also tried changing the config setting to `true`, with no luck.

**Screenshots**
<details>

![image](https://user-images.githubusercontent.com/17244425/113877771-5e06f880-97fc-11eb-8311-0ea6893f69f6.png)

Screenshot is from within neovim but have tried running standalone from powershell with the same problem.
</details>

**Desktop:**
 - OS: Windows 10
 - Lazygit Version 0.27

**Comment by mjarkk** [comment]
Just pulled in the latest master and it works perfectly fine on mac os.  

Maybe there is some problem with tcell's ` key on windows,  
Can you try to add something like this to the config file:
```yml
keybinding:
    files:
        toggleTreeView: 't'
```

The config file is located at: `%APPDATA%\jesseduffield\lazygit\config.yml`

**Comment by kalvinpearce** [comment]
I have just tried the keybinding change now and still same issue, unfortunately

**Comment by jesseduffield** [comment]
There will be times when the tree appears flat because there is no directory that contains multiple children, however in your screenshot that does not appear to be the case. I wonder why it wouldn't work on windows. Maybe the code is assuming forward slashes as path separators somewhere. In fact that's almost certainly what it is haha

**Comment by jesseduffield** [comment]
@kalvinpearce can you see if your issue is resolved on the latest master? I just tested it on my PC and it worked for me

**Comment by kalvinpearce** [comment]
🙏 beautiful! working like a charm. On a small side note, I don't suppose theres a way to collapse those tree nodes is there? Could be a nice addition if not but absolutely this does wonders for readability and I am keen to use lazygit more as my primaray git interface

**Comment by kalvinpearce** [comment]
Never mind i just found the folding 🙏 you are a legend!!!

**Comment by jesseduffield** [comment]
Pleasure to be of service!
