### ISSUE TITLE
Commit message pane is stay opened after `git commit` when `commit.gpgSign` is true

### ISSUE THREAD

**Issue by Ryooooooga** [jesseduffield/lazygit#1228]
**Describe the bug**
When `commit.gpgSign` is true, the commit message pane is stay opened even if `git commit` succeeds.

**To Reproduce**
1. `git config commit.gpgSign true`
2. Stage some changes and commit them
3. `git commit -m "..."` is executed
4. Press enter to return to lazygit
5. The commit message pane is stay opened

**Expected behavior**
If `git commit` is succeeds, it should be closed.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS
 - Lazygit Version: HEAD
 - The last commit id: a229547048b78fb5130fc5252f696dc8e2d59be4

---

https://github.com/jesseduffield/lazygit/blob/a229547048b78fb5130fc5252f696dc8e2d59be4/pkg/gui/commit_message_panel.go#L20

This sentence may return true (?) but `runSubprocessWithSuspense()` never returns an error.

**Comment by jesseduffield** [comment]
fixed in https://github.com/jesseduffield/lazygit/pull/1232

**Comment by jesseduffield** [comment]
@Ryooooooga can you test this on v0.27.2?

**Comment by Ryooooooga** [comment]
@jesseduffield Thank you for fixing it. But won't this close the panel if the pre-commit hook fails?

**Comment by jesseduffield** [comment]
I did notice that would be a change. Is that necessarily a bad thing? I expect that a precommit hook failing means you need to fix up some files

**Comment by Ryooooooga** [comment]
That's right.
