### ISSUE TITLE
Crash during startup

### ISSUE THREAD

**Issue by tomekwilk** [jesseduffield/lazygit#1229]
**Describe the bug**
Lazygit crashes during startup. 

**To Reproduce**
1. Type `lazygit` from the command line

**Expected behavior**
Lazygit should start succesfully

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.1
 - Lazygit Version v0.27.1
 - The last commit id if you built project from sources a229547048b78fb5130fc5252f696dc8e2d59be4

**Additional context**
$ ./lazygit
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x99f0f3]

goroutine 1 [running]:
github.com/jesseduffield/gocui.(*View).Name(...)
	/home/tomek/go/pkg/mod/github.com/jesseduffield/gocui@v0.3.1-0.20210406065942-1b0c68414064/view.go:350
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).getWindowForView(...)
	/home/tomek/lazygit/pkg/gui/window.go:25
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).currentWindow(...)
	/home/tomek/lazygit/pkg/gui/window.go:37
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).getMidSectionWeights(0xc00008cc00, 0xc0001bd518, 0x453b47)
	/home/tomek/lazygit/pkg/gui/arrangement.go:42 +0x153
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).getWindowDimensions(0xc00008cc00, 0xc00002f480, 0x1d, 0x0, 0x0, 0x76)
	/home/tomek/lazygit/pkg/gui/arrangement.go:136 +0x5e
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).layout(0xc00008cc00, 0xc00008cd80, 0x0, 0xc00006e900)
	/home/tomek/lazygit/pkg/gui/layout.go:48 +0x16d
github.com/jesseduffield/gocui.ManagerFunc.Layout(0xc0000203b0, 0xc00008cd80, 0x25, 0xc0001bd880)
	/home/tomek/go/pkg/mod/github.com/jesseduffield/gocui@v0.3.1-0.20210406065942-1b0c68414064/gui.go:555 +0x30
github.com/jesseduffield/gocui.(*Gui).flush(0xc00008cd80, 0x0, 0x0)
	/home/tomek/go/pkg/mod/github.com/jesseduffield/gocui@v0.3.1-0.20210406065942-1b0c68414064/gui.go:669 +0x45d
github.com/jesseduffield/gocui.(*Gui).MainLoop(0xc00008cd80, 0xc000000004, 0xc0001bda18)
	/home/tomek/go/pkg/mod/github.com/jesseduffield/gocui@v0.3.1-0.20210406065942-1b0c68414064/gui.go:614 +0x21d
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).Run(0xc00008cc00, 0x0, 0x0)
	/home/tomek/lazygit/pkg/gui/gui.go:529 +0x51b
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).RunAndHandleError.func1(0xc00008cc01, 0xc000088600)
	/home/tomek/lazygit/pkg/gui/gui.go:537 +0x45
github.com/jesseduffield/lazygit/pkg/utils.SafeWithError(0xc0001bdb50, 0x0, 0x0)
	/home/tomek/lazygit/pkg/utils/utils.go:380 +0x62
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).RunAndHandleError(0xc00008cc00, 0x0, 0xb6a89f)
	/home/tomek/lazygit/pkg/gui/gui.go:536 +0x7d
github.com/jesseduffield/lazygit/pkg/app.(*App).Run(0xc00017fb90, 0xc000160630, 0x0)
	/home/tomek/lazygit/pkg/app/app.go:242 +0x6b
main.main()
	/home/tomek/lazygit/main.go:126 +0xb3b

$ uname -a
Linux t-vm1 5.8.0-48-generic #54~20.04.1-Ubuntu SMP Sat Mar 20 13:40:25 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

$ lazygit -v
commit=, build date=2021-04-07, build source=debian, version=0.27.1, os=linux, arch=amd64

**Comment by jesseduffield** [comment]
should be fixed in v0.27.2

**Comment by tomekwilk** [comment]
I am getting build failure with v0.27.2
$ go build ./...
# github.com/jesseduffield/lazygit/pkg/gui
pkg/gui/gui.go:484:4: cannot use getRecordingSpeed() (type float64) as type int in field value

$ git log -1
commit d5504fa5d0d4e0312e1b27b8dbe3c6c664395a31 (HEAD -> master, tag: v0.27.2, origin/master, origin/HEAD)
Author: Jesse Duffield <jessedduffield@gmail.com>
Date:   Fri Apr 9 00:33:39 2021 +1000

    potentially fix credentials issue

**Comment by tomekwilk** [comment]
Casting float64 to int in pkg/gui/gui.go:484 fixes the build issue.
Also verified that 0.27.2 fixes the crash issue for me on Ubuntu.
