### ISSUE TITLE
lazygit-0.27.1 has broken prompt on git push (Shift+p) action

### ISSUE THREAD

**Issue by band-a-prend** [jesseduffield/lazygit#1231]
The lazygit 0.27 and 0.27.1 have broken `git push` action by pressing shortcut `Shift+p`:
after pressing shortcut `Shift+p` the `Pushing ....\` popup is shown but no "https"/"ssh" prompts appear to ask credentials/passphrase even after long wait ~1 minute.

Both 0.27.x versions were built with Go 1.16.2 (Gentoo dev-lang/go-1.1.6.2).
The release of lazygit-0.26.1 isn't affected this issue.

**Comment by jesseduffield** [comment]
@band-a-prend can you try v0.27.2?

**Comment by band-a-prend** [comment]
Thank you! This issue is fixed in lazygit 0.27.2.

**Comment by joshgummersall** [comment]
I noticed the same issue earlier today, just upgraded to 0.27.2, and the issue is resolved!

**Comment by jesseduffield** [comment]
Sweet :) closing

**Comment by fcomoreira1** [comment]
When is version 0.27.2 going to be pushed to Copr?

**Comment by jesseduffield** [comment]
I am actually not sure; I don't manage the Copr repo
