### ISSUE TITLE
Invisible added lines in some modified or added files

### ISSUE THREAD

**Issue by NikolayXHD** [jesseduffield/lazygit#1235]
**Describe the bug**

Since v. 0.27.1, Invisible added lines in some, but not all, modified files

**To Reproduce**

1. clone https://github.com/NikolayXHD/Mtgdb repository
2. go to commit 20bcdcd2
3. choose in commit files pane Mtgdb.Data/ImageRepository.cs

**Screenshots**
modified files (green lines starting with +) invisible
![image](https://user-images.githubusercontent.com/12046452/114021252-2db16f80-9879-11eb-84fe-1b5624d6ede6.png)

if I hit enter, to edit the patch, the modified lines become visible
![image](https://user-images.githubusercontent.com/12046452/114021386-50438880-9879-11eb-9ce8-fc9f4e32c668.png)

**Desktop (please complete the following information):**
 - OS: Kubuntu 20.04
 - Lazygit Version 0.27.1

**Comment by jesseduffield** [comment]
snap, I didn't think of carriage returns when implementing that code to reduce flicker. I'll revert that code for now and think some more about how to handle carriage returns: https://github.com/jesseduffield/lazygit/pull/1236

**Comment by jesseduffield** [comment]
v0.27.2 has the revert :)

**Comment by NikolayXHD** [comment]
Thank you!
