### ISSUE TITLE
Amending a commit causes hanging "Press enter to return to lazygit"

### ISSUE THREAD

**Issue by joshgummersall** [jesseduffield/lazygit#1240]
**Describe the bug**

The "Press enter to return to lazygit" message is presented but subsequent input is ignored.

**To Reproduce**
1. Stage some files and then press `Shift+A` to amend the last commit
2. Press enter to confirm
3. Observe "Press enter to return to lazygit"
4. Press enter (or `Ctrl+C`) and observe that nothing happens

**Expected behavior**
Pressing enter should return me lazygit, an `Ctrl+C` should kill the process and drop me back in my terminal.

**Desktop (please complete the following information):**
 - OS: Mac
 - Lazygit Version: 0.27.2

**Comment by jesseduffield** [comment]
@joshgummersall this sometimes happens if lazygit panics in a prior session. Do you recall that happening?

**Comment by joshgummersall** [comment]
I think I may have seen that earlier - is there some local state I can clear to see if that resolves the issue?

**Comment by jesseduffield** [comment]
I think it requires passing a specific code to the terminal to switch it to a certain mode but I'm not sure what that is (something I intend on investigating). When it happens to me I close the current terminal panel and open a new one in its place

**Comment by joshgummersall** [comment]
The same behavior continues even after completely exiting and reopening iTerm2 which seems odd. Let me know if there's any extra context or data I can provide that might help!

**Comment by jesseduffield** [comment]
interesting, this might be a legit newly introduced bug. When I go to amend a commit it just does it from within lazygit. Do you have something configured that makes it switch to a subprocess? E.g. gpg signing enabled?

**Comment by joshgummersall** [comment]
I do use gpg signing. I'm almost positive I amended commits without any issues yesterday, I ran `brew upgrade` this morning and then it no longer worked. Maybe I should clone the repo and do a bisect, would that help?

**Comment by jesseduffield** [comment]
@joshgummersall please do!

**Comment by joshgummersall** [comment]
@jesseduffield `git bisect` yielded `6a6024e38fed189606c4267dc6c18b1e1040c7ad` as the offending commit. I ran `go build -o ../lg main.go` to produce a binary, the executed that binary in a test repo with a change to amend the latest commit. Running `git checkout 6a6024e38fed189606c4267dc6c18b1e1040c7ad~1` and repeating the test worked as expected. Let me know if there's any extra info that might be helpful!

**Comment by jesseduffield** [comment]
nice! should be fixed on master now https://github.com/jesseduffield/lazygit/pull/1243

**Comment by joshgummersall** [comment]
Yep - all set! Thank you.
