### ISSUE TITLE
PPA not working for installation. Seems to be blank?

### ISSUE THREAD

**Issue by Antonio-Bennett** [jesseduffield/lazygit#1248]
**Topic**
A clear and concise description of what you want to discuss

I want to install lazygit on ubuntu via the ppa but it seems to be blank? Even though it says there was 40 updates in the last month? I cannot install

![image](https://user-images.githubusercontent.com/31296212/114298007-142f4400-9a82-11eb-8361-dd4dd870d3da.png)
![image](https://user-images.githubusercontent.com/31296212/114298088-96b80380-9a82-11eb-8a0c-a3a8bcf44fc1.png)

**Your thoughts**
What you have to say about the topic

As you can see it's not finding Lazygit. Wasn't really sure if this was a bug since it just seems that ppa has to be updated.

**Comment by jesseduffield** [comment]
Looks like the build is failing:
https://launchpad.net/~lazygit-team/+archive/ubuntu/release/+build/21381313
https://launchpadlibrarian.net/532948874/buildlog_ubuntu-focal-arm64.lazygit_0.27.4-1~ubuntu20.04.1_BUILDING.txt.gz
```
VERSION=0.27.4
dh_auto_build -- -ldflags \
	"-X main.commit= \
	-X main.date=2021-04-11 \
	-X main.version=0.27.4 \
	-X main.buildSource=debian"
	cd obj-aarch64-linux-gnu && go install -v -p 1 -ldflags "-X main.commit= 	-X main.date=2021-04-11 	-X main.version=0.27.4 	-X main.buildSource=debian"
Can't exec "go": No such file or directory at /usr/share/perl5/Debian/Debhelper/Dh_Lib.pm line 484.
dh_auto_build: error: cd obj-aarch64-linux-gnu && go install -v -p 1 -ldflags "-X main.commit= 	-X main.date=2021-04-11 	-X main.version=0.27.4 	-X main.buildSource=debian" failed to execute: No child processes
dh_auto_build: error: cd obj-aarch64-linux-gnu && go install -v -p 1 -ldflags "-X main.commit= 	-X main.date=2021-04-11 	-X main.version=0.27.4 	-X main.buildSource=debian" returned exit code 25
```

I am not too sure how to tackle this. Any ideas @dawidd6 ?

**Comment by dawidd6** [comment]
Last few releases were problematic. There were some build errors with go1.10. I had to drop support for Ubuntu older than 18.04, because newer Go is needed now. I'm going to make a revision bump and build new packages now.

**Comment by jesseduffield** [comment]
@dawidd6 fair enough: should we update the readme accordingly?

**Comment by dawidd6** [comment]
Yes
