### ISSUE TITLE
Rendering issues with new library

### ISSUE THREAD

**Issue by fsmiamoto** [jesseduffield/lazygit#1254]
As it appears, the change of the rendering library introduced in #1217 has brought some rendering issues on my environment.

I've tested on both 0.26.1 and 0.27.4 (which uses `tcell`) and been able to reproduce the issue on the terminal emulators `st` and `alacritty`.

Both builds used were taken from the official releases of the repo.

I'm not very familiar with the inner workings of the rendering libraries so I'm not sure what could be the cause but I can definitely help investigate it :)

**Expected behavior**
Rendering of both versions should be the same.

**Screenshots**
- 0.26.1
![image](https://user-images.githubusercontent.com/20388082/114309901-36938280-9abf-11eb-8f6c-af0ba532d8ea.png)

- 0.27.4
![image](https://user-images.githubusercontent.com/20388082/114309893-2ed3de00-9abf-11eb-865a-89f60e6dd367.png)

**Environment**
 - Distro / Kernel: Arch Linux - 5.11.12-arch1-1
 - Lazygit Versions: `0.26.1` and `0.27.4`
 - `$TERM`: `st-256color`

**Comment by ms-jpq** [comment]
I have noticed some issues too

1) some boxes are out of alignment

2) the popup dialog eats the first column, 


![图片](https://user-images.githubusercontent.com/50598611/114371370-45b51780-9b35-11eb-8b16-7dabcc06a226.png)

**Comment by jesseduffield** [comment]
The file for st-256color terms is https://github.com/jesseduffield/lazygit/blob/master/vendor/github.com/gdamore/tcell/v2/terminfo/s/simpleterm/term.go

I would expect any weird rendering stuff to be a result of how things are configured in that file, although nothing jumps out at me as being problematic. Hmm

**Comment by jesseduffield** [comment]
@ms-jpq @fsmiamoto I've done some digging: this is due to the runewidth package thinking that box characters are double-width in east asian encodings. Going `export LANG=en_US.UTF-8` should suffice as a workaround for now, but I've raised an issue in the runewidth repo to fix this: https://github.com/mattn/go-runewidth/issues/49

**Comment by fsmiamoto** [comment]
Oh it was that then, thanks @jesseduffield :)

**Comment by jesseduffield** [comment]
fixed in https://github.com/jesseduffield/lazygit/pull/1284
