### ISSUE TITLE
Add new line in commit message popup prompt stopped working

### ISSUE THREAD

**Issue by mastern2k3** [jesseduffield/lazygit#1258]
**Describe the bug**
When writing a commit message in the popup prompt, pressing the TAB key should add a new line to the message.
This used to work in the past but no longer works for me.

**To Reproduce**
1. Open **lazygit** for a repository with pending changes.
2. Click `C` to open the commit message dialog.
3. Write a message.
4. Press `Tab`

**Expected behavior**
A new line should appear after the commit line written in the prompt, expanding the prompt box.

**Screenshots**
![Screenshot from 2021-04-12 12-55-41](https://user-images.githubusercontent.com/4235611/114376650-7f663c80-9b8e-11eb-9f5c-cd6417346bb4.png)

**Desktop (please complete the following information):**
 - OS: Linux Mint
 - lazygit --version `commit=, build date=2021-04-11, build source=debian, version=0.27.4, os=linux, arch=amd64`

**Comment by jesseduffield** [comment]
v0.27 changed the default keybinding to alt-enter (i.e. meta-enter). You can change it back to tab in your config with:
```
keybinding:
  universal:
    appendNewline: '<tab>'
```

I'm open to having the old keybinding there by default, but it would take away from the ability to add an actual tab character (which is admittedly not currently possible). What are your thoughts?

**Comment by mastern2k3** [comment]
I'm good with alt-enter, more into standard and friendly for new users, it is the correct choice as a default.

Then you might consider changing the info label on the bottom:

![Screenshot from 2021-04-12 15-19-30](https://user-images.githubusercontent.com/4235611/114393281-85feaf00-9ba2-11eb-8c94-5cdb98da172d.png)

e.g. `tab: new line`

P.S. can't stress how much I find **lazygit** helpful and efficient, it is a great tool, thanks for making this all possible :+1:

**Comment by jesseduffield** [comment]
Good pickup: fixed in https://github.com/jesseduffield/lazygit/pull/1262

And thanks for the kind words! I really appreciate it
