### ISSUE TITLE
Files view-box rendering

### ISSUE THREAD

**Issue by MiroslavMikus** [jesseduffield/lazygit#1268]
**Describe the bug**
Files view-box outline is sometimes wrong:
*see screenshot*

**To Reproduce**
Try to change/add many files and scroll down.

**Expected behavior**
Viewbox should be rendered correctly.

**Screenshots**
![Lazy_git_files_bug](https://user-images.githubusercontent.com/29312172/114543234-37601c00-9c59-11eb-8292-c42891dab706.gif)

**Desktop:**
 - OS: Windows 10.0.19042
 - Terminal: WindowsTerminal 1.6.10571.0
 - Powershell: 7.1.3
 - Lazygit Version 0.25.1

**Comment by jesseduffield** [comment]
@MiroslavMikus are you able to try this on the latest version?

**Comment by MiroslavMikus** [comment]
@jesseduffield Hey, thanks for the quick response. I could not reproduce this issue in 0.27.4!
