### ISSUE TITLE
Auto-fetch should not refresh Patch view

### ISSUE THREAD

**Issue by MiroslavMikus** [jesseduffield/lazygit#1272]
**Describe the bug**
When I read a huge file in the `Commits>Page` view I don't want the view to jump to the top every 60 seconds.

**To Reproduce**
1. Open `Commits>Page`
2. Select file with `Enter`
3. Scroll down with `Page-down`
4. Either wait for fetch update or add to settings:
``` yaml
refresher:
  refreshInterval: 10
  fetchInterval: 1
```
**Expected behavior**
I expect to get the latest git updates with the auto-fetch feature enabled and be able to read files at the same time.

**Screenshots**
![LG_Reader](https://user-images.githubusercontent.com/29312172/114612795-da895380-9ca2-11eb-86a7-5076b74e50e1.gif)

**Desktop:**
 - Lazygit Version 0.27.4

**Comment by grossjohann** [comment]
Actually, I think this is true for everything that is shown in the right hand panel, the panel that is scrolled with J/K and the page up/down keys.  For example, if that panel shows the list of commits (output of `git log`, mostly), then that also scrolls back to the top.
