### ISSUE TITLE
layout is broken on Japanese environment

### ISSUE THREAD

**Issue by t2h5** [jesseduffield/lazygit#1277]
**Describe the bug**

In my environment, lazygit layout is broken since v0.27.
- macOS: 11.2.3
- zsh: 5.8 (x86_64-apple-darwin20.1.0)

**To Reproduce**

Open `lazygit` v0.27.x on Japanese setting macOS.

**Expected behavior**

v0.27 keeps layout as v0.26.

**Screenshots**

v0.26 works fine but v0.27 is not.
- v0.26.1
![image](https://user-images.githubusercontent.com/19473293/115018553-f420da00-9ef2-11eb-9deb-b6c3dc81bc50.png)

- v0.27.4
![image](https://user-images.githubusercontent.com/19473293/115018800-47932800-9ef3-11eb-8481-09eb5b0eb4c5.png)

**Desktop (please complete the following information):**
 - OS: macOS (Japanese setting)
 - Lazygit Version: v0.27.4

**Additional context**

I'm not sure, but this problem is related with [gocui](https://github.com/jesseduffield/gocui)?

**Comment by jesseduffield** [comment]
@t2h5 which terminal do you use? I'm on mac using iterm2 and that works. terminal.app also works

**Comment by t2h5** [comment]
@jesseduffield I'm using iterm2 (version 3.4.5), but same thing happens on terminal.app.

**Comment by t2h5** [comment]
Maybe I found this is some regional problem.
I'm using mac system on Japanese (日本語), but after switch language to English, v0.27.4 works fine.

![image](https://user-images.githubusercontent.com/19473293/115099537-849dff80-9f71-11eb-9351-05cb0f5a6a19.png)

**Comment by t2h5** [comment]
I was using lazygit under `LANG="ja_JP.UTF-8"`.
v0.27 works on Japanese setting by configure `LANG` as `en_US.UTF-8`.

```
export LANG=en_US.UTF-8
```

**Comment by t2h5** [comment]
@jesseduffield 
This problem was solved, `LANG` setting works fine for me.
Please close this issue if it's ok with you.
Thank you.

**Comment by jesseduffield** [comment]
Nice investigation @t2h5 !

I'll leave this issue open until we can fix the issue without the user needing to change their LANG env var. I've opened an issue in the runewidth package to address this: https://github.com/mattn/go-runewidth/issues/49

**Comment by jesseduffield** [comment]
fixed in https://github.com/jesseduffield/lazygit/pull/1284

**Comment by chungonion** [comment]
Thank you @t2h5 for finding this issue! My mac uses Traditional Chinese as the primary language and this issue has bothered me for a while... 

Also many thanks for @jesseduffield for fixing this issue and the amount of work spent on this piece of software, thank you so much =]

**Comment by jesseduffield** [comment]
@chungonion thanks I really appreciate it!
