### ISSUE TITLE
Keybindings file with <kbd> tag

### ISSUE THREAD

**Issue by ponsfrilus** [jesseduffield/lazygit#128]
This is not an issue but more a "what do you think" ticket. I've changed the Keybindings.md file to add the `<kbd></kbd>` tags which results in [this](https://jbt.github.io/markdown-editor/#jVVLbtswEN37FANkEQcF4n1gZNEE7aIoYCToAShqJDGmSIak7LoH6LqfG/YkHdKiTMlWEK044pvfm+HMFXzBQyFUKVTt7haLqyv4LHXB5N1ibSzeLwDW26K8//fz13oVDr30ZyT9Hkl/j9Iqik129ZKdt9lZHs93AIrtRM08Jreb+pvJrW3qRzWAh89xq6WEUlQVGKZQwrJzeLRQ9fgPUepG1sZ3pd73MmgF2n2/SVG8nrscvtdO+IQzb+BMJ2XCuUZUPne9uaRoOtcs1qtYhVCXT0Kig03Ib1IcZxjHzITXdS0RnGc1lgnEJz64blvhgTdM1ehmQ3tIaj2+c9QpUNMJS+G1nVV8TooUhmugCtEnsJ/EwsqSCud5gyUsxS3eghF8S7F1autAV8CiPiUWoENd9MSMNqjSHU7uQrRDrBf0QChwXSFFi7C0SGW1xPZ1+HUdc2fq5Hg3Y2DnuC5H+kE+1xcX8qfcbolWUStth/4vJ8ASJXoEUUGnvGV8S4QRa3yrOx/+pn9LtmVQE1t7driZLdFTsm6xomhTkbKe+2iZIvvvarshjiIqJVQ1TqHSluMcth1jW7Q1JauIGt5Zi8rLw1GVUjzXnnT4yceB5ko7cDoZIAr3EzsT0nvOe0xGzkN8ETPcjG241y48gjBiYKkVpcF2TEhWUFMTI1R802rn+0c2VMyOrRADlEcPSph6inHoQzP5RrgEzYJ+jq/xHeVkxsjDjBOjzRxZlq4ydxttOnPRHbpRvbjUDlecOMZhTlLBMaOAa1UJ2w5DhBW5gQgO1ZRC0ROkxxCePA2rmzyeJ3Ra7sII+xqb64FsSsGpisvHsD5ipDfvW37nC25YZGmPxZij/ZOtN5ZlvhRfhvlJ/cc9hFk4N/DhOC9zSDGZHEdEoX0TYUM8P6a4TpX6rEf3jYgLRdCaFcoJGnKnbZsI/g8=).

![image](https://user-images.githubusercontent.com/176002/43990472-5e5a2ca0-9d5c-11e8-92cf-2f448d90323b.png) vs ![image](https://user-images.githubusercontent.com/176002/43990591-79f04d86-9d5d-11e8-807d-baeae68aeaea.png)

#### Pros
  * Visually better, more appealing

#### Cons
  * More tricky to edit
  * More difficult to read from the file itself

Should I make a PR for this ?

**Comment by jesseduffield** [comment]
looks good to me!
