### ISSUE TITLE
Worktree integration

### ISSUE THREAD

**Issue by abenz1267** [jesseduffield/lazygit#1280]
Hello,

right now checking out branches that are present as worktrees doesn't work, as you get "fatal: *branch* is alreadt checked out at .."

Not sure if it's doable or even makes sense, but a simple cwd change would be the expected behaviour i guess.

Also opening up lazygit in the bare repo doesn't recognize the folder as a bare repo and wants to init git first, which ofc isn't want you want.

Ideas? Would this be within the scope of Lazygit?

Regards

**Comment by parnmatt** [comment]
I too would like to see this feature :+1:

**Comment by jmauriciosalasmoreno** [comment]
This would be very useful
Getting the following error ".git not a directory". Since .git does not exist in the subdirectories added via "git worktree add"

**Comment by parnmatt** [comment]
> Since .git does not exist in the subdirectories added via "git worktree add"

It *does* create a `.git`; however, it is not a directory, it is a file containing something like:

    gitdir: <PATH_TO_BARE_REPO>.git/worktrees/<WORKTREE_NAME>

this can therefore be used by Lazy git to point to the relevant git directory

**Comment by williamgoulois** [comment]
I would love to have this feature implemented ! I'm still using stashes or wip commits to be able to checkout to another branch and it's quite painful

**Comment by FacePalmDev** [comment]
For those of you who are desperate for this feature... Check this out:

![image](https://user-images.githubusercontent.com/4026553/188816683-157f6ae7-4aee-4fae-8e90-30aa4ccea971.png)

How? Simple... go to File, Preferences, Custom Commands and add it there:

![image](https://user-images.githubusercontent.com/4026553/188816884-ff0d7744-04aa-4640-a2fa-3e12cf2d00c4.png)

I hope this helps you ;-)

**Comment by mark2185** [comment]
I'm sorry, but is that a _GUI_ for `lazygit` or...?

**Comment by FacePalmDev** [comment]
I got a little too excited and confused there!
Nope it was for gitfork! Sorry!


Best wishes,
Kiran

**Comment by ptim** [comment]
> ... can therefore be used by Lazy git to point to the relevant git directory ([comment](https://github.com/jesseduffield/lazygit/issues/1280#issuecomment-903258653))

this is working well for me - think I misunderstood the context of the issue 👍

**Comment by jesseduffield** [comment]
Worktree support is on the way: https://github.com/jesseduffield/lazygit/pull/2147

If you would like to shape the UX check out the discussion here: https://github.com/jesseduffield/lazygit/discussions/2803

**Comment by JakeTompkins** [comment]
> Worktree support is on the way: #2147
> 
> If you would like to shape the UX check out the discussion here: #2803

This functionality is very exciting. Do we have a tentative schedule for the next release?

**Comment by jesseduffield** [comment]
It's not far off, I think it'll be in the next couple days. I just want to spend a bit more time with it to catch intermittent UI bugs (e.g. https://github.com/jesseduffield/lazygit/pull/2863)

**Comment by JakeTompkins** [comment]
> It's not far off, I think it'll be in the next couple days. I just want to spend a bit more time with it to catch intermittent UI bugs (e.g. #2863)

Awesome!

**Comment by jackoconnordev** [comment]
That's amazing it's on the way soon! I was just watching this video https://m.youtube.com/watch?v=IK_mjDqGUYE about Git Worktrees and came straight here and it sounds so useful 😁

**Comment by jesseduffield** [comment]
This has now been released so I'm closing this issue off :)
