### ISSUE TITLE
Lazygit 0.28.1 build, mouse not working

### ISSUE THREAD

**Issue by lcc014** [jesseduffield/lazygit#1290]
Just upgraded lazygit from 0.26 to 0.28.1 today and found that mouse did not work anymore.  I used to use mouse pointer to activate different panel or select different file names, etc.  It was working fine in build 0.26 but not working anymore.  I can switch between panel using number keys and arrow keys to select/scroll around files, commits, etc.

Is mouse function disabled in 0.28.1 build or else ?  My git version is 2.27.0

Thanks.

Ching-Ho Cheng

**Comment by peppy** [comment]
Looks to be working as expected here.

**Comment by lcc014** [comment]
Thank you for the confirmation.  In which build did lazygit stop supporting the usage of mouse ?

**Comment by mjarkk** [comment]
@lcc014 Mouse support should work.  
What terminal emulator are you using?

**Comment by lcc014** [comment]
Xterm used to work but not with 0.28.1.  Then I tried LX Terminal, it worked fine with mouse.  So I am using LX Term from now on.  Also, the color in Xterm was hard to distinguish the highlighted items such as branch, commit, files etc in the left hand side panels.
