### ISSUE TITLE
Random Tip got cut off in random occasion

### ISSUE THREAD

**Issue by Iyxan23** [jesseduffield/lazygit#1292]
**Describe the bug**
Every time I ran `lazygit`, a Random Tip will appear at the command log, but on some random occasion, the front of the text got cut off.

**To Reproduce**
1. Run `lazygit` multiple times until you get the bug

**Expected behavior**
The text shouldn't be cut off, it should display the entirety of the tip, I'm guessing this has something to do with word wrapping.

**Screenshots**
![image](https://user-images.githubusercontent.com/31884435/115675947-4b063380-a379-11eb-9fce-acefb233d2df.png)
![image](https://user-images.githubusercontent.com/31884435/115676086-70933d00-a379-11eb-9298-edbde82a1161.png)

**Desktop:**
 - OS: OpenSUSE Tumbleweed Linux
 - Lazygit Version 0.28.1

**Comment by Iyxan23** [comment]
Oh wait I just checked that I can scroll the command log to see the uncut tip

**Comment by jesseduffield** [comment]
Yep this comes down to the fact that it's not easy to scroll to the beginning of the random tip. When you're using up the whole terminal window it should have more room to show the whole tip, but when it's only one line it's tricky. It's something I could look into though
