### ISSUE TITLE
Windows "cat" command "The syntax of the command is incorrect" when files use '/' in the path instead of '\'

### ISSUE THREAD

**Issue by mwebb387** [jesseduffield/lazygit#1299]
Describe the bug
The merge conflicts panel displays an error saying, "The syntax of the command is incorrect" rather than the merge conflict.

To Reproduce

Run a rebase that will produce a conflict.
Go to the files panel
Expected behavior
I would expect to see a typically conflict diff in the merge conflicts panel.

Screenshots
![image](https://user-images.githubusercontent.com/22566991/116255474-46a69580-a740-11eb-9887-eb6825223324.png)

Desktop (please complete the following information):

OS: Windows 10
Lazygit Version v0.28.1
Additional context
I believe this has to do with the format expected by cmd.exe and a requirement of `\` in the file path instead of `/`. The output from Lazygit is the following:

> {"buildDate":"2021-04-20T11:09:15Z","command":"cmd /c type ProjectFolder/css/dist/global.min.css","commit":"9190e9beac90d80e854a726134b12e15d239df45","debug":true,"level":"info","msg":"Cat","time":"2021-04-27T09:52:49-04:00","version":"0.28.1"}
> {"buildDate":"2021-04-20T11:09:15Z","command":"cmd /c type ProjectFolder/css/dist/global.min.css","commit":"9190e9beac90d80e854a726134b12e15d239df45","debug":true,"level":"error","msg":"The syntax of the command is incorrect.\r\n","time":"2021-04-27T09:52:49-04:00","version":"0.28.1"}

If I type the command from the above log output directly into the shell I get the same error reported from Lazygit, but if I type the same command using `\` in the file path instead, I get the file output in the shell correctly.

Maybe this can be added as a configuration option in the future as well. I have both `cat.exe` and `bat.exe` in my path on windows, so to to be able to configure the cat command directly would also be helpful.

**Comment by bin101** [comment]
I also experienced the issue today. Would be great if this could be fixed in the near future.
