### ISSUE TITLE
Interface bug

### ISSUE THREAD

**Issue by SmokeCat** [jesseduffield/lazygit#130]
Win10
PowerShell
lazygit_0.1.51_Windows_x86_64

![lazygit_bug](https://user-images.githubusercontent.com/31913234/43992401-86be4fe2-9db0-11e8-94c6-a0d48dbd8be2.png)

**Comment by jesseduffield** [comment]
This is an issue with how the gocui library deals with some unicode characters. See https://github.com/jesseduffield/lazygit/issues/24

Closing as a duplicate
