### ISSUE TITLE
"The syntax of the command is incorrect"

### ISSUE THREAD

**Issue by amatosg** [jesseduffield/lazygit#1316]
**Describe the bug**
When having conflicts, I cannot resolve the conflicts as shown in the picture 

**To Reproduce**
1. Merge 2 branches that create conflicts
2. See the error.

**Expected behavior**
I should be able to resolve conflicts

**Screenshots**
![image](https://user-images.githubusercontent.com/42916953/118520784-f9469400-b6ff-11eb-9a7a-965ca2d312d2.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Lazygit Version v0.28.1 (commit id: 9190e9beac90d80e854a726134b12e15d239df45)
 - The last commit id if you built project from sources

**Comment by Ryooooooga** [comment]
Fixed in https://github.com/jesseduffield/lazygit/pull/1449
