### ISSUE TITLE
lazy git fails in deleted dirs

### ISSUE THREAD

**Issue by paxel** [jesseduffield/lazygit#1321]
**Describe the bug**
typing lg in a deleted dir in a repo leads to

```
2021/05/19 12:53:01 An error occurred! Please create an issue at https://github.com/jesseduffield/lazygit/issues

*os.SyscallError getwd: no such file or directory
/build/lazygit-FjUyrt/lazygit-0.26.1/obj-x86_64-linux-gnu/src/github.com/jesseduffield/lazygit/main.go:133 (0x99f83a)
/usr/lib/go-1.10/src/runtime/proc.go:198 (0x42cec2)
/usr/lib/go-1.10/src/runtime/asm_amd64.s:2361 (0x458121)
sh: 0: getcwd() failed: No such file or directory
```

**To Reproduce**
* go into a directory in a git repo
* delete the directory (from a different shell)
* type lg / lazygit

**Expected behavior**
dunno, maybe try to navigate to parent dirs until it works :D

**Desktop (please complete the following information):**
 - OS: 18.04.1-Ubunt
 - Lazygit Version commit=, build date=2021-03-14, build source=debian, version=0.26.1, os=linux, arch=amd64

**Comment by mark2185** [comment]
This doesn't seem like a `lazygit` issue in and of itself, even `ls` or `pwd` would fail here. How are we supposed to recover?
