### ISSUE TITLE
Is there a quick way to open the project with one click

### ISSUE THREAD

**Issue by vitasapple** [jesseduffield/lazygit#1328]
Every time I want to use lazygit, I need to open the terminal and type cd to the project, then type lazygit to start the commit operation, is there a quick way to open the project with one click?

**Comment by mjarkk** [comment]
There is a switch to a recent repo option in lazygit by going to the status panel and pressing enter.  
When outside of a repo folder you can also open lazygit say NO to creating a new repo and then the same menu also pops up.

**Comment by vitasapple** [comment]
> There is a switch to a recent repo option in lazygit by going to the status panel and pressing enter.
> When outside of a repo folder you can also open lazygit say NO to creating a new repo and then the same menu also pops up.
> These are both not one click actions but they might be much faster if you have long repo paths.

thanks
