### ISSUE TITLE
I want to help make i18n happen

### ISSUE THREAD

**Issue by mjarkk** [jesseduffield/lazygit#134]
This project looks interesting and i would like to help make i18n happen.  
But there are many ways this could be dune.  
  
Do you have a preferred way to get i18n into the project?  
  
Here are some package options:  
- http://nicksnyder.github.io/go-i18n/
- https://github.com/rocwong/i18n
- https://godoc.org/github.com/nicksnyder/go-i18n/i18n

**Comment by jesseduffield** [comment]
To clarify: when you say you want i18n support do you mean you want all unicode characters to render properly (see https://github.com/jesseduffield/lazygit/issues/24 for issue relating to unicode characters causing display issues) or do you mean you want all the messages to be available in different languages?

**Comment by jesseduffield** [comment]
Cool :) I'll have a read over those options and get back to you

**Comment by mjarkk** [comment]
Already working on i18n support view pull request: #137  
Because of that this issue is no longer relevant  
Closing issue
