### ISSUE TITLE
Crash on setting upstream with "ambigous" name.

### ISSUE THREAD

**Issue by andrewsav-bt** [jesseduffield/lazygit#1349]
**Describe the bug**

This is somewhat related to https://github.com/jesseduffield/lazygit/issues/884 and https://github.com/jesseduffield/lazygit/issues/833. Lazygit crashes if one uses the "default" workflow of not renaming the remote branch when creating a local one from it, and then trying to set the upstream branch

**To Reproduce**

- Go to Branches Panel
- Press `]` to navigate to remotes. Press `Enter` on line with remote branch count to populate remote branches list.
- Scroll to the remote branch you want to checkout locally and press `n` and then enter. 
- Press `]`, `Enter` again, and scrol to the same remote branch as above. Press `u` and `Enter`. Observe the crash in the `Sceenshots` section below.
Update the name if needed (I prefer removing origin/ from the name. Press Enter and you have the local branch created

**Expected behavior**

At the very minimum not to crash. However, it seems that it does not make sense to have local branch that includes the "origin/" prefix of the remote branch. Everyone is deleting this "origin/" anyway.  So why not let Lazygit strip it off in the first place? It (probably) never makes sense to leave it in anyway.

As a side note, in the line editor `Home` and `End` button do not seem to work so you have to press left arrow a zillion times to get to the line beginning in order to remove the "origin/" prefix. Can we support `Home` and `End` please?

**Screenshots**
```
2021/06/03 14:10:45 An error occurred! Please create an issue at: https://github.com/jesseduffield/lazygit/issues

*errors.errorString warning: refname 'origin/feature/somebranchname' is ambiguous.
fatal: Ambiguous object name: 'origin/feature/somebranchname'.

/home/runner/work/lazygit/lazygit/pkg/commands/oscommands/os.go:296 (0xc583b8)
/home/runner/work/lazygit/lazygit/pkg/commands/oscommands/os.go:173 (0xc57111)
/home/runner/work/lazygit/lazygit/pkg/commands/git.go:233 (0xf55533)
/home/runner/work/lazygit/lazygit/pkg/commands/git.go:222 (0xfe7cf9)
/home/runner/work/lazygit/lazygit/pkg/commands/branches.go:93 (0xfe7bef)
/home/runner/work/lazygit/lazygit/pkg/gui/remote_branches_panel.go:92 (0xfe7b8e)
/home/runner/work/lazygit/lazygit/pkg/gui/confirmation_panel.go:81 (0xfdb64c)
/home/runner/work/lazygit/lazygit/pkg/gui/confirmation_panel.go:314 (0xfdbd2d)
/home/runner/work/lazygit/lazygit/vendor/github.com/jesseduffield/gocui/gui.go:1167 (0xc42a8d)
/home/runner/work/lazygit/lazygit/vendor/github.com/jesseduffield/gocui/gui.go:1135 (0xc42671)
/home/runner/work/lazygit/lazygit/vendor/github.com/jesseduffield/gocui/gui.go:1060 (0xc4244e)
/home/runner/work/lazygit/lazygit/vendor/github.com/jesseduffield/gocui/gui.go:651 (0xc404ed)
/home/runner/work/lazygit/lazygit/vendor/github.com/jesseduffield/gocui/gui.go:611 (0xc400d8)
/home/runner/work/lazygit/lazygit/pkg/gui/gui.go:540 (0xf95adb)
/home/runner/work/lazygit/lazygit/pkg/gui/gui.go:548 (0xfe2028)
/home/runner/work/lazygit/lazygit/pkg/utils/utils.go:380 (0xc4c767)
/home/runner/work/lazygit/lazygit/pkg/gui/gui.go:547 (0xf95e68)
/home/runner/work/lazygit/lazygit/pkg/app/app.go:242 (0xfff1b3)
/home/runner/work/lazygit/lazygit/main.go:127 (0x1000b5b)
/opt/hostedtoolcache/go/1.16.3/x64/src/runtime/proc.go:225 (0x9fbfd6)
/opt/hostedtoolcache/go/1.16.3/x64/src/runtime/asm_amd64.s:1371 (0xa2d701)
```

**Desktop (please complete the following information):**
 - OS: Windows
 - Lazygit Version: v0.28.1

**Comment by andrewsav-bt** [comment]
"origin/" stripping aspect has been fixed in https://github.com/jesseduffield/lazygit/commit/bc044c64b2315c3fb8c523fa0ae7ef71bcba3b31

**Comment by jesseduffield** [comment]
fixed in https://github.com/jesseduffield/lazygit/pull/1522

As for home/end, that is in motion here: https://github.com/jesseduffield/lazygit/pull/1142
