### ISSUE TITLE
lazygit chashed after merge

### ISSUE THREAD

**Issue by timsofteng** [jesseduffield/lazygit#1351]
**Describe the bug**

**To Reproduce**
I've just merged master branch into another branch. Idk how to reproduce it.

![image](https://user-images.githubusercontent.com/51912173/120644848-77d15e80-c480-11eb-9064-7e342cf9ee2a.png)

**Desktop (please complete the following information):**
 - Linux Debian testing
 - lazygit 0.28.1

**Comment by jesseduffield** [comment]
Should be fixed in v0.28.2
