### ISSUE TITLE
Support Markdown emoji

### ISSUE THREAD

**Issue by Sebclem** [jesseduffield/lazygit#1354]
**Is your feature request related to a problem? Please describe.**
I'm using a lot of markdown emoji in my commits message, but in lazygui, the emoji are not parsed.

**Describe the solution you'd like**
Replace all markdown emoji by it's Unicode equivalent in commits list.

EDIT:
I have found this [file](https://github.com/mcdee/go-markdown-emoji/blob/master/emoji.go) that can be useful

**Describe alternatives you've considered**

**Additional context**

In lazygit :
![image](https://user-images.githubusercontent.com/23737709/120847245-82205500-c573-11eb-88c2-5d594db282a9.png)

In gitlab UI:

![image](https://user-images.githubusercontent.com/23737709/120847332-a2501400-c573-11eb-887e-1a7b3116dc64.png)

**Comment by mjarkk** [comment]
Nice idea, May i add that when this gets implemented we still should have a setting to disable it as there are a lot of linux distros that don't come with emoji support out of the box

**Comment by Sebclem** [comment]
Yea adding the ability to disable parsing can also be interesting for large got repo I think

**Comment by jesseduffield** [comment]
I like the idea, and it seems simple enough to implement. The large-git-repo thing is definitely one concern I have. If our display logic had it that we only rendered the current page shown in the commits panel, it wouldn't matter how large the repo is, but currently we 'render' all the commits at once.

**Comment by mjarkk** [comment]
The PR is merged if you're building from source or once a new release is out you can enable this feature with:
```yaml
go:
  parseEmoji: true
```
