### ISSUE TITLE
ubuntu: cannot install with `go get`

### ISSUE THREAD

**Issue by jangalinski** [jesseduffield/lazygit#136]
**Describe the bug**

I try to install via `go get github.com/jesseduffield/lazygit`

but get

      package math/bits: unrecognized import path "math/bits" (import path does not begin with hostname)

**To Reproduce**

s.a.

**Expected behavior**

I would expect lazygit to be installed

**Desktop (please complete the following information):**

 - OS: Ubuntu 17.04
 - Lazygit Version latest
- go: 1.7.3

**Comment by remyabel** [comment]
Your version of [Golang is too old](https://golang.org/doc/go1.9#math-bits). Follow the [official instructions](https://github.com/golang/go/wiki/Ubuntu) on how to get a newer version.

**Comment by jangalinski** [comment]
yep, go env still showed the old versioon, thanks!
