### ISSUE TITLE
Search the full log as well

### ISSUE THREAD

**Issue by samaursa** [jesseduffield/lazygit#1362]
I realize that a search feature is already implemented in commits/local-branches/files windows, however I regularly search the main graph (with all branches). I have to use a GUI like Fork for searching and would like to avoid it and stay in lazygit.

Is there a chance of adding search to the window on the right as well?

![image](https://user-images.githubusercontent.com/817849/121751184-ac29c800-cadb-11eb-9956-3b06ae37ee54.png)

**Comment by jesseduffield** [comment]
This is now possible in v0.31 (use `<c-l>` in the commits panel to open the log menu and select the `git log --all` option). Lemme know if you have any issues :)
