### ISSUE TITLE
Switch between multiple log views

### ISSUE THREAD

**Issue by samaursa** [jesseduffield/lazygit#1363]
I use the log graph in a couple of different ways. One is to quickly see all the commits, in which case I use `oneline` with a cutoff so that many commits are displayed in the log graph in `1 -> a`. Sometimes, I need to switch back and forth between `oneline` and the default (since the default gives me a lot more default of a particular commit).

Currently, I have set the `allBranchesLogCmd` to be a particular command (e.g. oneline logs with a cutoff). But sometimes I would like to see the expanded log with full commit description, branches, files etc (i.e. the default version of `1 -> a`).

It would be great if I can press `a` repeatedly to cycle between different versions of the `allBranchesLogCmd` in the config (it can be a hard coded number e.g. `allBranchesLogCmd`, `allBranchesLogCmd_Optional1`, `allBranchesLogCmd_Optional2` just as an example).

**Comment by jesseduffield** [comment]
This sounds reasonable to me. I'm chucking a 'good first issue' label on this as it should be straightforward to implement
