### ISSUE TITLE
Option to change upstream branch

### ISSUE THREAD

**Issue by Rambhosale** [jesseduffield/lazygit#1365]
**Is your feature request related to a problem? Please describe.**
Unable to change the upstream directly from lazygit.

**Describe the solution you'd like**
An option or a shortcut to quickly change the upstream branch from a list of existing remotes, if this feature already exists can you point out how to use it?

**Describe alternatives you've considered**
Right now I change the upstream from the command

**Comment by jesseduffield** [comment]
You can change the upstream of the checked out branch by going to the remotes tab then entering a remote with 'enter' and pressing 'u' on a remote branch.

I'll close this off but lemme know if that doesn't satisfy your use case and we can reopen
