### ISSUE TITLE
Don't cd to git root after exiting lazygit

### ISSUE THREAD

**Issue by josefglatz** [jesseduffield/lazygit#1370]
It would be nice to have a decision wether the directory is changed to git root after exiting lazygit.

Is this already possible? If not, an option in the config file or via ENV would be really helpful.

**Comment by mjarkk** [comment]
What shell ar you using?  
I'm using fish and when i exit lazygit in a sub directory it doesn't cd to the repo root

**Comment by josefglatz** [comment]
zsh



Diese Nachricht wurde von meinem Smartphone versandt

**Comment by mjarkk** [comment]
I might live in the country beside Germany but that doesn't mean I can speak German 😅

**Comment by josefglatz** [comment]
Sorry this was autotext from mobilephone. The first line is essential: I use ZSH

**Comment by mjarkk** [comment]
Ah, just tested it on zsh and neither there it cd's to the root of the git repo
<img width="445" alt="image" src="https://user-images.githubusercontent.com/15320763/127300927-a1846a95-b149-4f6e-98a6-cf354476b539.png">

**Comment by mjarkk** [comment]
What version of lazygit are you running?

**Comment by josefglatz** [comment]
The problem was https://github.com/jesseduffield/lazygit#changing-directory-on-exit

I never read the snippet and thought this is necessary or very useful when using lazygit via `lg`.

Sorry for disturbing you. After removing the function all is fine...
