### ISSUE TITLE
Unstaging/Modifying parts of the last commit

### ISSUE THREAD

**Issue by chirino** [jesseduffield/lazygit#1379]
**Topic**
Sometimes I include too many changes in my last commit.  

Is there an easy way drill into the last commit and select files or parts of files and then remove them from the commit but to keep the changes in my working tree so it's available to add in the next commit?

Here's an example of being able to do something like that with GitX:

https://user-images.githubusercontent.com/103255/124408107-84f99b80-dd13-11eb-97a8-9053e497cfb5.mp4

**Comment by jesseduffield** [comment]
The way to do this is to press enter on the commit to view that commit's files and then press space on each commit to add it to a patch (or press enter again and stage line-by-line) and then when you've got the patch you want, press ctrl+p to open the patch menu and choose to pull the patch out into the index

**Comment by jesseduffield** [comment]
Closing due to staleness
