### ISSUE TITLE
Feature request: Adding possibility to push commit to reference.

### ISSUE THREAD

**Issue by lukaszgard** [jesseduffield/lazygit#138]
Right now there is only possibility to upload change to specific branch, user should have option to type   reference name and secondly once we would like to work on Gerrit* project then creating a review and uploading patch set's are made also in the same way.

In my opinion there should be a new key-binding for such operation, that will open a new window with "prompt" (like for commit msg.) for defining reference name for coming change. If am getting clear mean goal of this project, user should have already installed needed hook file used to 

I was able to implement this feature on my forked repo - https://github.com/lukaszgard/lazygit

I am new in go lang, and very glad to propose this stuff to this project.

*Creating a review is by applying a specific line into commit message and upload a commit into reference [(quick wiki how to create review in Gerrit)][1]:

[1]: https://gerrit-review.googlesource.com/Documentation/intro-gerrit-walkthrough.html

**Comment by lukaszgard** [comment]
adding "Feature request: " to topic.

**Comment by lukaszgard** [comment]
@jesseduffield may I ask about comment to this request ?

**Comment by jesseduffield** [comment]
@lukaszgard sorry for the late reply, I haven't come across Gerrit before, so I'll need to do some reading before I decide on the extent to which we'll support it. When I get the chance I'll have a look at your fork and see how complex the code is to implement :)

**Comment by lukaszgard** [comment]
Thank's @jesseduffield, so I shall wait patiently :)

**Comment by jesseduffield** [comment]
@lukaszgard it has been quite a while! Sorry it took so long to get back to you here, but I've just recently added support for custom keybindings and recalled this issue as a good candidate. Do the custom keybindings seen [here](https://github.com/jesseduffield/lazygit/wiki/Custom-Commands-Compendium) satisfy your use case?

**Comment by lukaszgard** [comment]
Hi @jesseduffield indeed this what I wanted to implement, thank's!
