### ISSUE TITLE
Add a tag _with a message_ to a commit

### ISSUE THREAD

**Issue by jbrains** [jesseduffield/lazygit#1381]
I would find it very pleasant to be able to add a message when creating a tag. I know that I can do this from the command line, but I would like to have the option of adding a message to the tag when I use the "Add tag" command.

Clearly this is (merely) a UX nicety. Perhaps this becomes a simpler feature for a new contributor to work on. I don't feel comfortable enough with golang to do it myself.

**Comment by fsmiamoto** [comment]
I think I can tackle this one!

To avoid adding an extra step for those that do not want it, I'd say we should add it as a separate keybinding e.g. `^t`.

How does it sound @jesseduffield?

**Comment by jesseduffield** [comment]
I would use the same keybinding but open a menu with the option to create a tag without and with a message. I believe its called an annotated tag when it comes with a message but not sure if that’s a well-known term.

Worth noting there are two places we can create a tag: in the commits panel and in the tags tab: I would use the same menu in both for the two different keybindings

**Comment by jesseduffield** [comment]
@nagy135 there is a PR for this in motion now: https://github.com/jesseduffield/lazygit/pull/1469.
As for pushing tags: by default we include the `--follow-tags` arg when pushing. You can also push an individual tag by pressing shift+P on that tag

**Comment by jesseduffield** [comment]
Actually now would be a good time to ask @nagy135: do you intend on having multi-line messages against these tags?

**Comment by jesseduffield** [comment]
Now that this is done, I'll close this off, and if somebody has a need for multi-line here we can have a new issue for that

**Comment by JonatasAmaral** [comment]
hey, am i missing something here?
how can i add a tag to the branch?

i've installed it from go, and can see the tags tab
but can't se any "tag" option on menu (`?` or `x`) over branch

i was expecting to hover a branch, press "t", and get a input box (just like commit)




ps. a can see the tag option on commits panel only, so there's it, i only exists there?

**Comment by mark2185** [comment]
@JonatasAmaral try going to the `Tags` tab in the `Local Branches` panel (`]` switches tabs) and pressing `n` there. That should create the tag of the currently checked out branch.

**Comment by JonatasAmaral** [comment]
thanks @mark2185, that solver my case a bit.

but i personally think it should me possible to tag the branch (any hovered one), and press "t" on it to tag.

pushing it there looks a bit harder. my first thought it "t" to tag, "T" to push the tag (maybe create & pushing)
but it would make it confuse, considering how it is done on Commits panel (as "t" used for revert, to "T" simply tag it)

should i create a new issue to suggest it?

**Comment by mark2185** [comment]
> should i create a new issue to suggest it?

There's already a [PR](https://github.com/jesseduffield/lazygit/pull/2421) meant to resolve the issue you've stumbled upon today :)
