### ISSUE TITLE
Chinese characters are not cleared after moving to the next commit / file / etc

### ISSUE THREAD

**Issue by echaya** [jesseduffield/lazygit#1383]
**Describe the bug**
Chinese characters are not cleared after moving to the next commit / file

**To Reproduce**
1. move to any file / commit that contains Chinese characters 
2. move to the next file / commit
3.  (half-width) Chinese characters are kept on the screen

**Expected behavior**
Chinese characters to be cleared when the new file / commit info is rendered

**Screenshots**
![chinese rendering](https://user-images.githubusercontent.com/34254408/125187132-abae5980-e260-11eb-8bf1-5d773ade9463.gif)

**Desktop (please complete the following information):**
 - OS: windows
 - Lazygit Version: 0.28.2
 - The last commit id if you built project from sources (run : ```git-rev parse HEAD```)

**Additional context**
- Chinese characters are working fine in my CMD. The issue seems to be is lazygit specific but different from https://github.com/jesseduffield/lazygit/issues/24

**Comment by rainsia** [comment]
I upgraded to 0.31.2, and I can report that this problem remains.

Displaying Chinese characters is totally fine, but after I scrolled the content, some lines will keep on its original position.

**Comment by jerviscui** [comment]
The same question.

**Comment by dmcslt** [comment]
same question

**Comment by FurryWolfX** [comment]
same question

**Comment by Mickychen00** [comment]
Hi, I'm still seeing incorrect characters displayed on my Windows PC when using Lazygit. However, Lazygit works fine with no errors on my Mac and Linux systems.
My Lazygit Version is 0.37.0.
![image](https://user-images.githubusercontent.com/28621570/232360160-9abb5fb5-de7f-486f-a789-58911425824c.png)
