### ISSUE TITLE
Lazygit crashes on startup with panic index out of range

### ISSUE THREAD

**Issue by kirsa** [jesseduffield/lazygit#1385]
**Describe the bug**
The following is the result of attempting to launch lazygit inside a git repo

❯ lazygit
panic: runtime error: index out of range [1] with length 1

goroutine 21 [running]:
github.com/jesseduffield/lazygit/pkg/commands.(*BranchListBuilder).obtainBranches(0xc00013f6f0, 0x0, 0x0, 0x0)
        /private/tmp/lazygit-20210605-59301-6hnv7l/lazygit-0.28.2/pkg/commands/loading_branches.go:56 +0x6c6
github.com/jesseduffield/lazygit/pkg/commands.(*BranchListBuilder).Build(0xc0000beef0, 0x0, 0x9c11778, 0x10)
        /private/tmp/lazygit-20210605-59301-6hnv7l/lazygit-0.28.2/pkg/commands/loading_branches.go:97 +0x45
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).refreshBranches(0xc0000ec000)
        /private/tmp/lazygit-20210605-59301-6hnv7l/lazygit-0.28.2/pkg/gui/branches_panel.go:71 +0xbe
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).refreshCommits.func1()
        /private/tmp/lazygit-20210605-59301-6hnv7l/lazygit-0.28.2/pkg/gui/commits_panel.go:85 +0x46
github.com/jesseduffield/lazygit/pkg/utils.Safe.func1(0x1006e75, 0xc0000704e0)
        /private/tmp/lazygit-20210605-59301-6hnv7l/lazygit-0.28.2/pkg/utils/utils.go:107 +0x24
github.com/jesseduffield/lazygit/pkg/utils.SafeWithError(0xc00013f7b8, 0x0, 0x0)
        /private/tmp/lazygit-20210605-59301-6hnv7l/lazygit-0.28.2/pkg/utils/utils.go:118 +0x62
github.com/jesseduffield/lazygit/pkg/utils.Safe(0xc0000a62d0)
        /private/tmp/lazygit-20210605-59301-6hnv7l/lazygit-0.28.2/pkg/utils/utils.go:107 +0x49
created by github.com/jesseduffield/lazygit/pkg/gui.(*Gui).refreshCommits
        /private/tmp/lazygit-20210605-59301-6hnv7l/lazygit-0.28.2/pkg/gui/commits_panel.go:82 +0xa8

System details:
OS : macOS Big Sur 11.4
Terminal : iterm2 Build 3.4.8
Git : version 2.32.0
Homebrew : 3.2.2

Updated lazygit using $homebrew upgrade lazygit

lazygit: stable 0.28.2 (bottled)
Simple terminal UI for git commands
https://github.com/jesseduffield/lazygit/
/usr/local/Cellar/lazygit/0.28.2 (5 files, 16.3MB) *
  Poured from bottle on 2021-06-05 at 17:41:04
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/lazygit.rb
License: MIT
==> Dependencies
Build: go ✔
==> Analytics
install: 1,452 (30 days), 6,520 (90 days), 28,704 (365 days)
install-on-request: 1,452 (30 days), 6,519 (90 days), 28,671 (365 days)
build-error: 0 (30 days)

**Comment by ebudan** [comment]
Similar problems on Fedora 34, both latest packaged version and source-built all the way back to lazygit 0.26. This is with a particular repository - several others seem to work fine, and this one worked fine last time I checked a couple of weeks ago. 

I'll be happy to provide more details if someone gives a hint as to what I should be looking for.

```
$ go version
go version go1.16.5 linux/amd64
$ lazygit
panic: runtime error: slice bounds out of range [:2] with length 0

goroutine 32 [running]:
github.com/jesseduffield/lazygit/pkg/commands.(*GitCommand).GetStatusFiles(0xc000097b00, 0x0, 0x0, 0x0, 0x0)
	/builddir/build/BUILD/lazygit-0.28.2/pkg/commands/loading_files.go:39 +0xa8b
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).refreshStateFiles(0xc0000f01c0, 0x0, 0x0)
	/builddir/build/BUILD/lazygit-0.28.2/pkg/gui/files_panel.go:525 +0xb5
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).refreshFilesAndSubmodules(0xc0000f01c0, 0x0, 0x0)
	/builddir/build/BUILD/lazygit-0.28.2/pkg/gui/files_panel.go:112 +0xd4
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).refreshSidePanels.func1.2.1()
	/builddir/build/BUILD/lazygit-0.28.2/pkg/gui/view_helpers.go:129 +0x2a
github.com/jesseduffield/lazygit/pkg/utils.Safe.func1(0x0, 0x0)
	/builddir/build/BUILD/lazygit-0.28.2/pkg/utils/utils.go:107 +0x24
github.com/jesseduffield/lazygit/pkg/utils.SafeWithError(0xc00044a7b8, 0x0, 0x0)
	/builddir/build/BUILD/lazygit-0.28.2/pkg/utils/utils.go:118 +0x62
github.com/jesseduffield/lazygit/pkg/utils.Safe(0xc0004846a0)
	/builddir/build/BUILD/lazygit-0.28.2/pkg/utils/utils.go:107 +0x49
created by github.com/jesseduffield/lazygit/pkg/gui.(*Gui).refreshSidePanels.func1.2
	/builddir/build/BUILD/lazygit-0.28.2/pkg/gui/view_helpers.go:129 +0x77
```

BTW running lazygit in a non-repository dir and answering N results in the same:

```
$ lazygit
Not in a git repository. Create a new git repository? (y/n): n
panic: runtime error: slice bounds out of range [:2] with length 0

goroutine 42 [running]:
github.com/jesseduffield/lazygit/pkg/commands.(*GitCommand).GetStatusFiles(0xc000181ce0, 0x0, 0x0, 0x0, 0x0)
	/builddir/build/BUILD/lazygit-0.28.2/pkg/commands/loading_files.go:39 +0xa8b
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).refreshStateFiles(0xc0001c21c0, 0x0, 0x0)
	/builddir/build/BUILD/lazygit-0.28.2/pkg/gui/files_panel.go:525 +0xb5
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).refreshFilesAndSubmodules(0xc0001c21c0, 0x0, 0x0)
	/builddir/build/BUILD/lazygit-0.28.2/pkg/gui/files_panel.go:112 +0xd4
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).refreshSidePanels.func1.2.1()
	/builddir/build/BUILD/lazygit-0.28.2/pkg/gui/view_helpers.go:129 +0x2a
github.com/jesseduffield/lazygit/pkg/utils.Safe.func1(0x0, 0x0)
	/builddir/build/BUILD/lazygit-0.28.2/pkg/utils/utils.go:107 +0x24
github.com/jesseduffield/lazygit/pkg/utils.SafeWithError(0xc0000e2fb8, 0x0, 0x0)
	/builddir/build/BUILD/lazygit-0.28.2/pkg/utils/utils.go:118 +0x62
github.com/jesseduffield/lazygit/pkg/utils.Safe(0xc00044bf30)
	/builddir/build/BUILD/lazygit-0.28.2/pkg/utils/utils.go:107 +0x49
created by github.com/jesseduffield/lazygit/pkg/gui.(*Gui).refreshSidePanels.func1.2
	/builddir/build/BUILD/lazygit-0.28.2/pkg/gui/view_helpers.go:129 +0x77
```

**Comment by mjarkk** [comment]
@kirsa can you show me what the output of the following command is in the same repo?
```
git for-each-ref --sort=-committerdate --format="%(HEAD)|%(refname:short)|%(upstream:short)|%(upstream:track)" refs/heads
```

**Comment by ebudan** [comment]
Found the reason for my particular case: there were programmatically generated files with a trailing linefeed in the file name (bug), and that confused the `git status` line splitting logic. Those probably got generated running some tests before the buggy linefeed was fixed. 

Not a lazygit bug per se, and probably not the same bug as the original on this page. (Maybe a file name safety scan would be useful, but not sure if the effort is worth the once in a blue moon occurrence.)

**Comment by mjarkk** [comment]
@ebudan Ah, the way lg is build i'm not sure if we can fix those problems.
I've tried to add an extra check in #1392 would you like to check that one out to see if it doesn't panic with your files?

**Comment by ebudan** [comment]
I'll confirm your fix will survive the silly file names. It will, however, only show `foo` once in the following situation:
```
$ git status --untracked-files=all --porcelain --no-renames
?? foo
?? "foo\n"
```
We should only be getting empty entries if a filename is malformed. Since no-one should be making names like this, would it be better to log a warning about a bad filename and exit? That would give a bit of a hint to anyone making a mistake.

**Comment by mjarkk** [comment]
> We should only be getting empty entries if a filename is malformed. Since no-one should be making names like this, would it be better to log a warning about a bad filename and exit? That would give a bit of a hint to anyone making a mistake.

Good point,  
From your output and a quick local test it seems like git wraps the wired filename in "" so it's probably possible possible to detect that and at least show a warning the application might be unstable with such files.

**Comment by ebudan** [comment]
@kirsa can you run the following command in the repo causing problems and paste the output?

```
git for-each-ref --sort=-committerdate --format="%(HEAD)|%(refname:short)|%(upstream:short)|%(upstream:track)" refs/heads
```
Looks like somehow the formatted string lazygit is receiving doesn't contain the | separators.

**Comment by ebudan** [comment]
@mjarkk let's move further discussion of loading_files.go to #1392?

**Comment by ebudan** [comment]
> From your output and a quick local test it seems like git wraps the wired filename in "" so it's probably possible possible to detect that and at least show a warning the application might be unstable with such files.

Tested quickly -  OSCommand.Run...() or some deeper call is filtering those quotes away, looks like this won't help.

**Comment by kirsa** [comment]
@mjarkk Thanks for looking into this.

Here is the result.
❯ git for-each-ref --sort=-committerdate --format="%(HEAD)|%(refname:short)|%(upstream:short)|%(upstream:track)" refs/heads

warning: ignoring ref with broken name refs/heads/main 2
*|main|origin/main|

**Comment by mjarkk** [comment]
Tried to simulate my env as closely to @kirsa 's but lazygit still works fine so i presume there is something special going on with the repo lazygit was opened in.

This is as close as i could get matching the authors system details:
OS : macOS Big Sur 11.4
Terminal : iterm2 Build 3.4.8
Git : version 2.32.0
Homebrew : 3.2.3-59-gb18bbac (not equal to autor)

**Comment by kirsa** [comment]
@mjarkk thanks for trying it out. Trying out lazygit in different repos works so I think it's just an issue with the repo I opened it in. Closing this issue.

**Comment by ebudan** [comment]
> ❯ git for-each-ref --sort=-committerdate --format="%(HEAD)|%(refname:short)|%(upstream:short)|%(upstream:track)" refs/heads
> 
> warning: ignoring ref with broken name refs/heads/main 2
> *|main|origin/main|

OK, so if I'm not reading that wrong, there's a branch name with a space, which confuses git, and the error confuses lazygit. (I haven't encountered broken repo names, anyone more familiar with that warning feel free to correct.)

I'll open a new minor bug that summarizes the issue and refers here. Ideally lazygit would inform the user of parsing inconsistency, but at least a record will inform the random user encountering this type of problem.

**Comment by mjarkk** [comment]
@ebudan opened #1396, that should at least fix the panic
