### ISSUE TITLE
$EDITOR opens with empty COMMIT_EDITMSG buffer upon confirming commit message

### ISSUE THREAD

**Issue by martinklepsch** [jesseduffield/lazygit#139]
With some staged changes I hit <kbd>c</kbd> and enter a message. After confirming with <kbd>RET</kbd> my `$EDITOR` opens as if I had typed `git commit` in a terminal window.

I would have expected that the commit is made with the specified commit message without my editor being opened.

**Screenshots**

Asciinema recording: https://asciinema.org/a/WiQmQzUlyfV6CZa8UiZGi55v6

**Desktop**
 - OS: Mac High Sierra
- Lazygit Version: `commit=1354885db06d72607145836d77a912882ed1bcc3, build date=2018-08-12T13:20:22Z, version=0.1.55`

**Comment by remyabel** [comment]
What editor are you using? Are you using MacVim? By default, MacVim will detach and confuse git. Try adding the ``-f`` switch to make sure it doesn't detach.

**Comment by jesseduffield** [comment]
@martinklepsch this should be fixed in the current master branch. Are you able to pull that down and give it a test?

**Comment by martinklepsch** [comment]
> What editor are you using? Are you using MacVim?

Using standard Vim as shipped with Mac OS.

> Are you able to pull that down and give it a test?

I don't have Go installed, is there a way I could download a binary release from somewhere? 

Thanks for the help!

**Comment by jesseduffield** [comment]
@martinklepsch thanks for your patience! I've just pushed a new [release](https://github.com/jesseduffield/lazygit/releases/tag/v0.1.57) that should fix your issue. If it doesn't, let me know and we can jump into more troubleshooting

**Comment by martinklepsch** [comment]
Works! Thanks a bunch for the excellent support and the time and effort you spent on this project ❤️
