### ISSUE TITLE
With Ubuntu PPA deprecated, what is the best way to install on Ubuntu?

### ISSUE THREAD

**Issue by carstengehling** [jesseduffield/lazygit#1399]
I just saw, that the Ubuntu PPA has been deprecated, and indeed the latest release is not available through PPA.

So I just want to know, when running Ubuntu (or Mint) what is the preferred way to install Lazygit and automatically receive updates from now on?

**Comment by mjarkk** [comment]
Quoting @dawidd6 from https://github.com/jesseduffield/lazygit/issues/1248#issuecomment-817279859

> Actually scratch that, I'm going to deprecate the PPA. Users can now get lazygit from Homebrew on Linux easily. It's too much hassle to maintain the Debian packages. I'll try to build last packages and then I'm out. If someone wants to step up as a maintainer, I'll happily pass the torch.

**Comment by dawidd6** [comment]
Use Homebrew. It runs on Linux too.

**Comment by carstengehling** [comment]
Oh nice, I didn't know that. Thank you.

**Comment by x86dev** [comment]
FWIW, this is a one-liner which takes care of downloading and installing latest lazygit to /usr/local/bin (CURL required), as I'm not too keen on having yet another package manager like brew on my system:

`MY_FLAVOR=Linux_x86_64; curl -s -L $(curl -s https://api.github.com/repos/jesseduffield/lazygit/releases/latest | grep browser_download_url | cut -d '"' -f 4 | grep -i "$MY_FLAVOR") | sudo tar xzf - -C /usr/local/bin lazygit`

Tweak this to your likings, hope this helps -- might be worth adding to the README if it's helpful.

**Comment by ChrisMcD1** [comment]
The Ubuntu PPA was deprecated, removed, but now a new install set of instructions are back!

https://github.com/jesseduffield/lazygit/pull/4501
