### ISSUE TITLE
Homebrew formula

### ISSUE THREAD

**Issue by pshirshov** [jesseduffield/lazygit#14]
Hi, it would be great to have this available in homebrew main tree or as a tap.

**Comment by jesseduffield** [comment]
those upvotes tell me there is definitely a demand for this :) I've never worked with homebrew before so I'll need to do some reading on how to hook it all up, but if somebody wants to beat me to the punch and put up a PR please feel free!

**Comment by jesseduffield** [comment]
@pshirshov I'm using Goreleaser which currently doesn't support the homebrew main tree, but we are (*drumroll*) LIVE with a tap:
```
brew tap jesseduffield/lazygit
brew install lazygit
```

**Comment by pshirshov** [comment]
This is awesome! Thank you guys!
