### ISSUE TITLE
Quitting lazygit completely deletes cursor in bash shell, gives error in cmd

### ISSUE THREAD

**Issue by SentientCoffee** [jesseduffield/lazygit#1404]
**Describe the bug**
When using lazygit in a bash shell (such as the one that comes with the Git for Window installation), once lazygit is exited, the bash does not have a cursor anymore, making it near impossible to use the bash terminal normally after using lazygit.

When exiting from a cmd prompt, that functions normally (at least using the Cmder shell with ConEmu backend), but it gives a message saying "cannot kill child process" once it exits

**To Reproduce**
Bash:
1. Open lazygit in a bash shell
2. Perform any operations you want if inside a repo (optional)
3. Exit lazygit
4. Bash should not have a visible cursor anymore, although typing is still possible

Cmd:
1. Open lazygit in a bash shell
2. Perform any operations you want if inside a repo (optional)
3. Exit lazygit
4. See message: "cannot kill child process" before seeing normal prompt

**Expected behavior**
Lazygit should exit gracefully and not mess with my bash shell, forcing me to restart it.

**Screenshots**
Bash before opening lazygit (visible cursor):
![image](https://user-images.githubusercontent.com/22991229/127225966-6a9c7f75-7df8-4d1f-86aa-9555d7eb7ebe.png)

Opening lazygit:
![image](https://user-images.githubusercontent.com/22991229/127226053-97f4302a-11cd-46a8-9bba-46cd5eeef4d9.png)
![image](https://user-images.githubusercontent.com/22991229/127226080-226ef34c-ef80-47b1-9eb2-3e91c3b5dfcd.png)
![image](https://user-images.githubusercontent.com/22991229/127226130-e76f8d58-053f-4039-9398-8834d043afb4.png)

After closing lazygit (no cursor):
![image](https://user-images.githubusercontent.com/22991229/127226192-bb6a17be-9260-4b26-9e35-914876d81db5.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Lazygit version v0.28.2

**Comment by SentientCoffee** [comment]
Closing, fixed in latest release (0.29)

**Comment by willparsons** [comment]
I'm having this issue in 0.34.

**Comment by willparsons** [comment]
I just tested and my cursor disappears on both v0.29 and v0.34

**Comment by willparsons** [comment]
If it helps it's the mintty terminal.
