### ISSUE TITLE
Order remote branches by date of last commit

### ISSUE THREAD

**Issue by jkogler-cloudflight** [jesseduffield/lazygit#1412]
**Is your feature request related to a problem? Please describe.**
In our company we have way too many branches remotely. Basically everybody creates new ones for every PR, and most of the time the branches don't get deleted afterwards.
That makes it very hard to check out a remote branch with lazygit, as I have to search for it. Need to know the exact PR number, ...

**Describe the solution you'd like**
I would like that the remote branches are ordered by the date of their last commit, and not alphabetically (similar to the local branches (although they are sorted by last checkout, not by last commit).
Or at least I would like to have the option to enable such a sorting.

**Describe alternatives you've considered**
I know the best solution would be that my team enforces a delete-branch-after-merge policy, but I would still appreciate this feature. Not sure if everybody can enforce it, and that still leaves all he stall branches that don't get merged.

**Additional context**

**Comment by jesseduffield** [comment]
Sounds a lot like my company haha. This sounds like a sensible change to me. I wonder if it's expensive to grab the last commit date for each remote branch, but I suspect it's not.

**Comment by apaatsio** [comment]
A simple solution is to replace the git command in:

https://github.com/jesseduffield/lazygit/blob/f4011643dda14c6da522dcd172b66b2d2cadb02b/pkg/commands/loaders/remotes.go#L34

with

`"git for-each-ref --sort=-authordate refs/remotes --format=\"%(refname:lstrip=2)\""`
