### ISSUE TITLE
panic: non-positive interval for NewTicker

### ISSUE THREAD

**Issue by geins** [jesseduffield/lazygit#1417]
**Describe the bug**
Since a few weeks (without updating lazygit itself), I get the following error when starting lazygit from the shell:

panic: non-positive interval for NewTicker

goroutine 11 [running]:
time.NewTicker(0x0, 0x0)
	/opt/homebrew/Cellar/go/1.16.4/libexec/src/time/tick.go:24 +0x144
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).goEvery.func1()
	/private/tmp/lazygit-20210604-23703-e7fn5f/lazygit-0.28.2/pkg/gui/gui.go:697 +0x4c
github.com/jesseduffield/lazygit/pkg/utils.Safe.func1(0x0, 0x0)
	/private/tmp/lazygit-20210604-23703-e7fn5f/lazygit-0.28.2/pkg/utils/utils.go:107 +0x28
github.com/jesseduffield/lazygit/pkg/utils.SafeWithError(0x140002727b8, 0x0, 0x0)
	/private/tmp/lazygit-20210604-23703-e7fn5f/lazygit-0.28.2/pkg/utils/utils.go:118 +0x5c
github.com/jesseduffield/lazygit/pkg/utils.Safe(0x14000079050)
	/private/tmp/lazygit-20210604-23703-e7fn5f/lazygit-0.28.2/pkg/utils/utils.go:107 +0x40
created by github.com/jesseduffield/lazygit/pkg/gui.(*Gui).goEvery
	/private/tmp/lazygit-20210604-23703-e7fn5f/lazygit-0.28.2/pkg/gui/gui.go:696 +0x88

**Desktop (please complete the following information):**
 - OS: OSX 11.5.1, M1 Macbook Pro, Homebrew
 - Lazygit Version 0.28.2 via homebrew

Thank You for your help!

**Comment by mjarkk** [comment]
Can you share your lazygit config?

**Comment by geins** [comment]
Thank You, you pointed me to the right direction:

I changed:

```
refreshInterval: 0 #10 # file/submodule refresh interval in seconds
fetchInterval: 0 #60 # re-fetch interval in seconds
```

Changing these back to 10 and 60 did the trick.

Best regards, 
Ralf.

**Comment by mjarkk** [comment]
Great you fixed the problem and thanks for pointing out the fields that where the problem.
What did you expect to happen when you set your config to 0?, i'm thinking of 2 things that could happen:
- Fallback to the default value if 0 is set
- Disable this interval

**Comment by geins** [comment]
I was having problems when reviewing code changes. The viewport jumps to the top of the page when time interval of refresh is reached. I tried to disable automatic refresh completely.

**Comment by henkworks** [comment]
I also want to disable automatic refresh completely. @jesseduffield please implement this so 0 means to disable it.
I’m not using lazygit yet because of this. I just hate when automatically run things want to use my ssh key and a windows pops up on my screen asking me to unlock it without me having any context what it will be used for.
Thanks!

**Comment by moha-gh** [comment]
@henkworks Auto fetching can be disabled by setting the `autoFetch` option in the config file to `false`.

```
git:                                                                                                
  autoFetch: false
```
@jesseduffield Would it make sense to check whether `fetchInterval` is not `0` (when `autoFetch` is `true`) before enabling the background fetch? Also, I could have a go at implementing support to disable the file refresh via `refreshInterval: 0` if you think that's a good idea.

**Comment by henkworks** [comment]
> @henkworks Auto fetching can be disabled by setting the `autoFetch` option in the config file to `false`.
> 
> ```
> git:                                                                                                
>   autoFetch: false
> ```

Thank you very much, that helps with my main concern!

The issue this bug is about is still present with that setting though, as long as the following is in the config, it seems:
```
refresher:
  refreshInterval: 0
```
produces:
```
± ~/go/bin/lazygit
panic: non-positive interval for NewTicker

goroutine 18 [running]:
time.NewTicker(0x0, 0x4db02f)
        /usr/lib/go-1.15/src/time/tick.go:23 +0x151
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).goEvery.func1()
        /home/henk/Data/public/software/lazygit/pkg/gui/gui.go:692 +0x67
github.com/jesseduffield/lazygit/pkg/utils.Safe.func1(0xc0001e6840, 0xc0000437b0)
        /home/henk/Data/public/software/lazygit/pkg/utils/utils.go:95 +0x24
github.com/jesseduffield/lazygit/pkg/utils.SafeWithError(0xc0000437b8, 0x0, 0x0)
        /home/henk/Data/public/software/lazygit/pkg/utils/utils.go:106 +0x62
github.com/jesseduffield/lazygit/pkg/utils.Safe(0xc000090600)
        /home/henk/Data/public/software/lazygit/pkg/utils/utils.go:95 +0x49
created by github.com/jesseduffield/lazygit/pkg/gui.(*Gui).goEvery
        /home/henk/Data/public/software/lazygit/pkg/gui/gui.go:691 +0x8a
[2]    1585044 exit 2     ~/go/bin/lazygit
```

**Comment by jesseduffield** [comment]
@moha-gh Using zero to mean 'never' isn't directly obvious, however I don't think we can use `false` in a field that's meant to be a number. So if we document it properly then I think zero is good enough.

**Comment by jesseduffield** [comment]
actually how about we add an 'autoRefresh' key similar to 'autoFetch'? That would be far more explicit

**Comment by moha-gh** [comment]
@jesseduffield @henkworks I've created a PR that adds the new `autoRefresh` config option and also ensures that we don't crash anymore if somebody configures non-positive intervals.
