### ISSUE TITLE
Serious bug

### ISSUE THREAD

**Issue by brandoncc** [jesseduffield/lazygit#1422]
I think there is a serious bug in lazygit. I don't know how to reproduce it, and I'm honestly too stressed out to even try to figure it out. Periodically when I push a feature branch lazygit will tell me that my branch has diverged and ask if I want to force push. For the first time, I said yes today. That was a huge mistake. I had a feature branch checked out and it force pushed MASTER. Thankfully I can retrace my steps using my CI/CD history to rebuild all of the stuff I just lost from master.

**Comment by brandoncc** [comment]
By the way, I'm on MacOS Big Sur 11.4.

**Comment by jesseduffield** [comment]
I'm not sure what could have happened here. Lazygit doesn't actually ever use the `--force` flag when pushing, it instead uses `--force-with-lease`, so if there was some bug that made it push to master, it shouldn't have removed any commits from master.

Some questions from me:
1) Do you know which lazygit version you were using?
2) Is there any chance you had commands being logged (either via the command log panel or by passing the `-debug` flag to lazygit?). The command log isn't persisted between sessions but if you leave lazygit open always it should still be there.
3) What was the change that was applied to the master branch? Did you feature branch's commits end up on the master branch? Did the master branch lose commits or just receive new ones?

**Comment by jesseduffield** [comment]
Another few questions if you've got the time:
4. Did you expect the 'force' option to come up? It should only come up when your branch is missing commits that are on the remote branch. If your branch wasn't missing anything (meaning e.g. you hadn't done any rebasing), this suggests you were checked out on master and somehow pushed the commits of the feature branch.
5. If you haven't since made any local changes to your master branch, does your local master branch look okay? Does it have any commits from the feature branch on it? I'm wondering if it's possible it was reset to your feature branch. (looking at your reflog could also help confirm this)
6. You said this was your first time doing the 'force' option from lazygit. Do you ever force push from the command line? If so, have you ever seen a similar issue there?
7. Is your feature branch tracking the remote master branch? (running `git status` with the feature branch checked out should tell you)
8. If you look at `.git/config` and `~/.gitconfig` can you see master mentioned anywhere?
9. what does `git config --global push.default` return?

**Comment by brandoncc** [comment]
Hi Jesse,

Sorry for the delay. Fortunately, I was able to recover the lost commits.

I think I have identified what happened:

1. Local master branch matched origin/master
2. A new feature branch was created from master (using n key)
3. Commits were added to the feature branch
4. A pull request was opened on Github
5. A second new feature branch was opened using the n key on the master branch again
6. The pull request on Github was merged into origin/master
7. Commits were added to the second feature branch locally
8. I had the second feature branch checked out
9. I used "P" to push
10. I was given a message saying that my branch had diverged, and asked if I wanted to force push

I'm pretty sure these are the steps to reproduce what happened to me. I think what I considered a bug might actually be a fundamental misunderstanding about how lazygit works. It seems to me that when I push, lazygit must be pushing all of my local branches? I definitely don't want that. I only want to push the checked-out branch. Am I on the right track about what happened? Is there a way to stop the pushing of non-checked-out branches?

------

> I'm not sure what could have happened here. Lazygit doesn't actually ever use the --force flag when pushing, it instead uses --force-with-lease, so if there was some bug that made it push to master, the change should have been rejected (unless you were the last person to push to master yourself).

I was the last person to push to master.

> Do you know which lazygit version you were using?

0.27.4

> Is there any chance you had commands being logged (either via the command log panel or by passing the -debug flag to lazygit?). The command log isn't persisted between sessions but if you leave lazygit open always it should still be there.

No, I didn't have that turned on

> What was the change that was applied to the master branch? Did your feature branch's commits end up on the master branch? Did the master branch lose commits or just receive new ones?

I lost two merged pull requests that consisted of something like six commits total. Fortunately, I still had the merged feature branches locally so I was able to merge them into master again. None of the commits from the feature branch were pushed to origin/master. origin/master was made to match local master, and origin/add-vwo-goals was created with the commits in local add-vwo-goals (which was checked out).

> Did you expect the 'force' option to come up? It should only come up when your branch is missing commits that are on the remote branch. If your branch wasn't missing anything (meaning e.g. you hadn't done any rebasing), this suggests you were checked out on master and somehow pushed the commits of the feature branch.

I would expect the force option to come up if my feature branch had deviated, but it really hadn't. origin/master had more commits than the local master branch that tracked it and the feature branch had been created from, but that is all.

> If you haven't since made any local changes to your master branch, does your local master branch look okay? Does it have any commits from the feature branch on it? I'm wondering if it's possible it was reset to your feature branch. (looking at your reflog could also help confirm this)

origin/master was made to match the local master branch. origin/master was originally ahead of local master and the feature request.

> You said this was your first time doing the 'force' option from lazygit. Do you ever force push from the command line? If so, have you ever seen a similar issue there?

I have said yes to force pushing using lazygit in situations where I expected the prompt, but this was the first time that I had said yes when I was on a branch that hadn't deviated. I figured the force would be a no-op since it hadn't deviated...boy was I wrong!

> Is your feature branch tracking the remote master branch? (running git status with the feature branch checked out should tell you)

Here is the `git status` output for the branch I was on:

```
On branch add-vwo-goals
Your branch is up to date with 'origin/add-vwo-goals'.

Cherry-pick currently in progress.
  (run "git cherry-pick --continue" to continue)
  (use "git cherry-pick --skip" to skip this patch)
  (use "git cherry-pick --abort" to cancel the cherry-pick operation)

nothing to commit, working tree clean
``` 

I think you might be onto something here though I believe this "bug" only happens when I am pushing a branch for the first time. I just created a new feature branch that is not tracking a remote, just as the feature branch from the other day would have been. Here is the output for that:

```
On branch test-feature-branch
Cherry-pick currently in progress.
  (run "git cherry-pick --continue" to continue)
  (use "git cherry-pick --skip" to skip this patch)
  (use "git cherry-pick --abort" to cancel the cherry-pick operation)

nothing to commit, working tree clean
```

Maybe since it doesn't track a branch, all of the branches got pushed when I pressed "P"?

> If you look at .git/config and ~/.gitconfig can you see master mentioned anywhere?

This is in `.git/config`:

```
[branch "master"]
	remote = origin
	merge = refs/heads/master
...
[gitflow "branch"]
	master = master
	develop = master
```

I think gitflow is from Tower. I wonder if that caused it?

This was in `~/.gitconfig` until recently...I'm not sure if it was in there on the day of the issue:

```
[init]
	defaultBranch = master
```

> what does git config --global push.default return?

"matching"

---

Thank you for taking the time to dig into this. I hope my answers helped you. I'm very curious to see what your response is!

**Comment by brandoncc** [comment]
Here is a screenshot of it happening again:

![image](https://user-images.githubusercontent.com/543973/128823829-51d76d36-c311-4518-ad2c-4c04620b9b79.png)

You can see I'm on a feature branch and my local master branch is two commits behind... "P" is trying to push both my feature branch (which it did fine even when I hit escape when told I had diverged) and master. That is not what I want at all!

**Comment by brandoncc** [comment]
This continues to happen to me every day. Is there a solution?

**Comment by jesseduffield** [comment]
@brandoncc sorry for the delay: it looks like having push.default set to 'matching' means that you will indeed be pushing more than just the current branch. See https://git-scm.com/docs/git-push#Documentation/git-push.txt---force:

> Note that --force applies to all the refs that are pushed, hence using it with push.default set to matching or with multiple push destinations configured with remote.*.push may overwrite refs other than the current branch (including local refs that are strictly behind their remote counterpart). To force a push to only one branch, use a + in front of the refspec to push (e.g git push origin +master to force a push to the master branch). See the <refspec>... section above for details.

Lazygit just says `git push` and `git push --force` (i.e. it does not specify the current branch). This mimics how it would typically be used on the command line (to my understanding at least).

I hesitate to change this behaviour to only target the checked out branch because other users may depend on lazygit pushing any matching branches if that's what is configured in their git config. In general I try to keep lazygit as close to the CLI as possible which means honouring the gitconfig.

So you can resolve this issue by going `git config --global push.default current`, but I'm open to the argument that lazygit should hard code the behaviour. Lemme know your thoughts :)

**Comment by brandoncc** [comment]
Thank you for your response, Jesse. I didn't realize matching would push all branches. I have changed the default and I'm sure I'll go on happily now. I do not think you should make lazygit hard code the behavior, as it is configurable anyway. I always specify the remote and branch when I type out a push command, so I bet that is why it seemed so odd to me.

Thank you again for your time, I really enjoy using lazygit.

**Comment by jesseduffield** [comment]
No worries, and thanks for your patience with my responses!
