### ISSUE TITLE
Can't update submodule whose file path contains spaces

### ISSUE THREAD

**Issue by jbrains** [jesseduffield/lazygit#1436]
**Describe the bug**
I have a submodule located along a path that contains spaces in the name. I can neither enter the submodule nor update it. The error message makes it pretty clear that the problem is not escaping the spaces in the pathname.

**To Reproduce**
1. Create a repository with directory containing spaces in the name, then add a submodule inside that directory.
2. Go to the "Submodules" tab in lazygit.
3. Press `ENTER` and see nothing happen.
4. Press `u` and see an error message about pathspec not matching anything found in git.

**Expected behavior**
We should be able to enter/update the submodule.

**Screenshots**
https://user-images.githubusercontent.com/61505/129493404-f7ff1888-286c-453f-a695-4df696c8fb12.mp4

**Desktop (please complete the following information):**
 - OS: Pop!_OS 21.04
 - The last commit id if you built project from sources: a2ee52142c2fe28b10d8ff5985dfd7d973a25a83

**Comment by mjarkk** [comment]
@jbrains the problem should now be fixed.  
Would you like to checkout the latest master to see if your problem still exists?

**Comment by jbrains** [comment]
@mjarkk Thank you!

Good news: this works.

Bad news: now "view reset options... > nuke working tree" exhibits exactly the same problem.

**Comment by mjarkk** [comment]
@jbrains your second point should now be fixed.
Also @Ryooooooga fixed the bugs so you should thank him instead :)
