### ISSUE TITLE
中文的Commit信息显示不完整

### ISSUE THREAD

**Issue by 0fisher** [jesseduffield/lazygit#144]
**Describe the bug**
在Mac OSX 上，安装了lazygit
cd git目录
直接运行lazygit 打开窗口后，显示的commit message 不完整。

**To Reproduce**
1. Go to 'git目录'
2. See error

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/42238173/44071016-6c805656-9fb9-11e8-8719-c9ff73871d93.png)

**Desktop (please complete the following information):**
 - OS: Mac OSX(10.13.6 )
 - Lazygit Version 0.1.55

**Additional context**

**Comment by ponsfrilus** [comment]
See #24

**Comment by 0fisher** [comment]
Good
