### ISSUE TITLE
The commits pannel does not show any commits

### ISSUE THREAD

**Issue by jaredyam** [jesseduffield/lazygit#1441]
**To Reproduce**
1. Download the most new binary release: lazygit_0.28.2_Linux_x86_64.tar.gz
2. Move the binary to an executable path `/usr/local/bin`
4. The Commits pannel doesnt show any commits but the other pannels work properly

**Desktop (please complete the following information):**
 - OS: Ubuntu16.04
 - Lazygit Version: 0.28.2 binary release

**Comment by mjarkk** [comment]
Would you like to try out the latest code in the master branch?

**Comment by lixiaoquan** [comment]
I run into similar issue when I use default git in ubuntu 16.04, but a newer git works fine.

**Comment by jaredyam** [comment]
@lixiaoquan
Thanks for your reply. After I upgraded the git, the issue was indeed solved.
