### ISSUE TITLE
OpenBSD Binary Support

### ISSUE THREAD

**Issue by ralphee** [jesseduffield/lazygit#1442]
Hey J,
was just wondering if you would consider supporting a binary for openbsd?

**Comment by mjarkk** [comment]
Can you build the lazygit binary from source?, if so we can maybe easily support openbsd in every release

**Comment by ralphee** [comment]
> Can you build the lazygit binary from source?, if so we can maybe easily support openbsd in every release

ahhh great! `go get github.com/jesseduffield/lazygit` did the trick

**Comment by ralphee** [comment]
> Can you build the lazygit binary from source?, if so we can maybe easily support openbsd in every release

bump
