### ISSUE TITLE
How to manually change the language setting?

### ISSUE THREAD

**Issue by AlexCZhou** [jesseduffield/lazygit#1444]
I think lazygit chooses my system language automatically. But it looks like this after I closing the menu:

![image](https://user-images.githubusercontent.com/33609801/129826403-e18d74ca-8831-4f51-8b3c-581e37b526c5.png)

Maybe I can avoid this by switching the language to English. But how to manually change the language setting? I have read the [User Config](https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md) but there is no answer.

**Comment by Ryooooooga** [comment]
Lazygit uses `jibber_jabber.DetectLanguage` to detect language,

https://github.com/jesseduffield/lazygit/blob/0aad68acf0b62ef0485508b52ee48b8fc8d3a071/pkg/i18n/i18n.go#L19

and, on Windows, it calls `GetUserDefaultLocaleName` or `GetSystemDefaultLocaleName` internally.

https://github.com/jesseduffield/lazygit/blob/2eeff1257b883898609015ba891e8869578957e7/vendor/github.com/cloudfoundry/jibber_jabber/jibber_jabber_windows.go#L79-L82

So, it is currently difficult to switch languages on Windows. (*nix can be done with `LANG` environment variable)

@jesseduffield How about adding a "lang" setting to the config?

**Comment by jesseduffield** [comment]
@Ryooooooga I'm fine with adding a language key to the config
