### ISSUE TITLE
git push / pull breaks when asked for username / password

### ISSUE THREAD

**Issue by mjarkk** [jesseduffield/lazygit#145]
**Describe the bug**
Hangs when inside the git config the git username is saved and password is NOT (cache time is over)

**To Reproduce**
1. `$ git config credential.helper store`
2. `$ git config credential.helper cache 1`
3. Try to push something using lazygit

**Expected behavior**
No program hang

**Screenshots**
![screenshot from 2018-08-14 21-08-02](https://user-images.githubusercontent.com/15320763/44112811-7175d6a2-a006-11e8-9fbb-6f94f73c7baf.png)

**Desktop (please complete the following information):**
 - OS: Linux (fedora 4.17.12-200.fc28.x86_64)
 - Shell: bash
 - Lazygit v0.1.59

**Comment by jesseduffield** [comment]
@mjarkk currently we currently have a pattern for switching to a subprocess when we're going to be asked for a password. We do this with committing when you have gpgsigning enabled. If we can find a way ahead of time to know whether a password will be asked for (i.e. if the expiration is up), we can switch to a `git pull` subprocess where the password can be entered. Obviously it would be better to support entering a password inside the app but I haven't found a way to make that work yet.

Do you know how we'd be able to know ahead of time whether the password will be asked for?
Maybe this could help us out https://git-scm.com/docs/git-credential

**Comment by remyabel** [comment]
This is a similar issue to #81. What happens is git will first try to use the configured [ASKPASS program](https://github.com/git/git/blob/e629a7d28a405e48fae6b064a781a10e885159fc/prompt.c#L8), i.e the GUI. If you click cancel, it will then fallback to a [terminal prompt](https://github.com/git/git/blob/26e47e261e969491ad4e3b6c298450c061749c9e/credential.c#L115). When not running `git push` in a subprocess, you get the behavior demonstrated above. But now you run into two other issues:

- If you enter invalid credentials, the error will be spit to the terminal, and not inside lazygit

- If you press CTRL+C, it will exit lazygit as well

For reference, this is my code:

```diff
diff --git a/pkg/commands/git.go b/pkg/commands/git.go
index 44fd57f..55cfb41 100644
--- a/pkg/commands/git.go
+++ b/pkg/commands/git.go
@@ -270,8 +270,9 @@ func (c *GitCommand) Pull() error {
 }
 
 // Push push to a branch
-func (c *GitCommand) Push(branchName string) error {
-       return c.OSCommand.RunCommand("git push -u origin " + branchName)
+func (c *GitCommand) Push(branchName string) (*exec.Cmd, error) {
+       command := "git push -u origin " + c.OSCommand.Quote(branchName)
+       return c.OSCommand.PrepareSubProcess(c.OSCommand.Platform.shell, c.OSCommand.Platform.shellArg, command)
 }
 
 // SquashPreviousTwoCommits squashes a commit down to the one below it
diff --git a/pkg/gui/files_panel.go b/pkg/gui/files_panel.go
index a7e9683..e9496bc 100644
--- a/pkg/gui/files_panel.go
+++ b/pkg/gui/files_panel.go
@@ -349,17 +349,19 @@ func (gui *Gui) pullFiles(g *gocui.Gui, v *gocui.View) error {
 
 func (gui *Gui) pushFiles(g *gocui.Gui, v *gocui.View) error {
        gui.createMessagePanel(g, v, "", "Pushing...")
-       go func() {
-               branchName := gui.State.Branches[0].Name
-               if err := gui.GitCommand.Push(branchName); err != nil {
-                       gui.createErrorPanel(g, err.Error())
-               } else {
-                       gui.closeConfirmationPrompt(g)
-                       gui.refreshCommits(g)
-                       gui.refreshStatus(g)
-               }
-       }()
-       return nil
+       branchName := gui.State.Branches[0].Name
+       sub, err := gui.GitCommand.Push(branchName)
+
+       if err != nil {
+               return gui.createErrorPanel(g, err.Error())
+       }
+       if sub != nil {
+               gui.SubProcess = sub
+               return ErrSubProcess
+       }
+       gui.closeConfirmationPrompt(g)
+       gui.refreshStatus(g)
+       return gui.refreshCommits(g)
 }
 
 func (gui *Gui) handleSwitchToMerge(g *gocui.Gui, v *gocui.View) error {```

**Comment by mjarkk** [comment]
You can check before doing this all if the credentials file (`~/.git-credentials`) still exist and has the credentials.  
When doing that also check if git cache is enabled in `~/.gitconfig`  
But this leads probably into a big mess because the credentials are stored on all kinds of places depending on the OS and Env

**Comment by jesseduffield** [comment]
what would be cool is if we started a subprocess regardless but only switched to it if it requests input ie we run a goroutine that keeps track of the subprocess and if it receives a request for input (not sure if thats actually a thing) or matches the output with a pattern e.g /password/ it tells the gui to switch to the subprocess.

**Comment by mjarkk** [comment]
I'm not sure how the code handles the sub process but if you can place text inside the sub process and get text from the sub process it's totally possible to perform a regex over the output  

These stackoverflow post might help a bit: 
- https://stackoverflow.com/questions/23166468/how-can-i-get-stdin-to-exec-cmd-in-golang
- https://stackoverflow.com/questions/8875038/redirect-stdout-pipe-of-child-process-in-go

**Comment by remyabel** [comment]
Hmm, maybe we can do the following based on [this](https://git-scm.com/docs/gitcredentials):

1. Check if `git.config credential` is set
2. Check if `GIT_ASKPASS` is set
3. Check if `core.askPass` is set
4. Check if `SSH_ASKPASS` is set

In these situations, we should always switch to a subprocess because there's no way of telling what these programs will do. If none of these are set, git will prompt on the terminal. There's no need to parse the output because it's guaranteed by the spec.

**Comment by mjarkk** [comment]
An update to this problem: it also breaks when i need to fill in a username:  
![screenshot from 2018-08-21 17-08-22](https://user-images.githubusercontent.com/15320763/44410521-deea2680-a564-11e8-9f71-0d8def036d76.png)

**Comment by remyabel** [comment]
@mjarkk Do you mind taking a look at my PR and see if it resolves your issue?

**Comment by mjarkk** [comment]
Here you go:  
This is what happens  
![screenshot](https://i.imgur.com/iS5XUSM.gif)

**Comment by remyabel** [comment]
Can you elaborate on what the problem is? Is the push succeeding?

**Comment by mjarkk** [comment]
Push works fine but there is no visual feedback.  
When using the jesseduffield/lazygit master branch it shows a popup with `Pushing...`

**Comment by remyabel** [comment]
Hmm I see what you're saying. I'm not taking into account the situation where a credential helper is being used but the credentials are cached. I'll have to think about this.

**Comment by colmartofus** [comment]
I'm on ubuntu 18.04 getting the nightly ppa for lazygit. Here's my output:

```
sudo apt install --only-upgrade lazygit
Reading package lists... Done
Building dependency tree       
Reading state information... Done
lazygit is already the newest version (0.0~git20180913.303.fa08c6c-1~ubuntu18.04.1).
```

Should #203 be in this version or was it refused because of circleci? I'm wondering if I'm doing something wrong on my end.

**Comment by mjarkk** [comment]
That pull request is not in the master...  
It's because of the bugs shown earlier this issue i think.  
*I'm not exactly sure why he has closed the pull request because he closed it himself and there are no comments why*

**Comment by remyabel** [comment]
I closed it because I couldn't figure out an solution to my aforementioned comment:
> I'm not taking into account the situation where a credential helper is being used but the credentials are cached.

**Comment by mjarkk** [comment]
Update!! I think i have a solution for this problem  
on a test project i'm be able to read the current shell line that is send to the user and send a message as response without using a wired hack or having it take over the full terminal screen.  

I'll try to integrate it this evening in Lazygit  

It's a quit long explanation how i have dune it so i'll make a pull request when it's kinda working

**Comment by mjarkk** [comment]
Closing this issue because this is solved on macos and linux now

**Comment by colmartofus** [comment]
I don't think this is fixed. I just ran:

```
sudo add-apt-repository ppa:lazygit-team/daily
sudo apt-get update
sudo apt-get install lazygit
```

Went into a repo, hit 'p' (for pull) and got a non-interactable prompt asking for my username.

**Comment by mjarkk** [comment]
Hmmm that is wired.  
Can you give more details about your system, shell, git version, etc?
