### ISSUE TITLE
Got a massive Error prompt when I amend commit with staged changes, but can't decipher or understand it

### ISSUE THREAD

**Issue by SimonBao** [jesseduffield/lazygit#1454]
<img width="756" alt="Screenshot 2021-08-25 at 23 59 01" src="https://user-images.githubusercontent.com/23066880/130875489-bd388a92-9bb0-455d-9f7a-57793522c55f.png">

Not really sure what the error is and what I can do to fix/change it.

It seems to be able to actually amend it and add a fixup! commit, just wondering if this will cause me any issues?

**Comment by jesseduffield** [comment]
I'm gonna close this and re can re-visit if we find that others have the same issue
