### ISSUE TITLE
Allow Ctrl + arrow keys sentence navigation in commit message

### ISSUE THREAD

**Issue by mjarkk** [jesseduffield/lazygit#147]
**Describe the bug**
Can't change the cursor position in a commit message using <kbd>Ctrl</kbd> + arrow keys (<kbd>←</kbd> <kbd>→</kbd>)  
Currently when doing this the popup changes to:
```
┌─Clear file panel────────────────────────────────────┐
│Are you sure you want `reset --hard HEAD`? You may lo│
│se changes                                           │
└─────────────────────────────────────────────────────┘
```

**To Reproduce**
1. Open lazygit
2. Under commits Press C
3. Do: <kbd>Ctrl</kbd> + <kbd>←</kbd> OR <kbd>Ctrl</kbd> + <kbd>→</kbd>
4. See the popup change

**Expected behavior**
When the cursor is here in a sentence: `some words with| a cursor` (`|` = the cursor)  
And pressed <kbd>Ctrl</kbd> + <kbd>←</kbd> the cursor needs to be here: `some words |with a cursor`

**Desktop:**
 - OS: Linux (fedora 4.17.12-200.fc28.x86_64)
 - Shell: Bash
 - Lazygit v0.1.59

**Additional context**  
I'm not sure if <kbd>Ctrl</kbd> + <kbd>←</kbd> is possible in Go.  
If not it might be a good idea to block the `Clear files panel` popup

**Comment by jesseduffield** [comment]
looks like it's not possible: https://github.com/nsf/termbox-go/issues/60
It will always be interpreted as the beginning of an escape sequence hence the weird behaviour.

**Comment by jesseduffield** [comment]
closing cos it seems like this isn't possible :P

**Comment by asfaltboy** [comment]
@jesseduffield I know it's been just shy of 4 years, but I wonder is it still impossible, given we've switched to tcell (albeit a fork)? Would we be able to add a custom binding to implement this behavior manually if not?

For me, at least, jumping between words to fix typos is a productivity super-power :pray:

**Comment by asfaltboy** [comment]
Thanks for the quick reply @stefanhaller, this was probably a user error!

I'm using kitty terminal emulator on macOS (and also in Arch) but pressing alt+left in lazygit only added the `b` or `f` character to the output.

But now I remember that I added a few mappings to allow alt+left/right word jumping in [edgedb-cli](https://github.com/edgedb/edgedb-cli).

Commenting these out solved it for me:

```patch
 # jump word in apps like edgedb
-map alt+left send_text all \x1b\x62
-map alt+right send_text all \x1b\x66
+# map alt+left send_text all \x1b\x62
+# map alt+right send_text all \x1b\x66
```
 
This means I'll have to figure out another way to send the right sequence to [edgedb-cli](https://github.com/edgedb/edgedb-cli) ([source](https://github.com/tailhook/rustyline/blob/55dcab54fbab0ba0610799291276785e5b31199c/src/keymap.rs#L469-L499))... 😢
