### ISSUE TITLE
Seems there are some unused strings define in i18n

### ISSUE THREAD

**Issue by black-desk** [jesseduffield/lazygit#1476]
such as

https://github.com/jesseduffield/lazygit/blob/f44ae68e99386d5351d7cdec05a3231aa01a2d84/pkg/i18n/english.go#L148

@jesseduffield maybe we should remove them?

**Comment by mjarkk** [comment]
I would say lets remove them for a few reasons:
- Makes the binary bigger without any reason
- We can always get these back by going back in the commit history
- As there are so many translations there is a big change a new entry is created even if we already have something for that translation
