### ISSUE TITLE
Testing & quality tools

### ISSUE THREAD

**Issue by antham** [jesseduffield/lazygit#148]
**Is your feature request related to a problem? Please describe.**
It is not really a feature, I would like to suggest adding a CI, some go quality tools and a coverage tool could increase the quality and ease the maintenance.

**Describe the solution you'd like**
For instance using https://circleci.com as CI, https://golangci.com as quality check tool and https://codecov.io as a coverage tool, they are all free for open source project.

**Describe alternatives you've considered**
/

**Additional context**
/

**Comment by jesseduffield** [comment]
I have a little bit of experience with travis CI, how does circle CI compare?

Golang CI looks good, I'm a little scared that it will tear the codebase to pieces, but that's probably a good thing.

Codecov looks cool too

Would you be able to raise a PR for this?

**Comment by antham** [comment]
I used before travis for all my open source project, it's a good tool but I found it cumbersome at the end and moved to circle, but maybe some other people could have a different point of view and argue that I was misuing it. 

Circle has first class support for docker, you can define build workflows, you can ssh when you can't troubleshoot locally and you have a nice cli to simulate locally a build.

Have a look here on this project, I moved from travis to circle, you can compare to have a kind of idea : [travis build](https://travis-ci.org/antham/chyle/builds), [travis config](https://github.com/antham/chyle/blob/c8a485da70ca3c7af0e178f8142b2b84ccdc3c07/.travis.yml) vs [circle build](https://circleci.com/gh/antham/chyle), [circle config](https://github.com/antham/chyle/blob/master/.circleci/config.yml).

Sure I can setup everything but you need to create accounts first.

**Comment by jesseduffield** [comment]
I made a circle CI config file and a circle CI account, but I'm not sure how to share permissions. Do I need to set up the Circle CI account as an org account? I'm not 100% familiar with the right approach here

**Comment by antham** [comment]
I don't know about user management, you can add someone here https://circleci.com/team/gh/jesseduffield ,  but maybe it necessary to add the person as a collaborator in project.

**Comment by antham** [comment]
Yes anybody can see it, as you can see my project I pasted earlier, I thought you were talking about interacting with circleci. For codecov it's not necessary to add any token, it will works directly if you added the project. Thank you for setting up everything, I will check that soon.
