### ISSUE TITLE
Missing UI feedback when rebasing onto another branch

### ISSUE THREAD

**Issue by grossjohann** [jesseduffield/lazygit#1488]
**Describe the bug**
When hitting `r` in the "Local Branches" panel to rebase the currently checked-out branch onto the selected branch, there is no user feedback while the operation is ongoing.  Lazygit usually responds really fast, so if it appears to hang for a couple of seconds, I start suspecting that something went wrong.

**To Reproduce**
Start a branch and work on it for a while.  Let's say that other people push to `master` while you are working on your branch.  After some commits on `master` have happened, while you are still in your branch:
- Start lazygit
- Navigate to the "Local Branches" panel
- Navigate to the `master` branch in the "Local Branches" panel
- Hit `f` to fetch the commits that have happened on the master branch
- Hit `r` to rebase your branch on top of master

**Expected behavior**
After hitting `r`, the UI updates soon.  If the rebase operation is fast, it makes sense to display the result.  If the rebase operation is slow, perhaps a spinner would be nice, like the ones from push and pull.

**Screenshots**
I think screenshots are not required.

**Desktop (please complete the following information):**
 - OS: macOS Big Sur version 11.6
 - Lazygit Version: 0.29 (installed via the `jesseduffield/lazygit` tap for HomeBrew)

**Additional context**

**Comment by rickyelopez** [comment]
This is still a problem. I'm working on a pretty massive repo, and the rebase operation makes everything hang for sometimes up to a full minute. Worse than it hanging, there's no feedback that lazygit as registered me hitting enter on the "are you sure you want to rebase" prompt, and subsequent enter presses while it is frozen will be applied to the next dialog that appears (i.e. the "conflicts! press enter to continue" prompt).

Would it be possible to make rebasing work like some other operations where while waiting there's a spinner in the bottom left that tells you there's something happening? Or maybe there's another solution?

**Comment by jesseduffield** [comment]
This should be a really simple fix: In the `rebase()` method in `pkg/gui/controllers/branches_controller.go` we just need to wrap the action in a `WithLoaderPanel` call (you can see an example of that happening elsewhere in the file)

I've chucked a good-first-issue label on this. Do you feel up to the task @rickyelopez or @grossjohann ?

**Comment by rickyelopez** [comment]
yep sounds like fun, I can give it a shot in the next few weeks.

**Comment by topher200** [comment]
This issue can be closed; it's resolved by #2851

**Comment by grossjohann** [comment]
Thank you @topher200 for the reminder.  Yes, with the new behavior there is very nice feedback.  Let me close this issue.

**Comment by rickyelopez** [comment]
thanks guys! sorry I never got to it myself
