### ISSUE TITLE
Rewording long commit messages results in a panic: runtime error: index out of range [0] with length 0

### ISSUE THREAD

**Issue by kylepollina** [jesseduffield/lazygit#1495]
**Describe the bug**
Rewording long commit messages results in a panic: runtime error: index out of range [0] with length 0

**To Reproduce**
1. Create a commit with a really long commit message
2. Choose the commit and hit `r` to reword the commit message
3. This will pop up an input box with the commit message wrapped onto multiple lines. Start deleting the commit message
and as soon as the cursor deletes the first character on the second line the program panics

**Expected behavior**
Rewording a long commit message does not result in a panic. 

**Screenshots**
Really long commit message
<img width="971" alt="Screen Shot 2021-09-27 at 1 20 33 PM" src="https://user-images.githubusercontent.com/13981456/134979417-01e983e7-38c0-46f5-85af-16e833e73dcf.png">

Hitting `r` to reword opens this multiline pop-up
<img width="971" alt="Screen Shot 2021-09-27 at 1 20 43 PM" src="https://user-images.githubusercontent.com/13981456/134979424-5335d47c-d1f6-40fb-875a-a7df72d3a2f4.png">

Deleting the characters is fine until you are have already deleted all the characters on this line.
<img width="971" alt="Screen Shot 2021-09-27 at 1 20 49 PM" src="https://user-images.githubusercontent.com/13981456/134979429-e8fe0c97-c5a4-4d64-9364-407dfb7bf9e7.png">

Now pressing backspace will result in the following panic:

```
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/jesseduffield/gocui.(*View).EditDelete(0xc0002fc1e0, 0x1)
	/home/runner/work/lazygit/lazygit/vendor/github.com/jesseduffield/gocui/edit.go:179 +0x337
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).defaultEditor(0xc0000f4000, 0xc0002fc1e0, 0x13007f, 0xc000130000, 0x1047dec)
	/home/runner/work/lazygit/lazygit/pkg/gui/editors.go:60 +0x45
github.com/jesseduffield/gocui.EditorFunc.Edit(0xc00062bdd0, 0xc0002fc1e0, 0x7f, 0x10102f90000, 0x0)
	/home/runner/work/lazygit/lazygit/vendor/github.com/jesseduffield/gocui/edit.go:29 +0x4c
github.com/jesseduffield/gocui.(*Gui).execKeybindings(0xc0000a49c0, 0xc0002fc1e0, 0xc000133900, 0xc000000180, 0xc0001338f0, 0xc0000baba0)
	/home/runner/work/lazygit/lazygit/vendor/github.com/jesseduffield/gocui/gui.go:1152 +0x2bf
github.com/jesseduffield/gocui.(*Gui).onKey(0xc0000a49c0, 0xc000133900, 0xc00006c0d0, 0xc00029a100)
	/home/runner/work/lazygit/lazygit/vendor/github.com/jesseduffield/gocui/gui.go:1063 +0x2c5
github.com/jesseduffield/gocui.(*Gui).handleEvent(0xc0000a49c0, 0xc000133900, 0x0, 0x0)
	/home/runner/work/lazygit/lazygit/vendor/github.com/jesseduffield/gocui/gui.go:654 +0x46
github.com/jesseduffield/gocui.(*Gui).MainLoop(0xc0000a49c0, 0xc000000004, 0xc00031fa08)
	/home/runner/work/lazygit/lazygit/vendor/github.com/jesseduffield/gocui/gui.go:614 +0x1c5
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).Run(0xc0000f4000, 0x0, 0x0)
	/home/runner/work/lazygit/lazygit/pkg/gui/gui.go:523 +0x51b
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).RunAndHandleError.func1(0xc000272a01, 0xc000094120)
	/home/runner/work/lazygit/lazygit/pkg/gui/gui.go:531 +0x45
github.com/jesseduffield/lazygit/pkg/utils.SafeWithError(0xc00031fb40, 0x0, 0x0)
	/home/runner/work/lazygit/lazygit/pkg/utils/utils.go:126 +0x62
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).RunAndHandleError(0xc0000f4000, 0x0, 0x17a6db2)
	/home/runner/work/lazygit/lazygit/pkg/gui/gui.go:530 +0x7d
github.com/jesseduffield/lazygit/pkg/app.(*App).Run(0xc000291880, 0xc00023a6c0, 0x0)
	/home/runner/work/lazygit/lazygit/pkg/app/app.go:240 +0x6b
main.main()
	/home/runner/work/lazygit/lazygit/main.go:127 +0xb7b
```

**Desktop (please complete the following information):**
 - OS: Darwin
 - Lazygit Version v0.29

**Additional context**
You are beautiful

**Comment by Ryooooooga** [comment]
may fixed in https://github.com/jesseduffield/gocui/pull/14 or https://github.com/jesseduffield/gocui/pull/16

**Comment by jesseduffield** [comment]
Fixed in https://github.com/jesseduffield/lazygit/pull/1518 (though notable wrapping is replaced with scrolling there. If that's a concern lemme know)
