### ISSUE TITLE
Lazygit seems to get heavy on CPU usage after sleeping

### ISSUE THREAD

**Issue by laurentS** [jesseduffield/lazygit#1502]
**Describe the bug**

I've noticed lazygit getting in the 20-30% of CPU usage for prolonged periods of time (for several minutes at least,
probably hours if I leave it be). This seems to be happening virtually every time my laptop wakes up from sleeping
(suspend to ram I think is the correct term). Just now, as an example, I opened my laptop, checked htop for heavy CPU
users, and lazygit was floating around 23-26%. I had multiple instance (on different repos) opened at the same time.
After closing all of them, and restarting a single instance, CPU usage is 0 again, as I would expect given that the app
is not doing anything. Opening multiple instances back again does not seem to bring the CPU usage up either, even after
waiting for a few minutes (doing nothing, just leaving the app open).

**To Reproduce**
1. Open lazygit in a working tree folder
2. Put computer to sleep (close lid, whatever you do...)
3. Wake up computer
4. Check CPU usage for lazygit

**Expected behavior**
Given that the app is doing "nothing", and that its cpu usage is hovering around 0 before going to sleep, I'd expect the same after sleeping.

**Screenshots**
Not relevant here

**Desktop (please complete the following information):**
 - OS: Debian linux (unstable)
 - Lazygit Version 0.29

**Additional context**
I *think* this was happening before upgrading to 0.29, so it's probably not a regression in the last release (but not 100% sure about this).
I'm running lazygit in byobu/tmux, in case it makes any difference.

**Comment by mark2185** [comment]
Does this still occur in `v0.35` or `master`?

**Comment by laurentS** [comment]
With `0.34`, I still see the problem. After wake up the CPU is around 10-15%, so it's better than before, but still there.
With `0.35`, it's a bit better. I left several sessions open before putting my machine to sleep. After waking up, `htop` shows CPU loads of ~9/4/3% for the top 3 ones. Cumulated it's still over 10% CPU. As before, if I close the various sessions and restart the app, CPU usage drops to almost nothing again.
My machine is 6 years old, so the CPU isn't exactly a beast, but still.

Is there anything I can do to help locate the problem? (I'm not a go developer :sweat_smile:)

**Comment by mark2185** [comment]
Actually I encountered this as well.

The only thing we could do is profile it and try to reproduce it.

**Comment by peppy** [comment]
I can reproduce high idle CPU on a regular basis. It seems to happen after doing a `git pull` operation, and persist from that point forward.

[Sample of lazygit.txt](https://github.com/jesseduffield/lazygit/files/10123664/Sample.of.lazygit.txt)

**Comment by laurentS** [comment]
I am still seeing this with `0.36`. I just had to close 2 instances that were hogging 60% of my CPU post wake-up. I can close them normally, so the app is still responsive and functional.

**Comment by laurentS** [comment]
I just tested a build of `master` commit c769a78d and the problem appears to be gone. After resuming from sleep, CPU load is virtually null.
Thanks for fixing this!

**Comment by laurentS** [comment]
I've been running `0.37` for a few hours and I've seen no sign of the issue so far. I'll close this, and reopen if I can spot the issue again.
Thanks to everyone who fixed it!
