### ISSUE TITLE
Pushing a new branch to a remote no longer works

### ISSUE THREAD

**Issue by peppy** [jesseduffield/lazygit#1524]
**Describe the bug**

Using the push command on a new branch no longer works, with an error.

**To Reproduce**
1. Create new branch
2. Push to remote

**Expected behavior**
Push succeeds, new branch is created on the target remote.

**Screenshots**

https://user-images.githubusercontent.com/191335/137669665-ebedd792-bf40-4383-a9a6-de7bc442fd1f.mp4

**Desktop (please complete the following information):**
 - OS: macOS (Monterey beta 10)
 - Lazygit Version (source 71fdc5c03885bfabc50ccd6bfe0f83637a6cd4cc)

**Additional context**
This has regressed recently, and only occurs in a build from source. It works correctly on 0.29 (from brew).

**Comment by jesseduffield** [comment]
I'll have a look into this after work

**Comment by jesseduffield** [comment]
merged :) I really need to find a way to test this properly with pushing/pulling, maybe with an integration test that uses a local git server. It's quite a blind spot
