### ISSUE TITLE
Adding new file in new folder only shows message that `null` cannot be accessed

### ISSUE THREAD

**Issue by aragon999** [jesseduffield/lazygit#1545]
**Describe the bug**
When using the folder tree view there seems to be a problem when one has a folder where just a new file has been added, when viewing the folder in lazygit the message `error: Could not access 'path/to/new/folder/null'` also see the screenshot below. 

**To Reproduce**
Create a new file inside a new folder and view the unstaged changes in lazygit.

**Expected behavior**
Show the changes of the file.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/6317761/138767828-a2b4b32b-49d9-4699-951b-7c10358d32aa.png)

**Desktop (please complete the following information):**
commit=v0.30, build date=2021-10-23T20:51:08Z, build source=binaryRelease, version=0.30, os=linux, arch=amd64

**Comment by blm** [comment]
- I was able to reproduce this problem.
- What I did was create a directory in the cloned repository and inside that a file.
- When you start lazygit and navigate to the directory in the "Files - Submodules" window, the error message is shown.
- In my test I created a directory called "testing" and a file inside it called asd.txt
- The error message:
```
error: Could not access 'testing/null'
```
- This seems to come from the command:
```
$ git diff --submodule --no-ext-diff --color=always --no-index -- /dev/null testing
error: Could not access 'testing/null'

```
- The error message is going from git diff.  I think "null" is being added to the directory name inside git diff

**Comment by socketbox** [comment]
To add a little to this: the directory need not be new or contain only a new file. I've got a `docs` directory that's full of markdown files and I added an XML file to it. When I opened lazygit (commit c4e71356), it reported `error: Could not access 'docs/null'`

**Comment by mark2185** [comment]
@socketbox Is the directory `docs` staged?

**Comment by paulmiddelkoop** [comment]
Same problem here with a new directory (status: ``??``) .

**Comment by jesseduffield** [comment]
Just reproduced locally: I've added a file called `text.txt` to `pkg/commands/oscommands` here's the command that's run when I select the directory:
```
git diff --submodule --no-ext-diff --unified=3 --color=always --no-index -- /dev/null "pkg/commands/oscommands"
```

When I remove the /dev/null part then it no longer returns that error (though interestingly it does _not_ show the untracked file's changes. Even just a regular `git diff pkg/commands/oscommands` doesn't show that.

I've got a PR up for this now: https://github.com/jesseduffield/lazygit/pull/2260
