### ISSUE TITLE
Azure devops git provider

### ISSUE THREAD

**Issue by MiroslavMikus** [jesseduffield/lazygit#1548]
**Describe the solution you'd like**
Could we get Azure DevOps [git provider](https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md#custom-pull-request-urls) so we can use `o` and `O` shortcuts in `local branches` window.

**Describe alternatives you've considered**
Yeah, Im working on customs command which can help me with this. Its already great, but IMO native support can be much better. I will share this command when finished 😄 

> alternative would be an custom command whitch calls the [azure cli tool](https://docs.microsoft.com/en-us/cli/azure/repos/pr?view=azure-cli-latest) which is an WIP on my site :)

Thanks 🦸

**Comment by tiwood** [comment]
I wanted to add some more details which may be helpful for the implementation.

Say we have the following git remotes:

* https://My-Demo-Org@dev.azure.com/My-Demo-Org/Demo-Project/_git/DemoRepository
* git@ssh.dev.azure.com:v3/My-Demo-Org/Demo-Project/DemoRepository

To create a PR from branch `develop` to `master` URL would be:

```html
https://dev.azure.com/My-Demo-Org/Demo-Project/_git/DemoRepository/pullrequestcreate?sourceRef=develop&targetRef=master
```

```golang
return fmt.Sprintf("https://%s/%s/%s/_git/%s/pullrequestcreate?sourceRef=%s&targetRef=%s", 
siteDomain, "My-Demo-Org", "Demo-Project", repository, from, to)
```

**Comment by MiroslavMikus** [comment]
Amazing, great work :) I will test it ASAP (As Soon As  I install go compiler) 😄 

In any case, big thanks :heart_eyes:

**Comment by MiroslavMikus** [comment]
Tested, works like expected :+1:
