### ISSUE TITLE
Branch commit window not scrolling correctly

### ISSUE THREAD

**Issue by bartgol** [jesseduffield/lazygit#1569]
**Describe the bug**
When scrolling the list of commits in a branch, upon reaching the last displayed commit, scrolling further does not visually scroll the list, although the correct commit msg (and first part of diff) is displayed in the Commit window

**To Reproduce**
1. Go to Local branches windo
2. Click on any branch
3. Scroll down to the last commit that is displayed. Then try to scroll down more.
4. Commit list in the window does not scroll.

**Expected behavior**
Scrolling past the last commit in the window causes all commits to go up by one, with the top one "going out of scope", and the new older commit "entering the window" at the bottom.

**Screenshots**
Here is when I reach the bottom commit.
![last_line](https://user-images.githubusercontent.com/3226046/140873539-225b3570-a218-4dac-90c4-65755fbd190d.png)

Here is after I scroll a couple more times. Notice that the commit index has increased, and the commit window shows the correct message and diff (you can't tell the Commit window is showing the right stuff, but I can assure you it does).
![after_scrolling](https://user-images.githubusercontent.com/3226046/140873536-7981d519-da8d-4b5e-8134-92780e496679.png)

**Desktop (please complete the following information):**
 - OS: RHEL 7.5
 - Lazygit Version v0.31.2
 - The last commit id if you built project from sources: N/A (installed via conda)
 - Conda version: 4.6.14

**Additional context**
I tried to force reinstall the conda pkg, to no avail. I have lazygit installed on virtually all my machines, and this is the only one that shows this behavior.

**Comment by jesseduffield** [comment]
fixed in v0.31.3
