### ISSUE TITLE
csv files only display last line and only if #lines > 1?

### ISSUE THREAD

**Issue by fiendish** [jesseduffield/lazygit#157]
**Describe the bug**
I only see the last line of csv files and only if there is more than one line in the file

**To Reproduce**
Put these files in a new repo and invoke lazygit. Then look at the files. What's happening to them?

[test7.txt](https://github.com/jesseduffield/lazygit/files/2291690/test7.txt)
[test6.txt](https://github.com/jesseduffield/lazygit/files/2291691/test6.txt)
[test5.txt](https://github.com/jesseduffield/lazygit/files/2291692/test5.txt)
[test4.txt](https://github.com/jesseduffield/lazygit/files/2291693/test4.txt)
[test3.txt](https://github.com/jesseduffield/lazygit/files/2291694/test3.txt)
[test2.txt](https://github.com/jesseduffield/lazygit/files/2291695/test2.txt)
[test.txt](https://github.com/jesseduffield/lazygit/files/2291696/test.txt)

**Screenshots**
<img width="938" alt="screen shot 2018-08-15 at 5 04 23 pm" src="https://user-images.githubusercontent.com/201996/44173250-60e1d780-a0ad-11e8-9465-00cc525b6d22.png">

<img width="1023" alt="screen shot 2018-08-15 at 5 05 58 pm" src="https://user-images.githubusercontent.com/201996/44173289-7f47d300-a0ad-11e8-8dbf-00cee18c3e3e.png">

**Desktop (please complete the following information):**
 - OS: macOS 10.13.5
 - Lazygit Version master via go get

**Comment by remyabel** [comment]
The glitch appears to occur because you Windows-style line endings in your text files, i.e `M^`. Running `dos2unix` makes the problem go away.

**Comment by mjarkk** [comment]
I think this issue can be closed, the example files shown above look fine in lazygit now.

**Comment by jesseduffield** [comment]
very well, closing!
