### ISSUE TITLE
Skip "press enter to return to lazygit"

### ISSUE THREAD

**Issue by simon-lang** [jesseduffield/lazygit#1576]
### Discussed in https://github.com/jesseduffield/lazygit/discussions/1462

<div type='discussions-op-text'>

<sup>Originally posted by **theduke** September  4, 2021</sup>
Is there a way to skip the "press enter to return to lazygit" step?

I mostly use the editor for commits, and that extra step is quite annoying.</div>

**Comment by nikolasetiawan** [comment]
+1

**Comment by c02y** [comment]
+2

**Comment by jesseduffield** [comment]
Good catch @c02y 

closing given this is configurable
