### ISSUE TITLE
Words surrounded by backticks get removed from commit messages 

### ISSUE THREAD

**Issue by sanbornm** [jesseduffield/lazygit#158]
**Describe the bug**
Words surrounded by backticks get removed from commit messages.

    This commit `message`

Would end up like:

    This commit 

**To Reproduce**

Make a commit with backticks surrounding a word.

**Expected behavior**

A commit message to be:

    This commit `message`

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Lazygit Version: `unversioned` (go get)

**Comment by remyabel** [comment]
Having backticks in commit messages is slightly dangerous because it will get interpreted by the shell, but please pull down the PR and test it.

**Comment by glvr182** [comment]
@remyabel @sanbornm Is it fixed now?

**Comment by sanbornm** [comment]
@glvr182 It is, thanks!
