### ISSUE TITLE
Missing version info

### ISSUE THREAD

**Issue by somera** [jesseduffield/lazygit#1587]
**Is your feature request related to a problem? Please describe.**
Why lazygit -v is not showing any info?

```
$ lazygit -v
commit=, build date=, build source=unknown, version=unversioned, os=linux, arch=amd64
```

Same in the UI

![image](https://user-images.githubusercontent.com/8334250/142677354-a8a45a5e-3316-48bc-bf91-16fd29256ba1.png)

**Comment by jesseduffield** [comment]
This would be because the binary was built from source as opposed to being built with version flags. May I ask where you got the binary from?

**Comment by somera** [comment]
Self compiled ... https://github.com/jesseduffield/lazygit#manual

```
git clone https://github.com/jesseduffield/lazygit.git
cd lazygit
go install
```

**Comment by jesseduffield** [comment]
Go 1.18 will allow adding the git commit sha in the installed binary without adding any additional flags, but that go version is a little way off at the moment (should be out in february I believe) https://utcc.utoronto.ca/~cks/space/blog/programming/GoVersionOfYourSource

**Comment by somera** [comment]
But we are talking about the lazygit version. And not the git version.

**Comment by jesseduffield** [comment]
the lazygit version e.g. v0.31.3 is based on a git tag with that version being baked in upon build, which itself is just against a particular commit sha. We add this on release with the following ldflags (from `.goreleaser.yml`, see https://goreleaser.com/customization/build/):
```yml
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.buildSource=binaryRelease
```

I'm not sure how we would add this version info upon local install other than having a bash script which gets the head commit and the name of a tag against that commit, if one exists. I'm happy to accept a PR which adds such a script

**Comment by somera** [comment]
`I'm happy to accept a PR which adds such a script`

Sounds good.

**Comment by jbrains** [comment]
Does this issue duplicate #1439 ?

**Comment by jesseduffield** [comment]
Good point. I'll close this off in favour of https://github.com/jesseduffield/lazygit/issues/1439
