### ISSUE TITLE
Freezes when opening a repo that has neither `main` or `master` branches

### ISSUE THREAD

**Issue by lucianoratamero** [jesseduffield/lazygit#1595]
First of all, thanks for lazygit! It is an amazing tool <3

**Describe the bug**

I work in a repo that uses `dev` as the default branch, and never had neither `main` or `master` branches.
As soon as I launch `lazygit`, it just hangs; nothing is displayed and I can't even kill the process with ctrl+c (or any other key combination). The only way to kill it is from outside.

Here are the logs:
![image](https://user-images.githubusercontent.com/1103672/143183445-d5862d96-e07a-4fbe-84f0-50f47ae9e3c5.png)

**To Reproduce**
1. Go to the directory with a git project that hasn't had a master/main branch
2. Launch lazygit

**Expected behavior**
For it to open as in other projects.

**Desktop:**
 - OS: Fedora Workstation 35
 - Lazygit version: 0.31.4

**Comment by lucianoratamero** [comment]
Maybe having something to detect the default branch before running the git calls could prevent this error, and fix most issues about main vs master branches.

I've found this command that can give you the default branch for origin:
`git remote show origin | sed -n '/HEAD branch/s/.*: //p'`

No idea what would happen if the main origin is not called `origin`, though.

**Comment by fsmiamoto** [comment]
Hmm interesting, but I couldn't reproduce it at first try so I think there's more elements to it.
Here's the log of what I've done in trying to reproduce it:
```sh
$ mkdir test
$ cd test
$ git init -b dev
Initialized empty Git repository in /home/shigueo/code/test/.git/
$ lazygit # Check whether it would show the behavior, all fine here
$ touch a
$ git add -A
$ git commit -m "initial commit"
[dev (root-commit) 1b85ee8] initial commit
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 a
$ lazygit # Checking again, normal behavior as well
```

**Comment by lucianoratamero** [comment]
thanks for checking!
I'll try to reproduce it with a new repo based on the tools I use at work to see what's going on :]
I'll ping you here if I find out what it is!

**Comment by mark2185** [comment]
Did you ever manage to reproduce it?

**Comment by mark2185** [comment]
Stale/not reproducible.
