### ISSUE TITLE
Recent repos don't exist in state = crash.

### ISSUE THREAD

**Issue by LiamKearn** [jesseduffield/lazygit#1596]
If your recent repo paths that are in state.yml don't exist and you prompt no to the create new repo you will encounter a crash. (I don't know if this is generated file but I encountered this moving dotfiles around)

Sorry for the little context managed to fix the problem and forget to file a issue.

I can attempt to recreate again if this isn't enough.

**Comment by mark2185** [comment]
@LiamKearn could you test `v0.35` to see if it still happens? #1931 should have fixed it.

**Comment by LiamKearn** [comment]
Thanks for that @mark2185. Looks like it's working like butter over here.

Was already on the brew --HEAD.

Behaviour now:
1. I purposely bunk the first path in state.yml (`/recentrepos[0]`)
2. Lazygit moves onto the next valid path in the state file and removes the bunked entry
3. If remove all the paths and lazygit exits with the expected message (`Must open lazygit in a git repository. No valid recent repositories. Exiting.`)
