### ISSUE TITLE
Text Expand Not Working

### ISSUE THREAD

**Issue by AKIB44** [jesseduffield/lazygit#1599]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Lazygit Version [e.g. v0.1.45]
 - The last commit id if you built project from sources (run : ```git-rev parse HEAD```)

**Additional context**

**Comment by lifeModder19135** [comment]
Wtf? @akiii02 Is this not finished? It looks like you just filled out the title bar and hit `submit`. What is the point in even filling out an issue if there isn't enough info to even reproduce / diagnose the issue or bug (let alone fix it.) In the current form, this is just going to confuse and annoy people.

**Comment by nadeemkhedr** [comment]
I have filled an issue related to text expand here #1578
