### ISSUE TITLE
Add Gitea to PR list

### ISSUE THREAD

**Issue by jolheiser** [jesseduffield/lazygit#1615]
I would love to add Gitea support to lazygit.

I've just merged https://github.com/go-gitea/gitea/pull/17908 which allows the default branch to be inferred for a PR (which I see the other forges currently in lazygit support)

The PR above will appear in Gitea v1.16.0, which should be released (at a hazy guess) within the next month or so.

Prior to that (or if anyone uses the PR link on an outdated version) users will get a 404, and I don't want you to have to deal with questions if they come here. 🙂 

That being said, how long would you like me to wait before sending a PR?

**Comment by jesseduffield** [comment]
Nice, I'm honestly fine with you sending a PR whenever. We could merge it behind a feature flag (i.e. `if false {`) and do a follow-up PR to remove the guard. What do you think?

**Comment by jolheiser** [comment]
I think that would be a good idea. I'll kick it around a bit more and then open a PR for review. 

Thanks for the feedback!

**Comment by kentrosi** [comment]
Could this include self-hosted gitea as well? Some kind of `gitea.domain.tld`

https://github.com/jesseduffield/lazygit/blob/990dc8c4ea1133a58d5c863abd543ee5cde1e700/pkg/commands/pull_request.go#L28-L43
