### ISSUE TITLE
Running copy to clipboard on OSX terminal whilst ssh'd into a remote box fails.

### ISSUE THREAD

**Issue by LiamKearn** [jesseduffield/lazygit#1617]
**Describe the bug**
Running copy to clipboard on OSX terminal whilst ssh'd into a remote box fails.
Results in exit code 1.
However the logs do not show anything:
```
Dec  8 11:14:09 |INFO| RunCommand command="Copying '348e4fdd731d33143bb8e6f1e6a75fec83891334' to clipboard"
Dec  8 11:14:09 |INFO| refreshing all scopes in async mode 
```

**To Reproduce**
Run OSX Terminal remote to a linux box run copy commit to clipboard

**Expected behavior**
Commit is copied to clipboard without exit code 1 and failure.

**Screenshots**
![Screenshot 2021-12-08 at 11 16 37 am](https://user-images.githubusercontent.com/76269376/145125779-afb2582b-f991-49ca-b2f2-a0b40fbe645a.png)

**Desktop (please complete the following information):**
 - OS: OSX Mont whatever it is
 - commit=02bf6a5c177c145c46e5e62524458fc3375d01af, build date=2021-11-22T10:08:20Z, build source=binaryRelease, version=0.31.4, os=linux, arch=amd64 (Lazygit version)
 
 
 This could just be a ID10T error on my part, Do I need some sort of specific terminal configuration to copy to clipboard remotely?

**Comment by LiamKearn** [comment]
If it is an ID10T error on my part might I suggest a prompt to notify clients with no clipboard support?

**Comment by LiamKearn** [comment]
Fixed this on my part by providing a binary for the ext-package that resolves clipboard.

I just used [clipper](https://github.com/wincent/clipper) to forward it locally.

**Comment by greenfrogs** [comment]
After setting up [clipper](https://github.com/wincent/clipper/tree/master), just add the following to the [lazy git config file](https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md):

```
os:
  copyToClipboardCmd: 'echo {{text}} | nc -N localhost 8377'
```

**Comment by LiamKearn** [comment]
> After setting up [clipper](https://github.com/wincent/clipper/tree/master), just add the following to the [lazy git config file](https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md):
> 
> ```
> os:
>   copyToClipboardCmd: 'echo {{text}} | nc -N localhost 8377'
> ```

Yeah there was a ext go library which resolved the clipboard copy command back when I had the issue, was a bit stupid but I had to chuck a binary in PATH that it expected that actually forwarded stuff over to clippers socket.

Good to see there is a better solution now!
