### ISSUE TITLE
Showfiletree option in configuration does not work

### ISSUE THREAD

**Issue by alesbrelih** [jesseduffield/lazygit#1620]
**Describe the bug**
I've tried setting
```
gui:
 - showFileTree: false
```
in config.yml

And it does not work. Everytime I open lazygit it uses filetree structure.

**To Reproduce**
Set:
```
gui:
 - showFileTree: false
```
in config.yml

And run lazygit.

**Expected behavior**
Changes should not be listed in file tree view.

**Desktop (please complete the following information):**
 - OS: OSX Monterey (M1 chip)
 - Lazygit Version: commit=02bf6a5c177c145c46e5e62524458fc3375d01af, build date=2021-11-22T10:08:20Z, build source=binaryRelease, version=0.31.4, os=darwin, arch=arm64

And also.. thank you for this awesome tool!!

**Comment by alesbrelih** [comment]
Assumption is the mother of all f*** ups... Closing this issue.. Thanks again for this awesome plugin!

**Comment by sirodoht** [comment]
What was the assumption? I might have the same.

**Comment by alesbrelih** [comment]
@sirodoht  I used '-' inside the yaml spec.

Once I've changed to:
`gui:
    showFileTree: false
`
It started to work. Hope this helps.

**Comment by sirodoht** [comment]
Oh I see, thanks!
