### ISSUE TITLE
feature: press arrow up on commit message box to re-use previous message

### ISSUE THREAD

**Issue by GitSquared** [jesseduffield/lazygit#1623]
**Is your feature request related to a problem? Please describe.**
I'm working in a corporate environment where we run a bunch of checks and linters as pre-commit hooks.
They're usually quite fast but they often fix minor nits in my staged files and return a non-zero code so i can stage the fixed changes before committing.
However with lazygit's current UI I have to re-enter my commit message every time the hooks fail 🤯

**Describe the solution you'd like**
I would love if I could just arrow-up my way to previous commit messages while in this box.

![image](https://user-images.githubusercontent.com/24496417/145488574-06364679-f979-4b42-8b72-72ddbda9551e.png)

**Describe alternatives you've considered**
Maybe lg could detect files changed by hooks and propose to add them & re-run on the commit log screen. But that would be more work I suppose.

**Additional context**
Just started using lg a few days ago (loving it so far!) so maybe I am missing some built-in feat that could help me achieve what I want.
Might take a stab at implementing this but I know nothing about Go.

**Comment by mark2185** [comment]
A minor nitpick - this should work only for empty messages, having a multiline commit message disappear upon pressing `<Up>` would seem really odd.

**Comment by GitSquared** [comment]
+1 on that - I've seen some shells (i think the psql one?) that save the currently editing message in a separate buffer so you can check something in history then go back to editing your message. I think that would be 👌 

I'll attempt a first impl next week

**Comment by mark2185** [comment]
I was thinking more in the lines of using a different keymap for previous message, like `<c-k>` for previous and `<c-j>` for next.

The arrow key use should be intuitive, like moving the cursor to the line above. (that currently needs implementing too)

**Comment by jakobkogler** [comment]
My open PR https://github.com/jesseduffield/lazygit/pull/1612 is related to this issue.
The idea is a bit different though. My current implementation will remember the commit message if the commit fails, and then pre-fill it when you make the next commit. It's not a persistent solution though, so if lazygit is closed in between it will forget the message.

**Comment by GitSquared** [comment]
Fonctional issue fixed in #1612, closing
