### ISSUE TITLE
Specify specific PR Url Pattern using config.yml

### ISSUE THREAD

**Issue by FHc24** [jesseduffield/lazygit#1632]
**Is your feature request related to a problem? Please describe.**
Currently there is no possibility - at least none im aware of - to create PRs for a private hosted VCS since the domains are not covered in the hardcoded list of git providers in: https://github.com/jesseduffield/lazygit/blob/df0e3e52fea02950d78af5233a859f592092d475/pkg/commands/pull_request.go#L32

**Describe the solution you'd like**
I suggest to allow enhancing the list dynamically reading a list of names and url-patterns from the config file

**Describe alternatives you've considered**
tbh i dont so one. For now the only way to make this work is extendin the list and compiling lazygit. Sadly im not yet good enough at go introducing config consideration instead of the hardcoded list :D

**Additional context**
I guess this opens this feature for everyone using this on remote hosts besides github, bitbucket or gitlab

**Comment by FHc24** [comment]
sry - https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md

saw this late

**Comment by eerison** [comment]
Just to be more specific where it is located 

https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md#custom-pull-request-urls
