### ISSUE TITLE
Add configurable colors for branch prefixes

### ISSUE THREAD

**Issue by matt-cles** [jesseduffield/lazygit#1634]
**Is your feature request related to a problem? Please describe.**
Currently, there are 3 branch prefixes that will render the branch name in a color other than the default. (green for feature, red for hotfix, and yellow for bugfix). I would like to be able to set additional colors for different branch prefixes

**Describe the solution you'd like**
I would like for there to be a section in the config file for assigning colors to different prefixes. I imagine this would be similar to assigning different colors to different users

**Describe alternatives you've considered**
Additional other branch prefixes could be added to the current switch statement, but that would be less configurable for anyone else wanting different colors for different branch prefixes

**Additional context**
Here is a mock up of what it could look like with additional prefixes having different colors:
![image](https://user-images.githubusercontent.com/70937327/147320613-8d89ba4d-fab9-4668-9eb9-33234a4dec2e.png)

**Comment by matt-cles** [comment]
Also, this is something I would like to try to contribute. I don't have much experience in Go, but my plan would be to look into how the user color configuration is set up and replicate that in the branches.go file for changing the branch color

**Comment by basseX** [comment]
I'm on @matt-cles on this one. Assigning colors to different prefixes would be a nice feature.

**Comment by jesseduffield** [comment]
Sorry for the delay getting back to this. This sounds like a great feature. It should be fairly straightforward to implement: we have a similar config for commit author colours in `pkg/config/user_config.go` (search for the `AuthorColors` field). That maps a name to a hex colour and here we could instead map a branch prefix to a hex colour. Then in `GetBranchTextStyle` in `pkg/gui/presentation/branches.go` we would take that mapping into consideration (we would need to pass the user config through as an arg to `GetBranchListDisplayStrings` so we can access it from within).

@matt-cles if you're still up to contribute let me know, I can give you any pointers you need

**Comment by matt-cles** [comment]
Yes I am still interested in contributing this! Thanks for the info on the starting point, I'll be sure to reach out if I get stuck

**Comment by matt-cles** [comment]
I've created a PR for this feature: https://github.com/jesseduffield/lazygit/pull/1744

Please let me know if I need to change anything in the PR. This was my first time working with Go so hopefully what I did makes sense for the end result I was going for!

**Comment by jesseduffield** [comment]
closing as this is now in master
