### ISSUE TITLE
Execution  lazygit command error

### ISSUE THREAD

**Issue by ConanEdogawa1** [jesseduffield/lazygit#1657]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: mac os
 - Lazygit Version [e.g. v0.1.45]
 - The last commit id if you built project from sources (run : ```git-rev parse HEAD```)

**Additional context**

*errors.errorString repository does not exist
/home/runner/work/lazygit/lazygit/main.go:141 (0x167be5b)
/opt/hostedtoolcache/go/1.16.10/x64/src/runtime/proc.go:225 (0x1038396)
/opt/hostedtoolcache/go/1.16.10/x64/src/runtime/asm_amd64.s:1371 (0x106c181)

**Comment by mark2185** [comment]
Please try out `v0.35` to see if it still happens.

If it does, please reopen the issue _and fill out the issue template_.

**Comment by amplexus** [comment]
I got the same error on both new (`git init`) and existing repos. Running Ubuntu 22.04.

I was using the snap version, which is 0.34. I uninstalled that and then downloaded the latest github build (0.36) and the problem went away.

**Comment by craigmac** [comment]
Same errors here on fresh 22.04.4 LTS Ubuntu, after doing `snap install lazygit`. Lazygit won't start and keeps reporting 'repository does not exist' and crashing:

```
2024/07/09 15:53:46 An error occurred! Please create an issue at: https://github.com/jesseduffield/lazygit/issues

*errors.errorString repository does not exist
/build/lazygit/parts/lazygit/build/main.go:145 (0x9de7d6)
/snap/go/9415/src/runtime/proc.go:250 (0x4389b2)
/snap/go/9415/src/runtime/asm_amd64.s:1571 (0x466281)
```

This is in a freshly created git folder in ~/.local/tmp/ just to see if it was a permissions thing.
