### ISSUE TITLE
Mysterious crash on push

### ISSUE THREAD

**Issue by Axel-Jacobsen** [jesseduffield/lazygit#166]
**Describe the bug**
On trying to push a relatively large commit (some large photos, code changes), there was a panic crash. Unfortunately, I started the push and then walked away, so I can't be super descriptive. Sorry!

**To Reproduce**
I am not sure the steps; my best guess would be to
1. Create a large commit (perhaps several large photos)
2. Push
but I have pushed larger w/ lazygit so that may not be the reason.

**Expected behavior**
A successful push to GitHub

**Screenshots**
<img width="801" alt="screen shot 2018-08-16 at 6 47 31 pm" src="https://user-images.githubusercontent.com/20530172/44243681-31060300-a185-11e8-9e6e-bd6a4ede1244.png">

**Desktop (please complete the following information):**
 - OS: MacOS
 - `lg -v`
--> `commit=ed6f21ee7437b4305c7048615eb218d2a2edeae2, build date=2018-08-09T13:35:18Z, version=0.1.48`

**Comment by jesseduffield** [comment]
I just checked out that commit and tested pushing a 10mb file, but it pushed fine. I would update to the latest version and see if the issue arises again. Are you cool for me to close this issue and re-open if it pops up again?

**Comment by Axel-Jacobsen** [comment]
Yea for sure! thanks for the eye
