### ISSUE TITLE
Highlighting missing for current selected menu item

### ISSUE THREAD

**Issue by JeppeSRC** [jesseduffield/lazygit#1661]
After a clean install of Windows 10 Version 21H2 the highlighting which shows which line you're on in a menu. For instance which file you're staging in the Files menu.

I've tried older versions and none work. It used to work before I reinstalled windows.
Switching to the legacy console makes it work again, but as I said it used to work with the non-legacy console before.

With normal console:
![image](https://user-images.githubusercontent.com/6404138/148644483-326c2278-c5cd-456c-9a99-57986a1c89e2.png)

Legacy console with the expected result:
![image](https://user-images.githubusercontent.com/6404138/148644520-70154b08-a108-40ec-98ed-e1fddc6c7f39.png)

**Comment by jesseduffield** [comment]
I believe this PR solves that problem https://github.com/jesseduffield/lazygit/pull/1656 and that's now been merged to master. Are you able to build from master and see if that fixes the issue?

**Comment by JeppeSRC** [comment]
Yeah, no worries thanks.
