### ISSUE TITLE
Attempting to patch an older commit with a hunk from a newer commit causes error "amiguous argument ..."

### ISSUE THREAD

**Issue by adamakhtar** [jesseduffield/lazygit#1666]
**Describe the bug**

When attempting to patch a commit with code from another commit Lazygit displays an error:

<img width="661" alt="image" src="https://user-images.githubusercontent.com/238342/149068334-92b4d73d-6bd4-4104-a8b0-191c19b576cf.png">

https://user-images.githubusercontent.com/238342/149068253-63e46fe4-4f74-48c7-bdff-265ac60cf04f.mp4

The repo in question is just a simple repo to learn Lazygit. I created a simple repo with one file. The first commit defines a method. The second commit adds an extra line to the method. That's all. 

**To Reproduce**
Steps to reproduce the behaviour:

1. In the commit history panel select the second commit and press enter twice to edit a patch and add the line added into the patch. 
2. Press escape twice to return to the commit panel 
3. Highlight the first commit 
4. Press ctrl+p and choose to "move patch to selected commit"
5. Error is shown 

**Expected behavior**

To apply the patch's code to the selected commit. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac Big Sur 11.6 (M1 Silicon)
 - Lazygit Version v0.31.4

**Comment by jesseduffield** [comment]
The issue here is that it's trying to get the parent of the root commit. There is actually a special commit hash reserved for this (undocumented). There's a PR taking a stab at fixing this issue (or at least a very related one) but it's unfortunately gone stale https://github.com/jesseduffield/lazygit/pull/1483/files

**Comment by adamakhtar** [comment]
Thanks @jesseduffield its not critical for me but just wanted to see if this was a known issue or an error on my part. I'll keep an eye out on that PR for now. Thanks for creating this great tool. Really love using it.

**Comment by stefanhaller** [comment]
I'm pretty sure this has been fixed in 0.38. I'm too lazy to look up the exact PR right now, let me know if you want to know more.
