### ISSUE TITLE
Edit file jumps current cursor line

### ISSUE THREAD

**Issue by mark2185** [jesseduffield/lazygit#1671]
**Is your feature request related to a problem? Please describe.**
When partially adding a file, I would sometimes like to edit the current line before adding it, pressing `e` opens the file in `$EDITOR` which is for me `vim`, but the cursor is at the start of the file.

**Describe the solution you'd like**
`vim` can take an argument in the form of `+135` which puts the cursor on the 135th line.

**Describe alternatives you've considered**
I tried pressing `o` to _open_ the file, but then `lazygit` crashes because it tries to run `xdg-open filename:135`, which fails, and the error isn't handled well, I guess.

**Additional context**
Should I open a separate issue for `xdg-open filename:135` causing a crash?

**Comment by jesseduffield** [comment]
There is a section in the docs for configuring this to your editor: https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md#configuring-file-editing

However it sounds like we should have some sensible built-in defaults for the common editors like vim, vscode, sublime, emacs, etc. I'll chuck a good-first-issue label on this for that purpose.

For anybody who wants to tackle this issue, the relevant method is `GetEditCmdStr` in `pkg/commands/git_commands/file.go`. We can check to see if `editCmdTemplate` is set to the default (i.e. `{{editor}} {{filename}}`) and if so, refer to a list of editor-specific templates.
