### ISSUE TITLE
Diverged multiple branches: push force pushes all

### ISSUE THREAD

**Issue by oscarmlage** [jesseduffield/lazygit#1673]
**Description**

If you have different branches, more than one are diverged from origin and then you try to force push just one of them, lazygit performs a force push to the other branches too. Result: I think not only the branch you selected to force push performs it, but all of them.

**To Reproduce**

1. Init a new repo and clone it to your computer (we'll call it local)
2. Create a couple of branches, let's say we have `main`,` branch1`, `branch2`
3. Commit and push some stuff from local to origin in `main` and `branch1`
4. Push some stuff to origin from other source in `main`
5. Push some stuff to origin from other source in `branch1`
5. **Without any pull**, commit some stuff from local in `branch1` (we're trying to create a divergence in `branch1`)
6. On lazygit, **with the cursor on `branch1`**, press `P` to push the changes in local to origin
  6.1. Note that 
  6.2. Note, need to have the `disableForcePushing: false` in order to allow you to force pushing
  6.3. It says that it performed a `git push --force-with-lease` in the command log
7. Note that not only `branch1` has been pushed, `main` has been force pushed too
8. Result: `branch1` is ok, because is the one we wanted to "forcepush" but `main` is not ok, we lose all the changes we had in the remote.

**Expected behavior**

In my mind I expected to "forcepush" only the selected branch (`branch1`), not all of them, but maybe is the way git works (dunno to be honest).

**Desktop (please complete the following information):**
 - OS: macOS 12.1
 - Lazygit Version 0.31.4

**Comment by oscarmlage** [comment]
Note: This issue is related - in a way - with #1668 where I was asking to disable force push by default because I had this issue. The only doubt I have right now if it's a bug or it is the way git works by default.

**Comment by jesseduffield** [comment]
You can configure in your git config to only push to the current branch, however I think it's sensible to have lazygit always specify the remote and remote branch to push to. I've started on a PR for this here: https://github.com/jesseduffield/lazygit/pull/1674

**Comment by jesseduffield** [comment]
fixed in v0.32.2
