### ISSUE TITLE
Colours not always rendering correctly (mosh + tmux)

### ISSUE THREAD

**Issue by peppy** [jesseduffield/lazygit#1679]
**Describe the bug**

Background colours don't always end when they should in the terminal. I think this may be an issue with the terminal emulator itself (Blink on iOS, also reported https://github.com/blinksh/blink/issues/1334) but I could have sworn I saw a PR or commit message recently mentioning something about colour compatibility so posting this issue for visibility at this side.

If this is a case of not-my-issue then feel free to close this.

**To Reproduce**
1. Open Blink
2. Start a `mosh`session to a host
3. Open `tmux`
4. Start lazygit
5. Have commit messages with author colouring visible

**Screenshots**

https://user-images.githubusercontent.com/191335/149616636-4508d427-6bc7-46eb-88b6-7bcda434b0a5.MOV

In the video, I show the broken behaviour via `mosh`, then switch to `ssh` to show it works correctly there. Note that I can't repro similar breakage on any other app, including a true colour vim instance.

**Comment by jesseduffield** [comment]
Not sure if it's a bug with the terminal emulator itself, but we could provide a config option to lock the randomised commit author colours to 16 colours, assuming it's the RGB colours that cause the issue.

**Comment by peppy** [comment]
I haven't investigated further, but if everything looks correct from lazygit's end then that's probably the case.

Am I dreaming that I saw a recent effort to improve colour compatibility? May have been a notification from another project I miscategorised in my head..

**Comment by peppy** [comment]
I've made a local fix for this for now, it does definitely look to be something incorrect with the terminal emulation in this case, as I can't repro with three other terminal emulators I tested.

**Comment by jesseduffield** [comment]
@peppy there was some discussion about having 16 colours for randomised author colours in another PR and I suggested the person to raise an issue about it (though I haven't checked if they did), so it's possible that that's what you're recalling
