### ISSUE TITLE
Feature: use repo name as application (window) title?

### ISSUE THREAD

**Issue by birgersp** [jesseduffield/lazygit#1691]
**Is your feature request related to a problem? Please describe.**
Each of the applications in my taskbar has a title. For instance an instance of Firefox has the same title as the webpage that is currently open. So I have the icon to know that it's Firefox and I have the text that shows me that the loaded webpage is Github. This is useful, because sometimes you have multiple instance of an application opened and you need to distinguish them from one another. The lazygit application does not have a "title". The text by the icon is the path to the lazygit executable.

**Describe the solution you'd like**
I would like the lazygit application in my taskbar to display the name of the currently open repo.

**Describe alternatives you've considered**
None.

**Additional context**
I'm on Windows 10.
![image](https://user-images.githubusercontent.com/5260237/149911298-0d12ca65-72a5-4816-9064-80700b1008a7.png)

**Comment by jesseduffield** [comment]
I'm on a mac so I'm not very across how this would work in windows. Happy to accept a PR though :)

**Comment by birgersp** [comment]
Never touched golang before but I'll do my best.

lazygit is a masterpiece btw

**Comment by jesseduffield** [comment]
you're too kind! Let me know if you need any guidance

**Comment by birgersp** [comment]
So this is a way to set the title for the application. Works in cmd and PowerShell terminals.

```
cmdTitleSet := exec.Command("cmd", "/C", "title", "your_title_here")
errTitleSet := cmdTitleSet.Run()
if errTitleSet != nil {
	fmt.Println(errTitleSet.Error())
}
```

Next steps is to figure out
a) Where it is appropriate to put this code
b) How to obtain the "repo name" to use as title

**Comment by jesseduffield** [comment]
left comments on the PR :)
