### ISSUE TITLE
Light theme regression - can't see all of the selected/highlighted line

### ISSUE THREAD

**Issue by kkonopko** [jesseduffield/lazygit#1694]
Highlighted content is invisible - a regression caused by the following commit: 7539929703d76b4228a034ca7524293744839c3d

Found by bisecting with Git.

**Expected behavior**
Highlighted context should be visible (in bold).

**Screenshots**
![2022-01-18-135715_grim](https://user-images.githubusercontent.com/2945452/149942545-e82e9c09-91bb-490e-b436-324aa0d2c6cf.png)

**Desktop:**
 - OS: Linux (sway/alacritty)
 - Lazygit Version v0.32.1 and mainline
 - The last commit id build: b5a8ecf786a7d7593060684029ba97abd7ad093a
 
**Additional context**
None of the following helps:
https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md#light-terminal-theme
https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md#struggling-to-see-selected-line

**Comment by jesseduffield** [comment]
@Kavantix do you know what might cause this to happen?

**Comment by Kavantix** [comment]
@kkonopko can you share the 16 colors of your terminal theme?

**Comment by kkonopko** [comment]
I'm using 256-color palette (if that matters?) and exactly this color scheme for Alacritty: https://github.com/aarowill/base16-alacritty/blob/master/colors/base16-ia-light-256.yml

I'm not working with colors much myself (other than just being a user), so a handy snippet to run in the terminal would be useful, if you want me to provide more/other info.

**Comment by Kavantix** [comment]
As I suspected this is simply caused by your theme.
Your bright white color (line 34 in the file you linked) is almost the same as your background color.
To get the best experience try making all the bright colors distinct from the normal colors.
Or for a simple fix to get the bright color to match the normal color replace line 34 with `    white: "0x181818"`

**Comment by kkonopko** [comment]
I see.  I guess without your change there's no additional color highlighting (otherwise achieved with a bold font only)?  And other terminal apps I use do not use bright colors (no other app is causing problems for me)?

I also guess you can never get this right for every theme possible if the theme's settings make some of the colours useless?
Ie. indeed in my case bright white seems to be botched in the theme:
![2022-01-19-105747_grim](https://user-images.githubusercontent.com/2945452/150107925-4590d487-dc0d-421d-a8c7-759b611d8e2e.png)

Also something to consider could be to check the "distance" between the background and bright color before trying to use it, ie. if they are to close, give up on using the bright alternative and stick with the default.

**Comment by kkonopko** [comment]
In the end I selected a different theme with saner default for the bright white.

**Comment by Kavantix** [comment]
Probably the best solution @kkonopko 
@jesseduffield I believe this can be closed.

Btw @kkonopko we cannot know the actual values of those 16 colors so there is no way to check the distance.
And indeed many programs don’t make use of the bright colors
