### ISSUE TITLE
Custom services do not work anymore

### ISSUE THREAD

**Issue by bin101** [jesseduffield/lazygit#1695]
**Describe the bug**
I have two gitlab instances configured but during creation of a pull request or opening a commit I will be redirected to gitlab.com instead of the configured instance.

**To Reproduce**
1. configure a custom pull request url:
```
services:
  '<gitDomain>': '<provider>:<webDomain>'
```
2. Try to open a pull request
3. See error

**Expected behavior**
I should be redirected to the configured instance.

**Desktop (please complete the following information):**
 - OS: Windows/Linux/macOS
 - Lazygit Version 0.32.2

**Last working version**
0.31.4

**Comment by jesseduffield** [comment]
What's the repo url for your instance (if it's not confidential)?

I suspect we just need to check against the configured instances before checking against the defaults in `pkg/commands/hosting_service/hosting_service.go` (`getCandidateServiceDomains function`). I'll add a good-first-issue label

**Comment by bin101** [comment]
Sry but both instances are confidential.

**Comment by bin101** [comment]
The issue is here:
https://github.com/jesseduffield/lazygit/blob/1f923bdc4ba96ad21846797aadfacf5ecb3890e1/pkg/commands/hosting_service/hosting_service.go#L85

Just adding the defaultServices after the custom ones wouldn't help because if I configure two gitlab services the first one would be pulled for both cases.
