### ISSUE TITLE
Document how to debug lazygit

### ISSUE THREAD

**Issue by birgersp** [jesseduffield/lazygit#1697]
**Topic**
(Title)

**Your thoughts**
Sorry if this is really obvious and/or well documented. But how to debug this project while actually seeing the UI is totally lost on me. I am using VSCode with the Go extension. I can run a debug session and any output (with `fmt.Println`) is written to the "debug console". But I am not seeing the lazygit UI anywhere. But if I run `go run main.go` in the terminal (either VSCode's internal or in different terminal) then I can see the UI but there is no debugging available.

How do you guys debug this project while running its UI?

**Comment by birgersp** [comment]
This helped: https://github.com/golang/vscode-go/issues/124#issuecomment-1006122877

**Comment by jesseduffield** [comment]
You can also pass a `-debug` flag to lazygit and then in another terminal window run `lazygit --logs` to see a stream of logs. Most parts of the codebase have access to a log field e.g. `gui.log.Warn("blah")`.

**Comment by jesseduffield** [comment]
I've reopened and changed the title to be about documenting this process

**Comment by birgersp** [comment]
Okay. For future readers this is the launch configuration that made me able to debug while viewing the UI in VSCode.

```
// .vscode/launch.json
{
	"version": "0.2.0",
	"configurations": [
		{
			"name": "debug lazygit",
			"type": "go",
			"request": "launch",
			"mode": "auto",
			"program": "main.go",
			"console": "externalTerminal" // <-- you need this to actually see the lazygit UI in a window while debugging
		}
	]
}
```

(Note that as I am writing this, `console` is not yet added to the stable version of the VSCode Go extension. [Look here](https://github.com/golang/vscode-go/issues/124#issuecomment-1006122877). It will probably be added to stable version soon, though)

**Comment by jesseduffield** [comment]
Updated the documentation in https://github.com/jesseduffield/lazygit/tree-save/master/CONTRIBUTING.md. I'll close this issue
