### ISSUE TITLE
Color scheme

### ISSUE THREAD

**Issue by Kriechi** [jesseduffield/lazygit#17]
I'm using the Solarized Light color scheme for my terminal - which unfortunately doesn't work well with the color map of lazygit in many sections of the GUI:
<img width="832" alt="screen shot 2018-08-05 at 12 20 51" src="https://user-images.githubusercontent.com/114300/43684939-1513e0b0-98aa-11e8-8f67-b370a7116e0f.png">

Please not the (at least for my eyes) unreadable blue status bar text, and very faint text in the Status/Branches/Commits sections.
It would be great if we could configure individual colors or select a color profile / palette!

**Comment by jesseduffield** [comment]
yes this is definitely something I want to implement. I'm not sure how long it would take for me to do an audit on all the references to colour in the app and replace them with config-based values, but I'll hopefully get to have a look at it soon. In the meantime there are alternative themes available which work better with ANSI colours. For example the default solarised light theme in iterm is a little more palatable
![solarised](https://user-images.githubusercontent.com/8456633/43686852-a6f0f472-990f-11e8-9288-902f4106b926.png)

**Comment by jesseduffield** [comment]
I've made some minor color changes that might make the application easier on the eyes, and I've made a milestone for the bigger task of having configurable colour schemes

**Comment by jesseduffield** [comment]
I think colours are configurable enough now for this to be closed, but if not, let me know

**Comment by tmartty** [comment]
Sorry to re open this but I was wondering whether pushed & not-pushed commits colors are configurable or not. I'm colorblind (Deuteranopia) and I usually have a hard time telling if a commit has been pushed or not.

Would be awesome if it could be configurable!
