### ISSUE TITLE
Automaticly generate version

### ISSUE THREAD

**Issue by glvr182** [jesseduffield/lazygit#171]
**Is your feature request related to a problem? Please describe.**
I saw the version is done semi-manually in the main. This could be done with go generate aswell. 

**Describe the solution you'd like**
A go generate action that changes the version.  

**Describe alternatives you've considered**
I've considerd hard-coding the version which is fine aswell. This could be stored 
in a seperate go file if that is wanted

**Additional context**
Nothing

**Comment by jesseduffield** [comment]
We were storing the version in a file in case you build the binary from sources, but the binaries built by goreleaser get the version baked in via ldflags (see https://www.atatus.com/blog/golang-auto-build-versioning/). So goreleaser just grabs the version from the tag and stores that as a variable in main.

see discussion at the end of https://github.com/jesseduffield/lazygit/pull/179

We're just gonna scrap the use of the VERSION file altogether; if somebody built the binary from sources, they'll have access to the commit hash and that's gonna be easier to debug with than the version number
