### ISSUE TITLE
Current progress in conflict resolution interrupted by `refreshInterval`

### ISSUE THREAD

**Issue by peppy** [jesseduffield/lazygit#1718]
**Describe the bug**

Each refresh, the current position of conflict resolution will be reset. May also apply to other visual interfaces.

**To Reproduce**
1. Set `refreshInterval` low
2. Try and resolve a conflict

With refresh set to 5 seconds:

![20220124 203452 (iTerm2)](https://user-images.githubusercontent.com/191335/150776001-070b8637-1882-4853-a7de-9787466d230b.gif)

**Desktop (please complete the following information):**
 - OS: macOS
 - Lazygit Version `HEAD`
 - The last commit id if you built project from sources 61ccc1efd287b022cf29059914788152fb9f09ad

Why do I have refresh set to 5? lazygit doesn't generally see changes otherwise. I'd probably set it lower if it wasn't for this issue.

**Comment by jesseduffield** [comment]
Fixed on master. I might make another issue about the frequent-refresh thing.

Lemme know if you have any issues with the new logic

**Comment by peppy** [comment]
Looks to be working well, thanks!
