### ISSUE TITLE
Option to always show unstaged/staged panels

### ISSUE THREAD

**Issue by sdegutis** [jesseduffield/lazygit#1721]
I like to scroll through files and look at either all staged, or all unstaged, while also seeing the relation to each other. This request is to make this at least an option.

**Comment by jesseduffield** [comment]
(Sorry, added this to the wrong issue before)

Makes sense, I've added a good-first-issue label. Relevant place to update the code is in the `filesRenderToMain` function in `pkg/gui/files_panel.go`. We need to be unconditionally setting `refreshOpts.secondary` to a value (even if it's rendering nothing) if a user config value is set that says we should always show staged and unstaged changes in separate panels. 

We could call the user config 'SplitDiff' with 'always' and 'auto' as possible values. We can chuck it on GuiConfig in `pkg/config/user_config.go`

**Comment by HiromasaNojima** [comment]
@jesseduffield 
Hi! I'd  like to tackle this issue!

**Comment by jesseduffield** [comment]
@HiromasaNojima awesome! Reach out if you need any pointers
