### ISSUE TITLE
Rename should not show diff as file being added

### ISSUE THREAD

**Issue by sdegutis** [jesseduffield/lazygit#1722]
Renaming a file shows the staged changes diff as the entire file contents being added. It should do a diff of only what changed (if any) like `git diff --cached` does.

**Comment by jesseduffield** [comment]
Makes sense, I've added a good-first-issue label. Relevant place to update the code is in the `filesRenderToMain` function in `pkg/gui/files_panel.go. We need to be unconditionally setting `refreshOpts.secondary` to a value (even if it's rendering nothing) if a user config value is set that says we should always show staged and unstaged changes in separate panels. 

We could call the user config 'SplitDiff' with 'always' and 'auto' as possible values. We can chuck it on GuiConfig in `pkg/config/user_config.go`

**Comment by StefanMich** [comment]
I would like to take a look at this :)

**Comment by jesseduffield** [comment]
@StefanMich feel free :) let me know if you need any pointers

**Comment by mark2185** [comment]
@sdegutis could you try building the current `master` and see if #1859 solves the problem?

**Comment by sdegutis** [comment]
Not for like a few weeks. Very swamped.

**Comment by PatrickF1** [comment]
I believe this was successfully fixed #1859, can close this now.
