### ISSUE TITLE
Ability to choose the default branch name when creating a new repo

### ISSUE THREAD

**Issue by enkeyz** [jesseduffield/lazygit#1724]
**Is your feature request related to a problem? Please describe.**
Lazygit names the default branch `master`

**Describe the solution you'd like**
Would be nice to choose the default branch name when creating a new git repo with lazygit: the default branch name lazygit chooses right now is `master`.

**Comment by jesseduffield** [comment]
You can set a default in your git config with `init.defaultBranch`. I'm pretty sure lazygit will honour that. Does that suffice for your use case, or would you like to be able to type in a branch name? I assume most people go with master/main

**Comment by enkeyz** [comment]
Yeah, it would be nice to type the branch name when creating a repo.
