### ISSUE TITLE
Clarify on wording: "If you're using git, that makes you a programmer"

### ISSUE THREAD

**Issue by bnoctis** [jesseduffield/lazygit#1756]
I'm sorta confused by the Chinese translation of the popup message on first run.

Chinese version: https://github.com/jesseduffield/lazygit/blob/9adf4a190864fd0c6a3b00ef46f23e93b0e6a5f5/pkg/i18n/chinese.go#L24

English version: https://github.com/jesseduffield/lazygit/blob/9adf4a190864fd0c6a3b00ef46f23e93b0e6a5f5/pkg/i18n/english.go#L577

**如果您使用 git，这将使您成为一名程序员！** translated back to English is "If you use git, that (fact) will _make you become_ a programmer!". However, to my understanding, the original English version means "If you are using git, that (fact) _means_ you are (already) a programmer", supposedly translated as **使用 Git 说明您是一位程序员**, which also fits better into the context, in my opinion.

**Comment by mjarkk** [comment]
@black-desk what do you think?

**Comment by black-desk** [comment]
lgtm

**Comment by mjarkk** [comment]
@bnoctis you are welcome to create a PR for this

**Comment by bnoctis** [comment]
@mjarkk Here it goes (#1757). Did a little polish along with it. 🐯

**Comment by mjarkk** [comment]
I think this is fixed now
