### ISSUE TITLE
Using gitflow in the project itself

### ISSUE THREAD

**Issue by glvr182** [jesseduffield/lazygit#176]
**Is your feature request related to a problem? Please describe.**
Not related to any problem, just an idea.. We could use the gitflow mechanics to
structure the project even better.

**Describe the solution you'd like**
I've been using the gitflow for a while now and I think it's really helpfull

**Describe alternatives you've considered**
The other flows.

**Additional context**
It's just an idea and I'd love to hear what others think about it.

**Comment by jesseduffield** [comment]
I use gitflow insofar as I prefix branch names with feature/ and hotfix/ but that's about it. I'm not actually familiar with what gitflow would look like in the context of this project. Any pointers?

**Comment by glvr182** [comment]
Heres a good link to [atlassian's explanation](https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow) about gitflow.

What would be different is you would make your master branch less active, only pushing to there when you have a release. The develop branch would then be your "main" branch. Then developers branch off from that with a feature/ prefix (as u already do now). When it's time to release you just merge develop to master and tag a version on the master.

This is a short version of the link I sent, I recommend reading that one and may the other flows aswell they are pretty interesting

**Comment by glvr182** [comment]
Also before this issue gets too long we could talk about it on slack or smthing

**Comment by jesseduffield** [comment]
I've had a read of that article and I'm down. I've made a develop branch and I'll start branching off these. The only annoying thing I can see with git flow is that you need to make a new release branch for every hotfix, and currently I'm pushing out a lot of hotfixes (although come to think of it I need to tag each hotfix deploy anyway so it's not like it's that much more overhead to make a release branch for it). In terms of semantic versioning, would I be correct in assuming that typically hotfix deploys would correspond to patch numbers, whereas feature deploys would correspond to minor/major numbers?

**Comment by remyabel** [comment]
At work we did something similar to this. Master was protected, you could only merge into master using pull requests. The idea is that master is "clean" (a broken build should never be committed to master) while all of the actual work is done on other branches. The other advantage is that this facilitates backporting. If somebody is running an older/stable version of lazygit, you can cherry-pick hotfixes easily.

**Comment by glvr182** [comment]
@remyabel Same here, it's a handy system imo. Only downside is we would have to clean the branches and issues/pull requests once (now) and then we can organize everything perfectly. In my opinion worth it!!

**Comment by remyabel** [comment]
Yeah, with the "commit at least once a day" it can easily get messy. Multiple people working on feature branches should regularly push their updates so that others can ensure that they're not going in the wrong direction. This only makes sense for collaborators; for non-write access, a pull request with "[NO MERGE]" would be equivalent. Since most people won't have write access, the messy branches shouldn't be an issue. 
For PR's the scheme we followed (but there are others) is to use "#issuenumber_short_description_of_issue". Then you can do "Fixes #issuenumber" when merging the PR and it'll automatically close the issue.

**Comment by glvr182** [comment]
@jesseduffield Yes semver is as following:
x.y.x

X: MAJOR 
  This means a change has been made with (likely) the API aswell resulting in a backwards incompatible system.
Y: Minor
  This means a change has been made that was likely a new feature or addition. Not a bugfix
Z: Patch
  Patches are as stated patches, they fix a bug and are not that big in terms of deltas (usually).

See [semver](https://semver.org/) for a proper explanation

**Comment by glvr182** [comment]
@jesseduffield @remyabel We could have a convo on slack or anyother mean to discuss it easier. If we are going to switch to that it has to be well planned and I'd happily make a lil plan with you guys

**Comment by glvr182** [comment]
Discord would work for this aswell

**Comment by jesseduffield** [comment]
@glvr182 yeah happy to move this to slack and what comes of it we can chuck in the contributor guidelines

**Comment by glvr182** [comment]
TODOLIST at #184
