### ISSUE TITLE
the Ignore feature,adds a file to the gitignore for the repo, not working

### ISSUE THREAD

**Issue by tbxy09** [jesseduffield/lazygit#177]
**Describe the bug**
the Ignore feature,adds a file to the gitignore for the repo, not working'

**Describe the bug**
here is what I found now,
rm  the commits "refactor commands to depend less on the shell" related to the
"RunDirectCommand" in os.git, issue gone
this commits changes seems to make the quote "" in command line disappear, and also fail the command.

**To Reproduce**
1. active files window
2. type 'i', the ignore feature binding key
3. the expected is to see files list refresh with the selected item deleted
4. nothing happend

**Expected behavior**
the expected is to see files list refresh with the deleted item

**Screenshots**
NA

**Desktop (please complete the following information):**
 - OS:linux
 - Lazygit Version
commit=, builddate=, version=v0.1.64

**Additional context**
NA

**Comment by glvr182** [comment]
Can you check if the latest version has this issue aswell?

**Comment by jesseduffield** [comment]
I've fixed this in https://github.com/jesseduffield/lazygit/pull/187
Pushing up a new release now :)

**Comment by tbxy09** [comment]
no, issue gone, works fine now~~~

**Comment by jesseduffield** [comment]
Closing :)

**Comment by tbxy09** [comment]
sorry for the late response, and thanks all. it's a very cool git tool, really enjoy using it.
