### ISSUE TITLE
`lazygit` generating load after `pull`

### ISSUE THREAD

**Issue by hboetes** [jesseduffield/lazygit#1779]
Hi there,

I've just noticed `lazygit` is keeps doing something after 'pulling'. If I run `htop` at the same time it's not doing anything, until I pull and then the CPU load goes up to about 10%. I've started `strace -o foo lazygit` and `tail -f goo` to see what it does, but `strace` doesn't notice any syscalls.

I've noticed the same behaviour on both OpenBSD and Linux. I'm using the latest build from git.

Thanks for looking into this peculiar behaviour.

**Comment by Ryooooooga** [comment]
solved in https://github.com/jesseduffield/lazygit/pull/2345
