### ISSUE TITLE
[Feature Request] Get  message of last commit in the commit popup

### ISSUE THREAD

**Issue by devansh08** [jesseduffield/lazygit#1780]
**Is your feature request related to a problem? Please describe.**
Not exactly a problem but something I am used to doing with other tools (like VSCode's git integration) and would like to see if it can be done here too :)
Usually my commits would contain repeatable phrases about the task I'm working on like ticket number, pairs/authors etc. So its quite useful to just pick up my last commit and edit out the description while leaving the prefix/suffix as it is.

**Describe the solution you'd like**
After opening the commit popup if I press the Up arrow the message of the last commit (and maybe cycle through the older commits ?) pops up and I can make some minor adjustments to that. 

**Describe alternatives you've considered**
I dont really know of any way that I can get my previous commit outside of a copy/paste approach. Pls let me know if there is already something like this :)

**Additional Context**
With the Up arrow approach (can be anything else too if its easier) the trigger to populate the last message should be if its pressed while the cursor is at the first character, so that editing a multi line commit message does not break. Also, maybe have a Down arrow impl to come back to where we were if Up is accidentally pressed ? Pls let me know your thoughts.

**Comment by MuhammadSawalhy** [comment]
I need such a feature as well

**Comment by mark2185** [comment]
I vote for having mappings other than `Up/Down` for such navigation, so it's not done by accident more often than not.

Many unix tools use `ctrl+p` for previous and `ctrl+n` for next, that might be a good alternative.

**Comment by stefanhaller** [comment]
We have up/down arrow in the new commit message panel. I actually don't know when it was added, and I'm too lazy to check. Closing this, feel free to reopen if there's still something missing.
