### ISSUE TITLE
[Feature Request] Better input field, e.g. for commit message

### ISSUE THREAD

**Issue by MuhammadSawalhy** [jesseduffield/lazygit#1783]
**Is your feature request related to a problem? Please describe.**

I want to use some of the keybindings and shortcuts that are available in the terminal for example delete a word using <kbd>Ctrl</kbd><kbd>w</kbd> or deleting till the end of the line <kbd>Ctrl</kbd><kbd>u</kbd> are not working, ...etc. 

https://user-images.githubusercontent.com/42011920/154994698-29465721-173f-47ae-a8ef-e5c4121023a3.mp4

Also, I am struggling with editing a multiline commit message with the built text input field.

![image](https://user-images.githubusercontent.com/42011920/154974128-62ccb934-8968-4f9e-8dd9-88f2f2bfeae6.png)

**Describe the solution you'd like**

To easily edit my commit message. And it is better to provide an easy way to configure the keybindings in the input field, which I prefer to be vim-like keybindings, so there will be _"normal"_ and _"insert"_ mode.

**Describe alternatives you've considered**

I will reword my commit with my editor, for now, <kbd>R</kbd>.

**Comment by Ryooooooga** [comment]
https://github.com/jesseduffield/gocui/pull/16
