### ISSUE TITLE
no matching versions for query "v0.33"

### ISSUE THREAD

**Issue by smartding** [jesseduffield/lazygit#1787]
**Describe the bug**
go install fails with latest version.

**To Reproduce**

Run the following command:  
```sh
go install -ldflags "-s -w" github.com/jesseduffield/lazygit@v0.33
```
**Expected behavior**

The latest version is v0.33, I expect the above command to succeed.

**Desktop (please complete the following information):**
 - OS: gentoo linux
 - Lazygit Version 0.33

**Additional context**

If I install an older version with go install, the command succeeds, e.g.  `go install -ldflags "-s -w" github.com/jesseduffield/lazygit@v0.32.2`

**Comment by fsmiamoto** [comment]
I think this is happening because the `pkg.go.dev` registry is still reporting `v0.32.2` as the latest version as of today:
![image](https://user-images.githubusercontent.com/20388082/159186413-9a1c838d-8676-4a98-a249-ff678b0900c8.png)

Maybe we need to add to our CI/CD pipeline a request to the registry  to make sure the latest version is present there

**Comment by fsmiamoto** [comment]
Doing something like this should do the trick but is not working for some reason for 0.33:
```sh
$ curl https://proxy.golang.org/github.com/jesseduffield/lazygit/@v/v0.32.info
{"Version":"v0.32.2","Time":"2022-01-17T08:24:10Z"}%

$ curl https://proxy.golang.org/github.com/jesseduffield/lazygit/@v/v0.33.info
not found: module github.com/jesseduffield/lazygit: no matching versions for query "v0.33"%
```

**Comment by jesseduffield** [comment]
weird. Does it still fail if you go `GOPROXY=direct go install ...`?

**Comment by smartding** [comment]
> weird. Does it still fail if you go `GOPROXY=direct go install ...`?

`go install` still fails with `GOPROXY=direct`

**Comment by smartding** [comment]
@jesseduffield
Any update on this issue?
I just checked and pkg.go.dev registry is still reporting v0.32.2 as the latest version as of today.

**Comment by smartding** [comment]
v0.35 can now be installed with go install, while v0.33 and v0.34 still can't.
