### ISSUE TITLE
Weird behavior when .gitattributes error

### ISSUE THREAD

**Issue by dmun** [jesseduffield/lazygit#1788]
**Describe the bug**
When there's a .gitattributes error you are not able to stage certain files for some reason.

**To Reproduce**
1. Make sure you have a .gitattributes file with an error like this:
```
*.sh text eol=lf    # comments behind a line aren't allowed in .gitattribute files
```
2. Look at the changes and try to stage a file

**Expected behavior**
Normal shown changes.

**Screenshots**

<img width="609" alt="image" src="https://user-images.githubusercontent.com/39461169/155732041-1f1cd6e4-edb9-4a12-ba90-00cb4836e38a.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Lazygit Version 0.32.2

**Comment by mark2185** [comment]
@dmun could you check if the issue still occurs with the latest master? https://github.com/jesseduffield/lazygit/pull/2081 should have fixed it.

**Comment by dmun** [comment]
@mark2185 Seems to be working, nice!

**Comment by mark2185** [comment]
Great! 

Feel free to reopen if it happens again (but it shouldn't)
