### ISSUE TITLE
Delete word with ctrl + w

### ISSUE THREAD

**Issue by eruizc-dev** [jesseduffield/lazygit#1789]
**Is your feature request related to a problem? Please describe.**

When I'm typing a commit message, branch name, tag name or anything in the text prompt I'd like to delete a word with ctrl+w.

**Describe the solution you'd like**

When I press ctrl+w will delete last word with trailing characters. Eg:

`hello world` -> `hello ` (with space at the end)

`hello-world` -> `hello-`

`hello-world-` ->  `hello-`

`hello-world-      ` -> `hello-`

**Additional context**

This feature is already present in most terminals and editors such as vim.

**Comment by ptim** [comment]
https://github.com/jesseduffield/lazygit/issues/1783

**Comment by eruizc-dev** [comment]
Thanks for finding what I did not :P

Closing duplicate issue
