### ISSUE TITLE
Allow multi-line commit message from lazygit commit window

### ISSUE THREAD

**Issue by bartgol** [jesseduffield/lazygit#1790]
This might be a long shot, but I figured I asked.

Sometimes I need to make a long commit. Since `c` only allows a single-line commit (that I can tell, at least), I do `<shift>+C`, to open vim and type a well thought message. Then I save and close, and am prompted for the gpg passphrase to sign the commit. If by accident I type the wrong password, the signing fails, and I am returned to lazygit, but the long message is lost. On the other hand, if I make a typo when signing a commit made with `c` (i.e., from within lazygit), the commit msg is not lost, so hitting `c` again will bring it back.

I would like to be able to make multi-line commit msgs without losing the message if I accidentally fail to sign the commit. Since I doubt lazygit can cache the commit message when using an external editor, I feel like the best shot is enabling multi-line commit message from within lazygit (the window you get hitting `c`).

It is possible that I am missing how to make a multi-line commit msg from within lazygit. But assuming that's indeed not a current feature, it would be nice to add it. For instance, it would be convenient if the commit window treated <Enter> and <Shift>+<Enter> differently, with one of the two implementing a soft return and the other a hard return (don't really care which does which). That's already common in a few interfaces (e.g., chat-like windows).

Regardless, thanks for developing (and constantly maintaining!) such a great tool!

**Comment by Hofer-Julian** [comment]
Seems like with the current version, new lines can be created with alt-enter

**Comment by bartgol** [comment]
NICE! Thanks for the tip! This genuinely improves my day-to-day work.

Closing.

**Comment by kiwimind** [comment]
This is not the case (as far as I can tell) on a Mac. I don't seem to be able to create this soft return with any combination of keys, so either I'm missing something (and am happy to be corrected) or it's not possible.

Just to throw an idea in the pot, how about `c` still opens the commit prompt, but it's two part: the first is the commit message, and when hitting enter a second prompt is shown where you can optionally enter a description? 

This way, creating a quick one-line commit without description is a minor inconvenience of hitting enter twice, while allowing a more fleshed out commit to be created for those that want it.

**Comment by mark2185** [comment]
What if someone wants multiple lines in the second prompt?

**Comment by kiwimind** [comment]
@mark2185 great question - wasn't sure how to tackle that so didn't mention it :)

Perhaps there needs to be a way of saving the description by way of key combo.

**Comment by mark2185** [comment]
I don't like the direction this is taking, the quote "The best option is the no-option option." resonates with me :)

I'd rather we just fix the message caching in case of a failed commit.

**Comment by kiwimind** [comment]
No skin off my nose. Just offering alternative thoughts. 👍

**Comment by mark2185** [comment]
But now that you mention it, maybe we could have a two part popup, like we do for custom commands.

Where as the first line is the title (which should be just one line anyway), and pressing `enter` commits it, but pressing `tab` switches to the bottom half where `enter` actually inserts a newline. Commiting would then be done by pressing `tab` again to return to the `title` part and pressing `enter` to commit it.

@jesseduffield thoughts?

I'd also rather have this instead of `alt+Enter` because that's not viable for me.

**Comment by jesseduffield** [comment]
hmm, that sounds pretty good. It also would allow the 'up' and 'down' keys to cycle back through previous commit messages (while the subject line view is focused)

**Comment by mark2185** [comment]
Chucked it into the "good first issue" bin.

**Comment by bartgol** [comment]
Ah, interesting. The multiline commit does not work on another machine where I have lazygit installed, despite them being similar (I don't have my laptop open, so I will complete the details next time I have it at hand).

Workstation (doesn't work):
- rhel 8.7
- python 3.9.13
- conda 4.10.3
- lazygit 0.36.0
- git 2.31.1

Laptop (works)
- TO BE COMPLETED.

**Comment by watson28** [comment]
Does someone know the reason for using ALT+Enter instead of Swift+Enter for new lines? It's more common to use the latest for introducing new lines in a text box.

**Comment by mark2185** [comment]
I presume `shift+Enter` may not always be detectable in terminals.

> It's more common to use the

It _does_ depend on how big your sample size is :)
