### ISSUE TITLE
WigleWifi log report

### ISSUE THREAD

**Issue by krazyfix** [jesseduffield/lazygit#1792]
Log Data:

11:47:55.636 main] Tried to update BTLE batch in improbably short time: 0
11:47:58.627 main] startScan returned false. last response seconds ago: 3.021
11:47:58.641 main] wifi receive, results: 22
11:48:00.645 main] Tried to update BTLE batch in improbably short time: 0
11:48:01.634 main] startScan returned false. last response seconds ago: 3.006
11:48:01.644 main] wifi receive, results: 22
11:48:03.641 main] startScan returned false. last response seconds ago: 2.006
11:48:03.649 main] wifi receive, results: 22
11:48:04.145 GuardThread-Thread-4] Service is foreground: true
11:48:05.658 main] Tried to update BTLE batch in improbably short time: 0
11:48:06.645 main] startScan returned true. last response seconds ago: 3.003
11:48:08.647 main] startScan returned false. last response seconds ago: 5.005
11:48:10.649 main] startScan returned false. last response seconds ago: 7.006
11:48:10.693 main] Tried to update BTLE batch in improbably short time: 1
11:48:12.651 main] startScan returned false. last response seconds ago: 9.008
11:48:15.654 main] startScan returned false. last response seconds ago: 12.011
11:48:15.683 main] Tried to update BTLE batch in improbably short time: 1
11:48:17.658 main] startScan returned false. last response seconds ago: 14.015
11:48:17.783 main] Going faster, scheduling scan
11:48:17.787 main] startScan returned false. last response seconds ago: 14.145
11:48:19.170 GuardThread-Thread-4] Service is foreground: true
11:48:19.633 main] wifi receive, results: 29
11:48:20.670 main] startScan returned false. last response seconds ago: 1.048
11:48:20.683 main] wifi receive, results: 29
11:48:20.736 main] Tried to update BTLE batch in improbably short time: 0

**Comment by jesseduffield** [comment]
Closing because this does not conform to the required issue template
