### ISSUE TITLE
Line highlighting not working in Windows Terminal

### ISSUE THREAD

**Issue by basseX** [jesseduffield/lazygit#1795]
**Describe the bug**
Selected line is not highlighted in Windows Terminal, no matter what font I use. 

**To Reproduce**
Install Windows Terminal from any source you like. Start it and run lazygit. 

**Expected behavior**
Expected behavior is that the line selected on the left is highlighted in bold.

**Desktop (please complete the following information):**
 - OS: Windows 11 OS Build 22000.493
 - Lazygit Version v0.33

**Comment by all500234765** [comment]
Try this: https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md#struggling-to-see-selected-line

It helped me

**Comment by basseX** [comment]
@all500234765 Hi, thanks for the suggestion. Unfortunately, I've already tried that with no luck.

**Comment by basseX** [comment]
I found the issue. You need to turn on `Bold font` under `Intense text style`. This can either be done globally or per profile in Windows Terminal. For anyone else having this problem, you can find it by digging into the settings of the profile you're using, then `Appearance` -> `Intense text style`.

**Comment by JolinpiggyYulongJin** [comment]
> I found the issue. You need to turn on `Bold font` under `Intense text style`. This can either be done globally or per profile in Windows Terminal. For anyone else having this problem, you can find it by digging into the settings of the profile you're using, then `Appearance` -> `Intense text style`.

Hi, @bastianpedersen I was experiencing the same issue as yours. I have tried your suggestion, and it is working fine for me so far :)
Both 'Bold' and 'Bold font with bright colors' will work.
Also Chinese translation is provided here:
我也有相同的问题：在 Windows Terminal 中使用 lazygit 没有正确地显示当前选中的行（例如当前分支、当前提交等等）。在设置中对单个终端Profile里面的Appearance外观选项-文本格式化（强调文本样式）中选择“加粗字体”或者“亮色加粗字体”。然后就可以正确地加粗显示当前行了。
@bastianpedersen Thanks a lot !
