### ISSUE TITLE
[Feature Request] Write to `$LAZYGIT_NEW_DIR_FILE` on dir change

### ISSUE THREAD

**Issue by davdroman** [jesseduffield/lazygit#1800]
Currently, `$LAZYGIT_NEW_DIR_FILE`'s path only gets updated on exit. It'd be a lot more useful if it was updated on the spot whenever directories are changed while running lazygit.

This would enable a new realm of functionality outside of lazygit, namely being able to quickly span a parallel session that points to lazygit's current directory for running miscellaneous commands.

The only other alternative to achieve this right now requires exiting lazygit and reopening it in order to get the current path written to `$LAZYGIT_NEW_DIR_FILE`, which is inconvenient and unproductive if lazygit is in a particularly complex navigation state.

On macOS, I'm currently using this AppleScript attached to a custom command in order to automate this as much as possible, but it's still inconvenient and slow:

```applescript
tell application "iTerm"
	activate
	
	tell the current session of current tab of current window
		# send ctrl+c command
		tell application "System Events" to ¬
			key code 8 using {control down}
		# re-open lazygit
		write text "lazygit"
		# wait a fraction to ensure path is written to $LAZYGIT_NEW_DIR_FILE
		delay 0.05
		# open new session (that cd's to the path in $LAZYGIT_NEW_DIR_FILE, if it exists)
		split vertically with default profile
	end tell
	
	tell the last session of current tab of current window
		# switch focus to new session
		select
	end tell
end tell
```

**Comment by jesseduffield** [comment]
This sounds fairly straightforward so I'll add a good-first-issue label. It's just a matter of calling `recordCurrentDirectory` in `pkg/gui/quitting.go` whenever we switch repos as opposed to whenever we quit the program. We switch repos in `dispatchSwitchToRepo` in `pkg/gui/recent_repos_panel.go`

**Comment by davdroman** [comment]
@jesseduffield thanks for the tips. I have no experience in Go but I'm willing to take it for a spin if I'm able to find some time.

**Comment by jesseduffield** [comment]
Awesome @davdroman , lemme know if you need any pointers
