### ISSUE TITLE
"No patch created" when it has been

### ISSUE THREAD

**Issue by jdowd** [jesseduffield/lazygit#1805]
Firstly: Thanks for an amazing tool!

**Describe the bug**
As of a few days ago, I can no longer `view custom patch options`. Whether i stage an entire file, or use spacebar to stage individual lines, I get `No patch created yet. To start build a patch, use 'space' on a commit file or enter to add specific lines` when I hit ctrl-p (or select via the menu)

**To Reproduce**
1. introduce changes to the index
2. open lazygit
3. select file in Files panel by hitting spacebar
4. hit `ctrl-p`
5. error: `No patch created yet. To start build a patch, use 'space' on a commit file or enter to add specific lines`

**Expected behavior**
I should see the custom patch options, rather than the error

**Screenshots**
output from `lazygit --logs`:
```
Tailing log file /Users/john/Library/Application Support/lazygit/development.log

Mar 13 09:04:38 |DEBU| using cache for key core.pager commit="" debug=true buildDate="" version="0.33"
Mar 13 09:04:39 |INFO| RunCommand command="git fetch"
Mar 13 09:04:39 |INFO| refreshing the following scopes in async mode: branches,commits,remotes,tags 
Mar 13 09:04:40 |DEBU| RunCommand command="git tag --list --sort=-creatordate"
Mar 13 09:04:40 |DEBU| RunCommand command="git branch -r"
Mar 13 09:04:40 |DEBU| RunCommand command="git merge-base \"HEAD\" \"HEAD\"@{u}"
Mar 13 09:04:40 |DEBU| RunCommand command="git for-each-ref --sort=-committerdate --format=\"%(HEAD)|%(refname:short)|%(upstream:short)|%(upstream:track)\" refs/heads"
Mar 13 09:04:40 |DEBU| RunCommand command="git symbolic-ref --short HEAD"
Mar 13 09:04:40 |DEBU| RunCommand command="git merge-base \"HEAD\" \"master\""
Mar 13 09:04:40 |ERRO| fatal: Not a valid object name master
 
Mar 13 09:04:48 |DEBU| using cache for key status.showUntrackedFiles 
Mar 13 09:04:48 |DEBU| RunCommand command="git status --untracked-files=all --porcelain -z"
Mar 13 09:04:48 |DEBU| using cache for key core.pager 
Mar 13 09:04:50 |DEBU| RunCommand command="git diff --submodule --no-ext-diff --unified=3 --color=never -- \"app/models/user.rb\""
Mar 13 09:04:50 |DEBU| RunCommand command="git diff --submodule --no-ext-diff --unified=3 --color=never --cached -- \"app/models/user.rb\""
Mar 13 09:04:52 |DEBU| using cache for key core.pager 
Mar 13 09:04:58 |DEBU| using cache for key status.showUntrackedFiles 
Mar 13 09:04:58 |DEBU| RunCommand command="git status --untracked-files=all --porcelain -z"
Mar 13 09:04:58 |DEBU| using cache for key core.pager 
Mar 13 09:05:00 |DEBU| RunCommand command="git add -- \"app/models/user.rb\""
Mar 13 09:05:00 |INFO| refreshing the following scopes in sync mode: files 
Mar 13 09:05:00 |DEBU| using cache for key status.showUntrackedFiles 
Mar 13 09:05:00 |DEBU| RunCommand command="git status --untracked-files=all --porcelain -z"
Mar 13 09:05:00 |DEBU| using cache for key core.pager 
Mar 13 09:05:00 |DEBU| using cache for key core.pager 
Mar 13 09:05:02 |INFO| refreshing all scopes in async mode 
Mar 13 09:05:02 |DEBU| RunCommand command="git merge-base \"HEAD\" \"HEAD\"@{u}"
Mar 13 09:05:02 |DEBU| using cache for key status.showUntrackedFiles 
Mar 13 09:05:02 |DEBU| RunCommand command="git branch -r"
Mar 13 09:05:02 |DEBU| RunCommand command="git tag --list --sort=-creatordate"
Mar 13 09:05:02 |DEBU| RunCommand command="git stash list --pretty='%gs'"
Mar 13 09:05:02 |DEBU| RunCommand command="git status --untracked-files=all --porcelain -z"
Mar 13 09:05:02 |DEBU| RunCommand command="git for-each-ref --sort=-committerdate --format=\"%(HEAD)|%(refname:short)|%(upstream:short)|%(upstream:track)\" refs/heads"
Mar 13 09:05:02 |DEBU| RunCommand command="git symbolic-ref --short HEAD"
Mar 13 09:05:02 |DEBU| RunCommand command="git merge-base \"HEAD\" \"master\""
Mar 13 09:05:02 |ERRO| fatal: Not a valid object name master
 

```
**Desktop (please complete the following information):**
 - OS: MacOS 12.1
 - Lazygit Version 0.33

**Additional context**
Everything was working great until just a few days ago. I have no idea what happened to cause the bug, but I suspect it's something on my machine. 

The logs contain a fatal error about "Not a valid object name master", but this is also happening in another repo locally that does have a `master` branch, fwiw.

Also, I've uninstalled and reinstalled lazygit, to no avail.

**Comment by jesseduffield** [comment]
Ah, so this is potentially a failure on my part to name/word things intuitively. The 'custom patch' refers not to the patch that you're building in your working tree / index but the patch you build based on a previous commit. So if you focus the commits panel, view the commit's files with 'enter' and hit space on one of them, that will create a custom patch.

The options available there don't really make sense in the context of the working tree.

That said, I'm not sure what other name to use. Perhaps 'commit patch' or something.

**Comment by jdowd** [comment]
@jesseduffield the issue magically went away...no idea what I changed to fix it. I'll follow up if I see it again.

**Comment by lycheeje11y** [comment]
I saw it again...
