### ISSUE TITLE
Duplicate line breaks when copying commit message to clipboard / Rewording commit

### ISSUE THREAD

**Issue by moha-gh** [jesseduffield/lazygit#1808]
**Describe the bug**

When using the "copy commit message to clipboard" action, the message will end up in the clipboard with duplicate line breaks. The same issue also seems to affect the "Reword Commit" command.

I tried to dig around in the code a bit and I think this might be caused by `GetCommitMessage()` in [pkg/commands/git_commands/commit.go](https://github.com/jesseduffield/lazygit/blob/f4011643dda14c6da522dcd172b66b2d2cadb02b/pkg/commands/git_commands/commit.go#L73).

```
	[...]
	message := strings.Join(strings.SplitAfter(messageWithHeader, "\n")[1:], "\n")
```

The `SplitAfter` will not remove the line breaks, and the `Join` will add new ones, causing the duplicates.

I'd be happy to file a PR for this - if somebody with more knowledge of the code base can confirm that this actually looks like / is the root cause (and whether tests can be added for it).

**To Reproduce**
1. Select a commit in 'Commits' view (e.g. c7c4a375a98130e746af021fd706e354cf989d1f)
2. Invoke 'copy commit message to clipboard' (CTRL+y)
3. Paste message into an editor

**Expected behavior**

```
Merge pull request #1750 from mark2185/fix-issue-template

'git-rev parse' should be 'git rev-parse'
```

**Actual behavior**

```
Merge pull request #1750 from mark2185/fix-issue-template



'git-rev parse' should be 'git rev-parse'
```

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: Linux
 - Lazygit Version: v0.33

**Additional context**
n/a

**Comment by fsmiamoto** [comment]
@moha-gh Nice, this indeed looks like the cause of the error. 

I've drafted a unit test that you can start off with that is currently broken due to the bug: 
```go
func TestGetCommitMsg(t *testing.T) {
	type scenario struct {
		testName       string
		input          string
		expectedOutput string
	}
	scenarios := []scenario{
		{
			"with line breaks", ` commit deadbeef
Merge pull request #1750 from mark2185/fix-issue-template

'git-rev parse' should be 'git rev-parse'`, `Merge pull request #1750 from mark2185/fix-issue-template

'git-rev parse' should be 'git rev-parse'`,
		},
	}

	for _, s := range scenarios {
		s := s
		t.Run(s.testName, func(t *testing.T) {
			instance := buildCommitCommands(commonDeps{
				runner: oscommands.NewFakeRunner(t).Expect("git rev-list --format=%B --max-count=1 deadbeef", s.input, nil),
			})

			output, err := instance.GetCommitMessage("deadbeef")

			assert.NoError(t, err)

			assert.Equal(t, s.expectedOutput, output)

		})
	}
```

 Running this test gives:
```
|| === RUN   TestGetCommitMsg/with_line_breaks
||     commit_test.go:152: 
||         	Error Trace:	commit_test.go:152
||         	Error:      	Not equal: 
||         	            	expected: "Merge pull request #1750 from mark2185/fix-issue-template\n\n'git-rev parse' should be 'git rev-parse'\n"
||         	            	actual  : "Merge pull request #1750 from mark2185/fix-issue-template\n\n\n\n'git-rev parse' should be 'git rev-parse'"
```

**Comment by jesseduffield** [comment]
Nice catch @moha-gh , looks to be the cause of the problem

**Comment by moha-gh** [comment]
@fsmiamoto Thanks a lot for the test draft! I've extended it a bit by adding two additional scenarios and included it in my PR.
