### ISSUE TITLE
`pushRemote` and `pushDefault` settings no longer respected

### ISSUE THREAD

**Issue by Garmelon** [jesseduffield/lazygit#1821]
**Describe the bug**
After version 0.32.2, lazygit stopped respecting the `pushRemote` and `pushDefault` settings when pushing/pulling a branch.

**To Reproduce**
1. Configure a `branch.<name>.pushRemote` for a branch that's different from its `branch.<name>.remote`
2. Select the branch in the `Local Branches` tab
3. Press `P` to push
4. Observe that lazygit pushes to the branch's `remote`, not its `pushRemote`

Alternatively, configure the `remote.pushDefault` in step 1 and observe that lazygit ignores it in step 4.

**Expected behavior**
Lazygit should push to the `pushRemote` or `pushDefault` if configured, not to the `remote`.

**Desktop (please complete the following information):**
 - OS: linux (NixOS)
 - Lazygit Version: 0.33

**Additional context**
This change was mentioned in issue #1425, where I also give an example for a workflow benefitting from the `pushRemote`/`pushDefault` settings. I'm not sure whether this is a bug or a feature request, but the change broke a previously working workflow for using multiple remotes, so I filed it as a bug.

**Comment by jesseduffield** [comment]
It sounds like we've got a general problem of lazygit no longer honouring the git config when pushing/pulling/fetching. So far I haven't been able to find the cause, but it might be time to bring out the big guns with some git bisect action

**Comment by jesseduffield** [comment]
ah sorry @Garmelon I didn't read your linked comment. I'll need to have a think about this. I recall there being a good reason for the change but can't find the related issue.

**Comment by Garmelon** [comment]
For completeness' sake, the relevant commit appears to be 1c84f7731920e1970d52f81361d321268054e559. It appears to have been introduced as part of #1674. This PR references issue #1673 which may have been the reason.
