### ISSUE TITLE
can't log-in to github? 

### ISSUE THREAD

**Issue by kroobeN** [jesseduffield/lazygit#1823]
trying to push, it prompts me to enter my username and then the token, which are both correct but it says username or password is invalid. 

in the command log it says: 
**Username for 'https://github.com': kroobeN**
**Password for 'https://kroobeN@github.com':**

~~for some reason i think that the username is incorrect, i mean why is my username a url? or am i completely missing the point of something here?~~ 
i tried to find some sort of guide for lazygit that included the log-in process but i couldn't find any.

Edit: well i kind of figured it out, i can't copy and paste my token into the password prompt, had to type it. but the next issue arises: i have to type it every time i pull/push from the repo. is there any way to stay logged in?

**Comment by mark2185** [comment]
This isn't really a `lazygit` issue, so you could use RSA keys to authenticate yourself - [GitHub docs for that](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/adding-a-new-ssh-key-to-your-github-account).

Or you could tell `git` to cache it for a certain number of seconds, as [this stackoverflow post](https://stackoverflow.com/a/5343146/11241796) says.
```
git config --global credential.helper "cache --timeout=3600"
```

**Comment by kroobeN** [comment]
thank you very much! got it working now.
