### ISSUE TITLE
Only remote branches should be suggested when creating a PR against selected branch

### ISSUE THREAD

**Issue by moha-gh** [jesseduffield/lazygit#1826]
**Is your feature request related to a problem? Please describe.**

When creating a PR against a selected branch (via ` O` = "create pull request options"), the suggestion area is populated with all local branches. I'd say that only remote branches should be listed there - it doesn't really make sense to create a PR against a branch that doesn't exist on the remote (at least for Github).

**To Reproduce**

1. Checkout local branch
2. Press 'O'
3. Select '... -> select branch' option

**Describe the solution you'd like**

Only remote branches are listed as suggestions.

**Describe alternatives you've considered**

n/a

**Additional context**

The suggestion function used in [createPullRequestMenu()](https://github.com/jesseduffield/lazygit/blob/a34bdf1a046c90c22a1c0b653241b8107e89c7f9/pkg/gui/controllers/branches_controller.go#L378) returns all local branches. Simply replacing it with [GetRemoteBranchesSuggestionsFunc()](https://github.com/jesseduffield/lazygit/blob/a34bdf1a046c90c22a1c0b653241b8107e89c7f9/pkg/gui/controllers/helpers/suggestions_helper.go#L173) doesn't work since   the corresponding remote is then included in the branch name (i.e.  `<remote>/<branch>`) - breaking the generated link.

I'd be happy to have a go at fixing this, but I'd need some pointers: I haven't fully grasped yet how the whole "create PR" feature deals with multiple remotes, for example - and whether that must be taken into account. Would a new suggestion function that lists remote branches without the `<remote>/` prefix (and possibly for `origin` only) do the trick?

**Comment by jesseduffield** [comment]
I believe at the moment the assumption is that you'll only be dealing with 'origin's remote branches, given that the github git repo is usually what origin points to.

So yeah feel free to only show those for origin (and whether to include the origin/ prefix or not just depends on whatever works)

**Comment by moha-gh** [comment]
I've started to work on this, hope to be able to file a PR in the next days.
