### ISSUE TITLE
Colors set in .gitconfig are misinterpreted

### ISSUE THREAD

**Issue by matejcik** [jesseduffield/lazygit#1831]
Git seems to accept colors in the following format: `style fg bg`, or `fg bg style`.

`style` seems to go alright for everything.
`fg` and `bg` can be either one of the color names, or a color number, or a hex color code.

Plain color names behave as expected.
Hex codes seem to be completely ignored.
Colors like `brightmagenta` render as bold black.

For added fun: when such color is streamed through a custom pager such as `delta`, it turns into blinking text! So #1274 is possibly related.

Example git config snippet:
```
[diff]
	colorMoved = default
	colorMovedWS = allow-indentation-change
[color "diff"]
	oldMoved = bold brightmagenta "#ffe0e0"
	oldMovedAlternative = bold brightmagenta "#ffe0e0"
	newMoved = bold brightblue "#d0ffd0"
	newMovedAlternative = bold brightblue "#d0ffd0"
```
(Best to demonstrate on moved colors, because those get passed down to `delta`, while `old` and `new` are ignored in that case.

`git diff` output:
![image](https://user-images.githubusercontent.com/596073/159898750-51aebdb7-81e8-4d99-b603-feb130b3fa3e.png)

lazygit interpretation:
![image](https://user-images.githubusercontent.com/596073/159898889-f0289e1c-0dfc-4901-8ada-c86f9aebfb26.png)

git output with `delta`:
![image](https://user-images.githubusercontent.com/596073/159898936-0101a763-e3b9-4a70-9c44-40e04d533763.png)

lazygit with delta:
![image](https://user-images.githubusercontent.com/596073/159899048-214f0946-527b-453e-995e-54a7586700e3.png)
(the text is black and blinking)

reproduced in xterm and mate-terminal, lazygit and delta from today's master, git 2.35.1

**Comment by hqkhan** [comment]
Running into the same issue.

![image](https://user-images.githubusercontent.com/22674069/223936028-3c8c8f6b-a07c-4951-9335-43cbbe09f9a2.png)

The above is output from `git diff`

![image](https://user-images.githubusercontent.com/22674069/223936127-869ff702-d283-48e8-bad8-77d3ea24e0d3.png)

The above image is from lazygit's preview. 

Were you able to find a resolution for this @matejcik ?

**Comment by matejcik** [comment]
nope, just deleted the alternate colors from my config because i needed to see the diff :woman_shrugging:

**Comment by hqkhan** [comment]
Got it. Oh @Ryooooooga made a PR for this. Hope it gets merged. That'd be awesome.
