### ISSUE TITLE
Unintuitive color hint on selected/focus item

### ISSUE THREAD

**Issue by jiyolla** [jesseduffield/lazygit#1845]
Currently, on my machine(Monterey 12.3, iterm2, ohmyzsh), vanilla lazygit is greying out selected item/panel which is not a common custom imo. Is this intended?

The branch panel is the selected one
<img width="946" alt="image" src="https://user-images.githubusercontent.com/71974321/160287562-9056510c-038c-443e-83b8-1c79db3f56f6.png">

The branch name input field is the selected one
<img width="946" alt="image" src="https://user-images.githubusercontent.com/71974321/160287571-78495a5c-3709-4222-b322-e6d07e8ffa4a.png">

If it is intended, I'd want to know the reason behind this design.

If not, I'd like to know what could be wrong and how to correct it.

**Comment by jesseduffield** [comment]
@jiyolla I think your theme is actually darkening colours when displaying the 'bright' variant of that colour. You should be able to check that in your iterm preferences

**Comment by socketbox** [comment]
I had this same problem in gnome-terminal with Solarized Dark theme and the _Show bold text in bright colors_ option selected. Disabling the latter corrected the issue.
