### ISSUE TITLE
Preview pane stops updating on Windows

### ISSUE THREAD

**Issue by naoey** [jesseduffield/lazygit#1851]
**Describe the bug**
The preview pane on the right side stops updating to the highlighted selected item and remains stuck on a seemingly random item. I've noticed this happens more consistently when switching through items very quickly, such as holding down the next key to go down a long list of files, branches or commits. The issue occurs randomly as well however, especially when lazygit has been left open for an extended period of time.

When exiting lazygit in this state, there's also an error on the console post exit that says `cannot kill child process`.

**To Reproduce**
1. Open any repository
2. Go to files/branches/commits pane with lot of entries
3. Hold 'j' or down arrow to go through several items quickly
4. See preview pane stops updating

**Expected behavior**
The preview pane should continue updating to show the currently highlighted item.

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro 21H2
 - Lazygit Version: `commit=7be25a105d389a262ef040133a4270f2f745d255, build date=2022-03-17T07:07:02Z, build source=binaryRelease, version=0.34, os=windows, arch=amd64`

**Additional context**
The same behaviour occurs in both cmd and PS, and I believe this issue may be recently introduced as I don't recall being bothered by this more than a month ago.

**Comment by Aziks0** [comment]
#1265 duplicate

_(even if this one is more clearly explained)_

**Comment by naoey** [comment]
Thanks, closing as duplicate.
