### ISSUE TITLE
Allow `unset-upstream` via lazygit

### ISSUE THREAD

**Issue by jsbeckr** [jesseduffield/lazygit#1856]
**Problem**
I tried to rename a branch locally and remotely following this SO post: https://stackoverflow.com/questions/30590083/how-do-i-rename-both-a-git-local-and-remote-branch-name

It seems that it is not possible to `git unset-upstream <new-branch>` via lazygit. So I had to fallback to the terminal. 

**Solution**

An option in the Local Branches panel to `unset-upstream`.

**Considerations**

Maybe a complete workflow that renames local and remote branches would be nice? But considering that the described solution in the SO post delete the remote branch and pushed the local branch again, could lead to confusion. So I am not sure if that is really nice solution.

**Comment by jesseduffield** [comment]
I'm not sure about the whole workflow but just having an unset-upstream keybinding makes sense. In fact we should have an upstream menu where you can:
* set the upstream
* unset the upstream

We can use the 'u' keybinding for opening this menu. Any chance you'd be keen to give this a crack @jsbeckr ?

**Comment by jsbeckr** [comment]
Sorry for not responding 🙈 

Despite loving lazygit I am not really a big fan of Go. So I am not really interested in working on that. But I am very happy that @mark2185 is already working on that. I think we can close this issue in favor of #1869
