### ISSUE TITLE
Add confirmation prompt type to custom commands

### ISSUE THREAD

**Issue by jesseduffield** [jesseduffield/lazygit#1858]
**Is your feature request related to a problem? Please describe.**
When creating a custom command by following `docs/Custom_Command_Keybindings.md` there's no way to have a confirmation popup appear saying e.g. 'Are you sure you want to delete all files?'.

**Describe the solution you'd like**
We should add a 'confirm' prompt type alongside 'input' and 'menu' in `pkg/gui/services/custom_commands/handler_creator.go`'s `call` function. That can basically copy what we're doing in `inputPrompt` but using `self.c.Confirm`.

We should also update the docs at `docs/Custom_Command_Keybindings.md` to reflect this new type.

**Describe alternatives you've considered**
Right now the only alternative is to use a 'menu' prompt with a 'yes' and 'cancel' option.

**Comment by m-mead** [comment]
Hi, I took a shot at implementing this issue and submitted a PR. I tried my best to follow the contributing guide; this is my first time contributing to the project (and writing Go code for that matter), so please let me know what I can improve. 🙂 

PR link: https://github.com/jesseduffield/lazygit/pull/2017
