### ISSUE TITLE
How do I make each "section" have a solid line instead of stippled (Windows)

### ISSUE THREAD

**Issue by basseX** [jesseduffield/lazygit#1860]
I'm wondering how I can make the lines surrounding each section of lazygit solid, instead of stippled.

 - OS: Windows

![WindowsTerminal_xYGd6kBgej](https://user-images.githubusercontent.com/58905488/161813291-fe86f99b-c5fb-46df-918e-187bdbc20105.png)

**Comment by jesseduffield** [comment]
I assume this is an issue with your terminal font. Are you able to run other terminal UI's without the stippling?

**Comment by basseX** [comment]
@jesseduffield I can confirm this is an issue with the terminal/font. This is not an issue using a different terminal (ie. Hyper terminal). Will investigate further.

**Comment by basseX** [comment]
I can confirm that this is an issue with the font I'm using.
