### ISSUE TITLE
Add git stash --keep-index

### ISSUE THREAD

**Issue by canac** [jesseduffield/lazygit#1863]
**Is your feature request related to a problem? Please describe.**
When I need to stash away part of my working directory, my workflow before using lazygit is to stage the files I want to keep, then run, `git stash --keep-index`. Maybe I'm missing something, but it doesn't seem like lazygit's stashing options support the `--keep-index` flag.

**Describe the solution you'd like**
In the "Stash options" pane, I'd like to see a new "stash unstaged changes" that does essentially the opposite of "stash stage changes".

**Describe alternatives you've considered**
I could train myself to do the inverse and stage the files I want to have stashed, and use the "stash staged changes" command.

Thanks for an awesome tool! lazygit makes it so much easier for me to quickly view diffs, interactively stage files, and amend commits from the terminal. Those are probably my favorite features!

**Comment by mark2185** [comment]
Could you build current `master` and test if #1870 solves your issue?

**Comment by canac** [comment]
Yes it does. Thanks so much @mark2185 for implementing this!

**Comment by Keshav-writes-code** [comment]
how does it work please?

**Comment by mark2185** [comment]
> how does it work please?

Stage some changes and press `S` in the `Files` pane, you'll get a popup window with possible ways to stash the changes.

**Comment by Keshav-writes-code** [comment]
Thanks 🙏🙏🙏🙏🙏🙏!
