### ISSUE TITLE
Change author name / --reset-author

### ISSUE THREAD

**Issue by canadaduane** [jesseduffield/lazygit#1871]
**Is your feature request related to a problem? Please describe.**
I have several commits checked in with the wrong username / email. In my case, this happened be because I re-installed my OS and it picked up my login & default email (e.g. "duane@pop-os.localdomain") as name and email.

**Describe the solution you'd like**
I'd like to be able to revisit commits in the "Commits" box and press a key to "--reset-author" on just that commit. It might also be handy to be able to change the author name or email, but it's less important for my use case.

**Describe alternatives you've considered**
Long and ugly rebase commands e.g. https://stackoverflow.com/a/3042512/159344

**Comment by 4x0v7** [comment]
+1 for this!

I just did basically the same thing (pop!OS install even) and was looking for the "rename author/committer" option :smile: 

I did in fact do a rebase and author amend to get it all right, but this would be super handy as a lazygit feature!

**Comment by mark2185** [comment]
@canadaduane could you check if #1893 solved your issue?

It's available in `v0.35`.

**Comment by canadaduane** [comment]
> @canadaduane could you check if #1893 solved your issue?

Looks good to me! Thanks.
