### ISSUE TITLE
Allow on push to select the upstream to push

### ISSUE THREAD

**Issue by otavioschwanck** [jesseduffield/lazygit#1872]
Im used to this on magit and i really miss.  Would be nice to select upstream / set upstream of a branch.

**Comment by mark2185** [comment]
Something like [this](https://github.com/jesseduffield/lazygit/issues/1856)?

Although, this only lets you choose an existing upstream branch as target. In any case, [a PR](https://github.com/jesseduffield/lazygit/pull/1869) is currently in development.

**Comment by otavioschwanck** [comment]
> Something like [this](https://github.com/jesseduffield/lazygit/issues/1856)?
> 
> Although, this only lets you choose an existing upstream branch as target. In any case, [a PR](https://github.com/jesseduffield/lazygit/pull/1869) is currently in development.

No,

On Magit is possible to select the upstream in the time of push.

**Comment by mark2185** [comment]
Yes, it was discussed in the meantime and there are plans for creating a `push with options` which include selecting the upstream, there are some steps required beforehand, but it should solve this issue.

**Comment by mark2185** [comment]
Do you have any config options regarding `push` in your gitconfig (e.g. `push.default`)?

If there aren't any, `lazygit` should prompt for the upstream you want to push to.

**Comment by Edke** [comment]
Any plans on this ? 

Would love this feature as many times have project with multiple upstreams . As I can now select only one tracked, if pushing in controlled manner to the other upstream, need to jump out of `lazygit` and do manually. Which is not a problem of course but would be lovely to stay in `lazygit` and do it, right ? :)

**Comment by mark2185** [comment]
> would be lovely to stay in lazygit and do it

You could always use a custom command like [this one](https://github.com/jesseduffield/lazygit/wiki/Custom-Commands-Compendium#pushing-to-a-specific-remote-repository).

**Comment by Edke** [comment]
> > would be lovely to stay in lazygit and do it
> 
> You could always use a custom command like [this one](https://github.com/jesseduffield/lazygit/wiki/Custom-Commands-Compendium#pushing-to-a-specific-remote-repository).

Wow, that is perfect way to solve for now, thank you for this tip.

**Comment by otavioschwanck** [comment]
> > would be lovely to stay in lazygit and do it
> 
> You could always use a custom command like [this one](https://github.com/jesseduffield/lazygit/wiki/Custom-Commands-Compendium#pushing-to-a-specific-remote-repository).

that solves the problem! closing issue

**Comment by Edke** [comment]
Hi @otavioschwanck ,

managed to create this command (and much more) with this :) thank you.

one note, there is a minor bug in example you shared, should I create a MR to fix ? there is a missing `command` in that block.
