### ISSUE TITLE
Add support for `open pull request` with GitLab

### ISSUE THREAD

**Issue by basseX** [jesseduffield/lazygit#1874]
**Describe the bug**
Currently I'm not able to use `open pull request` option when using GitLab. I get an error message saying `Unsupported git service`. Is this an issue because I don't have the right setup on my computer, or because I'm using GitLab? 

**To Reproduce**
1. Open lazygit
2. In the `branch` tab, press `o`

**Expected behavior**
Lazygit creating a pull request

**Screenshots**
![image](https://user-images.githubusercontent.com/58905488/163126615-c980c202-fd97-40de-a2fe-1566d52886b5.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Newest lazygit version

**Comment by Steadyx** [comment]
You might need to follow the steps from the configuration documentation.


![Screenshot 2022-04-13 at 10 45 42](https://user-images.githubusercontent.com/13971238/163150267-22ab9fcc-57b3-4592-b031-6c11e82f86d0.png)

**Comment by basseX** [comment]
Thank you @Steadyx, this fixed my issue.
