### ISSUE TITLE
Accept named colors for authorColors

### ISSUE THREAD

**Issue by ismay** [jesseduffield/lazygit#1879]
**Is your feature request related to a problem? Please describe.**

The `authorColors` setting (documented [here](https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md#custom-author-color)) does not seem to accept named colors. I would like to just display all authors in a single named color, because the autogenerated colors clash with my colorscheme:

```
gui:
  authorColors:
    '*': red
```

**Describe the solution you'd like**

Accept named colors for the authorColors setting.

**Describe alternatives you've considered**

Another option that would resolve generated colors clashing with terminal theme colors is allowing generated author colors to be turned off. Provided lazygit would then fall back to a named color for all authors.

**Additional context**

As you can see in the screenshot, using `red` for all authorColors does not result in the author name being rendered in red (seems like black):

![image](https://user-images.githubusercontent.com/7355199/163666547-8047f4e5-3e12-4190-86ce-11da9b2130c6.png)

Also, the reason I'd like to use a named color, and not a hex color, is because if I use a named color it will adapt automatically to my terminal color scheme. See: https://jeffkreeftmeijer.com/vim-16-color/ for the rationale behind that approach.

**Comment by mark2185** [comment]
Could you try building `master` to see if #1910 works for you?

**Comment by ismay** [comment]
Hi @mark2185, I checked it out, and current master responds correctly to named authorColors. So it seems #1910 works as intended. Thanks for the fix @Ryooooooga!

**Comment by mark2185** [comment]
Great! Feel free to close the issue :)
