### ISSUE TITLE
Add support for git restore

### ISSUE THREAD

**Issue by attriaayush** [jesseduffield/lazygit#1887]
**Is your feature request related to a problem? Please describe.**
I use `git restore` quite a lot which is a very handy command specially when you want to get rid of all of the changes in a file quickly without needing to stash them. Currently I cannot see any way to run `git restore` while using lazygit, the only options I see is to either stash my changes or reset the changes to the previous commit. Unless I am missing something here completely.

**Describe the solution you'd like**
Add support for [`git restore`](https://git-scm.com/docs/git-restore), for when viewing the diff of a file I can hit a key or two to quickly restore all the changes.

**Describe alternatives you've considered**
I guess stashing the changes or use the `git` CLI.  

Thanks for building such an amazing tool.

**Comment by mark2185** [comment]
To what point exactly are you trying to restore, could you give an example?

> when you want to get rid of all of the changes in a file quickly without needing to stash them

That sounds like just discarding changes, i.e. pressing `d` on a file in the `Files` panel. In the background it just does `git checkout -- <file>` (or an equivalent) to reset it to `HEAD`.

**Comment by attriaayush** [comment]
ah yes that is correct the `d` shortcut should be good enough there actually. I guess an example could be when you want to restore to a particular commit in the history but I guess `git reset`with `g` shortcut would do just that too. And another one that I can think of is doing something like `git restore --staged *.rs` to restore all of files of certain extensions but at the same time its not something I do very often.

For the use cases I can think of, I reckon conjunction of `git checkout` and `git reset` commands already in place can do alot of those things that `git restore` has to offer so I am happy to close this issue. Thanks for your help.
