### ISSUE TITLE
No newline at end of file when adding to .gitignore

### ISSUE THREAD

**Issue by matejcik** [jesseduffield/lazygit#1898]
Lazygit does not add a trailing newline character when modifying `.gitignore`.

It should definitely do that on Unixes, personally I think it can't hurt on Windows either.

**Comment by mark2185** [comment]
Could you clarify when does this happen?

Does `lazygit` actively edit the `.gitignore` somehow or does it just not register the trailing `\n` or is it something else?

**Comment by matejcik** [comment]
There is an option "ignore this file" in the file tab.
When you press it (i think it's bound to `i`?), lazygit will edit the
.gitignore file and add an entry for the selected file.
While doing this, it does not add a newline at end.
