### ISSUE TITLE
Integrating diff-so-fancy as a diff viewer?

### ISSUE THREAD

**Issue by aneveux** [jesseduffield/lazygit#190]
**Is your feature request related to a problem? Please describe.**

My request is not at all related to a problem but rather a personnal preference of looking at git diffs. I'm using [diff-so-fancy](https://github.com/so-fancy/diff-so-fancy) for quite a while now and I'm really enjoying how readable the diffs are (it's a simple yet effective modification of how the diffs are displayed).

I was wondering if it could be possible to somehow specify to lazygit to use that program to display the diff in the proper editor instead of the default git diff.

**Describe the solution you'd like**

I'd like to be able to set an user option to select the diff viewer I'd like: default, or diff-so-fancy. I'm using dotfiles a lot so I'm thinking of a .lazygit file in which there would be an entry like `diff-viewer: diff-so-fancy` or something (I completely didn't think at all about the wording though, I'm sorry :/), then lazygit would simply use that tool (if alredy installed on the system) to display the diff on the panel on the right.

**Describe alternatives you've considered**

An alternative if diff-so-fancy is not installed is to simply rely on the default diff viewer you already have, which completely does the job :)

**Additional context**

See [diff-so-fancy](https://github.com/so-fancy/diff-so-fancy) for screenshots of how it looks.

---

**Thank you!**

Aside from this small idea/request, I really wanted to congrats and thank you for that really nice project of yours! I really enjoy this kind of tools and you did a really good job at building something around git! 

Well done and thanks a lot for the efforts and the really good job!

Have an awesome day!

**Comment by aneveux** [comment]
That's what I thought while starting using lazygit actually, since I already had this pager option set up in my gitconfig file, but it actually isn't working this way.

Just to confirm, I ran your command as well and picked an example from a repository of mine, and it confirms setting this option in git configuration doesn't work as we could think:

![diff](https://user-images.githubusercontent.com/311677/44347802-18edf680-a499-11e8-9b90-182294a88a97.png)

I'm guessing there must be some more integration to have in lazygit, or maybe it's just not taking the gitconfig file into account while computing the diff :/

**Comment by jesseduffield** [comment]
It's actually tricky to read the git config and translate that into something that works in lazygit, because we effectively need to produce a string output that we can render. I think the best way to go about this is to support user-defined git diff template commands with some variables that we can pass in. In this case the template would be:

`git diff --color {{args}} {{filename}} | diff-so-fancy`

where args will be something like `--cached` (for diffing staged files) and filename is something like `blah.go`

That way we can kill two birds with one stone, as we'd be able to use the same template approach for https://github.com/jesseduffield/lazygit/pull/161

i.e.

`git difftool --no-prompt {{args}} --extcmd="icdiff --cols={{width}}" {{filename}}`

What are your thoughts on that approach?

**Comment by jesseduffield** [comment]
for reference here's how it looks on my screen

![image](https://user-images.githubusercontent.com/8456633/44397395-8fffb980-a583-11e8-87d4-7392dd7c5a4a.png)

BTW thanks for the words of support! Glad I can help out in reducing the burden of the git command line for all!

**Comment by aneveux** [comment]
Your idea of supporting user defined git diff template commands is a great solution imho :)

It allows to have a decent and fine default solution out of the box, and allows people with other preferences to plug in their own tools without you having to think about a deep integration in lazygit. Plus it'll perhaps cover other tools people maybe using for viewing diffs :)

The way it looks on your screen is exactly the kind of view I was looking for actually, so that solution would be perfect :smile: 

Being able to put that diff template command line somewhere in the configuration file would be standard and easy enough for people to be able to easily customize the view :)

Nice solution @jesseduffield, that looks really promising :smile:

**Comment by apazzolini** [comment]
I've looked through the config options and other issues in this repo, but can't find a way to mimic the above screenshot (effectively just using diff-so-fancy in the diff view).

Is there something I'm missing or is this still outstanding? Would love support for this!

**Comment by jesseduffield** [comment]
@apazzolini I had a PR up for this but it went stale so I closed it: https://github.com/jesseduffield/lazygit/pull/201/files

Admittedly it really wouldn't be too hard to do now that the app can better handle slow commands (using a fancy diff tool usually results in a delayed output). 

There will be some awkwardness: firstly line-by-line-staging is only supported in the form of a normal `git diff` so if you want to do that it'll be a different format than when you're just flicking through files. Secondly, if you have a file that is part staged and part unstaged, there will be four columns displayed: the before/after for the unstaged changes, and the before/after for the staged changes, so screen realestate will become an issue. We do currently split the screen vertically when there's not much width, perhaps we could also make that min width configurable for users of side-by-side diff tools.

**Comment by DrSensor** [comment]
adding another fancy diff viewer to the list :slightly_smiling_face: 
https://github.com/dandavison/delta

**Comment by mattpass** [comment]
Would also like to see diff-so-fancy used in diff views, will sponsor if you can make it happen somehow. (IMO would like to not see it as a config option, but whatever git's CLI is using, Lazygit uses).

**Comment by DrSensor** [comment]
While at it,  it would be nice if lazygit respect `.git/config` then fallback to `~/.gitconfig`.
I use `core.pager` field to make `git log --patch` prettier.
```ini
[core]
  pager = delta --dark
```
![Peek 2020-02-29 03-08](https://user-images.githubusercontent.com/4953069/75583582-7b697f00-5aa0-11ea-9ccc-0a3ed2fd79a5.gif)

**Comment by jesseduffield** [comment]
@mattpass I've made a start on this today

**Comment by jesseduffield** [comment]
I've got a WIP PR up now https://github.com/jesseduffield/lazygit/pull/690 That describes my proposed solution in the description. If anybody wants to pull it down and give it a go, or has ideas about a better approach, let me know :)

**Comment by jesseduffield** [comment]
I've also just put up a PR in the delta repo for forcing it to not use a pager: https://github.com/dandavison/delta/issues/108

**Comment by jesseduffield** [comment]
This has now been implemented. See https://github.com/jesseduffield/lazygit/blob/master/docs/Custom_Pagers.md

If anybody would like to see changes to the feature, let me know :) closing

**Comment by fredcallaway** [comment]
Oddly, I find that the diff highlighting is slightly different in lazygit. Specifically, it highlights everything after the change in a line instead of just the section that was changed. See comparison of lg and diff-so-fancy below:

<img width="940" alt="image" src="https://user-images.githubusercontent.com/7883156/189978111-5f449d41-8b4b-42f5-888c-625076cadb95.png">
