### ISSUE TITLE
高亮很浅，上下移动几乎看不见，在nvim中打开lazygit

### ISSUE THREAD

**Issue by 505384662** [jesseduffield/lazygit#1908]
![image](https://user-images.githubusercontent.com/31720616/166395834-04db3889-6c47-4bae-b1a4-a97eb5353b36.png)

**Comment by jesseduffield** [comment]
see https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md#highlighting-the-selected-line

**Comment by 505384662** [comment]
Thank you so much

**Comment by jesseduffield** [comment]
No worries, closing
