### ISSUE TITLE
Opening two modal dialogs can result in a broken interaction state

### ISSUE THREAD

**Issue by peppy** [jesseduffield/lazygit#1917]
**To Reproduce**
1. Focus commits panel
2. Press "reword" binding and leave confirmation visible on screen. 
4. Press "recent repositories" binding. 
5. Hit escape many times.

**Expected behavior**

Should be able exit both modal dialogs, but can only exit one.

**Screenshots**

https://user-images.githubusercontent.com/191335/167097323-c511c378-8167-45a7-a1f6-b15214dff52f.mp4

**Desktop (please complete the following information):**
 - OS: macOS
 - The last commit id if you built project from sources: 6253258d4b59ab35088145e4b799dbbedec6783c

**Comment by mark2185** [comment]
This may be solved by #1648 which is still in progress.

**Comment by peppy** [comment]
This one's pretty frustrating, have had it happen a few times a week.

**Comment by jesseduffield** [comment]
Sorry for neglecting this one @peppy . Fixed by https://github.com/jesseduffield/lazygit/pull/2079
