### ISSUE TITLE
Chinese commit message display incompleted

### ISSUE THREAD

**Issue by linningmii** [jesseduffield/lazygit#192]
Logs and commit messages cannot fully display Chinese characters.

OS: macOS 10.13.6
terminal: zsh

##### lazygit
![image](https://user-images.githubusercontent.com/14858674/44320643-dc5cd380-a475-11e8-9a11-87a99c839d8e.png)

##### sourceTree
![image](https://user-images.githubusercontent.com/14858674/44320652-f0a0d080-a475-11e8-83bb-d656a18e8937.png)

**Comment by jesseduffield** [comment]
Yeah it looks like this is an issue with the gocui library itself. I believe an issue has been raised there. Nonetheless I'm closing this issue as a duplicate of #24
