### ISSUE TITLE
recent repositories list lost first character

### ISSUE THREAD

**Issue by lddsb** [jesseduffield/lazygit#1922]
**Describe the bug**
Recent repositories list lost first character.

**To Reproduce**
1. input `lg` then input `enter`

**Screenshots**
![image](https://user-images.githubusercontent.com/20765867/167246806-810b03fe-e191-4d04-ae19-680ffa0fb80f.png)

**Desktop (please complete the following information):**
 - OS: `Ubuntu`
 - Lazygit Version: `commit=, build date=2021-04-11, build source=debian, version=0.27.4, os=linux, arch=amd64`

**Comment by mark2185** [comment]
That's a pretty dated version, could you update and try again?

**Comment by lddsb** [comment]
> That's a pretty dated version, could you update and try again?

okok
