### ISSUE TITLE
Add option to disable scrollbars

### ISSUE THREAD

**Issue by mvllow** [jesseduffield/lazygit#1924]
**Describe the solution you'd like**

An option to disable the newly added scrollbars from #1878

**Describe alternatives you've considered**

- Because the smaller left boxes already have context such as "8 of 8" to indicate where you are in the list, an alternative solution could be to only have scrollbars on the larger, main section.

**Comment by fschoenfeldt** [comment]
I totally agree, it makes lazygit look chunkier and busier.

I'd like to deactivate the scrollbars aswell / or maybe just make em not so thick.

**Comment by liaohui5** [comment]
I support this proposal with both hands, it looks ugly, and too wide

**Comment by liaohui5** [comment]
Is there any solution now?

**Comment by jesseduffield** [comment]
I agree, the scrollbars do look pretty chunky. I want to know if it's possible to redesign them to be less chunky such that users don't feel the need to reach for a config option. For example, what do people think of these:

![image](https://github.com/jesseduffield/lazygit/assets/8456633/115fb068-ba0d-4097-85b3-71a474312f9d)

![image](https://github.com/jesseduffield/lazygit/assets/8456633/2b3bcfe8-a677-4cae-8ec6-a7f4d78b5988)


(compared to current)
![image](https://github.com/jesseduffield/lazygit/assets/8456633/db9248d1-e8c1-49dd-9204-b4eefd9a090f)

**Comment by stefanhaller** [comment]
It would be great to have a (hacky) patch to try these out, would that be possible easily?

**Comment by jesseduffield** [comment]
Here ya go: https://github.com/jesseduffield/lazygit/commit/7c5ecf8bd55208525f13d945ef4dacb27a21092f

**Comment by stefanhaller** [comment]
Thanks. It's really tricky to find a good balance between it being discernible (at a glance) and still looking elegant. I feel we could do without the `┴` and `┬` to mark the beginning and end of the scrollbar; it looks more elegant without, and I think it's still clear enough. Drawing a black line seems to result in gray in your color scheme, but in mine I can hardly see the line.

Here's another attempt that's much simpler: 7a190f080625. I'm not saying it's better, just some more input. It's too bad that the thicker line isn't centered, but I couldn't find a glyph that's better. Also, for this the algorithm in `calcScrollbar` needs to be adapted, it now has a minimum size of 3, but it should be 1. I couldn't concentrate enough on the math needed for that right now.

**Comment by jwhitley** [comment]
I rather like the first option, from the screenshot. Effective, but less "bold" and therefore visually obtrusive. For the record, I _really_ like the addition of scrollbars. But one view of the history of scrollbars is "a big catfight over how they should look." 😜

I'll grab the branch later and try these options out.

**Comment by jesseduffield** [comment]
For the sake of comparison here's @stefanhaller's scrollbar:

![image](https://github.com/jesseduffield/lazygit/assets/8456633/97f18360-689a-4519-a10d-d573799dc699)

I actually like this quite a bit: I avoided using glyphs that weren't centered, but I actually think this works really well because the scrollbar isn't encroaching on the content inside the view: instead it's taking up the space between the views which is just dead space.

It does feel _slightly_ awkward that the scrollbar's bounds aren't clearly defined, but I can't think of a glyph that we could put on either end that could signify the bounds, e.g. this looks bad:
![image](https://github.com/jesseduffield/lazygit/assets/8456633/21e463f0-7d97-4d71-aae5-92fc11b85051)

So on net I think having a boundless scrollbar is better. All we need to do is change it so that it can be one character long at minimum.

**Comment by jesseduffield** [comment]
I'm gonna add this to the v0.41 milestone because once you really see the existing chunky scrollbars for what they are you cannot unsee

**Comment by jesseduffield** [comment]
> Are you expecting me to do that? I wouldn't be angry if you beat me to it...

I've just spent a couple minutes on it myself and I am struggling to actually find the right place to change, so any assistance is appreciated (though I truly made this bed myself and now it's time to sleep in it)

**Comment by stefanhaller** [comment]
I had the feeling that you'll need to adapt all of `calcScrollbar`, `calcScrollbarHeight`, and `calcRealScrollbarStartEnd` somehow. But it's really just a feeling, couldn't really wrap my head around it yet. And now I'm going to bed. Good luck!

**Comment by jesseduffield** [comment]
Good night :)

**Comment by jesseduffield** [comment]
Alright with https://github.com/jesseduffield/lazygit/pull/3283 we now have slim scrollbars. 

Before:
![image](https://github.com/jesseduffield/lazygit/assets/8456633/48d2ee7e-fede-4b3c-a93b-0993332b5600)

After:
![image](https://github.com/jesseduffield/lazygit/assets/8456633/79aa4dd4-894a-44e9-a690-0a00e5dc2e00)

Now the question is: is this a big enough improvement to remove the need to make scrollbars's visibility configurable? I think at the very least we should see how people react in the next release.

**Comment by apazzolini** [comment]
> Now the question is: is this a big enough improvement to remove the need to make scrollbars's visibility configurable? I think at the very least we should see how people react in the next release.

Thanks for revisiting this issue! FWIW I will personally still use my fork that disables the scrollbars. I don't see any value in their presence given the `123 of 456` footer, it's just unneeded visual noise for me.
