### ISSUE TITLE
Automatic fetch resets scroll position

### ISSUE THREAD

**Issue by bin101** [jesseduffield/lazygit#1942]
**Describe the bug**
Automatic fetch resets scroll position

**To Reproduce**
1. Scroll down inside Log/Patch/etc.
2. Wait for automatic fetch (default every 60s)
3. Scroll position will be reset and you are back on top

**Expected behavior**
I want to stay on my current scroll position

**Desktop (please complete the following information):**
 - OS: macos 11.6.1
 - Lazygit Version v0.34

**Comment by piegamesde** [comment]
At the moment, this is my only true pain point with lazygit, because it forces me to switch to tig when I want to browser longer commit diffs.

**Comment by kkHAIKE** [comment]
maybe fixed in 0.35

**Comment by bin101** [comment]
yes seems to be fixed. I will close this now.
