### ISSUE TITLE
Show current checked out branch on "Recent Repositories" dialog

### ISSUE THREAD

**Issue by rmti** [jesseduffield/lazygit#1949]
I work with 14 different repos and often use the same branch name when making related changes across different repos. It would be great to be able to see the current selected branch when showing the "Recent Repositories" to make it easier to see what branches are being worked on across projects, i.e. see the project/checked out branches in one shot.

**Comment by mark2185** [comment]
@jesseduffield this seems doable, just a `git -C lazygit rev-parse --abbrev-ref HEAD` for every repository in the list, does that sound reasonable?

It could be triggered by opening the `recent repos` window, which would also be a great time to filter out invalid paths?
