### ISSUE TITLE
How do I get alternative icons?

### ISSUE THREAD

**Issue by bastianpedersen** [jesseduffield/lazygit#1952]
**Topic**
How do I get alternative icons in the `branches` panel like the ones on the picture?

![obs64_HEpFtQ0toj](https://user-images.githubusercontent.com/58905488/168554655-d8dc5a3b-1e2f-4eab-b762-4b6c739f0bb0.png)

**Comment by mark2185** [comment]
Which icons are you asking about, the ones on the right side of the branch name?

They are in the current `master`, as long as you are using a font that provides them they should appear by default.

**Comment by mark2185** [comment]
`Nerd fonts` should have it. 

As for how to install it - I have no idea.
