### ISSUE TITLE
Add hashtag in commit message

### ISSUE THREAD

**Issue by MolletSimon** [jesseduffield/lazygit#1955]
**The bug**
We can't add hashtag (#) in our commit message, ALT+GR + " doesn't work, Alt + 35 neither.

**To Reproduce**
1. Add some files
2. Try to add hashtag to commit message

**Expected behavior**
A # should appear

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Lazygit Version 0.34
 - Commit id : 7be25a105d389a262ef040133a4270f2f745d255

**Comment by mark2185** [comment]
Until this is fixed - try using a different keyboard layout, adding `#` with `shift+3` in the US layout works fine.

**Comment by stefanhaller** [comment]
Should be fixed by #3194.
