### ISSUE TITLE
Edit the highlighted line in the diff with Kakoune

### ISSUE THREAD

**Issue by JacobTravers** [jesseduffield/lazygit#1958]
Sometimes I read a diff and spot an error. I would like to be able to highlight that error in the diff view, and then press `e` to open the editor at that specific line of the file.

Most editors support this passing in the line number as an additional argument prefixed with `+` for example:
```sh
$EDITOR "$file_name" +"$line_number"
```

**Comment by mark2185** [comment]
Could you try updating? That feature is in `master` for quite a while now.

Which editor are you using? It should work for `nano`, `emacs`, `vi`, `vim`, `neovim`, `sublime` and `vscode`.

**Comment by JacobTravers** [comment]
Ahh I see the issue [here](https://github.com/jesseduffield/lazygit/blob/babb9d86567593bb0707570d3105d1010bf8aca9/pkg/commands/git_commands/file.go#L63), I am using `kakoune` or `kak`

**Comment by mark2185** [comment]
This part of the docs might of help, then:

> You can specify a line number you are currently at when in the line-by-line mode.
```
os:
  editCommand: 'vim'
  editCommandTemplate: '{{editor}} +{{line}} -- {{filename}}'
```

**Comment by JacobTravers** [comment]
Thank you very much for the help! I should have looked into this more, closing this issue out.
