### ISSUE TITLE
Test fails, when building debian package

### ISSUE THREAD

**Issue by dawidd6** [jesseduffield/lazygit#196]
**Describe the bug**
One test fails when building debian package.

**To Reproduce**
1. Try to build debian package
2. Observe getting similar error
```sh
	go test -v github.com/jesseduffield/lazygit github.com/jesseduffield/lazygit/pkg/app github.com/jesseduffield/lazygit/pkg/commands github.com/jesseduffield/lazygit/pkg/config github.com/jesseduffield/lazygit/pkg/git github.com/jesseduffield/lazygit/pkg/gui github.com/jesseduffield/lazygit/pkg/i18n github.com/jesseduffield/lazygit/pkg/test github.com/jesseduffield/lazygit/pkg/utils github.com/jesseduffield/lazygit/scripts
go: disabling cache (/nonexistent/.cache/go-build) due to initialization failure: mkdir /nonexistent: permission denied
?   	github.com/jesseduffield/lazygit	[no test files]
?   	github.com/jesseduffield/lazygit/pkg/app	[no test files]
=== RUN   TestDiff
--- FAIL: TestDiff (0.00s)
	git_test.go:35: chdir /var/cache/pbuilder/chroot-ubuntu-xenial-amd64/lazygit/test/repos/: no such file or directory
=== RUN   TestQuote
--- PASS: TestQuote (0.00s)
FAIL
FAIL	github.com/jesseduffield/lazygit/pkg/commands	0.003s
?   	github.com/jesseduffield/lazygit/pkg/config	[no test files]
?   	github.com/jesseduffield/lazygit/pkg/git	[no test files]
?   	github.com/jesseduffield/lazygit/pkg/gui	[no test files]
?   	github.com/jesseduffield/lazygit/pkg/i18n	[no test files]
?   	github.com/jesseduffield/lazygit/pkg/test	[no test files]
=== RUN   TestSplitLines
--- PASS: TestSplitLines (0.00s)
=== RUN   TestWithPadding
--- PASS: TestWithPadding (0.00s)
=== RUN   TestTrimTrailingNewline
--- PASS: TestTrimTrailingNewline (0.00s)
PASS
ok  	github.com/jesseduffield/lazygit/pkg/utils	0.002s
?   	github.com/jesseduffield/lazygit/scripts	[no test files]
```

**Expected behavior**
Pass all tests.

**Desktop (please complete the following information):**
 - OS: Ubuntu 16.04
 - Lazygit Version: master

**Additional context**
Seems like with this command above `go test -v ...` current directory is being changed or idk. I guess that current dir then is `pkg/commands` and that's why it's failing but i may be wrong.

Problem exists only when building debian packages, currently i disabled testing at all but, well.

**Comment by dawidd6** [comment]
Okay, my bad problem exists only when building debian package, hmm.

**Comment by jesseduffield** [comment]
looks like `mkdir /nonexistent: permission denied` is the giveaway. Perhaps it's a permissions issue? I found this which looks related https://github.com/golang/go/issues/23638

**Comment by dawidd6** [comment]
Nah, it's just the cache, the problem is somewhere else. Need to investigate it deeper.

**Comment by dawidd6** [comment]
@jesseduffield found the cause:

https://github.com/jesseduffield/lazygit/blob/2aa89ade0dff22658c7a550213f5d4b7c4eeb229/pkg/utils/utils.go#L70-L76

Don't know why this split is necessary tho.

I've produced a patch for that:
```diff
diff --git a/pkg/test/test.go b/pkg/test/test.go
index 7bdbd4c..ff133a6 100644
--- a/pkg/test/test.go
+++ b/pkg/test/test.go
@@ -4,6 +4,7 @@ import (
        "errors"
        "os"
        "os/exec"
+       "path/filepath"
 
        "github.com/jesseduffield/lazygit/pkg/utils"
 )
@@ -11,7 +12,14 @@ import (
 // GenerateRepo generates a repo from test/repos and changes the directory to be
 // inside the newly made repo
 func GenerateRepo(filename string) error {
-       testPath := utils.GetProjectRoot() + "/test/repos/"
+       reposDir := "/test/repos/"
+       testPath := utils.GetProjectRoot() + reposDir
+
+       // workaround for debian packaging
+       if _, err := os.Stat(testPath); os.IsNotExist(err) {
+               cwd, _ := os.Getwd()
+               testPath = filepath.Dir(filepath.Dir(cwd)) + reposDir
+       }
        if err := os.Chdir(testPath); err != nil {
                return err
        }
```

Would it be merged if i would pack it up in PR?

**Comment by jesseduffield** [comment]
@dawidd6 the split was so that we could go from `/a/b/lazygit/c/d` to `['a/b/', '/c/d']` to `a/b/lazygit` i.e. getting to the project root. 

Is the issue with debian packaging that we're not inside the lazygit directory when we invoke the tests? Would it be possible to cd into the directory to run the test, then `cd ..` back out again? I'm hesitant to add code to the codebase that's packaging-specific. But if there's no other way, I'm happy to merge it

**Comment by dawidd6** [comment]
`GetProjectRoot()` is returning non existing directory. When test is invoked, current directory is `pkg/commands`

**Comment by jesseduffield** [comment]
Fair enough :) If you raise a PR with the above patch I'll happily merge
