### ISSUE TITLE
Move patch into new commit with message

### ISSUE THREAD

**Issue by mark2185** [jesseduffield/lazygit#1963]
**Is your feature request related to a problem? Please describe.**
Usually when I use `move patch into new commit` I'd like to reword that commit, I'd rather get the popup with the `Split from <patch message here">` as initial value than having to manually go back, reword the newly added commit, and return to the view where I was (since I want to split a few other things as well)

**Describe the solution you'd like**
Popup for the new commit message.

**Comment by derteta** [comment]
I've had the same wish and made a [prototype](https://github.com/derteta/lazygit/tree/pull-patch-reword-commit). It simply re-uses the "reword commit" prompt (meaning it also suffers from [this issue](https://github.com/jesseduffield/lazygit/issues/2060)). Would that work for you?

**Comment by mark2185** [comment]
Actually yes, that's exactly what I had in mind! 

Except that I always get `error: <changed file>: does not exist in index` :)

Feel free to open a PR to continue the discussion there.

**Comment by derteta** [comment]
:facepalm: You're right! It was working at some point, must have messed up somewhere.
Will fix it, set up a PR and ping you in it!

**Comment by mark2185** [comment]
@derteta are you able to open up a PR so we finish  this up, doesn't seem like it needs too much additional work on top of what you've already done :)

**Comment by mark2185** [comment]
Solved by #2800 .
