### ISSUE TITLE
yaml: unmarshal errors

### ISSUE THREAD

**Issue by linzhefeng** [jesseduffield/lazygit#1968]
**Describe the bug**
I use brew install lazygit, and run 'lazygit ', and then some error happend

yaml: unmarshal errors:
  line 1: cannot unmarshal !!str `o` into config.UserConfig

**Desktop (please complete the following information):**
 - OS: [macos 11.5.1]
 - Lazygit Version [lastest version 2022.05.28]

**Comment by mark2185** [comment]
There's a mistake in your config, could you post it, please?

**Comment by linzhefeng** [comment]
> 

I am new in lazygit, idk where the config file is, please tell the path

**Comment by mark2185** [comment]
It should be in `~/Library/Application Support/lazygit/config.yml`

**Comment by linzhefeng** [comment]
> It should be in `~/Library/Application Support/lazygit/config.yml`

lol,thank you so much ~ , I think the problem has been solved!!(but I am so sure I never edit this file before😂)
![image](https://user-images.githubusercontent.com/50944875/170825826-ce598111-9b86-4322-b3f8-af766fb819b6.png)

**Comment by mark2185** [comment]
Great! Glad that it's fixed, feel free to close up the issue :)
