### ISSUE TITLE
Allow esc to exit program when not in the popup panel

### ISSUE THREAD

**Issue by InnovativeInventor** [jesseduffield/lazygit#197]
**Is your feature request related to a problem? Please describe.**
Most users will expect esc to be able to exit the program when a popup panel is not open.

**Describe the solution you'd like**
I would like pressing esc to exit the program when a popup panel is not open.

**Describe alternatives you've considered**
None.

**Additional context**
This was rather annoying to get used to when I first started using lazygit.

**Comment by remyabel** [comment]
Here, try this:

```diff
diff --git a/pkg/gui/keybindings.go b/pkg/gui/keybindings.go
index 68cccda..d09ed64 100644
--- a/pkg/gui/keybindings.go
+++ b/pkg/gui/keybindings.go
@@ -16,6 +16,7 @@ func (gui *Gui) keybindings(g *gocui.Gui) error {
        bindings := []Binding{
                {ViewName: "", Key: 'q', Modifier: gocui.ModNone, Handler: gui.quit},
                {ViewName: "", Key: gocui.KeyCtrlC, Modifier: gocui.ModNone, Handler: gui.quit},
+               {ViewName: "", Key: gocui.KeyEsc, Modifier: gocui.ModNone, Handler: gui.quit},
                {ViewName: "", Key: gocui.KeyPgup, Modifier: gocui.ModNone, Handler: gui.scrollUpMain},
                {ViewName: "", Key: gocui.KeyPgdn, Modifier: gocui.ModNone, Handler: gui.scrollDownMain},
                {ViewName: "", Key: gocui.KeyCtrlU, Modifier: gocui.ModNone, Handler: gui.scrollUpMain},
```

**Comment by remyabel** [comment]
Posted a new diff, please test and let me know if there's any problems.

**Comment by InnovativeInventor** [comment]
I tried doing that, and it does not work.

**Comment by remyabel** [comment]
What doesn't work, specifically?

**Comment by remyabel** [comment]
I've added a gif.

![esc](https://user-images.githubusercontent.com/41764622/44380545-fa5c1f80-a4d9-11e8-9308-66b0351ce9f9.gif)

**Comment by InnovativeInventor** [comment]
Sorry, I didn't build it properly and executed the precompiled lazygit binary. It works as expected, nice job!
