### ISSUE TITLE
Lazygit asking for username/password every time I push/pull

### ISSUE THREAD

**Issue by skossan** [jesseduffield/lazygit#1982]
**Topic**
Lazygit is asking me for my username and password every time I wanna push/pull a branch.

**Your thoughts**
I installed LG on my Linux Mint by downloading the tar.gz file and extracted the executable and moved it to */usr/bin*.
It seems like my username/password isn't stored somewhere hence why it's asking me every time. 

Any tips on how to avoid this?

**Comment by mark2185** [comment]
It's not a `lazygit` issue, it's due to `git` itself, I presume. Have you tried using RSA keys or increasing the cache timeout?

**Comment by skossan** [comment]
I installed git the other day using *sudo apt install git* and haven't used it until now. I've never had this problem before using git.

**Comment by mark2185** [comment]
Does `git` ask you to type in your username and password when pushing and pulling? If it does, then _it_ isn't stashing your credentials.

**Comment by skossan** [comment]
> Does `git` ask you to type in your username and password when pushing and pulling? If it does, then _it_ isn't stashing your credentials.

It does yes. However. I've only ever used git on windows and mac before and there, it never asks for username/password. Perhaps itäs different on Linux?

**Comment by mark2185** [comment]
Don't know about `windows`, and `MacOS` probably uses the system's keychain, as for linux, either setup [caching](https://stackoverflow.com/questions/5343068/is-there-a-way-to-cache-https-credentials-for-pushing-commits) or use RSA keys.

In any case, it isn't a `lazygit` issue.

**Comment by skossan** [comment]
> Don't know about `windows`, and `MacOS` probably uses the system's keychain, as for linux, either setup [caching](https://stackoverflow.com/questions/5343068/is-there-a-way-to-cache-https-credentials-for-pushing-commits) or use RSA keys.
> 
> In any case, it isn't a `lazygit` issue.

Thank for the tip. I'm glad to hear it's not lazygit. Have used LG before on both windows and mac and it's always been great!
I guess this can be closed!

**Comment by mark2185** [comment]
Feel free to close it then, tack! :)
