### ISSUE TITLE
Commit message history on commit

### ISSUE THREAD

**Issue by oprichnik** [jesseduffield/lazygit#199]
A simple usefull enhancement would be to navigate between commits messages with UP / DOWN arrows when commit popup is open (to allow something like `git commit -c HEAD~X`).

**Comment by dawidd6** [comment]
I have implemented it here: https://github.com/dawidd6/lazygit/tree/feature/commit_history

Cycling is done with `Home` and `End` keys currently. Would be great if you @oprichnik could test it.

**Comment by jesseduffield** [comment]
The home/end approach sounds good to me. Not sure how stale that implementation is but this sounds like a small-enough feature to be a good fit for hacktoberfest

**Comment by jesseduffield** [comment]
note that home/end are now being used to jump to the start/end of the commit message so we'd need to find other keybindings

**Comment by jesseduffield** [comment]
Sounds good @Liberatys :)

**Comment by sportshead** [comment]
@jesseduffield currently <kbd>Up</kbd> jumps to the start of the commit message, while <kbd>Down</kbd> does nothing. Since <kbd>Home</kbd> already jumps to the start, what do you think about <kbd>Up</kbd>/<kbd>Down</kbd> for navigating through commit messages?

**Comment by mark2185** [comment]
This has been implemented in #2390, closing.
