### ISSUE TITLE
On mac, runnning lazygit in a tmux popup pane fails

### ISSUE THREAD

**Issue by carjuan** [jesseduffield/lazygit#1995]
**Describe the bug**
On Mac, when using tmux popup pane feature: `tmux popup -E "lazygit"`, I get `*exec.ExitError status 1` as seen in screenshot below.
If not running Lazygit in a tmux popup pane, that is in a regular tmux session, it works as expected. 

**To Reproduce**
1. On Mac, run tmux
2. type command `tmux popup -EE "lazygit"
3. floating window shows "An error occurred..."

**Expected behavior**
I have installed lazygit version 0.34 and tmux version 3.3a on both Ubuntu 20.04.4 LTS and WSL. They both run as expected. See _Additional context_ for screenshots of expected behaviour

**Screenshots**
<img width="1179" alt="Screen Shot 2022-06-11 at 3 20 39 PM" src="https://user-images.githubusercontent.com/52611356/173204673-caa7c8d7-ae52-4158-af38-6a4d2187aa84.png">

**Desktop (please complete the following information):**
 - OS: Darwin 
 - Lazygit Version: 0.34
 
**Additional context**
This is what I get when using a Linux machine or WSL which is the expected behaviour:
![WbpC5XK](https://user-images.githubusercontent.com/52611356/173204842-ce7d40d6-9a3a-41d4-98fc-71a82c146190.png)

**Comment by tg0h** [comment]
![Screenshot 2022-06-12 at 10 21 02 - kitty@2x](https://user-images.githubusercontent.com/7954426/173211715-965cfcae-b0a9-45e8-8949-f5fd5263c8a3.jpg)

strange, it works for me ...

**Comment by mark2185** [comment]
@carjuan have you had any luck narrowing it down, maybe? I can't reproduce it locally, and it seems to work for @tg0h as well.

Trying a different `terminal emulator`, building current `master`?

**Comment by serhez** [comment]
I'm having the same issue! I am running on alacritty, zsh, Intel Mac.

**Comment by mark2185** [comment]
@serhez current `master` or `v0.34`? If it's the latter, try the former.

**Comment by serhez** [comment]
Just tested it on an M1 Pro Mac, and it also fails the same way.

**Comment by mark2185** [comment]
I presume it's the latest release (3 months old), not `master`.

**Comment by serhez** [comment]
👆🏻 It works on master (I built from source using `go install`). Ideally, I'd like to have lazygit through brew so that I don't have to manually build for updates, can this fix be released any time soon?

Thanks btw :)

**Comment by mark2185** [comment]
For that we'll have to summon @jesseduffield .

In other news, does `brew` support some sort of `-git` packages like the AUR does? I'm not very experienced with homebrew, but if anyone would like to contribute _something_ that would allow people to install current `master`, that'd be swell!

**Comment by jesseduffield** [comment]
I have been holding off on a release for a while but it really is time for one. I'll try to get one out today (will take a while to write up the release notes though given the time since the last release haha)

**Comment by carjuan** [comment]
> 👆🏻 It works on master (I built from source using `go install`). Ideally, I'd like to have lazygit through brew so that I don't have to manually build for updates, can this fix be released any time soon?
> 
> Thanks btw :)
This!

**Comment by carjuan** [comment]
> 👆🏻 It works on master (I built from source using `go install`). Ideally, I'd like to have lazygit through brew so that I don't have to manually build for updates, can this fix be released any time soon?
> 
> Thanks btw :)

This!

**Comment by carjuan** [comment]
> @serhez current `master` or `v0.34`? If it's the latter, try the former.

I built it from source and it now works. Just as @serhez described.

**Comment by mark2185** [comment]
@lougreenwood not yet, `v0.34` is still the latest version. I'll let you know here when it gets updated, in the meantime I'd suggest you to keep using the manually built one.

**Comment by mark2185** [comment]
@lougreenwood `v0.35` is out, feel free to take it for a spin!

**Comment by mark2185** [comment]
@serhez how about now?

**Comment by serhez** [comment]
@mark2185 still getting v0.34 😞 I am guessing it's on `homebrew`'s side to update the tap?

**Comment by mark2185** [comment]
No idea, [homebrew says it's at](https://formulae.brew.sh/formula/lazygit) `v0.35`.

**Comment by carjuan** [comment]
can confirm, 0.35 is up, running and working as expected now! Thank you guys @jesseduffield @mark2185
