### ISSUE TITLE
Esc wont close commit message window/Takes me out of insert mode

### ISSUE THREAD

**Issue by whoop-t** [jesseduffield/lazygit#1999]
**Describe the bug**
Using Astronvim (This may actually just be an Astronvim issue, if believed so I will close issue and open there)
When in commit message prompt, esc just takes me out of insert mode. Cant exit any prompt in lazygit

**To Reproduce**
1. Clone Astronvim
2. brew install lazygit (tap)
3. make change to file, open lazygit (leader + gg)
4. Open commit prompt, press esc

**Expected behavior**
Close commit message window

**Screenshots**
![Screen Shot 2022-06-12 at 10 20 34 PM](https://user-images.githubusercontent.com/52976607/173285453-d907ea92-e6c4-4a5a-bc6e-f9d41ba6c160.png)
(cursor fly off to do its own thing)

**Desktop (please complete the following information):**
 - OS: macOS Monterey
 - Latest

**Comment by mark2185** [comment]
> Using Astronvim (This may actually just be an Astronvim issue, if believed so I will close issue and open there)

I didn't quite get this part, do you open `lazygit` from _within_ `astronvim`, in the internal `terminal` or? Does it happen with regular `nvim`?

> Latest

Does that mean you've built from sources or?

Because if it doesn't, could you try building current `master` to see if it helps?
