### ISSUE TITLE
[Question/Discussion] using .git/info/exclude to exclude local file instead of .gitignore 

### ISSUE THREAD

**Issue by gozes** [jesseduffield/lazygit#2014]
**should there be an option to use .git/info/exclude in the File window?**
A bit of context from the git docs as to what .git/info/exclude  is 

> Patterns which are specific to a particular repository but which do not need to be shared with other related repositories (e.g., auxiliary files that live inside the repository but are specific to one user's workflow) should go into the $GIT_DIR/info/exclude file.
 FYI this file has the same format as `.gitignore`

**Your thoughts**
I really think it will be quite useful to have let say `I` in the File window to add files to the exclude file along side the `i` command we already have. 

I use this quite a bit to put my editor config for a repo. Another good example of using this is to put the VSCode `devcontainer.json` used in the Remote container extension so that you can have your own container to run a project in. Has anyone else used the exclude file before if so what do you think will it be useful to have this in lazygit?

**Comment by mark2185** [comment]
Is this just a `.gitignore` that isn't committed, if I'm reading into this right?

**Comment by gozes** [comment]
@mark2185 yup it just goes inside of `.git/info/` instead of the root of your project and I believe it has to be called `exclude`

**Comment by mark2185** [comment]
Sounds like a neat addition, didn't even know about it.

Would you be interested in opening a PR? The logic should be the same as with adding to `.gitignore`, only the destination differs.

**Comment by gozes** [comment]
@mark2185 I will love too, can you point me ate where the logic for this is. I was looking but was having a hard time finding it :)

**Comment by mark2185** [comment]
Off the top of my head - look into the files changed in PR #2004, that should be a start.

Let me know if you need additional pointers and I'll take a closer look next time I'm at my laptop.

**Comment by gozes** [comment]
So having another look at this it seams like there is a few references to gitignore in `git_commands` package in `working_tree.go` and in `file_controller.go` I'm still looking at the code trying to find the best place to add this. I have yet to find how this things relate to the file window in the GUI.

**Comment by mark2185** [comment]
The one you're looking for is in [files_controller.go](https://github.com/jesseduffield/lazygit/blob/41071c37035a5944f77b4f0da5f07ec3b52fef0e/pkg/gui/controllers/files_controller.go#L90), this sets the function [ignore](https://github.com/jesseduffield/lazygit/blob/41071c37035a5944f77b4f0da5f07ec3b52fef0e/pkg/gui/controllers/files_controller.go#L305) as the handler for when someone presses `IgnoreFile` (which is `i` by default).

What we're trying to go for now is adding a new mapping (`I`) which would do the same thing as `ignore()`, but write to a different file in the end. Since it does exactly the same thing, I'd suggest making `ignore` take an additional argument beside the `filetree.FileNode`, which would be a `string` representing the `destination file` and then just pass the correct one when the user presses `i` or `I`. Of course, the subsequent call to `Ignore()` should also be modified.

The handlers could be ordinary lambdas that do what [checkSelectedFileNode](https://github.com/jesseduffield/lazygit/blob/41071c37035a5944f77b4f0da5f07ec3b52fef0e/pkg/gui/controllers/files_controller.go#L217) does before invoking `ignore(node, <correct destination file>)`. Maybe @jesseduffield has a better idea how to do that, but I'd rather leave that for the review.

Does that help? Do let us know if there's anything else to clear up! :)

**Comment by gozes** [comment]
ok so just did my first try on it and send you a draft [PR](https://github.com/jesseduffield/lazygit/pull/2016) for it. It probably needs some more work. One question I still have is how to actually add `I` binding. Happy to keep working with you on this as I'm still finding my feet in the codebase so any guidance/support you can offer is greatly appreciated

**Comment by gozes** [comment]
> The one you're looking for is in [files_controller.go](https://github.com/jesseduffield/lazygit/blob/41071c37035a5944f77b4f0da5f07ec3b52fef0e/pkg/gui/controllers/files_controller.go#L90), this sets the function [ignore](https://github.com/jesseduffield/lazygit/blob/41071c37035a5944f77b4f0da5f07ec3b52fef0e/pkg/gui/controllers/files_controller.go#L305) as the handler for when someone presses `IgnoreFile` (which is `i` by default).
> 
> What we're trying to go for now is adding a new mapping (`I`) which would do the same thing as `ignore()`, but write to a different file in the end. Since it does exactly the same thing, I'd suggest making `ignore` take an additional argument beside the `filetree.FileNode`, which would be a `string` representing the `destination file` and then just pass the correct one when the user presses `i` or `I`. Of course, the subsequent call to `Ignore()` should also be modified.
> 
> The handlers could be ordinary lambdas that do what [checkSelectedFileNode](https://github.com/jesseduffield/lazygit/blob/41071c37035a5944f77b4f0da5f07ec3b52fef0e/pkg/gui/controllers/files_controller.go#L217) does before invoking `ignore(node, <correct destination file>)`. Maybe @jesseduffield has a better idea how to do that, but I'd rather leave that for the review.
> 
> Does that help? Do let us know if there's anything else to clear up! :)

Just saw this after making the draft PR. will have look again at this over the weekend and amend my PR with your comments :)

**Comment by gozes** [comment]
@mark2185 looking at this at the moment. I don't think your suggestion will work because it calls to `WorkingTree.Ignore` so I have refactored `WorkingTree.Ignore` into a more general `Omit` function in `WorkingTree` so I can use it for both ignoring and excluding. I'm trying to refactor `ignore` in  `file_controller` so I can have a clear separation between ignoring and excluding.  :)

**Comment by mark2185** [comment]
> I have refactored WorkingTree.Ignore into a more general Omit function

That's perfectly reasonable, it _could/should_ take a parameter as the destination file.

> Of course, the subsequent call to `Ignore()` should also be modified.

_That_, as well as the rest of the steps down to the bottom, such as `WorkingTree.Ignore`, as you've noted :)

**Comment by gozes** [comment]
@mark2185 ok so the Refactoring was successful and ignore is back to working order. However, I can get exclude (a.k.a `I`) to show up in the menu and I'm not sure why. Have I missed something?

**Comment by gozes** [comment]
BTW @jesseduffield  your [video](https://www.youtube.com/watch?v=kNavnhzZHtk) on adding a feature was really helpful in getting to grips with the bits of the codebase I have to touch. Thank you for making it. I hope you will make more like it in the future

**Comment by jesseduffield** [comment]
No worries @gozes ! I'm in the process of trying to free up more time to make more videos / guides so hopefully there'll be more in the near future

**Comment by mark2185** [comment]
I believe this can be closed now :)

Great work! @gozes
