### ISSUE TITLE
i need page turning with keyboard on info panel , example Logs panel or Patchs panel

### ISSUE THREAD

**Issue by AustinWp** [jesseduffield/lazygit#2025]
Like this area ...  support page turning 

![image](https://user-images.githubusercontent.com/11920137/177260464-a11e488d-a086-4e3a-b5fa-0e11c600fbf7.png)
![image](https://user-images.githubusercontent.com/11920137/177260538-64870462-45be-48cf-8a60-f2262881adce.png)

**Comment by jesseduffield** [comment]
closing because you did not use the provided template. Happy to reopen if you change the description to match the template
