### ISSUE TITLE
Merge squash

### ISSUE THREAD

**Issue by mark2185** [jesseduffield/lazygit#2028]
### Discussed in https://github.com/jesseduffield/lazygit/discussions/1296

<div type='discussions-op-text'>

<sup>Originally posted by **mestihudson** April 26, 2021</sup>
Is there a way to get a `git merge <branch> --squash`?
I know that is possible to use a custom command, but I'd like to follow the lazygit way.

Thanks for this awesome tool.</div>

**Comment by mark2185** [comment]
I recommend creating a menu under `M` in which we'd have two options:
- `m` would merge as usual
- `s` would merge with `--squash`
- `n` for `--no-commit`,
- `e` for `--edit`

I don't know, surely people will think of something.

@jesseduffield what do you say about moving this to the `m` key, and having the current `m` (`Rebase options`) appear only when in a `rebase/merge` context? Is that easily doable?

I remember reading about that somewhere...

**Comment by LcLz0** [comment]
Old issue, but this would be awesome. This is like the one thing I drop down to a terminal to do.

**Comment by 9mm** [comment]
this would be reallllly sweet

**Comment by jesseduffield** [comment]
@mark2185  all those options are orthogonal so it sounds like we'll need to solve https://github.com/jesseduffield/lazygit/issues/2849 before we can do this (not necessarily the 'complex mode' thing but the menu that lets you configure different args before confirming an action)

**Comment by all500234765** [comment]
bump, would love to see this too

**Comment by ofurtumi** [comment]
bump, this would be really great

**Comment by 9mm** [comment]
Is this on the roadmap anywhere? This seems like a pretty major thing for git software not to have

**Comment by KrekoG** [comment]
Bumping, would be neat to have!
Also, cheers for the hard work on this project in general, Lazygit is my main go to git client.

**Comment by danielo515** [comment]
Will this allow to rebase/squash a branch onto itsel? I many times want to just flat  my current branch commit history

**Comment by stefanhaller** [comment]
> Will this allow to rebase/squash a branch onto itsel? I many times want to just flat my current branch commit history

I don't think so, but this is also not what I would do to flatten my history. The easiest way to do that is to select the last commit _before_ your branch, and hit `g enter` to do a mixed reset. This removes all commits, but leaves all the modifications of the branch in your working copy; from there, you can create one or more new commits.

Alternatively, if you want to keep the first commit and its message and want to squash all other commits into that one, select the second commit of the branch, press and hold shift-up-arrow until you hit the top, and press `f` to fix them up into the first commit.

**Comment by AndrewSav** [comment]
I think this can be closed now because it's implemented in https://github.com/jesseduffield/lazygit/pull/3566

**Comment by 9mm** [comment]
freaking amazing!

**Comment by jesseduffield** [comment]
great work @noahfraiture ! Closing
