### ISSUE TITLE
push after pull another branch, push a wrong branch

### ISSUE THREAD

**Issue by Nauxscript** [jesseduffield/lazygit#2036]
**Describe the bug**
push after pull another branch, push a wrong branch

**To Reproduce**
for example: i got two branches, master and child, child is base on master
1. checkout child, change something and commit 
2. pull remote master on child branch
3. i am still on branch child, and press `P` try to push child
4. command log window say: 

```
Push
  git push "origin" "master"
```

5. child branch haven't push to remote

**Expected behavior**
push the new commit of child branch to remote 

**Screenshots**
![lgerror4](https://user-images.githubusercontent.com/13010589/178921183-2d635baf-8a6f-4a31-aa91-3c0355a8f527.gif)

**Desktop (please complete the following information):**
 - OS: [MacOS]
 - Lazygit Version [0.34]

**Comment by mark2185** [comment]
Please fill out the provided template.

**Comment by Nauxscript** [comment]
> Please fill out the provided template.

ok now

**Comment by Nauxscript** [comment]
I found its not a bug just because I change the upstream....

**Comment by Nauxscript** [comment]
if I want to pull the master branch (I am on child branch and child branch is a new branch, haven't set upstream), how can i do?

**Comment by mark2185** [comment]
The latest version (`v0.34`) doesn't support setting the upstream, but if you can build the current `master`, you can set the upstream by pressing `u` in the branches panel.

Also I think this was actually a bug that was fixed, but not yet released.

**Comment by Nauxscript** [comment]
> The latest version (`v0.34`) doesn't support setting the upstream, but if you can build the current `master`, you can set the upstream by pressing `u` in the branches panel.
> 
> Also I think this was actually a bug that was fixed, but not yet released.

ok, I see .
lets wait the next version.
