### ISSUE TITLE
Can't type certain characters in modal text box

### ISSUE THREAD

**Issue by dpeter99** [jesseduffield/lazygit#2040]
**Describe the bug**
When I try to type a commit message, I can't type in `[ ]`, or when adding a new remote I can't copy in `@`.

**To Reproduce**
1. Go to remoters
2. Click on add new
3. give it any name
4. Try to copy in a SSH URL for the remote

**Expected behavior**
I would expect to be able to use any character in these input fields.

**Desktop (please complete the following information):**
 - OS: Windows
 - Lazygit Version: 0.34

**Comment by mark2185** [comment]
Are you using a US layout?

Could you try building current `master` to see if that helps?

**Comment by dpeter99** [comment]
My keyboard is Hungarian layout. I will check out the `master` after work.

**Comment by mark2185** [comment]
My guess is that the combination of `altGr + <something>` is the underlying issue here.

This cropped up [once before](https://github.com/jesseduffield/lazygit/issues/1955), actually.

@jesseduffield would you happen to have any insight whether this is an issue of a dependency such as `gocui` or?

**Comment by jesseduffield** [comment]
yeah it sounds like a gocui issue: quite possibly the same issue that https://github.com/jesseduffield/lazygit/issues/1516 talks about (there's a PR up to address that but it's stale)

**Comment by Jerakin** [comment]
This is an issue for me to on a Nordic layout, issues like this means I have to swap between layouts when using lazygit which isn't very user friendly :) (but lazygit is so good it's worth it)

**Comment by stefanhaller** [comment]
Should be fixed by #3194.
