### ISSUE TITLE
The mouse click response area does not match the text position on CHINESE language version

### ISSUE THREAD

**Issue by Smalldy** [jesseduffield/lazygit#2048]
**Describe the bug**
The mouse click response area does not match the text position.

Specifically, they are
- 分支页面 
- 远程页面
- 标签页面

if you click the '标' of '标签页面', the '远程页面' will be clicked!

**To Reproduce**
1. Go to main page 
2. Click on '标签页面'
3. See error

**Screenshots**
![图片](https://user-images.githubusercontent.com/14820063/180377092-ada930e6-3e29-41f0-b125-a6b2cbb3bc38.png)

**Desktop (please complete the following information):**
 - OS: ubuntu20.4
 - Lazygit Version : commit=367b0d331836c90c015bf0c45f88612f3d94d08a, build date=2022-07-20T09:27:56Z, build source=binaryRelease, version=0.35, os=linux, arch=amd64

**Comment by Ryooooooga** [comment]
https://github.com/jesseduffield/gocui/pull/20

**Comment by jesseduffield** [comment]
closing as fixed on master
