### ISSUE TITLE
rewording commit

### ISSUE THREAD

**Issue by jslmorrison** [jesseduffield/lazygit#2060]
**Describe the bug**
Characters stripped from front of commit message

**To Reproduce**
1. Pick a commit in reflog
2. Press 'r' on keyboard
3. Dialog box appears in order to edit commit
4. Original commit has (10) chars stripped from start

**Expected behavior**
Original commit should be presented unchanged before rewording.

**Desktop (please complete the following information):**
 - OS: Linux
 - Lazygit Version [0.35]

**Additional context**
Installed using dnf from copr:copr.fedorainfracloud.org:atim:lazygit repo

**Comment by jslmorrison** [comment]
Same occurs when pushing branch to remote for first time, branch name has chars stripped from front.

**Comment by mark2185** [comment]
Just a note: the message isn't actually changed, it's just the view that's shifted. Try holding `Left` and you'll see that everything is there.

It's only a visual bug and I encounter it daily, it is annoying, but nothing worrisome.

**Comment by mark2185** [comment]
This should actually be solved by #2123.

**Comment by mark2185** [comment]
@jslmorrison would you be willing to build current `master` to see if the issue persists? #2123 was merged.

**Comment by jslmorrison** [comment]
@mark2185 That seems to have fixed it now. Thanks
