### ISSUE TITLE
The ability to view an entire commit's patch without going through each file.

### ISSUE THREAD

**Issue by nullishamy** [jesseduffield/lazygit#2063]
**Is your feature request related to a problem? Please describe.**
It's quite annoying having to go through each file in a commit when attempting to view its changes, especially with commits that change a non trivial amount of files.

**Describe the solution you'd like**
It would be nice to have a bind to switch into the patch menu when in the Commits pane.

**Describe alternatives you've considered**
A bind to jump to next file would be okay, though suboptimal.

**Additional context**
N/A

**Comment by mark2185** [comment]
Could you post your `.gitconfig` and your `lazygit/config.yml`?

Selecting a commit in the `Commits` (just highlighting it, not pressing `Enter`) should enable you to scroll through the entire diff with `J/K`, at least that's what it does for me.

**Comment by nullishamy** [comment]
Ah, perfect, that works fine. Im not sure if I missed something in the docs or what, but I could not find out how to do that lol.

**Comment by mark2185** [comment]
Great!

By pressing `x` in any panel a pop-up with all of the keymaps will appear.

By searching for `scroll` with `/scroll<ENTER>` you will find:
- `pgup scroll up main panel`
- `pgdown scroll down main panel`

The `J` and `K` are just alternative mappings.
