### ISSUE TITLE
Bad file descriptor error after updating to v0.35

### ISSUE THREAD

**Issue by batusai513** [jesseduffield/lazygit#2080]
**Describe the bug**
when navigating though the changed files with j/k, the application closes and shows this error:
```
An error occurred! Please create an issue at: https://github.com/jesseduffield/lazygit/issues

syscall.Errno bad file descriptor
/home/runner/work/lazygit/lazygit/pkg/app/app.go:52 (0x1639876)
/home/runner/work/lazygit/lazygit/main.go:154 (0x16472f0)
/opt/hostedtoolcache/go/1.18.4/x64/src/runtime/proc.go:250 (0x10353b2)
/opt/hostedtoolcache/go/1.18.4/x64/src/runtime/asm_amd64.s:1571 (0x10630e1)
```

**To Reproduce**

1. open lazygit on a repository with changes
2. Try to navigate the changed files in the Files window with j/k (scroll down or up really fast or keep the key pressed)

* I cannot reproduce this error on all repos

**Expected behavior**
not seeing any error

**Screenshots**

**Version info:**
`commit=367b0d331836c90c015bf0c45f88612f3d94d08a, build date=2022-07-20T09:27:56Z, build source=binaryRelease, version=0.35, os=darwin, arch=amd64`

**Additional context**

**Note:** please try updating to the latest version or [manually building](https://github.com/jesseduffield/lazygit/#manual) the latest `master` to see if the issue still occurs.

**Comment by mark2185** [comment]
Do you use the `delta` pager by any chance?

**Comment by batusai513** [comment]
@mark2185 I use `delta` pager, yes

**Comment by mark2185** [comment]
There are issues with it currently, if you could use another pager, it would probably solve your problems. We are working on fixing it.
