### ISSUE TITLE
Unable to rebind quit key

### ISSUE THREAD

**Issue by pindab0ter** [jesseduffield/lazygit#2083]
**Describe the bug**
When I rebind the 'quit' key to something else, the default 'quit' key (<kbd>q</kbd>) still quits the program.

**To Reproduce**

1. Add the following to `config.yaml`: 
   ```yaml
   keybinding:
     quit: '<c-q>'
   ```

2. Start `lazygit`
3. Press <kbd>q</kbd>
4. Application quits even though I rebound it to not be <kbd>q</kbd>.

**Expected behavior**
The program should respect the key binding in `config.yaml`.

**Version info:**
`commit=, build date=, build source=homebrew, version=0.35, os=darwin, arch=arm64`

**Comment by Ryooooooga** [comment]
```yaml
keybinding:
  universal:
    quit: 
```
