### ISSUE TITLE
SSH key passphrase area isn't empty on startup

### ISSUE THREAD

**Issue by BenGH28** [jesseduffield/lazygit#2090]
**Describe the bug**
When I go to push a commit to my repo the passphrase area has `*`'s the length of the passphrase area but I can still input my password just fine.  To be clear this is just visual, the password box takes my password just fine, I just can't see it.

**To Reproduce**

1. Commit to a repo
2. Push to the repo using ssh
3. See error

**Expected behavior**
The area should be empty at first only showing the `*` character when typing in the passphrase like a normal password box.

**Screenshots**
![image](https://user-images.githubusercontent.com/45215137/183278479-90c378dc-5a2d-4476-a77b-864862be552b.png)

**Version info:**
- the latest binary on manjaro:
commit=v0.35, build date=2022-07-20T10:20:42Z, build source=binaryRelease, version=0.35, os=linux, arch=amd64
- and source
commit=2e7b935bfb14a5a621e94781933e898b3be0ce93, build date=2022-08-07T03:03:28Z, build source=unknown, version=2e7b935b, os=linux, arch=amd64

**NOTE**: I tried both binary release and building from source

**Comment by mark2185** [comment]
I think this is intended, for privacy purposes. Just like `sudo` doesn't echo back `*` for each character you input.

**Comment by BenGH28** [comment]
Oh I see.  Makes sense. Thanks for the info!
