### ISSUE TITLE
Add git version to lazygit's --version

### ISSUE THREAD

**Issue by mark2185** [jesseduffield/lazygit#2099]
It would be helpful to have the `git` version in the `--version` output to shorten debugging when resolving github issues.

This seems like a somewhat trivial task.

**Comment by nitinmewar** [comment]
can I start working on it?

**Comment by mark2185** [comment]
Definitely! Let us know if you need any pointers.

**Comment by nitinmewar** [comment]
it is my first open source pull request. I just did 2 commits for this issue. please let me know if there is anything more to do.

**Comment by arnaudperalta** [comment]
Its seems that this issue can be closed, it has been done on this commit : https://github.com/jesseduffield/lazygit/commit/188890fc49b8a8a2ccabf68307d1cfc7e2ef0a31
