### ISSUE TITLE
Releases / Binary Distribution

### ISSUE THREAD

**Issue by cookiengineer** [jesseduffield/lazygit#21]
Is there a way to distribute binaries in this project by using the releases/tags for it?

It would heavily improve the installation for people not familiar with go and people that don't have a working go setup and just want to build a simple package for a binary.

**Comment by jesseduffield** [comment]
Yeah that sounds like a good idea. I'm not very across how to set up a good release workflow. There's a PR (https://github.com/jesseduffield/lazygit/pull/20) up that does this for ubuntu but it's pending my question about how to update etc. Does anybody have some pointers on the best way to do this?

**Comment by dawidd6** [comment]
Maybe build binary on some kind of CI service like travis-ci and then upload it somewhere with link attached in README.

**Comment by cookiengineer** [comment]
@jesseduffield What I did for my projects is that on my buildbot I use `curl` to upload the binaries into the releases section automatically after they've been built and tested.

AFAIK [circle](https://circleci.com/blog/publishing-to-github-releases-via-circleci/) and [travis](https://docs.travis-ci.com/user/deployment/releases/) both have a github releases API that also allows you to push the binaries to github afterwards, but I don't know their limitations on that.

(My binaries were too big, as it was around 12GB of system images etc. so I had to use a VPS for that.)

**Comment by f-breidenstein** [comment]
Hey,

I started to use [GoReleaser](http://goreleaser.com) a few days ago for some of my Go projects. You have a pretty simple .goreleaser.yml in your repository and when you run `goreleaser` on a commit with a tag, it will automatically build binarys for macos/linux/windows and also 32/64bit depending on your configuration and because you gave him an API token for Github it will push them directly to the 'Releases' section.
You can take a look at my [testrepo](https://github.com/f-breidenstein/goreleaser-test) which contains configuration for GoReleaser and also TravisCI to automatically build new tags.

Felix

**Comment by Code0x58** [comment]
I've used Travis to build binaries before for releases on github, then you can just have download based instructions (or use those binaries in package managers):

[example PR on atombender/ktail](https://github.com/atombender/ktail/pull/2) with setup instructions.

**Comment by jesseduffield** [comment]
I ended up using travis ci and we've got releases / binaries working :) Please feel free to have a look at the .travis.yml and see if there's any improvements that could be made

**Comment by dawidd6** [comment]
Can we also build binaries for other architectures like arm and arm64?

**Comment by jesseduffield** [comment]
yep, getting onto that now

**Comment by jesseduffield** [comment]
we have LIFTOFF https://github.com/jesseduffield/lazygit/releases (note I've removed the version number from the end of the file because we now store that in the binary itself)

**Comment by jesseduffield** [comment]
closing

**Comment by Tallefer** [comment]
@jesseduffield What do you think about adding 32 bit builds to the bunch?

**Comment by jesseduffield** [comment]
@Tallefer I've chucked 32 bit builds in the latest release :) https://github.com/jesseduffield/lazygit/releases/tag/v0.1.66
