### ISSUE TITLE
Random crash when move cursor inside Files box

### ISSUE THREAD

**Issue by ray-x** [jesseduffield/lazygit#2100]
**Describe the bug**
When move cursor inside Files box, see random crash

**To Reproduce**

1. Go to 'Files' box
2. Click on a file
3. Scroll up and down

**Expected behavior**
no crash

**Crash log**
Crash log
2022/08/08 19:08:53 An error occurred! Please create an issue at: https://github.com/jesseduffield/lazygit/issues

syscall.Errno bad file descriptor
/home/ray/go/pkg/mod/github.com/jesseduffield/lazygit@v0.35.0/pkg/app/app.go:52 (0xa55fd6)
	Run: newErr := errors.Wrap(err, 0)
/home/ray/go/pkg/mod/github.com/jesseduffield/lazygit@v0.35.0/main.go:154 (0xa63bd0)
	main: app.Run(appConfig, common, types.NewStartArgs(filterPath, parsedGitArg))
/usr/lib/go/src/runtime/proc.go:250 (0x439cd2)
	main: fn()
/usr/lib/go/src/runtime/asm_amd64.s:1594 (0x4682e1)
	goexit: BYTE	$0x90	// NOP

**Version info:**
@v0.35.0

**Additional context**
OS: Linux (archlinux)
Shell: Fish
Terminal: Kitty

**lazygit --log**
Aug  8 19:08:53 |ERRO| syscall.Errno bad file descriptor
/home/ray/go/pkg/mod/github.com/jesseduffield/lazygit@v0.35.0/pkg/app/app.go:52 (0xa55fd6)
Run: newErr := errors.Wrap(err, 0)
/home/ray/go/pkg/mod/github.com/jesseduffield/lazygit@v0.35.0/main.go:154 (0xa63bd0)
main: app.Run(appConfig, common, types.NewStartArgs(filterPath, parsedGitArg))
/usr/lib/go/src/runtime/proc.go:250 (0x439cd2)
main: fn()
/usr/lib/go/src/runtime/asm_amd64.s:1594 (0x4682e1)
				goexit: BYTE$0x90// NOP

**Comment by mark2185** [comment]
Do you by any chance use a non-default pager, e.g. `delta`?

**Comment by ray-x** [comment]
my lazygit was configured to use `delta`.

**Comment by mark2185** [comment]
Pagers have some issues currently, could you please trying using the default pager?

**Comment by ray-x** [comment]
sure. I can use a default pager and check if the issue still existed.

**Comment by jesseduffield** [comment]
I actually think I know what causes this problem, and I'm pretty sure it's fixed on master. Could you try this out on the master branch @ray-x ?

**Comment by ray-x** [comment]
I had switched to master and enable debug by default. Will check if it is still reproduceable.

**Comment by ray-x** [comment]
I think it looks good so far on master.
The error was 1/10 when I use lazygit. But it did not reproduce so far, will close it for now.
