### ISSUE TITLE
Branch renaming does not auto-apply dashes when renaming a newly created branch

### ISSUE THREAD

**Issue by bastianpedersen** [jesseduffield/lazygit#2101]
**Describe the bug**
When creating a new branch with spaces in the name, lazygit automatically applies dashes for the whitespaces. When renaming a newly creating branch with whitespaces in it, lazygit says that the branch name is not supported.

**To Reproduce**
- Create a new branch with whitespaces in its name.
- Rename the newly created branch with whitespaces in its name.

**Expected behavior**
Lazygit adds dashes where whitespace is present.

**Screenshots**

**Version info:**
Newest lazygit version

**Comment by mark2185** [comment]
Would you be interested in taking a shot at this?

I take it we just need to replace `' '` with `'-'` [here](https://github.com/mark2185/lazygit/blob/ac6b33ebc30a60dff44cac7c1c343debc1383baa/pkg/commands/git_commands/branch.go#L145).

**Comment by bastianpedersen** [comment]
> 

Sure, here is a video of the problem:

https://user-images.githubusercontent.com/58905488/184503238-7d039c0a-6063-4208-92b4-62341b50b03e.mp4

**Comment by mark2185** [comment]
Oh, I meant "taking a shot" in the sense of "would you like to try and fix this"?

**Comment by bastianpedersen** [comment]
Oh sorry, my bad 😆 Yeah, I can give it a shot tomorrow 👍🏼

**Comment by bastianpedersen** [comment]
Sorry for the inactivity. Kinda forgot about this issue. @mark2185 Is this issue still relevant?

**Comment by mark2185** [comment]
Nobody fixed it in the meantime, as far as I'm aware :)

**Comment by mark2185** [comment]
Uhhh... I meant that it is still not fixed, so it should remain open :sweat_smile:

**Comment by mark2185** [comment]
Closed by #2990 .
