### ISSUE TITLE
Esc and Quit conflicting

### ISSUE THREAD

**Issue by paulhmurray** [jesseduffield/lazygit#2112]
**Describe the bug**
Loading LazyGit with NeoVim plugin there is conflict when using Esc and then trying to exit LazyGit with 'q' command for quit

**To Reproduce**

1. Load LazyGit
2. Press Esc
3. Then try and leave LazyGit by pressing 'q' for quit won't work
4. Only way to exit is to use Vim's ":q"

**Expected behavior**
That exiting the floating LazyGit screen will work regardless of pressing the 'esc' button

**Screenshots**
Not much need for a screenshot, as the floating LazyGit window just hangs until I select ":q" for vim exit

**Version info:**
LazyGit Version 0.34
Git version 2.34.1

**Comment by mark2185** [comment]
Wouldn't this be an issue for the plugin, then?

**Comment by paulhmurray** [comment]
Yes, that is correct. Sorry

**Comment by shasherazi** [comment]
hi @paulhmurray, did you find a solution to this?

**Comment by paulhmurray** [comment]
No @shasherazi i didn't figure a solution. I'm on AstroNvim now, rather than my previous NeoVim setup. Lazy Git works perfectly here, and when I re-create the steps it doesn't fault like before.

**Comment by shasherazi** [comment]
Did you find how AstroNvim does it tho @paulhmurray?

**Comment by paulhmurray** [comment]
I'm sorry, I didn't. I lost interest once it was resolved. Looking at the dotfiles, it all looks very standard for lazy git install mate. Perhaps it was more of a localised issue.
