### ISSUE TITLE
How can I pull a different remote branch into my local branch?

### ISSUE THREAD

**Issue by Calieston** [jesseduffield/lazygit#2119]
**Topic**
I'm working locally on branch _feature/project-123_ and want to prepare a PR. Before doing that, I pull remote branch main/master into my branch locally by doing a git pull origin main/master.

In lazygit I only find a "pull" option when checking menu with "x".
Is there another way which I missed? 
Thanks.

**Comment by Calieston** [comment]
Alright, sounds good. Thanks for your answer.

**Comment by mark2185** [comment]
Which one? Rebase or (re)setting upstream?

**Comment by Calieston** [comment]
The (re)setting upstream. Would still prefer a second pull option where you can define a default branch like "main" or you can enter another branch to make it easier.
Thanks.

**Comment by mark2185** [comment]
We have options both for merging and for rebasing, you could use them directly, so you don't depend on your `pull`'s default configuration.
