### ISSUE TITLE
Feature request: Rebasing

### ISSUE THREAD

**Issue by mbouchenoire** [jesseduffield/lazygit#212]
I can easily see lazygit becoming my next go-to git client, but there is just one missing feature that prevents me to do so right now : I cannot rebase directly within lazygit.

I'm not an UX expert so I'd let the right people design the integration within lazygit. It will probably be very similar to the merge feature.

Thanks for your time.

**Comment by jesseduffield** [comment]
Hi @mbouchenoire, what would your general use-case be? Can you give some examples of common command-line commands you would use in this case. There's a lot of complexity that comes with rebasing so I'm interested to know if your particular use case could be satisfied easily.

**Comment by mbouchenoire** [comment]
The basic use-case would be:
1. I start a `feature` branch from a `develop` branch
2. the `develop` branch evolves while I develop on the `feature` branch
3. I want to **rebase** my branch (`feature`) on `develop` before making a pull request, that would be a `git rebase develop feature`

**Comment by internetimagery** [comment]
I came across this as well today (after having also discovered this awesome tool). Same thing. Local branch needing to rebase against a moving target before being merged. Hunted through all menus expecting to see the option. Glad to hear it may be considered! :+1:

**Comment by HoffmannP** [comment]
Yeah, `rebase`ing would be great, I got used to it developing in a bigger context with more parties involved and it's unavoidable now.

**Comment by jesseduffield** [comment]
doing a simple feature where you select a branch and hit 'b' or something, then have git run `git rebase {{branchName}} {{currentBranch}}` would be super easy. If there are any takers for a PR that does this, I can give pointers. Otherwise I might be able to do it this weekend

**Comment by glvr182** [comment]
Will work on it during the weekend @jesseduffield

**Comment by glvr182** [comment]
See #331

**Comment by glvr182** [comment]
@mbouchenoire @jesseduffield @internetimagery @HoffmannP Theres an mvp up right now at #331. So if you guys would like to test it, please do.

**Comment by jesseduffield** [comment]
This is now implemented in 0.7.2 :) Let me know what you think!

**Comment by glvr182** [comment]
I suggest closing this
