### ISSUE TITLE
Branch name cut off when pushing upstream

### ISSUE THREAD

**Issue by rafaelderolez** [jesseduffield/lazygit#2122]
**Describe the bug**
When pushing a branch upstream, an input field + suggestions box show up. However, the input field, already containing the current branch name, is 'scrolled' all the way to the end. This can be annoying if the input field has enough room to display the complete branch name.

**To Reproduce**

1. Push branch upstream

<img width="913" alt="image" src="https://user-images.githubusercontent.com/6158959/185143102-e2c07fd2-14ac-4de2-a008-c7f5b03ce94c.png">

**Expected behavior**
This is how I'd expect it to look. (after scrolling all the way to the left)
<img width="908" alt="image" src="https://user-images.githubusercontent.com/6158959/185143694-8bc393b2-c933-4c01-bfaa-5844e4635a99.png">

**Version info:**
_Run `lazygit --version` and paste the result here_
```
commit=367b0d331836c90c015bf0c45f88612f3d94d08a, build date=2022-07-20T09:27:56Z, build source=binaryRelease, version=0.35, os=darwin, arch=arm64
```

_Run `git --version` and paste the result here_
```
git version 2.37.2
```

**Comment by jesseduffield** [comment]
I saw this in an integration test the other day. Very annoying. But a git bisect should get us to the cause pretty quick. I'll chuck a good-first-issue label on this and anybody who wants to pick it up and doesn't know what git bisect is, reach out!
