### ISSUE TITLE
Open in browser doesn't work for some gitlab repos

### ISSUE THREAD

**Issue by jtraub** [jesseduffield/lazygit#2131]
**Describe the bug**
Open in browser doesn't work for some gitlab repos

**To Reproduce**
1. Clone [this repo](https://gitlab.com/gitlab-com/alliances/aws/public-tracker) with https: `git clone https://gitlab.com/gitlab-com/alliances/aws/public-tracker.git` 
2. Launch lazygit
3. Pick any commit and press `o` to open it in the browser
4. Observe 404 page

**Expected behavior**
I expect to see commit page, actually, because it exists and available to all users

**Comment by jtraub** [comment]
Oh, I see now why this happens

Gitlab service definition uses default regexp
https://github.com/jesseduffield/lazygit/blob/master/pkg/commands/hosting_service/definitions.go#L5

which assumes that URL structure would be `gitlab.com/owner/repo.git`

However, this is not the case for gitlab. A repo in gitlab belong to a group. Group itself can be member of another group (in this case they call such child group a subgroup) up to 20 levels.

Source: https://docs.gitlab.com/ee/user/group/subgroups/index.html

**Comment by mark2185** [comment]
> Should I submit a PR?

That would be great, thanks!
