### ISSUE TITLE
3-way merge conflict editor

### ISSUE THREAD

**Issue by mrjones2014** [jesseduffield/lazygit#2133]
**Is your feature request related to a problem? Please describe.**

Merge conflicts suck. Resolving them can get really confusing. Sometimes you're not sure what you're looking at when the changes are stacked on top of each other like that, and sometimes you want some parts of both changes.

**Describe the solution you'd like**

A 3-way merge conflict editor UI. Basically, it shows the local file on the left, the remote file on the right, and the merged result preview in the middle (which is also manually editable so you can make minor tweaks to the merged result if needed). Here's an example of what the one built into JetBrains products looks like:

![3 way merge editor from JetBrains](https://user-images.githubusercontent.com/8648891/186430364-b89a4670-5d57-44ce-80d0-3702dfb37342.png)

Note that you can manually edit the file in the middle view. Not sure if this is possible/feasible in lazygit though.

**Describe alternatives you've considered**

- Using a GUI merge conflict resolution tool 🙁 
- Using the simple merge conflict resolution tool already built into lazygit

**Comment by mark2185** [comment]
> Using a GUI merge conflict resolution tool :slightly_frowning_face:

Well, until we support such a feature _within_ `lazygit` itself, at least launching a merge tool isn't far (`M` opens an external merge tool)

Would you be interested in adding support for 3 way merging?

**Comment by mrjones2014** [comment]
>Would you be interested in adding support for 3 way merging?

I might need some help but I can give it a shot!

**Comment by mark2185** [comment]
Well I'm guessing it would require planning and a discussion of what it should look like for which we need Jesse.

But if I were to guess of what we should discuss beforehand:
- similar to the partial staging panel, but having 3 splits instead of 2 ( maybe the third one could be below ) 
- all should be editable, which we don't currently have anywhere except for the commit message textbox
- we'd need to work how to switch between them
- mappings for accepting changes from one, the other, or both of the panels

**Comment by hsheikhali1** [comment]
> Well I'm guessing it would require planning and a discussion of what it should look like for which we need Jesse.
> 
> But if I were to guess of what we should discuss beforehand:
> 
> * similar to the partial staging panel, but having 3 splits instead of 2 ( maybe the third one could be below )
> * all should be editable, which we don't currently have (at least not of that specific use, e.g. existing text with multiple lines filling an editable buffer)
> * we'd need to work how to switch between them
> * mappings for accepting changes from one, the other, or both of the panels

I got a few questions since I've been using LazyGit for months and the one thing I dislike is how it handles merge conflicts.

1. What is the partial staging panel ? 
2. You mentioned mappings for accepting changes from one or the other or both panels - i feel like functionality is already there just needs to be implemented to support this behaviour ?
3. Would lazygit ever support the option to show a totally different view strictly for merge conflicts?

**Comment by mark2185** [comment]
1. You can partially stage files by pressing `Enter` on a file and staging/unstaging lines with `Scape`.
2. Well since this is a specific scenario, where one would have 3 panels, so it _is_ mostly familiar, but not completely.
3. Jesse would know

**Comment by mark2185** [comment]
Do note that if we would implement separate editable buffers, 0.01s after its merge to `master`, there would be a request for it to support {vim,emacs,kakoune,somethingelse}-bindings. I'm not sure we want to open that particular door.

**Comment by mrjones2014** [comment]
Is there maybe a way we could just embed a TUI editor within the TUI? Idk if that’s possible, haven’t worked much with TUI, but I know Neovim at least is designed to be embeddable.

**Comment by mark2185** [comment]
Is there a point in doing that when the user could just run the TUI editor externally?

**Comment by mrjones2014** [comment]
Hm, I suppose not actually.

**Comment by mark2185** [comment]
So, what would we gain by adding a 3-way merge conflict editor that has the most basic editing capabilities, namely moving around using arrow keys and typing and deleting?

On the other hand, one could just use the desired merge tool one is used to, e.g. `emerge`, `vimdiff`, `kdiff3`, `meld` etc.

**Comment by mrjones2014** [comment]
Good point. After a little more tinkering I've found that installing the `vim-fugitive` Vim plugin, then setting my mergetool like so:

```gitconfig
[merge]
  tool = nvim
[mergetool "nvim"]
  cmd = nvim -f -c \"Gdiffsplit!\" \"$MERGED\"
[mergetool]
  prompt = false
```

works well enough for me. Being able to launch this directly from `lazygit` too is nice.

I'm good to close this issue. I'll use vim with the `vim-fugitive` 3 way merge conflict editor and launch it from `lazygit` when needed.

**Comment by mark2185** [comment]
If you really so desire, I guess it's possible to use `IntelliJ` as a mergetool as well (that's what you listed as an example in the original issue)

[Someone tried it](https://gist.github.com/ffittschen/6d9be1720f30eb8dc0142cc0ed91c7d9).

**Comment by mark2185** [comment]
I don't think there's a way to do that other than opening it up in an external `mergetool`, which you can use VScode for.

**Comment by kuzyo** [comment]
@mark2185 Thank you.

**Comment by Ryooooooga** [comment]
@kuzyo You can open a VSCode from the Conflict panel using `editCommand`(`e`) or `openCommand`(`o`).

```yaml
os:
  openCommand: 'code --goto -- {{filename}}:{{line}}'
  editCommand: 'code'
```

**Comment by nullromo** [comment]
> setting my mergetool like so

@mrjones2014 This looks like TOML syntax. Can you explain how you set this up? Is it a git thing or a lazygit thing?

**Comment by mrjones2014** [comment]
it's TOML, it goes in your git config.

However, I've since switched to [diffview.nvim](https://github.com/sindrets/diffview.nvim) instead of `vim-fugitive`. The config for it is similar, just with a different command:

```toml
[merge]
  tool = nvim
[mergetool "nvim"]
  cmd = nvim -c "DiffviewOpen"
[mergetool]
  prompt = false
```

**Comment by nullromo** [comment]
Ok, wow, today I learned that `~/.gitconfig` is a thing...

Previously I only knew about `git config --global <args>` on the command line. Nice to know there's a far easier method of managing it!

And yeah, I was just looking into Diffview.nvim and it seems great.

Thanks!

**Comment by 7flash** [comment]
Usually I just need, either accepts --theirs changes or mine; does lazygit have a hotkey for it?

**Comment by rs545837** [comment]
If you want to reduce the number of merge conflicts you need to resolve in the first place, check out [weave](https://github.com/ataraxy-labs/weave). It's a Git merge driver that parses code with tree-sitter and merges at the function/class level instead of lines. Independent changes to different functions in the same file get merged cleanly instead of producing false conflicts. 31/31 clean merges vs git's 15/31 on concurrent edits.

**Comment by chojs23** [comment]
I made 3-way tui git merge conflict resolver [ec](https://github.com/chojs23/ec), it works so smoothly with lazygit.

**Comment by mloskot** [comment]
> I made 3-way tui git merge conflict resolver [ec](https://github.com/chojs23/ec), it works so smoothly with lazygit.

@chojs23 Could you share some details how did you configured and integrated the `ec` with Lazygit?
Did you just do what's in the [Git mergetool configuration](https://github.com/chojs23/ec/blob/7f2b723183792cdaf7de837b7ad0e7cf5f6caf2b/README.md?plain=1#L101) section or some more customisations?

**Comment by chojs23** [comment]
@mloskot You don't need to configure lazygit. 

If you install ec, just use shell command in lazygit (press `:` and run `ec`) or set git mergetool as ec and resolve conflict with external mergetool in lazygit(`M-m`)

**Comment by mloskot** [comment]
@chojs23 It is simple as that indeed! Thanks!
<a href="https://github.com/chojs23/ec"><img width="184" height="48" alt="Image" src="https://github.com/user-attachments/assets/19a93c04-8604-45c3-bda0-5cbd20459e6a" /></a>
