### ISSUE TITLE
Broken documentation links

### ISSUE THREAD

**Issue by BossElijah** [jesseduffield/lazygit#2135]
**Describe the bug**
The config and keybindings documentation links lead to Github's 404 pages. See screenshot.

**To Reproduce**

1. Open lazygit
2. Go to the status section
3. Click the two Github documentation links
4. See that they don't work

**Expected behavior**
I expect to see documentation, not broken links.

**Screenshots**
![lazygit](https://user-images.githubusercontent.com/54446109/186610544-d21d0b33-54e8-4b49-a2de-3cb069336631.png)

**Version info:**
_Run `lazygit --version` and paste the result here:_ `commit=, build date=, build source=homebrew, version=0.34, os=darwin, arch=amd64`
_Run `git --version` and paste the result here:_ `git version 2.32.1 (Apple Git-133)`

**Additional context**
I am on MacOS Intel with Monterey if that does anything.

**Comment by mark2185** [comment]
Both links are perfectly valid, though.

https://github.com/jesseduffield/lazygit/blob/master/docs/keybindings
https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md

What link does your browser try to open?

**Comment by BossElijah** [comment]
After digging a bit more into this, I suddenly notice that because of the line breaks, it adds a pipe where the line break occured. So these are the links it is trying to open:

- https://github.com/jesseduffield/lazygit/blob/master/docs/keybind%E2%94%82ings
- https://github.com/jesseduffield/lazygit/blob/master/docs/Conf%E2%94%82ig.md

**Comment by mark2185** [comment]
That seems like a problem of the terminal emulator itself (since clicking the link is the functionality of it), the `|` is the right border of that pane.

**Comment by BossElijah** [comment]
So the problem is that when the window isn't wide enough for the links to be displayed in one line, it adds a pipe ('|').
And you think that my terminal is the problem? I'm on iTerm.

If I understand you correctly, you're saying that this has nothing to do with lazygit?

**Comment by BossElijah** [comment]
I will close this issue, if it is only a problem with my terminal.

And btw, thank you for the fast support.

**Comment by mark2185** [comment]
> So the problem is that when the window isn't wide enough for the links to be displayed in one line, it adds a pipe ('|').
And you think that my terminal is the problem? I'm on iTerm.

I'm guessing the terminal thinks that `|` is a part of the link. By checking the same functionality on `kitty`, look at what _it_ thinks is the whole URL (it includes the pipes, when I click it):
![image](https://user-images.githubusercontent.com/8365241/186614093-73c8ab5d-c751-48b0-b74a-ee0db15d2c29.png)

> If I understand you correctly, you're saying that this has nothing to do with lazygit?

Correct. `lazygit` only displays the text, the `click and I'll open it up in a browser` part is the terminal emulator's job.

**Comment by BossElijah** [comment]
Okay, thank you very much!
