### ISSUE TITLE
Lazygit will not run inside tmux

### ISSUE THREAD

**Issue by pixels-bytes** [jesseduffield/lazygit#2136]
**Describe the bug**
Lazygit runs perfectly unless I am in a tmux session and then it will not run at all

**To Reproduce**

1. Open tmux
2. Navigate to a folder that has a git repository
3. Open lazygit

**Expected behavior**
I expected lazygit to function normally as it does outside a tmux session

**Screenshots**
Error given:

```
2022/08/25 20:56:55 An error occurred! Please create an issue at: https://github.com/jesseduffield/lazygit/issues

*exec.ExitError exit status 1
/private/tmp/lazygit-20220721-4073-sbhoke/lazygit-0.35/pkg/app/app.go:52 (0x163cb76)
/private/tmp/lazygit-20220721-4073-sbhoke/lazygit-0.35/main.go:154 (0x164a5f0)
/usr/local/Cellar/go/1.18.4/libexec/src/runtime/proc.go:250 (0x1036db2)
/usr/local/Cellar/go/1.18.4/libexec/src/runtime/asm_amd64.s:1571 (0x1064c21)
```

**Version info:**
_Run `lazygit --version` and paste the result here_
commit=, build date=, build source=homebrew, version=0.35, os=darwin, arch=amd64

_Run `git --version` and paste the result here_
commit=, build date=, build source=homebrew, version=0.35, os=darwin, arch=amd64

Updated to the latest brew version

The logs after running `lazygit —debug` don’t shed any more light onto the problem, unfortunately:

```
Aug 25 21:05:05 |INFO| language: en 
Aug 25 21:05:05 |DEBU| RunCommand command="git --version"
Aug 25 21:05:05 |DEBU| RunCommand command="git rev-parse --git-dir"
Aug 25 21:05:05 |ERRO| *exec.ExitError exit status 1
/private/tmp/lazygit-20220721-4073-sbhoke/lazygit-0.35/pkg/app/app.go:52 (0x163cb76)
/private/tmp/lazygit-20220721-4073-sbhoke/lazygit-0.35/main.go:154 (0x164a5f0)
/usr/local/Cellar/go/1.18.4/libexec/src/runtime/proc.go:250 (0x1036db2)
/usr/local/Cellar/go/1.18.4/libexec/src/runtime/asm_amd64.s:1571 (0x1064c21)
```

**Comment by mark2185** [comment]
Could you try building latest `master`?

And if that doesn't work, you wouldn't happen to be willing to try running it under a debugger, would you? :)

**Comment by pixels-bytes** [comment]
Hmmm. Built from master but lazygit was still using the homebrew version. Uninstalled homebrew version, rebuilt from src, but lazygit command not recognised. Where does it get installed?

**Comment by mark2185** [comment]
In `GOPATH`, wherever that points to, by default it's `~/go`, I guess.

You can just run `go run main.go` and it'll run.

**Comment by pixels-bytes** [comment]
`go run main.go` runs lazygit finel but inside tmux it is still crashing. 

logs after running `go run main.go —debug`
```
Aug 25 22:00:11 |INFO| language: en
Aug 25 22:00:11 |DEBU| RunCommand command="git --version"
Aug 25 22:00:11 |DEBU| RunCommand command="git rev-parse --git-dir"
Aug 25 22:00:11 |DEBU| RunCommand command="git rev-parse --is-bare-repository"
Aug 25 22:00:11 |ERRO| *exec.ExitError exit status 1
/Users/abu/src/lazygit/pkg/app/app.go:57 (0x1678f3c)
Run: newErr := errors.Wrap(err, 0)
/Users/abu/src/lazygit/pkg/app/entry_point.go:139 (0x167af6b)
Start: Run(appConfig, common, appTypes.NewStartArgs(cliArgs.FilterPath, parsedGitArg, integrationTest))
/Users/abu/src/lazygit/main.go:23 (0x167cb3e)
main: app.Start(ldFlagsBuildInfo, nil)
/usr/local/Cellar/go/1.19/libexec/src/runtime/proc.go:250 (0x1038e92)
main: fn()
/usr/local/Cellar/go/1.19/libexec/src/runtime/asm_amd64.s:1594 (0x1067bc1)
                                goexit: BYTE$0x90// NOP
```

**Comment by pixels-bytes** [comment]
Running `lldb -- ~/go/bin/lazygit` gives be the output:

```
(lldb) target create “/Users/abu/go/bin/lazygit
Current executable set to ‘Users/abu/go/bin/lazygit’ (x86_64).
terminals database is inaccessible
```

**Comment by mark2185** [comment]
What about `delve`? It's intended for `go` debugging - [click](https://github.com/go-delve/delve).

**Comment by pixels-bytes** [comment]
Thanks for the headsup @mark2185. I’ve never used go before.

` ~/go/bin/dlv debug main.go` followed by `continue` gives the exact same `ExitError exit status 1` output as above

**Comment by mark2185** [comment]
> Thanks for the headsup @mark2185. I’ve never used go before.

Thanks for being willing to do that since I can't reproduce it.

> ` ~/go/bin/dlv debug main.go` followed by `continue` gives the exact same `ExitError exit status 1` output as above

Fun! There should be some sort of `backtrace` or something to dump the callstack.

Does it crash even if you run it in a non-git repo? 
Have you tried clearing your config and cache?
It works A-okay outside of tmux?

**Comment by pixels-bytes** [comment]
> Does it crash even if you run it in a non-git repo?
Yes. It asks if I want to create a repo, and either option leads to the same crash

> It works A-okay outside of tmux?
Impeccably 😂

> Have you tried clearing your config and cache?
I’m not sure how to. These are my first (somewhat disastrous) fumblings with tmux and now go

I will have a fiddle around and see if I can find a way to dump the callstack

Thanks for your help.

**Comment by mark2185** [comment]
> I’m not sure how to. These are my first fumblings with tmux and now go

I was referring to `lazygit`'s `config.yml` and `cache.yml` - [default user config path](https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md#user-config).

> (somewhat disastrous) 

That means it'll probably go upwards :)

Btw what version of `tmux` is it?

**Comment by pixels-bytes** [comment]
> I was referring to lazygit's config.yml and cache.yml - [default user config path](https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md#user-config).

Ah right… they’re deleted

> Btw what version of tmux is it?

tmux 3.3a

**Comment by jtraub** [comment]
@pixels-bytes What shell and terminal emulator do you use? Do you use programs that modify shell prompt like `starship`?

**Comment by Ryooooooga** [comment]
https://github.com/pixels-bytes/dotfiles/blob/6acb5803b6f3d4431019075cd51d800f6eea9a15/tmux/tmux.conf#L21

your `default-terminal` looks weird. try to set `xterm-256color`.

**Comment by pixels-bytes** [comment]
Thanks @Ryooooooga @jtraub. Just reporting back in case anyone else hits the same roadblock.

The `terminals database is inaccessible` output was the clue: It’s a TERM problem not a lazygit problem.
In tmux if I change the TERM temporarily `set -lx TERM screen-256color` then lazygit runs as it should.
Guess I better dig through anywhere that TERM is set.

**Comment by pixels-bytes** [comment]
Thanks for all your help guys
