### ISSUE TITLE
Problem finding different panels

### ISSUE THREAD

**Issue by amir-teymuri** [jesseduffield/lazygit#2139]
I just started looking at lazygit and am already starting to love it!
From reading the documentations under https://github.com/jesseduffield/lazygit/blob/master/docs/keybindings/Keybindings_en.md I have the problem of switching to the panels not shown on the main page, for instance Remote Branches, Remotes etc.

Since there is the option `1-5: jump to panel` at the bottom of the main page, I'm not sure how I could switch to those hidden panels, and I think it would be very helpful to put this information in the docs too.

**Comment by mark2185** [comment]
By pressing `x` at any point, a popup help menu will appear.

In it, you can find the options for `]` and `[`, `next` and `previous` tab, respectively.
