### ISSUE TITLE
showBottomLine config option does nothing

### ISSUE THREAD

**Issue by nullishamy** [jesseduffield/lazygit#2149]
**Describe the bug**
The `showBottomLine` does not change the behaviour of lazygit. When set to `false`, the line persists.

**To Reproduce**
1. Set showBottomLine to false in the config file
2. Launch lazygit
3. Observe the bottom line

**Expected behavior**
The bottom line should disappear

**Screenshots**
N/A

**Version info:**
commit=, build date=, build source=nix, version=0.34, os=linux, arch=amd64
git version 2.36.0

**Additional context**
N/A

**Comment by mark2185** [comment]
Please fill out the `bug report template` in its entirety, namely this:

```
**Note:** please try updating to the latest version or [manually building](https://github.com/jesseduffield/lazygit/#manual) the latest `master` to see if the issue still occurs.
```

That specific feature was added on `Apr 18th`, whilst the `v0.34` was tagged on `Mar 17th`, so `v0.35` is the first one that should have it.

**Comment by nullishamy** [comment]
That explains it, thanks.
