### ISSUE TITLE
possibility to paste a string previously copied with <c-o>

### ISSUE THREAD

**Issue by TheHappyAkita** [jesseduffield/lazygit#2158]
**Is your feature request related to a problem? Please describe.**
I am working on projects that are highly modularized and each module has its own git entry.
Sometimes for fix/feature I  need to have the same branch name across such modules and therefore I can copy the branch name, that I created for one module, with \<c-o\>.
It would be nice to be able to paste the copied name for the next module where I create a new branch.

**Describe the solution you'd like**
Maybe \<s-o\> for pasting the previously copied string

**Additional context**
I am using lazygit almost from inside nvim.

**Comment by mark2185** [comment]
Have you tried using `ctrl+v` to paste? Works as one would expect.

**Comment by hosseinadib-hub** [comment]
I run latest version of Lazygit on Windows OS.
Ctrl + Shift + v and Ctrl + v doesn't work for me

**Comment by mark2185** [comment]
> I run latest version of Lazygit on Windows OS.
> Ctrl + Shift + v and Ctrl + v doesn't work for me

On windows it's likely `Shift+Insert`.

**Comment by hosseinadib-hub** [comment]
It doesn't seem to work. I'm trying to paste text into the New Branch name dialog, but I can't find a way to do it. I've tried using Ctrl + Shift + V, Ctrl + V, and Shift + Insert.
 LazyGit is incredibly handy and useful, but without the ability to paste, I can't effectively use it!
