### ISSUE TITLE
Feature Request: A way to disable a keybinding

### ISSUE THREAD

**Issue by claudiofreitas** [jesseduffield/lazygit#2159]
### Discussed in https://github.com/jesseduffield/lazygit/discussions/2150

<div type='discussions-op-text'>

<sup>Originally posted by **claudiofreitas** September  3, 2022</sup>
Is there any way to disable a keybinding?
I wanted to disable most of them and enable them as I discover my own needs,
also to avoid pressing some key by accident and have a blank slate not having to worry about key clashes.

I tried the snippet below to see if empty string would do the trick, but the app crashes.

```yaml
keybinding:
  universal:
    quit: ''
```</div>

**Comment by mark2185** [comment]
Oh, I already opened an issue 😅 

Look at #2152 .

**Comment by fildenisov** [comment]
Hi everyone, I made a small feature you requested. Feel free to comment if I made something wrong and I ll fix it =)
https://github.com/jesseduffield/lazygit/pull/2161
Usage:
`keybinding:
  universal:
    quit: '<nop>'`

**Comment by claudiofreitas** [comment]
> Oh, I already opened an issue 😅
> 
> Look at #2152 .

Oh thank you!!



> Hi everyone, I made a small feature you requested. Feel free to comment if I made something wrong and I ll fix it =) #2161 Usage:
> 
> ```
> keybinding:
>   universal:
>     quit: '<nop>'
> ```

Oh so quick, nice! Thank you!
