### ISSUE TITLE
git pull --rebase option?

### ISSUE THREAD

**Issue by ZacharyRizer** [jesseduffield/lazygit#2175]
**Topic**
Default keybinding for `git pull --rebase` 

**Your thoughts**
Sorry if this is obvious. After searching the docs and playing around, I don't see a built in option for a `git pull --rebase` option, or a way to set `git pull` to behave this way. I know I could make a custom command, but I wanted to make sure it isn't hiding somewhere already before I do.

**Comment by mark2185** [comment]
You could add this to your `.gitconfig`:
```
[pull]
	rebase = true
```

**Comment by ZacharyRizer** [comment]
> 

Totally, and I was thinking of doing this. But I don't really want every pull to be a rebase. I was hoping I could pick one or the other on the fly through Lazygit.

**Comment by mark2185** [comment]
Just out of curiosity, when would you not want a rebase?

I usually use `f` instead of pulling, which stands for `fast-forward this branch from its upstream`.

As for `git pull --rebase`, I guess we could add a functionality to `rebase @{upstream}` for branches, that has been something I had needed a handful of times, _and_ it would solve this issue by sheer coincidence.

**Comment by ZacharyRizer** [comment]
I had looked into the fast-forward option as well. To be honest I wasn't really sure of the difference between that and git pull --rebase in the use cases I have been investigating. I usually just did pulls, but on a recent team they prefer to keep the main branch free of the merge commit that would come along with pull origin main into local main.

**Comment by mark2185** [comment]
>  but on a recent team they prefer to keep the main branch free of the merge commit

Sounds to me like you'll _always_ be fast forwarding.

> branch free of the merge commit that would come along with pull origin main into local main

That's only if you happen to commit on `master` locally and then there are conflicts. If you do not want such `merge` commits, you should `git pull --rebase`.

What I'm trying to say, I'm not sure you'll ever need a _non-rebase_ pull. :sweat_smile:

**Comment by ZacharyRizer** [comment]
You are probably correct on that one! But if I'm understanding correctly, fast-forwarding is technically a merge process, not a rebase process right? Sorry for the ignorance.

**Comment by mark2185** [comment]
A _merge process_ in this sense occurs only if there are conflicting sources and they are _merged_.

As for what `man git pull` says:
```
Incorporates changes from a remote repository into the current branch. If the current branch is
behind the remote, then by default it will fast-forward the current branch to match the remote.
If the current branch and the remote have diverged, the user needs to specify how to reconcile
the divergent branches with --rebase or --no-rebase (or the corresponding configuration option
in pull.rebase).

More precisely, git pull runs git fetch with the given parameters and then depending on
configuration options or command line flags, will call either git rebase or git merge to
reconcile diverging branches.
```

In other words, if there are only _new_ commits on the remote, it will be a `fast-forward`.
If there's a divergence, it'll either be a `git merge` (resulting in a merge commit) or `git rebase` (local history will be updated so that your commits are ahead of the remote).

> Sorry for the ignorance.

Nonsense, don't hesitate to ask if anything is unclear. :)

**Comment by ZacharyRizer** [comment]
Awesome, honestly it sounds like fast-forward is going to accomplish what I need. But if a keybinding or optional one for git pull --rebase gets added to Lazygit, that couldn't hurt either. Thanks again!

**Comment by noahfraiture** [comment]
Hello, I would like to talk about this issue. 
If I made a PR that add the option to `git pull --rebase`, will it be accepted ? I disagree with what is said in this issue https://github.com/jesseduffield/lazygit/issues/3033, `git pull --rebase` respect the config but ignore it for that particular command

**Comment by stefanhaller** [comment]
> I disagree with what is said in this issue #3033, `git pull --rebase` respect the config but ignore it for that particular command

I don't understand, can you elaborate please? What's wrong with `git config --global pull.rebase true`?

**Comment by stefanhaller** [comment]
This seems like an uncommon enough thing to me that I don't think we need to support it in lazygit as a separate command. You can easily create a custom command for this.
