### ISSUE TITLE
Misrendered highlighting with diff-so-fancy 

### ISSUE THREAD

**Issue by fredcallaway** [jesseduffield/lazygit#2176]
When using diff-so-fancy as the pager, lazygit incorrectly renders the highlighted change in a line. Specifically, it highlights everything after the change in a line instead of just the section that was changed. See comparison of lg and diff-so-fancy below:

<img width="940" alt="image" src="https://user-images.githubusercontent.com/7883156/189978111-5f449d41-8b4b-42f5-888c-625076cadb95.png">

My best guess is that the end-highlight marker is getting ignored.

_Originally posted by @fredcallaway in https://github.com/jesseduffield/lazygit/issues/190#issuecomment-1245779998_

**Comment by jesseduffield** [comment]
Looks like we have an ANSI escape code that we're not properly honouring in vendor/github.com/jesseduffield/gocui/escape.go

**Comment by fredcallaway** [comment]
I unfortunately don't have the go chops to make a pull request myself. But I can tell you that the relevant escape code is 27, which means "not reverse". For example, here is the output of `git diff | diff-so-fancy | less` (after switching back to "second" back to "first".

```
ESC[1;31mthis is the ESC[7msecondESC[27m thing hereESC[0m
ESC[1;32mthis is the ESC[7mfirstESC[27m thing hereESC[0m
```

**Comment by scottchiefbaker** [comment]
diff-so-fancy maintainer here... Happy to see it being used in the wild.
