### ISSUE TITLE
Empty config.yml

### ISSUE THREAD

**Issue by dawidd6** [jesseduffield/lazygit#218]
**Describe the bug**
Lazygit is creating empty `config.yml`.

**To Reproduce**
1. Install lazygit in clear environment or delete `config.yml` manually.
2. Start lazygit
3. See that created config.yml is empty

**Expected behavior**
`config.yml` created with defaults.

**Desktop:**
 - OS: ubuntu 16.04
 - 93ab892 master

**Comment by jesseduffield** [comment]
I actually intentionally made it so that the defaults aren't saved in config.yml, so that if down the line we want to change the defaults, we can do so without blowing away user's existing configs. Under the current setup, the only things that will be in the user's config is values they explicitly set. Having said that if that's a non-standard approach to configs I'm happy to change it

**Comment by dawidd6** [comment]
I think we should create config with defaults when there is no config already exsiting. It will not blow away user's config if it's already in place.

Here's my proposition:
https://github.com/dawidd6/lazygit/commit/cc008656cea64eae1c5de06cf9ea3f63eb27af5f

It's not overwritten, one can see that i've changed `white` to `magenta` and it is still there after lazygit restart.
![zrzut ekranu z 2018-08-26 10-44-02](https://user-images.githubusercontent.com/9713907/44626455-f6d2f900-a91c-11e8-903d-7884c93040fa.png)

**Comment by dawidd6** [comment]
Well, your points are valid and i agree with you. I would add a flag to display to stdout current default config, so users can easily compare what is new in default config and eventually add new entries to their config or change them accordingly to their will.

Easy to implement and will save some time, i.e. users will not have to visit `Config.md` to see what changed. Just run `lazygit -config` and see what's up.

**Comment by dawidd6** [comment]
https://github.com/dawidd6/lazygit/commit/b7f6bcb3caa45ecb516670704513110a7d2f6a74

**Comment by remyabel** [comment]
That's a good idea, but keep in mind that if you distribute an empty config file, users will not be able to know when config options are added/changed. In RPM-based distros, this is handled with `rpmsave` (backup) and `rpmnew`. They can do a diff to see what's different. Of course, davidd6's idea is very good as well. Another idea would be to add a config option that shows what config values lazygit is currently using.

**Comment by jesseduffield** [comment]
I think the -config option is a good solution for now. I think at v1.0.0 we can switch to saving the default config when the file doesn't exist, but for now we'll play it safe and leave it blank. @dawidd6 can you raise a PR with that commit?
