### ISSUE TITLE
Interactive rebase shows faulty `<-- YOU ARE HERE ---`

### ISSUE THREAD

**Issue by mark2185** [jesseduffield/lazygit#2188]
**Describe the bug**
I think that after continuing a rebase and stumbling upon conflicts, the `<-- YOU ARE HERE ---` points to the commit _before_ the one conflicted (which is fine), but we're not _really_ there, are we?

We're in limbo where we need to resolve the conflicts and decide what to do next, so the `<-- YOU ARE HERE ---` is kinda misleading.

Also, after resolving conflicts, and not continuing, trying to commit (basically edit whatever previously was at this point in the history) using the popup prompt doesn't prefill the box with the original message, whereas invoking an external editor does.

This is more of a bookkeeping bug report than anything else.

**Comment by jesseduffield** [comment]
I think that's actually okay: so long as the YOU ARE HERE commit is the HEAD commit, then it's not lying

**Comment by mark2185** [comment]
Well it isn't, but I thought it had dropped the commit I was currently resolving conflicts for.
