### ISSUE TITLE
feature: push specify remote

### ISSUE THREAD

**Issue by wandiao** [jesseduffield/lazygit#219]
when I want to push upstream, but it only push default origin

**Comment by lukaszgard** [comment]
Hi @wandiao, here is my feature request for supporting pushing changes to references - https://github.com/jesseduffield/lazygit/issues/138

**Comment by jesseduffield** [comment]
I think it's time to finally do this. I'm thinking that on your first push we'll get you to specify the branch name and it will default to `origin/your-branch-name`

**Comment by jesseduffield** [comment]
I've now got a prompt coming up asking what upstream you want to set when you first push a branch: https://github.com/jesseduffield/lazygit/pull/532

Lemme know if there's anything you want tweaked about that solution  :)

**Comment by dvdbng** [comment]
Is there a way to get the previous behavior? I have `git config --global push.default current` in my .gitconfig, but lazygit asks for every new branch regardless

**Comment by jesseduffield** [comment]
@dvdbng could you open a new issue for that? I think it's a worthwhile feature to have (though would require some more work to be compatible with the new code)

**Comment by dvdbng** [comment]
@jesseduffield Yep, added here https://github.com/jesseduffield/lazygit/issues/635
