### ISSUE TITLE
what is `v` (vscode) supposed to do?

### ISSUE THREAD

**Issue by sbromberger** [jesseduffield/lazygit#22]
I have vscode installed but when I go to a file (see screenshot) and press `v`, nothing happens.

<img width="1067" alt="screen shot 2018-08-05 at 16 33 58" src="https://user-images.githubusercontent.com/941359/43691190-9a7a0234-98cd-11e8-8e0e-17383425196a.png">

**Comment by jesseduffield** [comment]
hmm looks like a regression. I'll have a closer look in a bit

**Comment by sbromberger** [comment]
Thank you!

**Comment by itsheng** [comment]
@sbromberger I pressed 'o' and the file got opened in vscode.

**Comment by scbizu** [comment]
@itsheng it  It will open the Finder under the MacOS XDDDD

**Comment by sbromberger** [comment]
`o` will open the associated application (in my case, for this file, TeXPad).

**Comment by scbizu** [comment]
It seems like @jesseduffield forgets to binds the `v` and `s` in KeyBindings ,check it in [gui.go](https://github.com/jesseduffield/lazygit/blob/master/gui.go)

**Comment by jesseduffield** [comment]
Fixed this in https://github.com/jesseduffield/lazygit/commit/9a3b565806689a35f1d330c233dbbc725bb7ebe8 :)
