### ISSUE TITLE
Feature Request: commit message characters count

### ISSUE THREAD

**Issue by epistrephein** [jesseduffield/lazygit#223]
**Is your feature request related to a problem? Please describe.**
A lot of git guidelines specify that the maximum length of the commit message should be 50 characters.

**Describe the solution you'd like**
It would be nice if the current commit message modal displayed a count of the characters of the message. Something like:

![commit message count](https://epi.st/share/lazygit-commit-count-feature.png)

**Comment by jesseduffield** [comment]
Sounds like a good feature to me, and simple enough to implement (i.e. chuck a new view on top of the confirmation view without a frame and render the character count in it). Any takers for a PR? I probably wouldn't be able to get around to this for a while

**Comment by dawidd6** [comment]
I'll take it.

**Comment by dawidd6** [comment]
@epistrephein should be resolved since PR for that has been already merged into master (https://github.com/jesseduffield/lazygit/pull/262)

**Comment by epistrephein** [comment]
Awesome @dawidd6, thank you very much for the work! 😊

**Comment by jesseduffield** [comment]
closing :)
