### ISSUE TITLE
Cannot compile: found packages ...

### ISSUE THREAD

**Issue by mjk-gh** [jesseduffield/lazygit#2233]
**Describe the bug**
After cloning the git repository and following the instructions in README.md on manual compilation, I cannot successfully compile lazygit. 

**To Reproduce**
```
$ go install
vendor/github.com/mattn/go-runewidth/runewidth.go:7:2: found packages uniseg (doc.go) and main (gen_breaktest.go) in /home/mjk/tmp/prog/git/lazygit/lazygit/vendor/github.com/rivo/uniseg
```
Same with `go run main.go`.

**Expected behavior**
Compilation succeeds with building a binary called `lazygit`.

**Version info:**
- Most current git version of lazygit source
- git version 2.34.1
- go version go1.15.15 linux/amd64

**Additional context**
```
$ dpkg -l|grep uniseg
ii  golang-github-rivo-uniseg-dev                 0.2.0-1                                        all          Unicode Text Segmentation for Go
```

**Note:** please try updating to the latest version or [manually building](https://github.com/jesseduffield/lazygit/#manual) the latest `master` to see if the issue still occurs.
I did a `git pull` before compiling: Already up to date.

**Comment by mark2185** [comment]
Are you able to update `go` to `v1.18` or `v1.19`?

**Comment by mjk-gh** [comment]
Thanks for the suggestion! I was able to install `v1.19` from Backports.

Now I can at least run `go run main.go` in the git directory, and lazygit will start.

Only thing that will not work is the installation of any kind of binary, neither using `go run main.go` nor `go install`. No error messages, but also no installation, neither as user nor as root.

Where would the binary file be created within the git directory and/or in the system's file system?

**Comment by mark2185** [comment]
`go run main.go` doesn't create a binary (or it does, but then it's a temporary one)

As for `go install`, it probably installs it in `$GOPATH`, which is I'm guessing `~/go` by default, so check in `~/go/bin` after running `go install`. If it _is_ there, don't forget to add it to your path.

**Comment by mjk-gh** [comment]
Bingo! Found it in ~/go/bin.

Thanks a lot! *hug*
