### ISSUE TITLE
"No patch created" when trying to push one changed file

### ISSUE THREAD

**Issue by rakula4** [jesseduffield/lazygit#2242]
**Describe the bug**
After changing multiple files in a repo, I only want to commit and push one file. When I hit `space` on one file and then `c` to add a commit message, and finally `ctrl-p` to push, it gives an error:
```No patch created yet. To start building a patch, use 'space' on a commit file or enter to add specific lines```

**To Reproduce**

1. Introduces changes to multiple files in a codebase
2. In the Files panel, hit `space` on one file to add those changes.
3. Hit `c` to prompt commit message and add the message, hit `enter`. 
4. Hit `ctrl-p` to push that commit -> this results in error:
```No patch created yet. To start building a patch, use 'space' on a commit file or enter to add specific lines```

**Expected behavior**
`ctrl-p` should result in pushing that change. 

**Screenshots**
N/A

**Version info:**
_Run `lazygit --version` and paste the result here_
commit=367b0d331836c90c015bf0c45f88612f3d94d08a, build date=2022-07-20T09:27:56Z, build source=binaryRelease, version=0.35, os=darwin, arch=amd64

_Run `git --version` and paste the result here_
git version 2.32.1 (Apple Git-133)

**Additional context**

**Note:** please try updating to the latest version or [manually building](https://github.com/jesseduffield/lazygit/#manual) the latest `master` to see if the issue still occurs.

**Comment by mark2185** [comment]
I'm not sure if it's closed by accident or not, but just for future reference: it's `uppercase P` for `push`, i.e. `shift+p`.
