### ISSUE TITLE
Pull and update selected branch (not checked-out) without checkout

### ISSUE THREAD

**Issue by ooopscc** [jesseduffield/lazygit#2243]
**Is your feature request related to a problem? Please describe.**
When using cli, I always do a `git fetch origin X:X` to update X branch without branch switching. It's really helpful. X branch usually is a target branch, then I can rebase on it.

**Describe the solution you'd like**
Selected a branch in lazygit, pull or fetch should using this branch.

**Describe alternatives you've considered**
You can add more options to let us select to update which branch but I need this feature, thanks.

**Comment by mark2185** [comment]
Have you tried pressing `f` on the branch you want to fetch? I think that fetches only the currently selected one.

**Comment by ooopscc** [comment]
Excellent, already implemented. Sorry, I search pull/update/sync instead and didn't find it before.
