### ISSUE TITLE
Force push fails

### ISSUE THREAD

**Issue by socketbox** [jesseduffield/lazygit#2246]
**Describe the bug**
In a git worktree, I make changes that require modifying existing commits that have already been pushed to a remote. After committing these changes, I attempt to push them to the remote. I'm then appropriately prompted to approve a force push. After electing to force push, I'm presented with the following error.

![image](https://user-images.githubusercontent.com/1593835/199505954-619e5be0-ccaf-4e04-9d68-21477ff2bd1f.png)

**To Reproduce**

1. Create a git worktree project by creating a bare clone of a repo: `git clone --bare git@github.com:example/workit.git .bare`  
2. Set `gitdir`: `echo "gitdir: ./.bare" > .git`
3. Add `main` and another branch using `git worktree add`. Your directory structure should look something like this:
```
`.\project_dir`
`.\project_dir\.bare` <-- the result of `git clone --bare git@github.com:yourorg/project.git .bare`
`.\project_dir\.git` <-- contains `gitdir: ./.bare`
`.\project_dir\main` <-- the result of `git worktree add main`
`.\project_dir\feature_branch` <-- the result of `git worktree add feature_branch`
```
5. In the `feature_branch` worktree, run `lazgyit`. Make changes that alter previous commits (amend, for example)
6. Stage, commit, and type `P` to push to the remote.
7. Agree to force the push using `Enter`
8. You should now see an error like the one pictured above.
<error image>

**Expected behavior**
I expect that, after step 7, the changes are pushed to the remote without fail.

**Version info:**
```
commit=c4e71356bbb0bff7ba4d12d4b86f2959f32fed47, build date=2022-10-25T05:49:39Z, build source=unknown, version=c4e71356, os=linux, arch=amd64
```
`git version 2.38.1`

**Additional context**
What was mentioned previously regarding git worktrees. That, and there's also a discussion regarding this behavior (with debug logging) here: https://github.com/jesseduffield/lazygit/issues/2237#issuecomment-1298954907

**Comment by mark2185** [comment]
Could you try the same thing, but from a _non-bare_ repo?

**Comment by socketbox** [comment]
Just to clarify: I'm not in the directory that contains `.bare` when I run `lazygit`. I'm in a sibling/peer directory of the `.bare` directory that is a worktree. To clarify:
```
`.\project_dir`
`.\project_dir\.bare`
`.\project_dir\.git` 
`.\project_dir\main` <-- a worktree for main
`.\project_dir\feature_branch` <-- I'm inside a directory like this when I run lazygit
```
I'm not familiar with how one goes about setting up a project that uses git worktrees without first obtaining a bare clone of the repo. Could you provide me with a link or instructions on how to do so?

**Comment by mark2185** [comment]
> I'm not familiar with how one goes about setting up a project that uses git worktrees without first obtaining a bare clone of the repo. Could you provide me with a link or instructions on how to do so?

It's the same, both with a bare repo or a full one, `git worktree create /path/to/worktree <branch-name>`.

> If the tip is valid, then shouldn't we include the information it provides in the warning that I've quoted?

Good point.

**Comment by socketbox** [comment]
Not sure why, but this seems to be no longer an issue. 
```
[2022-12-30 16:26:13]» lazygit -version
commit=c4e71356bbb0bff7ba4d12d4b86f2959f32fed47, build date=2022-10-25T05:49:39Z, build source=unknown, version=c4e71356, os=linux, arch=amd64

[2022-12-30 16:26:16]» git --version 
git version 2.39.0                   

```
There are some rebase-related changes in 2.38.2 and 2.39, but I don't know enough about how LG uses rebase to determine if any of them might have had a role in correcting this issue.

**Comment by Arrow-x** [comment]
this is still exactly the issue  0.37.0-1
