### ISSUE TITLE
Merge loaders package into git_commands package

### ISSUE THREAD

**Issue by jesseduffield** [jesseduffield/lazygit#2248]
The loaders package (`pkg/commands/loaders`) should be merged into `pkg/commands/git_commands` because:
* it operates at the same level of abstraction (that is: calling git commands directly), so if we want to change how git commands are called, we'll need to change both packages
* there are circular dependency problems: the loaders package defines a BranchInfo struct as of https://github.com/jesseduffield/lazygit/pull/2224 which is used from the gui package but the gui package shouldn't care about the distinction between the git_commands and the loaders package. We could use a facade but that's extra maintenance work that I don't think is necessary given how similar the two packages are.

To keep the file names meaningful we'll need to append `_loader` to the files from the loaders package e.g. `pkg/commands/loaders/files.go` becomes `pkg/commands/git_commands/file_loader.go`. In this case we're using the singular `file` instead of the plural `files` because the loader struct defined in the file is actually called `FileLoader`.

**Comment by nikpivkin** [comment]
@jesseduffield Should it be closed?

**Comment by jesseduffield** [comment]
@nikpivkin Yes! Good pickup, I'll close this now
