### ISSUE TITLE
Use foreground instead of white color

### ISSUE THREAD

**Issue by lukepighetti** [jesseduffield/lazygit#2255]
On light theme terminals, the text contrast is very low.
<img width="779" alt="Screen Shot 2022-11-09 at 10 25 56 AM" src="https://user-images.githubusercontent.com/666539/200870910-7c2f9a81-7c12-4789-97cd-ddb163184953.png">

 I have to change White in iTerm to almost black for it to paint correctly
<img width="1153" alt="Screen Shot 2022-11-09 at 10 26 06 AM" src="https://user-images.githubusercontent.com/666539/200870929-cfbbf889-5c0a-4b75-bcc8-78e93cfa3606.png">

**Comment by Ryooooooga** [comment]
```yaml
gui:
  theme:
    lightTheme: true
```

**Comment by lukepighetti** [comment]
Looking for a solution that doesn't need to be reconfigured when my system automatically switches from dark to light mode, is that implemented?

**Comment by jesseduffield** [comment]
in `pkg/theme/theme.go` we're going 
```go
	isLightTheme := themeConfig.LightTheme
	if isLightTheme {
		DefaultTextColor = style.FgBlack
		DefaultHiTextColor = style.FgBlackLighter
		GocuiDefaultTextColor = gocui.ColorBlack
	} else {
		DefaultTextColor = style.FgWhite
		DefaultHiTextColor = style.FgLightWhite
		GocuiDefaultTextColor = gocui.ColorWhite
	}
```

And to my knowledge there's no way to know whether we're in a light theme without a config value.

With that said, `DefaultHiTextColor` doesn't actually get used anywhere and `DefaultTextColor` could be set to style.FgDefault, and `GocuiDefaultTextColor` could be set to gocui.ColorDefault. I'm pretty sure that would actually give us what we want.
