### ISSUE TITLE
Show custom commands pending status in a popup

### ISSUE THREAD

**Issue by artvi** [jesseduffield/lazygit#2258]
**Is your feature request related to a problem? Please describe.**
Currently, when the `showBottomLine` option is set to `false`, the pending status of custom command is not displayed anywhere. There is no way to tell if a command is still running if you don't stream the output to command log or use `showOutput` feature. It feels glitchy when a popup with command output suddenly appears without any previous indication though.

**Describe the solution you'd like**
I think that in many cases displaying loading status in a popup (the same way as it already implemented with built-in pulling) might be a better UI solution. At least when `showOutput` option is on. It will feel more consistent while interacting with prompts and waiting for commands to be executed and output something.

**Describe alternatives you've considered**
Alternatively, the execution status could be still shown in the bottom line, but it should ignore `showBottomLine` then.

**Comment by jesseduffield** [comment]
When something is loading, it should already ignore the showBottomLine config, so I assume that there's no loader and that's the core of the problem. I'm thinking we go with that approach

**Comment by jesseduffield** [comment]
hmm in `pkg/gui/services/custom_commands/handler_creator.go` we actually are using a loader:
```go
	return self.c.WithWaitingStatus(loadingText, func() error {
		self.c.LogAction(self.c.Tr.Actions.CustomCommand)

		if customCommand.Stream {
			cmdObj.StreamOutput()
		}
		output, err := cmdObj.RunWithOutput()
		if err != nil {
			return self.c.Error(err)
		}

		if customCommand.ShowOutput {
			if strings.TrimSpace(output) == "" {
				output = self.c.Tr.EmptyOutput
			}
			if err = self.c.Alert(cmdStr, output); err != nil {
				return self.c.Error(err)
			}
			return self.c.Refresh(types.RefreshOptions{})
		}
		return self.c.Refresh(types.RefreshOptions{})
	})
```

**Comment by jesseduffield** [comment]
in `pkg/gui/arrangement.go` we have:
```go
showInfoSection := gui.c.UserConfig.Gui.ShowBottomLine || (gui.State.Searching.isSearching || gui.isAnyModeActive())
```

So looks like we just need to also show the bottom line when we're loading

**Comment by artvi** [comment]
@jesseduffield sure, I'll do it. Your suggestion fixes the issue, but It also brings the whole bottom line back for the period of waiting. I think it would be nice if it behaved like search line (covering the whole bottom line with bg=default) when showBottomLine is set to false. What do you think?

**Comment by jesseduffield** [comment]
I agree. We'll need to ensure, however, that if we're both in a 'mode' (for example, if you press 'c' on a commit we enter cherry-picking mode and it says '1 commit selected' at the bottom right) and we're loading something, that both the loader is shown (bottom left) and the mode text is shown (bottom right)

**Comment by jesseduffield** [comment]
This was fixed by https://github.com/jesseduffield/lazygit/pull/2273. Thanks @artvi !
