### ISSUE TITLE
Panic selecting a directory in the Files pane

### ISSUE THREAD

**Issue by ingorichter** [jesseduffield/lazygit#226]
**Describe the bug**
Selecting a directory in the Files pane results in panic

**To Reproduce**
1. add a directory to your repo
2. select that directory in the Files pane
3. See error

**Expected behavior**
No panic!

**Screenshots**
![image](https://user-images.githubusercontent.com/86214/44704074-e02cbf00-aa4e-11e8-9442-59ee28cfa177.png)
Moving the selection to the directory `public` will result in the panic

**Desktop (please complete the following information):**
 - OS: macOS 10.13.5
 - Lazygit Version v.0.1.80
 - The last commit id if you built project from sources N/A

**Additional context**
panic: cat: public: Is a directory

goroutine 1 [running]:
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).catSelectedFile(0xc420104c60, 0xc4202ce000, 0xc420347d07, 0xc420347d00, 0xc420347cf0, 0xc420347ce6)
	/go/src/github.com/jesseduffield/lazygit/pkg/gui/files_panel.go:326 +0x27b
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).refreshMergePanel(0xc420104c60, 0xc4202ce000, 0xc4203bba70, 0x0)
	/go/src/github.com/jesseduffield/lazygit/pkg/gui/merge_panel.go:179 +0x4d
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).handleFileSelect(0xc420104c60, 0xc4202ce000, 0xc42032a1e0, 0x5, 0x0)
	/go/src/github.com/jesseduffield/lazygit/pkg/gui/files_panel.go:190 +0x264
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).newLineFocused(0xc420104c60, 0xc4202ce000, 0xc42032a1e0, 0x13, 0x2)
	/go/src/github.com/jesseduffield/lazygit/pkg/gui/view_helpers.go:89 +0xd0
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).cursorDown(0xc420104c60, 0xc4202ce000, 0xc42032a1e0, 0x0, 0xc4203bbdb0)
	/go/src/github.com/jesseduffield/lazygit/pkg/gui/view_helpers.go:191 +0x13d
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).(github.com/jesseduffield/lazygit/pkg/gui.cursorDown)-fm(0xc4202ce000, 0xc42032a1e0, 0xc4203bbdb0, 0xc4202d0000)
	/go/src/github.com/jesseduffield/lazygit/pkg/gui/keybindings.go:83 +0x3e
github.com/jesseduffield/lazygit/vendor/github.com/jesseduffield/gocui.(*Gui).execKeybinding(0xc4202ce000, 0xc42032a1e0, 0xc4201daf00, 0xc420000201, 0xc4203bbdb0, 0xc4203bbdb0)
	/go/src/github.com/jesseduffield/lazygit/vendor/github.com/jesseduffield/gocui/gui.go:679 +0x3e
github.com/jesseduffield/lazygit/vendor/github.com/jesseduffield/gocui.(*Gui).execKeybindings(0xc4202ce000, 0xc42032a1e0, 0xc4203bbd18, 0x114b0e9, 0x0, 0x0)
	/go/src/github.com/jesseduffield/lazygit/vendor/github.com/jesseduffield/gocui/gui.go:665 +0x10b
github.com/jesseduffield/lazygit/vendor/github.com/jesseduffield/gocui.(*Gui).onKey(0xc4202ce000, 0xc4203bbd18, 0xc4202ec100, 0xc4202e60a0)
	/go/src/github.com/jesseduffield/lazygit/vendor/github.com/jesseduffield/gocui/gui.go:626 +0x1b3
github.com/jesseduffield/lazygit/vendor/github.com/jesseduffield/gocui.(*Gui).handleEvent(0xc4202ce000, 0xc4203bbd18, 0xc4203bbd10, 0x0)
	/go/src/github.com/jesseduffield/lazygit/vendor/github.com/jesseduffield/gocui/gui.go:431 +0x40
github.com/jesseduffield/lazygit/vendor/github.com/jesseduffield/gocui.(*Gui).MainLoop(0xc4202ce000, 0xc4202ce000, 0x0)
	/go/src/github.com/jesseduffield/lazygit/vendor/github.com/jesseduffield/gocui/gui.go:391 +0x2e4
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).Run(0xc420104c60, 0x0, 0x0)
	/go/src/github.com/jesseduffield/lazygit/pkg/gui/gui.go:337 +0x270
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).RunWithSubprocesses(0xc420104c60)
	/go/src/github.com/jesseduffield/lazygit/pkg/gui/gui.go:346 +0x2f
main.main()
	/go/src/github.com/jesseduffield/lazygit/main.go:48 +0x126

**Comment by jesseduffield** [comment]
I had not considered how to display a folder with a merge conflict. I think as a fix for now I can just make it check whether it's a directory and if it is, say 'this is a directory' in the diff view. I'm not sure how to go about supporting resolving of merge conflicts, because right now the list shown in the files panel is a 1-1 mirror image of what git status shows.

**Comment by ingorichter** [comment]
I think that is a viable solution. Panicking is a bit harsh ;-)

**Comment by jesseduffield** [comment]
@ingorichter let me know if this resolves your issue :)

**Comment by ingorichter** [comment]
@jesseduffield that looks good to me. Thanks for fixing!
