### ISSUE TITLE
Add ability to commit when "Staged Changes" panel is focused

### ISSUE THREAD

**Issue by OliverJAsh** [jesseduffield/lazygit#2285]
**Is your feature request related to a problem? Please describe.**
After I stage changes, I have to move focus back to the "Files" panel for the commit shortcut (`c`) to work.

**Describe the solution you'd like**
The commit shortcut should work when the "Staged Changes" panel is focused.

**Comment by jesseduffield** [comment]
Makes sense. We'd want to support 'c' (commit in-lazygit), 'shift+c' (commit in subprocess), and 'w' (the WIP commit keybinding). If we're supporting shift+c we'd want to ensure that we land back in the staging panel upon returning from the subprocess (can't recall if we already would do that).

To do this we'd need to take the handlers for the above keybindings out of `pkg/gui/controllers/files_controller.go` and into `pkg/gui/controllers/helpers/working_tree_helper.go` and then invoke them from `pkg/gui/controllers/files_controller.go` and `pkg/gui/controllers/staging_controller.go`. I'll chuck a good-first-issue label on this.

Would you be up for raising a PR @OliverJAsh ?

**Comment by arnaudperalta** [comment]
I'm working on it, can I be assigned ?
