### ISSUE TITLE
Add a shortcut to open user editor to rename commit

### ISSUE THREAD

**Issue by d-dorazio** [jesseduffield/lazygit#229]
**Is your feature request related to a problem? Please describe.**
As of now, I don't think there's a way to rename the last commit in the user editor, while it's possible to do so when creating a new commit.

**Describe the solution you'd like**
Ideally I'd like a shortcut to open the user editor to rename a commit.  <kbd> shift </kbd> + <kbd> R </kbd> seems intuitive since <kbd> shift </kbd> + <kbd> C </kbd> opens the user editor for a new commit. I know `lazygit` already uses <kbd> shift </kbd> + <kbd> R </kbd> for refreshing, but I don't think the two conflict with each other since they're meant to be used in different views, but I'm not totally sure.

**Describe alternatives you've considered**
I can always rename the commit in lazygit directly, but given that lazygit allows to enter a new commit in the user editor I think it'd be coherent to have the same feature for renaming.

**Additional context**
I'm happy to work on this and open a PR in the next few days if you think the feature is useful.
P.S. I'm loving this project! Keep up the good work!

**Comment by jesseduffield** [comment]
@d-dorazio thanks for the encouragement! If you want to open a PR for this that would be fantastic. I agree that shift+R makes sense. shift+R might currently be a global keybinding but there is no harm in restricting it to just the files panel. Let me know if you need any pointers to help you with the PR :)

**Comment by jesseduffield** [comment]
I believe this has been implemented for some time now, in that shift+R on any commit will allow you to rename/reword the commit in your editor in the same way that shift+C opens a commit message in your editor. Let me know if I've missed anything :)
