### ISSUE TITLE
gui.mainPanelSplitMode doesn't seem to do anything

### ISSUE THREAD

**Issue by LoveSponge** [jesseduffield/lazygit#2299]
**Describe the bug**
When defining in `.config/lazygit/config.yml` the option `gui.mainPanelSplitMode` (per #847) in any way, the panel arrangement seems unchanged regardless of window size; (it's always 'flexible'.)

**To Reproduce**

1. Set `mainPanelSplitMode: 'vertical' # or 'horizontal'` in `config.yml`
2. Restart lazygit
3. Resize window and notice the panels change layout depending on width/height of the window
4. Notice no change depending on config setting.

**Expected behavior**
Expected 'horizontal' setting to make the editor (right hand side) appear **below** the 'status', 'files', 'branches' and 'commits' panels.

**Screenshots**
Screenshots of how it should look are visible in the referenced (merged) pull request.

**Version info:**
```
commit=v0.36.0
build date=2022-11-15T07:26:07Z
build source=binaryRelease
version=0.36.0
os=linux
arch=amd64
git version=2.38.1
```

**Additional context**
I did try digging through the source files, since the one's written in the PR have changed over time since it was merged, but see no reason why any of the changes since the merge should stop this feature from working properly.

**Comment by Nivethan-Ar** [comment]
same issue for me, i want to set the half screen mode( achieved by pressing + ) as the default for lazy git. so i tried the following code 
`
gui:
  mainPanelSplitMode: 'vertical' # one of 'horizontal' | 'flexible' | 'vertical'
  theme:
    activeBorderColor:
      - red
      - bold
  splitdiff: 'always'

`
but this mainPanelSplitMode not doing any changes, i tried changing border colors and it changes instantly but not this! 
how do i make the half screen mode by default?

**Comment by jaykaron** [comment]
@LoveSponge
I think this is more confusion around the flag than a bug. The `mainPanelSplitMode` only affects the layout when the main panel is in 'split' mode (e.g. has 2 parts). For example, when staging parts of a file.

If the config is set to `"vertical"` then the 2 panels will always be stacked one on top of the other.
![image](https://user-images.githubusercontent.com/22824315/209354343-f122231c-6eeb-4fd9-bd49-ae696e9dc45e.png)

And they will be beside each other if it's `"horizontal"`.
![image](https://user-images.githubusercontent.com/22824315/209355140-402efd22-bb8b-424b-a4af-e53470c64790.png)

And the default `"flexible"` chooses the layout depending on the size of the terminal. 

But the setting doesn't change the layout of the main panel in respect to the other panels.

**Comment by LoveSponge** [comment]
This can be closed as its not a bug but a misunderstanding as to the purpose of these settings.
