### ISSUE TITLE
FR: Make main view focusable

### ISSUE THREAD

**Issue by jesseduffield** [jesseduffield/lazygit#230]
**Is your feature request related to a problem? Please describe.**
Currently the main view can be scrolled with pgup/pgdn but it would be good to use the arrow keys for scrolling that too

**Describe the solution you'd like**
We should be able to hit 'enter' on a selected item in a side panel and have the main view focused, where we can then naturally scroll the view with the up/down arrows (or equivalent vim keybindings)

**Describe alternatives you've considered**
none

**Additional context**
none

**Comment by glvr182** [comment]
I could do that when i work on the gui package rework

**Comment by OliverJAsh** [comment]
This would also be useful for searching the contents of a commit.
