### ISSUE TITLE
Make the wording of rebase less scary

### ISSUE THREAD

**Issue by jesseduffield** [jesseduffield/lazygit#2302]
### Discussed in https://github.com/jesseduffield/lazygit/discussions/2292

<div type='discussions-op-text'>

<sup>Originally posted by **danielo515** November 25, 2022</sup>
Hello.
Thank you for this great, great tool. Thanks to it I can use Nvim without missing VSCode UI at all.

Something I find particularly scary is the wording of rebase. The way (I think, correct me if I'm wrong) that you rebase your current branch on top of another one is by going to the local-branches section, put the selector on the branch you want to rebase (lets say it's master), and then hit `r`.
Then a confirmation modal (which is always wonderful) appears and asks for confirmation, but it says: `Are you sure that you want to rebase "your-branch" into "master"`
As far as I know, this rebases master with your changes from your-branch and keeps master untouched, all is done in your current branch. However, the wording ins confusing and may feel like you are going to modify the "master" branch, which is not what you want.

I understand that the message follows the GIT conventions, which I always found confusing about all the things related to rebasing. Will it be possible to make lazygit more friendly in that way?</div>

**Comment by jesseduffield** [comment]
as discussed we want to change the language to 'on top of' instead of 'onto'

**Comment by pavleprica** [comment]
I think this issue should be closed :D

**Comment by iogrt** [comment]
sorry for ghost bumping but please close this
