### ISSUE TITLE
Checkout by name without detaching

### ISSUE THREAD

**Issue by kabessao** [jesseduffield/lazygit#2312]
**Is your feature request related to a problem? Please describe.**
Whenever I'm about to change branches I use the "Checkout by name" menu, paste the branch name, press enter, and there is my branch, but I think this is a waste of time since this menu has a search feature, but whenever I choose the same branch on the search results it detaches, just because the result has a "origin/" at the beginning. 

**Describe the solution you'd like**
I would want the search result to not detach my repository.

**Describe alternatives you've considered**
Maybe creating a separate key ("C" for example ) that does the same but doesn't detaches.

**Additional context**

Lets say I have a branch called "feature/new_button". Using the search results this is the command lazygit uses:
git checkout "origin/feature/new_button"

and on "Local Branches" it will show as "(HEAD detached at origin/feature/new_button)".

But if in the same prompt I write "feature/new_button" and press enter without choosing any result this is the command it uses:
git checkout "feature/new_button"

and on "Local Branches" it will show as "feature/new_button".

(I apologize for any misunderstanding that may happen. English is not my native language)

**Comment by mark2185** [comment]
You could write a custom command for that and map it to `C`.

Here's [the docs](https://github.com/jesseduffield/lazygit/blob/master/docs/Custom_Command_Keybindings.md) for creating custom commands. Your command should basically be of type `input` and do `git checkout {{ index .PromptResponses 0}}`.

Alternatively, you could go to the `Branches panel` (number `3`), press `]` to switch to the remotes, press `enter` to enter the `origin` remote, search and checkout the branch from there.

**Comment by mark2185** [comment]
> Would still be good if it can pre-fill the branch name when you select a branch from remote in the checkout window

That should already happen, though. 

Here's a [demo](https://asciinema.org/a/WjBzarDV2WwvJI6Wob2Ul0aG6).

**Comment by lichader** [comment]
> > Would still be good if it can pre-fill the branch name when you select a branch from remote in the checkout window
> 
> That should already happen, though.
> 
> Here's a [demo](https://asciinema.org/a/WjBzarDV2WwvJI6Wob2Ul0aG6).

Thanks. I was meaning if you checkout directly from the `Branches panel` and select a remote branch.

**Comment by mark2185** [comment]
Ah, gotcha.

That's actually something I've been meaning to fix - if the `HEAD` is in a detached state, but it coincidentally points to an existing branch, maybe the initial prompt value for creating a new branch from it should be _that_ branch. 
Seems like a good first issue if someone else wants to take a shot at it.

@jesseduffield thoughts?

**Comment by cyrusduong** [comment]
For anyone trying to do this still here is the custom command I configured

```
customCommands:
  - key: "C"
    context: "localBranches"
    description: "Checkout branch using search"
    prompts:
      - type: 'input'
        title: "Branch Name"
        key: BranchName
        suggestions:
          preset: 'remoteBranches'
    command: "git checkout {{ .Form.BranchName }}"
```

**Comment by niderhoff** [comment]
> demo

Why can't the checkout command from the branches panel just provide 2 options:

1. create new branch and track the remote, checkout that (default behavior from git checkout <remote branch name>)
2. checkout detached (current behavior in lazygit)

or we could have 2 different hotkeys (as proposed): c vs. C

it is a bit puzzling why lazygit would here behave different than normal git-cli.
