### ISSUE TITLE
Commit from the "Unstaged Changes" pane

### ISSUE THREAD

**Issue by ooloth** [jesseduffield/lazygit#2313]
**Is your feature request related to a problem? Please describe.**

When I commit individual lines from a file (by pressing `Enter` on a file in the "Files" pane and then `Space` on individual lines in the "Unstaged Changes" pane), I instinctively then press `c` when I'm ready to commit the lines I've staged, but `c` does nothing while my cursor is in "Unstaged Changes".

To make `c` work, I need to press `Esc` to go back to "Files", then commit from there, then press `Enter` again to go back to "Unstaged Changes" and resume staging more lines in that file.

**Describe the solution you'd like**

I'd prefer if all the same commit commands that work in "Files" pane also work while in the "Unstaged/Staged Changes" panes so I can commit from where I already am while I'm staging individual lines.

**Describe alternatives you've considered**

I considered customizing my config file to add the missing keymaps, but I could easily figure out how to do that (feel free to let me know how if that's the preferred solution).

**Comment by mark2185** [comment]
That was actually added recently, in #2298 , but it hasn't been released yet. Until then you could build the current `master`.

**Comment by ooloth** [comment]
@mark2185 Oh sweet! That's great. Thanks for letting me know.
