### ISSUE TITLE
Where can I find the lazygit config file

### ISSUE THREAD

**Issue by restagner** [jesseduffield/lazygit#232]
Where can I find the lazyfit config file?

**Comment by dawidd6** [comment]
What OS are you using?

**Comment by restagner** [comment]
@dawidd6 

I'm using both Linux (Ubuntu 16.04) and MacOS

**Comment by dawidd6** [comment]
On Linux it's localized here:
`$HOME/.config/jesseduffield/lazygit`

On macOS probably too.

**Comment by restagner** [comment]
Thank you!!

**Comment by jesseduffield** [comment]
closing :)
