### ISSUE TITLE
Deleting a branch with its upstream

### ISSUE THREAD

**Issue by oereneli** [jesseduffield/lazygit#2321]
It would be great that when I deleted a branch locally, lazygit prompts to ask if I want to delete remote upstream branch also. This works in Intellij's internal git manager. Another approach also might be instead of `d` we can use `D` to delete the branch with its upstream.

**Comment by mark2185** [comment]
Duplicate of #2157 .

Do please add your suggestions there :)

**Comment by oereneli** [comment]
Sorry I didn't see that 👍
