### ISSUE TITLE
In max os  , how to show the shortcut key prompting in bottom?

### ISSUE THREAD

**Issue by heartaway** [jesseduffield/lazygit#233]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by jesseduffield** [comment]
It only displays when your terminal window is large enough or your font size is small enough. Looks like we need to find a better solution for showing keybindings

**Comment by heartaway** [comment]
think you .

**Comment by jesseduffield** [comment]
No worries :) closing
