### ISSUE TITLE
Can't remap `i` key in Files

### ISSUE THREAD

**Issue by jsekerez** [jesseduffield/lazygit#2347]
**Describe the bug**
After remapping `nextBlock-alt` to `i`, it doesn't work when in Files, forcing me to use the right arrow key. I've already remapped `ignoreFile` to `I`, and no other command is mapped to `i`.

**To Reproduce**

1. Go to the config file;
2. Remap `nextBlock-alt` to `i`, and `ignoreFile` to `I`. Ensure that no command is mapped to `i`.
3. Turn on lazygit and press `i` from the Files panel.
4. See that it doesn't do anything. Navigate to other panels, and see that it works.

**Expected behavior**
Pressing `i` should move to the next block.

**Version info:**
commit=, build date=, build source=homebrew, version=0.36.0, os=darwin, arch=arm64, git version=2.37.1 (Apple Git-137.1)

**Comment by Ryooooooga** [comment]
duplicated of #2317

**Comment by mark2185** [comment]
@jsekerez as stated in #2317 , it's fixed in current master and it'll be in `v0.37.0`. Feel free to try it out and reopen if it's not fixed.

Closing.
