### ISSUE TITLE
commits from 'main'-branch should be green not yellow, the 'master' branch is outdated

### ISSUE THREAD

**Issue by andrewendlinger** [jesseduffield/lazygit#2349]
In my understanding there is no way in the config file to specify a branch related commit color.

**Comment by Camille-Upway** [comment]
Although not ideal, you can create a symbolic ref to your `main` branch, so that lazygit works as expected:
```
git symbolic-ref refs/heads/master refs/heads/main
```

**Comment by joihn** [comment]
thanks for the suggestion @Camille-Upway. 
In my case, I would like to use `develop` instead of `master` for my commits coloring. 


Since a `master` already exist in my repo (used for some other purpose), I think applying your workaround would be a bad idea, right ?

**Comment by joihn** [comment]
here is my workaround (ugly hardcoded but functionnal ):
- clone the repo, 
- edit https://github.com/jesseduffield/lazygit/blob/master/pkg/commands/git_commands/commit_loader.go#L376 to whatever branch you want.
- compile you very own binary of lazygit (I personnal used the included docker image)
- copy the binary from the docker image (`/bin/lazygit`) to your system  (for example to `/usr/local/bin/lazygit`)

Of course the proper way to do it would be for this value is read from the user config :)

**Comment by Niels-NTG** [comment]
If I understand your issue correctly, this was resolved in version 0.39.1 with #2619 .

**Comment by jesseduffield** [comment]
Indeed @Niels-NTG . I'll close this off
