### ISSUE TITLE
[Feature request] Fuzzy searcher for the menu 

### ISSUE THREAD

**Issue by joihn** [jesseduffield/lazygit#2350]
**Is your feature request related to a problem? Please describe.**
I often press X to see the menu of available feature:
![image](https://user-images.githubusercontent.com/11663917/210978527-bd8be9ad-a404-40b9-bdbc-1e79afbb4566.png)
However it's tedious to read it all to find the stuff I want. 
I wish I could ```ctrl-f``` in it to quickly select and execute the wanted feature. 

**Describe the solution you'd like**
ctrl-f let you search trough the menu

**Comment by joihn** [comment]
Duplicate of https://github.com/jesseduffield/lazygit/issues/1489

**Comment by mark2185** [comment]
There's no reason to delete issues, especially since there's the revision history.

In any case, fuzzy searching for menus is not supported _yet_, regular search (`/`) will have to do until then.

**Comment by joihn** [comment]
yes thanks indeed, I found out regular about regular search and figured out it fulfilled my needs, thus the deletion

**Comment by mark2185** [comment]
I know, but others might have the same question and it would be helpful for them to see that it's not yet supported :)

Unless you delete the issue entirely, that is.
