### ISSUE TITLE
Filter commits by author

### ISSUE THREAD

**Issue by mark2185** [jesseduffield/lazygit#2351]
**Is your feature request related to a problem? Please describe.**
I wanna be able to filter by author, not just by file path.

**Describe the solution you'd like**
A new entry in the `<c-s>` menu in the `Commits` panel.

**Describe alternatives you've considered**
Searching with `/`

**Comment by Dagur** [comment]
duplicate of https://github.com/jesseduffield/lazygit/issues/914 I think

**Comment by mark2185** [comment]
Yup, you're right!
