### ISSUE TITLE
Add 'Save to file' or 'copy to clipboard' option to the patch options when building patch from commit

### ISSUE THREAD

**Issue by phanithinks** [jesseduffield/lazygit#2357]
**Is your feature request related to a problem? Please describe.**
It would be nice addition to add 'Save to file' or 'Copy to clipboard' options to the custom patch options in 'diff files' section

**Describe the solution you'd like**
1) Go to any commit. press enter to drill down to files.
2) Press space bar on any the of the file changes to create options
3) press ctrl+p to open patch options
    patch options should show any one of the following options  including the present options
     - save to file
     - copy to clipboard
     for save to file options  user should be prompted file name to save patch and patch should saved at the git repo root
     for copy to clipboard options custom patch should be copied to the clipboard

**Additional context**
This will be very useful to create patch from commits and share with other team members

By the way thank you for building such a awesome tool. Lazygit change my workflow completely

**Comment by mark2185** [comment]
Would you like to give this a shot? 

The `copy to clipboard` should be pretty simple, take a look at [CONTRIBUTING.md](https://github.com/jesseduffield/lazygit/blob/master/CONTRIBUTING.md) for more info, and don't hesitate to ask for help :)

**Comment by bashbunni** [comment]
Ok, I tried for so long to find where to get the Patch output you see in the TUI and I couldn't find it. Do you have any guidance on where I could find that output? I *think* I should be ok from there

**Comment by mark2185** [comment]
Take a look at `lazygit/pkg/commands/git_commands/patch.go`, there are methods like `MovePatchToSelectedCommit`, `MovePatchIntoIndex`, those sound like the options one can do when pressing `<C-P>`. You'll probably want to find the place where they are mapped so you could add a new menu entry with the `copy-to-clipboard` functionality which is already used as a global handler in several places :) 

The way I found this was by searching what I can see from _using_ the `Custom patch` panel in `lazygit`, i.e. its title - `"Custom patch"`, found it in `pkg/i18n/english.go`, then listing all of the references to that yields this:
```
pkg/i18n/english.go|516 col 2| CustomPatch                         string
pkg/gui/commits_panel.go|58 col 18| Title: gui.Tr.CustomPatch,
pkg/gui/refresh.go|691 col 18| Title: gui.Tr.CustomPatch,
pkg/gui/views.go|178 col 50| gui.Views.PatchBuildingSecondary.Title = gui.Tr.CustomPatch
pkg/i18n/english.go|1167 col 3| CustomPatch:                         "Custom patch",
```

So I checked `pkg/gui/commits_panel.go`, saw that the same method invokes something from `gui.git.Patch.PatchManager` and jumped to that.

**Comment by mark2185** [comment]
Great work @phanithinks ! :)

**Comment by phanithinks** [comment]
Thank you @mark2185
