### ISSUE TITLE
FR: Better handling of deleting branches

### ISSUE THREAD

**Issue by jesseduffield** [jesseduffield/lazygit#236]
**Is your feature request related to a problem? Please describe.**
Currently we support deleting a branch with 'd' and force deleting a branch with 'D'. The latter has a confirmation panel to confirm you want to delete the branch.

**Describe the solution you'd like**
We should just have a single 'd' keybinding and if git comes back telling us to use '-D' then we just swallow that error and show a confirmation prompt asking if they want to force delete.

**Describe alternatives you've considered**
What we have now works but it's not ideal

**Comment by glvr182** [comment]
A new TODO for the REWORK?

**Comment by rozuur** [comment]
Is this still open? Can I try fixing it?

**Comment by jesseduffield** [comment]
Yep still open, have a shot!

**Comment by jesseduffield** [comment]
The logic is similar to what we currently do with pushing branches. With pushing, we check to see if there's anything to push, and then we show a prompt asking if they want to force push if there are commits to pull.

With deleting branches, we want to first attempt to delete the branch, then if that gives an error, we want to look at the error and see if it's complaining about the branch not being merged. If that's the case, we want to prompt the user if they want to delete the branch, and if they say yes, we want to run the same command but with -D instead of -d

**Comment by rozuur** [comment]
Will try it over the weekend

**Comment by rozuur** [comment]
@jesseduffield Please go through the logic. If the approach is good, I will remove the support for invoking force delete using 'D'.

**Comment by glvr182** [comment]
@jesseduffield was this done?

**Comment by jesseduffield** [comment]
yep :) closing
