### ISSUE TITLE
Commiting from a diff panel doesn't clear the diff

### ISSUE THREAD

**Issue by mark2185** [jesseduffield/lazygit#2363]
**Describe the bug**
Title.

**To Reproduce**

1. Press `Enter` on an unstaged file
2. Stage something with `Space`
3. Press `c`
4. Commit it
5. Both the `Unstaged Changes` and the `Staged Changes` remain as they were

**Expected behavior**
The `Staged Changes` panel should refresh/be cleared.

**Version info:**
`lazygit` - latest `master` as of reporting this issue.

The feature was added [here](https://github.com/jesseduffield/lazygit/pull/2298), so that's a good place to start.

**Comment by shinhs0506** [comment]
hi! I would like to work on this if its not taken yet

**Comment by mark2185** [comment]
It's not taken, assigned it to you now :)
