### ISSUE TITLE
Lazygit in a docker environment

### ISSUE THREAD

**Issue by bwintertkb** [jesseduffield/lazygit#2366]
Using lazygit within a docker environment

Hey guys, first of all I really love using lazygit! Awesome work :)

I want to use in my docker environment. It works fine but unfortunately whenever I restart container and open lazygit the welcome board pops up. I can't for the life of me find where that flag of it's been seen is stored so I can mount it to a volume.

Could someone direct me to it?

Thank you in advance!

**Comment by mark2185** [comment]
It's probably `.config/lazygit`.

I'm guessing it's the `state.yml` which contains `startuppopupversion: <number>` that quiets it down.

**Comment by bwintertkb** [comment]
Perfect mate, that's exactly it! Cheers :)
