### ISSUE TITLE
ERROR: ppa 'lazygit-team/daily' not found

### ISSUE THREAD

**Issue by amunrarara** [jesseduffield/lazygit#2371]
**Describe the bug**
I'm attempting to install lazygit in an Ubuntu 20.04 VS Code / Docker _Dev Container_. Running the scripts provided by lazygit throw the following error: 

`sudo apt update &&\
sudo apt install software-properties-common -y
sudo add-apt-repository ppa:lazygit-team/daily &&\
sudo apt-get install lazygit -y`

`ERROR: ppa 'lazygit-team/daily' not found`

**To Reproduce**

1. Set up Dev Containers | https://learn.microsoft.com/en-us/training/modules/use-docker-container-dev-env-vs-code/
2. Start a new Ubuntu:jammy environment
3. Run the above scripts into the Dev Container terminal

**Expected behavior**
No errors! 

**Version info:**
lazygit version unavailable
git version 2.34.1

**Additional context**

**Note:** please try updating to the latest version or [manually building](https://github.com/jesseduffield/lazygit/#manual) the latest `master` to see if the issue still occurs.

**Comment by mark2185** [comment]
> Running the scripts provided by lazygit throw the following error

Where'd you find that? `grep`ping `software-properties-common` on the entire repo returns nothing.

The only instructions I could find for `ubuntu` are [these](https://github.com/jesseduffield/lazygit#ubuntu) and I tested them out in a docker container, it works.

**Comment by Ryooooooga** [comment]
related: https://github.com/jesseduffield/lazygit/pull/2372

**Comment by amunrarara** [comment]
`software-properties-common` is a package that includes `add-apt-repository` which is not included by default in the Ubuntu image.

**Comment by amunrarara** [comment]
@Ryooooooga I'll give it a try tonight with your PR, thanks!

**Comment by mark2185** [comment]
@amunrarara I tried it with the latest ubuntu, but my question was more in the lines of "where did you find those instructions?"

The README contains nothing like that for ubuntu.

**Comment by Ryooooooga** [comment]
https://github.com/jesseduffield/lazygit/commit/119002d98cf16fc8f161a9c2046350b6f3f1f179

**Comment by amunrarara** [comment]
Ah, I found that solution by googling this pretty standard error: 

`vscode ➜ /workspaces/worldspark-marketplace-devcontainer $ sudo add-apt-repository ppa:lazygit-team/daily
sudo: add-apt-repository: command not found`

Because, obviously, add-apt-repository isn't installed by default on the image.

I've also changed the Docker image, here's the full .devcontainer.json, and Dockerfile with the `apt install software-properties-common` omitted, so you can see why I'm running that command : 

.devcontainer.json
`{
	"name": "Ubuntu",
	"build": {
		"dockerfile": "Dockerfile"
	},
	"features": {
		"ghcr.io/devcontainers/features/git:1": {},
		"ghcr.io/devcontainers/features/github-cli:1": {},
		"ghcr.io/devcontainers/features/node:1": {}
	},
	"forwardPorts": [
		3000,
		3001,
		3002,
		3003
	],
	"customizations": {
		"vscode": {
			"extensions": [
				"dbaeumer.vscode-eslint"
			]
		}
	}
}
{
	"name": "Ubuntu",
	"build": {
		"dockerfile": "Dockerfile"
	},
	"features": {
		"ghcr.io/devcontainers/features/git:1": {},
		"ghcr.io/devcontainers/features/github-cli:1": {},
		"ghcr.io/devcontainers/features/node:1": {}
	},
	"forwardPorts": [
		3000,
		3001,
		3002,
		3003
	],
	"customizations": {
		"vscode": {
			"extensions": [
				"dbaeumer.vscode-eslint"
			]
		}
	}
}`

Dockerfile
`FROM mcr.microsoft.com/devcontainers/base:ubuntu
RUN sudo add-apt-repository ppa:lazygit-team/daily && sudo apt-get update && sudo apt-get install lazygit`

**Comment by Ryooooooga** [comment]
ppa is abandoned.

**Comment by amunrarara** [comment]
> ppa is abandoned. Please install from binary releases or `go install` as described above.

Ahhh, I made an error there, I followed these instructions and thought they were up-to-date: https://computingforgeeks.com/how-to-install-and-use-lazygit-a-simple-terminal-ui-for-git-commands/

I've updated my `init.sh` to match the Github README instructions for Ubuntu installation, and I'll report back with the results.

**Comment by amunrarara** [comment]
I updated my `init.sh` (see below), and I see `lazygit.tar.gz` in the file explorer. However, the build process threw this error: 

```
qemu: uncaught target signal 11 (Segmentation fault) - core dumped
/workspaces/worldspark-marketplace-devcontainer/.devcontainer/init.sh: line 7:  1905 Segmentation fault      lazygit --version
[56926 ms] postStartCommand failed with exit code 139. Skipping any further user-provided commands.
```

Running `lazygit` results in the following error: 

```
vscode ➜ /workspaces/worldspark-marketplace-devcontainer $ lazygit
qemu: uncaught target signal 11 (Segmentation fault) - core dumped
Segmentation fault
```

Here's `init.sh`
```

**Comment by mark2185** [comment]
> **arm64** M1

You need the `arm64` version then ([this one](https://github.com/jesseduffield/lazygit/releases/download/v0.36.0/lazygit_0.36.0_Linux_arm64.tar.gz))

Just replace the URL in your script:
```diff
-...${LAZYGIT_VERSION}_Linux_x86_64.tar.gz"
+...${LAZYGIT_VERSION}_Linux_arm64.tar.gz"
```

**Comment by amunrarara** [comment]
> > **arm64** M1
> 
> You need the `arm64` version then ([this one](https://github.com/jesseduffield/lazygit/releases/download/v0.36.0/lazygit_0.36.0_Linux_arm64.tar.gz))
> 
> Just replace the URL in your script:
> 
> ```diff
> -...${LAZYGIT_VERSION}_Linux_x86_64.tar.gz"
> +...${LAZYGIT_VERSION}_Linux_arm64.tar.gz"
> ```

That did it! Thanks for all the help, folks.
