### ISSUE TITLE
Custom git log output not working when using bash pipes

### ISSUE THREAD

**Issue by iogrt** [jesseduffield/lazygit#2399]
**Describe the bug**
I tried making a custom git log command that replaces some characters for a nicer output.

**To Reproduce**
Change config.yml to:

```yaml
git:
  branchLogCmd: "git log --graph --color=always --abbrev-commit --decorate --date=relative --pretty=medium {{branchName}} -- | sed 's,a,b,' "
```
git log appears empty within lazygit

**Expected behavior**
git logs with same behaviour as running the command outside

**Screenshots**
![2023-01-27_13:06:42](https://user-images.githubusercontent.com/39342422/215094169-6392d997-a56f-4a34-bfb9-3ba498e4f971.png)

**Version info:**
*Lazygit:* commit=, build date=, build source=nix, version=0.36.0, os=linux, arch=amd64, git version=2.38.1

*Git:* git version 2.38.1

**Comment by Ryooooooga** [comment]
```yaml
git:
  branchLogCmd: bash -c "git log --graph --color=always --abbrev-commit --decorate --date=relative --pretty=medium {{branchName}} -- | sed 's,a,b,'"
```

**Comment by iogrt** [comment]
Uhh, ofcourse. Sorry for the noob question
