### ISSUE TITLE
Umlauts in macOS don't work for me

### ISSUE THREAD

**Issue by srsp** [jesseduffield/lazygit#240]
When I create a file with an Umlaut (ä, ö, ü) I cannot stage this file.

**To Reproduce**
1. `git init`
2. `touch Mötörhead.txt`
3. Start lazygit and try to stage the file
4. File will show up as "M\303\266t\303\266rhead.txt" in Files pane

**Expected behavior**
The file name should read "Mötörhead.txt" in the Files pane.

**Screenshots**
![image](https://user-images.githubusercontent.com/1210541/44783838-f0968400-ab8b-11e8-882a-b488878de9a8.png)

**Desktop (please complete the following information):**
 - OS: macOS 10.13.6
 - Lazygit Version 0.2.1

Thank you for developing lazygit, I really like it!

**Comment by antham** [comment]
It's something related to your git configuration, try this in your repository : ```git config core.quotepath off```

**Comment by srsp** [comment]
`git config core.quotepath off` solved the problem for me. Thanks @jesseduffield

**Comment by antham** [comment]
It's only a partial solution because it doesn't solve the core problem. When we list files with ```git status```, we have to resolve the proper name to avoid such issue.
