### ISSUE TITLE
defaultFgColor uses white as default

### ISSUE THREAD

**Issue by uloco** [jesseduffield/lazygit#2410]
**Describe the bug**
The default setting of `defaultFgColor` uses white color although I have a light terminal theme.

**To Reproduce**
Open lazygit in any light terminal (I tested iTerm2 and Terminall.app.) with default config.
Foreground color (e.g. commits and not checked out branches) are white and hard to read.

**Expected behavior**
It should always use the fg color of the terminal. So it will always be correct.

**Screenshots**
![image](https://user-images.githubusercontent.com/8818340/216568293-7a77e755-af2b-4d1e-af80-62bc81cb0bcc.png)

**Version info:**
commit=, build date=, build source=homebrew, version=0.37.0, os=darwin, arch=arm64, git version=2.39.1

**Comment by Ryooooooga** [comment]
https://github.com/jesseduffield/lazygit/pull/2411
