### ISSUE TITLE
lazygit does not start/open

### ISSUE THREAD

**Issue by zwn** [jesseduffield/lazygit#2419]
**Describe the bug**
I run `lazygit` and nothing happens - nothing shows on terminal. I can only Ctrl-C to get back to shell prompt.

**To Reproduce**

1. Download static binary
2. Extract it
3. Run it

**Expected behavior**
It should either do what it is supposed to or display error.

**Version info:**
```
$ lazygit --version
commit=16802a048e0425182f08cf0e9a2bc31480e9a55d, build date=2023-02-01T11:02:43Z, build source=binaryRelease, version=0.37.0, os=linux, arch=amd64, git version=2.17.1
$ git --version
git version 2.17.1

```

**Additional context**
I did try the `--debug/--logs` trick but nothing obvious there:

```
Feb  7 14:57:41 |INFO| language: en 
Feb  7 14:57:41 |DEBU| RunCommand command="git --version"
Feb  7 14:57:41 |DEBU| RunCommand command="git rev-parse --git-dir"
Feb  7 14:57:41 |DEBU| RunCommand command="git rev-parse --is-bare-repository"
Feb  7 14:57:41 |INFO| starting main loop 
Feb  7 14:57:41 |INFO| Binary is not built with the buildBinary flag so we won't check for an update 
Feb  7 14:57:41 |DEBU| RunCommand command="git rev-parse --is-bare-repository"
Feb  7 14:57:41 |INFO| refreshing all scopes in async mode 
Feb  7 14:57:41 |DEBU| RunCommand command="git tag --list --sort=-creatordate"
Feb  7 14:57:41 |DEBU| RunCommand command="git stash list -z --pretty='%gs'"
Feb  7 14:57:41 |DEBU| RunCommand command="git for-each-ref --sort=-committerdate --format=\"%(HEAD)%00%(refname:short)%00%(upstream:short)%00%(upstream:track)\" refs/heads"
Feb  7 14:57:41 |DEBU| RunCommand command="git branch -r"
Feb  7 14:57:41 |DEBU| RunCommand command="git merge-base \"HEAD\" \"HEAD\"@{u}"
Feb  7 14:57:41 |DEBU| RunCommand command="git status --untracked-files=normal --porcelain -z"
Feb  7 14:57:41 |DEBU| RunCommand command="git for-each-ref --sort=-committerdate --format=\"%(HEAD)%00%(refname:short)%00%(upstream:short)%00%(upstream:track)\" refs/heads"
Feb  7 14:57:41 |DEBU| RunCommand command="git symbolic-ref --short HEAD"
Feb  7 14:57:41 |DEBU| RunCommand command="git merge-base \"HEAD\" \"master\""
Feb  7 14:57:51 |DEBU| using cache for key status.showUntrackedFiles 
Feb  7 14:57:51 |DEBU| RunCommand command="git status --untracked-files=normal --porcelain -z"
Feb  7 14:58:01 |DEBU| using cache for key status.showUntrackedFiles 
Feb  7 14:58:01 |DEBU| RunCommand command="git status --untracked-files=normal --porcelain -z"

```

**Comment by mark2185** [comment]
Could you try out a different terminal emulator? 

Have you tried opening up different `git` projects, or even running it outside of a repository?

**Comment by mark2185** [comment]
Would you be willing to build from source?

**Comment by zwn** [comment]
Attempt to do so results in

```
$ go run main.go
/home/zbynek/go/pkg/mod/github.com/mattn/go-runewidth@v0.0.14/runewidth.go:7:2: found packages uniseg (doc.go) and main (gen_breaktest.go) in /home/zbynek/go/pkg/mod/github.com/rivo/uniseg@v0.4.3
```
I have no idea what that means.

**Comment by mark2185** [comment]
Try using a different shell (`bash` etc.), maybe it's due to the shell settings.

**Comment by mark2185** [comment]
Try using a different shell (`bash` etc.), maybe it's due to the shell settings.

**Comment by zwn** [comment]
Very strange. It seems to be related somehow to my `.inputrc`. The steps that got it going:

1. move away `~/.inputrc`
2. open a new terminal
3. start `lazygit` -> it works :+1: 

I have returned my inputrc where it was but newly opened terminals still allow `lazygit` to work - only terminals opened before the charade still do not allow `lazygit` to start.

So I am afraid I am no longer able to recreate the issue, hence unable to help find the root cause.

**Comment by zwn** [comment]
Feel free to close the issue - `lazygit` is working for me. There must have been something related to `readline`/`inputrc` but it is gone now.

**Comment by mark2185** [comment]
Alrighty then!

P.S. the author can close issues as well :)
