### ISSUE TITLE
Trying to pull or something makes application crash

### ISSUE THREAD

**Issue by oprichnik** [jesseduffield/lazygit#244]
![screenshot from 2018-08-29 16-28-31](https://user-images.githubusercontent.com/6411030/44795310-a83a8e80-abaa-11e8-8426-574f335aa3f4.png)
**Describe the bug**
While using the application, if i'm taking too much time in it, the application crash (CTRL + D or CTRL C doesn't work, i have to kill the console window). When the bug occurs while in the commit message popup, A password for the remote repository is asked on the screen (like is the app was trying to pull from it)

**To Reproduce**
- Configure a repository with password authentication (not SSH one)
- Open the app
- Type "C" to enter commit message popup
- Wait some seconds until the app is unresponsive

**Screenshots**
[Screenshot](http://imagizer.imageshack.us/a/img924/230/BcHusi.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04.1
 - Lazygit Version: 0.2.1

**Comment by mjarkk** [comment]
Probably related: https://github.com/jesseduffield/lazygit/issues/145

**Comment by mjarkk** [comment]
Can confirm same issue here:
![screenshot](https://i.imgur.com/s49iYd7.png)

**Comment by jesseduffield** [comment]
I believe this is fixed on master. Feel free to leave a comment if this is not the case
