### ISSUE TITLE
Is it possible to show unstaged changes in split view rather than inline?

### ISSUE THREAD

**Issue by leanjunio** [jesseduffield/lazygit#2443]
**Topic**
When I'm browsing my tracked changes, I can use something like `ydiff` to view the changes in split but when I enter them to try and stage hunks, the unstaged changes and staged changes views turn into inline views.

Is there a way to change it to split view kind of like how it is in vs code?

**Your thoughts**
What you have to say about the topic

**Comment by mark2185** [comment]
Is this for already existing commits or for a new commit?

Would you kindly attach a screenshot to help clarify it a bit?

**Comment by leanjunio** [comment]
Hey @mark2185, thanks for the response.

This is for a new commit.

So here where I'm showing the unstaged chages, I have it using `ydiff`
![image](https://user-images.githubusercontent.com/8644699/219167187-2ca1e807-3f20-4289-aa4f-5ecd0ae2157c.png)

However, when I try to view a hunk, the display becomes inline
![image](https://user-images.githubusercontent.com/8644699/219167556-1cde62e4-b5d0-408a-83d2-96f6ee1abd29.png)

I'm trying to mimic this display
![image](https://user-images.githubusercontent.com/8644699/219168042-53b7f76e-412c-4aa3-a44e-45779d3dc54b.png)

**Comment by mark2185** [comment]
That's not what it's supposed to look like, the right panel should contain the staged changes.

Would you mind opening up a bug report?

**Comment by leanjunio** [comment]
Gotcha will do

**Comment by stefanhaller** [comment]
@mark2185 I don't see a bug here; there are no staged changes yet, so the right panel is empty.

@leanjunio The feature you are asking for (if I understand you right) is just not available in lazygit. It doesn't have a side-by-side view for showing staged and unstaged changes, like VS Code does.

**Comment by leanjunio** [comment]
> @mark2185 I don't see a bug here; there are no staged changes yet, so the right panel is empty.
> 
> @leanjunio The feature you are asking for (if I understand you right) is just not available in lazygit. It doesn't have a side-by-side view for showing staged and unstaged changes, like VS Code does.

I see. Yeah, that's exactly what I was hoping for, cool. Thanks for clarifying that.

**Comment by mark2185** [comment]
Ah, my bad, conflated the color green with 'staged'. Thanks for helping out :)

**Comment by stefanhaller** [comment]
Feel free to still file an issue; it's just not a bug, but a feature request. 😄
