### ISSUE TITLE
Error opening config file

### ISSUE THREAD

**Issue by pm-ur** [jesseduffield/lazygit#2473]
**Describe the bug**
I'm running a Debian 11 docker container in WSL2 on Windows 11. I open lazygit by opening a WSL terminal and then logging into the container via ssh. When I press 'o' to open the config file, I see the error message:
```
bash: line 1: powershell.exe: command not found
```

**To Reproduce**

1. Press 'o' to open config file when lazygit is running

**Expected behavior**
Config file should open in the currently configured editor (nano)

**Screenshots**
![image](https://user-images.githubusercontent.com/14093541/221323585-a927d3af-f286-4c8b-ba8d-7f50d8c8e443.png)

**Version info:**
commit=77093451d4f848d4ed613df90ff24104c21bd1cb, build date=2023-01-31T06:03:06Z, build source=unknown, version=77093451, os=linux, arch=amd64, git version=2.30.2

**Additional context**
I'm running a Debian 11 docker container in WSL2 on Windows 11. I use Windows terminal to open a WSL terminal (Ubuntu 20.04) and then ssh into the debian 11 docker container. Tehn I start lazygit by running the command in bash,

**Comment by humblepenguinn** [comment]
Do you run lazygit in the WSL session or in your docker session?

**Comment by pm-ur** [comment]
I open a wsl session and do 'ssh user@dockercontainer' to log into the container from a wsl prompt. I can try and post the result of a direct ssh to the container too.

**Comment by humblepenguinn** [comment]
ok, but where do you run lazygit? In the WSL session or the Docker session. You haven't answered that yet

**Comment by pm-ur** [comment]
Sorry. I thought that was implied. I run it from the container's command prompt. From the wsl prompt, I ssh into container and then I run lazygit from the prompt I get after logging into container via ssh.

**Comment by pm-ur** [comment]
So, it's like WSL terminal -> ssh into container -> lazygit

**Comment by humblepenguinn** [comment]
SSH into your container and post the output after running the command below

`cat /proc/sys/kernel/osrelease`

**Comment by pm-ur** [comment]
5.15.90.1-microsoft-standard-WSL2

**Comment by pm-ur** [comment]
> 5.15.90.1-microsoft-standard-WSL2

That's interesting... the container is Debian 11 container, but this shows WSL2 kernel!

**Comment by humblepenguinn** [comment]
> > 5.15.90.1-microsoft-standard-WSL2
> 
> That's interesting... the container is a regular Debian 11 container, but this shows WSL2 kernel! I get the same output even after I ssh directly into the container from a windows command prompt

Looks like we found the issue. I took a look at the source code and it thinks that your still running WSL. It basically reads that osrelease file and looks for the word 'microsoft' inside. 

So I'm thinking we might need to perform a check to see if we are running a docker container or entirely change the way we detect a WSL system

I'll look into the issue and hopefully get a pull request in today

**Comment by pm-ur** [comment]
👍

**Comment by humblepenguinn** [comment]
Hi, can you close this issue since its already been resolved!  Thank you

**Comment by pm-ur** [comment]
Thanks for fixing it.
