### ISSUE TITLE
Ability to hide the "Local Branches/Removes/Tags" window and expand Files window.

### ISSUE THREAD

**Issue by no-more-secrets** [jesseduffield/lazygit#2482]
**Is your feature request related to a problem? Please describe.**
The Files window is not large enough.

**Describe the solution you'd like**
Either a key binding or config option to hide the "Local Branches" window so that the Files window can fill the space that it used to occupy.

**Describe alternatives you've considered**
None.

**Comment by mark2185** [comment]
Have you tried switching to other view modes with `+` or `_` ?

**Comment by stefanhaller** [comment]
Have you tried setting `gui.expandFocusedSidePanel` to true in the config file?

**Comment by no-more-secrets** [comment]
@mark2185 @stefanhaller Thanks, those features have solved my problem.
