### ISSUE TITLE
Yank mapping (y) in Patch Options is executing the option that is currently highlighted

### ISSUE THREAD

**Issue by sungkang** [jesseduffield/lazygit#2494]
**Describe the bug**
When pressing the `y` keymap within the Patch Options, the copy to clipboard is not executed.
When navigating down to the option and pressing enter works fine.
If you press `y` on any currently highlighted option, it will execute that action instead of the copy to clipboard action.

**To Reproduce**

1. Navigate to the "Commits - Reflog" view panel.
2. Press `enter` to view the selected item's files.
3. Press `a` to add all the files of the commit to a custom patch.
4. Press `ctrl-p` to open the Patch Options modal.
5. Press `y` to copy patch to clipboard.

**Expected behavior**
I expect the "copy patch to clipboard" option to be called, but the first option it defaults to "reset patch" is called instead.

**Screenshots**

**Version info:**
commit=, build date=, build source=homebrew, version=0.37.0, os=darwin, arch=arm64, git version=2.39.2
git version 2.39.2

**Additional context**

**Note:** please try updating to the latest version or [manually building](https://github.com/jesseduffield/lazygit/#manual) the latest `master` to see if the issue still occurs.

**Comment by jesseduffield** [comment]
I can't recall where we landed on this y/n discussion. I'm still in favour of depending only on enter and escape for confirming/cancelling

**Comment by jesseduffield** [comment]
That's what I'm thinking. The more keybindings we have available for things the better

**Comment by stefanhaller** [comment]
For the record, I agree. I didn't even know that you can use `y` to confirm arbitrary prompts.

**Comment by mark2185** [comment]
Solved by #2495 .
