### ISSUE TITLE
A interesting problem: "HEAD" file will hide all commits in lazygit

### ISSUE THREAD

**Issue by tt67wq** [jesseduffield/lazygit#2498]
**Describe the bug**
lazygit show nothing in commit tab if thers's file named "HEAD" in repo.

**To Reproduce**

1. open any git repo;
2. touch HEAD;
3. run lazygit

**Expected behavior**
expect to see all history commits in commit tab, but if "HEAD" exists, there's nothing.

**Screenshots**
<img width="1508" alt="image" src="https://user-images.githubusercontent.com/12907812/224713776-646a521a-c691-4c88-9ef9-6455ac40dde2.png">

**Version info:**
commit=, build date=, build source=unknown, version=unversioned, os=darwin, arch=amd64, git version=2.39.2
git version 2.39.2

**Additional context**

**Note:** please try updating to the latest version or [manually building](https://github.com/jesseduffield/lazygit/#manual) the latest `master` to see if the issue still occurs.

**Comment by edoger** [comment]
Has the problem been fixed?

**Comment by mark2185** [comment]
It has been fixed in #2500 but it wasn't merged nor released yet (it's been less than a day), feel free to build from source until then.
