### ISSUE TITLE
Slow git pull if many files changed

### ISSUE THREAD

**Issue by engine-k2** [jesseduffield/lazygit#2503]
**Describe the bug**
If using "p" to pull newest changed from a branch, lazygit takes very long to do so if the pull involves many file changes or new files. Its very slowly printing the pull summary in the command log. If i quit out of lazygit with "q" while "it is still pulling" and do a git pull on commandline, it is already up to date which makes me think that it only takes so long to print the command log.

**To Reproduce**
- create a new repository and check it out in two different folders
- create a commit that adds round about 200 new files in one of those folders and push it
- open lazygit in the other folder and hit "p" to pull this new commit

**Expected behavior**
It should be as fast as doing git pull on commandline directly.

**Version info:**
commit=v0.37.0, build date=2023-02-01T11:17:14Z, build source=binaryRelease, version=0.37.0, os=linux, arch=amd64, git version=2.39.2

**Additional context**
I am on Manjaro plasma stable and installed lazygit via the official repositories. Manjaro plasma uses zsh in the "Konsole" terminal... if that makes a difference.

**Comment by mark2185** [comment]
[This](https://github.com/jesseduffield/lazygit/pull/2452) should fix it, feel free to build from the branch until it gets merged.
