### ISSUE TITLE
got error "support for password authentication was removed"

### ISSUE THREAD

**Issue by hopezh** [jesseduffield/lazygit#2505]
**Describe the bug**
I'm using neovim to edit a repo cloned from github. When I use lazygit to push/pull, I'm asked to provide use name and password, and after that, I get an error, saying "support for password authentication was removed", etc. 

May I ask if I have forgotten to config lazygit to allow it to access my github repos? 

**Expected behavior**
I can do push/pull for the same repo in vscode without been asked to provide use name and password. 

**Screenshots**
![2023-03-15-18-03-12](https://user-images.githubusercontent.com/23435810/225281066-361ef8bf-ea74-4e07-8cb1-67efa5f30f32.png)

**Version info:**
_Run `lazygit --version` and paste the result here_
commit=16802a048e0425182f08cf0e9a2bc31480e9a55d, build date=2023-02-01T11:02:43Z, build source=binaryRelease, version=0.37.0, os=linux, arch=amd64, git version=2.34.1

_Run `git --version` and paste the result here_
git version 2.34.1

**Comment by mark2185** [comment]
It's probably due to your `remote` being in the form of `https://github.com/hopezh/project.git` instead of `git@githib.com:hopezh/project`

Check the remotes in your cloned repo:
```
$> git remote -v
```

And change them accordingly, with `git remote set-url` - more info [here](https://devconnected.com/how-to-change-git-remote-origin/).

**Comment by hopezh** [comment]
> It's probably due to your `remote` being in the form of `https://github.com/hopezh/project.git` instead of `git@github.com:hopezh/project`
> 
> Check the remotes in your cloned repo:
> 
> ```
> $> git remote -v
> ```
> 
> And change them accordingly, with `git remote set-url` - more info [here](https://devconnected.com/how-to-change-git-remote-origin/).

Thanks, @mark2185 

I solved the issue by installing **GitHub CLI** and **caching the github credentials**.

I still don't know what caused it, because I have a very similar setup for git+neovim+lazygit in a Mac OS which doesn't have such an issue. 

The references I read are shown below:
- [Why is Git always asking for my password?](https://docs.github.com/en/get-started/getting-started-with-git/why-is-git-always-asking-for-my-password)

- [Caching your GitHub credentials in Git](https://docs.github.com/en/get-started/getting-started-with-git/caching-your-github-credentials-in-git?platform=linux)

**Comment by hopezh** [comment]
> > I solved the issue
> 
> Still curious, what does `git remote -v` output? Is it in the form of `https://blah` ?
> 
> I'd still advise to use keys given that password authentication support was removed 18 months ago.

Yes, I was using HTTPs, according to `git remote -v` as you advised. I agree with you that I should consider using the safer SSH, and allow me to take some time to understand GitHub's credential system. 

Anyway, I apologize that the issue I reported here is not related to lazygit at all. And, I thank you for your patience and generous help. (Such issue-reporting could be rejected immediately if it's on a different git repo...)
