### ISSUE TITLE
GPG destroys interface

### ISSUE THREAD

**Issue by dawidd6** [jesseduffield/lazygit#251]
**Describe the bug**
Screenshot says it all i guess.

**To Reproduce**
1. Probably have `gpgSign = true` in gitconfig
2. Stash file in lazygit
3. Observe this mess

**Expected behavior**
No output from gpg destroying interface.

**Screenshots**
![zrzut ekranu z 2018-09-01 17-36-48](https://user-images.githubusercontent.com/9713907/44947462-a15f8600-ae0d-11e8-9730-71c4764c7d7b.png)

**Desktop (please complete the following information):**
 - OS: ubuntu
 - Lazygit Version: b65fa85

It is fixed when i resize the terminal window. Can it be somehow refreshed automatically?

**Comment by dawidd6** [comment]
Similar issue: https://github.com/jesseduffield/lazygit/issues/30

PR: https://github.com/jesseduffield/lazygit/pull/133

**Comment by remyabel** [comment]
Currently the general technique is to check if GPG/a credential helper is being used and run in a subprocess. The problem is when the credentials are cached, you don't want to run it in a subprocess. So there's the much more difficult problem of detecting when there's a password prompt in general.

**Comment by m3tav3rse** [comment]
It also happens with git over ssh + passphrase
