### ISSUE TITLE
device not configured

### ISSUE THREAD

**Issue by AmelloAster** [jesseduffield/lazygit#2531]
**Describe the bug**
2023/03/31 17:36:04 An error occurred! Please create an issue at: https://github.com/jesseduffield/lazygit/issues

*fs.PathError open /dev/tty: device not configured
/home/runner/work/lazygit/lazygit/pkg/app/app.go:54 (0x102d63008)
/home/runner/work/lazygit/lazygit/pkg/app/entry_point.go:146 (0x102d64a28)
/home/runner/work/lazygit/lazygit/main.go:23 (0x102d668fc)
/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/proc.go:250 (0x1027b4cc0)
/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/asm_arm64.s:1270 (0x1027e3084)

**Comment by mark2185** [comment]
Please open up a `bug report` issue and fill out the template.
