### ISSUE TITLE
device not configured

### ISSUE THREAD

**Issue by AmelloAster** [jesseduffield/lazygit#2532]
**Describe the bug**
2023/03/31 19:56:14 An error occurred! Please create an issue at: https://github.com/jesseduffield/lazygit/issues

*fs.PathError open /dev/tty: device not configured
/home/runner/work/lazygit/lazygit/pkg/app/app.go:54 (0x100f27008)
/home/runner/work/lazygit/lazygit/pkg/app/entry_point.go:146 (0x100f28a28)
/home/runner/work/lazygit/lazygit/main.go:23 (0x100f2a8fc)
/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/proc.go:250 (0x100978cc0)
/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/asm_arm64.s:1270 (0x1009a7084)

**To Reproduce**
I updated my Mac today with the latest system update push, and lazygit is no longer available

**Expected behavior**
Normal work
**Screenshots**
<img width="910" alt="CleanShot 2023-03-31 at 19 56 32@2x" src="https://user-images.githubusercontent.com/26178326/229113809-80cb33bc-0c02-4b5c-a662-312cca4e080a.png">

**Version info:**
_Run `lazygit --version` 
commit=16802a048e0425182f08cf0e9a2bc31480e9a55d, build date=2023-02-01T11:02:43Z, build source=binaryRelease, version=0.37.0, os=darwin, arch=arm64, git version=2.37.1 (Apple Git-137.1)
_Run `git --version` 
git version 2.37.1 (Apple Git-137.1)

**Additional context**

**Note:** please try updating to the latest version or [manually building](https://github.com/jesseduffield/lazygit/#manual) the latest `master` to see if the issue still occurs.

**Comment by mark2185** [comment]
That's from a terminal like `iterm`, not from an integrated terminal like from within `IntelliJ`, right?

**Comment by AmelloAster** [comment]
> That's from a terminal like , not from an integrated terminal like from within , right?`iterm``IntelliJ`

yes, this is vscode iterm,  then I found that opening lazygit from Wrap works fine

**Comment by stefanhaller** [comment]
Are you using the VS Code Insiders build? I had the same problem with the Insiders build, starting from today. The regular VS Code release (1.77) works fine.

**Comment by AmelloAster** [comment]
> Are you using the VS Code Insiders build? I had the same problem with the Insiders build, starting from today. The regular VS Code release (1.77) works fine.

yes , I'm use VS Code Insiders build, then it looks like the vscode changes may be conflicting with lazygit

**Comment by stefanhaller** [comment]
This is now fixed in today's Insiders build. See https://github.com/microsoft/vscode/issues/178810.

@AmelloAster Please confirm and close.
