### ISSUE TITLE
Is it possible to stage a single file?

### ISSUE THREAD

**Issue by kevinrobayna** [jesseduffield/lazygit#2556]
**Topic**
Currently if i have a bunch of files that I've worked on but I only want to commit some I would need to get out of the lazygit and do `git add path/to/file` ideally I should be able to click `a` on a single file. It would also be nice to be able to add only sub parts of the git diff but I see that's somewhat complicated from what I saw on other issues (I tried to see if someone asked for this already xD)

**Comment by jesseduffield** [comment]
You can press space to stage a single file. Space is the key that is mapped to the most commonly needed action for a given panel.

**Comment by mark2185** [comment]
> It would also be nice to be able to add only sub parts of the git diff

Press `Enter` on a file and then stage individual lines using space.

I wholeheartedly recommend watching [15 lazygit features in under 15 minutes](https://m.youtube.com/watch?v=CPLdltN7wgE).

**Comment by kevinrobayna** [comment]
Thank you both!

I was hoping for it to be on the docs or something to configure but couldn't see it 😅
