### ISSUE TITLE
Cannot install on Fedora

### ISSUE THREAD

**Issue by TheDevelolper** [jesseduffield/lazygit#2559]
**Describe the bug**
Unable to install lazygit

**To Reproduce**
First I tried the dnf instructions listed on the readme including:
``` bash
$ sudo  dnf install 'dnf-command(copr)'
$ sudo dnf copr enable atim/lazygit -y
$ sudo dnf install lazygit

Last metadata expiration check: 2:22:27 ago on Wed Apr 19 08:34:46 2023.
No match for argument: lazygit
Error: Unable to find a match: lazygit
```

Then I tried installing manually: 
``` bash
 $ git clone https://github.com/jesseduffield/lazygit.git
 $ cd lazygit
 $ go install
vendor/github.com/mattn/go-runewidth/runewidth.go:7:2: //go:build comment without // +build comment
```

**Expected behavior**
Expect dnf install to work, or manual install to work in the other case. Perhaps instructions need to be updated or maybe I'm just being a total noob.

**Version info:**
N/A

**Additional context**
I am using Fedora on WSL2

**Note:** please try updating to the latest version or [manually building](https://github.com/jesseduffield/lazygit/#manual) the latest `master` to see if the issue still occurs.

Tried that again just to be sure 👍🏽

``` bash
$ git clone https://github.com/jesseduffield/lazygit.git
$ cd lazygit
$ go install
Cloning into 'lazygit'...
remote: Enumerating objects: 47688, done.
remote: Counting objects: 100% (47688/47688), done.
remote: Compressing objects: 100% (15088/15088), done.
remote: Total 47688 (delta 29813), reused 47413 (delta 29723), pack-reused 0
Receiving objects: 100% (47688/47688), 36.74 MiB | 3.49 MiB/s, done.
Resolving deltas: 100% (29813/29813), done.
vendor/github.com/mattn/go-runewidth/runewidth.go:7:2: //go:build comment without // +build comment
```

**Comment by TheDevelolper** [comment]
Okay so I did some reading and found that this is usually caused by an outdated golang installation so I went ahead and updated it. 

I was then able to run the install without any errors. 

now I get this though: 

``` terminal
❯ lazygit
bash: lazygit: command not found
```

even after running bash again

**Comment by mark2185** [comment]
If you're referring to installing it via `go install`, you need to add the folder where it's installed to your path.

It's `~/go/bin` by default, so just update your `.bashrc` with `export PATH=$HOME/go/bin:$PATH` and restart your shell.

**Comment by TheDevelolper** [comment]
Thank you, I'll give that a shot tomorrow.

**Comment by TheDevelolper** [comment]
It worked!!! Thank you so much :D
