### ISSUE TITLE
Add lazygit to the central homebrew repository 

### ISSUE THREAD

**Issue by chriscn** [jesseduffield/lazygit#256]
It would be a lot easier for end users to just run one command `brew install lazygit` and for brew to use its central repo located [here](https://github.com/Homebrew/homebrew-core/). What was the initial reason for not using the central repo and if we could migrate the Keg to that one?

**Comment by jesseduffield** [comment]
currently we're using Goreleaser for compiling/deploying which only supports pushing to a tap repository. I'm not sure how challenging it would be to integrate pushes to the main homebrew repo into CI.

Do you know how one would go about deploying to the main repo?

**Comment by glvr182** [comment]
@chriscn @jesseduffield Waking up this issue

**Comment by jesseduffield** [comment]
Yeah this feels important. I never spent more than half an hour reading up on how to do this, but I'm sure it can't be that hard. My main issue was that it couldn't easily be added to CI but a) releases aren't happening that often now anyway so maybe it's not so bad to be a manual step and b) for all I know it's not that hard to add this to CI.

I'm happy to take another look at this once the staging lines and rebasing PRs are in

**Comment by chriscn** [comment]
Sorry forgot about that, maybe when you feel that we have reached a major, stable release, manually one can build the binaries and link them on the Homebrew repo.

**Comment by jesseduffield** [comment]
This is now underway :) https://github.com/Homebrew/homebrew-core/pull/37614

**Comment by jesseduffield** [comment]
I'm not sure how easy it will be to hook up CI with version bumps in homebrew-core but I think the current version is stable enough to warrant being in the main branch

**Comment by jesseduffield** [comment]
this was done earlier in the year :)
