### ISSUE TITLE
Resize panel according to user preference

### ISSUE THREAD

**Issue by joihn** [jesseduffield/lazygit#2571]
**Is your feature request related to a problem? Please describe.**
My commits name are frequently too long to be displayed.

**Describe the solution you'd like**
A way to resize the panel (cf screenshot)
![image](https://user-images.githubusercontent.com/11663917/234202534-8d284536-e6c3-41f5-abbe-bb3df1a5246d.png)

**Describe alternatives you've considered**
"next screen mode" feature works but is a bit tedious to always go back and forth between screen mode

**Comment by mark2185** [comment]
From [the docs](https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md):
```
gui:
  sidePanelWidth: 0.3333 # number from 0 to 1
```

**Comment by joihn** [comment]
thanks ! This tool is already perfect :heart:

**Comment by kleutzinger** [comment]
![image](https://github.com/jesseduffield/lazygit/assets/6435727/af526e21-274e-48c6-a0e4-770b68e674db)

It would be cool to have this for the `half` mode as well. the `sidePanelWidth` value is ignored `half` mode
