### ISSUE TITLE
Square Brackets in Commit Messages not allowed

### ISSUE THREAD

**Issue by domsch1988** [jesseduffield/lazygit#2573]
I'm using a tag like system with Square Brackets in Commit Messages. Lazygit won't allow me to type Square or Curly Brackets. Regular Brackets work fine.
I already unset the Keybinds for the Square Brackets, but this didn't change the behavior.

**Comment by mark2185** [comment]
Please fill out the `Bug report` template, I can type in `[][][]` in my commit message.

**Comment by mark2185** [comment]
Are you using a US keyboard layout or some other?

**Comment by domsch1988** [comment]
That's interesting.
I'm using the German Keyboard Layout. Switching my OS to English(US) i can type Brackets without issues.
Not sure if it's important, but typing those brackets requires pressing Right Alt (Alt-Gr) plus Numbers 7 to 0

**Comment by mark2185** [comment]
That's what I was aiming at, the combination of `AltGr+key` is what causes it, I'm guessing.

Thanks for reporting, at least you have a workaround until it's properly fixed! :)

**Comment by adrivn** [comment]
Happens to me as well, using the Spanish (International sort) keyboard layout. Cannot input square brackets despite working normally in other editors (Neovim) / programs

**Comment by jesseduffield** [comment]
@Calvin1602 	I'm happy to accept a PR with your proposed change

**Comment by adrivn** [comment]
Hi Jesse, I don't know why but this is still not working on my machine. My keyboard layout is Spanish - International Sort (Windows 10), the keystroke for the [ ] symbols (as you can see, input is allowed as I am able to type these in here) is AltGr + the two keys to the right of "P", in the spain standard keyboard:

![Spanish Keyboard](https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/KB_Spanish.svg/1024px-KB_Spanish.svg.png)

It may be an edge case.
