### ISSUE TITLE
A possible problem with launching the expected editor

### ISSUE THREAD

**Issue by jbrains** [jesseduffield/lazygit#2576]
I'm not sure whether to call this a defect in lazygit and I'm already shaving two yaks, so I haven't taken the time to look at any production code yet. I'm curious whether someone more familiar with the project already knows what's going on.

I'm using bleeding edge lazygit. I'm in zsh and its environment has both `EDITOR` and `VISUAL` set to `$HOME/.local/bin/kak` to launch kakoune. There is no editor configuration in my lazygit configuration file.

In this situation, I'd expect lazygit to launch kakoune, but it launches vim instead. What I've figured out so far is that lazygit chooses vim by default, so I can't tell whether it's choosing vim affirmatively or falling back to vim. I presume it's falling back to vim because it guesses at the editor and fails to guess.

When I configure lazygit to use kakoune by setting `os/edit` and its cousins, lazygit correctly launches kakoune. That led me to try to contribute an editor preset for kakoune, which led me to look at the editor presets tests, and which led me to notice a possible gap in the testing and maybe even some kind of defect.

So now I'm left wondering how to inspect what lazygit is doing when I have not configured an editor in `os/edit*`. I'd like to understand this before I trying to contribute an editor preset for kakoune, move about my day, and possibly miss an opportunity to contribute another improvement to lazygit. Apart from reading the production code---I'm not yet functionally literate in go---how can I diagnose why lazygit seems to be choosing vim rather than the editor I've configured in my shell?

**Comment by jbrains** [comment]
> If you are in the staging view, then lazygit wants to call the editor with a given line number [...]

Aha! And this is why I asked. Thank you.

Even so, I'm a little more confused now. Maybe I don't understand how you're distinguishing the "file panel" from the "staging view".

I'm in the "Files" panel. I have uncommitted and unstaged changes. I press `e` on a file with unstaged changes, and then lazygit launches the fallback editor vim.

What do you mean by "the Files panel" if you don't mean what I'm describing here? What would I do in order to observe the "how it works in the Files panel" behavior?

**Comment by stefanhaller** [comment]
Yes, what you describe is the Files panel. But if you then press return, you enter the staging view for that file, and here you can move the cursor to a certain line. If you now press `e`, you jump to that same line in your editor.

**Comment by jbrains** [comment]
Excellent! I understand. In that case, lazygit is not behaving in the way that you described as your understanding/expectation.

Given:

- lazygit configuration does not specify an editor
- zsh environment specifies kakoune as both `EDITOR` and `visual`

when I press `e` in the Files panel, lazygit launches vim on that file instead of kakoune. (You seemed to expect it to launch kakoune, because it's not trying to specify a line number.)
when I press `e` in the Staging panel, lazygit launches vim on the corresponding line of that file instead of kakoune. (You seemed to expect this.)

Now I can't tell which is the case:

- I understand what's happening incorrectly.
- You have the wrong expectation.
- This is a defect in lazygit.

Whichever is the case, I'll contribute a preset for kakoune anyway, just after making coffee.

**Comment by stefanhaller** [comment]
No, you got me wrong. I did expect lazygit to call vim in both cases. I said that it _could_ call kakoune in the Files panels case (because it doesn't have to pass a line number in that case, so it would know how to do that for arbitrary editors). But it doesn't do that, and I consider this the appropriate behavior, because it would be confusing if it would call kakoune in some cases and vim in others.

**Comment by jbrains** [comment]
Indeed, when I read it again, I notice the "could" much more prominently. I believe I understand what's happening now. Thank you.
