### ISSUE TITLE
Issue when using shebang(!lazygit) from within neovim

### ISSUE THREAD

**Issue by RakshithNM** [jesseduffield/lazygit#2580]
**Describe the bug**
When I create a key mapping in neovim to launch lazygit, I get the following issue, which says "device not configured"

`*fs.PathError open /dev/tty: device not configured
/private/tmp/lazygit-20230201-4388-830qxa/lazygit-0.37.0/pkg/app/app.go:54 (0x16
842fc)
/private/tmp/lazygit-20230201-4388-830qxa/lazygit-0.37.0/pkg/app/entry_point.go:
146 (0x168622b)
/private/tmp/lazygit-20230201-4388-830qxa/lazygit-0.37.0/main.go:23 (0x168825e)
/usr/local/Cellar/go/1.19.5/libexec/src/runtime/proc.go:250 (0x1038e12)
/usr/local/Cellar/go/1.19.5/libexec/src/runtime/asm_amd64.s:1594 (0x1067b41)`

**To Reproduce**
Launching lazygit fails, in which ever way possible from neovim.

**Expected behavior**
Earlier I have used lazygit within vim8 using floaterm, but with neovim it should work out of the box.

**Version info:**
commit=, build date=, build source=homebrew, version=0.37.0, os=darwin, arch=amd64, git version=2.40.1

**Comment by mark2185** [comment]
This isn't a `lazygit` issue but a `neovim` issue, I can run `:tabnew term://lazygit` without an issue.
