### ISSUE TITLE
unknown option `empty=keep` on delete commit after upgrade to 0.38

### ISSUE THREAD

**Issue by Emkas** [jesseduffield/lazygit#2584]
**Describe the bug**
Could not delete a head commit on a current branch.

**To Reproduce**
Create a git repo, add some commit and try to delete a commit from master.

```bash
mkdir test_delete_lazygit
cd test_delete_lazygit/
git init
touch a b
git add a
git commit -m "added a"
git add b
git commit -m "added b"
```

Run lazygit and go to commit. Press d for delete.

**Expected behavior**
Deleting a commit.

**Screenshots**
![lazygit_0_38_delete_error](https://user-images.githubusercontent.com/7056309/235652748-a3ecedd5-4b33-4562-bb20-63e94f2f6f1a.png)

**Version info:**
```
lazygit --version
commit=c6c4346d4886dbfcfe3a164170f99936734febd8, build date=2023-05-01T12:30:28Z, build source=binaryRelease, version=0.38.0, os=linux, arch=amd64, git version=2.25.1
```

**Additional context**
Everything was fine for previous versions. This happens only on 0.38.0 and 0.38.1.

**Comment by Emkas** [comment]
Please let me know what other info is needed. I ran `lazygit --debug` but I see no difference.

**Comment by stefanhaller** [comment]
Do you have the option to update your git package? It's at 2.25.1 right now, which is pretty old. The `--empty=keep` option that lazygit uses is only available in git 2.26 or later.

That said, we [do have a fix](https://github.com/jesseduffield/lazygit/pull/2459/commits/5f1786d5e191bc567278ab7f14ec884d589dacf7) that checks for the git version before calling git with `--empty=keep`, but it didn't make it into the 0.38 release.

@jesseduffield Is it maybe worth doing a 0.38.2 release with that fix?

**Comment by Emkas** [comment]
Well, I'm on Ubuntu 20.04 defaults. I know to that's not the newest stable on Ubuntu, but it's not that old either :⁠-⁠) (I have to use it because of gnome version and a plugins I use).

Don't know how much effort is to upgrade to non-package git. But I can look into it.

**Comment by stefanhaller** [comment]
#2585 should fix this. I'll let @jesseduffield decide whether we need to do a 0.38.2 release, but I'm in favor.

**Comment by Emkas** [comment]
Version 0.38.2 works fine. Thank you for a fast fix!
