### ISSUE TITLE
Not detecting my config.yml

### ISSUE THREAD

**Issue by harmolipi** [jesseduffield/lazygit#2586]
**Describe the bug**
Lazygit isn't detecting my configuration in `~/.config/lazygit/config.yml` (which just contains a custom command for committing with commitizen).

I just moved my config over to a different computer, but lazygit doesn't seem to be detecting it, though it all worked fine on my previous setup. All I have is a simple custom command to commit with commitizen, but it's not showing up. I tried adding some more obvious config values to change UI colors, and indeed those don't show up either.

Is there a way to check whether the `config.yml` file is being loaded by lazygit, 

**To Reproduce**
Clone my lazygit config file from https://github.com/harmolipi/dotfiles/blob/main/lazygit/config.yml and open lazygit.

**Expected behavior**
Lazygit should have "C" set to commit with commitizen.

**Screenshots**

**Version info:**
`commit=, build date=, build source=homebrew, version=0.37.0, os=darwin, arch=arm64, git version=2.40.1`
`git version 2.40.1`

**Additional context**
I also tried adding some more obvious tweaks to the config file, like changing UI colors, but it didn't work so I don't believe lazygit is seeing the file. Also the config file's permissions are set to my current user/group and `.rw-r--r--`. Is there maybe a way to see what (if any) config file lazygit is referencing?

**Comment by stefanhaller** [comment]
On Mac the config file is in a different place than `~/.config/lazygit/config.yml`.

You don't have to remember or guess where the file is stored; from within lazygit, type `1` `e` to open it.

**Comment by harmolipi** [comment]
Silly me, that's it! Thanks for the quick reply!
