### ISSUE TITLE
Confirm Close/Quit

### ISSUE THREAD

**Issue by samburgers** [jesseduffield/lazygit#259]
Would be handy to get a "Confirm quit? Enter / Esc" modal for when you accidentally hit the `q` key. Thanks!

**Comment by jesseduffield** [comment]
I personally prefer q quitting instantly, however I see no reason to not make this a configurable user option along the lines of:
```
confirmOnQuit: yes
```

What are your thoughts on that?

**Comment by samburgers** [comment]
thats sounds ideal, thank you!

**Comment by dawidd6** [comment]
I can take it.
