### ISSUE TITLE
LazyGit is flagged as malware by Windows Security

### ISSUE THREAD

**Issue by hug0b** [jesseduffield/lazygit#2590]
**Describe the bug**
Windows 10 flags lazygit 0.38.1 as malware

`Trojan:Win32/Bearfoos.B!ml`
`This program is dangerous and executes commands from an attacker.`
`file: C:\Program Files\Lazygit\lazygit.exe`

**To Reproduce**
Install and execute lazygit 0.38.1 on Windows 10 

**Expected behavior**
Windows should not flag this program as a malware if the program isn't malicious.

**Version info:**
lazygit 0.38.1
git version 2.38.1.windows.1

**Additional context**
Reverting to version 0.37 seems to remove the security warning

**Comment by hug0b** [comment]
Continuing the investigation

## VirusTotal reports
[0.37 0/69 detections](https://www.virustotal.com/gui/file/a97525a47f0a61300d3b7a3bb8bf07b6c3c7b1175254b7a03e63e87dc98fdeeb)
[0.38 0/69 detections](https://www.virustotal.com/gui/file/04be0766b36cee58dcfaf1f4a264ffde9b509189ae3ed0c1a64466aa2074721d)
[0.38.1 1/69 detections](https://www.virustotal.com/gui/file/b38d8a541b5c869df41033acf6464ef76409e257eae4f4be47275074f5ec4508)
MaxSecure: Trojan.Malware.300983.susgen
[0.38.2 1/69 detections](https://www.virustotal.com/gui/file/21164ba5c49d06473477dfa81dd73c3cb4f83a6d5f034be51fda0f0b3bfd3f8f)
MaxSecure: Trojan.Malware.300983.susgen

Bitdefender does not seem to flag any version as a malware.

**Comment by jesseduffield** [comment]
I have no idea why it's been caught or what to do to rectify this. Does anybody have experience with Windows Security's false positives?

**Comment by Neko-Box-Coder** [comment]
See https://superuser.com/questions/1416678/my-own-backup-program-was-detected-as-win32-bearfoos-aml-virus
It might help submitting to Microsoft

**Comment by hug0b** [comment]
Closing since it seems I don't have this warning anymore

**Comment by robbyrice** [comment]
Just ran into this on a windows 11 machine with lazygit v0.54.2. The solution was to allow Windows Security to execute the file on my computer.
