### ISSUE TITLE
The help text on the commit description panel doesn't reflect the `universal.togglePanel` keybinding.

### ISSUE THREAD

**Issue by nestor-custodio** [jesseduffield/lazygit#2592]
**Describe the bug**
The 0.38.0 release added the (incredibly useful) "Commit description" panel, which includes a helpful "Press tab to toggle focus" message. This message does not actually reflect the `universal.togglePanel` keybinding, however, which is both confusing and (even worse) misleading.

**To Reproduce**

1. Rebind `universal.togglePanel` to something other than tab (I've set it to `'<f1>'` in the example below).
2. Run lazygit.
3. Attempt to commit a change.
4. Notice the "Commit description" panel's help text still indicates you should "Press tab to toggle focus".

**Expected behavior**
The help message should either:
- reflect the actual keybinding ("Press F1 to toggle focus" in my example)
- be omitted entirely (if properly representing all possible keybindings in a legible manner proves difficult)
- be changed to something more generally applicable, like "Use your 'toggle panel' key to change focus" (which is admittedly *awful* messaging, but at least is always correct)

**Screenshots**
![Screenshot 2023-05-03 11 04 01](https://user-images.githubusercontent.com/8892759/235978095-7e6a8070-e6da-40d6-8d16-0697cf6ef829.png)

**Version info:**
lazygit:
> commit=5149b24ab3dfad3860e2300519c7c583dcc8c9ff, build date=2023-05-03T08:00:22Z, build source=binaryRelease, version=0.38.2, os=linux, arch=amd64, git version=2.37.2

git:
> git version 2.37.2

**Additional context**
Verified to be an issue on 0.38.0, 0.38.1, and 0.38.2.

**Comment by stefanhaller** [comment]
Here's a PR that fixes this: #2777.
