### ISSUE TITLE
Multiline description is cut off

### ISSUE THREAD

**Issue by UrbanCMC** [jesseduffield/lazygit#2597]
**Describe the bug**
When writing a commit with a multiline description, anything after the first linebreak is cut off and not included in the created commit.

**To Reproduce**

1. Stage a changed file
2. Create a new commit with `c`
3. Write a commit message
4. Press `Tab`, write multiple lines of commit description, using `Enter` to create linebreaks
5. Press `Tab` to go back to commit message
6. Press `Enter` to create commit
7. Look at created commit in the `Commits` panel

**Expected behavior**
The created commit should have multiple lines of description. In the example below, the expected output would be:
```
Example message

Example description
spanning multiple
lines
```

**Screenshots**
![image](https://user-images.githubusercontent.com/9725089/236196908-59136a04-dca0-42cb-85f1-29c7a55e28e6.png)

**Version info:**
`commit=5149b24ab3dfad3860e2300519c7c583dcc8c9ff, build date=2023-05-03T08:00:22Z, build source=binaryRelease, version=0.38.2, os=windows, arch=amd64, git version=2.40.0.windows.1`

**Comment by mark2185** [comment]
That's odd, cannot reproduce it.

Could you post your `config.yml` and `gitconfig`? Or try it without the `config.yml` to rule that out.

**Comment by jesseduffield** [comment]
This was a windows-specific issue that is now fixed on master

**Comment by UrbanCMC** [comment]
Yes, it works just fine with the current master branch. Thank you for your work!
