### ISSUE TITLE
[question] having issue with password prompt

### ISSUE THREAD

**Issue by azinsharaf** [jesseduffield/lazygit#2600]
**Topic**
The password prompt is inaccessible when using git push. I can't type anything. 
lazygit version: 0.38.2
tried in multiple terminals, same result. Win Term, Alacritty, WSLTTY

![Screenshot 2023-05-04 103428](https://user-images.githubusercontent.com/10101468/236283830-be89ffb6-49bb-495b-a27f-7407a21d6609.png)

**Comment by mark2185** [comment]
How can you tell you cannot type anything? Have you tried inputting your password and pressing enter?

The `*` are there to hide the length of your password in case that someone is looking over your shoulder.

**Comment by jesseduffield** [comment]
Is this a new issue you're encountering? Do you know if an earlier version works for you?

**Comment by mark2185** [comment]
Okay, so just pasting the password doesn't work?

Do you maybe know the version when that worked?

**Comment by azinsharaf** [comment]
Ok, I did more test and it seems it is a clipboard issue in my temrinal because it works in alacritty not wsltty. Not a lazygit issue then.
The only thing is in `0.37.0 version` the cursor was blinking in the password prompt. Has it changed in the new release to increase security? It was good to have it blinking.
