### ISSUE TITLE
Lazygit freezing when scrolling too far to right in reflog window

### ISSUE THREAD

**Issue by rhutch117** [jesseduffield/lazygit#2609]
**Describe the bug**
When scrolling too far to the right in the reflog window, lazygit becomes unresponsive and hangs.

**To Reproduce**

1. Clone a repo
     `git clone git@github.com:jesseduffield/lazygit.git`
2. Open lazy git and navigate to the reflog window
3. Scroll to the right until you can see the whole commit message.
4. Scroll to the right one more time, lazygit will hang.

**Expected behavior**
When scrolling to the right, lazgit should remain functional, even if the user attempts to scroll to the right when at the end of commit message

**Screenshots**
<img width="533" alt="image" src="https://user-images.githubusercontent.com/16389693/236703925-2d435982-9954-4d6b-84fe-f6adc03711d5.png">

**Version info:**
commit=d1a8b05401ccda1e52215203139a252eb3be3b79, build date=2022-11-14T09:22:31Z, build source=binaryRelease, version=0.36.0, os=darwin, arch=arm64, git version=2.39.1

git version 2.39.1

**Note:** please try updating to the latest version or [manually building](https://github.com/jesseduffield/lazygit/#manual) the latest `master` to see if the issue still occurs.

**Comment by stefanhaller** [comment]
This should be fixed in 0.37. Your lazygit version (0.36) is quite old, current is 0.38.2; please update.
