### ISSUE TITLE
how can I push a commit to branch with lazygit

### ISSUE THREAD

**Issue by longway1024** [jesseduffield/lazygit#2630]
**Topic**
When I press ‘P’ for push a commit to $(BRANCH)，it always fail.
But if I press "git push origin HEAD:refs/for/$(BRANCH)" at shell, it sucessed.
How Can I push commit sucessed at lazygit?

**Your thoughts**
I don't know how can set it work at lazygit? I have no idea!
Can it set in config.yml or other way？

**Comment by Dagur** [comment]
Did you find a way to do this?
