### ISSUE TITLE
Feature not available for users using GPG happens when reword non-last commit

### ISSUE THREAD

**Issue by Tim-Cao** [jesseduffield/lazygit#2636]
**To Reproduce**

1. Set up gpg for Git commit signing
2. Access to the lazygit
3. Add a few new commits
4. Switch to the commits panel
5. Try to reword the second last commit

**Expected behavior**
It should be allowed to reword.

**Screenshots**
Feature not available for users using GPG

**Version info:**
lazygit version 0.38.2
git version 2.39.2

**Comment by MatejBransky** [comment]
I have the same issue.

**Version info:**
OS: macOS Ventura 13.3.1 (a)
lazygit version: 0.38.2
git version: 2.39.2 (Apple Git-143)

**Comment by uloco** [comment]
This also happens if you want to do changes inside the commit like deleting commits for a file completely. Don't understand why this should be forbidden.

**Comment by oliverguenther** [comment]
Do you have `git.overrideGpg` enabled in your lazygit config? With it and using 0.38.2, the warning is not shown as it short-circuits the check (here: https://github.com/jesseduffield/lazygit/blob/master/pkg/commands/git_commands/config.go#L63-L66) for gpg before this warning gets displayed: 

https://github.com/jesseduffield/lazygit/blob/master/pkg/commands/git_commands/patch.go#L155-L157
https://github.com/jesseduffield/lazygit/blob/master/pkg/commands/git_commands/rebase.go#L287-L289



Related: https://github.com/jesseduffield/lazygit/issues/1594
