### ISSUE TITLE
Add line length display to commit description field

### ISSUE THREAD

**Issue by thislooksfun** [jesseduffield/lazygit#2640]
**Is your feature request related to a problem? Please describe.**
The new split commit box is great, but I still want to enforce a hard 72-character line length limit on all my commits. Doing this inside of lazygit is hard because there's no indication of how long my line is, or how much room I still have.

**Describe the solution you'd like**
Add a display of the length of the line you're editing (like the "Commit summary" field has, but only for the line the cursor is on).

**Describe alternatives you've considered**
Another option would be to have a way to set a "maximum length" that will indicate if any line is too long, but this is more complicated as there isn't a good way to render a true editor "ruler", so the only options are:
- rendering a line where the max length is, but override it with text if you go that far
- render any text past the max length differently (bold / red / inverted / etc)
- impose a hard wrapping at the configured length (maybe even shrink the input width to match)

The second option is what I've been doing so far, which is to only edit descriptions in my `$EDITOR`, which _does_ offer a 72-char ruler.

**Additional context**
N/A

**Comment by stefanhaller** [comment]
More discussion here: #2627

**Comment by stefanhaller** [comment]
Made obsolete by #3173.
