### ISSUE TITLE
Potentially misleading menu behavior for 'space' and 'enter' keys.

### ISSUE THREAD

**Issue by gustavopcassol** [jesseduffield/lazygit#2650]
**Topic**
Pressing the 'space' or 'enter' key on the menu does not activate the corresponding entry, instead it executes the current highlighted one. This makes pressing 'space' or 'enter' in the menu behave differently from rest of the listed keys.

As an example, pressing '?' followed by 'space' on the files panel executes the command of the first menu entry, which does not 'toggle staged' as the menu indicates.

**Your thoughts**
Some ideas:
1. Use the 'right/l' key for executing the command instead. It could be complemented with 'left/h' key to close the menu or something similar.
2. I think that removing the menu entry highlighting altogether, although a little extreme, could also be worth considering. The 'up/k' and 'down/j' keys could then be used for scrolling menu up and down, and the only way to activate an command would be to press the corresponding key binding.

Since experienced users are, probably, the ones that use the menu the least, they would also be the least affected by a change in it's behavior.

**Comment by jesseduffield** [comment]
Any key that is bound to a view may also be bound to the menu, so rather than try and find a different key, or remove functionality, I've instead styled the label with a strikethrough if it's reserved for the menu: https://github.com/jesseduffield/lazygit/pull/2651.
