### ISSUE TITLE
Lazygit is not executable, in function 'termopen'

### ISSUE THREAD

**Issue by asiata25** [jesseduffield/lazygit#2657]
**Topic**
I was new to use lazyvim and got this error when I try to open lazygit by pressing `space g g`. Then a new blank window opened

**Your thoughts**
I use iTerm2, Lazyvim

`E5108: Error executing lua: Vim:E475: Invalid value for argument cmd: 'lazygit' is not executable
stack traceback:
	[C]: in function 'termopen'
	...khoir/.local/share/nvim/lazy/lazy.nvim/lua/lazy/util.lua:108: in function 'float_term'
	....local/share/nvim/lazy/LazyVim/lua/lazyvim/util/init.lua:133: in function 'float_term'
	...l/share/nvim/lazy/LazyVim/lua/lazyvim/config/keymaps.lua:115: in function <...l/share/nvim/lazy/LazyVim/lua/lazyvim/config/keymaps.lua:115>`

**Comment by mark2185** [comment]
Does `lazygit` work when you launch it from the terminal manually?

If it does, wouldn't this be a better question for the `lazyvim` project then?

**Comment by asiata25** [comment]
hmm, I think you are right. since I'm not installed from my terminal but it's included inside when I install lazyvim
