### ISSUE TITLE
Some keybinds don't work when opened outside of a git repository.

### ISSUE THREAD

**Issue by jdujava** [jesseduffield/lazygit#2658]
**Describe the bug**
Some keybinds don't initially work when `lazygit` is opened outside of a git repository.

**To Reproduce**

1. Open `lazygit` outside of a git repository.
2. Answer `n` to the prompt `Not in a git repository. Create a new git repository? (y/n):`.
3. Try out `Ctrl-r`, `h`, `l`, `D`, etc.. Nothing happens.
4. Pressing `]`, `4`, `j`, etc., has the usual effect.
5. Now even the previously non-working bindings work.

**Expected behavior**
All bindings should work from the beginning, not only after using certain other ones.

**Version info:**
_Run `lazygit --version`:_
commit=v0.38.2, build date=2023-05-03T15:21:01Z, build source=binaryRelease, version=0.38.2, os=linux, arch=amd64, git version=2.40.1
_Run `git --version`:_
git version 2.40.1

**Comment by mark2185** [comment]
On a related note, I've noticed that right after launching `lazygit` the key `l` (and possibly `h`) doesn't work unless I press `j`/`k` first, afterwards all is fine.

**Comment by jdujava** [comment]
Fixed by #2715. Thanks!
