### ISSUE TITLE
Start lazygit outside of repository

### ISSUE THREAD

**Issue by Jerakin** [jesseduffield/lazygit#2677]
**Is your feature request related to a problem? Please describe.**
I want to open lazygit without having to navigate to a repository. 

**Describe the solution you'd like**
Starting lazygit outside of a repository should open up an empty interface with the `recent repositories` open "window" open. The user can then select which repository to open (if there isn't one it should just be empty). If `esc` (or `q` as normal) is pressed quit lazy git.

**Comment by mark2185** [comment]
And what's the current behavior you are observing?

Because what you're describing _is_ the intended behavior. You can go to the status panel and press `Enter` to list the previous repos.

**Comment by Jerakin** [comment]
I get an must be inside git repo error
```
C:\Users\jerakin>lg
Error: must be run inside a git repository

C:\Users\jerakin>lg --version
Error: must be run inside a git repository
```

**Comment by mark2185** [comment]
Could you please post your config?

If you have this set, that would explain observed behaviour:
```
notARepository: 'quit'
```

**Comment by jesseduffield** [comment]
It's also possible you're on an old lazygit version

**Comment by mark2185** [comment]
@jerakin is this issue still relevant?

**Comment by Jerakin** [comment]
Updated to 0.40.2 and it behaves as you say it should
