### ISSUE TITLE
Prefix of commit not available any more since update

### ISSUE THREAD

**Issue by jefeenders** [jesseduffield/lazygit#2689]
**Description**
Since updating to 0.38.2 I do not get the commit prefix in the commit message anymore, however this was such a brilliant feature for my workflow. 

**To Reproduce**
Follow the steps in the configuration description https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md at "Predefiend commit message prefix

**Expected behavior**
I would like to have the prefix back in the commit message, maybe I have missed something between updates, then I am very sorry for opening up this issue.

**Version info:**
Lazygit: 0.38.2
Git: 2.37.1.windows.1
Windows 10

**Comment by ekans** [comment]
I have the same issue since the last release.
`commit=, build date=, build source=homebrew, version=0.38.2, os=darwin, arch=arm64, git version=2.40.1`

**Comment by jesseduffield** [comment]
This is fixed on master (by https://github.com/jesseduffield/lazygit/pull/2612) but I'm yet to cut a new release for it (I've got a separate bug I wanna fix first)

**Comment by ekans** [comment]
I confirm it's fixed in 0.39.1.
