### ISSUE TITLE
shortcuts for up and down arrows

### ISSUE THREAD

**Issue by ibeckermayer** [jesseduffield/lazygit#27]
It would be great if one could use the classic emacs/terminal shortcuts of C-n and C-p as substitutes for the up and down arrows. That way I could use lazygit without having to move my fingers too far from starting position. Another more general option would be either an interface or tutorial to allow users to change this to their desired keys.

**Comment by jesseduffield** [comment]
Yep configurable keybindings is gonna be first on my list of milestones. I'm going to list all the milestones on the readme tonight (currently at work and eager to get back to this project haha)

**Comment by fictorial** [comment]
h j k l and c-n c-p built-in might make sense

**Comment by ibeckermayer** [comment]
Yeah, C-n means “hold control and press n”

**Comment by jesseduffield** [comment]
Currently there is no possible keybinding for that supported by gocui (it only has command to my knowledge)

**Comment by p-z-l** [comment]
maybe it is possible to allow scrolling with n & p

**Comment by jesseduffield** [comment]
currently we support hjkl and we also support C-j and C-k for scrolling the main panel, so I'll close this issue and retain the one for generally supporting custom keybindings
