### ISSUE TITLE
L/R arrow keys to move panels doesn't work when lazygit is invoked in a non-git repo dir

### ISSUE THREAD

**Issue by amaanq** [jesseduffield/lazygit#2710]
**Describe the bug**

When opening lazygit in a non-git repo where it will fallback to the last git repo used (I think?), the left/right arrow keys to move panels does not work, it's totally fine in the repo itself/any git repo (easiest place to test is home, ~ ). Bisecting revealed the problem to be from commit d675117289cc195b7cae105a808a29383f48d9d4, going back to PushContext in onInitialViewsCreationForRepo fixes it.

**To Reproduce**

1. Open lazygit in non-git dir
2. Try to move panels with left/right arrow
3. Hitting another key, like up/down or anything else, THEN hitting left/right works (something to do with changed context..? Not familiar with this codebase).

**Expected behavior**

Left/Right arrow key to move panels should work right away

**Version info:**
Lazygit past d675117 will produce this
Git 2.41.0

**Additional context**

cc @stefanhaller

Bisect log:
```
git bisect start
# status: waiting for both good and bad commits
# good: [9d68b287db57b49eddf4b2b81ca1acd2e16aa5aa] Split commit message panel into commit summary and commit description panel
git bisect good 9d68b287db57b49eddf4b2b81ca1acd2e16aa5aa
# status: waiting for bad commit, 1 good commit known
# bad: [ced773ab18a116f926b2c28507d71cf283701fff] Updated README.md
git bisect bad ced773ab18a116f926b2c28507d71cf283701fff
# bad: [3cddd7cfa572e0d0983a85e28aaf1f61f28cb106] Don't keep commits that become empty during a rebase
git bisect bad 3cddd7cfa572e0d0983a85e28aaf1f61f28cb106
# bad: [5c95d231699b91bee40b505030d8c635453c2573] Merge pull request #2620 from jesseduffield/yaml
git bisect bad 5c95d231699b91bee40b505030d8c635453c2573
# good: [ee9ae8f07f493cc22059f10e04f2459c2d1d32c3] Merge pull request #2552 from stefanhaller/support-stacked-branches
git bisect good ee9ae8f07f493cc22059f10e04f2459c2d1d32c3
# bad: [d607b366cb809e821c4d5531a2f2f8abe35e5ba0] Add own version for test move_to_earlier_commit for older git versions
git bisect bad d607b366cb809e821c4d5531a2f2f8abe35e5ba0
# bad: [4160fa518c3c3c98e5139e2b446d7bb2870e7df3] Merge pull request #2582 from stefanhaller/config-for-showing-branch-heads
git bisect bad 4160fa518c3c3c98e5139e2b446d7bb2870e7df3
# bad: [c6c4346d4886dbfcfe3a164170f99936734febd8] Merge pull request #2551 from stefanhaller/fix-initial-context-activation
git bisect bad c6c4346d4886dbfcfe3a164170f99936734febd8
# bad: [d675117289cc195b7cae105a808a29383f48d9d4] Fix activation of initial context
git bisect bad d675117289cc195b7cae105a808a29383f48d9d4
# first bad commit: [d675117289cc195b7cae105a808a29383f48d9d4] Fix activation of initial context

d675117289cc195b7cae105a808a29383f48d9d4 is the first bad commit
commit d675117289cc195b7cae105a808a29383f48d9d4
Author: Stefan Haller <stefan@haller-berlin.de>
Date:   Thu Apr 13 11:13:57 2023 +0200

    Fix activation of initial context

    This broke with 40f6767cfc77; the symptom is that starting lazygit with a git
    arg (e.g. "lazygit log") wouldn't activate the requested panel correctly. While
    it would show in the expanded view, it didn't have a green frame, and keyboard
    events would go to the files panel.

 pkg/gui/gui_common.go   | 4 ++++
 pkg/gui/layout.go       | 2 +-
 pkg/gui/types/common.go | 1 +
 3 files changed, 6 insertions(+), 1 deletion(-)
 ```

**Comment by stefanhaller** [comment]
@jesseduffield OK I need help here. I debugged this a little bit, but my time budget for today is up.

What happens here is that when you start lazygit inside of a repository, you get to the code in [`onInitialViewsCreationForRepo`](https://github.com/jesseduffield/lazygit/commit/d675117289cc195b7cae105a808a29383f48d9d4#diff-922a69e96bed9c7eac522a3e4a356fd8b175f7847de50737d42a1616caf6ce4dL185) with just one context in the stack, so it will activate that and all is good.

However, when starting outside of a repo, there are two contexts on the stack, the working tree context and on top of that the recent repos menu. Calling `currentSideContext` returns the working tree context, so it activates that although the menu is on top. Not good.

Not sure how to solve it; it seems that we need to activate the current side context before opening the menu, but I don't understand the startup sequence well enough to be confident to make this change.

BTW, opening the recent repos menu on startup seems to never have worked, as far as I can see. Here's the three relevant commits that changed things about context activation again:
- 40f6767cfc
- b7c61aa883
- d675117289

and the recent repos menu didn't show up even before the first of these.

**Comment by jesseduffield** [comment]
I'm taking a look into this now

**Comment by jesseduffield** [comment]
fixed in https://github.com/jesseduffield/lazygit/pull/2715
