### ISSUE TITLE
CommitPrefixes not working

### ISSUE THREAD

**Issue by inaki6martinez** [jesseduffield/lazygit#2723]
**Describe the bug**
I am trying to add the branch name as a prefix for my commits, but for some reason it is not working. I'm triying to add fixed string and doesn't work neither.
```
git:
  commitPrefixes:
    meter_esmr5: # This is repository folder name
      pattern: "^\\w+.*"
      replace: 'bug'
```
![image](https://github.com/jesseduffield/lazygit/assets/12186402/da31ff6a-93dc-4e93-a6de-33c5139f7f1a)

**To Reproduce**

1. Add the cofiguration above
2. On a folder with a git repository execute lazygit
3. Stage changes
4. Commit them

**Expected behavior**
I expect having the prefix inserted on the commit header

**Screenshots**
![image](https://github.com/jesseduffield/lazygit/assets/12186402/d2d1a339-8eae-439c-902d-b0af396fbffc)

**Version info:**
_Run `lazygit --version` and paste the result here_
commit=88d4313970783d37f4e27354983b5313c108cd2d, build date=2023-05-02T09:01:04Z, build source=binaryRelease, version=0.38.1, os=linux, arch=amd64, git version=2.34.1
_Run `git --version` and paste the result here_
git version 2.34.1

**Additional context**

**Note:** please try updating to the latest version or [manually building](https://github.com/jesseduffield/lazygit/#manual) the latest `master` to see if the issue still occurs.

**Comment by mark2185** [comment]
Huh, the bug is not present on the latest `master`, but is present on `0.38.2`.

As a workaround until this is fixed, you could try building `lazygit` from source.
