### ISSUE TITLE
panic :runtime error: index out of range

### ISSUE THREAD

**Issue by cavapoo2** [jesseduffield/lazygit#273]
**Describe the bug**
Scrolling down the Files window with the down key. A lot of the files are marked ??. eventually it crashes

**To Reproduce**
I just cloned this repo (https://github.com/cavapoo2/eventsBoard). i then (need node and npm installed) i cd to booking_front and did `npm install`. i then open lazygit in the eventsBoard folder. 
All these files in node_modules are displayed of course. 

**Expected behavior**
Just wanted to scroll down. 

**Screenshots**

**Desktop (please complete the following information):**
ubuntu 16.04
Lazygit commit=, build date=2018-08-28, build source=unknown, version=0.2.1, os=linux, arch=amd64

**Comment by jesseduffield** [comment]
I can replicate this locally. I'm not sure what's going on, but it seems to be related to a race condition in the view's BufferLines() method in the gocui library. Is anybody able to pick this bug up?
