### ISSUE TITLE
why Chinese cannot be displayed？

### ISSUE THREAD

**Issue by strongyc** [jesseduffield/lazygit#2741]
**Describe the bug**

**To Reproduce**
![image](https://github.com/jesseduffield/lazygit/assets/51156342/84f17f31-8f96-438e-9ad8-77b5274a33c5)

why Chinese cannot be displayed？

**Version info:**
commit=de69fbd6450178ae64d80180efa64a3bed6489e6, build date=2023-06-22T17:00:41Z, build source=unknown, version=de69fbd6, os=windows, arch=amd64, git version=2.36.1.windows.11

**Comment by moreant** [comment]
我也有相同的问题，奇怪的是在 Wsl2 没有这个问题

**Comment by w4ngzhen** [comment]
Same problem. Both windows cmd and WezTerm.

**Comment by soluty** [comment]
我这里也是碰到一样的问题了,似乎就是lazygit本身的bug和终端无关, cmd,windows terminal和wezterm都有类似问题.

**Comment by Equationzhao** [comment]
😢 +1

**Comment by dragove** [comment]
I have the same problem among wezterm/cmder and windows terminal.

None-ASCII font. Font sometimes rendered but soon disappear after moving mouse.

The behavior can be found in https://github.com/wez/wezterm/issues/3705

**Comment by captainfffsama** [comment]
I have the same problem on windows terminal and git-bash...powershell have same problem

**Comment by lyj404** [comment]
I have the same problem

**Comment by zguiyang** [comment]
+ 1

**Comment by hwgao** [comment]
Version 0.37.0 doesn't have this issue.

**Comment by lyj404** [comment]
I feel like this issue has been forgotten

**Comment by godsay1983** [comment]
This is not friendly to the Chinese.

**Comment by ogios** [comment]
On Linux, I use kitty and it works fine
but when it comes to windows terminal, this problem occurred, and sometimes even broke the commit window's border

**Comment by jesseduffield** [comment]
It sounds like this issue is specific to windows. Are there other TUIs on windows that correctly render chinese characters? It would be good to find out whether this is an issue on our end or an issue with the terminal

**Comment by dragove** [comment]
> 

As a refrence, gitui works fine in windows with windows terminal

**Comment by jesseduffield** [comment]
That's good to know. So it's an issue on our end, now we just need to know where the issue comes from. We use tcell to render to the terminal, and it does have a couple open issues relating to rendering chinese characters:
https://github.com/gdamore/tcell/issues/621
https://github.com/gdamore/tcell/issues/291

**Comment by Penguin-SAMA** [comment]
I have the same problem.

If this issue can't be fixed promptly, how can I change the default display language of lazygit in Windows?

**Comment by mark2185** [comment]
@Penguin-SAMA set the language in your [`config.yml`](https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md#default), it's the `language` key.

**Comment by Penguin-SAMA** [comment]
@mark2185  After I changed the language key value to 'en', I am unable to run lazygit.

**Comment by mark2185** [comment]
Just to confirm, the `config.yml` looks something like this?
```
gui:
  language: 'en'
```

If it does look like that, could you please clarify what happens when you run `lazygit`?

**Comment by Penguin-SAMA** [comment]
Sorry, I made a mistake in my previous message. It's working fine now. Thank you for your help.

**Comment by road2coder** [comment]
@jesseduffield It seems the problems started with `v0.38.0`. `v0.37.0` works fine.

**Comment by qrsp** [comment]
[gdamore/tcell#621](https://github.com/gdamore/tcell/issues/621) has been resolved. I compiled lazygit using the updated tcell, and now Chinese characters are displayed correctly.

**Comment by stefanhaller** [comment]
That's awesome. I'll take care of bumping the tcell dependency.

**Comment by moreant** [comment]
> Could those of you who reported this problem and who are able to build from source please test if #3352 fixes the issue? Thanks!

@stefanhaller @qrsp I cloned and executed the latest code, and the issue with displaying Chinese characters has been resolved. I am deeply thankful for the contributions of both individuals.

![image](https://github.com/jesseduffield/lazygit/assets/45537528/1d94b892-6277-4bdc-bbb7-aeffe4ed0b42)
