### ISSUE TITLE
How to fold a directory in Files panel?

### ISSUE THREAD

**Issue by jiangyinzuo** [jesseduffield/lazygit#2743]
**Topic**
I have a large untracked directory and I want to fold it. What should I do? Is this feature already supported？

My lazygit version is `commit=d1a8b05401ccda1e52215203139a252eb3be3b79, build date=2022-11-14T09:22:31Z, build source=binaryRelease, version=0.36.0, os=linux, arch=amd64, git version=2.39.2`

**My thoughts**
If this feature is already supported, then it's better to add an item after `toggle file tree view` to the menu

<img width="828" alt="image" src="https://github.com/jesseduffield/lazygit/assets/40995042/6880a05e-9ee0-4885-bcc0-d954cb44ae6a">

**Comment by mark2185** [comment]
Just press `Enter` when the directory is highlighted.

Also I'd suggest adding `.cache` to the `ignorefile` by pressing `i` on it, a menu will pop up.

**Comment by jiangyinzuo** [comment]
It works. Thanks for your help!

**Comment by mark2185** [comment]
Be sure to watch the introductory video to `lazygit` - [15 lazygit features in under 15 minutes](https://www.youtube.com/watch?v=CPLdltN7wgE) :)

**Comment by crhf** [comment]
Can I collapse a folder when I'm *inside* it? just like `backspace` in nvim-tree.

**Comment by mark2185** [comment]
@crhf unfortunately that's not currently possible, but it might be a worthy addition. 

Although, I don't see any [information about a parent](https://github.com/jesseduffield/lazygit/blob/07cbb6251032720d194fec8d89dbf0d3ff7ece8e/pkg/gui/filetree/node.go#L10-L11) for the currently selected `Node` which would come in handy to know _which_ folder to fold. 

@jesseduffield thoughts? Aside from adding a `Parent` member, I don't have any other ideas. Searching upwards for the first `Directory` is undesirable IMO.

**Comment by jesseduffield** [comment]
We should allow folding a directory from within. I'm happy for the code to just search for the directory from the top level, it wouldn't be expensive to do.

**Comment by diego898** [comment]
Did this ever get added or is there a feature request tracking it? Thanks!
