### ISSUE TITLE
Fix focus issue in accordion mode

### ISSUE THREAD

**Issue by jesseduffield** [jesseduffield/lazygit#2744]
**Describe the bug**
By accordion mode I mean when we get a kind of accordion effect here:

<img width="887" alt="image" src="https://github.com/jesseduffield/lazygit/assets/8456633/669dff55-406e-4660-ae56-56df0a12070b">

Which is activated when the window is small.

The issue is that when switching between side views in compact mode, the selected line is not brought into the view. I believe this is because we're no longer calling FocusLine from within the layout function, meaning that our view hasn't been expanded by the time we try to focus the line.

This is broken on master so we can't cut another release until we fix it.

How we fix it... that is a good question. Two solutions that come to mind:
1) work out what the size of the view should be and then focus the line based on that
2) flag that we need to focus the current line and then if that flag is set within the layout function, we call FocusLine then.

**To Reproduce**
1) Open lazygit in a small window so we get the accordion
2) Select a line outside the original viewport
3) Focus the next view, and then focus the original one again
4) Observe that the selected line is not in the viewport.

**Version info:**
commit=b6a31369da3f42c1254f6d5ba0ca4e4cb79f42f7, build date=2023-06-07T07:21:03Z, build source=unknown, version=b6a31369, os=darwin, arch=amd64, git version=2.33.0

**Comment by stefanhaller** [comment]
I thought I noticed this back when I worked on #2608, and then decided it's not bad enough to do something about it.

However, now I can't reproduce it any more; whenever I switch views while the selection is outside the viewport in the target panel, it is scrolled into view correctly. Both in manual accordion mode (with `gui.expandFocusedSidePanel: true`), and "forced" accordion mode when the window is small. I don't even know which code does that 😅; have to look into this more.

Could you post a video showing the problem?

**Comment by stefanhaller** [comment]
Alright, I can reproduce it. I had tested it with a window that is only so small that the panels still show one line of content when they are collapsed (so total window height is 3); in that situation everything works. If you make it so small that each panel only shows its title bar (window height is 1), as in your screenshot, then the problem is apparent.

It's caused by a bug in gocui; the `FocusPoint` function doesn't work correctly for windows this small. The following patch fixes it for me (`ly` is -2 in the described scenario):

```diff
diff --git a/vendor/github.com/jesseduffield/gocui/view.go b/vendor/github.com/jesseduffield/gocui/view.go
index 950dab8e..57081f2f 100644
--- a/vendor/github.com/jesseduffield/gocui/view.go
+++ b/vendor/github.com/jesseduffield/gocui/view.go
@@ -269,7 +269,7 @@ func (v *View) FocusPoint(cx int, cy int) {
 	_, height := v.Size()
 
 	ly := height - 1
-	if ly == -1 {
+	if ly < 0 {
 		ly = 0
 	}
 
```

@jesseduffield Could you commit this change to gocui and bump it in lazygit? You can do this much faster than me having to fork it and make a PR.

(Alternatively, we could consider changing `Height()` so that it can never return a value less than zero. I'm not sure which fix is better.)

**Comment by jesseduffield** [comment]
First off, apologies for not getting back to your last comment.

Good work on the investigation., that patch is certainly an improvement There is still some weirdness in that if I have the cursor in the middle of a view, then focus another view and come back, the cursor is now at the top. The only way around that that I know of is to wait for the view to be enlarged before we call FocusLine(), but I'm happy for that to happen later as this issue is currently holding up a release and I think your solution is good enough to unblock us. I'm happy to apply it to gocui and bump it

**Comment by jesseduffield** [comment]
Fixed in https://github.com/jesseduffield/lazygit/pull/2792

(This fix implements the solution of enqueuing the focus-line at the end of the layout function so it's a proper fix)
