### ISSUE TITLE
When trying to open a pull request it seems lazy git needs xdg-open package which isn't safe

### ISSUE THREAD

**Issue by wakywayne** [jesseduffield/lazygit#2757]
**Describe the bug**
When trying to open a pull request it seems lazy git needs xdg-open package if you view the unbuntu docs [here](https://manpages.ubuntu.com/manpages/focal/man1/xdg-open.1.html#:~:text=xdg%2Dopen%20opens%20a%20file,ftp%2C%20http%20and%20https%20URLs.) it says: *xdg-open is for use inside a desktop session only. It is __not__ recommended to use xdg-open as root.* I feel like I would need to install this package as root to use with WSL Unbuntu. Isn't this dangerous? If not can someone tell me how I should go about installing this package for lazygit.

**To Reproduce**

1. open lazygit on a wsl Unbuntu neovim project 
2. go to branch and click o
3.  see error message requiring xdg-open

**Expected behavior**
A pull request to be open without error

**Version**
commit=5149b24ab3dfad3860e2300519c7c583dcc8c9ff, 
build date=2023-05-03T08:00:22Z, 
build source=binaryRelease, version=0.38.2, 
os=linux, arch=amd64, 
git version=2.34.1

**Additional context**
to do a pull request from the cli I am using wslview which comes with the wslu package. Can I use this instead?

**Comment by shinhs0506** [comment]
should be opening links with powershell after #1997, seems like there is a bug with [this function](https://github.com/jesseduffield/lazygit/blob/585ea361f6703526038f50cddf4e1f050fe0c3d0/pkg/config/config_linux.go#L14-L26) from #2486

**Comment by wakywayne** [comment]
I am using WSL, but I am definitely not good enough to be using docker lol. Are you saying lazy git isn't supposed to need xdg-open

**Comment by wakywayne** [comment]
Also if I try to go to the link he lists it seems whatever it was is crashed

**Comment by jasonquigleyhpecom** [comment]
Install `wslview` and `sudo ln -s $(which wslview) /usr/local/bin/xdg-open`
