### ISSUE TITLE
Edit opens an empty file

### ISSUE THREAD

**Issue by CCurl** [jesseduffield/lazygit#2762]
**Describe the bug**
I have neovim on my system (nvim), not vim.
So I have created a batch file named vim with the following contents:
-------------
@echo off
nvim %1
-------------

**To Reproduce**
When I press 'e' on the file in lazygit, an empty nvim window opens.

**Comment by geomorillo** [comment]
Y dont use vim nor neovim i should be nice if you can configure a custom editor
