### ISSUE TITLE
Cannot install on Debian

### ISSUE THREAD

**Issue by CCurl** [jesseduffield/lazygit#2763]
I have been unable to install lazygit on my Debian 12 system.

I tried following the instructions for Ubuntu, and also those in this issue:

https://github.com/jesseduffield/lazygit/issues/330

I get errors in both cases. Please advise.

**Comment by mark2185** [comment]
Could you please share what errors do you get?

**Comment by CCurl** [comment]
the Ubuntu error(s):
chris@ccc-laptop:~$ sudo add-apt-repository ppa:lazygit-team/daily
Traceback (most recent call last):
  File "/usr/bin/add-apt-repository", line 362, in <module>
    sys.exit(0 if addaptrepo.main() else 1)
                  ^^^^^^^^^^^^^^^^^
  File "/usr/bin/add-apt-repository", line 345, in main
    shortcut = handler(source, **shortcut_params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/softwareproperties/shortcuts.py", line 40, in shortcut_handler
    return handler(shortcut, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 86, in __init__
    if self.lpppa.publish_debug_symbols:
       ^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 126, in lpppa
    self._lpppa = self.lpteam.getPPAByName(name=self.ppaname)
                  ^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 113, in lpteam
    self._lpteam = self.lp.people(self.teamname)
                   ^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'people'

**Comment by CCurl** [comment]
The error from trying what the other issue said to try ... just a seg fault

chris@ccc-laptop:~$ sudo install lazygit /usr/bin
chris@ccc-laptop:~$ lazygit
Segmentation fault (core dumped)

**Comment by mark2185** [comment]
My advice would be to use the binary from [the latest release](https://github.com/jesseduffield/lazygit/releases/tag/v0.38.2) and putting it in your path, until a proper `ubuntu/debian` solution is in place.

**Comment by dariogriffo** [comment]
I'm packaging lazygit into Debian packages 
https://github.com/dariogriffo/lazygit-debian
