### ISSUE TITLE
Potential memory leak on windows during long running sessions

### ISSUE THREAD

**Issue by Renerick** [jesseduffield/lazygit#2766]
**Describe the bug**
I noticed a warning in Windows Event Viewer with the following message

> Windows successfully diagnosed a low virtual memory condition. The following programs consumed the most virtual memory: lazygit.exe (4224) consumed 120276787200 bytes...

This is more then 120 GB

**To Reproduce**

I'm not sure how to reproduce this reliably but from my observations this happens when I leave lazygit running for a long time

**Expected behavior**
No memory leaks

**Screenshots**
N/A

**Version info:**
```
lazygit --version
commit=5149b24ab3dfad3860e2300519c7c583dcc8c9ff, build date=2023-05-03T08:00:22Z, build source=binaryRelease, version=0.38.2, os=windows, arch=amd64, git version=2.41.0.windows.1
git --version
git version 2.41.0.windows.1
```

**Additional context**
I noticed that sometimes windows kills a lot of background processes and decided to investigate the event log, that's how I found it

**Note:** please try updating to the latest version or [manually building](https://github.com/jesseduffield/lazygit/#manual) the latest `master` to see if the issue still occurs.

**Comment by stefanhaller** [comment]
Looks like the same as #2460. (Which I have never been able to reproduce.)

**Comment by Renerick** [comment]
Yes, this appears to be the case. I'll close this issue then and follow the original
