### ISSUE TITLE
View filtering: pressing `<esc>` exits whole `Keybindings` instead of just filter mode

### ISSUE THREAD

**Issue by jdujava** [jesseduffield/lazygit#2802]
**Describe the bug**
When trying to exit filter mode in `Keybindings` (or `Recent repositories`) using `<esc>` (as the "tooltip" at the bottom suggests), the whole view is closed instead of just the filter mode.

**To Reproduce**
1. Open for example `Keybindings` via `?`.
2. Start filtering with `/`, enter and accept some filter pattern.
3. There is a tooltip at the bottom: _\<esc\>: Exit filter mode_
4. Pressing `<esc>` exits the `Keybindings` view, not just the filter mode

**Screenshots**
![2023-07-20_13-59](https://github.com/jesseduffield/lazygit/assets/19737748/51efb0b2-5c39-498c-89d1-d4f05354ed2a)

**Version info:**
```
$ lazygit --version 
commit=1f920ae6b, build date=20230720.112057, build source=unknown, version=pre-release-0.39-2.1f920ae6b, os=linux, arch=amd64, git version=2.41.0
```

**Comment by jesseduffield** [comment]
Ah damnit and right after cutting a new release! haha. Alright we'll need to push a fix for this soon
