### ISSUE TITLE
Interactive Addition of Files to .gitignore: A Feature Request 

### ISSUE THREAD

**Issue by EliorEstrin** [jesseduffield/lazygit#2815]
## Is your feature request related to a problem? Please describe.

Yes, my request is based on a recurring inconvenience. I frequently find myself needing to add files to .gitignore, and I find the process quite tedious when having to run a command like `echo 'report.json' >> .gitignore` every time I need to ignore a file.

## Describe the solution you'd like
I would like to have an interactive method of adding files to .gitignore. Ideally, this could be integrated into the Git client I'm using, where an option to ignore a file is available whenever a file is selected. This would automatically add the file to .gitignore.

## Describe alternatives you've considered
One alternative I've considered is writing a custom script to handle this task.

**Comment by jesseduffield** [comment]
The 'i' keybinding already does this :)

**Comment by EliorEstrin** [comment]
That is absolutely amazing!
