### ISSUE TITLE
Filtered view doesn't update when underlying model changes

### ISSUE THREAD

**Issue by stefanhaller** [jesseduffield/lazygit#2816]
It seems that the filtered view remembers indices into the model of the items that it should display. If the model changes, these are not updated, so the wrong items are shown.

There are probably many variations of situations in which this happens, but the two most common ones that I have run into are:

### Checking out a filtered branch
1. Press `/` and filter the list of branches down so that only a single branch is shown (which is not the current one)
2. Press space to check out this branch
3. Expected: the same branch should still be displayed in the filtered list; actual: an arbitrary different one is displayed instead

### Deleting a filtered branch
1. Filter the list of branches down so that three branches are shown
2. Select one of these and press `d` to delete it
3. Expected: only two branches should be displayed now; actual: it still shows three branches, and (depending on the order of the branches) totally arbitrary ones

**Version info:**
commit=a30537a4da5e6633135f9a7f423a5b23b14d9797, build date=2023-07-21T15:58:51Z, build source=unknown, version=a30537a4, os=darwin, arch=arm64, git version=2.41.0.49.g2c35e38aee

**Comment by jesseduffield** [comment]
I've seen this too. Annoying indeed.

**Comment by vlad-psh** [comment]
> Expected: the same branch should still be displayed in the filtered list; actual: an arbitrary different one is displayed instead

It's actually not the "arbitrary" branch displayed, but the branches with previous index positions.

Eg, if you have 10 branches, and filtering displays only 3rd, 5th and 7th, if you checkout 5th, it becomes number one in the list and all other branches (with indexes lower than checked out branch) will be shifted.
 
| available branches | displayed after filtering | index list after 5th branch checked out | filtered list after checkout |
| ---- | ----- | ----- | ---- |
| branch#1<br>branch#2<br>branch#3<br>branch#4<br>branch#5<br>branch#6<br>branch#7<br>branch#8<br>branch#9<br>branch#10 | -<br>-<br>branch#3<br>-<br>branch#5<br>-<br>branch#7<br>-<br>-<br>- | branch#5<br>branch#1<br>branch#2<br>branch#3<br>branch#4<br>branch#6<br>branch#7<br>branch#8<br>branch#9<br>branch#10 | -<br>-<br>branch#2<br>-<br>branch#4<br>-<br>branch#7<br>-<br>-<br>- |

Would be nice to see this fixed

I guess just re-applying current filter automatically after all list-reordering-actions should do the trick.
