### ISSUE TITLE
Sort order of filtered items is not stable

### ISSUE THREAD

**Issue by stefanhaller** [jesseduffield/lazygit#2817]
When filtering branches, I expect the filtered items to be shown in the same order in which they appear in the unfiltered list. This is not always the case. I haven't been able to work out what's going on, but sometimes two adjacent filtered items swap their place as I type another character. Can try to come up with a reproducible case if needed.

**Version info:**
commit=a30537a4da5e6633135f9a7f423a5b23b14d9797, build date=2023-07-21T15:58:51Z, build source=unknown, version=a30537a4, os=darwin, arch=arm64, git version=2.41.0.49.g2c35e38aee

**Comment by jesseduffield** [comment]
That would be thanks to the recently-merged https://github.com/jesseduffield/lazygit/pull/2808. With the fuzzy filter approach, given that there are going to be more matches than an exact filter, and of varying quality, we show the best match first.

I think showing the best match first is more desirable than retaining the original order, but I'm open to persuasion.

**Comment by stefanhaller** [comment]
Ah I see. I agree that it makes sense to put the best match first.
