### ISSUE TITLE
Incorrect display of some keybindings

### ISSUE THREAD

**Issue by pereBohigas** [jesseduffield/lazygit#2819]
**Describe the bug**
When keybindings are displayed, `<space>`, `<enter>` and `/` are being shown strike through and not with the proper color

**To Reproduce**

1. Go to any panel
2. Click on `?`
3. Scroll down to any of the mentioned keybindings

**Expected behavior**
The keybindings should be shown with the proper color and format

**Screenshots**
![bug_report](https://github.com/jesseduffield/lazygit/assets/38757307/a423f8c6-6414-4a33-9fce-d89273f36545)

**Version info:**
- **lazygit**
`commit=, build date=, build source=homebrew, version=0.39.3, os=darwin, arch=arm64, git version=2.41.0`

- **git**
`git version 2.41.0`

**Comment by jesseduffield** [comment]
The intention behind striking through enter and space is to tell you that you can't invoke the menu item with that keybinding, because the keybinding is reserved for invoking the currently selected menu item. As for '/', I'm not sure why that's struck-through, perhaps you've rebound that as a confirmation key?

**Comment by rholak** [comment]
The `/` keybinding is also formatted with the strikethrough on mine (version 0.40.2) on a completely fresh install with no customizations. The filter functions correctly in the help view even though the bind is marked with the strike.

**Comment by jesseduffield** [comment]
@rholak thats because the keybinding in the menu refers to filtering the original panel rather than the menu panel

**Comment by rholak** [comment]
@jesseduffield Thank you;  that makes sense now. 
I suggest adding this formatting convention as a FAQ entry  - I got some co-workers to start using lazygit as well, and they were also wondering why some of the items in the keybindings screen were crossed out.

**Comment by stefanhaller** [comment]
I'd rather suggest to not strike them out, since it seems to cause more confusion than it helps.

See #3365.
