### ISSUE TITLE
Bisect good/bad: current or selected commit?

### ISSUE THREAD

**Issue by stefanhaller** [jesseduffield/lazygit#2836]
When I'm in the middle of a bisect, and I want to mark a commit as good or bad, I always want to mark the _current_ commit. Not the selected commit. In 100% of the cases.

There are two common reasons for me why the current commit is not the selected one: 
- I moved around a bit (a few commits up/down) to see if I can quickly spot the bad commit myself, without having to continue the bisect. Then I forget to move the selection back to the current commit.
- I quit and restart lazygit. It doesn't select the current commit in this case (might be nice if it did).

Typing `b b` or `b g` in these cases doesn't do what I want, and I managed to confuse myself badly several times because of this. I expect these to behave as if I typed `git bisect good` or `git bisect bad` on the command line.

I noticed the following comment in the source code:
```
	// Originally we were allowing the user to, from the bisect menu, select whether
	// they were talking about the selected commit or the current bisect commit,
	// and that was a bit confusing (and required extra keypresses).
```

I couldn't find any PR where this was discussed; blaming this comment, it looks like it was there from the beginning (4ab5e5413944), so I'm not sure what the "Originally" is referring to.

My proposal is to change the behavior to unconditionally work on the current commit instead of the selected one; I claim that this is what everybody expects/wants. Alternatively, if this is deemed too much of a change, we could show a menu like this:
```
  b Mark current commit (deadbeef) as bad
  g Mark current commit (deadbeef) as good
  B Mark selected commit (fa1afe1) as bad
  G Mark selected commit (fa1afe1) as good
  s Skip current commit (deadbeef) 
  r Reset bisect
    Cancel
```

We would include the 3rd and 4th menu entries only when the selected commit is not the current one, so for the typical usage nothing would change.

**Comment by stefanhaller** [comment]
Oops, found this discussion meanwhile: https://github.com/jesseduffield/lazygit/pull/1704#issuecomment-1018969351

Doesn't change anything for me though...

**Comment by stefanhaller** [comment]
OK, after re-reading the discussion in #1704, it seems that you want the ability to _skip_ a selected commit that is not the current one. This makes sense to me, but I still think that marking selected (non-current) commits as good/bad doesn't.

So the menu would have to look something like this then:
```
  b Mark current commit (deadbeef) as bad
  g Mark current commit (deadbeef) as good
  s Skip current commit (deadbeef) 
  S Skip selected commit (fa1afe1) 
  r Reset bisect
    Cancel
```

Again, the `S` entry would only appear when the selected commit is not the current one.

Thoughts?

**Comment by jesseduffield** [comment]
I'm happy with that. I never need to mark the non-current commit as good/bad either. If somebody out there does have that use case, we can add additional menu items for that (after they raise an issue for it)

**Comment by stefanhaller** [comment]
OK cool. Here's the PR: #2837.

(And a slightly related one, just because it's also about bisecting: #2838)
