### ISSUE TITLE
But why though

### ISSUE THREAD

**Issue by Nllii** [jesseduffield/lazygit#2855]
[but why](https://m.youtube.com/watch?v=PEZWYXPvmS8)

![image](https://github.com/jesseduffield/lazygit/assets/5082827/771a4643-6259-4947-939c-ae37375b96b7)

![image](https://github.com/jesseduffield/lazygit/assets/5082827/96597a8e-2215-4d4c-874d-c659247ea6c6)

Don't get me wrong. This is great project. But why though?

**Comment by jesseduffield** [comment]
Do not ask why my brother, ask 'why not'. Go now, and spread the word of what you heard here today.
