### ISSUE TITLE
Color format described in an unclear way

### ISSUE THREAD

**Issue by EmilyGraceSeville7cf** [jesseduffield/lazygit#2858]
**Topic**
It's not written how to list several attributes: via comma, dash or in another way?

> For color attributes you can choose an array of attributes (with max one color attribute)
> The available attributes are:
> 
> **Colors**
> 
> - black
> - red
> - green
> - yellow
> - blue
> - magenta
> - cyan
> - white
> - '#ff00ff'
> 
> **Modifiers**
> 
> - bold
> - default
> - reverse # useful for high-contrast
> - underline
> - strikethrough

It's important to understand to define the right JSON schema for config.

**Comment by jesseduffield** [comment]
They're an array, for example:
```yml
  theme:
    activeBorderColor:
      - green
      - bold
```

**Comment by EmilySeville7cfg** [comment]
Ah, thanks. :) Got it.
