### ISSUE TITLE
Crash: failed to get worktree git dir path for bare repository

### ISSUE THREAD

**Issue by jdujava** [jesseduffield/lazygit#2880]
**Describe the bug**
I have a similar bare repository workflow for dotfiles as discussed in #1201.

However, after the commit https://github.com/jesseduffield/lazygit/commit/b73efb2c22bfe587b58210da8f130469430066ed (found via `git bisect`), executing
`lazygit -ucd ~/.config/lazygit/barerepo --git-dir=$HOME/.config/baredots/
--work-tree=$HOME`
results in a crash.

**Crash log**
```
$ lazygit -ucd ~/.config/lazygit/barerepo --git-dir=$HOME/.config/baredots/ --work-tree=$HOME
2023/08/05 14:25:24 An error occurred! Please create an issue at: https://github.com/jesseduffield/lazygit/issues

*errors.errorString Error getting repo paths: failed to get worktree git dir path: stat /home/<my_username>/.git: no such file or directory
/home/jonas/.cache/paru/clone/lazygit-git/src/src/github.com/jesseduffield/lazygit/pkg/commands/git.go:100 (0x9bd47a)
/home/jonas/.cache/paru/clone/lazygit-git/src/src/github.com/jesseduffield/lazygit/pkg/gui/gui.go:271 (0xaf04f4)
/home/jonas/.cache/paru/clone/lazygit-git/src/src/github.com/jesseduffield/lazygit/pkg/gui/gui.go:656 (0xaf3098)
/home/jonas/.cache/paru/clone/lazygit-git/src/src/github.com/jesseduffield/lazygit/pkg/gui/gui.go:675 (0xaf36ac)
/home/jonas/.cache/paru/clone/lazygit-git/src/src/github.com/jesseduffield/lazygit/pkg/utils/utils.go:108 (0x82de67)
/home/jonas/.cache/paru/clone/lazygit-git/src/src/github.com/jesseduffield/lazygit/pkg/gui/gui.go:674 (0xaf35f4)
/home/jonas/.cache/paru/clone/lazygit-git/src/src/github.com/jesseduffield/lazygit/pkg/app/app.go:263 (0xb1d8e9)
/home/jonas/.cache/paru/clone/lazygit-git/src/src/github.com/jesseduffield/lazygit/pkg/app/app.go:48 (0xb1d87e)
/home/jonas/.cache/paru/clone/lazygit-git/src/src/github.com/jesseduffield/lazygit/pkg/app/entry_point.go:154 (0xb1fb46)
/home/jonas/.cache/paru/clone/lazygit-git/src/src/github.com/jesseduffield/lazygit/main.go:23 (0xb213de)
/usr/lib/go/src/runtime/internal/atomic/types.go:194 (0x439767)
    (*Uint32).Load: return Load(&u.value)
/usr/lib/go/src/runtime/asm_amd64.s:1598 (0x469b01)
    goexit: BYTE    $0x90   // NOP
```

**Version info:**
```sh
$ lazygit --version
commit=c390c9d58, build date=20230803.223825, build source=unknown, version=v0.39.4.c390c9d58, os=linux, arch=amd64, git version=2.41.0
```

**Comment by jesseduffield** [comment]
Just to confirm: your $HOME is `/home/<my_username>`? Is there a .git file in that directory. afaik there should be if that's a worktree

**Comment by ngocphamm** [comment]
I am seeing the same behavior with new version `0.40`. I follow this for the dotfile management. https://www.atlassian.com/git/tutorials/dotfiles

It worked fine with previous versions of lazygit 🤔 

In my case my worktree is `$HOME`, and the git folder is `$HOME/.myconfig`.

**Comment by jdujava** [comment]
Yes, I just substituted my `$HOME` with `/home/<my_username>` in the crash log. There is no `.git` file in my home directory.
My bare dotfiles git repository is `$HOME/.config/baredots/`.

As @ngocphamm mentioned, this worked fine before, but I am not sure if there *should* be a `.git` file.

**Comment by snelling-a** [comment]
same error message, but only in a submodule or when switching to a submodule from the main project

**Comment by jesseduffield** [comment]
I think I've misunderstood the possible kinds of worktree that a repo can have. I can't find anything about this online but here's what I currently think is the case: there are three kinds of worktree:
* main worktree of a non-bare repo
* linked worktree of a bare or non-bare repo, with its own .git file pointing to its git dir in the repo's worktrees/ folder
* random folder (e.g. $HOME for dotfiles) that you treat as the worktree based on the --work-tree command.

It's that last case which the new code doesn't appreciate.

This begs the question: is the --work-tree arg only intended for the third case? It did confuse me how it seemed useless for specifying a linked worktree.

**Comment by robsonpeixoto** [comment]
I'm using lazygit only to read the log, and after version `0.40.0` is not working anymore:

```
lazygit -g $HOME/.dotfiles/ -w $HOME log

*errors.errorString Error getting repo paths: failed to get worktree git dir path: stat /home/<my_user>/.git: no such file or directory
github.com/jesseduffield/lazygit/pkg/commands/git.go:100 (0x9bd51a)
github.com/jesseduffield/lazygit/pkg/gui/gui.go:271 (0xaf0714)
github.com/jesseduffield/lazygit/pkg/gui/gui.go:656 (0xaf32b8)
github.com/jesseduffield/lazygit/pkg/gui/gui.go:675 (0xaf38cc)
github.com/jesseduffield/lazygit/pkg/utils/utils.go:108 (0x82df07)
github.com/jesseduffield/lazygit/pkg/gui/gui.go:674 (0xaf3814)
github.com/jesseduffield/lazygit/pkg/app/app.go:263 (0xb1db09)
github.com/jesseduffield/lazygit/pkg/app/app.go:48 (0xb1da9e)
github.com/jesseduffield/lazygit/pkg/app/entry_point.go:154 (0xb1fd66)
github.com/jesseduffield/lazygit/main.go:23 (0xb215fe)
runtime/internal/atomic/types.go:194 (0x439807)
runtime/asm_amd64.s:1598 (0x469ba1)

```

**Comment by jesseduffield** [comment]
Fixed by https://github.com/jesseduffield/lazygit/pull/2902
