### ISSUE TITLE
Organise keybindings menu items under headings

### ISSUE THREAD

**Issue by jesseduffield** [jesseduffield/lazygit#2890]
**Is your feature request related to a problem? Please describe.**
Our keybindings menu is quite disorganised. It would benefit from some headings. For example we should have a 'Commit' heading in the files view for
* Commit changes
* Amend last commit
* Commit changes using git editor
* Commit changes without pre-commit hook

When filtering, we would remove the headings

When iterating through the list, the cursor will need to skip headings.
When clicking on a heading, the cursor should not be moved (or it should be moved to the first item under the heading, whichever is easiest).

**Describe alternatives you've considered**
None

**Comment by jesseduffield** [comment]
Yep I thought about that exact use case. Roughly: I was thinking of having the view model store a mapping from original index to the index in the view, so that we don't need the headings to exist at the model level

**Comment by stefanhaller** [comment]
OK, that's the "Disregarding the question..." part, I wasn't asking about that here. 😄 

My question is, for any list view that wants to display section headers (no matter what its model is), how do we solve the problem that section headers are not a slice of n columns? `RenderDisplayStrings` assumes this right now.

**Comment by jesseduffield** [comment]
Whoops my bad for skimming your comment!

I don't think the display strings issue is necessarily a problem: we would use a function that takes an item index and returns the header, so the displaystrings thing can be handled separately. The actual rendering part will need to change

**Comment by jesseduffield** [comment]
To expound a bit more: you could get the display strings in one step and separately get the headers and their corresponding index ranges in another step, and then mash it all together in another step.

**Comment by stefanhaller** [comment]
OK, I think I have a bit more clarity now. We should leave `RenderDisplayStrings`/`getDisplayStrings` the way they are, and only insert the section headers afterwards, as you suggested. Also, ListCursor's selectedIdx should be a model index, not a view index. The only two remaining places that need to know about the model-index-to-view-index mapping are `ListController.HandleClick` (converts from view index to model index), and `ListContextTrait.FocusLine` (the other way). All other code simply keeps working with model indices as before.

This also nicely solves the problem that section headers should not be selectable, and that down-arrowing should skip past them. (Of course, if we ever *do* want them to be selectable, e.g. for hitting return to collaps/expand them, then we have a problem.)

I'm out of energy for today, but I could try this approach tomorrow if you think it's the right direction.

**Comment by jesseduffield** [comment]
Nice work, yep I think that's the right direction.

I agree about the expand/collapse thing. I can't prove it, but I have an intuition that if we implement this now such that headers can't be selected, it won't be too hard down the line to make them selectable/collapsible.

**Comment by stefanhaller** [comment]
Made good progress today, I hope to have something to look at tomorrow.

One problem I ran into: when filtering, menu items are sorted by best match, so sections are out of order. We could either hide the section headers as soon as we are filtering, or sort the filtered items by section again. Any preference?

**Comment by jesseduffield** [comment]
Nice! Let's hide the sections when filtering

**Comment by jesseduffield** [comment]
I'm happy with how the keybindings menu is now so I'm gonna close this. If we ever want to break the keybindings menu down into smaller sections we can raise another issue
