### ISSUE TITLE
`S` Squash all 'fixup!' commites above selected commit (autosquash) doesn't do anything

### ISSUE THREAD

**Issue by tkuraku** [jesseduffield/lazygit#2905]
**Describe the bug**
`S` Squash all 'fixup!' commites above selected commit (autosquash) doesn't do anything.
`s` Squash down has the expected behavior

**To Reproduce**

1. clone <https://gitlab.com/tkuraku/a>
2.  highlight commit 1, 2, or 3 and press `S` to squash all commits above the selected commit
3. Nothing Happens

**Version info:**
0.40.2

**Comment by stefanhaller** [comment]
You are mistaken as to what a 'fixup!' commit is, or what squashing all 'fixup!' commits means.

Read up about the concept of fixup commits here: https://riptutorial.com/git/example/3935/autosquash--committing-code-you-want-to-squash-during-a-rebase

Lazygit's `S` command is equivalent to `git rebase --autosquash` on the command line, i.e. it doesn't squash *all* commits as you apparently expected.

**Comment by tkuraku** [comment]
Got it. thanks for the clarification
