### ISSUE TITLE
Chinese translation key wrong in docs

### ISSUE THREAD

**Issue by Lutra-Fs** [jesseduffield/lazygit#2913]
**Describe the bug**
After traditional Chinese translation introduced to the project, the translation key for Chinese is now zh-CN(Simplified Chinese) or zh-TW(Traditional Chinese) instead of zh. Old 'zh' key doesn't work anymore.

**To Reproduce**

1. Go to 'config.yml'
2. Set the language key to 'zh'
3. Start lazygit
4. Lazygit returns "language not found"

**Expected behavior**
Load Chinese translation

**Screenshots**

**Version info:**
_Run `lazygit --version` and paste the result here_
_Run `git --version` and paste the result here_

**Additional context**
There is a PR #2842 relates to that.

**Note:** please try updating to the latest version or [manually building](https://github.com/jesseduffield/lazygit/#manual) the latest `master` to see if the issue still occurs.

**Comment by lucky51** [comment]
I set up language: 'zh-CN'  for `config.yml` on windows11  .lazygit can run but show below.

![1692262959267](https://github.com/jesseduffield/lazygit/assets/27793729/34f82d91-c3f0-4d57-af9d-2eb522a1cc2b)
