### ISSUE TITLE
Used in iterm2, the layout throws an exception

### ISSUE THREAD

**Issue by zguiyang** [jesseduffield/lazygit#2917]
**Describe the bug**
Install the latest version of lazygit on macos using Homebrew, then use lazygit and the layout appears abnormal as shown here

**To Reproduce**
1. Install lazygit
2. Run lazygit 

**Expected behavior**
Layout is uncluttered, with clear boundaries between modules

**Screenshots**
Normal
![image](https://github.com/jesseduffield/lazygit/assets/24975063/161790ce-2d62-4075-943c-48f98ab2205e)

Exceptions
![image](https://github.com/jesseduffield/lazygit/assets/24975063/f76ce925-abcf-4829-a3f8-34820087ebc3)
**Version info:**
`lazygit`
commit=5e388e21c8ca6aa883dbcbe45c47f6fdd5116815, build date=2023-08-07T14:05:48Z, build source=binaryRelease, version=0.40.2, os=darwin, arch=amd64, git version=2.39.1

`git` 
git version 2.39.1

**Additional context**
iTerm2 3.4.19
Macos 13.5

**Comment by jesseduffield** [comment]
I use iterm2 myself and don't have this issue. Could you try out another font to see if that's the cause of the issue?
