### ISSUE TITLE
Crash on Shift+Tab

### ISSUE THREAD

**Issue by mia0x75** [jesseduffield/lazygit#292]
Latest git version on Fedora 28 x86_64.

**Comment by jmkim** [comment]
Also happening with latest git version (7b90d24) on Debian `sid` `amd64`.

**Comment by remyabel** [comment]
This is a [termbox](https://github.com/nsf/termbox-go/issues/148) bug.

**Comment by grav** [comment]
@remyabel ... of which there are more than 200 forks. Wonder if one of them has fixed this bug ...

**Comment by jesseduffield** [comment]
Given this is indeed a termbox bug I'm closing this issue. Hopefully somebody fixes it eventually
