### ISSUE TITLE
Cannot list branches

### ISSUE THREAD

**Issue by mia0x75** [jesseduffield/lazygit#293]
Latest git version on Fedora 28.
![screenshot from 2018-09-19 13 32 59](https://user-images.githubusercontent.com/5111356/45732830-a9dafd80-bc10-11e8-86bb-f0ba4a33a1f2.png)

**Comment by glvr182** [comment]
Thats likely because lazygit only displays the local branches.  You should see your branch appear once you have it checked out. (Try c to checkout by name)

**Comment by glvr182** [comment]
@mia0x75 Did u try out what i suggested?

**Comment by mia0x75** [comment]
> @mia0x75 Did u try out what i suggested?

Yes, it can list local branches, thank.
