### ISSUE TITLE
an error occured! under a soft link dir

### ISSUE THREAD

**Issue by WhateverMO** [jesseduffield/lazygit#2932]
**Describe the bug**
In my foot terminal type lazygit under a soft link dir, and then it tell me an error occured!

**To Reproduce**

1. cd into a soft link dir
2. type lazygit
3. See error

**Expected behavior**
Should be successfully open the TUI.

**Screenshots**
![image](https://github.com/jesseduffield/lazygit/assets/75033001/ace67abd-dfaa-43fe-bbdf-ded5ddbb9a78)

**Version info:**
_Run `lazygit --version` and paste the result here_
commit=v0.40.2, build date=2023-08-12T17:47:33Z, build source=binaryRelease, version=0.40.2, os=linux, arch=amd64, git version=2.41.0
_Run `git --version` and paste the result here_
git version 2.41.0

**Additional context**
I also write a new feature report for soft link dir(because it seems alse a new feature).

**Comment by mark2185** [comment]
It's being tracked in https://github.com/jesseduffield/lazygit/issues/3015, along with the PR https://github.com/jesseduffield/lazygit/pull/3017.
