### ISSUE TITLE
Under a soft link dir it should be work!

### ISSUE THREAD

**Issue by WhateverMO** [jesseduffield/lazygit#2933]
**Is your feature request related to a problem? Please describe.**
yes,there is the bug report https://github.com/jesseduffield/lazygit/issues/2932

**Describe the solution you'd like**
make it just work like normal dir.

**Describe alternatives you've considered**
Automate switch to origin dir when open TUI under a soft link dir, and go back when exit TUI.
But it seems so silly.I hope can run TUI directly under soft link dir.

**Comment by mark2185** [comment]
It's being tracked in https://github.com/jesseduffield/lazygit/issues/3015, along with the PR https://github.com/jesseduffield/lazygit/pull/3017.
