### ISSUE TITLE
Support rebasing onto upstream of a branch

### ISSUE THREAD

**Issue by jesseduffield** [jesseduffield/lazygit#2938]
**Is your feature request related to a problem? Please describe.**
We need to provide an easy way to rebase onto a branch's upstream.

**Describe the solution you'd like**
I'm thinking we should put this option behind the upstream-specific menu that you see when you press 'u' on a branch.

**Describe alternatives you've considered**
We could instead add an option for the upstream when you press 'r' on a branch (or we could support both flows). I'm undecided whether this is worth it.

PR https://github.com/jesseduffield/lazygit/pull/2649 proposed making it so that when you use 'r' on the checked out branch it rebases onto the upstream. I rejected this on the basis that if we need a UX for rebasing onto any branch's upstream we may as well get that UX in place and avoid having the same keybinding to different things depending on whether the selected branch is checked out or not.

**Additional context**
Based on conversation in https://github.com/jesseduffield/lazygit/pull/2649

**Comment by AzraelSec** [comment]
Hey - sorry for resuming this issue 👋🏻

Considering how we implemented the feature of resetting the checked-out branch to the selected one upstream, I think @jesseduffield's solution would be the right one. We would offer a consistent experience to the users, and we would have a battle-tested pattern to follow for handling edge cases.

Shall we proceed this way? @mark2185, are you going to work on this?

**Comment by mark2185** [comment]
If you have extra time and want to work on it, feel free to take it! :)

I'll look at other issues for things to do, no worries.

**Comment by stefanhaller** [comment]
I agree that the proposal is a good one.

However, before working on it I would recommend to wait until #2992 is merged, you'll benefit from it for disabling the new entry in case the branch has no upstream. I hope to push this along a bit more on the weekend.

**Comment by AzraelSec** [comment]
Mh, you're right, @stefanhaller - thanks for pointing that out! I didn't realize it was moving so fast.

**Comment by stefanhaller** [comment]
@AzraelSec #2992 has been merged, so you can go ahead with this!
