### ISSUE TITLE
Fail to execute Generate Sponsors README

### ISSUE THREAD

**Issue by kyu08** [jesseduffield/lazygit#2951]
https://github.com/jesseduffield/lazygit/actions/runs/5924470574

[My changes](https://github.com/jesseduffield/lazygit/pull/2950) caused this.

I think [this issue](https://github.com/JamesIves/github-sponsors-readme-action/issues/450) will help solve the problem.

**Comment by kyu08** [comment]
@jesseduffield 
After a someday release of `JamesIves/github-sponsors-readme-action`, it seems that it is now necessary to grant `org:read` permission to the token (`secrets.SPONSORS_TOKEN`).

Could you do this and rerun [this job](https://github.com/jesseduffield/lazygit/actions/runs/5924470574) please?

**Comment by jesseduffield** [comment]
Thanks for digging into that @kyu08 : I've updated the token and it successfully updated the sponsors :) 

https://github.com/jesseduffield/lazygit/commit/8dfa8dc48ca2e44467bd1da817c9e8887a5deec3

**Comment by kyu08** [comment]
@jesseduffield 
Thanks for addressing this too.
