### ISSUE TITLE
Search through the `?` Menu to find keybindings faster

### ISSUE THREAD

**Issue by ScumbagScalawag** [jesseduffield/lazygit#2965]
**Is your feature request related to a problem? Please describe.**
It slows down productivity when you run into novel keybindings/actions that you haven't memorized.

**Describe the solution you'd like**
A quick way to search for text within the `?` menu would help get things done faster, while still forcing you to *use* the keybinding. 
This can help memorize keybindings easier and keep you in flow. 

**Describe alternatives you've considered**
Not sure about alternatives. Right now I just use the good old fashioned peepers. 

**Additional context**
[Nvim Tree](https://github.com/nvim-tree/nvim-tree.lua) has this exact feature (when you press `g?` from inside Nvim Tree). 

Best, 

scally

**Comment by ScumbagScalawag** [comment]
Additional note, in Nvim Tree you press `/` to start a search from within the `g?` menu.

**Comment by mark2185** [comment]
Have you tried pressing `/` in the `?` menu?

Could be you're not on the latest version, but `0.40.2` definitely supports filtering the menu entries upon pressing `/`.

**Comment by ScumbagScalawag** [comment]
Ah my apologies you're right. The difference, it seems, between the way lazyvim does it (as opposed to vim) is that you have to press enter for the highlighting to show. In regular vim, you get a "live view" of what you're typing after the `/`. I suppose this feature is probably not worth the effort development-wise.
