### ISSUE TITLE
Search using `/` not arriving at matching target

### ISSUE THREAD

**Issue by peppy** [jesseduffield/lazygit#2971]
Running from HEAD, I got into a scenario where search was not correctly arriving at the target. Restarting lazygit did fix this, but it was definitely weird:

https://github.com/jesseduffield/lazygit/assets/191335/fba701b5-f0c9-4d32-b572-ba7b5f4a73b6

Also it seems like search is keeping the last search term (when using `/`) rather than clearing it.

**Comment by jesseduffield** [comment]
Hmm, I can't reproduce on my end.

As for retaining the search, that was an intentional UX change to allow you to easily change the search string in case you made a typo

**Comment by peppy** [comment]
Yeah it was ocne off, so I'm not sure what the reproduction steps are, but caused some very weird operations since I was looking at a different commit to what i was reverting 😅 .

As for the UX change, I'm not sure about it. All other apps I use which feature `/` search clear on each usage (but have history using up arrow to repeat / edit a previous search).

**Comment by jesseduffield** [comment]
Hmm good point, if we did have a search history that would make life easier. So it's very convenient that there is a PR up for exactly this which I've thus-far ignored haha https://github.com/jesseduffield/lazygit/pull/2877

If we can get that PR merged I'm happy to clear the search on each usage

**Comment by peppy** [comment]
I've had the original issue happen again. It's very broken...


https://github.com/jesseduffield/lazygit/assets/191335/dbcd885f-6f84-47d3-a7c4-a740f921e67c

Basically on searching it's seemingly not correctly jumping the app-wise commit cursor to a target commit when the commit is too far away from recent history. It only jumps visually in the commits box, but this will be lost on the next operation (j/k to move around the commit list, reset operations etc.)

Jumping between matches updates the commits box correctly, but the cursor is still tracking the original location before the search. Each time I hit 'j' it moves down one commit, but ignoring the ongoing search:

https://github.com/jesseduffield/lazygit/assets/191335/4e3b5be8-5609-4c48-91b5-4115e14439ec

Hope this can help figure the source of the issue.

**Comment by mark2185** [comment]
Regarding this:

> All other apps I use which feature / search clear on each usage (but have history using up arrow to repeat / edit a previous search).

Do you think there's a need for the "history buffer" to be circular? E.g. if we store 10 elements that we can reach the _first_ one by pressing `Up` 11 times? Or that we can reach the `10th` by pressing `Down` once?

I'm thinking this is unnecessary and that we could just have a buffer of let's say `10` elements, pressing `/` clears the current search query and pressing `Up` or `Down` scrolls through the history and inputs that as the search query.


(if it helps to explain, just like `vim` does searching with `/`)

**Comment by jesseduffield** [comment]
I agree: there is no need to make this circular. Also I'd cap it at some arbitrarily large limit like 1000 given how cheap it is

**Comment by mark2185** [comment]
I take it that means the history should survive a restart?

**Comment by jesseduffield** [comment]
I wasn't thinking that: it's something we could do but I doubt there's a strong need for it

**Comment by mark2185** [comment]
Alright, I was asking because of the cap at `1000`. Thanks for clearing it up! :)

**Comment by jesseduffield** [comment]
It's admittedly arbitrary haha: just capping it at some point for the sake of the one user who keeps a session open for years

**Comment by jesseduffield** [comment]
https://github.com/jesseduffield/lazygit/pull/2877 is now merged courtesy of @karimkhaleel

**Comment by peppy** [comment]
This is frustrating to the point of potentially not using lazygit features. I feel the need to raise this again.

On latest `master`

- Perform search
- Use 'k' to return to latest commit
- Attempt to reword the commit
- The previous search commit will be reworded instead.

The same applies to any operation.

https://github.com/jesseduffield/lazygit/assets/191335/f082c70e-61c3-496f-9888-9f50160d2d5e

**Comment by stefanhaller** [comment]
It's strange, I can't reproduce your reword scenario, this works as expected for me.

However, when I move away from the current match (using j/k or arrow keys), then open the keybindings dialog (`?`), then escape out of it, the selection jumps back to the last match. The same happens with any other dialog, and also when I select a different side panel and then jump back to the commits panel. Maybe this can give us a clue what's going on.

**Comment by karimkhaleel** [comment]
I was able to reproduce the scenario on my machines. It seems to occur only when the search match is found beyond the initial display of 15 commits, as @peppy mentioned:

> Basically on searching it's seemingly not correctly jumping the app-wise commit cursor to a target commit when the commit is too far away from recent history.

I also found another issue that appears to be related. There seems to be a discrepancy between where lazygit thinks we are searching from and where our current selection actually is. Here's what happens when I search for the word "Add":
![image](https://github.com/jesseduffield/lazygit/assets/94621779/635aec37-b850-4c80-a8e1-677ecf159537)

Then, I moved my selection using the `Up` arrow key until I reached the beginning of the local commits window:
![image](https://github.com/jesseduffield/lazygit/assets/94621779/05e51969-417b-4786-9fcd-6bbfb10986c4)

Afterwards, I searched for the word "Remove" and pressed enter, expecting my selection to be at the point highlighted in red. However, instead of my selection moving to the expected location, it jumped to the second "Remove," which is after the position initially selected during the first search.
![image](https://github.com/jesseduffield/lazygit/assets/94621779/edef7054-43bd-4963-89cb-c72b1a72ce94)

**Comment by jesseduffield** [comment]
Thanks for that investigation @karimkhaleel . I've reproduced that and I see that it's resolved when I comment out this line:
https://github.com/jesseduffield/lazygit/blob/12bad5f45211a5177c810c5db6380291bf5b85ef/pkg/gui/controllers/helpers/search_helper.go#L87

I need to do some more digging to see why that line was added in the first place

**Comment by jesseduffield** [comment]
This PR should do the trick: https://github.com/jesseduffield/lazygit/pull/3022

**Comment by jesseduffield** [comment]
@peppy can you confirm your issues are resolved by that PR? I mostly focused on the first issue you mentioned

**Comment by peppy** [comment]
This does indeed look fixed, thanks 🙏
