### ISSUE TITLE
More clear commit color explanation

### ISSUE THREAD

**Issue by ScumbagScalawag** [jesseduffield/lazygit#2981]
**Topic**
I have questions and suggestions about how I'd like the commits to be colored, but first I'd like to know a little more about what the intended behavior is. 

**Your thoughts**
1. In a `main` branch (with a corresponding `origin/main`), commits not synced with `origin/main` are expectedly showing up red, but I don't understand why the others would not be green if they ARE synced. 
2. In branch `feature1` (both with *and* without a corresponding `origin/feature1`) that was branched from `main`, ALL the commits are yellow. This doesn't seem right, as I would expect commits shared between `feature1` and `main` to be green. 

At the very least I'd expect some distinction that separates commits from `feature1` and `main`, while also distinguishing between commits that are in sync with their corresponding remote branch. 

Is there a way to double check that everything is configured correctly to ensure that the green coloring works as intended? 
When are commit supposed to be Green and why aren't they in this case?

**Comment by ScumbagScalawag** [comment]
to expand a bit, the definition [here](https://github.com/jesseduffield/lazygit/issues/823#issuecomment-678770341) is what I would expect. 

I would like for commits shared between feature branches and branches defined in `git.mainBranches` array to be green. always. It would be nice to use lazygit as a simple visual aid to see if they are merged into `main` yet.

**Comment by stefanhaller** [comment]
Yes, that's how it is supposed to work, so we have to find out why it doesn't for you. Did you set the `git.mainBranches` config to something? (You shouldn't have to, "main" is in there by default). Can you post some screenshots? What lazygit version are you using?

**Comment by ScumbagScalawag** [comment]
Whoops. My apologies. I've upgraded all my software to latest version and it's working as intended. My custom script to automatically update Homebrew wasn't working this whole time!
