### ISSUE TITLE
Support disabled menu items

### ISSUE THREAD

**Issue by jesseduffield** [jesseduffield/lazygit#2985]
**Is your feature request related to a problem? Please describe.**
There are some menu items that we only want to enable if some condition is met. For example we only want to allow resetting to a branch's upstream if branch actually has an upstream.

Currently we have to choose between hiding the menu item, which could cause confusion if the user doesn't know why it's hidden, or show the menu item and then raise an error when it's pressed. Neither of these is good!

**Describe the solution you'd like**
Add a DisabledReason string field to the MenuItem struct. If this field is non-empty, we will display the reason for it being disabled in the tooltip. If there is already a defined tooltip, we'll display the disabled reason underneath e.g. if the DisabledReason is 'This branch is not tracking an upstream' and the existing tooltip is 'Reset to the branch's upstream', the resulting tooltip will be:
```
Reset to the branch's upstream

Disabled: This branch is not tracking an upstream
```

Whereas if the tooltip is not defined, we'll just get:
```
Disabled: This branch is not tracking an upstream
```

Nothing annoys me more than having a disabled menu item without knowing why, and so that's why I'm making it so that you must give a reason in order to disable something.

**Comment by stefanhaller** [comment]
Nice, I like the design.

What should happen if you try to invoke a disabled item? Do nothing, or show an error message? Doing nothing might be appropriate if it is invoked by selecting it and hitting return, because in this case you see the tooltip; but if you invoke it through its keybinding, you don't, and maybe an error message would be more appropriate in that case.

**Comment by jesseduffield** [comment]
Good point. We could just show the disabled reason as the error message upon invoking the menu item

**Comment by stefanhaller** [comment]
I don't think it would make it useless, and (at least for me) avoiding interaction feedback isn't the main goal here. Also, we want to use it in the main menu too, don't we? It would be useful if you try to reword a rebase todo command, for example. And you can't flash anything here (if the command is invoked through its key binding without opening the menu at all), we need to put up a message in that case.

**Comment by jesseduffield** [comment]
I agree with @stefanhaller: the goal of a disabled state is to show that an action _would_ be available under certain conditions but it's currently not. This helps with discoverability especially when you give a reason for it being disabled.

Interesting point about the keybindings menu: this is generated directly from the same keybindings slice used when a key is pressed, so in order to show one of those as disabled we'd need to have a function field in the keybinding that tells us whether the key is disabled and if so, what the reason is. Implementing this would be quite a task because:
* we'd need to pull out validation code from the handler function and move it into the disable function
* we'd want to run the disable function when the keybinding is invoked before running the handler so that we still get the validation (e.g. if we haven't gone through the menu, or if some state has changed since the menu was opened). This is simple enough to implement in a single place, but we will sometimes have to duplicated logic across the disable function and the handler function (e.g. obtaining the selected item or some associated item like a branch and its upstream)
* we'd need to run all the disabled functions whenever that keybindings menu is brought up given that the functions depend on the currently selected item.

None of this is _that_ bad so long as we have a rule that we can't have any code in a disable function that requires making an expensive call (which means no calls to git, and ideally no calls to the filesystem).

We can also gradually roll out the disable function where it's needed, and just say a keybinding is always enabled when its disable function is nil.

_But_ it's a big enough job that it might need to be done separately from what I originally had in mind which was just disabling menu items in menus other than the keybindings menu.

**Comment by jesseduffield** [comment]
Also to be clear I want these disabled items styled with a strikethrough (as we currently do the in the keybindings menu for 'space' and 'enter' keybindings

**Comment by stefanhaller** [comment]
> But it's a big enough job that it might need to be done separately from what I originally had in mind which was just disabling menu items in menus other than the keybindings menu.

I don't think it's so bad. [Here's a PR](https://github.com/jesseduffield/lazygit/pull/2992) that lays the ground, and uses it for a few examples. The bulk of the work is then to roll it out to more keybindings; I could imagine that the ones in `local_commits_controller` could be tricky, as the conditions for disabling things are spread a bit there. Will have a look at those later. Keeping it as a draft for now because I think it makes sense to first add more examples to validate the approach.

**Comment by stefanhaller** [comment]
Done in #2992.
