### ISSUE TITLE
Wired Display

### ISSUE THREAD

**Issue by Jevi06** [jesseduffield/lazygit#299]
**Describe the bug**
when use in win10 powershell or cmd ,it show a wired ui as pic I atteched below.

**To Reproduce**
1. Go to any git repo
2. open a cmd window
3. type lazygit 

**Expected behavior**
I expect a correct ui but it show a weried one

**Screenshots**
![clue](https://user-images.githubusercontent.com/17949749/45861442-1b48b680-bd9f-11e8-9452-c7df1ebd8c1f.png)

**Desktop (please complete the following information):**
 - OS: [ Windows10]
 - Lazygit Version [e.g. v0.2.2]

**Additional context**
it may be caused by my high resolution screen ,anyway fix it please

**Comment by ponsfrilus** [comment]
Please see https://github.com/jesseduffield/lazygit/issues/24

**Comment by Jevi06** [comment]
@ponsfrilus thanks ,good man.
