### ISSUE TITLE
Rounded Corners

### ISSUE THREAD

**Issue by moritz-t-w** [jesseduffield/lazygit#2997]
**Is your feature request related to a problem? Please describe.**
I don't quite like the sharp edges

**Describe the solution you'd like**
Using different characters for the edges they could be rounded, which makes it look modern and cool. Of course this would be configurable.
![image](https://github.com/jesseduffield/lazygit/assets/90388353/8500c750-372e-4e6c-8708-1694ffbe061c)
kinda like this

**Describe alternatives you've considered**
putting tape over the parts of my screen where the corners are and painting rounded corners over them

**Comment by stefanhaller** [comment]
Try
```
gui:
  border: rounded
```
in your config file. Just learned about this today. 😄

**Comment by moritz-t-w** [comment]
oh ma gawd

**Comment by moritz-t-w** [comment]
thanks!

**Comment by jesseduffield** [comment]
I was thinking yesterday we should make rounded the default

**Comment by stefanhaller** [comment]
I thought the same when I saw it. Want me to change it?

**Comment by jesseduffield** [comment]
Go for it :)

**Comment by tmwatchanan** [comment]
I think the `rounded` border is supposed to be default. But if I don't explicitly set `border: "rounded"`, I always get `single` border somehow. Is this a bug or just me?

**Comment by stefanhaller** [comment]
> I think the rounded border is supposed to be default.

Yes it is, on master, and in the next release. It isn't yet in the current release. The docs already describe the state of master.

**Comment by tmwatchanan** [comment]
Oh that's right. I was on the v0.40.2. Switching to HEAD works as expected. Thanks!
