### ISSUE TITLE
Exit lazygit when (e)diting a file

### ISSUE THREAD

**Issue by waiting-for-dev** [jesseduffield/lazygit#3009]
**Is your feature request related to a problem? Please describe.**
I have lazygit opening on a vim floating window. I'm using the remote options to edit files in the current instance. However, the floating window remains there awaiting to go back to lazygit.

**Describe the solution you'd like**
If there was an option for lazygit to exit whenever editing a file, I could leverage that along the `close_on_exit` toggleterm option.

**Describe alternatives you've considered**
Using a regular window, but it's not the same experience.

**Additional context**

**Comment by mark2185** [comment]
Have you thought about opening `lazygit` in a `tab` instead of a floating window? That way it won't get into the way, and you can still use it from within `vim`.

Or is that the alternative you have described?

**Comment by waiting-for-dev** [comment]
Thanks for getting back to me, @mark2185. That would help, as the focus is changed to the file tab. However, when going back to the lazygit tag it still shows the prompt `Press enter to return to lazygit`, so I need to 1) Press `i` to be able to interact with the process  2) Press `ENTER` to return to the lazygit panels, so it's not a very good experience. If we closed lazygit we'd open in again in a pristine state. Does it make sense?

**Comment by stefanhaller** [comment]
You can avoid the "Press enter to return to lazygit" prompt by putting
```
promptToReturnFromSubprocess: false
```
in your config file.

**Comment by mark2185** [comment]
In addition to what Stefan suggested, you can probably instruct `vim` to always enter the insert mode in buffers of the `term` type.

**Comment by waiting-for-dev** [comment]
> You can avoid the "Press enter to return to lazygit" prompt by putting
> 
> ```
> promptToReturnFromSubprocess: false
> ```
> 
> in your config file.

That definitely did the trick. Thanks a lot for your insights, @stefanhaller & @mark2185.
