### ISSUE TITLE
Not working properly with $GIT_DIR and $GIT_WORK_TREE environment vars

### ISSUE THREAD

**Issue by intrntbrn** [jesseduffield/lazygit#3010]
Lazygit is messed up when `$GIT_DIR` and `$GIT_WORK_TREE` is defined and *not* launched with `--git-dir` and `--work-tree` arguments.

Commits and files are displayed correctly but it's not possible to stage a file (or to run other commands), because the work-tree prefix is missing in the file's path (e.g. it tries to run `git add file` instead of `git add worktree/file` because worktree is undefined) 

The issue can be fixed by explicitly defining the arguments: `lazygit --git-dir=$GIT_DIR --work-tree=$GIT_WORK_TREE`.

**Comment by jesseduffield** [comment]
This should be an easy fix i.e. in https://github.com/jesseduffield/lazygit/blob/12bad5f45211a5177c810c5db6380291bf5b85ef/pkg/app/entry_point.go#L71 we need to Chdir to the worktree path when the CLI arg is passed or when the env var is set.

Would you be up to raising a PR for this @intrntbrn ?

**Comment by intrntbrn** [comment]
#3024 PR
