### ISSUE TITLE
Git Revert --no-commit

### ISSUE THREAD

**Issue by 9mm** [jesseduffield/lazygit#3011]
**Is your feature request related to a problem? Please describe.**

Lets say I make a commit called `remove tracking` and I remove 10 lines of code.

I want to essentially "undo" this commit but leaving the branch untouched, and leaving the old commit exactly as it is. Almost as if I said "oh I need to undo those changes" and I manually copy and paste from the red parts of the diff and paste them where they need to go, and have those changes be unstaged.

Often times I make lots of undo/redo related to split tests, and this workflow would be much more favorable than actually TRULY "undoing" the commit. I want to really just take the last commit and do the inverse of it and put that into unstaged, and nothing more.

The reason I want it unstaged is because usually after undoing it I need to make further changes to the undo, which is why I dont want an 'actual' undo.

**Describe the solution you'd like**

I would like somehow to have this version of `revert`

```git revert --no-commit```

> Use --no-commit flag and use git reset to remove the changes from staging area.

---

I know there are other git restore issues, i searched them but they were closed by the creator of the issue, or dont specifically address this usecase (maybe it can already be done with features that are already in lazy git?)

**Comment by 9mm** [comment]
I actually found this... `git revert` is what I mean... sorry, not git restore:

```
This is exactly what [git revert](https://git-scm.com/docs/git-revert) does:

Given one or more existing commits, revert the changes that the related patches introduce, and record some new commits that record them.

Use --no-commit flag and use git reset to remove the changes from staging area.

The answer by @eftshift0 works if the commit you want to undo is the previous one. git revert works even if the commit you want to undo is done earlier in the history.
```

**Comment by 9mm** [comment]
I noticed this reply and the concern of extra flags: https://github.com/jesseduffield/lazygit/issues/650

This makes sense, however given that `t` git revert already brings up a confirmation, perhaps we can change that to a 'select' pane with a 'cancel' exactly like `D` for the destroy menu, then it will not require an additional confirmation?

**Comment by mark2185** [comment]
Take a look at [this](https://github.com/jesseduffield/lazygit#rebase-magic-custom-patches), you basically want to apply the patch in reverse to the index.

Also, you could create a [custom command](https://github.com/jesseduffield/lazygit/blob/master/docs/Custom_Command_Keybindings.md) that does `git revert --no-commit {{.SelectedLocalCommit.Sha}}`.

**Comment by 9mm** [comment]
Ahhh interest!! Thanks! This is great.

I really appreciate it

**Comment by 9mm** [comment]
PS I see this should have been a discussion now, ,will do that in future

**Comment by 9mm** [comment]
@mark2185 I do have a question... this might be dumb, but when I apply it in reverse, does this do anything "special"? I notice that gitsigns is not showing modifications, yet if i modify another part of the file it does.

ive gone to git status and nothing stands out as different, and i even looked in the github app and nothing stands out there either

its like something about that action made them get treated differently even though they look like simple staged/unstaged modifications...

**Comment by 9mm** [comment]
yes that was dumb... for some reason i didnt realize gitsigns doesnt show things for staged, uncommited files... weird
