### ISSUE TITLE
lazygit does now show first file changed

### ISSUE THREAD

**Issue by axet** [jesseduffield/lazygit#3027]
**Describe the bug**

git status showing 1 file not under control / changed file. but lazygit showing nothing is changed / prepared to commit.

**To Reproduce**

1. cd any git repo
2. mkdir .install-6VqN
3. chown root:root .install-6VqN
4. chmod 700 .install-6VqN/

**Expected behavior**

Show all changes.

**Screenshots**

![Screenshot from 2023-09-26 18-29-03](https://github.com/jesseduffield/lazygit/assets/298672/17919596-1ff1-4331-ae94-eeaacd434686)
![Screenshot from 2023-09-26 18-29-20](https://github.com/jesseduffield/lazygit/assets/298672/c483420d-cbb0-404f-b13a-d4e8858855e8)

**Version info:**
$ lazygit --version
commit=, build date=, build source=unknown, version=unversioned, os=linux, arch=amd64
$ git --version
git version 2.39.2

**Comment by stefanhaller** [comment]
Then it's a bug in lazygit, because apparently it's reading both stdout and stderr of the `git status` call and trying to parse it all. Since the warning goes to stderr, this should be easy to fix. (I don't have time to look into it though.)

**Comment by stefanhaller** [comment]
OK, I'm confused now. We do already ignore stderr in the `git status` call, and this was changed as a bug fix in 0.36 (see https://github.com/jesseduffield/lazygit/pull/2081).

@axet, I can't tell what lazygit version you are using because the version information you included above doesn't tell us. I don't understand why that is, when I build from source I get at least a git commit hash there. Where does your lazygit come from?

**Comment by axet** [comment]
This is my lazygit shortcut (bash script). And before that I usually do 'rm -rf ~/.go'

```
#!/bin/bash

which lazygit > /dev/null 2>&1 || go install github.com/jesseduffield/lazygit@v0.35.0
lazygit "$@"
lg (END)
```

**Comment by stefanhaller** [comment]
I don't get it, it looks like you are pinning your lazygit version to 0.35? Why? (And this would totally explain what you are seeing, as the bug was only fixed in 0.36.)

**Comment by axet** [comment]
Typo. It suppose to be (and now is) '@master'.

**Comment by stefanhaller** [comment]
OK, so can you still reproduce the bug with that version?

**Comment by axet** [comment]
Works.
