### ISSUE TITLE
Branches - switch branch to previous one

### ISSUE THREAD

**Issue by smangels** [jesseduffield/lazygit#3030]
**Topic**
Is there a keyboard shortcut to quickly switch between 2 branches (back to previous).

**Your thoughts**
I'm doing it with `git checkout -` in the terminal and I wonder whether there is a way to achieve the same behaviour in Lazygit.

**Comment by mark2185** [comment]
Unfortunately there isn't, but you could use a `customCommand` to define a mapping yourself.

Just an example:
```
  - key: 't'
    command: 'git checkout -'
    context: 'localBranches'
    description: 'Checkout last branch'
```

**Comment by jesseduffield** [comment]
It's not documented but you can also press 'c' to bring up the branch checkout prompt and then enter '-' and hit enter. Only three keypresses!

**Comment by smangels** [comment]
thanks for answering  my question, I've took the freedom to provide a PR for it.
