### ISSUE TITLE
git pull --rebase

### ISSUE THREAD

**Issue by suntsu42** [jesseduffield/lazygit#3033]
**Topic**
I do have a branch (master in this case) on which i do have one commit and on which there are two commits on the remote:
![image](https://github.com/jesseduffield/lazygit/assets/1768336/289b524f-0eab-4754-85ca-6cf382295d3b)

If  i just use git pull (Shortcut p in lazygit), it would pull the two commits from remote and create a merge commit.
I now want to avoid this merge commit and instead use git pull --rebase

I am aware that this question was already asked once (https://github.com/jesseduffield/lazygit/issues/2175), but i don't understand the answer. In this thread, it was recommended to use fast-forward instead. But this doesn't work since i do have local commits and can't use ff. 

I am also aware that i can configure my gitconfig to use pull rebase by default which i like to avoid. 

Question: Is it possible to enable ```git pull --rebase``` in lazygit?

**Comment by stefanhaller** [comment]
Lazygit doesn't have an option for this, since git itself has a global setting for this (`git config --global pull.rebase true`), and lazygit respects that. The benefit of this approach is that it makes pressing `p` in lazygit do the same as typing `git pull` on the command line.

**Comment by suntsu42** [comment]
Thanks for the clarification. In this case, i'll just configure it in the git config.
