### ISSUE TITLE
Creating pull request from branches panel

### ISSUE THREAD

**Issue by kristijanhusak** [jesseduffield/lazygit#304]
I would like to be able to create pull request from branches panel, by opening link in browser that directly points to the new pull request.

In bitbucket, after you push to a branch, it prints this link in stdout, and opening it you go directly to the new PR page, with the branch preselected as source branch. Something like this: 
```sh
remote:
remote: Create pull request for feature/some-branch:
remote:   https://bitbucket.org/kris/my-repo/pull-requests/new?source=feature/some-branch&t=1
```
I think github does similar thing, but not always.

When we push the branch from lazygit, we don't get to see any output, so we cannot really use the solution above.

Here's how it would work:
* Select a branch in branches panel
* Press `o`, or any other keybinding that suits this.
* Your default browser opens with the link above

Implementation:
* Get the selected branch
* Get the repo remote url
* detect service (Github, bitbucket, etc.)
* generate proper url for service by the service base url and repo remote url.
* Open it with `xdg-open` on linux, `open` on mac, and `start` in windows i think.

If you consider this, i'll create implementation that will work with bitbucket and github. I'm not using any other services, but i'll make it easily extendable.

**Comment by kristijanhusak** [comment]
I'm closing this since it's implemented.

**Comment by allestaire** [comment]
When I tried it says Unsupported git service

**Comment by mark2185** [comment]
Which git service are you using? 

If it's a custom one, you need to [configure it properly](https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md#custom-pull-request-urls)

**Comment by allestaire** [comment]
> Which git service are you using?
> 
> If it's a custom one, you need to [configure it properly](https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md#custom-pull-request-urls)

Im using gitlab,
Also tried on bitbucket it works fine :)

**Comment by mark2185** [comment]
Are you using the latest version of `lazygit`? 

Tried it now with [this repo](https://gitlab.com/html-validate/demo) and I don't get the error message.

**Comment by allestaire** [comment]
Yes, I use the latest version 😄

**Comment by mark2185** [comment]
The latest version is `0.39.3`, though.

Please open up a separate bug issue (and fill out the template) for further debugging.
