### ISSUE TITLE
does it follows gitconfig configurations?

### ISSUE THREAD

**Issue by mzumberi** [jesseduffield/lazygit#3066]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when […]
i’d love to see that lazygit starts to follow the rules set on gitconfig

**Describe the solution you'd like**

my local gitconfig 
```
[pull]
	rebase = true
```

whether i push “p” to pull i want it to git pull —rebase as written in the git config

**Describe alternatives you've considered**
i considered the custom command option but this is not fast as the default “press p” to pull
i also considered to overwrite the pull command but i actually don’t know how to do it

**Additional context**

**Comment by mark2185** [comment]
Well, that's what is supposed to happen, which version of `lazygit` are you using?

**Comment by mzumberi** [comment]
i’m on a macbook
```
lazygit --version
commit=, build date=, build source=homebrew, version=0.40.2, os=darwin, arch=amd64, git version=2.23.0
```

when i pull i see from the lazygit command log ` git pull --no-edit ` instead of` git pull —rebase`

**Comment by stefanhaller** [comment]
This shouldn't depend on the version of lazygit at all; lazygit simply calls `git pull`. It is a feature of git itself that it does a rebase instead of a merge behind the scenes when saying `git pull`.

Are you sure that it's not rebasing, or are you only suspecting it because of what you see in the log?

**Comment by mzumberi** [comment]
Hi @stefanhaller i actually don’t know if lazygit actually rebases when it pulls
i just suspect as you said because of the command log that shows another command

**Comment by stefanhaller** [comment]
Well, then it's as if you type `git pull` on the command line. It does a rebase in that case too, although you don't see the `--rebase` option anywhere.

**Comment by mzumberi** [comment]
Ok great! thanks for the quick feedback!
btw great product lazygit
