### ISSUE TITLE
Keybindings window does not describe diff mode keybinding

### ISSUE THREAD

**Issue by jjohnston-aims** [jesseduffield/lazygit#3068]
**Describe the bug**
The keybindings window does not show an entry for entering diff mode.

**To Reproduce**

1. Go to any panel
2. Press '?'
4. Look for `<c-e>` keybinding
5. Fail to find it

**Expected behavior**
I would expect to see something about diffing in the keybindings window. Preferably I would see '<c-e> Enter diffing mode'

**Version info:**
commit=5e388e21c8ca6aa883dbcbe45c47f6fdd5116815, build date=2023-08-07T14:05:48Z, build source=binaryRelease, version=0.40.2, os=linux, arch=amd64, git version=2.25.1
git version 2.25.1

**Comment by stefanhaller** [comment]
`<c-e>` for diffing has been deprecated since 2020. It still works, but the official keybinding for it is `W`, which does show up in the menu.
