### ISSUE TITLE
Scrolling with mouse within the commit's diff

### ISSUE THREAD

**Issue by sundarv85** [jesseduffield/lazygit#307]
Feature Request:

The current option to scroll within the diff is to use fn+down and fn+up keys. Which is good.

When I scroll using my mouse over iterm2(v3), then it acts like the tab is being pressed and I’m moving to different sections. Instead, it would be helpful if I can focus within the diff section, then I can easily scroll and see big diffs...

**Comment by kristijanhusak** [comment]
There's also option to use `J` and `K` (uppercase with shift) https://github.com/jesseduffield/lazygit/pull/453, which is also really nice.

**Comment by jesseduffield** [comment]
I believe this has been implemented a while back but I forgot to close this issue. Let me know I'm wrong about that :)
