### ISSUE TITLE
Add tabs - Manage multiple repositories at the same time

### ISSUE THREAD

**Issue by varaskkar** [jesseduffield/lazygit#3072]
**Is your feature request related to a problem? Please describe.**
In my job I need to manage several repositories at the same time and know in which ones I have to pull to update it.

**Describe the solution you'd like**
Add tabs. In each one have a different repository. Show in each tab if there are changes to push or pull.

**Describe alternatives you've considered**
With a keyboard shortcut, add a new repository. Differentiate them by tabs or by boxes. 

Repository 1: ↑5 ↓2
Repository 2: ↑1 ↓3

**Additional context**
Instead of opening 3 or 4 instances of lazygit, one for each repository, you could open in lazygit as many repos as needed.

**Comment by stefanhaller** [comment]
I use different terminal tabs for this. What would be the advantage of replicating that functionality inside of lazygit?

**Comment by varaskkar** [comment]
To have everything centralized in one place

With different terminals you have to change the view between them to see if you have pull to bring, but having it all in the same terminal you can quickly see the status of the projects

For example, if you have several monitors you can have on the same monitor just 1 lazygit managing all the repositories

**Comment by mark2185** [comment]
This is mostly for one branch?

I guess having that info about up/down for each checked out branch in the `Recent repositories` could be good enough for you?

**Comment by varaskkar** [comment]
> This is mostly for one branch?
> 
> I guess having that info about up/down for each checked out branch in the `Recent repositories` could be good enough for you?

It'd be only for the current branch of each repository. And yes totally, that option would also be quite useful!

**Comment by jesseduffield** [comment]
I'd love to have the recent repos menu become a fully-fleged view that lets you e.g. concurrently do a `git pull` on each repo

But having tabs would be going too far

**Comment by jesseduffield** [comment]
I'm closing this issue in favour of https://github.com/jesseduffield/lazygit/issues/3278
