### ISSUE TITLE
Stop colouring filenames based on status?

### ISSUE THREAD

**Issue by jesseduffield** [jesseduffield/lazygit#3077]
I noticed that with coloured file icons, having the file name coloured based on status looked a little jarring going from a red status to a blue icon to a red file name:

<img width="599" alt="image" src="https://github.com/jesseduffield/lazygit/assets/8456633/2524d99a-25b1-4f83-a4d7-92fbcb4d0d86">

Maybe we should just leave the filename with the default text colour like so (grey colour in directories is just me playing around, not proposing we do that)

<img width="596" alt="image" src="https://github.com/jesseduffield/lazygit/assets/8456633/7a63ff14-f750-4416-85c2-0110687b0550">

Pros:
* red text (arguably also green text) can be hard to read so relegating it to the status means the file name is more readable
* arguably looks aesthetically more pleasing

Cons:
* currently we colour a directory green/red/yellow depending on the status of its files: if we remove that we'd need to add a new status marker against the directory itself which could increase clutter. Otherwise it will be hard to know the status of a collapsed directory
* slightly harder to see at a glance what the status of files are

**Comment by aashish2057** [comment]
I think going with white text is definitely better aesthetically and easier to read, in your screenshots the M still changes color based on the status of its files, which I think is great, keep its clean and you still have the information at a glance on the status of a file
