### ISSUE TITLE
Why I can't see any branches in the remote view

### ISSUE THREAD

**Issue by rabin-io** [jesseduffield/lazygit#3082]
**Topic**
$ubject

**Your thoughts**
Not sure if it is a bug or just me, but my remote show 0 branches. I was expecting lazygit to list my remote branches and let me checkout one just like with the local one.

![image](https://github.com/jesseduffield/lazygit/assets/5116363/6546f566-644f-4496-ab21-fec02de0ccc0)

**Comment by mark2185** [comment]
Did you try fetching it with `f`?

**Comment by mark2185** [comment]
Could you please fill out the bug template?

**Comment by rabin-io** [comment]
I opened an issue for this → https://github.com/jesseduffield/lazygit/issues/3084

**Comment by mark2185** [comment]
Alright, we'll track it there then.
