### ISSUE TITLE
Lazygit won't show branches in remote tab

### ISSUE THREAD

**Issue by rabin-io** [jesseduffield/lazygit#3084]
**Describe the bug**

In the remote view/tab it shows 0 branches,

**To Reproduce**

1. cloen git@github.com:openshift-cnv/cnv-ci.git
2. open the folder with lazygit
3. not showing anything in the remote
4. while 
```
❯ git branch -r
  origin/HEAD -> origin/master
  origin/master
  origin/release-4.10
  origin/release-4.11
  origin/release-4.12
  origin/release-4.13
  origin/release-4.14
  origin/release-4.15
  origin/release-4.6
  origin/release-4.7
  origin/release-4.8
  origin/release-4.9
```

**Expected behavior**
To show the remote branches, and be able to check out the branches.

**Screenshots**
![image](https://github.com/jesseduffield/lazygit/assets/5116363/09eab5f4-7993-4cf4-b150-2e3cb20e68ca)

**Version info:**
```
❯ lazygit --version && git --version
commit=5e388e21c8ca6aa883dbcbe45c47f6fdd5116815, build date=2023-08-07T14:05:48Z, build source=binaryRelease, version=0.40.2, os=linux, arch=amd64, git version=2.41.0
git version 2.41.0
```

**Comment by mark2185** [comment]
Does it happen with other repositories as well? I can't seem to reproduce it with the given steps, it shows 11 branches for me.

**Comment by AzraelSec** [comment]
I cannot reproduce the issue either. 11 branches for me as well.

**Comment by rabin-io** [comment]
Actually yes, it happens on other git repos as well

just in case, here is my [lazygit config](https://gist.github.com/rabin-io/27acc7dea5d5e02e426f80a190a81da2) and [git config](https://gist.github.com/rabin-io/ef9a2a9c89d67849881d6c0d7ac0bff9)

**Comment by rabin-io** [comment]
Not sure what is cussing this, but if I run lazygit inside an isolated container, I do see the branches.

```sh
❯ podman run -it --rm -v ~/src:/src -v /usr/local/bin:/usr/local/bin registry.fedoraproject.org/fedora-minimal:rawhide bash
```

Here are [logs from my local env](https://gist.github.com/rabin-io/f4353df453fe93e5843661fa8519732a) and the [logs from the container](https://gist.github.com/rabin-io/d9caba3ba8135ead3b849c937b930d2e)

**Comment by rabin-io** [comment]
Running lazygit with a clean git config file, seems to "resolve" the problem, so it seems something in my git config is responsible for my issue.

**Comment by rabin-io** [comment]
This is the config block which caused my problem,

```ini
[color]
    ui = always
 ```

Sorry for all the noise, and thank you
