### ISSUE TITLE
Enforce (or encourage) git commit 50/72 in the commit windows

### ISSUE THREAD

**Issue by baalimago** [jesseduffield/lazygit#3087]
First of all I'd like to say that I'm a big fan of lazygit, find it very fun to use! At first I mostly used it due to lunarvim's leader keys, now I've found that it increases my git productivity manyfold.

**Is your feature request related to a problem? Please describe.**
Yes! Using lunarvim, or simply vim, there's usually enforcement of the [git 50/72 rule](https://www.google.com/search?q=git+commit+50%2F72&newwindow=1&client=ubuntu-sn&hs=Csd&sca_esv=575606875&channel=fs&sxsrf=AM9HkKk6nhNTOsm4MQUh5YUgkseFsGpr4w%3A1697985324919&ei=LDM1ZdDVN4TGwPAPituXyAQ&oq=git+commit+50&gs_lp=Egxnd3Mtd2l6LXNlcnAiDWdpdCBjb21taXQgNTAqAggAMggQABjLARiABDIIEAAYywEYgAQyBhAAGBYYHjIGEAAYFhgeMgYQABgWGB4yBhAAGBYYHkjiJFD1AljLGXADeAGQAQCYAZ8BoAH9BqoBAzEuNrgBA8gBAPgBAcICChAAGEcY1gQYsAPCAgQQIxgnwgIHECMYigUYJ8ICBRAhGKAB4gMEGAAgQYgGAZAGCA&sclient=gws-wiz-serp). 

This is lacking, as far as I can tell, in LazyGit's commit window.

**Describe the solution you'd like**
Either I'd like strict enforcement, as in: the lazygit commit + description windows disallow messages breaking this rule.

Another alternative which is less breaking is to build in some keybind (perhaps "f"?) that formats the text as good as it can.

A third alternative is to hint to the user via color codes/highlights where the rule is broken.

**Additional context**
If this functionality is something that would be appreciated I'd like to submit the PR myself! I wish to contribute more to open source projects and couldn't think of a better place to star than lg.

EDIT: Spelling errors

**Comment by baalimago** [comment]
Judging by the reactions of https://github.com/jesseduffield/lazygit/issues/2627, I think a formatting key and highlighting might be the way to go.

Mimicking the highlighting behaviour of vim should be fairly easy to do:
![image](https://github.com/jesseduffield/lazygit/assets/21121209/36b559a5-d265-4e38-a2fa-896cb63826d1)

**Comment by mark2185** [comment]
I vote for highlighting the entire row when it passes 50/72 chars, definitely not a fan of automatic breaking/formatting.
