### ISSUE TITLE
Custom patches do not work if diff.noprefix is true

### ISSUE THREAD

**Issue by Reinis** [jesseduffield/lazygit#3107]
**Describe the bug**
Git fails to apply patches if it is configured to not prefix diffs. Seen in custom patch feature.
```.gitconfig
[diff]
	noprefix = true
```

Probably should use `git apply -p0`.

**To Reproduce**

1. Configure git diff to noprefix = true
2. Create a custom patch in lazygit
3. Move patch out into index

**Expected behavior**
The patch should be moved.

**Version info:**
Installed using `go install github.com/jesseduffield/lazygit@latest`.
```
$ lazygit --version
commit=, build date=, build source=unknown, version=unversioned, os=linux, arch=amd64, git version=2.40.1
```

**Comment by stefanhaller** [comment]
Thanks for the report. This should be easy to fix by explicitly passing `--default-prefix` to the git diff command. (However, `--default-prefix` was only added in 2.40.0, so for better compatibility we can use `--src-prefix=a/ --dst-prefix=b/` which were added in 1.5.4.)

Out of curiosity, why are you setting `diff.noprefix` to true?

**Comment by Reinis** [comment]
I'm using it so that it is easier to select file path from `git diff` output with a double click and pasting it in IDE to go to the file :man_shrugging:
