### ISSUE TITLE
Remove custom commands from suggestions

### ISSUE THREAD

**Issue by TomDeneire** [jesseduffield/lazygit#3114]
**Is your feature request related to a problem? Please describe.**
In the past I have entered some faulty or nonsensical custom commands (like `:wqa!` because of Vim muscle memory). There is, however, no way to delete these from the suggestions list (see screenshot)
![image](https://github.com/jesseduffield/lazygit/assets/37420199/d5b6153c-159f-479f-b1f3-91c54183c71b)

**Describe the solution you'd like**
Remove  custom command from the suggestions list with a keybinding (perhaps `d` analogous to other actions).

**Describe alternatives you've considered**
I've looked in the docs if this already existed and tried to find in the open issues, but I didn't find anything.

**Additional context**
None, but thanks for the great product!

**Comment by mark2185** [comment]
Currently it's only possible through manual editing of `~/.config/lazygit/state.yml`.

I'm not sure what was the consensus last time, I guess it fell under "not worth the effort".

**Comment by TomDeneire** [comment]
That's already a fine solution, thanks! I would agree, it's easy enough to do like this, so I'll close this
