### ISSUE TITLE
Not enough space to render panels

### ISSUE THREAD

**Issue by mia0x75** [jesseduffield/lazygit#312]
$ lazygit
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xb0 pc=0x96cf27]

goroutine 1 [running]:
github.com/jesseduffield/lazygit/vendor/github.com/jesseduffield/gocui.(*keybinding).matchView(...)
        /src/github.com/jesseduffield/lazygit/vendor/github.com/jesseduffield/gocui/keybinding.go:38
github.com/jesseduffield/lazygit/vendor/github.com/jesseduffield/gocui.(*Gui).execKeybindings(0xc4202803f0, 0x0, 0xc42025bc58, 0x96c14d, 0x0, 0x0)
        /src/github.com/jesseduffield/lazygit/vendor/github.com/jesseduffield/gocui/gui.go:688 +0xa7
github.com/jesseduffield/lazygit/vendor/github.com/jesseduffield/gocui.(*Gui).onKey(0xc4202803f0, 0xc42025bc58, 0xc42000ee20, 0xc4202dc100)
        /src/github.com/jesseduffield/lazygit/vendor/github.com/jesseduffield/gocui/gui.go:650 +0x1b3
github.com/jesseduffield/lazygit/vendor/github.com/jesseduffield/gocui.(*Gui).handleEvent(0xc4202803f0, 0xc42025bc58, 0xc42025bc50, 0x0)
        /src/github.com/jesseduffield/lazygit/vendor/github.com/jesseduffield/gocui/gui.go:431 +0x40
github.com/jesseduffield/lazygit/vendor/github.com/jesseduffield/gocui.(*Gui).MainLoop(0xc4202803f0, 0xc4202803f0, 0x0)
        /src/github.com/jesseduffield/lazygit/vendor/github.com/jesseduffield/gocui/gui.go:391 +0x2e4
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).Run(0xc4202da000, 0x0, 0x0)
        /src/github.com/jesseduffield/lazygit/pkg/gui/gui.go:397 +0x2cb
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).RunWithSubprocesses(0xc4202da000)
        /src/github.com/jesseduffield/lazygit/pkg/gui/gui.go:406 +0x2f
main.main()
        /src/github.com/jesseduffield/lazygit/main.go:53 +0x12e

**Comment by glvr182** [comment]
Reproduced it as following:
1. Open lg in a small terminal (not enough space)
2. Press q or ctrl+c for example
3. Experience crash

**Comment by glvr182** [comment]
Found the error: currentView is not set at the start

**Comment by glvr182** [comment]
Issue can be closed as soon as #314 is merged

**Comment by glvr182** [comment]
@mia0x75 @jesseduffield this issue can be closed
