### ISSUE TITLE
[Help] lazygit incorrectly recognized `git --version`

### ISSUE THREAD

**Issue by mantle2048** [jesseduffield/lazygit#3128]
**Describe the bug**

`lazygit` did not recognize the updated git version.

**To Reproduce**

I am using a centos7.8 server without root.

The git version on the server is low (v1.8.3.1), and I downloaded a newer version (v2.37.1) of git and placed it in `~/.local/bin`.
  
Then I installed a binary release of `lazygit` in `~/.local/bin` and run `lazygit`.

But `lazygit` did not catch the updated git version.

```
2023/11/24 13:52:35 Git version must be at least 2.20 (i.e. from 2018 onwards). 
Please upgrade your git version. Alternatively raise an issue at https://github.com/jesseduffield/lazygit/issues for lazygit to be more backwards compatible.
```

**Screenshots**
- `lazygit --debug` & `lazygit --logs`

![image](https://github.com/jesseduffield/lazygit/assets/37854077/e2023839-632c-4ad1-87c0-9764413510de)

**Expected behavior**

`lazygit` should identify correct version and location of git and run correctly.

**Version info:**
- `which lazygit`
```
~/.local/bin/lazygit
```
- `lazygit --version`
```
commit=5e388e21c8ca6aa883dbcbe45c47f6fdd5116815, build date=2023-08-07T14:05:48Z, build source=binaryRelease, version=0.40.2, os=linux, arch=amd64, git version=1.8.3.1
```
- `which git`
```
~/.local/bin/git
```
- `git --version`  
```
git version 2.37.1
```
- `/usr/bin/git --version`
```
git version 1.8.3.1
```

**Comment by stk-ableton** [comment]
It seems to me that the problem is not with how lazygit parses the git version, but about which git binary is found by lazygit. It would be good to log the result of the `git --version` call to confirm this.

I don't know how this can happen, as you show that `which git` does find the correct version. The only explanation I can imagine is that you set your PATH only in your shell, but didn't export it, so that lazygit doesn't know to look in `~/.local/bin`.

What does `env | grep PATH` return?

**Comment by mantle2048** [comment]
Hi, thanks for the reply. Here is the `env | grep PATH` return:

![image](https://github.com/jesseduffield/lazygit/assets/37854077/99fcf697-c549-48a1-a752-dc2df25dff0d)

It seems that `~/. local/bin` does in `PATH`.

It's indeed a bit strange and I will try to reproduce it on another laptop to see is this a problem with lazygit or just with my server.

**Comment by mantle2048** [comment]
Okay, I don't know what happened, but `lazygit` is all right now after I ssh to the server again.😂

**Comment by mantle2048** [comment]
Haha, I just use the newest binary release of git provided on the server.
