### ISSUE TITLE
Wrong commit renamed when search pattern exists

### ISSUE THREAD

**Issue by Bekaboo** [jesseduffield/lazygit#3146]
**Describe the bug**

**To Reproduce**

1. Use default/no config
2. Open lazygit in a git repo
3. Goto commit panel, search for a pattern
4. Move cursor to a commit that does not match the pattern
5. Press `r` to rename
6. Press enter, the first commit that matches the search instead of the commit under the cursor got renamed

**Expected behavior**

When a search pattern exists in the commit panel, renaming commit will change the commit message of the first commit matching the search pattern instead of the commit under the cursor.

**Screenshots**
1. Open lazygit in a git repo
    ![image](https://github.com/jesseduffield/lazygit/assets/76579810/3356cdd9-4266-4fb2-9730-f3b58c6700c7)
2. Search for a pattern, e.g. `2nd`
    ![image](https://github.com/jesseduffield/lazygit/assets/76579810/1eb3c970-65c6-40c3-b752-cc118277ae01)
3. Move the cursor to the top, press `r` to rename the lastest commit (with message `3rd`) to `zzz`
    ![image](https://github.com/jesseduffield/lazygit/assets/76579810/139374d7-f66d-47da-b2a2-7fc6ccfc9fdc)
    ![image](https://github.com/jesseduffield/lazygit/assets/76579810/e18170e3-b523-4c6c-9f12-88d79efcf847)

7. Press enter, the second commit instead of the lastest commit got renamed
   ![image](https://github.com/jesseduffield/lazygit/assets/76579810/786be151-a8d5-481e-b439-e6e7fd720e9f)

**Version info:**
_Run `lazygit --version` and paste the result here_

```
commit=v0.40.2, build date=2023-08-12T17:47:33Z, build source=binaryRelease, version=0.40.2, os=linux, arch=amd64, git version=2.43.0
```

_Run `git --version` and paste the result here_

```
git version 2.43.0
```

**Additional context**

Besides this bug, it is quite annoying when I press `/` to search for something if there exists a previous search pattern -- I have to use `<C-u>` to delete the old pattern manually and then start new searching. Is there any way to prevent lazygit from automatically inserting previous search patterns when pressing `/`?

**Note:** please try updating to the latest version or [manually building](https://github.com/jesseduffield/lazygit/#manual) the latest `master` to see if the issue still occurs.

**Comment by mark2185** [comment]
Both of these things have been fixed are on current `master`, they're just waiting for a release (most likely not before the end of year).

I suggest building from source in the meantime!

**Comment by Bekaboo** [comment]
Thanks, building from source fix this issue
