### ISSUE TITLE
pre-commit not found even if present in python virtual environment

### ISSUE THREAD

**Issue by Djedouas** [jesseduffield/lazygit#3149]
**Describe the bug**

When doing a simple thing like renaming a commit, upon validation I get the error `/usr/bin/python: No module named pre_commit`

![image](https://github.com/jesseduffield/lazygit/assets/34267385/ae283645-eba2-4990-822e-ba32a6cb2e6c)

pre-commit is **not** installed widely on my system, but installed individually in each of my python virtual environments.

**To Reproduce**

1. Activate a python virtual environment with pre-commit installed with pip
2. Try `python -m pre_commit`, see that it works
3. Try `pre-commit`, see that it also works
4. Try to rename a commit in lazygit, see the error described above

**Version info:**

commit=5e388e21c8ca6aa883dbcbe45c47f6fdd5116815, build date=2023-08-07T14:05:48Z, build source=binaryRelease, version=0.40.2, os=linux, arch=amd64, git version=2.34.1

git version 2.34.1

Ubuntu 22.04

**Comment by karimkhaleel** [comment]
Could you check what's inside your `.git/hooks/pre-commit` file?
The `INSTALL_PYTHON` variable is supposed to point to the environment that contains pre-commit.  From the error message pre-commit is showing, it looks like the environment is set to your system's python.

You can try manually modifying the `INSTALL_PYTHON` path in that file to point to your virtual environment instead.

**Comment by Djedouas** [comment]
My `.git/hooks/pre-commit` file is indeed pointing to the system's python. Why?

<details><summary>pre-commit file</summary>

```sh
#!/usr/bin/env bash
# File generated by pre-commit: https://pre-commit.com
# ID: 138fd403232d2ddd5efb44317e38bf03

# start templated
INSTALL_PYTHON=/usr/bin/python
ARGS=(hook-impl --config=.pre-commit-config.yaml --hook-type=pre-commit)
# end templated

HERE="$(cd "$(dirname "$0")" && pwd)"
ARGS+=(--hook-dir "$HERE" -- "$@")

if [ -x "$INSTALL_PYTHON" ]; then
    exec "$INSTALL_PYTHON" -mpre_commit "${ARGS[@]}"
elif command -v pre-commit > /dev/null; then
    exec pre-commit "${ARGS[@]}"
else
    echo '`pre-commit` not found.  Did you forget to activate your virtualenv?' 1>&2
    exit 1
fi
```

</details>

**Comment by karimkhaleel** [comment]
It depends on which environment the `pre-commit install` command was run from. You could try to uninstall the pre-commit hook with `pre-commit uninstall` and then recreate it using the environment pre-commit was installed with. This doesn't seem like it has anything to do with lazygit though.
