### ISSUE TITLE
Handle premissions denied

### ISSUE THREAD

**Issue by mjarkk** [jesseduffield/lazygit#316]
**Describe the bug**
In my work dir i have some files that need root permissions.  
When i open lazygit i see this error:  

**To Reproduce**
1. `mkdir test-lazygit/test -p`
2. `cd test-lazygit`
3. `sudo chown root:root test -R`
4. `sudo chown 700 test -R`
5. `lazygit`

**Expected behavior**
No premissions denied lines in the files pannel

**Screenshots**
In testing folder:  
![Screenshot 1](https://i.imgur.com/ahX6APM.png)  
In my work dir:  
![Screenshot 2](https://user-images.githubusercontent.com/15320763/47637027-af562c80-db5a-11e8-9443-3a542e278630.png)

**Desktop (please complete the following information):**
 - OS: **Linux, Fedora 28 (4.18.16-200.fc28.x86_64)**
 - Lazygit Version: **(latests commit from jesseduffield/lazygit) commit=, build date=, build source=unknown, version=unversioned, os=linux, arch=amd64**
 - The last commit id if you built project from sources: **I don't have git-ref installed**

**Comment by jesseduffield** [comment]
Any problem with simply skipping anything that has file permission issues @mjarkk ? And not showing them  in the files panel?

**Comment by mjarkk** [comment]
Nope that's perfect
