### ISSUE TITLE
Cherry picking specific files from a commit?

### ISSUE THREAD

**Issue by mikybars** [jesseduffield/lazygit#3168]
Can you tell me if this feature is implemented in some way or else it would be of interest to someone? For me at least it'd be.

**Comment by mark2185** [comment]
Would [this](https://github.com/jesseduffield/lazygit?tab=readme-ov-file#rebase-magic-custom-patches) help?

**Comment by mikybars** [comment]
Yeeees. This application doesn't stop to amaze me. Kudos 🙇🏾
