### ISSUE TITLE
lazygit not detecting git throwing unsupported git service

### ISSUE THREAD

**Issue by ManashX0PA** [jesseduffield/lazygit#3184]
I am trying to create a pull request from lazygit
My remote url pattern is "git@work:ManashDEMO/my_repo.git
But when I try to create the  pull request it throwing unsupported git service error
But if my remote url pattern is like this "https://github.com/ManashDEMO/my_repo.git" then it works
Assuming the SSH url pattern is not getting detected

Any way to fix this? Actually I have 3 accounts connected in my PC and would like to use lazygit for commiting across all those repos

**Comment by jwhitley** [comment]
The required settings for this are [in the documentation under custom pull request URLs](https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md#custom-pull-request-urls).  See an example of this configuration in #1794.

**Comment by ManashX0PA** [comment]
Thank you so much @jwhitley. It worked.
Wish you have a wonderful day up ahead : )

**Comment by mohammadazeemwani** [comment]
Just if anyone needs: 
For this `git@work:ManashDEMO/my_repo.git`, 
You would do 
```ini config.yml
services:
  'work': 'github:github.com'
```
