### ISSUE TITLE
Make some custom patch keybindings directly available in commit files view

### ISSUE THREAD

**Issue by jesseduffield** [jesseduffield/lazygit#3199]
**Is your feature request related to a problem? Please describe.**
Having to press ctrl+p to see the custom patch options is annoying, and we have plenty of keybinding realestate available in the commit files view.

**Describe the solution you'd like**
I propose that we add some keybindings to the commit files view for doing things with the custom patch:
* `shift+D`: remove the custom patch from the commit
* `n`: move patch out into a new commit
* `i`: move patch out into index

This matches the keybindings that are already in the menu except for 'd' which is currently reserved for removing individual files from the commit. I propose that we change the keybinding in the menu to shift+D so that things are kept consistent (regrettably, those with muscle memory to press `ctrl+p , d` will need to relearn but I think they'll be happy about the option for one less keypress.

There are a couple other keybindings:
* apply patch
* apply patch in reverse
* copy patch to clipboard

But I barely ever use these so I'm thinking we leave those in the menu.

**Comment by molejnik88** [comment]
I would like to pick this issue.
Is `CommitFilesController.GetKeybindings` a good starting point?
Do we need to move `handleDeletePatchFromCommit` from `CustomPatchOptionsMenuAction` to `CommitFilesController`?

**Comment by stefanhaller** [comment]
I have to say that I'm mildly opposed to this proposal. The local commits panel already has a ton of commands, adding more makes the important ones harder to find. Grouping some behind a menu is a good way to cut down in this.

I'm saying this as someone who uses custom patches **a lot** (I regularly use all the commands in the menu, except "y"), and the extra `<ctrl-p>` keypress has never bothered me.

**Comment by stefanhaller** [comment]
Oh wait, I see that you are talking about the commit files view. Is the proposal to make these extra commands only available there, but not in the commits panel? I would find this even more confusing (I usually leave the commit files view before invoking a custom patch command).

**Comment by jesseduffield** [comment]
@molejnik88 yep we'd want to move some handler functions out of pkg/gui/controllers/custom_patch_options_menu_action.go and into a new custom patch helper, to be used from both the custom patch options menu action and the commit files context.

@stefanhaller yep this would just be for the commit files panel, which conveniently has a small number of existing keybindings.

> I usually leave the commit files view before invoking a custom patch command

If we go through the proposed keybindings one by one, I think staying in the commit files view makes sense:
1) remove custom patch from commit: here I want to see which files remain after I remove the selected ones, and the commit files panel is the best place to see that
2) move patch into new commit: here I actually do want to see the newly created commit in the commits view after I perform the action, but that doesn't mean I should need to focus that view myself (see https://github.com/jesseduffield/lazygit/issues/3200)
3) move patch out into index: here I also want to see which files remain after I move out the patch, and there's no need to look at the commits view

Something I should have said in the OP: what prompted this feature request is that you can already press 'd' on a single commit file to remove it from the commit (a feature which predates custom patches), and now that we're introducing range-select, you'll be able to select a range of files and remove them all using the 'd' key, which is getting very close to selecting multiple files and removing them via a custom patch. So that's the reason I wanted to use `shift+D`: it lets you remove multiple files (and importantly, partial files) from the patch similar to what you can do with 'd' and it feels weird to have to go through a menu for this.

**Comment by stefanhaller** [comment]
> @stefanhaller yep this would just be for the commit files panel, which conveniently has a small number of existing keybindings.

I see. I still find it strange and inconsistent that
- the extra bindings are only available in one panel
- they are only available for some of the patch commands

Personally I just wouldn't do it for these reasons. (This is not a blocking objection though, if you feel really strongly that you want to have them.)

> If we go through the proposed keybindings one by one, I think staying in the commit files view makes sense:

This may make sense, but if I observe myself when working with custom patches, I see that I am often in arbitrary panels when invoking the commands (not necessarily the commits panel, and sometimes for no particular reason). I probably wouldn't do the extra mental work of deciding whether I can use the shorter keybinding in the particular situation I'm in, and would continue to always go through the menu.

One concrete example: for "move into index", if you have other unstaged modifications in one of the files that you are patching, the command will fail unless you stage them. This has happened to me more than once. In that case I move to the files panel, press `a` to stage everything, and then `<c-p> i` to extract the patch to the index.

> So that's the reason I wanted to use `shift+D`: it lets you remove multiple files (and importantly, partial files) from the patch similar to what you can do with 'd' and it feels weird to have to go through a menu for this.

I don't understand what feels weird about going through the menu for this, or why you want an extra new keybinding for it. The function is available as `<c-p> d` today, I use it often, and I would find an extra `shift-D` for it more confusing than helpful. It would feel like there's something special about this that makes it different from using a custom patch, somehow.

Speaking of `d` though, there's something else that I often wished was possible: discarding a line or selection range from a commit _without going through a custom patch_. I sometimes find myself selecting a line in the custom patch staging panel and pressing `d` to discard it (without staging it), and then I'm surprised that nothing happens. This would be very similar to what's possible in the files staging panel, and it would be useful to drop stray printf lines that you added for debugging. (For implementing this we'd probably create a custom patch behind the scenes, so the command would only be available if there's no custom patch yet.)

**Comment by jesseduffield** [comment]
Good points.

> Speaking of d though, there's something else that I often wished was possible: discarding a line or selection range from a commit without going through a custom patch. I sometimes find myself selecting a line in the custom patch staging panel and pressing d to discard it (without staging it), and then I'm surprised that nothing happens. This would be very similar to what's possible in the files staging panel, and it would be useful to drop stray printf lines that you added for debugging. (For implementing this we'd probably create a custom patch behind the scenes, so the command would only be available if there's no custom patch yet.)

This is interesting: I agree that this would be a good feature. But then we would have two ways of doing custom patch actions without explicitly creating a custom patch (deleting lines from a commit file and deleting individual commit files). 

But it sounds like you therefore have _some_ appetite for shaving off keypresses when it comes to custom patches. We already do this for commit files by letting you press 'd' on files to immediately remove them from the commit (and we'll extend that to selection ranges once that feature's in). What do you think about a feature where you can press 'i' on a file (or patch lines) to move it into the index (likewise with a range of files?). You can move files out to the index piecemeal (similarly to how you can delete stuff piecemeal) so it would reduce mental friction compared to having to select everything, then perform the action (even if it ends up taking longer due to slowness of rebases). I'm thinking of the situation where you think 'whoops I wasn't meant to commit that file'.

**Comment by stefanhaller** [comment]
> But then we would have two ways of doing custom patch actions without explicitly creating a custom patch (deleting lines from a commit file and deleting individual commit files).

Yes. I think both of these make sense as standalone commands because they are both using the `d` key which is such a generic concept in lazygit (delete/drop/discard whatever is currently selected). Which I love, btw.

I think `i` doesn't warrant its own command, since it's not a generic concept like that. I'd just use a custom patch normally for the scenario you describe, and I wouldn't have any problem with that.

**Comment by jesseduffield** [comment]
Fair enough. I'll close this issue and revisit after working with range-select some more (i.e. to see if it annoys me that there isn't a faster way to do things with it)
