### ISSUE TITLE
Tree view

### ISSUE THREAD

**Issue by Ashraf-Ali-aa** [jesseduffield/lazygit#32]
Hi would it be possible to add a tree view to lazygit that way you can visually see branch history
`git log --color --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit`

**Comment by jesseduffield** [comment]
I'm thinking I might just default to showing the graph when you're in the branch panel, given that if you want to see individual code changes, you can check it out and look through the commits panel. Given that people haven't warmed up to it too much, I hope I'll be forgiven for the design change, and if not I can't make it a configurable option in the future

**Comment by jesseduffield** [comment]
implemented in https://github.com/jesseduffield/lazygit/commit/a02d3a0c4ee6d5bb8e3365cb7bf7934f9b3a9a77
