### ISSUE TITLE
reset using `g` command not working

### ISSUE THREAD

**Issue by geneaky** [jesseduffield/lazygit#3209]
**Describe the bug**

**To Reproduce**

at local branch pannel -> push `g` -> select reset option -> not work

**Expected behavior**

to be reset
**Screenshots**
![image](https://github.com/jesseduffield/lazygit/assets/53224348/d8dbd5df-9328-4b2c-9b04-06a2f5a2d89f)

**Version info:**
_Run `lazygit --version` and paste the result here_
_Run `git --version` and paste the result here_
lazygit --version
commit=, build date=, build source=homebrew, version=0.40.2, os=darwin, arch=arm64, git version=2.39.2 (Apple Git-143)

git --version
git version 2.39.2 (Apple Git-143)

**Additional context**

**Note:** please try updating to the latest version or [manually building](https://github.com/jesseduffield/lazygit/#manual) the latest `master` to see if the issue still occurs.

**Comment by mark2185** [comment]
That's because you're resetting it to the local version of the branch, `git reset --hard master`, and I'm guessing you want to reset to the upstream?

In that case, go to the `Files` panel and press `g` there, you'll see the reset refers to `@{upstream}`.

**Comment by geneaky** [comment]
ah~ Thank you!!
