### ISSUE TITLE
Question about github.com/jesseduffield/gocui fork

### ISSUE THREAD

**Issue by VojtechVitek** [jesseduffield/lazygit#321]
Hi,
thanks for this project!

Just a general question about gocui and a fork which is vendored in this repo. I see github.com/jesseduffield/gocui has some interesting commits on top of the original repository. Do you plan to submit a PR against upstream?

Thanks,
Vojtech

**Comment by glvr182** [comment]
Tagging @jesseduffield so he can answer

**Comment by jesseduffield** [comment]
I probably should; most of the stuff I've committed has been fairly specific to the logic of lazygit, but I can see how others might want e.g. a panel subtitle, or keybindings restricted to one panel at a time, but the latter would need some more work to generalise it and make it configurable before it would be worthy of a PR. I'm in a fairly busy phase right now but when I've got some more time on my hands I'll look at putting up some PRs :)

**Comment by glvr182** [comment]
@VojtechVitek Is your question answered?

**Comment by mjarkk** [comment]
I think this issue can be closed because jroimartin's repo seems to be un-maintained,  
Jesse's fork is now merged into a community maintained fork located here: [awesome-gocui/gocui](https://github.com/awesome-gocui/gocui)  
Aside from Jesse's improvements it also has plenty of other improvements.

**Comment by VojtechVitek** [comment]
Let's close then :)
