### ISSUE TITLE
Branches panel push/pull indicator reposition

### ISSUE THREAD

**Issue by esfox** [jesseduffield/lazygit#3211]
**Is your feature request related to a problem? Please describe.**
I have a 1920x1080 resolution screen and usually, I have my terminal on one half of it and code on the other half. With this setup, I have an experience where having long branch names makes the indicator for the number of commits to push/pull not visible anymore, as shown below.
![image](https://github.com/jesseduffield/lazygit/assets/18418806/fc4d80be-9b02-4306-beac-bc80bc5df71b)

**Describe the solution you'd like**
I believe that repositioning the push/pull indicator to the left, as in after the last update time display, might alleviate this problem.

**Describe alternatives you've considered**
A workaround I do is just enlarge my terminal window or the "Local Branches" panel itself.

I apologize if this is a duplicate of an existing issue.

**Comment by stefanhaller** [comment]
This is already fixed on master. We now truncate long branch names as necessary to make room for the pushable/pullable indicator.
