### ISSUE TITLE
Configurable Pull request URL

### ISSUE THREAD

**Issue by internetimagery** [jesseduffield/lazygit#322]
**Describe the solution you'd like**
I've started experimenting with this awesome tool at work, and it's going great! One thing however I've noticed is that I cannot use the pull request feature.

I'm using it in a closed off network, with a custom gitlab setup, so of course the built in gitlab url doesn't appear, nor would it help if it did.

It would be awesome if the config could accept some "name: url:" parameters for custom pull request links.

Thanks again for the project. I love the simplicity and usability!

**Comment by TheMightyMat** [comment]
Yes this is an issue I have as well! Having this configurable from config.yml would be very useful!

**Comment by nakabonne** [comment]
I would like it as well!

**Comment by mjarkk** [comment]
we could also maybe detect what kind of server we are dealing with on the fly:    
- For github, gitlab, bitbucket we can detect it by the url
- For selfhosted gitlab check: `https://server.url/api/v4` and `https://server.url/api/v4/version`
- For gitea and gogs check: `https://server.url/api/v1/version`

**Comment by jesseduffield** [comment]
@mjarkk that sounds good to me. Are there any cases where we wouldn't be able to derive the url from the repo itself? If there are, then we'll need to add support for per-repo urls in the config.

**Comment by mjarkk** [comment]
ya there are some caveats to this, this won't work if:  
- The git server has a different domain name for git over ssh
- The API for the git server is implemented under a different domain name like the public gitlab (by default this is not the case with gitlab)

But for those cases we can show a popup with a list of the git servers we support.

**Comment by wwmoraes** [comment]
> * The git server has a different domain name for git over ssh

My case exactly. So to solve that, I came up [with this change](https://github.com/wwmoraes/lazygit/commit/d99dca806a38a319af662f43104fdc28d49b2371). The config.yml file looks like this:

```yaml
services:
  "gitlab.<myWorkDomain>": "https://gitlab.<myWorkDomain>/%s/%s/merge_requests/new?merge_request[source_branch]=%s"
  "git.<myWorkDomain>": "https://gitlab.<myworkDomain>/%s/%s/merge_requests/new?merge_request[source_branch]=%s"
```

That's definitely not the best way as it exposes the format string, which can lead to awfully wrong URLs, and also tightly couples the config string . So, some sort of refactoring is needed, e.g. create a `ServiceType` with a domain-variable format string, and then use those on the `Service` (fixed and user-added) by just pointing the type.

**Comment by wwmoraes** [comment]
[Here's the refactored option](https://github.com/wwmoraes/lazygit/commit/f92fa0587bd9216ca4401756c262b69b72470952), which allows this kind of configuration:

```yaml
services:
  "gitlab.<myWorkDomain>": "gitlab:gitlab.<myWorkDomain>"
  "git.<myWorkDomain>": "gitlab:gitlab.<myWorkDomain>"
```

P.S.: Also [I've fixed](https://github.com/wwmoraes/lazygit/commit/87ab46f8eb2e73c365a0cb509745bf9bbf74191e) the `getRepoInfoFromURL` function. as GitLab allows grouping, e.g. team/group-of-projects/project1. Let me know if I should cherry-pick that into a separate PR.

**Comment by craftyguy** [comment]
@wwmoraes did you submit a merge request for this?

**Comment by wwmoraes** [comment]
@craftyguy no I didn’t as I diverged my attention on other matters. I’ll pick it up in the morning, do some rebasing and submit 🚀 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
