### ISSUE TITLE
Panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by Lqlsoftware** [jesseduffield/lazygit#324]
**Describe the bug**
I found this panic, and by the time i'm try reproducing it, I found a another panic.
panic: fatal: Unable to create '/Users/robinlu/Documents/GitHub/feed-adjust-etl/.git/index.lock': File exists.
panic: runtime error: invalid memory address or nil pointer dereference

**To Reproduce**
1. Open lazygit in any repo
2. Checkout file by file quickly
3. Speed up checkout

**Expected behavior**
Checkout OK.

**Screenshots**
![image](https://user-images.githubusercontent.com/19875776/48176778-a2042380-e34c-11e8-9646-224b782c7e80.png)
![image](https://user-images.githubusercontent.com/19875776/48176746-7a14c000-e34c-11e8-8146-2b0a2b3c0d7e.png)

**Desktop (please complete the following information):**
 - OS: macOS Mojave 10.14
 - Lazygit Version v0.4
 - The last commit id if you built project from sources (I use brew cask to install lazygit)

**Additional context**
I think it's because lazygit use index.lock file to make a lock?

**Comment by jesseduffield** [comment]
I've been getting this too. There are definitely ways you can cause issues doing too many git commands at once due to the index.lock file, but yeah I think the nil pointer issue is a separate thing. I'm not really sure how best to debug this. I'll spend some time doing some digging.

**Comment by jesseduffield** [comment]
closing in favour of https://github.com/jesseduffield/lazygit/issues/652 (I haven't forgotten about this issue though!)

**Comment by Lqlsoftware** [comment]
Great! nice to see you found the reason for this issue. It's been a long time (almost two years) lol.
