### ISSUE TITLE
Change view/tab in selected pane

### ISSUE THREAD

**Issue by canhazcodez** [jesseduffield/lazygit#3242]
First of all, I am SORRY if this has been posted before, my modest search skills couldn't find anything when looking through issues.

I am trying to figure out what the keyboard keys are, that would allow me to change from local branches to remotes or tags within the pane that usually shows the branches. 
Same goes for the commits / Reflog pane and for the files/worktrees/submodules pane.

And to not bother you guys with more mundane questions, aside from trying to find the solution in the code, what other way is there to finding things like that out on my own?

Thank you so much in advance.

NOTE: Jesse (and everyone/anyone who contributed), you have changed the way I git and I am so thankful for lazygit!!

**Comment by stefanhaller** [comment]
> what other way is there to finding things like that out on my own?

Press `?` to open the menu with all keybindings. Scroll down a bit, you'll find the answer at the end of the "Global" section.

**Comment by canhazcodez** [comment]
@stefanhaller thank you so much for the answer.

It seems to me that I thought of looking through the code first BEFORE looking through the existing help.
I shall remember this answer to never bother others with mundane questions again.

❤️
