### ISSUE TITLE
Support range select for adding multiple commit files to patch

### ISSUE THREAD

**Issue by jesseduffield** [jesseduffield/lazygit#3251]
Currently you can press space on a file in the commit files view (which you access by pressing enter on a commit) in order to add it to a custom patch. However, range-select is not supported.

We recently added range-select support for staging multiple files in the files view (see https://github.com/jesseduffield/lazygit/pull/3248), so it should be straight-forward to copy the approach for adding commit files to a patch.

**Comment by afhoffman** [comment]
I wouldn't mind taking a shot at this one.

**Comment by jesseduffield** [comment]
Sure thing @afhoffman, let me know if you need any pointers :)

**Comment by afhoffman** [comment]
Awesome, thank you!

**Comment by afhoffman** [comment]
I think I was able to get the core functionality working, but ran into a bug that I need to turn over to someone with deeper understanding: #3258.
