### ISSUE TITLE
Retrying a multi-line commit move "commit description" to "commit summary" panel

### ISSUE THREAD

**Issue by watson28** [jesseduffield/lazygit#3252]
**Describe the bug**
When Retrying a multi-line commit, the initial content of the "commit description" appears in the "commit summary".

**To Reproduce**

1. add changes (that makes a pre-commit fail)  and stage them.
2. in files panel, press "c" to Create a commit using the "commit summary" and "commit description" panels
3. Commit fails because of 1.
5. in the files panel, press "c" to try to commit the changes again.

**Expected behavior**
The "commit summary" and "commit description" are populated with the initial values.

**Actual behavior**
the "commit description" first line appears in the "commit summary."  

**Screenshots**
<img width="889" alt="first commit" src="https://github.com/jesseduffield/lazygit/assets/2602588/a06fe97d-6ccc-4e97-9834-5f068491383f">

<img width="891" alt="retry commit 2" src="https://github.com/jesseduffield/lazygit/assets/2602588/0c01f253-0173-494c-b086-2a541a2bc07b">

**Version info:**
commit=, build date=, build source=unknown, version=0.40.2, os=linux, arch=arm64, git version=2.41.0
git version 2.41.0

**Additional context**
If I try to commit a third time, then the "commit summary" and "commit description" are shown correctly.

**Comment by stefanhaller** [comment]
Already fixed on master, see #3170.

**Comment by watson28** [comment]
Great. I will close this and wait for the next release, hopefully soon 🙏 .
