### ISSUE TITLE
Support range select for removing multiple files from a commit with 'd'

### ISSUE THREAD

**Issue by jesseduffield** [jesseduffield/lazygit#3260]
**Is your feature request related to a problem? Please describe.**
You can currently remove a file from a commit with 'd' without needing to explicitly make a custom patch. It would be good if this can support a selection range.

**Describe the solution you'd like**
When you select a range of files in the commit files view and press 'd', you can remove all the selected files from the commit in one go. We'll need to update the wording on the confirmation popup to say 'the selected file(s)' rather than 'this file'.

This should wait for https://github.com/jesseduffield/lazygit/pull/3259 to be merged because it will be making use of some of that PR's code.

**Comment by jesseduffield** [comment]
let me know if you wanna take this one @afhoffman

**Comment by afhoffman** [comment]
> let me know if you wanna take this one @afhoffman

Sure! I'd be happy to.
