### ISSUE TITLE
Squash all fixups in current branch

### ISSUE THREAD

**Issue by stefanhaller** [jesseduffield/lazygit#3263]
Now that we have 'i' for conveniently starting an interactive rebase of the current branch, I want the same for squashing fixups. I don't want to have to care about selecting a commit to start from, just an automatic "squash all fixups in my current branch" command.

To do that, we should rename `Squash all 'fixup!' commits above selected commit (autosquash)` to just `Squash 'fixup!' commits (autosquash)`; instead of showing a confirmation prompt it should show a menu with the choices "all fixups above the selected commit" and "all fixups in current branch".

For backwards compatibility and muscle memory the menu entries need to be in that order, so that `shift-S enter` does the same thing as before. On the other hand, I find "all fixups in current branch" much more useful and I expect to use it by default most of the time, so I'm inclined to make it the default and break compatibility. With #3261, maybe it's acceptable.

**Comment by stefanhaller** [comment]
I'm already in the middle of working on this, but I'm a bit time constrained right now and can't promise when it's done. Just filing it so that we can track it in #3262.

**Comment by jesseduffield** [comment]
Machiavelli says:
> Injuries, therefore, should be inflicted all at once, that their ill savour being less lasting may the less offend; whereas, benefits should be conferred little by little, that so they may be more fully relished.

Given this wisdom, and given how many other things which break muscle memory will be in this release, now would be the time to break muscle memory. I say we do it and see if anybody complains and use that to inform us for future decisions
