### ISSUE TITLE
Get Lazygit to automatically install on lunarvim?

### ISSUE THREAD

**Issue by stefanaerospace** [jesseduffield/lazygit#3268]
**Topic**
Lunarvim by default has a slot in it's UI for lazygit...but by default it doesn't do anything if lazygit isn't preinstalled.

**Your thoughts**
It'd be nice if this could be packaged in with lunarvim, or at least available with the Mason package manager.

I wasn't sure if you were aware of how popular you are with those folks :-)

**Comment by jwhitley** [comment]
I’d previously thought of [Mason](https://github.com/williamboman/mason.nvim) as primarily for LSP, DAP, etc. tools, but it does seem there’s at least a little precedent for other dev toolchain stuff.  E.g. GitHub’s gh cli tool [does show up in the Mason registry](https://github.com/mason-org/mason-registry/blob/main/packages/gh/package.yaml). So a lazygit package in Mason seems in-scope. I do note that lazygit is mentioned prominently in LunarVim’s [install docs](https://www.lunarvim.org/docs/installation#optional-feature-prerequisites).

I’m not familiar with LunarVim, but I’d be very surprised if a Neovim distro packaged platform-specific binaries. The docs simply have a list of usual suspects that it depends on (git, make, pip, python, etc. etc). Again, that’s what Mason or platform package managers are for.

For what it’s worth, I came to lazygit by way of [LazyVim](https://www.lazyvim.org/)’s integration. I suspect I found out the dependency either via the docs, or from LazyVim’s checkhealth command.

**Comment by stefanaerospace** [comment]
If you install lunarvim (which is a preconfigured neovim), press space, wait a moment and a menu will appear. Press g for 'Git', then g again for LazyGit, nothing will happen. It'd be nice if something did though without having to preinstall it.

**Comment by jwhitley** [comment]
That's not unreasonable, but I think that's an issue best filed directly on [LunarVim's repo](https://github.com/lunarvim/lunarvim) to improve that UX. Looks like a pretty easy change, adding some user guidance to [terminal.lua](https://github.com/LunarVim/LunarVim/blob/e85637c2408264f2591b9c9bca073cd58d314a97/lua/lvim/core/terminal.lua#L149) if lazygit isn't installed.

**Comment by jesseduffield** [comment]
I agree. Having better integration with neovim is definitely a goal of mine, though this specific issue isn't something lazygit has control over so I'll close this off
