### ISSUE TITLE
Allow user-configurable warning branches

### ISSUE THREAD

**Issue by jesseduffield** [jesseduffield/lazygit#327]
**Is your feature request related to a problem? Please describe.**
I just accidentally pushed straight to master at work because I forgot to create a hotfix branch. I rarely need to push directly to master at my job, so it makes sense to have a warning pop up saying 'are you sure you want to push directly to master?'

**Describe the solution you'd like**
a popup warning asking if you're sure you want to push to the branch if it's in a configurable list of warning branches

**Describe alternatives you've considered**
Being more conscientious as a human being rather than depending on my tool to compensate for me

**Comment by glvr182** [comment]
I think this should be left for the remotes using protected branches.

**Comment by jesseduffield** [comment]
I have admin permissions to push to master though, but I want a popup confirmation in lazygit when I do so. Does protected branches provide that functionality?

**Comment by jesseduffield** [comment]
I reckon this can be closed, it is indeed better to configure permissions in git itself
