### ISSUE TITLE
Support range select for amending commit attributes

### ISSUE THREAD

**Issue by jesseduffield** [jesseduffield/lazygit#3273]
**Is your feature request related to a problem? Please describe.**
Currently when you press 'a' on a commit, you see a menu with options to reset the commit author, amend the commit author, and add a co-author in the commit message.

![image](https://github.com/jesseduffield/lazygit/assets/8456633/9db4aede-9b64-4a35-987f-f689a2ee8221)

But this only works for individual commits. If you want to add a co-author for a range of commits, you'll need to perform the action on the commits one-by-one.

**Describe the solution you'd like**
Support these three actions for a range of commits.

**Additional context**
For reference, here's the PR which added the ability to add a co-author to an individual commit https://github.com/jesseduffield/lazygit/pull/2912

I don't believe we yet have a way of saying that you want to perform a specific action on a range of commits as part of a rebase, so we that may need to be added as part of this work.

**Comment by AzraelSec** [comment]
I'd like to work on this, if possible :)
