### ISSUE TITLE
How can I change the color of the selected line inside the "Unstaged changes" pane?

### ISSUE THREAD

**Issue by EddieBrunstedt** [jesseduffield/lazygit#3292]
**Topic**
How can I change the color of the selected line inside the "Unstaged changes" pane?

I can change the selected line color for all panes on the left-hand side using `selectedLineBgColor` but this has no effect on the selected lines in the pane where I can stage/unstage lines in a file.

I am referring to the cyan-ish line seen here:

![2024-02-01_16-44](https://github.com/jesseduffield/lazygit/assets/7594223/44cadcea-0786-4c2d-9c2a-c74e1e00b65f)

**Comment by stefanhaller** [comment]
See https://github.com/jesseduffield/lazygit/discussions/3239.

**Comment by EddieBrunstedt** [comment]
Thank you kind sir!

Fixed by setting `selectedRangeBgColor` in my config.

**Comment by EddieBrunstedt** [comment]
Thank you kind sir!

Fixed by setting selectedRangeBgColor in my config.

**Comment by EddieBrunstedt** [comment]
Thank you kind sir!

Fixed by setting `selectedRangeBgColor` in my config.
