### ISSUE TITLE
custom pager not used in staged/unstaged split view

### ISSUE THREAD

**Issue by owzim** [jesseduffield/lazygit#3297]
**Describe the bug**

when using delta

```yml
git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
```

It is correctly used, in this unsplit view

![image](https://github.com/jesseduffield/lazygit/assets/1720088/b1299eb1-ba1d-40a6-9a28-f64ad63f952d)

but not in this staged/unstaged split view

![image](https://github.com/jesseduffield/lazygit/assets/1720088/cd6c504a-7fe1-441d-b53b-170c92b32539)

**Expected behavior**

the configurable diff renderer should be applied to all panels/views where diffs are used

**Version info:**

```
commit=5e388e21c8ca6aa883dbcbe45c47f6fdd5116815, build date=2023-08-07T14:05:48Z, build source=binaryRelease, version=0.40.2, os=darwin, arch=amd64, git version=2.37.3
```

> **Note:** please try updating to the latest version or [manually building](https://github.com/jesseduffield/lazygit/#manual) the latest `master` to see if the issue still occurs.

I did, same issue in the most recent master build

**Comment by stefanhaller** [comment]
Duplicate of #2563.

It's technically not possible. If you look at the bottom screenshot, you'll notice the blue line `@@ -1,4 +1,7 @@`, lazygit needs this to parse the diff correctly. It is missing in first screenshot (as well as the `+` and `-` characters at the beginning of lines, all of this is needed for parsing the diff).

(It would be possible to make it work by using something like `--color-only` in the case of delta; however, not all pagers have such an option.)

**Comment by owzim** [comment]
@stefanhaller thanks closing it in favor of #2563 and #2117
