### ISSUE TITLE
difft not working as an external diff

### ISSUE THREAD

**Issue by shauryagoel** [jesseduffield/lazygit#3304]
**Topic**
I am trying to use difft as mentioned [here](https://github.com/jesseduffield/lazygit/blob/master/docs/Custom_Pagers.md#using-external-diff-commands). However, there is no effect when doing so as unstaged changes diff is same. Here is my config- 
```
git:
  paging:
    externalDiffCommand: difft --color=always
```
MacOS: 14.1.2
Lazygit version: 0.40.2
Difftastic version: 0.53.1
Git version: 2.39.3

**Comment by stefanhaller** [comment]
`externalDiffCommand` was only added after 0.40.2 was released. You'll have to use a master build to use it, or wait for the next release.
