### ISSUE TITLE
Icons not displayed in tmux popup

### ISSUE THREAD

**Issue by pentago** [jesseduffield/lazygit#3319]
**Describe the bug**
When using regularly, icons are displayed properly, just not when launchign lazygit from the tmux terminal via `tmux popup lazygit`

**To Reproduce**
Launch lazygit instance fom within tmux popup with tmux terminal via `tmux popup lazygit`

**Expected behavior**
Display nerd font icons normally.

**Version info:**
commit=, build date=, build source=homebrew, version=0.40.2, os=darwin, arch=amd64, git version=2.43.0
git version 2.43.0

**Comment by mark2185** [comment]
It's something due to the `TERM` variable, something something legacy something rabbithole.

Anyway, I don't have any such problems with this in my `~/.tmux.conf`:
```
set -g default-terminal "xterm-256color"
set -ga terminal-overrides ",xterm-256color:Tc"
```

**Comment by pentago** [comment]
Not sure, just tried your config on my setup (alacritty + tmux), didn't work:
regular:
![regular](https://i.imgur.com/YpGrtif.png)

popup:
![popup](https://i.imgur.com/G58lFfA.png)

**Comment by pentago** [comment]
I tweaked my shell startup flags (added `-i/--interactive`) which fixed the issue for me.
