### ISSUE TITLE
Feature Request: git checkout -p support

### ISSUE THREAD

**Issue by sundarv85** [jesseduffield/lazygit#332]
**Is your feature request related to a problem? Please describe.**
I’m trying to checkout a part of a file

**Describe the solution you'd like**
You can do so using `git checkout -p` option. See [here](https://stackoverflow.com/questions/6963129/is-it-possible-to-git-checkout-a-single-line-instead-of-the-entire-file)

Is this already possible with lazygit. If not, could this support be added (similar to the option t)

**Comment by jesseduffield** [comment]
I believe the functionality this involves is already covered by our new staging lines feature (in the sense that you can select a line or range of lines from your unstaged changes in a file and revert them).

If you'd still like to see some form of `git checkout -p` let me know :)
