### ISSUE TITLE
`[` `]` bindings not working within vscode terminal

### ISSUE THREAD

**Issue by bruchar1** [jesseduffield/lazygit#3366]
When opening lazygit from the vscode terminal, `[` and `]` navigation keys do not work. For instance, I'm not able to show Reflog when I am in the Commits panel. Running from the Windows Terminal application, things work as expected.

lazygit 0.4.0.2, on Windows.

**Comment by stefanhaller** [comment]
Works for me.

What's your keyboard layout, does it require Alt-Gr for accessing those keys? Might this be related to #2839? Could you try a master build?

**Comment by bruchar1** [comment]
Ok. This work when using a normal command prompt (in vscode). But not with my cmder command prompt (but works with cmder in the Terminal app).

Mouse does not work either in vscode terminal (both with cmder or with command prompt).

Anyway, this is probably related to a very complex and specific config. Sorry for the noise, and thank you for this wonderful app!
