### ISSUE TITLE
Fuzzy filtering is too fuzzy

### ISSUE THREAD

**Issue by stefanhaller** [jesseduffield/lazygit#3373]
Fuzzy filtering is a nice idea in principle, but when the data set is large and your search string is short, it doesn't work well.

As an example, we have almost 4000 remote branches at work; many developers use the convention of prefixing their branch names with their initials, e.g. `sh-some-cool-feature`. If I want to filter our remote branches to only mine, using the filter string `sh-`, it shows almost 800 unrelated matches, just because they contain the letters s, h, and - somewhere. This is useless. Using a substring search would only show my branches (plus very occasional false positives such as `xy-better-hash-table`).

However, often a simple substring search is not enough, because sometimes you know there are several words in the name but you don't know exactly where. For example, searching for `sh-cool` will find the branch `sh-some-cool-feature` using fuzzy filtering. To solve this, I'd propose to type these subwords separated by space (`sh- cool`), and it will do a substring search for each word separately, showing only results that match all. This can even be better than fuzzy searching, because typing `error check` will match both `better-error-checking` and `check-for-errors-more-thoroughly` (order doesn't matter). 

The question then is whether to make this optional, and how. I can see the following options:
1. Just change the behavior everywhere, unconditionally.
2. Provide a config option
  a. globally, for all views and prompts
  b. separately for each view and prompt (not sure how we would identify them)
3. let users choose while filtering, by recognizing special characters to change the behavior. For example, adding `=` at the beginning of your filter string could mean to search by substring (if fuzzy is the default), or `~` (similar to the "≈" symbol for "approximately") could mean to do a fuzzy search if substring searching is the default.

Needless to say, I'm in favor of option 1. 😄

Keen to hear your thoughts, @jesseduffield. BTW, this is also related to the discussion about retaining the sort order when filtering that we had in #3281; for example, [this scenario](https://github.com/jesseduffield/lazygit/issues/3281#issuecomment-1918936516) would no longer be an issue because `files_test` would only show the result you want, and you only get the others by saying `file test`, in which case it's probably good to show them in their natural order.

**Comment by stefanhaller** [comment]
Here's a quick-and-dirty PR: #3376. After testing it for a while I have to say that I greatly prefer this over fuzzy matching. I like how it filters the list down to show only relevant results much more quickly.

The only advantage of fuzzy matching might be that it's more forgiving to spelling errors; for example, if you want filter for Aaron Hoffman's commits, but don't remember whether it's Hoffman or Hofman, fuzzy searching can help with that. It's not a big deal though, because typing just "ho" already filters the list down to only the one matching name for me, whereas with fuzzy filtering it shows 12 matches, most of which are completely irrelevant.

**Comment by stefanhaller** [comment]
Adding some private discord discussion between Jesse and me here for everybody:

> Some concerns come to mind:
> - performance: how would this compare to doing a fuzzy search with a single string?

It's faster. Some very cursory, non-scientific tests: filtering for a single word in our list of 4000 remote branches takes 3ms with substring matching, 21ms with fuzzy searching.

It's different for filtering files, because the implementation is very different there. So far I only used a very simple, brute force implementation that walks the entire Trie; I haven't thought much about whether we can do something smarter with the prefix information, and I don't understand the implementation of VisitFuzzy enough to learn something from it. But it's still faster there, too: in our work repo (87000 files), substring filtering takes 52ms, fuzzy filtering takes 74ms.

> - ordering: would the order of substrings be preserved?

No, and I like that. Take your example of the gh-integration branch; maybe I don't remember whether it was called gh-integration or integrate-gh. Searching for either gh int or int gh with my approach finds both, whereas with fuzzy filtering only ghint finds it, but intgh doesn't.

> - familiarity: would people expect the search to work like fuzzy search in other apps?

That's a good question, I don't know. I talked to co-workers about all this, and some of them said they don't like the way fuzzy searching works in VS Code (for various reasons), so it doesn't sound like a good goal to behave exactly like it.

It may not be totally obvious that you now have to type a space between subwords, so maybe this would have to mentioned as a breaking change in the popup.

**Comment by stefanhaller** [comment]
@jwhitley @mark2185 @afhoffman @AzraelSec @karimkhaleel

For those of you who use filtering regularly: any opinion? It would be great if you could check out the PR linked above and try which of the two mechanisms works better for you.

**Comment by afhoffman** [comment]
@stefanhaller I just checked out #3376 and tried it on a repo where I had encountered a similar issue with filtering branch names. I haven't looked at any of the code in that pr yet, just checked the functionality.

The repo I checked it on has ~60 remote branches. The search string I'm using should return 3 branches. With sub-string search, I got exactly the branches I was looking for. Fuzzy search returns the 3 I'm looking for plus 13 false positives. I like the sub-string behavior _much_ better.

I also like that ordering of sub-strings is not preserved. If I have `feat/integration-test` and `feat/test-integration`, I think it's most helpful if the search string `integration test` matches both branches.

Enabling fuzzy search by prefixing with `~` could be useful, but I don't know how often I'd use it. Do you have any thoughts on how to document that if we leave it in? Maybe prepending something before `Filter:` in the status bar at the bottom?

As for familiarity, I'm personally not worried about it. I don't put much thought into how search behaves. I type in my search term and hope what I'm looking for is in the results. The only thing I find annoying with search in some applications is if they require a strange or complicated syntax.

This is looking great!

**Comment by karimkhaleel** [comment]
I don't have that many remote branches that I have to search through usually, so I haven't felt some of the pain points @stefanhaller has mentioned. The fuzzy remote branch filtering feature that lazygit has at the moment has been working fine for me so far.

I checked out https://github.com/jesseduffield/lazygit/pull/3376, and it has also been working just as well for me. I like that it preserves sort order.

Option 1 seems fine for me. All I need is just a way to find my branch with keywords.

**Comment by stefanhaller** [comment]
Note that this is not only about filtering branches. We filter things in other places too; if you have never used those before, it might be hard to form an opinion on what works better, but it might still be good to check them out and do some A/B testing. For example:
- filter commits by path. Type ctrl-s in the files panel, and pick "enter path to filter by". (In a big repo you may have to wait a while for files to be loaded.)
- filter commits by author. Again, ctrl-s in the files panel, but "enter author to filter by" this time.
- filter your custom commands when you type `:`
- filter the keybindings in the `?` menu

**Comment by karimkhaleel** [comment]
After playing around with it some more, especially with file path filtering, I prefer substring filtering to the fuzzy filtering algorithm in lazygit. Whenever I search for some file, I already just write out the fragments of words that I remember from the path. The only difference between what I did before and how I would have to adjust it for substring filtering is adding spaces between the word fragments.

**Comment by stefanhaller** [comment]
Fixed by #3376.
