### ISSUE TITLE
delta pager slow loading since 0.17.0

### ISSUE THREAD

**Issue by taras-biletskyi** [jesseduffield/lazygit#3405]
**Describe the bug**
There is a noticible slow down in delta pager after they released version 0.17.0.
That second of it loading for every file/commit grinds my gears a lot 🥲.

**Comment by taras-biletskyi** [comment]
nevermind... it's the theme flag(--dark/--light), its absence, that causes the slowdown

**Comment by farzadmf** [comment]
Thank you @taras-biletskyi ; it was driving me crazy! Do you know why that's happening without the flag?

**Comment by taras-biletskyi** [comment]
> Thank you @taras-biletskyi ; it was driving me crazy! Do you know why that's happening without the flag?

perhaps because they added auto terminal background detection in 0.17.0. That auto thing is triggered unless you explicitly specify the flag  `--light` or `--dark`. Did not look into it though.

**Comment by farzadmf** [comment]
Makes sense, but thank you anyways; was just about to give up on `delta` there 😁

**Comment by bash** [comment]
> perhaps because they added auto terminal background detection in 0.17.0

Yep, that was me. Sorry for breaking your setup!

For reference, here's the delta issue for the same thing: https://github.com/dandavison/delta/issues/1664

**Comment by stefanhaller** [comment]
Fixed by #3420.

**Comment by bluz71** [comment]
> nevermind... it's the theme flag(--dark/--light), its absence, that causes the slowdown

Thank you very much.

I very difficult issue to Google for, but I eventually found this. Issue totally solved via `--dark`.
