### ISSUE TITLE
Difftastic externalDiffCommand doesn't change the diff pager

### ISSUE THREAD

**Issue by raheelrjunaid** [jesseduffield/lazygit#3413]
**Bug Description**

Adding:
```yaml
git:
  paging:
    externalDiffCommand: difft --color=always
```
to the LazyGit config does function as expected (as outlined in #2868). Instead, it uses the default/built-in git pager.

https://github.com/jesseduffield/lazygit/assets/60077374/1ca346e2-f0d6-461c-9183-8a9d66ea104b

**To Reproduce**

1. Edit `~/Library/Application\ Support/lazygit/config.yml`
2. Add `externalDiffCommand` (or optionally, add it to your `~/.gitconfig` as the default `[diff]` tool and set `useConfig: true)
3. See that difftastic doesn't work. 

**Expected behavior**

The diff should display the following:

![CleanShot 2024-03-22 at 14 08 12@2x](https://github.com/jesseduffield/lazygit/assets/60077374/f64a1357-38f4-49a9-acf3-3c434d5cf9ef)

**Version info:**
```
build source = homebrew
version = 0.40.2
os = darwin
arch = arm64
git version = 2.44.0
```

**Additional context**

- I've confirmed the config is read upon instantiation by adding the `notARepository: 'quit'` parameter, which works as expected.
- I suspect there's something wrong with reading the config **after** `lazygit` is run considering that the above is true. `os.editPreset` also doesn't work for `lvim`

**Comment by stefanhaller** [comment]
This doesn't work in the 0.40.2 release yet. The docs describe the state of master, which isn't released yet. (It's gonna be real soon now.)
