### ISSUE TITLE
Automatically change directory to worktree location when switching worktrees

### ISSUE THREAD

**Issue by taylorthurlow** [jesseduffield/lazygit#3422]
When switching worktrees through lazygit, I expected the current directory of the underlying shell to change when I changed worktrees, but it doesn't. I suppose this could be less cut and dry, given that it's possible to, for example, use the `--path` argument to open lazygit from a different working directory.

**Comment by stefanhaller** [comment]
Processes can't change the directory of their parent shell directly, but you can achieve this with a trick; see https://github.com/jesseduffield/lazygit/tree/master?tab=readme-ov-file#changing-directory-on-exit.

**Comment by taylorthurlow** [comment]
Right, I suppose that makes sense. Sorry I wasn't able to find that section before creating this issue, I must not have done a good enough job searching. It works well for me - cheers.
