### ISSUE TITLE
Reword loads incorrect commit message/description with commit signing

### ISSUE THREAD

**Issue by chenasraf** [jesseduffield/lazygit#3425]
**Describe the bug**
Since I sign my commits via SSH (not sure if this reproduces with regular GPG signing), rewording a commit will prompt with the new commit message & description, but will incorrectly place values. It actually uses the signature verification as the message, and the message as the description, possibly losing the description. Here is a visible example:

Commit info:
![image](https://github.com/jesseduffield/lazygit/assets/167217/044b23a9-3b1a-4489-bb8f-35ceaade5c98)

Rewording said commit:
![image](https://github.com/jesseduffield/lazygit/assets/167217/0ba129de-8861-419a-9c4f-594209bf3813)

**To Reproduce**

1. Enable SSH signing for your git setup
2. Make any commit
3. Attempt to reword said commit
4. See the message/description values

**Version info:**
LazyGit version: `commit=3675570a391b1a49ddd198b4c7e71e17701d4404, build date=2024-03-23T09:09:11Z, build source=binaryRelease, version=0.41.0, os=darwin, arch=amd64, git version=2.39.3 (Apple Git-146)`
Git version: `git version 2.39.3 (Apple Git-146)`

**Additional context**

Related Git config:

```
log.showsignature=true
gpg.format=ssh
gpg.ssh.allowedsignersfile=~/.ssh/allowed_signers
commit.gpgsign=true
user.signingkey=[[MASKED]]
```

**Comment by stefanhaller** [comment]
Thanks for the report. Here's a fix: #3431. Would be great if you could test it if you know how to build from source.

**Comment by chenasraf** [comment]
Thanks for the fix! I will try it out soon and let you know

**Comment by chenasraf** [comment]
@stefanhaller Tested on my end and seems to be working great, definitely fixed the issue! Thanks!

**Comment by amaanq** [comment]
I can confirm that the fix works for me as well, finally :slightly_smiling_face:
