### ISSUE TITLE
Conflict during merge, lost last line of code after resolving conflict

### ISSUE THREAD

**Issue by pengatgstdev** [jesseduffield/lazygit#3444]
**Describe the bug**
Conflict during merge, lost last line of code after resolving conflict

**To Reproduce**

1. merge code
2. resolving conflict

**Screenshots**

![image](https://github.com/jesseduffield/lazygit/assets/19773374/ed7f8a04-c25c-4579-8ad7-045500882a5b)
![image](https://github.com/jesseduffield/lazygit/assets/19773374/321073ba-ea85-43d0-8ee2-40992bb4db7c)
![image](https://github.com/jesseduffield/lazygit/assets/19773374/5088e220-8feb-4cdc-bfda-01cad80a4503)
![image](https://github.com/jesseduffield/lazygit/assets/19773374/d8668c3d-d4a6-4a30-9d16-fe930a931605)

**Version info:**
`lazygit --version`
commit=3675570a391b1a49ddd198b4c7e71e17701d4404, build date=2024-03-23T09:09:11Z, build source=binaryRelease, version=0.41.0, os=linux, arch=amd64, git version=2.33.1
 `git --version`
git version 2.33.1

`uname -a`
Linux my 6.1.32-amd64-desktop-hwe #23.01.00.20 SMP PREEMPT_DYNAMIC Thu Jan 11 18:45:10 CST 2024 x86_64 GNU/Linux

**Comment by wlgemini** [comment]
+1

**Comment by Sticks-Stones** [comment]
+1

**Comment by wdixon-bzs** [comment]
+1

**Comment by mwebb-bzs** [comment]
+1

**Comment by stefanhaller** [comment]
As far as I can see, this happens whenever the file in question doesn't end with a line feed.

Here's a fix for that: #3976
