### ISSUE TITLE
Misrepresentation

### ISSUE THREAD

**Issue by vSEK1RO** [jesseduffield/lazygit#3472]
When you rename a folder, renaming of each file is displaying incorrectly

This thing is displayed into lazygit
![Screenshot_20240403_123111](https://github.com/jesseduffield/lazygit/assets/114253920/6df11643-847d-42bf-9a30-b6c0c51ab7e3)

But actually git dispay this
![Screenshot_20240403_123116](https://github.com/jesseduffield/lazygit/assets/114253920/ed1e1a96-523e-446e-be2a-ac4fc9bcd49e)

**Comment by fenguoerbian** [comment]
I think that's because in the lazygit file panel it is already shown what's in the `test` folder. So this matches the underline changes in this repo, but just a different way than git command line to visualize it.
