### ISSUE TITLE
[FR] Skip remotes list if there is only one remote

### ISSUE THREAD

**Issue by pinarruiz** [jesseduffield/lazygit#3483]
**Is your feature request related to a problem? Please describe.**
I usually work with single remote repos, it feels repetitive to have to press enter to enter to the remote when there is only one.

**Describe the solution you'd like**
Lazygit opens the only remote present for me.

**Describe alternatives you've considered**
- Having a remote set itself as default when you access it, so everytime you access a remote its left "open" on the tab

---

I don't know if this has already been discussed here, but could not find anything related.
Good work on lazygit, very cool and useful tool.

**Comment by mark2185** [comment]
To get a better understanding - could you please describe your workflow, why do you go so often to your remote panel?

**Comment by pinarruiz** [comment]
> To get a better understanding - could you please describe your workflow, why do you go so often to your remote panel?

Sure, lets say i have a repo that has dependabod configured, and i end up with x amount of branches:

![image](https://github.com/jesseduffield/lazygit/assets/37040888/cda5c7d0-6385-42d6-8b11-1d11107ea55c)

I might be doing something wrong, or not using the tool as is supposed, but if i want to check them all out i have to go go to the remote panel, press space on one, check that one out, and then i am redirectred to the local branches panel. Then again, i have to go to the remotes tab, select the remote, check out another branch and repeat.

**Comment by mark2185** [comment]
Try pressing `c` in the branches panel and see if that works for you. I'm suggesting alternatives because it's easier than dealing with automatic entering of a single remote, we'd still need a way to get to the menu of all remotes to add new ones and similar.

**Comment by pinarruiz** [comment]
Didn't know about that one, looks nice hehe, although might be cool to implement some kind of select and checkout, so we don't need to go one by one, what do you think? or maybe there is a way of doing this already -.-

**Comment by mark2185** [comment]
I don't recall the ability to checkout multiple branches at once.

Perhaps it would be better for you to write a script which you would then invoke through a [Custom command](https://github.com/jesseduffield/lazygit/wiki/Custom-Commands-Compendium) than hold your breath waiting for this feature :)

**Comment by pinarruiz** [comment]
I will look into that, so far i just made a quick git alias, thanks for the quick answers :smile:
