### ISSUE TITLE
Installing Lazygit with Go, dependency download failed

### ISSUE THREAD

**Issue by menkan** [jesseduffield/lazygit#3500]
**Describe the bug**
```shell
go: downloading github.com/karimkhaleel/jsonschema v0.0.0-20231001195015-d933f0d94ea3
D:\usr\local\go\pkg\mod\github.com\jesseduffield\lazygit@v0.41.0\pkg\config\user_config.go:6:2: github.com/karimkhaleel/jsonschema@v0.0.0-20231001195015-d933f0d94ea3: invalid version: unknown revision d933f0d94ea3
```

**To Reproduce**

1. `go install github.com/jesseduffield/lazygit@latest`

**Expected behavior**
install success. and run build

**Version info:**
git version 2.44.0.windows.1

**Comment by stefanhaller** [comment]
@karimkhaleel It looks like we were referencing the `main` branch of your fork, and you rebased it, is that right? Rebasing it is fine in principle, but you should push a tag pointing to the previous head of main that we referenced, just to retain it (the name of the tag doesn't matter).

Do you still have the commit d933f0d94ea3 in your local repo and could push a tag pointing to it? That should solve it (I hope).

**Comment by menkan** [comment]
The manual installation was successful.
[href](https://github.com/jesseduffield/lazygit/#manual)

I changed the dependency version number in the go.mod file.

`github. com/karimkhalel/jsonschema v0.0.0-20231105093532-44bdb914ed9c`

`go install ` successful

I hope this issue can be fixed. Thank you very much

**Comment by karimkhaleel** [comment]
My bad! Force of habit. I found `d933f0d94ea3` on my other computer. Pushed a new [branch](https://github.com/karimkhaleel/jsonschema/tree/main-lazygit) and a [tag](https://github.com/karimkhaleel/jsonschema/releases/tag/lazygit). 

I was able to run `go install` without issue even before I pushed the branch and tag. I am not familiar with dependency management in go. I removed the directory of the package: `~/go/pkg/mod/github.com/karimkhaleel` as well, and it was still working fine. Was go finding the commit in my local repo somehow?

**Comment by menkan** [comment]
Verified, can be installed through 'go install github.com/jesseduffield/lazygit@latest'
