### ISSUE TITLE
lazygit is not starting

### ISSUE THREAD

**Issue by bhushan** [jesseduffield/lazygit#3506]
<img width="1676" alt="Screenshot 2024-04-20 at 12 55 26 PM" src="https://github.com/jesseduffield/lazygit/assets/43483545/3ae6bb0d-8555-4878-ad3e-27f1f7fb641d">

lazygit is not loading at all

**Comment by stefanhaller** [comment]
Which lazygit version is this? I have this suspicion that this is fixed in the latest version, but it's hard to tell without more information.

**Comment by bhushan** [comment]
I updated version, now looks like its fixed.
