### ISSUE TITLE
externalDiffCommand doesn't work when diffing between 2 refs

### ISSUE THREAD

**Issue by vohoanglong0107** [jesseduffield/lazygit#3518]
**Is your feature request related to a problem? Please describe.**
`externalDiffCommand` currently works wonder when viewing the diff of each commits, but it doesn't work when we're diffing between 2 refs (with `W` key binding). Instead Lazygit used the default diff view

**Describe the solution you'd like**
`externalDiffCommand` should also applies to diff view between to refs.

**Describe alternatives you've considered**
The default diff view is good enough, but I prefer to use difftastic to view the diff.

**Additional context**

Normal diff:
<img width="1897" alt="image" src="https://github.com/jesseduffield/lazygit/assets/78085736/110826d9-d985-49f0-b036-5cdade2ccb2a">

Diff between branches:
<img width="1888" alt="image" src="https://github.com/jesseduffield/lazygit/assets/78085736/81c9041c-1d37-4fe1-9d4c-c268d2dd65ba">

I could help with implementing this, but I don't know where to start. Any help would be appreciated.

**Comment by stefanhaller** [comment]
Should be fixed by #3519, could you test this?

**Comment by vohoanglong0107** [comment]
@stefanhaller Thanks for the swift response. Can confirm it working as expected now
