### ISSUE TITLE
lazygit dislocation on the top

### ISSUE THREAD

**Issue by SukkaW** [jesseduffield/lazygit#352]
**Describe the bug**

![image](https://user-images.githubusercontent.com/40715044/50149248-a4677f00-02f5-11e9-8bac-526c667681cf.png)

**To Reproduce**

Nothing related to resizing or any actions. Just when I enter the `lazygit`

**Desktop (please complete the following information):**
 - OS: Windows Subsystem Linux(Ubuntu 18.04.1)
 - Lazygit Version: 

```bash
$ lg -v
commit=822dc5d, build date=2018-12-10, build source=debian, version=, os=linux, arch=amd64
```

**Additional context**

I run `lazygit` inside VSCode integrated terminal.

**Comment by jesseduffield** [comment]
That is a very strange looking bug. It appears that some characters are being skipped in the rendering of those two lines where the text is shifted. There should be a 0 and then a space following the down arrow at the top left, and there should be a space following the right arrow before the r in refactor/module. I wonder if perhaps the issue is related to the font you are using.

Could you try switching to a different font and seeing if the issue persists?

**Comment by SukkaW** [comment]
@jesseduffield 
I'm using fonts `Consolas`.

And when I switch to `monospace` it became:

![image](https://user-images.githubusercontent.com/40715044/50150374-b5fe5600-02f8-11e9-9b73-2669707e8e48.png)

It still happened.

I'm running lazygit inside VSCode integrated terminal, using mode `integrated`

**Comment by SukkaW** [comment]
There is also something stranged.

![image](https://user-images.githubusercontent.com/40715044/50150537-3755e880-02f9-11e9-8a04-042cf394c13e.png)

Default I was focused on stage panel. And I switched to top panel:

![image](https://user-images.githubusercontent.com/40715044/50150566-52c0f380-02f9-11e9-9bbb-c3cd5726413d.png)

The space came back, but the issue still unsoleved.

**Comment by jesseduffield** [comment]
Hmm, given that we don't render anything differently when you've focused that top panel, I'd say this looks like a bug in the gocui library, or perhaps in termbox. I'm not sure how to proceed in debugging this. Any takers?

**Comment by SukkaW** [comment]
@jesseduffield Do you have VSCode installed? You can test `lazygit` in VSCode terminal and then may be you can reproduce the issue as well. And I will try `lazygit` in other terminal with same font see if the issue still there.

**Comment by SukkaW** [comment]
![image](https://user-images.githubusercontent.com/40715044/51439499-174d8680-1cf6-11e9-96e8-9174e5afb372.png)

Currently I have reproduced the issue in [Hyper Terminal](https://hyper.is).
Strangely, after I adjust the difference window size, the dislocation disappear.

**Comment by SukkaW** [comment]
Hyper Terminal & VSCode Integrated Terminal are both based on electron, rendered using HTML & CSS. While a terminal based on mintty will not caused the issue.

**Comment by SukkaW** [comment]
I don't know what has happened but this problem seems disappeared since I have update to the latest lazygit. So I am closing the issue now.

**Comment by jesseduffield** [comment]
good to hear!
