### ISSUE TITLE
Tell Lazygit not to set the terminal title

### ISSUE THREAD

**Issue by JackoCoolio** [jesseduffield/lazygit#3526]
I use a shell function to set the title of my current terminal tab so I can identify them easily, but whenever I launch lazygit, it gets overwritten with `<dir> - Lazygit`. It'd be awesome if there were a config item or a CLI argument to disable that.

**Comment by belyakov-am** [comment]
I completely agree with this suggestion! If the maintainers are open to it, I'd be happy to investigate and contribute to the implementation of this feature.

**Comment by JackoCoolio** [comment]
Actually, it looks like this isn't something Lazygit is doing... This happens in Git Bash, but I can't reproduce it in WSL.

I'm guessing it's something MinGW is doing, but I can't find anything about it online. 🤷

**Comment by GTonehour** [comment]
Lazygit overrides the title on Windows in both Windows Terminal and Alacritty.
I don't have this problem with the other TUIs I use: Helix, WSL, yazi...

Lazygit ends up named "project - app" while all other apps lauched with https://github.com/GTonehour/wProjectDesktop are named "app - project".
