### ISSUE TITLE
Recent Repos panel is way too tall

### ISSUE THREAD

**Issue by jesseduffield** [jesseduffield/lazygit#354]
**Describe the bug**
When the terminal window is sufficiently small, opening a menu to see recently opened repos, the menu's height is too big.

**To Reproduce**
hit 's' when the status panel has been focused

**Expected behavior**
menu should open in the centre of the screen with just enough height to house each of the items inside it

**Screenshots**
![image](https://user-images.githubusercontent.com/8456633/50257434-5e263300-044f-11e9-8575-fd4822c8c85e.png)

**Desktop (please complete the following information):**
 - OS: OSX
 - Lazygit Version master 2738879a5eb0667195e92398f12904928d35e897

**Additional context**
I think this is a quick fix but don't have time to look into it now :)

**Comment by KOREAN139** [comment]
[this part](https://github.com/jesseduffield/lazygit/blob/0afffd03cab29d133ab1458964732e29a66ae757/pkg/gui/confirmation_panel.go#L44) seems like main cause for this.
since lazygit does not render lines longer than its panel, `lineCount += len(line)/width + 1` should be `lineCount += len(line)`, for just `return len(lines)`
i'll make PR after my work, if this guess is right :)

**Comment by jesseduffield** [comment]
ah so it looks like maybe we need to pass in the view to that method so that the method can check whether we need to worry about word wrap? Cos if view.Wrap == false, we only need to count the number of newlines in the message

**Comment by KOREAN139** [comment]
@jesseduffield Yep that sounds reasonable. [createMenu](https://github.com/jesseduffield/lazygit/blob/ff856b763033a241370bfde98d7386b43b7d0893/pkg/gui/menu_panel.go#L53) does not set `view.Wrap` as `true`, and [getMessageHeight](https://github.com/jesseduffield/lazygit/blob/0afffd03cab29d133ab1458964732e29a66ae757/pkg/gui/confirmation_panel.go#L40) counts height under assumption that `view.Wrap == true`. this is the cause of this bug, as we can see!

then PR should fix `getMessageHeight` to count lines, depending on `view.Wrap`. 👍

**Comment by KOREAN139** [comment]
@jesseduffield commit 69c538b and 02aeaaa only differs with if clause
```go
if v.View == true { // 69c538b
if v.View { // 02aeaaa
```
as @GolangCI says `should omit comparison to bool constant` in #357, fixed in that way.
review #358 will be enough for this issue

**Comment by KOREAN139** [comment]
resolved with PR #358 & commit 695b092c4120d41c15ad969a6ea472e38379ebbd

this issue can be closed i think @jesseduffield

**Comment by jesseduffield** [comment]
indeed it can. Thanks again for making the PR :)
