### ISSUE TITLE
FR: Shrink Branches & Files panel if they contain empty lines

### ISSUE THREAD

**Issue by kiryph** [jesseduffield/lazygit#355]
Screen space is usually precious, in particular, vertical space when using wide screen displays.

I often interact with repositories which use a lightweight branch model. Only one long-living branch master and feature branches are deleted after merges.

Also if I have not yet modifed anything or only a single file, the Files panel is empty or contains only a single line.

I'd prefer when the panels could be reduced below their default height to remove the empty lines (maybe except one) to give the Commit panel more space.

Does this sound reasonable?

**Comment by glvr182** [comment]
I think this is more or less a personal preference. Personally I would not like it, but I can see why others might like it. If others are backing this request aswell, we could make it configurable to make both sides happy.

**Comment by jesseduffield** [comment]
I've been thinking about this as well. It will certainly be a matter of personal preference, meaning we'll need to make it configurable.

My question would be: what is the best distribution of space? If we have some free space because there are no files that have changed, do we equally distribute the space around the remaining three panels? Or do we want to e.g. give the commits panel preference?

I've also considered having an accordion approach where the panel you've selected gets enlargened and everything else shrinks a fair bit, so that you can see whatever you need to in that panel if you focus on it.

What are our thoughts? How should we distribute space in the first option, and would there be a demand for both of the options?

**Comment by glvr182** [comment]
Personally I wouldn't like having movement (the accordion) in my terminal. It would get a little confusing at times.

**Comment by jesseduffield** [comment]
I agree. If we were to do some content-based resizing like shrinking the files view when there are no files, do you think distributing the space evenly among the remaining panels makes sense, as opposed to e.g. giving all the remaining space to the commits panel?

**Comment by glvr182** [comment]
@jesseduffield IMO it would make sense, but it wouldn't look nice. I think a static view is the best for a terminal. Let the dynamic and changing views be for websites and or applications.

**Comment by kiryph** [comment]
Is this feature request off the table or would you add a customization possibility?

- dynamic_resize=true/false
- fixed_ratio=1:1:1/2:1:3/...
- fixed_heights=10lines, 4lines, remaining lines

**Comment by glvr182** [comment]
We could in the future go for a dynamic resizing option (defaults to off). Although I'm not sure how much work it would be to implement it.

**Comment by jesseduffield** [comment]
On the master branch of lazygit this new config is supported:

```
  gui:
    expandFocusedSidePanel: true
```

Which allows for expanding the currently focused panel. The focused panel will be given a weight of 2 with all other side panels (except status and stash) taking up a weight of 1, giving an accordian effect. I know this isn't quite what you wanted @kiryph, but if you check out `pkg/gui/arrangement.go` and `pkg/gui/boxlayout/boxlayout.go` you'll see the code for handling the view arrangement, and if you (or anybody else) would like to raise a PR to support dynamically sizing boxes based on contents, I'll be happy to review :)

![2020-08-16 18 42 36](https://user-images.githubusercontent.com/8456633/90330490-5a65fd80-dff0-11ea-934f-976bd91396b9.gif)

**Comment by kiryph** [comment]
@jesseduffield Thank you for your work on this. I think it is a good feature. I could imagine to skip the expansion if a panel is sufficiently large.

Others have raised the concern that they do not like movement/accordion effect/non-predictable placement of the panels in their terminal which I understand. A static behaviour feels indeed more natural for a terminal on a second thought.

I would propose to add a keyboard shortcut to toggle the accordion effect on demand.

Another idea is to maximise the current side panel by a keyboard shortcut. A symbol could indicate the state of the panel.

**Comment by jesseduffield** [comment]
@kiryph good points, it just so happens that you can fully expand a panel by pressing '+' (the more you press it the larger it becomes, and pressing '-' goes in the reverse direction). What are your thoughts?

**Comment by kiryph** [comment]
@jesseduffield `+` and `_` are great and help here.

**Comment by jesseduffield** [comment]
I think this one is resolved. Closing :)
