### ISSUE TITLE
Unsupported git service

### ISSUE THREAD

**Issue by raphi-0901** [jesseduffield/lazygit#3551]
I try to configure my git services for pull requests as stated here:
https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md#custom-pull-request-urls

So this is my current `config.yml`:
```
services:
  'github.com': 'github:github.com'
```

But when I try to run the command, I just get this error message:
![image](https://github.com/jesseduffield/lazygit/assets/81636028/a574d684-cf6d-4e0d-b3a7-eae852cca02b)

My current version is:
```
commit=5e388e21c8ca6aa883dbcbe45c47f6fdd5116815, build date=2023-08-07T14:05:48Z, build source=binaryRelease, version=0.40.2, os=linux, arch=amd64, git version=2.34.1
```

Am I missing something or is this a bug?

**Comment by mark2185** [comment]
What does your remote's URL look like?

**Comment by raphi-0901** [comment]
It is exactly like in my original post.

**Comment by mark2185** [comment]
I meant the `git` remote URL, the one you get by running `git remote -v`:
```shell
$> git remote -v
origin	git@github.com:jesseduffield/lazygit (fetch)
origin	git@github.com:jesseduffield/lazygit (push)
```

The reason I'm asking is because `github` is supported by default, no configuration needed.

**Comment by raphi-0901** [comment]
Thank you! It works now.

**Comment by Nias26** [comment]
> Thank you! It works now.

@raphi-0901 How did you manage to solve the error?

**Comment by Georacer** [comment]
I have the same issue. Github used to work for me out of the box in 0.40.
After going to 0.44 I get the "unsupported" error.

**Comment by nasxisbest** [comment]
+1

**Comment by Georacer** [comment]
I think it's repo dependent. I haven't seen that issue recently. Perhaps it has something to do with private repos.

**Comment by tomashomey** [comment]
I have exactly same question as @minami22x3  .

**Comment by minami22x3** [comment]
> I have exactly same question as @minami22x3  .
> 
> 
> **Update**
> 
> this totally works https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md#custom-pull-request-urls 
> 
> <img width="1062" alt="Image" src="https://github.com/user-attachments/assets/18b077e5-d887-43c1-ba3f-ed63cf1a852d" />

Can you show me an example with my configuration above @tomashomey ? Thanks.
