### ISSUE TITLE
An option to hide merge diagrams

### ISSUE THREAD

**Issue by unlessgames** [jesseduffield/lazygit#3560]
While the merge diagram looks very pretty and nice, it might be useful to be able to hide it for projects that have a lot of merges to be able to see the commits better.

![lazygit_merge](https://github.com/jesseduffield/lazygit/assets/38718816/947ebafa-d8d4-4086-adbd-e1882ccc2711)

**Comment by stk-ableton** [comment]
Type ctrl-l to open the "Commit Log Options" window, choose "Show git graph...", and set it to either "never" or "when maximised".

It is currently not possible to show this for some repos but hide it for others, since the setting is stored in the global application state.

**Comment by unlessgames** [comment]
Nice, thank you!
