### ISSUE TITLE
Prepare for v0.42

### ISSUE THREAD

**Issue by jesseduffield** [jesseduffield/lazygit#3562]
Ah yes, once again we're late on releasing a new version. My bad! I am regrettably the co-founder of a startup now and am yet to strike a better balance of work/life/open-source.

Which issues/PRs do people think should go in this release?

Keep in mind that despite my abysmal failure at achieving monthly releases since the last one, we actually do want to be having smaller and more frequent releases so if there's nothing super important that we want to get into this release we can just release what's currently in master plus a couple PRs that are still open.

Tagging @stefanhaller @jwhitley @mark2185 @afhoffman @AzraelSec @karimkhaleel

**Comment by AzraelSec** [comment]
I've been inactive for a while, but from now on, I'll have time to spend on lazygit again. I have a couple of issues to work on; one of them is small enough to be fixed during the week: https://github.com/jesseduffield/lazygit/issues/3200. I'll try to open a PR tomorrow, but ignore me if I don't make it - we can include it as part of the next release.

**Comment by noahfraiture** [comment]
I'm working on https://github.com/jesseduffield/lazygit/pull/3566 why I want to finish this week with an interactive window to choose to make commit message or no. This is my first PR here and I don't know the workflow yet but if the PR is merged quickly it could be part of the release I guess

**Comment by mark2185** [comment]
I have just a draft (#3532 ) but I'm going to be unavailable for the next 4 weeks so I'll finish it up for the next release.

As for which other things should be in the release - no idea, I don't have any painpoints with the current `master`.

**Comment by stefanhaller** [comment]
I'll add #3569 because it's an important fix, and it's close to done.

**Comment by jesseduffield** [comment]
I'm gonna get https://github.com/jesseduffield/lazygit/pull/3508 in because it's a nice QoL change for neovim users

**Comment by jesseduffield** [comment]
@noahfraiture let's leave your PR to the next release, it seems like there's still some work to do there.

@stefanhaller If we can get https://github.com/jesseduffield/lazygit/pull/3534 and https://github.com/jesseduffield/lazygit/pull/3528 merged (I've approved both but left a documentation comment on one) then I'm happy to cut a release

**Comment by stefanhaller** [comment]
Looks like we're ready to go

**Comment by jesseduffield** [comment]
Release notes are up: https://github.com/jesseduffield/lazygit/releases/tag/v0.42.0

And deployment is currently underway: https://github.com/jesseduffield/lazygit/actions/runs/9146886198
