### ISSUE TITLE
Error when stashing all (more than 1) your "staged" files

### ISSUE THREAD

**Issue by dsolerh** [jesseduffield/lazygit#3563]
**Describe the bug**

**To Reproduce**

1. Create changes on multiple files
2. Press 'a' to stage them all
3. Press 'S' to open the stash options menu
4. Manually go to the option "Stash staged changes" and press Enter
5. Leave the name for the stash blank just press enter

**Expected behavior**
I expect not to be an error shown

**Screenshots**
Steps 1 and 2
<img width="1054" alt="image" src="https://github.com/jesseduffield/lazygit/assets/55502191/8138c1c6-581b-4f8e-897a-b3a5df62c008">
Step 3 and 4
<img width="1054" alt="image" src="https://github.com/jesseduffield/lazygit/assets/55502191/79ba38f5-17e1-4b84-b31f-4efd93bc0013">
Step 5
<img width="1059" alt="image" src="https://github.com/jesseduffield/lazygit/assets/55502191/15c663f4-c227-4bef-be14-a4eea98f766b">
Result
<img width="1057" alt="image" src="https://github.com/jesseduffield/lazygit/assets/55502191/a22f3d42-74a8-4d9f-9dc4-9048347d3cfd">

**Version info:**
commit=, build date=, build source=homebrew, version=0.41.0, os=darwin, arch=arm64, git version=2.44.0

**Additional context**

**Note:** please try updating to the latest version or [manually building](https://github.com/jesseduffield/lazygit/#manual) the latest `master` to see if the issue still occurs.

**Comment by dsolerh** [comment]
I also want to try and fix this

**Comment by stefanhaller** [comment]
This one looks easy to fix. It seems that we only need to check if there are any unstaged changes, and if not, fall back to the normal, simple stash.

There's a different, but somewhat related problem that seems harder to fix: #3333. In case you feel like looking into that one, too.

**Comment by dsolerh** [comment]
I added the PR, how can I link it to this issue?

**Comment by stefanhaller** [comment]
Fixed by #3569.
