### ISSUE TITLE
Confirmation Dialogue - How to interact?

### ISSUE THREAD

**Issue by zhdenny** [jesseduffield/lazygit#3583]
I occasionally receive Yes/No confirmation dialogue messages in the Command Log.....How do I interact with these messages!?
When I see the message, I press "y" or "n" but that doesn't work.
Screenshot below is just one example....it isn't the only confirmation message I see.

According to the Keybindings Chart:
"y" is to "Copy to Clipboard"
"n" doesn't do anything.

I tried to mouse click over the "Command Log" window. That doesn't do anything. I'm not really sure what to do here.

![image](https://github.com/jesseduffield/lazygit/assets/26662131/b3e678ff-5a94-41ff-a622-f77ed7bd0641)

**Comment by stefanhaller** [comment]
There's no way to interact with these, I'm afraid. Where do they come from?

Lazygit only has support for certain kinds of prompts that occur during certain operations, e.g. when you push and ssh asks you for a passphrase. The one in the screenshot doesn't look like a standard prompt (never seen it myself).

**Comment by zhdenny** [comment]
I cd into a git repo in my terminal, type "lazygit", lazygit opens and I see this message immediately almost all the time.

![image](https://github.com/jesseduffield/lazygit/assets/26662131/93f07e82-7231-44dd-824e-f03c70629a33)

**Comment by zhdenny** [comment]
Maybe this has to do with using ssh to authenticate into github....and "StrictHostKeyChecking ask" setting in ssh_config file. I'll experiment with changing that to:
```
Host github.com
     StrictHostKeyChecking no
```
