### ISSUE TITLE
Diff panel jumps to top by itself each 10 sec

### ISSUE THREAD

**Issue by kristijanhusak** [jesseduffield/lazygit#359]
**Describe the bug**
Diff panel refreshes and jumps to top each ~10 sec

**To Reproduce**
1. Have a big diff for a file
2. Select it, scroll down with Ctrl-D
3. Wait few seconds
4. See that it jumped to top of the diff

**Expected behavior**
I would expect diff panel not to jump by itself.

**Additional context**
I'm assuming this has something to do with this line https://github.com/jesseduffield/lazygit/blob/master/pkg/gui/gui.go#L537, but i'm not sure how can i fix it.

**Comment by kristijanhusak** [comment]
I tried this, but it's not working, probably because update is done in goroutine.

```diff
diff --git a/pkg/gui/files_panel.go b/pkg/gui/files_panel.go
index a891381..b9c9b55 100644
--- a/pkg/gui/files_panel.go
+++ b/pkg/gui/files_panel.go
@@ -53,15 +53,17 @@ func (gui *Gui) refreshFiles(g *gocui.Gui) error {
 		return err
 	}
 	gui.refreshStateFiles()
+	mainView, _ := g.View("main")
+	ox, oy := mainView.Origin()
 
 	gui.g.Update(func(g *gocui.Gui) error {
-
 		filesView.Clear()
 		list, err := utils.RenderList(gui.State.Files)
 		if err != nil {
 			return err
 		}
 		fmt.Fprint(filesView, list)
+		mainView.SetOrigin(ox, oy)
 
 		if filesView == g.CurrentView() {
 			return gui.handleFileSelect(g, filesView)
```

**Comment by jesseduffield** [comment]
This has been bugging me too. I've just gotten back from my holiday so I'll look into this ticket first thing

**Comment by jesseduffield** [comment]
I've got a PR up @kristijanhusak but It's a little verbose. Would you be able to take a look at it and give me your thoughts?

**Comment by kristijanhusak** [comment]
I'll check it out tomorrow, thanks.
