### ISSUE TITLE
docs: `fixup` description seems to be described incorrectly

### ISSUE THREAD

**Issue by xl4624** [jesseduffield/lazygit#3600]
The tooltip for `fixup` currently states:

> Meld the selected commit into the commit below it. Similar to fixup, but the selected commit's message will be discarded.

I believe it's supposed to say "Similar to squash" instead, since `squash` combines commit changes and appends messages while `fixup` discards them (unless I'm misunderstanding the tooltip).

**Comment by stefanhaller** [comment]
Yes, you're right, thanks for reporting.

There's another problem with the tooltip: on my screen, the word "discarded" at the end was cut off.

I made a PR that fixes both problems: #3601.
