### ISSUE TITLE
unstaged panel can be maximized, but staged panel cannot.

### ISSUE THREAD

**Issue by konosubakonoakua** [jesseduffield/lazygit#3629]
**Describe the bug**
unstaged panel can be maximized, but staged panel cannot.

**To Reproduce**

1. Go to any git repo
2. make multiple line changes
3. open lazygit, stage any of the changes
4. focus on staged, press + to test, then focus on unstaged, press + to test
5. staged panel cannot be maximized, instead, the panel keeps shrinking when hitting '+'

**Expected behavior**
staged panel should change screenmode like unstaged panel

**Screenshots**

![staged panel cannot be maximized](https://github.com/jesseduffield/lazygit/assets/42881610/3d218dd8-d8b3-4b47-a398-d90a59bdcee9)

**Version info:**
```
commit=6fcb7eb8bb616c170506312870b3bf15f3dbe37c, build date=2024-05-19T10:15:28Z, build source=binaryRelease, version=0.42.0, os=linux, ar
ch=amd64, git version=2.45.1
```

**Comment by JordanllHarper** [comment]
Reproduced this. Initial findings seem to be when focused the staged changes pane, the '+' behaviour has the same effect as on the 'files' pane.

**Comment by AzraelSec** [comment]
I opened a [PR](https://github.com/jesseduffield/lazygit/pull/3637) to fix this issue. In the meantime, feel free to test that branch.
