### ISSUE TITLE
Ability to see # of line changes in the diff window

### ISSUE THREAD

**Issue by lespea** [jesseduffield/lazygit#3643]
**Is your feature request related to a problem? Please describe.**
Maybe there's already a way to do this and I just don't know how, but it would be very useful to me if the "unstaged changes" window showed the # of lines add/removed/changed (or whatever variant works) either at the top of that window or maybe even inline with the file lists (like having the +/- numbers shown to the right of the filenames?).

**Describe alternatives you've considered**
I don't *need* that info and continue using the tool without it.

**Comment by stefanhaller** [comment]
Implemented in #4015.
