### ISSUE TITLE
The branch name is garbled

### ISSUE THREAD

**Issue by Timebevin** [jesseduffield/lazygit#3690]
<img width="137" alt="image" src="https://github.com/jesseduffield/lazygit/assets/56360119/c0436778-2f86-40ce-ad7e-290279b51d1a">
The branch name is garbled

**Comment by mark2185** [comment]
Please fillout the entire bug report template. 

And what does `bit branch` say the name should be?

**Comment by Timebevin** [comment]
<img width="273" alt="image" src="https://github.com/jesseduffield/lazygit/assets/56360119/ea9b8c56-aad0-488e-9fb5-765eccda14db">
<img width="308" alt="image" src="https://github.com/jesseduffield/lazygit/assets/56360119/1707e6cd-fc88-43ea-802d-7d0a4caa4ba1">
This name was supposed to be displayed, but it was displayed incorrectly
I don't know what the cause is, but this branch is a branch created by someone else with the windows system, and I am a mac system (this is the scene where the bug is generated)
And you can't do any other git operations

**Comment by Timebevin** [comment]
Resolved
