### ISSUE TITLE
Auto-generated keybinding cheatsheets in CI

### ISSUE THREAD

**Issue by jesseduffield** [jesseduffield/lazygit#370]
**Is your feature request related to a problem? Please describe.**
When CI is doing a release, it should check to see if the keybindings have changed since last time, and if so, should push new generated cheatsheets to our docs (one for each language).

**Describe the solution you'd like**
As above

**Describe alternatives you've considered**
Manually updating the cheatsheet as part of the process, or having CI tell you to auto-generate it when pushing to any branch where the keybindings have changed.

**Additional context**
none

**Comment by dawidd6** [comment]
Okay, so I think that it can be done in the following way:
1. Generate ssh key pair.
2. Add ssh public key to this repository in settings > deploy keys.
3. Add ssh private key to CircleCI (as secret variable?).
4. On CircleCI check if commit is a tag. If so, then proceed.
5. On CircleCI check `git diff $previous_tag $current_tag docs/Keybindings*`. If true or output is non-empty, then proceed.
6. Run generator script for every language.
7. Add files, commit and push.

Disclaimer: I don't really know CircleCI, but I guess it's not so different in comparision to other CIs.

**Comment by jesseduffield** [comment]
closing because I believe we did implement this
