### ISSUE TITLE
How can i change the date of the commit using lazygit

### ISSUE THREAD

**Issue by hsayed21** [jesseduffield/lazygit#3715]
**Topic**
How can I change the date of the commit using lazygit?

**Your thoughts**
I want to change the date of the commit with the current date or a specific date, Can we do that?

thanks

**Comment by stefanhaller** [comment]
Only to the current date, not to a specific date; and only by also changing the author to yourself at the same time. To do that, hit `a` on the commit and pick "Reset author".

(If you don't want to change the author to yourself, just set it back to what it was by hitting `a` again and picking "Set author", choosing the author that it had before.)
