### ISSUE TITLE
"Increase the size of the context" '}' not working via shortcut

### ISSUE THREAD

**Issue by lobneroO** [jesseduffield/lazygit#3741]
**Describe the bug**
When viewing unstaged changed and hovering a line in there, the help menu shows
 > } Increase the size of the context shown around changes in the diff view

When pressing the } key (on a German keyboard, so 'Alt Gr' + 0) nothing happens.
When selecting the entry in the help menu and pressing enter to apply it, it works.

**To Reproduce**
1. Go to the unstaged changes, press '}' (German keyboard, so 'Alt Gr' + 0)
 --> nothing happens
2. Open the Help menu by pressing '?'
3. Navigate to the appropriate line
4. Press enter 
 --> the context increases

**Expected behavior**
Upon pressing the shortcut, the context increases

**Version info:**
_Run `lazygit --version` and paste the result here_
commit=5e388e21c8ca6aa883dbcbe45c47f6fdd5116815, build date=2023-08-07T14:05:48Z, build source=binaryRelease, version=0.40.2, os=windows, arch=amd64, git version=2.41.0.windows.1
_Run `git --version` and paste the result here_
git version 2.41.0.windows.1

**Additional context**
Using a standard German keyboard Layout (specifically old 'blue' Logitech G15 in my case)
Windows 11 (22H2)
Windows Terminal 1.20.11781.0

**Comment by lobneroO** [comment]
Same problem with decreasing the context and (German keyboard) 'Alt Gr' + 7. Works with the help menu selection only.

**Comment by stefanhaller** [comment]
This sounds very much like the problem that we fixed in #3194. This shipped with v0.41, but you are using v40.2. Please update and report if the problem still exists.

**Comment by lobneroO** [comment]
Sorry, I thought I had upgraded (since I mainly use choco... but for some reason, I had this installed via winget).
You are correct, with this version it works.
