### ISSUE TITLE
Incorrect parsing of unicode escape codes

### ISSUE THREAD

**Issue by GR3YH4TT3R93** [jesseduffield/lazygit#3747]
**Describe the bug**
In the latest release (v0.43.1), some icons (e.g. nuxt.config.ts which uses the escape sequence `\uf1106`, and tailwind.config.ts which uses the escape sequence `\uf13ff`) are showing the incorrect icons (e.g. for nuxt.config.ts `\uf110`+6 shown as `icon`6 instead of \f1106 and for tailwind.config.ts `\uf13f`+f shown as `icon`f instead of `\uf13ff`).

**To Reproduce**

1. `git init`
2. `touch nuxt.config.ts tailwind.config.ts`
3. `lazygit`

**Expected behavior**
Expected to see the proper icons

**Version info:**
commit=v0.43.1, build date=2024-07-13T12:12:22Z, build source=termux, version=0.43.1, os=android, arch=arm64, git version=2.45.2
git version 2.45.2

**Comment by GR3YH4TT3R93** [comment]
Sorry, you'll also need to ensure to set `nerdFontsVersion: "3"` in your `~/.config/lazygit/config.yml` for the repro

**Comment by bmichotte** [comment]
I have the same issue

![CleanShot 2024-08-23 at 13 03 21@2x](https://github.com/user-attachments/assets/ca481009-9aec-415d-bae0-236775dd1cb8)

And I also can config that it's not an issue from my font, here's the screenshot from `pkg/gui/presentation/icons/file_icons.go`

![CleanShot 2024-08-23 at 13 03 59@2x](https://github.com/user-attachments/assets/96988549-9287-4fdf-9896-3e427c14b4ef)

as well as in neo-tree
![CleanShot 2024-08-23 at 13 05 26@2x](https://github.com/user-attachments/assets/96d2f426-6f34-49dd-aa43-3aa8d6948a44)

**Comment by xzhang8102** [comment]
I encountered a similar problem.
https://github.com/LazyVim/LazyVim/discussions/4559#discussion-7293831

**Comment by stefanhaller** [comment]
Here's a fix: #3975

**Comment by GR3YH4TT3R93** [comment]
It works! Thank You!
![Screenshot_2024-10-09-20-04-46-49_84d3000e3f4017145260f7618db1d683](https://github.com/user-attachments/assets/0b2d7cfd-0c27-47c1-a4c2-96438e87ebae)

**Comment by bmichotte** [comment]
Can confirm it's working for me as well. Thanks @stefanhaller 

![CleanShot 2024-10-10 at 08 33 44@2x](https://github.com/user-attachments/assets/de5d59c5-ae28-4d92-af6c-52f0035787fd)
