### ISSUE TITLE
Manual and/or Go install commands for lazygit

### ISSUE THREAD

**Issue by nullromo** [jesseduffield/lazygit#3753]
## Problem

I have an old version of lazygit installed (v0.42.0) and I want to update (to v0.43.1).

## What I Tried

The current install instructions say

#### Go

```
go install github.com/jesseduffield/lazygit@latest
```

#### Manual

```
git clone https://github.com/jesseduffield/lazygit.git
cd lazygit
go install
```

However, after trying these, I still have version 0.42.0.

```
$ which -a lazygit
/usr/local/bin/lazygit
$ lazygit --version
commit=6fcb7eb8bb616c170506312870b3bf15f3dbe37c, build date=2024-05-19T10:15:28Z, build source=binaryRelease, version=0.42.0, os=linux, arch=amd64, git version=2.39.2
$ ls -al /usr/local/bin/lazygit
-rwxr-xr-x 1 root root 17633432 Jun  3 09:27 /usr/local/bin/lazygit
$ go version
go version go1.22.4 linux/amd64
```

## Question

What did I miss? `go install` should build and install the package, right?

**Comment by mark2185** [comment]
Have you installed `lazygit` via your package manager as well maybe? 

`go install` install probably installed it into `~/go/bin/`, the `/usr/local/bin/lazygit` is most likely from the package manager.

**Comment by nullromo** [comment]
Aha, yes it is in `~/go/bin/`. I don't think I used the package manager before, since `apt list --installed | grep lazy` shows nothing. Maybe I installed it from source. Anyway, maybe the Go install instructions need to mention the location needs to be added to the path. Or is there's a way to get it to install in a regular location like `/usr/local/bin`?

**Comment by mark2185** [comment]
> Anyway, maybe the Go install instructions need to mention that the location needs to be added to the path.

You mean something more than [the current note](https://github.com/jesseduffield/lazygit?tab=readme-ov-file#go)?

> Please note: If you get an error claiming that lazygit cannot be found or is not defined, you may need to add ~/go/bin to your $PATH (MacOS/Linux), or %HOME%\go\bin (Windows). Not to be mistaken for C:\Go\bin (which is for Go's own binaries, not apps like lazygit).

> Or is there a way to get it to install in a regular location like /usr/local/bin

I guess you could set the `GOPATH` environment variable and then use `sudo` for `go install` but is it really worth it?

**Comment by nullromo** [comment]
Thanks, I didn't see that since I looked under the "Manual" section.
