### ISSUE TITLE
Make the active panel look more prominent

### ISSUE THREAD

**Issue by davxiao** [jesseduffield/lazygit#376]
A couple times I got confused on which panel is active. I suppose the highlight white lines surrounding the active panel are just not bright enough to my eyes. 

I wish there is configuration that allow user to make some adjustments, perhaps make the highlight lines twice as thick or a different color?

**Comment by mjarkk** [comment]
Good news there is a config file where you can do that :),  
On linux the config file is located under: `~/.config/jesseduffield/lazygit`  
I'm not sure where it's located on mac and windows.

**Comment by jesseduffield** [comment]
you can open the config file by selecting the top panel on the left (the status panel) and then pressing 'o' :)

I personally use green to highlight the current panel:

![image](https://user-images.githubusercontent.com/8456633/52920996-a043f600-3366-11e9-8a13-ca85ae3c3e3a.png)

**Comment by jesseduffield** [comment]
closing :) Let me know if you have any issues
