### ISSUE TITLE
Panel Selection Inversion

### ISSUE THREAD

**Issue by geomorillo** [jesseduffield/lazygit#3760]
**Describe the bug**
When using LazyGit, there appears to be an issue with the panel selection indicators in panels 1 and 2. When pressing the key '1', it should select panel 1, and pressing '2' should select panel 2. However, the selection is inverted: pressing '1' selects panel 2, and pressing '2' selects panel 1.

**To Reproduce**

1. Open LazyGit.
2. Attempt to select panel 1 by pressing the '1' key.
3. Observe that panel 2 is selected instead.
4. Attempt to select panel 2 by pressing the '2' key.
5. Observe that panel 1 is selected instead.

**Expected behavior**

- Pressing '1' should select panel 1.
- Pressing '2' should select panel 2.

**Screenshots**
![number](https://github.com/user-attachments/assets/f4884189-a5bf-4347-9b34-99b741edc3f6)

**Version info:**
commit=71ad3fac63a3ef3326021837b49e9497d332818b, build date=2024-07-13T10:24:19Z, build source=binaryRelease, version=0.43.1, os=windows, arch=amd64, git version=2.45.2.windows.1

git version 2.45.2.windows.1

**Additional context**
This issue affects usability as it leads to confusion when navigating between panels. It would be helpful to have this corrected to ensure intuitive panel selection.

**Comment by mark2185** [comment]
Have you maybe made any remappings in your `config.yml`?

I tried it on latest `master` (on `linux`, but still), but can't reproduce it.

**Comment by stefanhaller** [comment]
Remappings wouldn't explain it, this would also show the remapped keys in the panel titles. You can try that by using
```yaml
keybinding:
  universal:
    jumpToBlock:
      - "2"
      - "1"
      - "3"
      - "4"
      - "5"
```

@geomorillo I have no idea how this could be explained, sorry. Works correctly for me.

**Comment by geomorillo** [comment]
Thanks for the quick response. There seems to be a misunderstanding.

I initially thought there was an inversion issue with the panel selection indicators, but after playing with it for a bit, I realized the panels are selected correctly. However, the color change when a panel is selected is causing me confusion. The selected panel becomes darker, which gives the impression that it is not the active panel. Maybe changing the color to something like a light green would make it clearer?, so i will close this issue since is not a bug thanks
