### ISSUE TITLE
Configuration option to remove branch name default from commit message

### ISSUE THREAD

**Issue by JonnySB** [jesseduffield/lazygit#3764]
Hi, firstly I LOVE LAZYGIT! Thank you for all that you do - it's awesome! Just a small quality of life suggestion that would suit me. I have searched for this as a configuration option and couldn't find anything but I could well have missed something, and so apologies if this is the case. I use lazygit both directly in the terminal and through the neovim integration, and this is present in both.

**Is your feature request related to a problem? Please describe.**
I find it slightly annoying to have to delete out the branch name every time I want to create a commit. It's obviously not a massive thing but it would be nice to just be able to start typing the commit message immediately, saving those precious seconds.

**Describe the solution you'd like**
Have the default commit message be blank, ready to type your commit message. I.e. not autopopulate with the branch name.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by mark2185** [comment]
Just to confirm the steps:
- you stage come files
- press `c` in the `Files` panel
- get this popup, but it's prefilled with the branch name?

![image](https://github.com/user-attachments/assets/f950cfa9-cce2-466c-8af1-83ce7b6113f9)

**Comment by JonnySB** [comment]
Yes, is this not default behaviour?

**Comment by mark2185** [comment]
Not the default, but you can set it up with [predefined commit message prefixes](https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md#predefined-commit-message-prefix).

Could you please post your `config.yml`? It should be in the directory you get from running `lazygit -cd`.

**Comment by JonnySB** [comment]
Thanks. So I had been down this route and currently have both the pattern and replace options set to empty strings. Am I missing something?

**Comment by JonnySB** [comment]
Ah I'm dumb - just realised I need to state the pattern. All fixed! Thank you for pointing me in the right direction!

**Comment by mark2185** [comment]
You can also just omit it from the config :)

I'm glad it's sorted!
