### ISSUE TITLE
Configurable yellow commit hash

### ISSUE THREAD

**Issue by realhackcraft** [jesseduffield/lazygit#3765]
> A yellow commit signifies that the commit is not present on the `master` branch, or if you're on a feature branch, that the commit is not present on the `develop` branch.

**Describe the solution you'd like**
A config option list that allows the user to change which branches are considers "main". The defaults are "master", "develop" and probably "main". Maybe even an additional option to turn of the yellow commit hash all together, and only keeping the red and green ones. (turn yellow commit hash green, if the user doesn't care about it.)

**Describe alternatives you've considered**
Ignore the yellow commit hash.

**Additional context**
![Screenshot 2024-07-21 at 22 25 33](https://github.com/user-attachments/assets/39465e41-1ab0-425f-9ea6-d706360556d2)

**Comment by stefanhaller** [comment]
This setting exists already, it is called `gui.mainBranches`. It defaults to "master" and "main", so you'll have to add "develop" yourself if you want it; it didn't seem standard enough to add it by default.

I'd be curious why you want to turn off yellow altogether, what's the use case for that?

**Comment by realhackcraft** [comment]
Idk, when I created my dotfiles repo I had a branch for WezTerm and another one for Alacritty, but I have since realized I was using branches the wrong way and switched to a tag for Alacritty.
