### ISSUE TITLE
Possible to Fast Forward / Rebase / Merge to an upstream branch?

### ISSUE THREAD

**Issue by bhaidar** [jesseduffield/lazygit#3768]
Hello,

I am currently a GitKraken user and shifting to LazyGit! The tool is super impressive, thank you for all your efforts!

Given the following:
- I have an repo (not owned by me) that has two branches main and staging
- I fork the repo on my own GitHub account

Here's my workflow:

1. Checkout staging
2. Create a new branch
3. Push the new local branch to origin (my own repo)
4. Open a PR against the upstream repo / staging branch
5. Merge PR on upstream staging branch
6. Fetch the upstream staging branch
7. Checkout local staging branch, Fast-Forward to upstream staging branch (on GitKraken)
8. Push local staging to update the origin/staging branch

I am stuck on Step 7. I did a workaround, but is there an easier way to do the same thing? Maybe define a new custom command?

The way I've worked around Step 7 is, I change upstream on local staging branch to point to upstream/staging branch. Then hit f to fast forward to upstream/staging. Then, change the upstream on local staging to point back to origin/staging branch, then push back to origin/staging.

This works, but it's a long way.

I appreciate your feedback and ideas :-) 

Thank you
Bill

**Comment by mark2185** [comment]
> 6. Fetch the upstream staging branch
> 7. Checkout local staging branch, Fast-Forward to upstream staging branch (on GitKraken)
> 8. Push local staging to update the origin/staging branch

Presuming `staging -> origin/staging` is currently checked out, you could select the `staging -> upstream/staging`, press `f` to fetch (step 6), press `g` to reset to it and then select `hard reset` (step 7) and push as you normally would (step 8)?

**Comment by bhaidar** [comment]
Hey @mark2185 

Thanks for your reply.

So when I press f/g on the upstream staging, this would fetch the upstream staging and make it insync with the remote upstream, correct?

The idea is I want to Fast Forward the local staging to the upstream staging. This step is to update the local staging after merging the PR on the upstream staging.

**Comment by mark2185** [comment]
> So when I press f/g on the upstream staging, this would fetch the upstream staging and make it insync with the remote upstream, correct?

Yes, pressing `f` will fetch the currently selected branch.

> The idea is I want to Fast Forward the local staging to the upstream staging. This step is to update the local staging after merging the PR on the upstream staging.

At this point this is the same as `reset --hard`, right? Then you can press `g` and then `h`, or `r` to rebase, both should (?) work.

**Comment by bhaidar** [comment]
Super! Thanks a lot @mark2185 it works :-)


Bill
