### ISSUE TITLE
Error: unrecognized input when picking hunk

### ISSUE THREAD

**Issue by MoerkerkeLander** [jesseduffield/lazygit#377]
**Error (unrecognized input) when selecting a hunk while fixing a merge conflict**
When resolving a merge conflict, I press space in the diff panel to select a hunk the program crashes with this error:

```
2019/02/24 16:31:18 error: unrecognized input

panic: error: unrecognized input

goroutine 1 [running]:
log.Panicln(0xc000507df0, 0x1, 0x1)
    /usr/lib/go/src/log/log.go:340 +0xc2
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).RunWithSubprocesses(0xc0001781c0)
    /tmp/packerbuild-1000/lazygit/lazygit/src/src/github.com/jesseduffield/lazygit/pkg/gui/gui.go:571 +0xc4
main.main()
    /tmp/packerbuild-1000/lazygit/lazygit/src/src/github.com/jesseduffield/lazygit/main.go:53
+0x12c
```

**To Reproduce**
1. Get a merge conflict
2. Press space in the diff panel on a hunk
3. See error

**Expected behavior**
Selecting a hunk.

**Screenshots**
![image](https://user-images.githubusercontent.com/20244592/53301278-10fc7e00-3851-11e9-9e98-36dde1f062f7.png)
I press space:
![image](https://user-images.githubusercontent.com/20244592/53301340-bd3e6480-3851-11e9-8f9f-9c0f6c403863.png)

**Desktop**
 - OS: Linux Arch (kernel: 4.20.11-arch2-1-ARCH)
 - Lazygit Version 0.6.1

**Additional context**
I reproduced the same error while running:

- AUR lazygit (0.6-1)
- AUR lazygit-git (0.6.r4.e09f390-1)
- Go get (cannot get version info)

I also tried on two repositories, without luck.

**Comment by jesseduffield** [comment]
@MoerkerkeLander I'm not sure what would be causing that issue on your end. Are you able to checkout the branch on this PR and see if your issue is resolved on that? https://github.com/jesseduffield/lazygit/pull/375

I've made some code changes to the merge-process as part of that PR

**Comment by MoerkerkeLander** [comment]
@jesseduffield I checked out the branch but I can't figure out how to install it from source. I haven't found a way in the docs. How can I compile and install it?

Thanks!

**Comment by jesseduffield** [comment]
This should do the trick :)
```
go build
./lazygit
```

**Comment by MoerkerkeLander** [comment]
I tried that multiple times, didn't realise the checksums were mismatched    (._. ) 
Got it figured out now but still the same error... :neutral_face:

**Comment by jesseduffield** [comment]
damn :/ I know that we do some file manipulation with merge conflicts, maybe the issue here relates to the differences in line endings between osx (the platform I mainly test on) and arch linux. I'll have another look in a bit

**Comment by MoerkerkeLander** [comment]
Tried it the same situation with v0.5 and I can merge correctly without error. So it works on v0.5 :+1:

**Comment by MoerkerkeLander** [comment]
One thing to note: when in the diff panel the merging experience is different between version v0.5 and v0.6. On v0.5 I can only navigate, selecting by chunk and on v0.6, the navigation is done by line. There is also a colour difference, maybe is that says something?

On v0.5
![image](https://user-images.githubusercontent.com/20244592/53423740-366cc180-39e2-11e9-962f-443095eec875.png)

On v0.6
![image](https://user-images.githubusercontent.com/20244592/53423770-4389b080-39e2-11e9-9c9b-0e82f3cd089e.png)

**Comment by MoerkerkeLander** [comment]
Tried it again with the latest version (0.7.1) and it works
