### ISSUE TITLE
repeated commits shown in the history, not accessible by cursor

### ISSUE THREAD

**Issue by MilanV** [jesseduffield/lazygit#3778]
**Describe the bug**
Tab [4] Commits shows commits duplicated, duplicate lines are not accessible by the cursor.  for example, this happens after the branch switching

Note: it might be not a duplication but just not erased lines in tab [4] after topic branch containing more commits than master.

**To Reproduce**
Setup example repos on local filesystem: aaa and bbb. aaa contains just master branch with two commits, then clone this repo to bbb where you add a topic branch with another commits. topic branch is active when you start lazygit. Then, in lazygit, switch to the master branch in tab [3] and tab [4] shows master commits twice.
If you switch to tab [4], your cursor can move between two upper lines/commits, those duplicates are not accessible by cursor.

exactly, step by step:

$ mkdir -p lazyissue/aaa && cd lazyissue/aaa
$ git init
$ echo "first file" > file_a && git add file_a && git commit -m "master c1"
$ echo "second file" > file_b && git add file_b && git commit -m "master c2"
$ cd ..
$ git clone aaa bbb && cd bbb
$ git checkout -b topic_1
$ echo "topic modification A" >>file_a && git add file_a && git commit -m "topic c1"
$ echo "topic modification B" >>file_b && git add file_b && git commit -m "topic c2" 
$ lazygit     # in lazygit, press "3" to move to the branches tab and switch to master branch, check what appears in tab [4]                                                                                                                                                           

**Expected behavior**
Correct branch history shown in tab [4] after branch is switched.

**Screenshots**
![issue_repeated_commits_in_history](https://github.com/user-attachments/assets/b91bfcf4-cbd0-4b81-9fe7-d59f522dc38d)

**Version info:**
commit=71ad3fac63a3ef3326021837b49e9497d332818b, build date=2024-07-13T10:24:19Z, build source=binaryRelease, version=0.43.1, os=linux, arch=amd64, git version=2.39.2

**Additional context**
running on Debian 12, x86_64, usual packages from the main repo, no additional SW other then lazygit, no containers etc.

![issue_repeated_commits_in_history](https://github.com/user-attachments/assets/9ee23778-28c8-4688-9919-50770efcc184)

**Comment by MilanV** [comment]
As it looks as redrawing issue, I add these details, too:

terminal: qterminal, set as xterm-256color in preferences (a value of $TERM)

**Comment by stefanhaller** [comment]
Thanks for the very precise reproduction steps, it was very easy to reproduce with these. Here's a fix: #3783

**Comment by MilanV** [comment]
Thank you for such a quick fix, Stefan.
I tried to learn, install and run go quickly enough to be able to provide you a feedback :) but, unfortunately, I'm not able to compile lazygit here. Sorry for that. I try to figure this out or wait for your package, whatever comes sooner :)
