### ISSUE TITLE
VIM mode in the `commit description` editor

### ISSUE THREAD

**Issue by khaled4vokalz** [jesseduffield/lazygit#3785]
**Is your feature request related to a problem? Please describe.**
When I am in vim/neovim I expect everything that's some sort of sub editor inside it to be as close as that (VIM). Currently, the Commit description panel is not like that. I have use the ARROW keys to go forward/backward, to make it worse the CTRL+Arrow does not work there.

**Describe the solution you'd like**
The commit description editor should support VIM mode by default (Isn't it obvious?)

**Describe alternatives you've considered**
none

**Additional context**
I'm really confused why it's not the case from the beginning? I am guessing there are some limitations that is making it not work with VIM mode in the commit description editor? Probably, I'm missing something?

**Comment by mark2185** [comment]
It's supposed to be a simple text edit window, you have emacs mappings if you need them, but if you really want `vim`, then set it as your editor and commit using `C`, or press `<c-o>` in the commit window and select it there.

**Comment by khaled4vokalz** [comment]
>It's supposed to be a simple text editing window

I understand. But IMO it'll be a nice feature that I don't have to go for the actual VIM editor itself to write the message, rather do that part in this editor directly. It's just the keymaps right? we have it there everywhere in the lazygit console except for this part which is a bit weird...

**Comment by mark2185** [comment]
It's not just keymaps, it's at least two modes (`normal` and `insert`, but then someone will ask for `visual` as well) with a dozen key bindings (some of them should be two-part e.g. `f`/`t`, `d`, `c`).

All in all, complexity ramps up really quickly when someone could just press `C` and use the real thing.

**Comment by khaled4vokalz** [comment]
okay, I guess I understand what you're trying to say... I'll close this... Just one more thing, is there any config option to make the VIM editor to be default as the commit editor? so that the VIM editor opens up when I press `c` e.g.?

**Comment by khaled4vokalz** [comment]
okay, found it `commitChangesWithEditor`

**Comment by mark2185** [comment]
> okay, found it `commitChangesWithEditor`

If you set the editor in your global `git` config, `lazygit` should pick that up:
```
git config --global core.editor "vim"
```

You'll also get `vim` when you invoke `git` things that require input from the CLI as well so it's a win-win.

**Comment by lionel-** [comment]
Just noting that yazi (https://yazi-rs.github.io/) provides modal editing when e.g. renaming files. It's very simple but quite handy to have it there in the app. I think this shows how vim-like editing can be implemented without excessive feature creep (for anything more complex jumping into `$EDITOR` is there).

**Comment by mark2185** [comment]
Sure, but having a modal editor at all can be considered feature creep :)
