### ISSUE TITLE
Amend last commit removes part of commit message

### ISSUE THREAD

**Issue by carlmartus** [jesseduffield/lazygit#379]
**Describe the bug**
When using the feature *amend last commit* in the files view.
All lines after the first line in the commit message are removed.

**To Reproduce**
1. Create a new repository.
```sh
git init
```
2. Add some junk:
```sh
echo a > a
git add a
```
3. Add a multi line commit message:
```sh
git commit -m "Topic line

Commit description"
```
3. Change something:
```sh
echo b > a
```
4. Start lazygit.
5. Stage the change.
6. Press `A` (*amend last commit*) in the files view.
7. Confirm pop-up dialog.
8. The commit message has now changed. The commit description has disappeared.

**Expected behavior**
The commit message should not change.
It should be:
```txt
Topic line

Commit description
```

Not this:
```txt
Topic line
```

**Desktop (please complete the following information):**
 - OS: Ubuntu 16.04
 - Lazygit Version 0.6 (`commit=3a607061a2303d9f45d308de652fbebe7300b43c, build date=2019-01-19T01:37:45Z, build source=binaryRelease, version=0.6, os=linux, arch=amd64`).

**Comment by jesseduffield** [comment]
This is fixed in v0.7.2 :)
