### ISSUE TITLE
Lazygit exits when it's not in a Git repo

### ISSUE THREAD

**Issue by bartopine** [jesseduffield/lazygit#3795]
**Describe the bug**
the old version of lazygit will still run when not it a git repo
❯ gh
2024/08/03 17:18:42 Error: must be run inside a git repository

**Version info:**
 ❯ lazygit --version
commit=71ad3fac63a3ef3326021837b49e9497d332818b, build date=2024-07-13T10:24:19Z, build source=binaryRelease, version=0.43.1, os=windows, arch=amd64, git version=2.41.0.windows.1

**Expected behavior**
Previous versions will still run

**Comment by mark2185** [comment]
Should be fixed by #3779.

**Comment by WillEhrendreich** [comment]
@mark2185 that's good news, but the last version available via releases here and chocolatey is still the broken one. Since this is fixed can we get a release?

**Comment by stefanhaller** [comment]
Fixed in v0.44.
