### ISSUE TITLE
Contrast Issues (panel borders)

### ISSUE THREAD

**Issue by jesseduffield** [jesseduffield/lazygit#38]
I pushed a commit to increase the contrast of the highlighted panel vs the other panels as a few people suggested, and although it's looking good on all my iterm themes, I don't have full visibility over what it looks like for everybody. So if your contrast is out of whack, please let me know here :)

What mine currently looks like:
![image](https://user-images.githubusercontent.com/8456633/43722239-2681b1f4-99d8-11e8-8c6f-bd740ede7423.png)

**Comment by ponsfrilus** [comment]
See #17 for Color Scheme.

**Comment by karlmutch** [comment]
when using termite with TERM=xterm-termite and COLORTERM=truecolor the inactive borders disappear, what is unusual is that I see this in the screen shots others have included with their tickets.

Session is on Ubuntu 16.04 using termite v13
X11 Client is on OSX with XQuartz 2.7.11 (xorg-server 1.18.4)

![screen shot 2018-08-08 at 10 30 58 am](https://user-images.githubusercontent.com/1184005/43854064-b4958276-9af6-11e8-8837-5544e1e46977.png)

**Comment by jesseduffield** [comment]
yeah theres been quite a few people across all platforms with the black borders on inactive panels so ive reverted the change back to white borders, pending actual color configuration. I'll close this ticket for now :)
