### ISSUE TITLE
Rewording last commit freezes when GPG passphrase is needed in CLI

### ISSUE THREAD

**Issue by Neko-Box-Coder** [jesseduffield/lazygit#3806]
**Describe the bug**
When you have GPG passphrase setup to be prompt in CLI, it will hang indefinitely when trying to reword the last commit. No input can reach the gpg prompt.

While it works when you just want to do a normal commit.

**To Reproduce**

1. Have your GPG setup with passphrase, see [here](https://docs.github.com/en/authentication/managing-commit-signature-verification/generating-a-new-gpg-key)
2. Change GPG to ask passphrase in CLI by having `pinentry-mode loopback` in `~/.gnupg/gpg.conf`
3. Maybe restart your gpg agent by doing `gpg-connect-agent reloadagent /bye`
4. Reword the last commit in a repo by going to the Commits panel and press **r** on the last commit
5. Type your reworded message and press enter
6. See it asks for passphrase on top of lazygit TUI

**Expected behavior**
You should be able to enter your passphrase and submit it to GPG prompt.

**Screenshots**
![image](https://github.com/user-attachments/assets/8197c991-7179-405f-8171-21a6c9f76df8)

**Version info:**
`commit=v0.42.0, build date=2024-05-19T10:54:29Z, build source=binaryRelease, version=0.42.0, os=linux, arch=amd64, git version=2.45.2`

**Additional context**
This relates #3758 and #30.

It seems like it goes through the same code path as rebasing which does not have explicit GPG support.

The line in question is in here:
https://github.com/jesseduffield/lazygit/blob/a3560eb451fcf375378a316cbc2f4e08e24bf756/pkg/commands/git_commands/rebase.go#L37-L41

GPG works fine when committing normally, it goes to a different code path which can handle gpg.

https://github.com/jesseduffield/lazygit/blob/a3560eb451fcf375378a316cbc2f4e08e24bf756/pkg/gui/controllers/helpers/working_tree_helper.go#L103-L110

The question is just to access `gpghelper` from `RebaseCommands` and wrap the commands using `gpghelper`.

Maybe I can try to figure it out this weekend or this month when I am free, could also see if I can add initial gpg support to rebasing as mentioned here.

https://github.com/jesseduffield/lazygit/blob/a3560eb451fcf375378a316cbc2f4e08e24bf756/pkg/commands/git_commands/rebase.go#L392-L405

**Comment by stefanhaller** [comment]
An easier fix is probably to make the distinction of "is this the head commit" at the call site of `RebaseCommands.RewordCommit` (in `LocalCommitsController.handleReword`) rather than inside it. LocalCommitsController has access to the gpgHelper. This would then be similar to what we already do for Amend.
