### ISSUE TITLE
Crash when filtering by author

### ISSUE THREAD

**Issue by mark2185** [jesseduffield/lazygit#3812]
**Describe the bug**
The application crashes when filtering the commits by user (but not always, can't really pinpoint it, it's something when refreshing the view).

**To Reproduce**

1. Open `lazygit` in the `lazygit` repo
2. Go to `commits` panel
3. Filter the commits by author, e.g. `Luke Swan` (note: can pretty consistently crash it with this author or myself, but not all of them)
4. Exit that view, press `<c-s>` again and just press `Filter by <the current author>`
5. Crash

**Expected behavior**
No crashes.

**Screenshots**
Asciinema recording [here](https://asciinema.org/a/XJ0t35wROY2fBlsZM9ujgH7eb).

**Version info:**
`lazygit` version: built latest `master` as of today, `git` version `2.46.0`

**Additional context**
It seems like [these columnPositions](https://github.com/jesseduffield/lazygit/blob/a3560eb451fcf375378a316cbc2f4e08e24bf756/pkg/gui/context/local_commits_context.go#L212) have only one element so both accesses are out of bounds.

**Note:** please try updating to the latest version or [manually building](https://github.com/jesseduffield/lazygit/#manual) the latest `master` to see if the issue still occurs.

**Comment by stefanhaller** [comment]
I can reproduce it, I'll have a look. I think it happens whenever you are scrolled down so much that the selection index in the unfiltered list is larger than the length of the filtered list.

**Comment by stefanhaller** [comment]
@mark2185 Here's a fix, can you please have a look and/or test? #3838

**Comment by mark2185** [comment]
@stefanhaller seems to have done it, I can't crash it anymore, thanks!

As for reviewing, all the `gocui` things go over my head so can't really pass judgement on that.
