### ISSUE TITLE
Range select with more than just up/down arrows

### ISSUE THREAD

**Issue by socketbox** [jesseduffield/lazygit#3823]
**Is your feature request related to a problem? Please describe.**
I can't seem to select a range of text in the Unstaged Changes box without selecting one line at a time by pressing or holding down the up/down arrows. This is very slow and tedious.

**Describe the solution you'd like**
Ideally, I'd be able to select text using vim-like shortcuts, but I understand that the shortcut space is already quite crowded. But it would be super cool to be able to hit `v` and then have lazygit change keymaps and support all of the standard `vim`-like shortcuts (`ctrl-d` /`ctrl-u`, `gg`/`G`, etc).  But, short of  that, hitting `v` to toggle range selection and then using either `<`/`>` or `,`/`.` to select a range would be sufficient.

**Comment by stefanhaller** [comment]
I'm skeptical about vim-like shortcuts, for reasons that have been discussed here a few times (I'm too lazy to dig up references, sorry). But using `<`/`>` and `,`/`.` should totally work in range mode, and I'd call it a bug that they don't. Actually, they do in list views (e.g. in the commits panel), just not in the staging view.
