### ISSUE TITLE
`M` no longer in yellow to signify staged modifications/commit

### ISSUE THREAD

**Issue by socketbox** [jesseduffield/lazygit#3824]
**Topic**
It seems that the `M` shown to the left of the filename in the `Files` tab of pane 2 is no longer in yellow (or, at least, a color) to indicate that changes/modifications have been staged. 

**Your thoughts**
Is there a reason for this change?

**Comment by stefanhaller** [comment]
I think the M was never yellow. It is red for unstaged changes and green for staged changes; if there is both in a single file, it shows two Ms, one red, one green. It is the file names whose coloring has changed recently (here's the details: 7c3d8921b737), but they still get yellow if a file has both staged and unstaged changes.

**Comment by socketbox** [comment]
Thanks for the reply. This is an issue with the theme I've selected. In a raw xterm terminal, what you've described is indeed the case.
