### ISSUE TITLE
Commit "Reset" does not do anything

### ISSUE THREAD

**Issue by avario-cpu** [jesseduffield/lazygit#3831]
**Describe the bug**
Title.

**To Reproduce**

1. Go to commit reflog
2. Select latest commit
3. Press g
4. Press m for "mixed reset", or enter to select the option. (same for soft btw.. don't want to try hard for my current situation)

**Expected behavior**
Removes commit for reflog and puts its content back as unstanged changes. ( git reset HEAD~1)

**Version info:**
_Run `lazygit --version` and paste the result here_ version=0.43.1

_Run `git --version` and paste the result here_ version 2.45.1.windows.1

**Additional context**
I'm on the same branch from which the commit originated. The commit I'm trying to reset has not been pushed. "git reset HEAD~1" in bash works as expected when executed on the same target commit.

**Comment by stefanhaller** [comment]
This is not a bug. You need to select the last commit that you want to keep, i.e. the one before the last commit in your case. This is no different from the command line; you are passing HEAD~1, which means the parent of the HEAD commit.

**Comment by avario-cpu** [comment]
Ah !

Well thank you 👍 

Sorry for my ignorance
