### ISSUE TITLE
checksum is mismatch

### ISSUE THREAD

**Issue by skanehira** [jesseduffield/lazygit#384]
**Describe the bug**
I used  the go module to run main.go but checksum error is was happened.

**To Reproduce**
1. Create a container from golang:1.12 image.
2. Attach the container.
3. git clone this repo.
4. cd repo dir and execute the command `go run main.go`.
5. See error

<details>
<summary>operation log</summary>
<pre>
<code>
root@db07ca83412d:/go# git clone https://github.com/jesseduffield/lazygit.git
Cloning into 'lazygit'...
remote: Enumerating objects: 2, done.
remote: Counting objects: 100% (2/2), done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 8590 (delta 0), reused 1 (delta 0), pack-reused 8588
Receiving objects: 100% (8590/8590), 9.98 MiB | 5.41 MiB/s, done.
Resolving deltas: 100% (5175/5175), done.
root@db07ca83412d:/go#
root@db07ca83412d:/go#
root@db07ca83412d:/go#
root@db07ca83412d:/go# cd lazygit/
root@db07ca83412d:/go/lazygit# ls -la
total 120
drwxr-xr-x 10 root root  4096 Mar  8 05:01 .
drwxrwxrwx  1 root root  4096 Mar  8 05:01 ..
drwxr-xr-x  2 root root  4096 Mar  8 05:01 .circleci
drwxr-xr-x  8 root root  4096 Mar  8 05:01 .git
drwxr-xr-x  3 root root  4096 Mar  8 05:01 .github
-rw-r--r--  1 root root   238 Mar  8 05:01 .gitignore
-rw-r--r--  1 root root  1475 Mar  8 05:01 .goreleaser.yml
-rw-r--r--  1 root root  3344 Mar  8 05:01 CODE-OF-CONDUCT.md
-rw-r--r--  1 root root  1634 Mar  8 05:01 CONTRIBUTING.md
-rw-r--r--  1 root root   507 Mar  8 05:01 Dockerfile
-rw-r--r--  1 root root 18822 Mar  8 05:01 Gopkg.lock
-rw-r--r--  1 root root  1082 Mar  8 05:01 Gopkg.toml
-rw-r--r--  1 root root  1071 Mar  8 05:01 LICENSE
-rw-r--r--  1 root root  5452 Mar  8 05:01 README.md
drwxr-xr-x  3 root root  4096 Mar  8 05:01 docs
-rw-r--r--  1 root root  2990 Mar  8 05:01 go.mod
-rw-r--r--  1 root root 12253 Mar  8 05:01 go.sum
-rw-r--r--  1 root root  1397 Mar  8 05:01 main.go
drwxr-xr-x 11 root root  4096 Mar  8 05:01 pkg
drwxr-xr-x  3 root root  4096 Mar  8 05:01 scripts
drwxr-xr-x  4 root root  4096 Mar  8 05:01 test
-rwxr-xr-x  1 root root   585 Mar  8 05:01 test.sh
drwxr-xr-x  5 root root  4096 Mar  8 05:01 vendor
root@db07ca83412d:/go/lazygit# go run main.go
go: finding github.com/mattn/go-runewidth v0.0.2
go: finding github.com/src-d/gcfg v1.3.0
go: finding github.com/hashicorp/go-getter v0.0.0-20180809191950-4bda8fa99001
go: finding github.com/kardianos/osext v0.0.0-20170510131534-ae77be60afb1
go: finding github.com/mattn/go-isatty v0.0.3
go: finding github.com/go-errors/errors v1.0.1
go: finding github.com/spf13/afero v1.1.1
go: finding github.com/mgutz/str v1.2.0
go: finding github.com/spf13/cast v1.2.0
go: finding github.com/jesseduffield/go-getter v0.0.0-20180822080847-906e15686e63
go: finding github.com/go-ini/ini v1.38.2
go: finding github.com/cloudfoundry/jibber_jabber v0.0.0-20151120183258-bcc4c8345a21
go: finding github.com/jesseduffield/termbox-go v0.0.0-20180919093808-1e272ff78dcb
go: finding golang.org/x/crypto v0.0.0-20180808211826-de0752318171
go: finding golang.org/x/net v0.0.0-20180811021610-c39426892332
go: finding github.com/hashicorp/go-cleanhttp v0.0.0-20171218145408-d5fe4b57a186
go: finding github.com/mitchellh/mapstructure v0.0.0-20180715050151-f15292f7a699
go: finding github.com/aws/aws-sdk-go v1.15.21
go: finding github.com/stvp/roll v0.0.0-20170522205222-3627a5cbeaea
go: finding github.com/davecgh/go-spew v1.1.0
go: finding gopkg.in/warnings.v0 v0.1.2
go: finding github.com/heroku/rollrus v0.0.0-20180515183152-fc0cef2ff331
go: finding gopkg.in/src-d/go-billy.v4 v4.2.0
go: finding github.com/magiconair/properties v1.8.0
go: finding github.com/pelletier/go-toml v1.2.0
go: finding github.com/hashicorp/go-safetemp v0.0.0-20180326211150-b1a1dbde6fdc
go: finding github.com/mitchellh/go-testing-interface v0.0.0-20171004221916-a61a99592b77
go: finding gopkg.in/yaml.v2 v2.2.1
go: finding github.com/fatih/color v1.7.0
go: finding github.com/bgentry/go-netrc v0.0.0-20140422174119-9fd32a8b3d3d
go: finding github.com/jesseduffield/gocui v0.0.0-20190305102456-f0f0ab442e6c
go: finding github.com/xanzy/ssh-agent v0.2.0
go: finding github.com/hashicorp/hcl v0.0.0-20180404174102-ef8a98b0bbce
go: finding github.com/jesseduffield/pty v0.0.0-20181218102224-02db52c7e406
go: finding github.com/shibukawa/configdir v0.0.0-20170330084843-e180dbdc8da0
go: finding github.com/nicksnyder/go-i18n v0.0.0-20180803040939-a16b91a3ba80
go: finding github.com/sergi/go-diff v1.0.0
go: finding github.com/mitchellh/go-homedir v0.0.0-20180801233206-58046073cbff
go: finding github.com/emirpasic/gods v1.9.0
go: finding github.com/spkg/bom v0.0.0-20160624110644-59b7046e48ad
go: finding github.com/golang-collections/collections v0.0.0-20130729185459-604e922904d3
go: finding gopkg.in/check.v1 v0.0.0-20161208181325-20d25e280405
go: finding github.com/spf13/jwalterweatherman v0.0.0-20180814060501-14d3d4c51834
go: finding github.com/spf13/pflag v1.0.2
go: finding github.com/ulikunitz/xz v0.5.4
go: finding github.com/sirupsen/logrus v1.0.6
go: finding github.com/spf13/viper v1.1.0
go: finding github.com/hashicorp/go-version v1.0.0
go: finding github.com/jbenet/go-context v0.0.0-20150711004518-d14ea06fba99
go: finding github.com/kevinburke/ssh_config v0.0.0-20180317175531-9fc7bb800b55
go: finding github.com/jmespath/go-jmespath v0.0.0-20160202185014-0b12d6b521d8
go: finding github.com/mattn/go-colorable v0.0.9
go: finding golang.org/x/sys v0.0.0-20180810173357-98c5dad5d1a0
go: finding github.com/pelletier/go-buffruneio v0.2.0
go: finding gopkg.in/src-d/go-git.v4 v4.0.0-20180807092216-43d17e14b714
go: finding github.com/tcnksm/go-gitconfig v0.1.2
go: finding github.com/pkg/errors v0.8.0
go: finding github.com/fsnotify/fsnotify v1.4.7
go: finding github.com/go-ini/ini v1.25.4
go: downloading github.com/go-errors/errors v1.0.1
go: downloading gopkg.in/src-d/go-git.v4 v4.0.0-20180807092216-43d17e14b714
go: downloading github.com/cloudfoundry/jibber_jabber v0.0.0-20151120183258-bcc4c8345a21
go: downloading gopkg.in/yaml.v2 v2.2.1
go: downloading github.com/mgutz/str v1.2.0
go: downloading github.com/heroku/rollrus v0.0.0-20180515183152-fc0cef2ff331
go: downloading github.com/spf13/viper v1.1.0
go: extracting github.com/cloudfoundry/jibber_jabber v0.0.0-20151120183258-bcc4c8345a21
go: downloading github.com/fatih/color v1.7.0
go: downloading github.com/tcnksm/go-gitconfig v0.1.2
go: extracting github.com/mgutz/str v1.2.0
go: extracting github.com/go-errors/errors v1.0.1
go: extracting github.com/heroku/rollrus v0.0.0-20180515183152-fc0cef2ff331
go: downloading github.com/jesseduffield/gocui v0.0.0-20190305102456-f0f0ab442e6c
go: downloading github.com/shibukawa/configdir v0.0.0-20170330084843-e180dbdc8da0
go: extracting github.com/tcnksm/go-gitconfig v0.1.2
go: downloading github.com/spkg/bom v0.0.0-20160624110644-59b7046e48ad
go: downloading github.com/pkg/errors v0.8.0
go: extracting github.com/shibukawa/configdir v0.0.0-20170330084843-e180dbdc8da0
go: downloading github.com/sirupsen/logrus v1.0.6
go: extracting gopkg.in/yaml.v2 v2.2.1
go: extracting github.com/spkg/bom v0.0.0-20160624110644-59b7046e48ad
go: extracting github.com/jesseduffield/gocui v0.0.0-20190305102456-f0f0ab442e6c
go: extracting github.com/spf13/viper v1.1.0
go: downloading github.com/mattn/go-runewidth v0.0.2
go: downloading github.com/spf13/afero v1.1.1
go: extracting github.com/pkg/errors v0.8.0
go: downloading github.com/pelletier/go-toml v1.2.0
go: downloading github.com/jesseduffield/pty v0.0.0-20181218102224-02db52c7e406
go: downloading github.com/spf13/cast v1.2.0
go: downloading github.com/hashicorp/hcl v0.0.0-20180404174102-ef8a98b0bbce
go: extracting github.com/sirupsen/logrus v1.0.6
go: downloading golang.org/x/sys v0.0.0-20180810173357-98c5dad5d1a0
go: extracting github.com/jesseduffield/pty v0.0.0-20181218102224-02db52c7e406
go: downloading github.com/spf13/jwalterweatherman v0.0.0-20180814060501-14d3d4c51834
go: extracting github.com/mattn/go-runewidth v0.0.2
go: downloading github.com/kardianos/osext v0.0.0-20170510131534-ae77be60afb1
go: extracting github.com/spf13/afero v1.1.1
go: extracting github.com/spf13/cast v1.2.0
go: downloading github.com/stvp/roll v0.0.0-20170522205222-3627a5cbeaea
go: extracting github.com/kardianos/osext v0.0.0-20170510131534-ae77be60afb1
go: downloading github.com/magiconair/properties v1.8.0
go: extracting github.com/spf13/jwalterweatherman v0.0.0-20180814060501-14d3d4c51834
go: downloading github.com/nicksnyder/go-i18n v0.0.0-20180803040939-a16b91a3ba80
go: downloading golang.org/x/crypto v0.0.0-20180808211826-de0752318171
go: extracting github.com/pelletier/go-toml v1.2.0
go: extracting github.com/stvp/roll v0.0.0-20170522205222-3627a5cbeaea
go: downloading github.com/jesseduffield/go-getter v0.0.0-20180822080847-906e15686e63
go: downloading github.com/jesseduffield/termbox-go v0.0.0-20180919093808-1e272ff78dcb
go: extracting github.com/hashicorp/hcl v0.0.0-20180404174102-ef8a98b0bbce
go: downloading github.com/fsnotify/fsnotify v1.4.7
go: extracting github.com/magiconair/properties v1.8.0
go: extracting gopkg.in/src-d/go-git.v4 v4.0.0-20180807092216-43d17e14b714
go: extracting github.com/jesseduffield/termbox-go v0.0.0-20180919093808-1e272ff78dcb
go: extracting github.com/fatih/color v1.7.0
go: downloading github.com/golang-collections/collections v0.0.0-20130729185459-604e922904d3
go: extracting github.com/fsnotify/fsnotify v1.4.7
verifying github.com/jesseduffield/go-getter@v0.0.0-20180822080847-906e15686e63: checksum mismatch
        downloaded: h1:tbm85YuPi3d1LFAUr6yZyzZ4vR96ygV98rezZZ+ywbg=
        go.sum:     h1:Nrr/yUxNjXWYK0B3IqcFlYh1ICnesJDB4ogcfOVc5Ns=
root@db07ca83412d:/go/lazygit#
</code>
</pre>
</details>

**Expected behavior**
Can run main.go

**Screenshots**
See operation log.

**Desktop (please complete the following information):**
 - OS: 
```
root@db07ca83412d:/go# cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

 - Lazygit Version
latest
 - The last commit id if you built project from sources (run : ```git-rev parse HEAD```)
`1b6e46973ebfdb6ba873fac6a2ce05bb1f8db8c1`

**Additional context**
I was try below and it was worked.
You can see [there](https://roberto.selbach.ca/intro-to-go-modules/) about `go mod tidy`
```
$ rm -rf go.sum
$ go mod tidy -v
```

**Comment by jesseduffield** [comment]
I've removed support for gomodules, so this should no longer be an issue :)
