### ISSUE TITLE
Feature request: Implement `git log --graph --all` functionality in LazyGit

### ISSUE THREAD

**Issue by screw-hand** [jesseduffield/lazygit#3845]
**Is your feature request related to a problem? Please describe.**
Currently, LazyGit doesn't provide a built-in way to view a graph of all branches, including remote branches, similar to the `git log --graph --all` command in the terminal. This makes it difficult to visualize the entire commit history and branch structure within the LazyGit interface.

**Describe the solution you'd like**
I would like to see a feature in LazyGit that implements the functionality of `git log --graph --all`. This would allow users to visualize the commit history of all branches, including remote branches, in a graphical format within the LazyGit interface. Ideally, this could be accessed through a new view or an option in the existing commits view.

**Describe alternatives you've considered**
1. Using a custom command to execute `git log --graph --all` and display the output. However, this doesn't provide the interactive experience that LazyGit usually offers.
2. Exiting LazyGit to use the terminal command, but this interrupts the workflow within LazyGit.

**Additional context**
This feature would be particularly useful for understanding complex branch structures and merge histories across all branches in a repository. It would enhance LazyGit's ability to provide a comprehensive view of the repository's history.

While a custom command could potentially achieve this, having it as a built-in feature would provide a more integrated and user-friendly experience, consistent with LazyGit's design philosophy.

**Comment by mark2185** [comment]
> Ideally, this could be accessed through a new view or an option in the existing commits view.

There's a option under `<c-l>` in the `commits` panel to pass the `--all` flag to `git log`, is that what you're looking for?

Also there are options you could take a look at [here](https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md), e.g. `log.showWholeGraph`, or setting the [default git log command](https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md#custom-git-log-command), do these help?

**Comment by screw-hand** [comment]
> There's a option under `<c-l>` in the `commits` panel to pass the `--all` flag to `git log`, is that what you're looking for?

Yes, this is very convenient! And what I need is `log.showWholeGraph`. I'm extremely grateful to you.
