### ISSUE TITLE
Add option to show modified filenames log panel

### ISSUE THREAD

**Issue by unikitty37** [jesseduffield/lazygit#3848]
**Is your feature request related to a problem? Please describe.**
The log panel shows the output of `git log`, but this does not give any indication of which files were modified.

**Describe the solution you'd like**
I'd like an option to pass the `--name-status` flag to `git log` when generating the log panel output, so each modified file is shown, as this makes it much easier to see if a commit is the one I want.

**Describe alternatives you've considered**
I considered a custom command, but this requires running it every time; this proposal is to add an option to change the behaviour of the log panel, so all the normal actions work as expected.

I considered tabbing to the local branches pane, selecting the current branch, then tabbing to the commits pane and stepping through, but:

* this is much slower, as you can only see one commit at a time
* this shows the full changes, not just filenames and whether they were modified, added or deleted; if the first file in a commit has a lot of changes, it's difficult enough to even get to the second file (especially since PgUp and PgDown only scroll a line at a time, so there's no way to go a page at a time)

**Additional context**
Output currently:

```
commit c5ec9302e3de3441c802cac4c6f7c25e543fe30a
Author: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Date:   Tue Jan 5 12:36:57 2021

    Bump axios from 0.19.0 to 0.21.1
```

Expected output:

```
commit c5ec9302e3de3441c802cac4c6f7c25e543fe30a
Author: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Date:   Tue Jan 5 12:36:57 2021

    Bump axios from 0.19.0 to 0.21.1

M       package-lock.json
M       package.json
```

**Comment by stefanhaller** [comment]
You can set the `git.branchLogCmd` config to whatever you want to achieve this. Try something like

```yaml
git:
    branchLogCmd: git log --name-status --graph --color=always --abbrev-commit --decorate --date=relative --pretty=medium {{branchName}} --
```


It's a bit unfortunate that there's no way to just add an option to the existing command. You could imagine something like `git.additionalBranchLogArgs: --name-status`, but we don't have that. So you need to look up what the default setting is (which is documented [here](https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md)), and then add your options to it.

**Comment by unikitty37** [comment]
Thanks — that's worked 👍
