### ISSUE TITLE
Add the ability to copy the 7-character commit hash in lazygit: [4] Commits :: `y` <== Add first 7 characters hash mode

### ISSUE THREAD

**Issue by ucomru** [jesseduffield/lazygit#3861]
Currently, in lazygit, pressing `y` on a commit opens a menu that allows users to copy the full commit hash (`y` + `space`). However, there are many situations where **only the first 7 characters** of the commit hash are needed, which is the standard shorthand for identifying commits in Git.

**Problem:**
There is no easy way to copy just the 7-character commit hash directly from the lazygit interface. Users have to either copy the full hash and manually trim it to 7 characters or use external tools.
It's more useful for the changelog.

**Proposal:**
Add a new option to the menu that opens with `y`, allowing users to copy only the first 7 characters of the commit hash. This would simplify workflows that require the short hash and improve efficiency.

I think the best way is: 
- `y` + ` ` -- the full commit hash
- `y` + `y` -- the first 7 characters of the commit hash

**Screenshot:**
<img width="1248" alt="scr" src="https://github.com/user-attachments/assets/9e14efe4-8428-47c5-9f61-cd76e2f9bd98">

**Comment by stefanhaller** [comment]
You can press ctrl-o in the commits list to copy a short hash. You can even configure how many characters you want, with the `git.truncateCopiedCommitHashesTo` config.

I deliberately left the `y enter` thing untruncated so that people have a choice to copy the full or the truncated hash.

**Comment by ucomru** [comment]
> You can press ctrl-o in the commits list to copy a short hash. You can even configure how many characters you want, with the `git.truncateCopiedCommitHashesTo` config.
> 
> I deliberately left the `y enter` thing untruncated so that people have a choice to copy the full or the truncated hash.

Thanks a lot!!!

**Comment by stefanhaller** [comment]
Just to elaborate more: ctrl-o is lazygit's generic copy command, it means copy whatever is currently selected in whichever view you are in. In the files view it copies the file path of the selected file; in the branches view the name of the selected branch; in the staging panel you can even copy selected lines of a patch this way.
