### ISSUE TITLE
Commit panel doesn't appear to update correctly

### ISSUE THREAD

**Issue by stevel05** [jesseduffield/lazygit#3889]
**Describe the bug**
Commits panel not updating correctly when switching branches

**To Reproduce**

Create an empty git repository in a new folder
Create a file, stage and commit it - Master shows 1 commit
Create a new branch
Make 3 small amendments and stage and commit each - branch shows 4 commits
switch branch back to main - master shows 4 commits
enter the stash panel or close and restart lazygit - commit panel for Master shows 1 commit

**Expected behavior**
The commit panel shows the actual commits for that branch. 
It doesn't appear to be cleared before updating with the new branch until you enter the stash panel ot restart lazygit.

**Screenshots**
Branch1 after 3 commits
![image](https://github.com/user-attachments/assets/822904ea-dc13-4db2-9d86-3703f06b99a4)
Switch to Master
![image](https://github.com/user-attachments/assets/3e0974e5-0791-4ad5-b96c-76188638a617)
Enter stash pane
![image](https://github.com/user-attachments/assets/2ac9bdc7-2c4a-4067-823f-2003e684c944)

**Version info:**
Windows 10
lazygit --version
commit=71ad3fac63a3ef3326021837b49e9497d332818b, build date=2024-07-13T10:24:19Z, build source=binaryRelease, version=0.43.1, os=windows, arch=amd64, git version=2.46.0.windows.1

Also tested on Linux Mint
lazygit --version
commit=71ad3fac63a3ef3326021837b49e9497d332818b, build
date=2024-07-13T10:24:19Z, build source=binaryRelease, version=0.43.1,
os=linux, arch=amd64, git version=2.34.1

And on Windows 11 latest lazygit, git version 2.35.1.windows.2 (Not my pc)

**Comment by stefanhaller** [comment]
Thanks for reporting; this is already fixed on master, see https://github.com/jesseduffield/lazygit/pull/3783.

**Comment by stevel05** [comment]
Ahh OK, I did check the issues and discussions before I reported it. So it just hasn't made the binary releases yet?

**Comment by stefanhaller** [comment]
A new release is overdue, I hope it won't take too long until then.

**Comment by stevel05** [comment]
Thanks
