### ISSUE TITLE
Release 0.44

### ISSUE THREAD

**Issue by jesseduffield** [jesseduffield/lazygit#3893]
It is time once again to cut a release for v0.44 (https://github.com/jesseduffield/lazygit/milestone/16).

Let me know if there's a PR you'd like to get in!

Tagging @stefanhaller @karimkhaleel @mark2185 @afhoffman @AzraelSec

**Comment by stefanhaller** [comment]
Nothing from my side. For #3892 I want to test it a bit more locally before we merge it (let alone release it), as I'm not quite sure yet if there might be situations where the behavior is unwanted after all. And for #3876 it might take a little while to iterate on it until we're all happy, and I don't think it's important enough to hold up a release.

I'd vote for releasing rather sooner than later, people keep reporting the same bugs that have long been fixed on master.

**Comment by jesseduffield** [comment]
Very well, it is done! https://github.com/jesseduffield/lazygit/releases/tag/v0.44.0
