### ISSUE TITLE
New Bug: "Error: must be run inside a git repository"

### ISSUE THREAD

**Issue by barnacker** [jesseduffield/lazygit#3895]
**Describe the bug**
Switched to latest 0.43.1 and now I can't invoke Lazygit from anywhere anymore, it has to be in a repo just to then be able to select the repo I want.

**To Reproduce**
Run Lazygit outside a repo, no matter if you set "skip" mode or whatever config settings, it just crashes instantly.

**Expected behavior**
Open Lazygit and either show the repo selector menu or load the last repo depending on my config and desired behaviour.

**Screenshots**
`2024/09/06 10:14:07 Error: must be run inside a git repository`

**Version info:**
commit=, build date=, build source=nix, version=0.43.1, os=linux, arch=amd64, git version=2.46.0
git version 2.46.0

**Comment by stefanhaller** [comment]
This is already fixed on master, see #3779. We'll hopefully have a new release soon.

**Comment by stefanhaller** [comment]
Fixed in v0.44.
