### ISSUE TITLE
Avoid reading whole files into memory

### ISSUE THREAD

**Issue by toniperic** [jesseduffield/lazygit#39]
Had a large un-staged file in the repo and while scrolling the file-list in lazygit it seemed like everything gets loaded into memory, even though the preview only shows a couple dozen of lines.

Could you maybe use use a different approach instead of reading everything?

**Comment by jesseduffield** [comment]
Yeah I think the best first step to this is limiting how much we render when selecting files, and then asynchronously load the whole thing when you start scrolling on it. I'll make a 'performance' milestone and tag this issue with it
