### ISSUE TITLE
How I can discard unstaged changes

### ISSUE THREAD

**Issue by ellipticaldoor** [jesseduffield/lazygit#390]
**Is your feature request related to a problem? Please describe.**
So I'm moving from GitSavvy into lazygit because it doesn't depends on sublime text and it has a very similar way of handling git. All I'm used to do with GitSavvy I can do it with lazygit except to discard unstaged changes.

For example I edit a file, the I stage the change, then before I commit I make another change to the file. Now instead of adding again the change into the stage what I want to do is to destroy the change so the stage goes as it was.

![image](https://user-images.githubusercontent.com/3449006/54320023-869f7280-45e3-11e9-8527-28f392bdb26c.png)

"[d] discard changes to file" and "[D] discard all unstaged changes" is what I would like.

**Describe the solution you'd like**
Not sure if this can be done already with lazygit, I tried every option but none of them has the behaviour I described above.

With this git commands I can accomplish this

``` shell
# For all unstaged files in current working directory use:
git checkout -- .

# For a specific file use:
git checkout -- path/to/file/to/revert
```

Could be possible to achieve this with lazygit?

**Comment by jesseduffield** [comment]
I've just put up a PR that will support this functionality. hitting 'd' on a file now brings up a menu where if there are both staged and unstaged changes to a file, you can remove the unstaged changes.

Likewise if you hit 'D' there are various options for resetting the worktree, including 'git checkout -- .'

Please pull down the branch and test it out, and let me know if you have any suggestions for improvement :)

**Comment by ellipticaldoor** [comment]
Cool!, I will try it in a moment

**Comment by ellipticaldoor** [comment]
@jesseduffield how I can build the project? I'm not used to go and I can't find how to build the app.

**Comment by jesseduffield** [comment]
Installation instructions are here:
https://github.com/jesseduffield/lazygit#go

But they're a bit brief. `go run main.go` should do the trick. Otherwise, `go install && lazygit`

**Comment by ellipticaldoor** [comment]
Uhm, I'm getting this error when trying to install from the branch

```
 $ go run main.go                                                                                                                                                 [16:55:40]
go: downloading golang.org/x/sys v0.0.0-20180810173357-98c5dad5d1a0
go: downloading github.com/jesseduffield/go-getter v0.0.0-20180822080847-906e15686e63
go: downloading github.com/fatih/color v1.7.0
go: downloading github.com/tcnksm/go-gitconfig v0.1.2
go: downloading golang.org/x/text v0.3.0
go: extracting github.com/tcnksm/go-gitconfig v0.1.2
go: downloading gopkg.in/src-d/go-git.v4 v4.0.0-20180807092216-43d17e14b714
go: downloading golang.org/x/crypto v0.0.0-20180808211826-de0752318171
verifying github.com/jesseduffield/go-getter@v0.0.0-20180822080847-906e15686e63: checksum mismatch
	downloaded: h1:tbm85YuPi3d1LFAUr6yZyzZ4vR96ygV98rezZZ+ywbg=
	go.sum:     h1:Nrr/yUxNjXWYK0B3IqcFlYh1ICnesJDB4ogcfOVc5Ns=
```

**Comment by jesseduffield** [comment]
@ellipticaldoor hmm that's annoying. I've pushed a change that should fix that, although if you still get an error, you might need to install go/dep via `go get -u github.com/golang/dep/cmd/dep`.

But I think it should just work :) Let me know

**Comment by jesseduffield** [comment]
I've merged https://github.com/jesseduffield/lazygit/pull/398 into master. I've also removed support for go modules so that checksum mismatch shouldn't be an issue anymore. Let me know if you have any issues :)
