### ISSUE TITLE
Process suspended after shell command execution

### ISSUE THREAD

**Issue by abobov** [jesseduffield/lazygit#3903]
**Describe the bug**

When shell command executed with `:` hotkey lazygit process become suspended.

**To Reproduce**

1. Open lazygit
2. Type `:` to enter shell command menu
3. Type any command, ex.: `date`
4. Command output displayed and lazygit process suspended, your shell is open.

**Expected behavior**

Lazygit ask to press any key and after return to lazygit.

**Screenshots**

[demo.webm](https://github.com/user-attachments/assets/42fc45ca-b509-4dac-814e-48449a49bf00)

**Version info:**
_Run `lazygit --version` and paste the result here_

commit=2d0c7cb0fc85e3c262837eb9691813fa97e00e80, build date=2024-09-07T02:26:26Z, build source=binaryRelease, version=0.44.0, os=linux, arch=amd64, git version=2.39.2

_Run `git --version` and paste the result here_

git version 2.39.2

**Additional context**

Problem appears with version 0.44.0 and master.

**Comment by abobov** [comment]
Reverting https://github.com/jesseduffield/lazygit/pull/3793 on master fix my issue. Maybe it is now expected behavior now?

**Comment by stefanhaller** [comment]
No, it's not the expected behavior, and it doesn't happen for me.

I can't explain why this happens to you, but I suspect it has something to do with what's in your `.zshrc` (or maybe `.zprofile`). Could you post those?

**Comment by abobov** [comment]
It is not related to my zsh config.  I also tested it on debian:latest docker image with default bash:

```shell
docker run -it debian:latest

# In container shell
apt update && apt install -y git wget
wget https://github.com/jesseduffield/lazygit/releases/download/v0.44.0/lazygit_0.44.0_Linux_x86_64.tar.gz
tar xf lazygit_0.44.0_Linux_x86_64.tar.gz
git init
./lazygit
```

**Comment by huhu415** [comment]
i have the same issue, i am so confuse that i search everywhere. oh..

**Comment by stkr** [comment]
Just to add a bit more information, the behavior is reproducible also on WSL Ubuntu-24.04 with lazygit version 0.44.1_Linux_x86_64:
* It happens using either bash or fish - so does not seem to be shell (zsh) specific (?)
* It happens in windows conpty as well as alacritty as terminal emulator - so maybe not terminal specific either (?)
* The workaround of adding "</dev/null" as described above works in all tested cases
