### ISSUE TITLE
Umlaut (German characters) in diffs not displayed correctly

### ISSUE THREAD

**Issue by lobneroO** [jesseduffield/lazygit#3910]
**Describe the bug**
When diffing a file that contains an Umlaut (ÄÖÜäöü), lazygit prints questionmark characters.

See file opened in neovim:
![image](https://github.com/user-attachments/assets/c78fe3e6-c5d1-4400-8029-f109445c260c)

Versus diff opened in lazygit:
![image](https://github.com/user-attachments/assets/19b9f81d-7356-486b-a8cb-efd0c7ffb1cc)

**To Reproduce**
1. Create a file and add it to a git repository
2. Commit the file
3. Edit the file to contain an Umlaut character, e.g. (Ä)
4. Open Lazygit to view the diff

**Expected behavior**
All characters printed as expected, in this case Ä

**Screenshots**
Shown in description

**Version info:**
_Run `lazygit --version` and paste the result here_
> lg --version
commit=v0.44.0, build date=2024-09-07T08:46:08Z, build source=binaryRelease, version=0.44.0, os=linux, arch=amd64, git version=2.46.0

_Run `git --version` and paste the result here_
> git --version
git version 2.46.0

**Additional context**
Arch Linux, KDE's Konsole, Jet Brains Mono Font

**Note:** please try updating to the latest version or [manually building](https://github.com/jesseduffield/lazygit/#manual) the latest `master` to see if the issue still occurs.
Updated before the problem was visible

Logs:
```
Sep 14 11:27:12 |INFO| git worktree list --porcelain (1.041819ms) 
Sep 14 11:27:12 |DEBU| RunCommand command="git -C /home/tare/.config/nvim rev-parse --path-format=absolute --absolute-git-dir"
Sep 14 11:27:12 |INFO| git log HEAD --topo-order --oneline --pretty=format:%H%x00%at%x00%aN%x00%ae%x00%D%x00%p%x00%m%x00%s --abbrev=40 -300 --no-show-signature -- (2.501617ms) 
Sep 14 11:27:12 |DEBU| RunCommand command="git rev-parse --verify --quiet refs/heads/main"
Sep 14 11:27:12 |INFO| git -C /home/tare/.config/nvim rev-parse --path-format=absolute --absolute-git-dir (793.587µs) 
Sep 14 11:27:12 |INFO| postRefreshUpdate for worktrees took 32.982µs 
Sep 14 11:27:12 |INFO| postRefreshUpdate for reflogCommits took 1.213557ms 
Sep 14 11:27:12 |INFO| postRefreshUpdate for localBranches took 98.215µs 
Sep 14 11:27:12 |ERRO| <no msg> command="git rev-parse --verify --quiet refs/heads/main"
Sep 14 11:27:12 |INFO| git rev-parse --verify --quiet refs/heads/main (733.604µs) 

```

**Comment by stefanhaller** [comment]
This doesn't look like a lazygit issue to me, more like a general locale issue. My guess would be that it happens in the same way when using `git show` or `git diff` in the terminal. I could well be wrong, please confirm.

What's your `$LANG` environment variable set to? If it's empty, try if `export LANG=de_DE.UTF-8` makes a difference.

**Comment by lobneroO** [comment]
`git diff` does not show the correct character, you're right. But it is not a questionmark either:
![image](https://github.com/user-attachments/assets/2f91f077-cdbb-4513-b604-d80028a726e0)

`echo $LANG` returns C (not sure, what that is about...)
Changing it to de_DE.UTF-8 works, thank you

**Comment by lobneroO** [comment]
I have looked into this a bit more. Changin `LANG` led to at least some of my output being translated to German, which I do not want. With `git diff`, [others that have had the problem](https://makandracards.com/makandra/29621-fix-git-diff-show-umlauts-ascii-characters-properly) changed the `LESSCHARSET` to `UTF-8`, and I tried that - it works fine.
However, lazygit does not use less for its output (it seems), so while git diff does what I want, lazygit does not. I appreciate that this comes from system settings, so sorry if reopening is not exactly the best way to handle this problem. However I do not know what to look for here - is there anything other than `LANG` which lazygit uses?

**Comment by lobneroO** [comment]
Oh actually, never mind. Just using a LANG with UTF-8 (like `en_US.UTF-8` rather than `de_DE.UTF-8`)  does the trick

**Comment by stefanhaller** [comment]
Again, this is basic locale stuff, nothing specific to lazygit. LANG is just a catch-all umbrella setting that overrides the individual `LC_*` variables that you could use for more fine-tuned configuration. It sets the character set being used (which solves your question mark problem), but also the language to use (which you don't want), and other things, such as date and number formats. [This](https://stackoverflow.com/a/30480596) explains it a bit more.

There are several ways to achieve what you want; what I personally do is
```
export LANG=de_DE.UTF-8
export LC_MESSAGES=C
```

**Comment by stefanhaller** [comment]
> ... that overrides the individual `LC_*` variables

and that was not correct, of course. It doesn't override them, it acts as a fallback for any that are unset.
