### ISSUE TITLE
How to fetch remote branches?

### ISSUE THREAD

**Issue by philharmonie** [jesseduffield/lazygit#3912]
I am going to the `Local branches` tab by pressing `3`. Then I press `]` to go to the Remote branches. In my case, it shows
```
origin 7 branches
```
then I hit `enter` to list them, but now I can't press `f` to fetch or `p ` to pull.
How can I download a remote branch?

**Comment by mark2185** [comment]
Try pressing `?` in that panel to bring up help.

But you're probably looking for `space`.

**Comment by philharmonie** [comment]
That's it, thank you!
