### ISSUE TITLE
Copying the commit author adds single ticks in wrong places

### ISSUE THREAD

**Issue by ekorchmar** [jesseduffield/lazygit#3933]
**Describe the bug**
When copying author name (and e-mail), Lazygit adds single ticks around the coppied string; however, last ticks lands just before the closing angle bracket.

So instead of copying `'Eduard <korchmar.eduard+git@gmail.com>'`, it would end up with `'Eduard <korchmar.eduard+git@gmail.com'>`.

**To Reproduce**

1. Go to Commits panel in any repo with commits
2. Press `y` (copy commit attribute) and `a` (copy commit author)
3. Go into any text editor, shell or editable text field inside Lazygit
4. Paste the clipboard content and see the malformed author string.

**Expected behavior**
Added ticks surround the entire copied string.

**Screenshots**
![image](https://github.com/user-attachments/assets/6b72b970-31fe-4e20-9ac4-42347f34a549)

**Version info:**
_Run `lazygit --version` and paste the result here_
commit=v0.44.1, build date=2024-09-18T13:19:48Z, build source=binaryRelease, version=0.44.1, os=linux, arch=amd64, git version=2.46.1
_Run `git --version` and paste the result here_
git version 2.46.1

The bug is also observable in manually built binary from the current latest commit.

**Additional context**
I do not understand why ticks are being added at all, but I assume for portability? I will assume this is intended and useful.

**Comment by stefanhaller** [comment]
> **Additional context** I do not understand why ticks are being added at all, but I assume for portability? I will assume this is intended and useful.

No, it's neither intended nor useful. It's a regression introduced in v0.39 (in this commit: 25f8b0337).

Here's a fix: #3936
