### ISSUE TITLE
Is there an option to disable the "Loading ..." message in the main pane?

### ISSUE THREAD

**Issue by xuyangyuio** [jesseduffield/lazygit#3934]
**Topic**
The "Loading ..." message in the main pane shows up and disappear in less than a second when I switch branches in the Branches panel. The same when I switch commits in the Commits panel. The message might be informative but makes the screen "flickering".  Up to version 0.42, I have never noticed this "Loading ..." message in the main pane; maybe because lazygit was very fast to load the content in the main pane?

**Your thoughts**
An option to disable the "Loading ..." message will be nice.

**Comment by stefanhaller** [comment]
I only see the "Loading" message if my repo has accumulated a lot of cruft over time. I'm wondering if you are affected by [this problem](https://github.com/jesseduffield/lazygit/discussions/3965#discussioncomment-10841236). Please try the measures mentioned there and report back if this makes a difference.

**Comment by xuyangyuio** [comment]
Thanks @stefanhaller. I tried cleaning the repo aggressively. But that did not help much. The same problem even in a brand new repo with only one commit.

**Comment by xuyangyuio** [comment]
@stefanhaller Updating delta solved the problem.
