### ISSUE TITLE
How do you do `--allow-empty` commits

### ISSUE THREAD

**Issue by awalvie** [jesseduffield/lazygit#3942]
**Topic**
Trying to make an empty commit by pressing `c` in the `Files` pane, but every time I do I get the following error: 

![image](https://github.com/user-attachments/assets/836dba26-711f-4a4d-8676-91e1d43f1a91)

Am I just missing how to do this or has this not been implemented yet?

**Comment by stefanhaller** [comment]
It's not implemented. This is related to this discussion: #2849

As a workaround, you can type `:` to bring up the shell command prompt, and type `git commit --allow-empty -m "My message"` there.

**Comment by awalvie** [comment]
Gotcha, I'll close this issue in that case! Thanks for the help!
