### ISSUE TITLE
[Request] display diff between specific commits

### ISSUE THREAD

**Issue by skanehira** [jesseduffield/lazygit#397]
**Is your feature request related to a problem? Please describe.**
This a feature request.

**Describe the solution you'd like**
Add feature of diff between specific commits.

**Describe alternatives you've considered**
When use space to select 2 commit, then display diff between selected commits.
This operation like `git diff id1 id2`

**Additional context**
What do you think about this request?
If necessary I'll try implement.

**Comment by jesseduffield** [comment]
This sounds like a good feature to me.

After some thinking, I think we should only allow one commit to be selected, and then have the diff occur based on whatever is highlighted by the user. This means we can diff a commit against other commits as well as other branches, or commits in other branches if we want to checkout a branch and select something there.

If you hit space on a new commit, that commit becomes the new one that everything compares to. And if you hit space on an already selected commit, it un-selects it, and lazygit goes back to normal.

How does that solution sound? I'd be interested to know how quickly these diffs could be performed. If they are super slow, maybe we do need to allow two commits to be selected to be directly compared, however there's going to be some tricky logic to work out when it comes to selecting two different commits.

For example, if two commits are selected and we want to select another, which of the two original commits gets un-selected?

**Comment by skanehira** [comment]
@jesseduffield 

>This means we can diff a commit against >other commits as well as other branches, or commits in other branches if we want to checkout a >branch and select something there.

I think this idea is very good, but I don't know git can diff author branch commits.
I will try to find out about it

>If you hit space on a new commit, that commit becomes the new one that everything compares to. And if you hit space on an already selected commit, it un-selects it, and lazygit goes back to normal.

This is the same as my idea

>however there's going to be some tricky logic to work out when it comes to selecting two different commits.

isn't just run `git diff id1 id2` on lazygit?

>For example, if two commits are selected and we want to select another, which of the two original commits gets un-selected?

I was thinking that up to two commits could be selected.

**Comment by jesseduffield** [comment]
> isn't just run git diff id1 id2 on lazygit?

I meant that the ability to highlight two commits in the PR would be tricky, I wasn't referring to the actual git command that would diff the commits :)

**Comment by skanehira** [comment]
Sorry, I don't know where is tricky...
Can you tell me?

**Comment by jesseduffield** [comment]
I mean it's tricky to decide how the user will interact with the commits. lets say that hitting 'space' on a commit highlights it, and if you hit space on another commit, it also gets highlighted and now the diff that is shown is the diff of the two commits. If you then try to hit 'space' on another commit, do we un-highlight one of the original two commits, or just prevent the user from highlighting the third commit?

In order for another commit to be highlighted, do we require the user to go back and hit 'space' on one of the two original commits to de-highlight them?

**Comment by skanehira** [comment]
>In order for another commit to be highlighted, do we require the user to go back and hit 'space' on one of the two original commits to de-highlight them?

Yes, I think If user want to highlight another commit, need to de-highlight one of the two commits.

**Comment by jesseduffield** [comment]
yeah I think that makes sense. It's still worth testing if it's slow for the computer to just diff the highlighted branch with whatever the currently selected branch is, because that would make the interface easier

**Comment by skanehira** [comment]
Today I used lazygit on WSL it was very slow because my project has many files(over 2000).
I think it would be better to display two diffs after selecting two commits.

**Comment by jesseduffield** [comment]
fair enough :)

**Comment by skanehira** [comment]
Thank you for accepting my thoughts :)
I'll try implement this

**Comment by skanehira** [comment]
Hi @jesseduffield 
I implemented this :)
Please review 59f7fe0

**Comment by skanehira** [comment]
Close issue because it was implemented in c350cdb
