### ISSUE TITLE
[Status Panel] Keybindings link broken

### ISSUE THREAD

**Issue by marcelotedeschi** [jesseduffield/lazygit#399]
**Describe the bug**
After https://github.com/jesseduffield/lazygit/pull/395, The status panel link to keybindings is not working, as it's pointing to the old file: https://github.com/jesseduffield/lazygit/blob/ac5088eee691de5285ab8e08d825ad398c85441c/pkg/gui/status_panel.go#L64

**To Reproduce**
1. Go to Status Panel
2. Follow link to `Keybindings`

**Comment by jesseduffield** [comment]
Good pickup :) This is fixed in https://github.com/jesseduffield/lazygit/pull/400
