### ISSUE TITLE
Gitlab MR link broken if there are carriage returns

### ISSUE THREAD

**Issue by ginolegigot** [jesseduffield/lazygit#3999]
Hello!

**Describe the bug**
When a MR link is cut in several pieces because there are Carrriage Returns, the MR link appears clickable only on the first part

**To Reproduce**

Open lazygit in a small window, Push in a new branch, the MR link will be suggested. If the window is small enough the MR Link will be separated into several parts through line return. only the first part of the MR link will e clickable leading to a broken link in the browser

**Expected behavior**
The whole MR link remains clickable even if they are carriage returns.

**Screenshots**
![test](https://github.com/user-attachments/assets/f1c7ec08-d508-4985-a924-247f1b8b6fd5)
In the screenshot only the part with https://gitlab is clickable the rest of the link is not.

**Version info:**
commit=611fabde11d24d9acc71ee26077b9a1101f59f27, build date=2024-09-18T10:56:10Z, build source=binaryRelease, version=0.44.1, os=linux, arch=amd64, git version=2.43.0

**Comment by stefanhaller** [comment]
This should already be fixed in master, see #3914. If you can build from master, could you please verify this?

**Comment by ginolegigot** [comment]
Works like a charm thanks!
