### ISSUE TITLE
Discussion: Should we remove go modules support?

### ISSUE THREAD

**Issue by jesseduffield** [jesseduffield/lazygit#401]
At some point I made the decision to support go modules and I'm starting to regret it.

It may be that if we made the jump from go dep to go modules properly, rather than supporting both like we do now, it would fix the headache that we currently have.

But I've got no issue with go dep and it's workflow is really simple to follow, and to my knowledge removing go modules right now is a victimless crime. The only people affected would be those who pull down the source code and have go modules enabled in some strict way where they get an error if the project isn't using go modules.

I'm making this issue because I seem to continually bump into issues with go modules's checksum mismatches and just weird behaviour that I keep having to debug, and I can't see any point in it.

So please anybody who has an opinion let me know your thoughts :)

**Comment by mjarkk** [comment]
LGTM,  
Beside the points you mentioned i think most people know how go dep works and there are a lot of people that still use an older versions of go that doesn't have support for modules.

**Comment by jesseduffield** [comment]
that's all the confirmation I needed :) I'll put up a PR

**Comment by jesseduffield** [comment]
fixed in https://github.com/jesseduffield/lazygit/pull/402
