### ISSUE TITLE
Delete Multiple Branches

### ISSUE THREAD

**Issue by waelmahrous** [jesseduffield/lazygit#4041]
**Is your feature request related to a problem? Please describe.**
I work with many concurrent branches at a time and can not delete multiple branches simultaneously. I need to select one branch at a time.

**Describe the solution you'd like**
I would like the delete action, local or remote, to support range selection.

**Describe alternatives you've considered**
n/a

**Additional context**
This might be a good first issue for me to work on, if you find this request reasonable :)

**Comment by stefanhaller** [comment]
Implemented in #4073
