### ISSUE TITLE
Add config option to disable changing of tab when pressing multiple time a view key

### ISSUE THREAD

**Issue by peauc** [jesseduffield/lazygit#4042]
**Is your feature request related to a problem? Please describe.**
When I use lazygit and press a key the change the view, if I repress it again it changes the tab. It's annoying.

**Describe the solution you'd like**
A config option to disable it

**Comment by stefanhaller** [comment]
There's already [a PR](https://github.com/jesseduffield/lazygit/pull/3927) for this, but it hasn't been merged yet.

**Comment by peauc** [comment]
Thank you @stefanhaller for bringing this up. I was looking for it but missed it :)
