### ISSUE TITLE
[Feature] Horizontal scrolling in unstages/stages changes panels

### ISSUE THREAD

**Issue by lonix1** [jesseduffield/lazygit#4044]
**Is your feature request related to a problem? Please describe.**
The "Unstaged changes" and "Staged changes" panels often have long text which is clipped at the screen edge.

**Describe the solution you'd like**
It would be nice to be able to scroll horizontally in those panels, using the left/right keys. The same way one can scroll in *less*, *nano*, etc.

**Describe alternatives you've considered**
Buying a wider monitor.

**Additional context**
In those two panels, the left/right keys do not have default behaviours. So this would be a non-breaking change.

**Comment by mark2185** [comment]
> It would be nice to be able to scroll horizontally in those panels, using the left/right keys. The same way one can scroll in less, nano, etc.

You can scroll them like all other panels, using `H` and `L`. It looks like these aren't in the help menu, though.

> In those two panels, the left/right keys do not have default behaviours

They do, they jump between hunks. This is in the help menu under `?`.

**Comment by mark2185** [comment]
> For me "H" and "L" jump between hunks. (I did not customise those keys.)
>
> I'm referring to horizontal scrolling.

_Uppercase_ `H` and _uppercase_ `L`?

**Comment by stefanhaller** [comment]
@lonix1 Ok, that's good input, I'll make it configurable then.

Again, horizontal scrolling is available today, using uppercase `H` and `L`. It is the same as in other views that don't wrap, e.g. the commits view; this can sometimes be useful to read long commit messages. Lowercase `h` and `l` have the same function as left/right.
