### ISSUE TITLE
Add diff-menu to Keybinding overlay

### ISSUE THREAD

**Issue by SHU-red** [jesseduffield/lazygit#4061]
**Is your feature request related to a problem? Please describe.**
I fully aggree with: https://github.com/jesseduffield/lazygit/pull/768#issuecomment-2473035041
Had to search internet to find keybinding

**Describe the solution you'd like**
Just list <c-e> to "?" menu

**Describe alternatives you've considered**
none

**Additional context**
Not needing to diff often, makes me forget the binding
Having it in ? is convenient

**Comment by stefanhaller** [comment]
I think the comment that you are quoting is talking about the `<c-e>` key binding. That one is obsolete (I don't even know why it's still supported; @jesseduffield?).

The official key binding is `W`, which _is_ listed in the `?` menu.

**Comment by SHU-red** [comment]
You are right
Didnt see that

Thanks
