### ISSUE TITLE
Initial delay for autoFetch not applied to recent repositories

### ISSUE THREAD

**Issue by gwolves** [jesseduffield/lazygit#4083]
**Describe the bug**
I suspect this line is intended to introduce an initial delay before autoFetch for recently used repositories:
https://github.com/jesseduffield/lazygit/blob/c3cf48cc4976e45bff901cecc0686287c1ad2fbc/pkg/gui/background.go#L81-L83

However, since time.After returns a channel, the correct implementation should be:
```go
 if !isNew { 
 	<-time.After(time.Duration(userConfig.Refresher.FetchInterval) * time.Second) 
 } 
```

As a result, there is no initial delay before autoFetch starts.

**To Reproduce**

1. Open LazyGit on a recently used repository.
2. Observe that autoFetch runs immediately.

**Expected behavior**
The first autoFetch should occur after refresher.fetchInterval, assuming my interpretation is correct.

**Screenshots**

**Version info:**
commit=, build date=, build source=nix, version=0.44.1, os=darwin, arch=arm64, git version=2.46.0
git version 2.46.0

**Additional context**

**Comment by stefanhaller** [comment]
Fixed by #4084.
