### ISSUE TITLE
lazygit not loaded under branch created by `git worktree`

### ISSUE THREAD

**Issue by gzzengwei** [jesseduffield/lazygit#409]
**Describe the bug**
when under branch that created by `git worktree` , it cannot loaded.

**To Reproduce**
1. Go to your repo
2. create new branch with `git worktree add -b my_new_feature ./features/my_new_feature`
3. Go to branch folder: `cd ./features/my_new_feature`
4. run `lazygit`
5. See error
```
2019/03/28 11:18:21 An error occurred! Please create an issue at https://github.com/jesseduffield/lazygit/issues

*errors.errorString <nil>
/go/src/github.com/jesseduffield/lazygit/pkg/commands/git.go:35 (0x155f785)
/go/src/github.com/jesseduffield/lazygit/pkg/commands/git.go:87 (0x1568e79)
/go/src/github.com/jesseduffield/lazygit/pkg/commands/git.go:97 (0x155fb32)
/go/src/github.com/jesseduffield/lazygit/pkg/app/app.go:106 (0x1775431)
/go/src/github.com/jesseduffield/lazygit/main.go:48 (0x1775f0f)
/usr/local/go/src/runtime/proc.go:198 (0x102a7a2)
/usr/local/go/src/runtime/asm_amd64.s:2361 (0x10545e1)
```
**Expected behavior**
lazygit should be loaded

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [MacOS Mojave]
 - Lazygit Version [commit=63e2ccfccf32bd7fff2e721940f8173c6194cce5, build date=2019-03-05T10:57:47Z, build source=binaryRelease, version=0.7.2, os=darwin, arch=amd64]

**Additional context**

**Comment by skanehira** [comment]
@gzzengwei 
Hi!
It's looks like your `.git` file not exist.

https://github.com/jesseduffield/lazygit/blob/63e2ccfccf32bd7fff2e721940f8173c6194cce5/pkg/commands/git.go#L35

Also, there occur another error when use worktree in my environment.

```
2019/04/02 09:59:22 An error occurred! Please create an issue at https://github.com/jesseduffield/lazygit/issues

*os.PathError stat .git/rebase-apply: not a directory
/Users/skanehira/dev/go/src/github.com/skanehira/lazygit/main.go:55 (0x18304a3)
        main: newErr := errors.Wrap(err, 0)
/usr/local/Cellar/go/1.12/libexec/src/runtime/proc.go:200 (0x102eecc)
        main: fn()
/usr/local/Cellar/go/1.12/libexec/src/runtime/asm_amd64.s:1337 (0x10599d1)
        goexit: BYTE    $0x90   // NOP
```

I saw the implementation, it looks like doesn't support worktree so I think lazygit need to support it.

**Comment by jesseduffield** [comment]
Testing locally, looks like this issue is now fixed. Closing
