### ISSUE TITLE
Ask for hard soft or mixed, when resetting to a commit

### ISSUE THREAD

**Issue by MishaFrenkman** [jesseduffield/lazygit#410]
**Is your feature request related to a problem? Please describe.**
Resetting to a commit apparently does mixed reset, although I'd like to to hard or soft

**Describe the solution you'd like**
When resetting, give those three options

**Describe alternatives you've considered**
Workaround for now is doing the default mixed reset and commiting or deleting untracked files

**Comment by jesseduffield** [comment]
This is thankfully simple to implement. I've got a PR up here https://github.com/jesseduffield/lazygit/pull/412

Please let me know if this PR works for you and I can merge it. Also let me know if you need help pulling down that PR.

**Comment by MishaFrenkman** [comment]
Hi Jesse, thanks for the quick reply.
I checked out that branch and built it, but it still behaves the same way, meaning it does a mixed reset without asking first. I tripple checked if if I was on the right branch with the changes in place and it seems to be correct.

Tested in macOS

**Comment by jesseduffield** [comment]
I believe I too came across that bug while I was testing during the week. Could you pull the branch again and see if that issue is now resolved?

**Comment by MishaFrenkman** [comment]
Still the same behaviour

**Comment by jesseduffield** [comment]
when you say without asking first, do you mean that you don't get this popup?

![image](https://user-images.githubusercontent.com/8456633/56073534-2ae62600-5de9-11e9-9c04-d28c48f1ead6.png)

Or you do get the popup but regardless of choice, it does a mixed reset?

**Comment by MishaFrenkman** [comment]
@jesseduffield I don't see this popup. It just runs the mixed reset by default.
Or maybe I'm testing it wrong?
What are the steps to reproduce that?

I did checkout the branch and `go build` it. Then I do a commit and try to reset it afterwards.

**Comment by mjarkk** [comment]
I see the popup when:  
```sh
mkdir -p $GOPATH/src/github.com/jesseduffield/ && cd $GOPATH/src/github.com/jesseduffield/
git clone git clone https://github.com/jesseduffield/lazygit
git checkout 410_reset_to_commit
go install
```

**Comment by jesseduffield** [comment]
This is now in v0.8. If you're still having issues, let me know
