### ISSUE TITLE
[Feature Request] an option to delete both local and remote branch

### ISSUE THREAD

**Issue by SukkaW** [jesseduffield/lazygit#4108]
**Is your feature request related to a problem? Please describe.**

We use squash merge when merging PRs. After a PR is merged, we will clear up branches. However, we need to use <kbd>d</kbd> twice to delete both local and remote branches.

**Describe the solution you'd like**

Add an new option here to delete both local and remote branches in one go.

<img width="793" alt="iTerm2 2024-12-12 16 03 14" src="https://github.com/user-attachments/assets/c37c567b-044b-4750-a936-12b031bd1909" />

Under the hood lazygit will delete the remote branch first then the local branch.

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by mark2185** [comment]
I think it just wasn't released yet, check [this](https://github.com/jesseduffield/lazygit/pull/3916#issuecomment-2435739091) out.

**Comment by SukkaW** [comment]
> I think it just wasn't released yet, check [this](https://github.com/jesseduffield/lazygit/pull/3916#issuecomment-2435739091) out.

Oh I see!

I will build from the default branch then~
