### ISSUE TITLE
Branch form specific commit

### ISSUE THREAD

**Issue by MishaFrenkman** [jesseduffield/lazygit#411]
**Is your feature request related to a problem? Please describe.**
Want to create a branch from a specific commit, rather than branch off of another branch and then reset to the wanted commit

**Describe the solution you'd like**
Inside the commits section, have a key binding which checkouts that commit and creates a new branch

**Comment by skanehira** [comment]
@MishaFrenkman 
I think this is good idea and the feature is useful.

@jesseduffield 
If implement, how about following steps?

1. select a commit
2. press <ctrl-c> and will popup input field
3. input branch name and hit enter

**Comment by jesseduffield** [comment]
May I ask @MishaFrenkman , if you were able to checkout commits themselves, and then branch off the commit from the branches panel, would that be sufficient? I think that if we can do it in two steps like that, it would prevent us from having too much clutter in our keybindings.

**Comment by MishaFrenkman** [comment]
@jesseduffield Yes that sounds alright to me

**Comment by jesseduffield** [comment]
Cool. In that case I'll close this issue in lieu of https://github.com/jesseduffield/lazygit/issues/431
