### ISSUE TITLE
Provide git directory as argument to Lazygit

### ISSUE THREAD

**Issue by MishaFrenkman** [jesseduffield/lazygit#413]
**Is your feature request related to a problem? Please describe.**
Beeing able to run git from any folder by providing the wanted git directory with an argument.

**Describe the solution you'd like**
Something like
```bash
lazygit --git-dir=/path/to/git/dir/
```
(analogue to the official git [api](http://man7.org/linux/man-pages/man1/git.1.html))

Or something more convenient like
```bash
lazygit -p (--path) /path/to/git/dir

**Comment by mjarkk** [comment]
What about just `lazygit /dir/to/some/git/repo`  
Most programs work like that, for example vscode:  
- `code` opens vscode
- `code /path/to/dir` opens vscode in a specific dir/file

**Comment by glvr182** [comment]
I'd also go for what @mjarkk suggests.

**Comment by MishaFrenkman** [comment]
Agree

**Comment by glvr182** [comment]
Ill have a quick check on how to implement this

**Comment by glvr182** [comment]
@MishaFrenkman @mjarkk PR is up following the standard `lazygit /path/to/dir`.

**Comment by jesseduffield** [comment]
thanks @glvr182 for tackling this issue :)

@MishaFrenkman just to get clarification on your use case, there is a feature for opening recent repos, by going to the status panel (the top left one) and hitting 's'. Is your use case not satisfied by that feature?

**Comment by MishaFrenkman** [comment]
@jesseduffield true, but I cannot start lazygit without being inside a non-git folder tho

**Comment by jesseduffield** [comment]
@MishaFrenkman do you think it would be helpful to have lazygit let the user choose from a list of recent repos if you're opening lazygit it outside a git folder?

**Comment by MishaFrenkman** [comment]
@jesseduffield yes, that's a good idea indeed

**Comment by houfeng0923** [comment]
or like git cmd: 
```
git log -- . # show log for current dir
```
so , we can use it like :

```
lazygit .
```

**Comment by mjarkk** [comment]
@houfeng0923 I think what you are trying to say is already said in the second comment,  
But correct me if i'm wrong.

**Comment by dawidd6** [comment]
You can now run `lazygit /path/to/repo/dir`. PR implementing this was just merged to `master`.

**Comment by houfeng0923** [comment]
@mjarkk sorry for later answer.

```
git log -- . # show log for current dir
```
👆is not same as  @mjarkk said . 
the path is not a root path for git repo , but a subpath for repo .

because , in a monorepo , i just want to see  the logs about one package. 

i am not sure whether lazygit support or not . if it can , please give me same message .

thank u .
