### ISSUE TITLE
git revert functionality

### ISSUE THREAD

**Issue by adilJamshad** [jesseduffield/lazygit#4132]
**Is your feature request related to a problem? Please describe.**
I am used to vscode's git revert last commit functionality. While using lazygit, i have to close up everything and go to terminal to execute the git revert command. it is frustrating. Can we add a command and a key mapping for it?

**Describe the solution you'd like**
Upon hitting `R`, a dialog box appears if we want to revert last commit and selecting yes would revert the last commit and selecting no would not change anything.

**Describe alternatives you've considered**
going back to terminal executing the command seems frustrating when you have to close down a lot of windows.

**Additional context**

**Comment by adilJamshad** [comment]
Assign to me, please!

**Comment by stefanhaller** [comment]
Lazygit doesn't have a command to specifically revert the _last_ commit, but it does have one for reverting _any_ commit. So you just need to make sure that the last commit is selected, then hit the `t` key to revert it.

> going back to terminal executing the command seems frustrating when you have to close down a lot of windows.

I'm not sure what you mean by `close down a lot of windows`, but if you want to execute a git shell command that lazygit doesn't support yet, a convenient way to do that is to type `:` to bring up the shell prompt.

**Comment by adilJamshad** [comment]
> Lazygit doesn't have a command to specifically revert the _last_ commit, but it does have one for reverting _any_ commit. So you just need to make sure that the last commit is selected, then hit the `t` key to revert it.
> 
> > going back to terminal executing the command seems frustrating when you have to close down a lot of windows.
> 
> I'm not sure what you mean by `close down a lot of windows`, but if you want to execute a git shell command that lazygit doesn't support yet, a convenient way to do that is to type `:` to bring up the shell prompt.

in the nick of time, it will be frustrating to find the hash for last commit and reverting it. By `close down a lot windows`, i meant i didn't know about shell commands in lazygit 😅
It is something good to have and i want to create a PR for it.

**Comment by stefanhaller** [comment]
> in the nick of time, it will be frustrating to find the hash for last commit and reverting it.

No need for that, `git revert HEAD` works just fine.

> It is something good to have and i want to create a PR for it.

This doesn't make sense. As I said, lazygit does have a command to revert a commit (`t`), you just need to select the last commit first, because it allows you to revert any other commit too.

If you really, really want an extra keybinding for explicitly reverting the last commit, you can easily create one yourself with lazygit's [custom command](https://github.com/jesseduffield/lazygit/blob/master/docs/Custom_Command_Keybindings.md) feature.
