### ISSUE TITLE
Auto-suggest/auto-complete branch names when checkouting by name

### ISSUE THREAD

**Issue by mslazynski** [jesseduffield/lazygit#416]
First, lazygit is great. I'm missing one feature though.
I would like to quickly checkout remote branches and at the moment it requires to put whole branch name into a field. And branches tend to have quite long names, e.g. `feature/PROJECT-101-feature-name`.

It would be great if the text field in "checkout by name" was able to auto-complete/auto-suggest branch name. A basic <TAB> shell-like auto-complete would be enough, but a fuzzy search returning the closest match would be IMHO even better.

Alternatively, it could be enough just to display and traverse through list of the remote branches and checkout them without any text input.

Again, thanks for your hard work!

**Comment by jesseduffield** [comment]
hey @mslazynski sorry for the late reply. I've recently released a feature for viewing remote branches. Does this satisfy your use case? Or do you still think a typeahead feature is a good idea?

**Comment by mslazynski** [comment]
I think it would be cool, but it's not crucial. Viewing remote branches is sufficient :)
