### ISSUE TITLE
Git Flow integration

### ISSUE THREAD

**Issue by jukefr** [jesseduffield/lazygit#42]
It would be nice to have git flow integration :
- https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow

(will update with more information later)

**Comment by jesseduffield** [comment]
I agree! Open to ideas on how best to design that. For a start, I'm thinking something like upon new branch if you're branching off of master/another hotfix branch it defaults to `hotfix` and likewise with develop -> `feature`. But given that some people wouldn't want that, I'm thinking that functionality should be a configurable option that defaults to off. Which reminds me, I gotta get started on making things configurable!

**Comment by jukefr** [comment]
I'd be glad to help out with a PR at some point on this issue when I have the time.
I'm currently learning Go so this could be some nice practice.

I'll start looking into the theory and update this issue with some pointers that might be useful in the meanwhile.

**Comment by hubertba** [comment]
me too ... git flow would be great ...I could also help ..

**Comment by portellaa** [comment]
Awesome idea 🎉 👍 

Perhaps it could read the repository configuration for git and check for gitflow section. For example `git config --get-regexp gitflow`

**Comment by jesseduffield** [comment]
It has been quite a long time since this issue was raised but as part of my 'Road to 1.0' project I've put up a PR for this: https://github.com/jesseduffield/lazygit/pull/579

Currently only starting/finishing branches is supported, and it requires the program 'git-flow' to be installed. Let me know if there's any changes you guys would like to see :)

**Comment by jesseduffield** [comment]
closing :)

**Comment by mcakircali** [comment]
The usage of `--local` while grabbing the git-flow prefixes causes false failure for the local/global mixed configs, see below.

```bash
global  gitflow.prefix.feature feature/
global  gitflow.prefix.release release/
global  gitflow.prefix.hotfix hotfix/
global  gitflow.prefix.support support/
global  gitflow.prefix.versiontag
local   gitflow.branch.master main
local   gitflow.branch.develop develop
```
