### ISSUE TITLE
Easy WIP commit creation

### ISSUE THREAD

**Issue by jesseduffield** [jesseduffield/lazygit#428]
**Is your feature request related to a problem? Please describe.**
All the time I need to quickly change branches, and I want to store my current working directory changes against my branch as a WIP commit so that I can easily reset and keep going next time I check out the branch (the alternative of using the stash is not ideal because it's easy for things to get lost).

But rarely is my code in good enough shape to appease the linters in my pre-commit hooks.

using `git commit --no-verify` lets you bypass pre-commit hooks.

**Describe the solution you'd like**
I want an easy way to create a WIP commit. I think the best solution is to have a hotkey dedicated to it, and when you hit that key, a commit message pops up saying 'WIP' and you can add more to it as you please. Then when you confirm, it does a commit with the --no-verify flag.

**Describe alternatives you've considered**
adding the keybinding to the commit message panel itself rather than the files panel (where most keybindings go) to reduce clutter. This isn't ideal because there's no way to add the functionality for when you use shift+C and commit with your editor.

Skipping the text box and just directly committing with the message of 'WIP'. This is faster, but it means you can't enter in a meaningful message. I think if we express the fact that we're going to be skipping hooks in the title of the commit message panel, it'll be the same number of keypresses as if you had just shown a confirmation panel to confirm that the user wanted to commit their stuff without hooks.

**Additional context**
This would make my life much easier

**Comment by jesseduffield** [comment]
This has been implemented and is on master right now :)

**Comment by JoardarAdi** [comment]
Its 2026, have been using lazygit for the past 1.5years now. Faced the same issue since the repo I work in, has a alot of pre-commit checks and I had to stage my code, commit via the terminal using the `--no-verify` tag and then come back to lazygit to check and push the code. 
I was so naive. All this time, I was just a google search away from my solution ;) 
Thanks @jesseduffield for creating such an awesome Github TUI.
