### ISSUE TITLE
Error opening file in empty table "Files"

### ISSUE THREAD

**Issue by sokolovskiyma** [jesseduffield/lazygit#429]
**Describe the bug**
Error opening file in empty table "Files"

**To Reproduce**
1. Open lazygit in git folder without changes
2. In empty table "Files" click "e" or "o" (edit file, open file)
4. See error - *errors.errorString No changed files

**Expected behavior**
Error message, without closing lazygit 

**Desktop (please complete the following information):**
 - OS: Manjaro
 - Lazygit Version: commit=63e2ccfccf32bd7fff2e721940f8173c6194cce5, build date=2019-04-11T21:04:58Z, build source=binaryRelease, version=0.7.2, os=linux, arch=amd64

**Additional context**
```2019/04/12 00:34:14 An error occurred! Please create an issue at https://github.com/jesseduffield/lazygit/issues

*errors.errorString No changed files
/home/user/.cache/yay/lazygit/src/src/github.com/jesseduffield/lazygit/pkg/gui/gui.go:55 (0x55cd0e6f2874)
/home/user/.cache/yay/lazygit/src/src/github.com/jesseduffield/lazygit/pkg/gui/gui.go:177 (0x55cd0e6f2d4f)
/home/user/.cache/yay/lazygit/src/src/github.com/jesseduffield/lazygit/pkg/app/app.go:114 (0x55cd0e71abb2)
/home/user/.cache/yay/lazygit/src/src/github.com/jesseduffield/lazygit/main.go:48 (0x55cd0e71b5bf)
/usr/lib/go/src/runtime/proc.go:200 (0x55cd0df18044)
	main: fn()
/usr/lib/go/src/runtime/asm_amd64.s:1337 (0x55cd0df43281)
	goexit: BYTE	$0x90	// NOP```

**Comment by skanehira** [comment]
@sokolovskiyma 
It's fixed  https://github.com/jesseduffield/lazygit/commit/d5f617ec92ae4ee6fff9675dafbe7a3bd57bf2bd :)

**Comment by jesseduffield** [comment]
yep this is already fixed. I'll do another release soon after ironing out a couple more bugs :)

**Comment by sokolovskiyma** [comment]
Thank you guys
