### ISSUE TITLE
Installation not working on macOS

### ISSUE THREAD

**Issue by peterschussheim** [jesseduffield/lazygit#43]
Hi,

Trying to get this installed on macOS but still have nothing working.  my `go` environment works as expected but when running `go get github.com/jesseduffield/lazygit`, the command runs and produces nothing in the terminal session.  Any suggestions?

Thanks

**Comment by MSylvia** [comment]
The `go get github.com/jesseduffield/lazygit` command does not return anything if it succeeds I believe. 

Have you tried calling `lazygit` in a git repo after the installation?

**Comment by ksmandersen** [comment]
@MSylvia Nothing is installed when I run the command.

running ``lazygit`` gives ``-bash: lazygit: command not found``. I've confirmed that the libexec of go is part of my $PATH (``/usr/local/opt/go/libexec/bin``). And that directory has a few binaries but nut ``lazygit``

**Comment by peterschussheim** [comment]
@MSylvia `zsh: command not found: lazygit`

**Comment by davecowart** [comment]
I was able to get it working on my machine (MacOS Mojave) by adding `~/go/bin` to my $PATH.

**Comment by peterschussheim** [comment]
Thanks @davecowart, that fixed the issue.  Looks like this was due to incorrect go installation on my local profile.

**Comment by LuanFreitas** [comment]
@peterschussheim here did not give :(

**Comment by LuanFreitas** [comment]
@davecowart, @peterschussheim oooh now yes. I think I was doing something wrong but I got the solution you guys used :)

**Comment by faimin** [comment]
add the below setting to `.zshrc` (my default terminal is `iTerm`)
```ruby
export PATH=$PATH:/usr/local/opt/go/libexec/bin  # go path
export PATH=$PATH:~/go/bin  # for lazygit
```

It work to me .

**Comment by jesseduffield** [comment]
as the readme has a note about $GOPATH, and the app can now be installed on homebrew and via binaries on the release page, I'm closing :)
