### ISSUE TITLE
Gogit failed to parse your gitconfig file due to the presence of unquoted '\' characters

### ISSUE THREAD

**Issue by igorkulman** [jesseduffield/lazygit#430]
**Describe the bug**
Running `lazygit` fails with 

```
2019/04/12 14:50:12 An error occurred! Please create an issue at https://github.com/jesseduffield/lazygit/issues

*errors.errorString Gogit failed to parse your gitconfig file due to the presence of unquoted '\' characters. Removing these should fix the issue.
/private/tmp/lazygit-20190404-25553-rwbozq/lazygit-0.7.2/src/github.com/jesseduffield/lazygit/pkg/commands/git.go:49 (0x15d4981)
/private/tmp/lazygit-20190404-25553-rwbozq/lazygit-0.7.2/src/github.com/jesseduffield/lazygit/pkg/commands/git.go:91 (0x15de11a)
/private/tmp/lazygit-20190404-25553-rwbozq/lazygit-0.7.2/src/github.com/jesseduffield/lazygit/pkg/commands/git.go:97 (0x15d4ae1)
/private/tmp/lazygit-20190404-25553-rwbozq/lazygit-0.7.2/src/github.com/jesseduffield/lazygit/pkg/app/app.go:106 (0x1829e8c)
/private/tmp/lazygit-20190404-25553-rwbozq/lazygit-0.7.2/src/github.com/jesseduffield/lazygit/main.go:48 (0x182a9fd)
/usr/local/Cellar/go/1.12.1/libexec/src/runtime/proc.go:200 (0x102f39c)
/usr/local/Cellar/go/1.12.1/libexec/src/runtime/asm_amd64.s:1337 (0x105a141)
```

**To Reproduce**
1. Install `lazygit` from Hoembrew
2. Run `lazygit` in a git repo directory

**Expected behavior**
The app to start

**Desktop (please complete the following information):**
 - OS: macOS 10.14.4
 - Lazygit Version commit=, build date=, build source=homebrew, version=0.7.2, os=darwin, arch=amd64

**Additional context**

This happens only in 1 git repo. Other git repos work fine, no crash, the app starts like expected.

**Comment by glvr182** [comment]
Can you upload the .gitconfig of that repo (redacted values if you want), it seems to have a config option with a '\' that breaks the config parser.

**Comment by igorkulman** [comment]
I found the problem:

```
[difftool "tower"]
    cmd = \"/Applications/Tower.app/Contents/Resources/p4merge.sh\" \"$LOCAL\" \"$REMOTE\" \"$MERGED\"
```

Deleting this makes the app work

**Comment by jesseduffield** [comment]
Glad to see this got resolved :) I think the error from gogit is sufficiently detailed that we don't need to update our docs, so I'm closing this ticket

**Comment by featdd** [comment]
Hi @jesseduffield 

the problem is'nt resolved, in my example I got the same error while it is a valid config for git

```
[alias]
  set-upstream = !git branch --set-upstream-to=origin/`git symbolic-ref --short HEAD
```

Greetings
Daniel
