### ISSUE TITLE
Checking out commits

### ISSUE THREAD

**Issue by jesseduffield** [jesseduffield/lazygit#431]
**Is your feature request related to a problem? Please describe.**
We want to be able to checkout specific commits

**Describe the solution you'd like**
We need a keybinding for checking out commits. I would have liked to use space to mimic the behaviour in the branches panel but unfortunately we're using space for selecting commits to diff against.

Maybe we should give the space keybinding to this action, and find another keybinding for diffing commits. We can't use 'c' or shift+C because that's for copy+pasting commits. Maybe space is too easy to accidentally press and checking out a commit might be an unexpected action.

I'm open to suggestions :)

**Describe alternatives you've considered**
none

**Additional context**
This is originally based on https://github.com/jesseduffield/lazygit/issues/411

**Comment by skanehira** [comment]
@jesseduffield 
>Maybe we should give the space keybinding to this action, and find another keybinding for diffing commits. We can't use 'c' or shift+C because that's for copy+pasting commits. Maybe space is too easy to accidentally press and checking out a commit might be an unexpected action.

How about use the ctr-c to checkout commit?

**Comment by glvr182** [comment]
I dont think we should use the ctrl+c keybind for anything else but closing. I think many users have gotten used to closing lg like that.

We could make a confirmation panel when the user presses space. However users might get annoyed that they have to press confirm everytime.

**Comment by mjarkk** [comment]
Vim has `y` for copy (yank) and uses `p` for past.  
We could replace that with the current copy and past.  
But because p is already in use, replace the current p when the user presses c with the past command.  
Then you can use the c keybinding again.  

I guess most users of lg also know a bit of vim or even use it actively.

**Comment by jesseduffield** [comment]
Although I do appreciate that lazygit probably does have many vim users, I don't want to overload the 'p' keybinding unless I absolutely have to, especially if doing so requires us to keep track of state. If the user copies a commit, goes to another branch, goes to pull the branch before pasting the commit, it's not going to work as expected.

I think it comes down to this: if we expect people to check out commits more often than they'll be diffing individual commits, we should use the space keybinding for checking out, and we should use a confirmation box. I don't think confirmation boxes are that bad, if you know it's coming you just instinctively hit enter after pressing the original key.

If we think diffing commits will be a more frequent use case, we'll just need to find another keybinding for checking out commits, whatever that may be.

For me personally, checking out commits will be more common than diffing specific commits, so I think space should be for checking out, but I'm not what the situation for the average user would be.

**Comment by jesseduffield** [comment]
I've gone ahead and used 'space' for the keybinding and I've moved the diff mode keybinding to 'i'. Let me know if you think this should be changed :)
