### ISSUE TITLE
default config values aren't loaded properly

### ISSUE THREAD

**Issue by jesseduffield** [jesseduffield/lazygit#434]
**Describe the bug**
viper loads config values from yaml files as having lowercase keys, but we access them with mixed case. This means that if the user hasn't set their own config values manually in config.yml (where the values retain their mixed case) then the defaults will be ignored.

**To Reproduce**
without setting any config.yml file, hitting 'w' in the files panel should bring up the commit message panel with the skipHookPrefix value from the default config i.e. 'WIP'.

**Expected behavior**
defaults should be loaded, for example `git.skipHookPrefix: 'WIP'` (pending https://github.com/jesseduffield/lazygit/pull/433 being merged)

What we actually get is an error message saying it's not configured.

**Desktop (please complete the following information):**
 - OS: OSX
 - Lazygit adc74e

**Additional context**
There is a PR up for this which may be merged soon so the plan is to just bump the version once that PR is merged https://github.com/spf13/viper/pull/635

**Comment by colemars** [comment]
What is the work around for this? How do I manually configure config.yml?

**Comment by matejcik** [comment]
note that the default config file is wrong, per e2419f3b50a3a2a7c7b67201aeb29c00bc05e4c2. isn't that the root cause of this issue?

**Comment by jesseduffield** [comment]
hey @matejcik I think you're right :) I'll close this issue and reopen if issues persist
