### ISSUE TITLE
lazygit 0.7.2 crashes on startup on macOS 10.14.4

### ISSUE THREAD

**Issue by sothawo** [jesseduffield/lazygit#439]
After downloading and extracting lazygit from the releases page (https://github.com/jesseduffield/lazygit/releases) and starting it in a directory that contains a git repository, I get the following error:

~~~
2019/04/15 09:31:02 An error occurred! Please create an issue at https://github.com/jesseduffield/lazygit/issues

*errors.errorString <nil>
/go/src/github.com/jesseduffield/lazygit/pkg/commands/git.go:35 (0x155f785)
/go/src/github.com/jesseduffield/lazygit/pkg/commands/git.go:87 (0x1568e79)
/go/src/github.com/jesseduffield/lazygit/pkg/commands/git.go:97 (0x155fb32)
/go/src/github.com/jesseduffield/lazygit/pkg/app/app.go:106 (0x1775431)
/go/src/github.com/jesseduffield/lazygit/main.go:48 (0x1775f0f)
/usr/local/go/src/runtime/proc.go:198 (0x102a7a2)
	main: return
/usr/local/go/src/runtime/asm_amd64.s:2361 (0x10545e1)
	goexit: ???
~~~

**Desktop (please complete the following information):**
 - OS: macOS 10.14.4
 - Lazygit Version 0.7.2

**Comment by marcizhu** [comment]
I'm using macOS 10.14.4 and Lazygit v0.7.2 too and it seems to work fine for me. Have you tried installing it using Hombrew? Just run `brew install lazygit` on your terminal and it should work without any problems.

Hope this fixes it :)

**Comment by sothawo** [comment]
that's no option for me as I am using MacPorts and not homebrew

**Comment by mjarkk** [comment]
Do you have a custom lazygit config?

**Comment by sothawo** [comment]
rebooting seems to halve solved the problem; thanks
