### ISSUE TITLE
Change UI when the terminal resolution is small

### ISSUE THREAD

**Issue by mjarkk** [jesseduffield/lazygit#440]
**Is your feature request related to a problem? Please describe.**
I'm quite often using lg on it's smallest possible size. When i'm using lg like that there are only 3-1 lines of usable information per block. That makes it hard to use especially when i'm trying to find something where i need to scroll.

**Describe the solution you'd like**
When the blocks on the left get to small like 3-1 line(s) of usable information show only one block at the time.  
Like this: *(left is lazygit, right is something i would like to see)*   
![Screenshot from 2019-04-15 18-15-25](https://user-images.githubusercontent.com/15320763/56152932-56b60700-5fb5-11e9-8125-cb6f3fbebc49.png)  

This way there is still usable information on the screen and it's obvious on witch panel you'r on and where the other panels are.  
Beside that this might allow lg to run on even smaller terminal resolutions.

**Describe alternatives you've considered**
Making the terminal bigger or using git via commands

**Additional context**
None

**Comment by jesseduffield** [comment]
I am 100% behind this idea. We discussed an accordian style layout in another issue but that was to be used at all times. I think switching to this view when we have a very small window size is a good idea. I also think it wouldn't be super hard to implement

**Comment by mjarkk** [comment]
Good to hear that,  
I'm going to take a look if i can implement this.

**Comment by mjarkk** [comment]
Because #441 is merged in this issue can be closed/
