### ISSUE TITLE
[FEATURE REQUEST] Shift + J/K as alternative to PageUp/Down (Scroll)

### ISSUE THREAD

**Issue by ybbond** [jesseduffield/lazygit#442]
**Problem**
Using PageUp and PageDown to scroll the righthand window is not intuitive.
It makes user's hands get out of keyboard's home row, which is inconvenient and (I think) anti pattern in vim-ish keybinding.

**Solution**
Even though you provide workaround at #423 , but I think setting <S-j> (Shift + j) for scroll up and <S-k> (Shift + k) for scroll down will be more intuitive, as it prevent user's hand get out of the keyboard's home row.

**Alternative**
Make both PageUp/Down and <S-k/j> available

**Comment by heygema** [comment]
#400

**Comment by jesseduffield** [comment]
@ybbond I completely agree. We are currently using shift+j/k for moving commits in the commits panel, but I'll remap that to ctrl+j/k (assuming that doesn't clash with anything else; I'm not a vim user myself)

**Comment by jesseduffield** [comment]
PR is up https://github.com/jesseduffield/lazygit/pull/453

**Comment by jesseduffield** [comment]
this was implemented a while back now :)
