### ISSUE TITLE
Strange bug when opening files in neovim

### ISSUE THREAD

**Issue by kristijanhusak** [jesseduffield/lazygit#451]
I have a really really strange bug. I have no idea how to reproduce it, or how to fix it, and that's why i'm writing here for help.
Here's asciinema link that has a recording of what's happening 
https://asciinema.org/a/247547

Basically i open up lazygit, select a file, and when i press e (edit), or even when i try to commit with editor (C), neovim opens in that really strange way where it doesn't respond, and i have to kill the process with Ctrl+C.
When i use vim instead of neovim as an editor, i get this warning before file opens:
```
Vim: Warning: Output is not to a terminal
```
But after the warning the file properly opens. 

Really strange thing around this is that i have 2 other machines with the same OS, terminal, neovim and lazygit, and everything works fine there.

OS: Manjaro Linux i3
Neovim version: v0.4.0-736
Lazygit version: `commit=, build date=, build source=unknown, version=unversioned, os=linux, arch=amd64` (installed via go get).

I tried installing lazygit from aur as a stable, it worked for some time, and then it stopped.

I have no idea how to see the output error or anything that would give me a hint what's happening.

Any help is appreciated, thanks!

**Comment by mjarkk** [comment]
Thank for submitting an issue, though this is a duplicate of: https://github.com/jesseduffield/lazygit/issues/437  

To fix this you need to change your git config to:  
```
[core]
	editor = nvim -es
```

**Comment by kristijanhusak** [comment]
@mjarkk thanks. That unfortunately doesn't work for me. I'll write on the original ticket. Closing this in favor of #437
