### ISSUE TITLE
unable to use emacsclient as editor in gitconfig when using lazygit

### ISSUE THREAD

**Issue by c02y** [jesseduffield/lazygit#462]
**Describe the bug**
When I set `editor = emacsclient -t -a=` in `~/.gitconfig` file, and `e` key in status window of lazygit to open the config file in `editor`, lazygit will crash.

The editor of gitconfig works fine if using `git commit` in a repo

**To Reproduce**
1. set `editor = emacsclient -t -a=` in `~/.gitconfig` file
2. open lazygit
3. `e` in status window of lazygit to open the config file using `editor`
4. lazygit crashes

**Expected behavior**
Open the config file or commit message using `editor` (emacsclient)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: `openSUSE Tumbleweed and RHEL7`
 - Lazygit Version: `0.8`, installed using `conda install -c conda-forge lazygit`, result of `lazygit -v` is `commit=, build date=, build source=unknown, version=unversioned, os=linux, arch=amd64`, but the installation of path is `~/anaconda3/pkgs/lazygit-0.8-0`
 - The last commit id if you built project from sources (run : ```git-rev parse HEAD```)

**Additional context**
The error message when crashes:
~~~
2019/06/10 14:21:25 An error occurred! Please create an issue at https://github.com/jesseduffield/lazygit/issues

*exec.Error exec: "emacsclient -t -a=": executable file not found in $PATH
/home/conda/feedstock_root/build_artifacts/lazygit_1557663207978/gopath/src/github.com/jesseduffield/lazygit/main.go:55 (0xbb8631)
/home/conda/feedstock_root/build_artifacts/lazygit_1557663207978/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p
lacehold_placehold_placehold_placehold_placehold_placehold_pla/go/src/runtime/proc.go:201 (0x42c187)
/home/conda/feedstock_root/build_artifacts/lazygit_1557663207978/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p
lacehold_placehold_placehold_placehold_placehold_placehold_pla/go/src/runtime/asm_amd64.s:1333 (0x457431)
~~~

**Comment by mjarkk** [comment]
Can you try to replace the `-a=` with `-a`
And `editor=emacsclient` in staid of `editor = emacsclient`

**Comment by c02y** [comment]
No, either of them work, I think you tried to treat the argument of editor as one command as try to find it in $PATH, like 

~~~
*exec.Error exec: "emacsclient -t -a=": executable file not found in $PATH
~~~

and if I set it to `emacsclient`, it won't work, I don't know whether you use emacs/emacsclient, emacsclient without options is not the proper way to use emacsclient.

**Comment by Nani-o** [comment]
I'm not sure if this is related, but I can't seems to get sublime text working as an editor as I would like.

In my `gitconfig` file I use :

**Comment by c02y** [comment]
I tried the version(commit=3e36affa69f) installed from AUR, yes, I changed my platform.

lazygit doesn't crush anymore, but 
~~~
editor = emacsclient -t -a=
~~~

`e` in lazygit wouldn't open editor either, it just prints
~~~
+ emacsclient -t -a= git/.gitconfig


Press enter to return to lazygit
~~~

**Comment by jesseduffield** [comment]
@c02y could you see if https://github.com/jesseduffield/lazygit/pull/934 fixes your issue? If you need help testing it let me know

**Comment by c02y** [comment]
It works now, thanks.

I just installed lazygit using "go get github.com/jesseduffield/lazygit", it should include the latest commit, right?

**Comment by jesseduffield** [comment]
yep :)
