### ISSUE TITLE
use `Shift-Tab` to scroll back to the previous window

### ISSUE THREAD

**Issue by c02y** [jesseduffield/lazygit#463]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
`Tab` key will switch to the next window, but have to hit `Tab` multiple times to switch the previous window, so please make of `Shift-Tab` to switch the previous window.

**Describe alternatives you've considered**
And an index for each window and I can use the index to switch to the window is a good idea too.

**Additional context**

**Comment by jesseduffield** [comment]
unfortunately shift+tab isn't possible in a terminal, hence why that keybinding is missing. Though I like the idea about the numbers. I'll put up a separate FR issue for that and close this one
