### ISSUE TITLE
can't commit through vscode or nano

### ISSUE THREAD

**Issue by goldylucks** [jesseduffield/lazygit#464]
**Describe the bug**
can't commit through vscode or nano

**To Reproduce**
1. set vscode as default git core editor: `$ git config --global core.editor "code"`
1. make a change in git repo
1. hit `shift+c`
this opens `repo_root/.git/COMMIT_EDITMSG` in `vscode`, and the output of lazygit is this:
![image](https://user-images.githubusercontent.com/6963212/59423492-e839cd80-8dda-11e9-850f-38319425646c.png)

I have husky running precommit hook, but the relevant part is: **"Aborting commit die to empy commit message"**

**Expected behavior**
hitting `shift+c` should open vscode, and saving the changes should update `lazygit` to make the commit

**Screenshots**
![image](https://user-images.githubusercontent.com/6963212/59423609-27681e80-8ddb-11e9-8e9c-d819270bc0a5.png)

**Desktop (please complete the following information):**
```bash
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic

$ lazygit -v
commit=, build date=2019-05-13, build source=debian, version=0.8, os=linux, arch=amd64
```

**Additional context**
if I set `$ git config --global core.editor "nano"`, then hitting `ctrl+c` opens nano but then I can't close it, hitting `ctrl x` doens't do anything - all other commands don't work as well.

however, setting to vim `$ git config --global core.editor "vim"` works, and I can commit and life is good :sunglasses: 

I do prefer to use vscode for this since that's what I use for everything :)

**Comment by matejcik** [comment]
this doesn't seem to work in raw git either.
you should set your `code.editor` to `"code --wait"`

**Comment by jesseduffield** [comment]
assuming @matejcik is correct, I'm closing this issue. Otherwise let me know :)
