### ISSUE TITLE
View branch diff

### ISSUE THREAD

**Issue by goldylucks** [jesseduffield/lazygit#466]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
if I'm on branch A, I'd like to hover over Branch B and press a key, let's say `Shift+d`, and see the diff between the branches.

Would also be nice to have another hotkey for viewing diff of current selected branch and the base branch, usually master

**Describe alternatives you've considered**
I can go to another tab in terminal and type `$ git diff ...`

**Additional context**
N/A

**Comment by leeyunlong001230** [comment]
does lazygit have compare different branches features

**Comment by jesseduffield** [comment]
Currently the closest feature we have is the ability to diff two commits. I think the next big feature I'll work on is allowing you to diff any two things, which will include branches.

**Comment by jesseduffield** [comment]
This has now been implemented in https://github.com/jesseduffield/lazygit/pull/768, let me know if you'd like to see any changes :)

**Comment by Keshav-writes-code** [comment]
is it possible to diff the same file from 2 branches
