### ISSUE TITLE
Open PR for Bitbucket with windows bug

### ISSUE THREAD

**Issue by samburville** [jesseduffield/lazygit#470]
**Describe the bug**
When using lazygit on windows for a bitbucket repo, if you create a PR then you get the error 't' is not recognized as an internal or external command ...

**To Reproduce**
1. Go to Branches when in a bitbucket repo
2. Press o to open a PR
3. See error

**Expected behavior**
No error should appear when opening a PR

**Screenshots**
![image](https://user-images.githubusercontent.com/7041731/60453219-7a8a0000-9c28-11e9-8984-7362fdaa35d0.png)

**Desktop (please complete the following information):**
 - OS: Windows
 -  lazygit_0.8.1_Windows_x86_64

**Additional context**
This is due to the & symbol in the url
https://bitbucket.org/%s/%s/pull-requests/new?source=%s&t=1
being an escape character in the windows open link command here
openLinkCommand: 'cmd /c "start "" {{link}}"'`

Quick fix could be to change the link to
https://bitbucket.org/%s/%s/pull-requests/new?source=%s

Alternatively the OpenLink function could replace & by ^& if the OS was windows - and would then would have the correct behaviour.

Happy to give either of these a go. If we go with the latter - are there any other characters in windows (or other OS's) that you would be worried about?

**Comment by naoey** [comment]
Sorry to bump such an old issue, but I'm still encountering this problem on Windows with BitBucket PRs. Doesn't really break usage but is still a frequent annoyance. Any possibilities of getting the fix in? 😅

**Comment by jesseduffield** [comment]
Sorry for the late reply: strange that & has meaning even when inside quotes. I wonder if this is a problem across all situations where we want to quote something, in which case escaping with ^& makes sense (we can add a line in `pkg/commands/oscommands/os.go:337`)
