### ISSUE TITLE
Back-port mouse handleClick 

### ISSUE THREAD

**Issue by dudo** [jesseduffield/lazygit#471]
**Describe the solution you'd like**
Lazydocker introduced some snazzy mouse click handlers. I’d like to see the same within Lazygit.

**Comment by dudo** [comment]
We chatted briefly on Reddit. Here’s the suggested path forward, which I’m going to take a crack at

> basically in lazydocker I've added a function called `handleClick` to `pkg/gui/view_helpers.go` and in each of the side panels I've got an e.g. `handleContainersClick` function which passes the selected item to `handleClick`. I would like to use polymorphism here but I couldn't find a way to do it elegantly in golang.

> Then in `keybindings.go` I bind the mouse click to the corresponding handlers (if you search for `handleContainersClick` you'll find it).

> I can't recall how it is in lazygit but we also call `gui.focusPoint` in e.g. `handleContainerSelect` to actually highlight the selected line.

**Comment by jesseduffield** [comment]
This is now done :) I want to add some even more mouse-friendly elements like buttons you can click to bring up certain menus, but for now we've got parity with lazydocker
