### ISSUE TITLE
Windows platform usage issues

### ISSUE THREAD

**Issue by VKingi** [jesseduffield/lazygit#474]
## operating environment
1. system: windows 10  x64
2. lazygit: lazygit_0.8.1_Windows_x86_64

## issues
1. Layout error, please see below
![XJZLF4{{YA%AD59WL(39WVM](https://user-images.githubusercontent.com/16144561/60826195-eb5c8980-a1df-11e9-8341-e1a443aac276.png)

2. When I enter the commit message,The Originally intended to type "This", but it is not intended as intended, please see below
![PW6VSVSSFMM8RPMJJ%A$LVT](https://user-images.githubusercontent.com/16144561/60826719-1693a880-a1e1-11e9-9d8a-6b1f7376461d.png)

**Comment by mjarkk** [comment]
Jup i've seen this earlier,  
May i ask which shell do you use?  

For me only cmd and powershell seems to work fine.

**Comment by VKingi** [comment]
Use the cmd.exe, version: Microsoft Windows [version 10.0.14393]

**Comment by jesseduffield** [comment]
is it possible this is a font issue?

**Comment by zQueal** [comment]
This is a cmd issue. Using the new experimental terminal things work wonderfully.

![mEuCqAQ](https://user-images.githubusercontent.com/239193/63569434-5cb18b00-c547-11e9-9755-31da5ac57386.jpg)

**Comment by mjarkk** [comment]
@zQueal I don't think so because i've used it before on cmd and as far as i know the new windows terminal uses the same api as the normal cmd,  
@VKingi do you have any customization made to your cmd shell like setting another encoding or something else?

**Comment by zQueal** [comment]
It does use the same API, however, when you update to the experimental terminal you download an update from Windows Update, IIRC.

I had tried lazygit a few months ago with an older version of windows and got the same issues. I updated, still the same issues. I downloaded the new terminal, and all of a sudden, after restarting and installing updates, it's working perfectly.

¯\_(ツ)_/¯

**Comment by mjarkk** [comment]
I've just installed a fresh copy of windows and tried it out but works just fine with cmd:  
![Screenshot from 2019-08-23 10-17-45](https://user-images.githubusercontent.com/15320763/63577789-7d9dce80-c58f-11e9-999d-2003764727e6.png)  

But can we conclude this to, just update windows and it will magically work?

**Comment by zQueal** [comment]
> But can we conclude this to, just update windows and it will magically work?

Not a guarantee, but that seems to be what happened. As I said before, yesterday it wasn't working correctly, I updated, and now it is.

**Comment by VKingi** [comment]
@jesseduffield ## Layout error, should not be the font problem:
1. The default font I use
2. Tried to modify the font to solve this problem, but failed
3. No changes have been made to cmd.exe, using the default configuration

## But when submitting a message, the input text problem seems to find a pattern:
![image](https://user-images.githubusercontent.com/16144561/63639833-0bca9f80-c6cb-11e9-90da-97d689592f23.png)
> When I try to type the word 'This', first I type 'T' and it doesn't show 'T', then I type 'h' and it shows 'T', then I type' I 'and it shows 'h'...When I type on the keyboard it displays the previous key value each time

**Comment by VKingi** [comment]
@mjarkk No changes have been made to cmd.exe, using the default configuration.May I ask what is the system version of the new copy you installed? I plan to upgrade the system, because the current system version is a little old
The mirror currently used: windows_10_enterprise_2016_ltsb_x64_dvd_9060409.iso

**Comment by VKingi** [comment]
@zQueal @mjarkk If "cmd.exe" is not normal at first, but a new terminal is installed, which is normal in the new terminal, it is likely to be related to the same width font

**Comment by VKingi** [comment]
@mjarkk @jesseduffield @zQueal  Thanks for your help. Now I can make it display normally!It's probably the font
![image](https://user-images.githubusercontent.com/16144561/63640425-cf02a680-c6d2-11e9-8e71-1ae7544c2c1a.png)

**Comment by zQueal** [comment]
I'm going to guess that the windows update changed the default CMD font. Crazy times.

**Comment by BSDxxxx** [comment]
Fixed by execute `chcp 65001` (default value was `936`).

**Comment by asmwarrior** [comment]
> 
> 
> Fixed by execute `chcp 65001` in cmd (default value was `936`).
> It’s caused by Chinese characters.

This solve some issue in my Windows 7 64 bit Simplified Chinese edition. (I'm using the latest ConEmu)

But it looks like the one Chinese character's width is a bit wider than two English characters. Do you guys see this issue?
I see this in the git log messages.

Here are some suggestions:
1, some FAQ should mention this issue
