### ISSUE TITLE
Commits list doesn't update when I commit from a different window

### ISSUE THREAD

**Issue by devpolish** [jesseduffield/lazygit#475]
**Describe the bug**
I'm trying to create a commit from a different window but my commits list doesn't retrieve the last commit
**Expected behavior**
It's just me or the commits list is not being updated automatically? I was expecting to retrieve the last commit

**Screenshots**
Replication
![Peek 2019-07-08 23-53](https://user-images.githubusercontent.com/19675690/60845329-383e6100-a1dc-11e9-9c31-0dee37d174c4.gif)

It shows the last commit when I put on the branch only
![Screenshot from 2019-07-08 23-54-02](https://user-images.githubusercontent.com/19675690/60845333-3d031500-a1dc-11e9-832e-5cdc5d779314.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu Bionic 18.04 w Tmux support
 - Lazygit Version 0.8.1

**Comment by jesseduffield** [comment]
obtaining the new commits can sometime be expensive, so currently it's not refreshed automatically. You can use shift+R to refresh all the side panels manually.

**Comment by mjarkk** [comment]
I think this issue can be closed due to `shift+R` being the solution for the problem.

**Comment by jesseduffield** [comment]
agreed :)

**Comment by raph-amiard** [comment]
Hi there. I have the same problem but the Shift + R shortcut doesn’t seem to work at all. Any ideas if it was changed to something else ?

**Comment by stefanhaller** [comment]
@raph-amiard The situation with the "Refresh" keybinding is a bit of a mess. Yes, it's still shift-R, except in the Branches panel, where shift-R is bound to "Rename branch" (which takes precedence), and in the Commits panel, where it is bound to "Reword with editor". I'm confused that you say "doesn't work at all", it should always do one of these three things.

But also: this is a very old issue. We now have auto-refresh on focus, so you shouldn't have to refresh manually at all. Unless your terminal doesn't support the necessary focus events, but I'm not aware of any that don't. What platform are you on, and what terminal are you using?

**Comment by rpgdev** [comment]
@stefanhaller  When I click into a branch, I see a list of commits, which does get updated when I go into the branch, but once I'm there, hitting Shift+R doesn't refresh the commits, even though the keybindings help says it does "Refresh." I would expect it to refresh commits once you're inside a branch. Is it still refreshing branches instead?
