### ISSUE TITLE
Automatically Set Upstream

### ISSUE THREAD

**Issue by nahtnam** [jesseduffield/lazygit#48]
Hi,

I created a new branch using lazygit, commited some changes, and pressed "p". It started pulling the code, and then gave the following error:
![image](https://user-images.githubusercontent.com/20051852/43743021-0d3e63b2-9989-11e8-8f95-4dd1c456d8c6.png)

It would be nice to have it ask what branch to set the upstream to and default to the current branch name.

Other than that, love lazygit!

**Comment by jesseduffield** [comment]
yeah that sounds reasonable. The push command currently pushes to origin and sets the upstream (so that's a workaround for now), but I'm now realising that if people have multiple remotes that's going to cause issues, so your suggestion is the best fit.

**Comment by jesseduffield** [comment]
this is now fixed in https://github.com/jesseduffield/lazygit/pull/539 :)
