### ISSUE TITLE
Allow cycling side panels with number keys

### ISSUE THREAD

**Issue by jesseduffield** [jesseduffield/lazygit#480]
**Is your feature request related to a problem? Please describe.**
It would be cool if e.g. pressing 1 focused the status panel, 2 focused the files panel, etc.

**Comment by giorgioprevitera** [comment]
@jesseduffield giving this one a try too

**Comment by victorvianna** [comment]
Is this up for grabs?

**Comment by giorgioprevitera** [comment]
@victor there's already a PR open, see above your comment
