### ISSUE TITLE
disable auto-fetch

### ISSUE THREAD

**Issue by matejcik** [jesseduffield/lazygit#482]
lazygit seems to auto-fetch periodically(?) while running.

I authenticate my ssh connections with Trezor, so I have to physically click to confirm each operation. I don't want to do that, and I don't like the prompt being shown all the time.
I expect that there are other valid reasons to not want auto-fetch, e.g. being on a metered connection? :)

It would be awesome if there was a way to disable the auto-fetch. I haven't found an existing option.
(also i'm not totally sure that auto-fetch is what is causing the ssh prompts. but there definitely is a feature that is doing it)

**Comment by mjarkk** [comment]
This is actually somewhat solved when git asks for credentials in the terminal, then lg automatically stops auto fetching.  
Something better than a option to disable auto fetch all together would be to auto detect these things.

**Comment by matejcik** [comment]
> This is actually somewhat solved when git asks for credentials in the terminal, then lg automatically stops auto fetching.
> Something better than a option to disable auto fetch all together would be to auto detect these things.

That wouldn't resolve my original issue: i don't want a pop-up on my hardware security device just because I typed `lg` in terminal. This implements a mode where lazygit doesn't even *attempt* to fetch, which is the desired (for me) behavior.

**Comment by mjarkk** [comment]
Ow i didn't understand that the popup was on a external device,  
Then your pr makes total sense.
