### ISSUE TITLE
crash on start on some repos

### ISSUE THREAD

**Issue by Adrian-Grimm** [jesseduffield/lazygit#483]
**Describe the bug**
Some Git Repos are working perfect but on two of mine it crashes on start with "illegal character"

**To Reproduce**
1. just start lazygit in special repo

**Expected behavior**
start

**Screenshots**
![image](https://user-images.githubusercontent.com/5657002/61471428-07e88680-a983-11e9-9f9e-554d1b4f51fc.png)

**Desktop (please complete the following information):**
 - OS: Windows10 1903 with WSL.ese running Ubuntu 18.04 LTS in Terminus
 - Lazygit Version: commit=, build date=2019-06-24, build source=debian, version=0.8.1, os=linux, arch=amd64

**Additional context**
----
scanner.ErrorList 1:1: illegal character U+FEFF
/build/lazygit-kdKTvQ/lazygit-0.8.1/obj-x86_64-linux-gnu/src/github.com/jesseduffield/lazygit/main.go:55 (0xb851d5)
/usr/lib/go-1.10/src/runtime/proc.go:198 (0x42cca2)
        main: fn()
/usr/lib/go-1.10/src/runtime/asm_amd64.s:2361 (0x457931)
        goexit: BYTE    $0x90   // NOP
----
*errors.errorString Gogit failed to parse your gitconfig file due to the presence of unquoted '\' characters. Removing these should fix the issue.       
/build/lazygit-kdKTvQ/lazygit-0.8.1/obj-x86_64-linux-gnu/src/github.com/jesseduffield/lazygit/pkg/commands/git.go:49 (0x964243)
/build/lazygit-kdKTvQ/lazygit-0.8.1/obj-x86_64-linux-gnu/src/github.com/jesseduffield/lazygit/pkg/commands/git.go:92 (0x96f692)
/build/lazygit-kdKTvQ/lazygit-0.8.1/obj-x86_64-linux-gnu/src/github.com/jesseduffield/lazygit/pkg/commands/git.go:98 (0x9643bf)
/build/lazygit-kdKTvQ/lazygit-0.8.1/obj-x86_64-linux-gnu/src/github.com/jesseduffield/lazygit/pkg/app/app.go:126 (0xb843ee)
/build/lazygit-kdKTvQ/lazygit-0.8.1/obj-x86_64-linux-gnu/src/github.com/jesseduffield/lazygit/main.go:48 (0xb8518f)
/usr/lib/go-1.10/src/runtime/proc.go:198 (0x42cca2)
        main: fn()
/usr/lib/go-1.10/src/runtime/asm_amd64.s:2361 (0x457931)
        goexit: BYTE    $0x90   // NOP

**Comment by aasifkhan7** [comment]
@Adrian-Grimm Can you please give a reference to the Git Repo. on which this error is encountered?

**Comment by Adrian-Grimm** [comment]
> @Adrian-Grimm Can you please give a reference to the Git Repo. on which this error is encountered?

Sorry those are private and I don't have permissions to give you access..

**Comment by glvr182** [comment]
@Adrian-Grimm It's a know bug see #430 , it could be solved by changing the string to something that does not contain '\' or, the library (go-git) needs to patch this problem

**Comment by Adrian-Grimm** [comment]
But my .git/config contains only things that habe to be there... every other git client ist able to work with that one...

Maybe the same - but different details: 
![image](https://user-images.githubusercontent.com/5657002/61706267-e6ebb100-ad47-11e9-81ff-381af8459b37.png)
![image](https://user-images.githubusercontent.com/5657002/61706440-66798000-ad48-11e9-8e25-ba4d769faf21.png)

**Comment by glvr182** [comment]
Yea normal git and different clients have no problems parsing the config, but for some reason the go-git library has a lot of issues with escape chars

**Comment by Adrian-Grimm** [comment]
But why the hell is that known Bug closed? https://github.com/jesseduffield/lazygit/issues/430

**Comment by step21** [comment]
For me it turned out to be an entry about diff tool/merge helper added by the tower client.

```
[difftool "tower"]
  1   cmd = \"/private/var/folders/sh/xg3rtw1n3315w6s04g29zjhh0000gn/T/AppTranslocation/A76983B5-8031-4187-BE4F-    168CACC0E357/d/Tower.app/Contents/Resources/textwrangler.sh\" \"$LOCAL\" \"$REMOTE\"
```

**Comment by Adrian-Grimm** [comment]
> For me it turned out to be an entry about diff tool/merge helper added by the tower client.
> 

Same here - but in my case it's more important to keep those line working:
```
[mergetool "smerge"]
	cmd = smerge.exe mergetool \"$BASE\" \"$LOCAL\" \"$REMOTE\" -o \"$MERGED\"
```
( I use git over WSL but Sublime-Merge for conflicts )

**Comment by jesseduffield** [comment]
I've just made a PR that bumps go-git, and I believe this should resolve the issue: https://github.com/jesseduffield/lazygit/pull/495

For whatever reason I wasn't able to replicate the issue by using either of those two config examples, but please pull down this branch and see if it resolves the problem for you :)

**Comment by Adrian-Grimm** [comment]
My error was resolved by changing this:
```
[mergetool "smerge"]
	cmd = smerge.exe mergetool \"$BASE\" \"$LOCAL\" \"$REMOTE\" -o \"$MERGED\"
[difftool "vsdiffmerge"]
	cmd = \"C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Professional\\Common7\\IDE\\CommonExtensions\\Microsoft\\TeamFoundation\\Team Explorer\\vsdiffmerge.exe\" \"$LOCAL\" \"$REMOTE\" //t
	keepBackup = false
```
to that:
```
[mergetool "smerge"]
	cmd = "smerge.exe mergetool \"$BASE\" \"$LOCAL\" \"$REMOTE\" -o \"$MERGED\""
[difftool "vsdiffmerge"]
	cmd = "\"C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Professional\\Common7\\IDE\\CommonExtensions\\Microsoft\\TeamFoundation\\Team Explorer\\vsdiffmerge.exe\" \"$LOCAL\" \"$REMOTE\" //t"
	keepBackup = false
```
Adding those **normaly not needed quotes** solved the issue...

**Comment by zsoltika** [comment]
I'm on WSL as well, but my error is unrelated to config (likely):

`╭─ebotzso@HU-00000367 ~/.emacs.d  ‹develop›
╰─➤  lazygit
2019/10/28 16:26:53 An error occurred! Please create an issue at https://github.com/jesseduffield/lazygit/issues

syscall.Errno invalid argument
/build/lazygit-0j5bvA/lazygit-0.8.1/obj-x86_64-linux-gnu/src/github.com/jesseduffield/lazygit/main.go:55 (0xb851c5)
/usr/lib/go-1.10/src/runtime/proc.go:198 (0x42cc92)
        main: fn()
/usr/lib/go-1.10/src/runtime/asm_amd64.s:2361 (0x457921)
        goexit: BYTE    $0x90   // NOP
╭─ebotzso@HU-00000367 ~/.emacs.d  ‹develop›
╰─➤  cat ~/.gitconfig                                                                                                                                            1 ↵
───────┬─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       │ File: /home/ebotzso/.gitconfig
───────┼─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   1   │ [user]
   2   │        name = Zsolt Botykai
   3   │        email = zsolt.botykai@gmail.com
───────┴─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
╭─ebotzso@HU-00000367 ~/.emacs.d  ‹develop›
╰─➤  git status
On branch develop
Your branch is up to date with 'origin/develop'.

nothing to commit, working tree clean
╭─ebotzso@HU-00000367 ~/.emacs.d  ‹develop›
╰─➤`

The git repo is created via `git clone https://github.com/syl20bnr/spacemacs ~/.emacs.d`

I have installed `lazygit` via both the Ubuntu repo version and later tried via 'go get...'

**Comment by mjarkk** [comment]
@zsoltika What is your git version mine is `git version 2.23.0` and trying what you did works perfectly fine for me:  
```sh
git clone https://github.com/syl20bnr/spacemacs ~/.emacs.d
cd ~/.emacs.d
lazygit
# lazygit opens perfectly fine
```
*Nice bat to cat alias btw :), i have that too but with the -p to make more like cat*

**Comment by zsoltika** [comment]
@mjarkk it's the one provided by WSL: 

```
╭─username@HOSTNAME /mnt/c/Users/
╰─➤  git --version
git version 2.17.1
```

**Comment by jesseduffield** [comment]
any chance somebody could test if this PR fixes the issue? https://github.com/jesseduffield/lazygit/pull/541

I wasn't able to reproduce the issue locally but I think that PR will fix it

**Comment by zsoltika** [comment]
Hi @jesseduffield , 
can You give me some hints how to do it? I just `git pull`-d checked out the branch via (` git checkout update-go-git-2`), and checked `git log` and according to this the branch is at `09f268b (HEAD -> update-go-git-2) Update FUNDING.yml` and does not contain this commit? https://github.com/jesseduffield/lazygit/pull/541/commits/4c687da319285054d56e87903034bc50a7b1fa86 
Sorry if I'm missing some point!
Br,
/Zsolt

**Comment by jesseduffield** [comment]
@zsoltika it should be sufficient to just use the latest release to test

**Comment by zsoltika** [comment]
Hi @jesseduffield, upgraded and it works wonderfully. Thanks for the solution!

**Comment by jesseduffield** [comment]
awesome! closing
