### ISSUE TITLE
Showing all remote branches

### ISSUE THREAD

**Issue by haselkern** [jesseduffield/lazygit#492]
Checking out remote branches is a pain. While it is possible, you always have to know the exact name.

A nice solution would be to show all available remote branches in the branches window. This would be done by having a shortcut to switch between local and remote view. You could checkout a remote branch by pressing space as usual in this mode.

As an alternative, you could press a key in the branches window and have all available remote branches show up in the main window on the right. Again, pressing space while in that mode would check out the selected remote branch.

**Comment by jesseduffield** [comment]
I've got a PR up for this now: https://github.com/jesseduffield/lazygit/pull/544

**Comment by jesseduffield** [comment]
This has now been implemented
