### ISSUE TITLE
View staged changes of partially staged file

### ISSUE THREAD

**Issue by matejcik** [jesseduffield/lazygit#496]
**Is your feature request related to a problem? Please describe.**
When staging parts of the file, lazygit only shows unstaged changes.
When staging the whole file, lazygit shows the full diff, i.e., staged changes of that file.

**Describe the solution you'd like**
A toggle to show staged or unstaged changes of a partially staged file, plus support for un-staging changes in the staged changes view. This would let me, e.g., stage the full file with <space> and then un-stage a couple lines that I want to leave out.

**Comment by jesseduffield** [comment]
this has been implemented :) let me know if there's anything you'd like tweaked about the approach I took

**Comment by matejcik** [comment]
Thanks!
I like it, but the split makes the file pane too wide - I usually use lazygit in a relatively small terminal window, i need to maximize it for this to be used efficiently. This is good for a quick overview of staged vs unstaged though. Maybe cycling between staged/unstaged/both would be good, with both being the default you get when scrolling between files?

Also it's still impossible to un-stage changes. Should I file a separate issue for that?

**Comment by matejcik** [comment]
Oh, you can unstage with `d`! i just watched the video .)
that's neat. But really not discoverable? I'd expect <Space> in the staged changes pane to un-stage.

**Comment by matejcik** [comment]
maybe just add "Use `d` to unstage" to the error text that says "cannot stage an already staged change"?

**Comment by matejcik** [comment]
hmmm but the drawback of using `d` for unstage is that I might make a mistake and discard a changed line if i'm not in the correct pane

**Comment by jesseduffield** [comment]
yeah I think it makes sense in that d is for one direction and space is for the other. As for the split view taking up too much space, I've got a PR that splits it vertically  as opposed to horizontally when your terminal window is too small. I'll see if I can make some more progress on that

**Comment by jesseduffield** [comment]
I've merged https://github.com/jesseduffield/lazygit/pull/609 which will preserve the width of the side bar when the total window width is small. Closing :)
