### ISSUE TITLE
Manual resolution of merge conflict

### ISSUE THREAD

**Issue by josh-byster** [jesseduffield/lazygit#497]
**Is your feature request related to a problem? Please describe.**
First, I wanted to say thank you for making such an awesome tool. 
When I want to resolve a merge conflict, I have this issue where oftentimes, I need to modify directly the file that contains a conflict, since using both hunks will cause duplicated information. So in order to do this right now, I have to exit lazygit, open up my text editor, resolve the change manually, then open up lazygit and finish the merge.

**Describe the solution you'd like**

It would be nice to add an option to make a file edit to resolve the merge. That way it could open up the preferred editor to that file to allow us to make the corresponding change to resolve the conflict and then have us land right back in lazygit to stage the change and finish the merge.

**Describe alternatives you've considered**

I'm not quite sure if there's any better way but to either open up an external editor or to allow edits inline, but I'm not sure if that is necessary given that it's a very specific use case to build in full text editing functionality.

**Additional context**
Here's a screenshot of the options I see:
![image](https://user-images.githubusercontent.com/8664074/62817936-a42a2700-bb04-11e9-8a1f-c0d0656bd387.png)

Thanks so much!

**Comment by jesseduffield** [comment]
hey @josh-byster I've put up a PR for this: https://github.com/jesseduffield/lazygit/pull/536

This also adds file watching so that lazygit can instantly know when the conflicts are resolved and prompt you to continue. Do you have time to give that PR a test?

**Comment by jesseduffield** [comment]
closing. Let me know if your original issue hasn't been resolved :)

**Comment by grav** [comment]
For me (on Linux) the file watcher is sometimes quite slow. I can resolve the conflict and then sit around waiting for quite a while, sometimes minutes.

Sometimes I give up, but then I need to manually mark files as resolved `git add ...`, and then I won't get Lazygit's auto-generated merge-commit message.

Would it be possible to initiate the check manually somehow?

**Comment by stefanhaller** [comment]
As far as I can see, there isn't really a file watcher in that sense. There are some rudiments of one in the code, but it seems to be disabled. It was disabled in March 2020, with the comment "TODO: get this going again, and ensure we don't see any crashes from it".

So there's just the normal auto-refresh that happens periodically, every 10s by default. I'm surprised that you have to wait minutes.

In my fork I have a [very hacky commit](https://github.com/stefanhaller/lazygit/commit/34aa9457ebe8c) that auto-refreshes when the lazygit terminal window gets the focus. I actually prefer this to file watching, it works perfectly for me in practice, and it's one of the things that I couldn't live without any more. (I notice this every time I have to work on master for some reason.) I was meaning to contribute it as a PR for a long time now, but didn't get around to it yet. Feel free to cherry-pick the commit if you can build from master, I'd be interested how well it works for you.

**Comment by grav** [comment]
> So there's just the normal auto-refresh that happens periodically, every 10s by default. I'm surprised that you have to wait minutes.

Sorry, just re-tested and I cannot repro the minutes with the current repo. But > 10s is something I've seen. Maybe the number of changed files in the merge also adds to the delay?

> In my fork I have a [very hacky commit](https://github.com/stefanhaller/lazygit/commit/34aa9457ebe8c) that auto-refreshes when the lazygit terminal window gets the focus. I actually prefer this to file watching, it works perfectly for me in practice, and it's one of the things that I couldn't live without any more. (I notice this every time I have to work on master for some reason.) I was meaning to contribute it as a PR for a long time now, but didn't get around to it yet. Feel free to cherry-pick the commit if you can build from master, I'd be interested how well it works for you.

That sounds like a good solution to me as well. Did you create a pull request?

I'm depending on package-manager builds currently, and I don't know if I can easily build everything myself. I'll see if I get to it at some point :+1:

**Comment by stefanhaller** [comment]
> Did you create a pull request?

No, not yet. I was meaning to for weeks now. 😄 

It depends on a PR to an upstream dependency which hasn't been merged yet (https://github.com/gdamore/tcell/pull/599), so we'd have to fork that repo for the time being, which makes it a bit more work.
