### ISSUE TITLE
Hard to see the text of the keymap with a black background

### ISSUE THREAD

**Issue by KsRyY** [jesseduffield/lazygit#499]
The keymap text in the last line of the window is a dark blue, therefore I it very hard to see when I am using a black background - which is default on windows

**Comment by KsRyY** [comment]
It seems that this problem only exists on the CMD.exe and powershell.exe terminal that uses the default Windows Console Host.

**Comment by mjarkk** [comment]
I think you can change this in the lazygit config: (Status > `e`)  
```yml
gui:
  theme:
    optionsTextColor:
      - white
```
For more info see: https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md

**Comment by KsRyY** [comment]
Thank you.
