### ISSUE TITLE
Doing this might clobber your rc file!

### ISSUE THREAD

**Issue by korlaxxalrok** [jesseduffield/lazygit#5]
Hellooo,

Looks like a cool and useful project 👍 😄 

In the readme, you have this:
```
If you want, you can also add an alias for this with echo "alias lg='lazygit' > ~/.zshrc (or whichever rc file you're using)
```
This seems to be missing the closing quote for the string _and_ it_ will clobber the file 😱 

Should it be `echo "alias lg='lazygit'" >> ~/.zshrc`?

**Comment by jesseduffield** [comment]
yes! Thanks for the pickup, just pushed the fix :)
