### ISSUE TITLE
Unlimit get commits (currently max 100)

### ISSUE THREAD

**Issue by skanehira** [jesseduffield/lazygit#500]
**Topic**
Add  `-unlimited` option that does not limit get maximum commits

**Your thoughts**
Sometimes I want to lookup some commit over 100, I think if Add `-unlimited` option that's can be more useful

**Comment by skanehira** [comment]
sample code

```diff
-func (c *GitCommand) GetBranchGraph(branchName string) (string, error) {
-       return c.OSCommand.RunCommandWithOutput(fmt.Sprintf("git log --graph --color --abbrev-commit --decorate --date=relative --pretty=medium -100 %s", branchName))
+func (c *GitCommand) GetBranchGraph(branchName string, unlimited bool) (string, error) {
+       cmd := "git log --graph --color --abbrev-commit --decorate --date=relative --pretty=medium "
+       if unlimited {
+               cmd += "-100 %s"
+       } else {
+               cmd += "%s"
+       }
+
+       return c.OSCommand.RunCommandWithOutput(fmt.Sprintf(cmd, branchName))
 }
```

**Comment by jesseduffield** [comment]
I think a better solution would be to have it load a small amount of commits initially but then if you start scrolling down the list it fetches more. That way we don't need to load a heap at once on application start.

**Comment by bradphelan** [comment]
What about search. If I search for something beyond the 100 then I can't find it.

**Comment by Ryooooooga** [comment]
Press `>` (scroll to bottom) to load all commits.

**Comment by stefanhaller** [comment]
Unfortunately this only works in the local commits panel, but not in the branches panel.

**Comment by Ryooooooga** [comment]
https://github.com/jesseduffield/lazygit/pull/2433
