### ISSUE TITLE
Support commit SignOff

### ISSUE THREAD

**Issue by Silvanoc** [jesseduffield/lazygit#505]
**Is your feature request related to a problem? Please describe.**
I participate in projects where _SignOff_ of commits is a requirement, but I cannot get it done with `lazygit`.

**Describe the solution you'd like**
I'd like to have a configuration flag (ON/OFF) to have signoff of commits.

I'd consider this option only for the _C_ key (commit with editor), not for the _c_ key.

**Describe alternatives you've considered**
To have a configuration option to pass whatever desired options to the different git commands.
Something like `git.commit.options` where I'd have to assign `--signoff` to get that option active.

**Additional context**
My current console GUI is _tig_, where I've configured `~/.tigrc` with `bind status C !git commit --signoff` for this matter.

**Comment by jesseduffield** [comment]
does signing off require you to enter a password or anything or is it just automatic? If it's automatic this should be straightforward to implement, otherwise potentially not.

Also would you want commit signing when doing things like amending old commits or creating merge commits?

**Comment by nwaywood** [comment]
@jesseduffield Signoff does not require you to enter a password. 

I also have to sign off commits in some projects. For me, being able to sign off both a new commit or sign off via amend would be awesome. In command line, an amend signoff is simply `git commit --amend --signoff`

**Comment by Silvanoc** [comment]
Ups, sorry @jesseduffield that I never answered your question. I oversaw it.

I'm unsure if we are on the same page. I'm talking about [`--signoff`](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt--s), not about [`--gpg-sign`](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt--Sltkeyidgt).

**Sign-off** is about [adding some specific text to the commit message](https://cert-manager.io/docs/contributing/sign-off/), whereas **GPG-signing** is about cryptographic signatures.

Signing doesn't require any password, it's just the flag. Of course, you have to configure the username and e-mail that you want to get in the sign-off.

It's a flag of the `commit` subcommand, therefore I'd expect it to work for all the different possible calls of `git commit` (like `--amend`).

I don't use merge workflows, but rebase workflows, therefore I didn't think on `git merge`. But you are right, `git merge` can also [sign-off](https://cert-manager.io/docs/contributing/sign-off/) the merge commits. The same options should be possible here.

**Comment by jesseduffield** [comment]
Sorry it's taken me so long to get back around  to this @Silvanoc. Sounds like a config flag is the way to go, I'm imagining:
```
git:
  commit:
    signOff: true
```

I've attached the good-first-issue label to this issue in case anybody else wants to tackle it. A commit that would be good to mimic is https://github.com/jesseduffield/lazygit/commit/e89bf5d06b8a90b0aca702c0b9ef570504183cd1 (using a bool rather than a string config value)

**Comment by jesseduffield** [comment]
I've closed https://github.com/jesseduffield/lazygit/pull/1031 due to staleness but this is still a good first issue and I'll chuck a hacktoberfest label on it

**Comment by chivalryq** [comment]
Expecting this feature! Some open souce project requires developer to commit with "sign-off" flag, or the CI will block. It's a good way to automatically do this.
