### ISSUE TITLE
it can't run on my mac

### ISSUE THREAD

**Issue by canoejun** [jesseduffield/lazygit#507]
### Environment：
* OS: macOS 10.14.2 Mojave

### Description
when I finished using homebrew to install lazygit , then I try to run it with the command "lazygit" ,it go to error .

### Error
$ lazygit
2019/09/08 10:04:46 An error occurred! Please create an issue at https://github.com/jesseduffield/lazygit/issues

*errors.errorString fatal: not a git repository (or any of the parent directories): .git

/private/tmp/lazygit-20190625-82337-1uw655x/lazygit-0.8.1/src/github.com/jesseduffield/lazygit/pkg/commands/os.go:152 (0x15dd124)
/private/tmp/lazygit-20190625-82337-1uw655x/lazygit-0.8.1/src/github.com/jesseduffield/lazygit/pkg/commands/os.go:64 (0x15dc79d)
/private/tmp/lazygit-20190625-82337-1uw655x/lazygit-0.8.1/src/github.com/jesseduffield/lazygit/pkg/commands/os.go:118 (0x18355ad)
/private/tmp/lazygit-20190625-82337-1uw655x/lazygit-0.8.1/src/github.com/jesseduffield/lazygit/pkg/commands/os.go:118 (0x183558f)
/private/tmp/lazygit-20190625-82337-1uw655x/lazygit-0.8.1/src/github.com/jesseduffield/lazygit/pkg/app/app.go:122 (0x1835190)
/private/tmp/lazygit-20190625-82337-1uw655x/lazygit-0.8.1/src/github.com/jesseduffield/lazygit/main.go:48 (0x18360cd)
/usr/local/Cellar/go/1.12.6/libexec/src/runtime/proc.go:200 (0x102f38c)
/usr/local/Cellar/go/1.12.6/libexec/src/runtime/asm_amd64.s:1337 (0x105a131)

### Error With Screenshots
![image](https://user-images.githubusercontent.com/34930002/64482295-c0170a80-d221-11e9-8ad4-82dedd2c7032.png)

**Comment by marcizhu** [comment]
This happens because you are trying to run lazygit inside a folder that is not a git repository. Try opening it inside a folder containing a repo and this should fix it :)

**Comment by jesseduffield** [comment]
apologies for the less-than-ideal error message. We have a PR in progress to better deal with lazygit not being opened in a git repo

**Comment by jesseduffield** [comment]
@canoejun this is fixed in the latest version:
```
▶ gg
2019/11/12 23:15:24 Error: must be run inside a git repository
```

It may not be in the core homebrew branch in which case you'll need to use the tap via `brew install jesseduffield/lazygit/lazygit`
