### ISSUE TITLE
Default colors don't work well with dark-on-light terminal color scheme

### ISSUE THREAD

**Issue by liyanage** [jesseduffield/lazygit#508]
**Describe the bug**
The default color theme is hard to read with a dark-on-light terminal theme (black text on gray background in my case, see screenshot).

**To Reproduce**
1. On macOS Terminal, import and activate the attached theme configuration
2. Launch lazygit

**Expected behavior**
More readable color choices on this background

**Screenshots**
Screenshots attached

**Desktop (please complete the following information):**
 - OS: [e.g. Windows] macOS
 - Lazygit Version [e.g. v0.1.45] 0.8.1

**Additional context**

<img width="1262" alt="Screen Shot 2019-09-10 at 1 53 33 PM" src="https://user-images.githubusercontent.com/52640/64650499-32c7e780-d3d4-11e9-8709-431fd6a3a2b1.png">

**Comment by liyanage** [comment]
I can't attach the terminal theme file, so below it is in base64. Re-create the file by copying the dump and running:

    pbpaste | base64 -d > ~/Desktop/DarkOnLight.terminal

    PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz4KPCFET0NUWVBFIHBsaXN0IFBVQkxJ
    QyAiLS8vQXBwbGUvL0RURCBQTElTVCAxLjAvL0VOIiAiaHR0cDovL3d3dy5hcHBsZS5jb20vRFREcy9Q
    cm9wZXJ0eUxpc3QtMS4wLmR0ZCI+CjxwbGlzdCB2ZXJzaW9uPSIxLjAiPgo8ZGljdD4KCTxrZXk+QmFj
    a2dyb3VuZENvbG9yPC9rZXk+Cgk8ZGF0YT4KCVluQnNhWE4wTUREVUFRSURCQVVHQndwWUpIWmxjbk5w
    YjI1WkpHRnlZMmhwZG1WeVZDUjBiM0JZSkc5aWFtVmpkSE1TCglBQUdHb0Y4UUQwNVRTMlY1WldSQmNt
    Tm9hWFpsY3RFSUNWUnliMjkwZ0FHakN3d1RWU1J1ZFd4czB3ME9EeEFSRWxkTwoJVTFkb2FYUmxYRTVU
    UTI5c2IzSlRjR0ZqWlZZa1kyeGhjM05FTUM0NEFCQURnQUxTRkJVV0Yxb2tZMnhoYzNOdVlXMWwKCVdD
    UmpiR0Z6YzJWelYwNVRRMjlzYjNLaUZoaFlUbE5QWW1wbFkzUUlFUm9rS1RJM1NVeFJVMWRkWkd4NWdJ
    V0hpWTZaCglvcXF0QUFBQUFBQUFBUUVBQUFBQUFBQUFHUUFBQUFBQUFBQUFBQUFBQUFBQUFMWT0KCTwv
    ZGF0YT4KCTxrZXk+Rm9udDwva2V5PgoJPGRhdGE+CglZbkJzYVhOME1ERFVBUUlEQkFVR0J3cFlKSFps
    Y25OcGIyNVpKR0Z5WTJocGRtVnlWQ1IwYjNCWUpHOWlhbVZqZEhNUwoJQUFHR29GOFFEMDVUUzJWNVpX
    UkJjbU5vYVhabGN0RUlDVlJ5YjI5MGdBR2tDd3dWRmxVa2JuVnNiTlFORGc4UUVSSVQKCUZGWk9VMU5w
    ZW1WWVRsTm1SbXhoWjNOV1RsTk9ZVzFsVmlSamJHRnpjeU5BS0FBQUFBQUFBQkFRZ0FLQUExOFFGMVJv
    CglaVk5oYm5OTmIyNXZRMlF0VnpWU1pXZDFiR0Z5MGhjWUdScGFKR05zWVhOemJtRnRaVmdrWTJ4aGMz
    TmxjMVpPVTBadgoJYm5TaUdSdFlUbE5QWW1wbFkzUUlFUm9rS1RJM1NVeFJVMWhlWjI1M2ZvV09rSktV
    cnJPK3g4N1JBQUFBQUFBQUFRRUEKCUFBQUFBQUFBSEFBQUFBQUFBQUFBQUFBQUFBQUFBTm89Cgk8L2Rh
    dGE+Cgk8a2V5PkZvbnRIZWlnaHRTcGFjaW5nPC9rZXk+Cgk8aW50ZWdlcj4xPC9pbnRlZ2VyPgoJPGtl
    eT5Qcm9maWxlQ3VycmVudFZlcnNpb248L2tleT4KCTxyZWFsPjIuMDY5OTk5OTk5OTk5OTk5ODwvcmVh
    bD4KCTxrZXk+VGVybWluYWxUeXBlPC9rZXk+Cgk8c3RyaW5nPnh0ZXJtLTI1NmNvbG9yPC9zdHJpbmc+
    Cgk8a2V5PmNvbHVtbkNvdW50PC9rZXk+Cgk8aW50ZWdlcj4xMjA8L2ludGVnZXI+Cgk8a2V5PmtleU1h
    cEJvdW5kS2V5czwva2V5PgoJPGRpY3Q+CgkJPGtleT4jRjczOTwva2V5PgoJCTxzdHJpbmc+dG9nZ2xl
    TnVtTG9jazo8L3N0cmluZz4KCQk8a2V5PiRGNzAyPC9rZXk+CgkJPHN0cmluZz4bWzE7MkQ8L3N0cmlu
    Zz4KCQk8a2V5PiRGNzAzPC9rZXk+CgkJPHN0cmluZz4bWzE7MkM8L3N0cmluZz4KCQk8a2V5PiRGNzA4
    PC9rZXk+CgkJPHN0cmluZz4bWzI1fjwvc3RyaW5nPgoJCTxrZXk+JEY3MDk8L2tleT4KCQk8c3RyaW5n
    PhtbMjZ+PC9zdHJpbmc+CgkJPGtleT4kRjcwQTwva2V5PgoJCTxzdHJpbmc+G1syOH48L3N0cmluZz4K
    CQk8a2V5PiRGNzBCPC9rZXk+CgkJPHN0cmluZz4bWzI5fjwvc3RyaW5nPgoJCTxrZXk+JEY3MEM8L2tl
    eT4KCQk8c3RyaW5nPhtbMzF+PC9zdHJpbmc+CgkJPGtleT4kRjcwRDwva2V5PgoJCTxzdHJpbmc+G1sz
    Mn48L3N0cmluZz4KCQk8a2V5PiRGNzBFPC9rZXk+CgkJPHN0cmluZz4bWzMzfjwvc3RyaW5nPgoJCTxr
    ZXk+JEY3MEY8L2tleT4KCQk8c3RyaW5nPhtbMzR+PC9zdHJpbmc+CgkJPGtleT4kRjcyODwva2V5PgoJ
    CTxzdHJpbmc+G1szOzJ+PC9zdHJpbmc+CgkJPGtleT5GNzA0PC9rZXk+CgkJPHN0cmluZz4bT1A8L3N0
    cmluZz4KCQk8a2V5PkY3MDU8L2tleT4KCQk8c3RyaW5nPhtPUTwvc3RyaW5nPgoJCTxrZXk+RjcwNjwv
    a2V5PgoJCTxzdHJpbmc+G09SPC9zdHJpbmc+CgkJPGtleT5GNzA3PC9rZXk+CgkJPHN0cmluZz4bT1M8
    L3N0cmluZz4KCQk8a2V5PkY3MDg8L2tleT4KCQk8c3RyaW5nPhtbMTV+PC9zdHJpbmc+CgkJPGtleT5G
    NzA5PC9rZXk+CgkJPHN0cmluZz4bWzE3fjwvc3RyaW5nPgoJCTxrZXk+RjcwQTwva2V5PgoJCTxzdHJp
    bmc+G1sxOH48L3N0cmluZz4KCQk8a2V5PkY3MEI8L2tleT4KCQk8c3RyaW5nPhtbMTl+PC9zdHJpbmc+
    CgkJPGtleT5GNzBDPC9rZXk+CgkJPHN0cmluZz4bWzIwfjwvc3RyaW5nPgoJCTxrZXk+RjcwRDwva2V5
    PgoJCTxzdHJpbmc+G1syMX48L3N0cmluZz4KCQk8a2V5PkY3MEU8L2tleT4KCQk8c3RyaW5nPhtbMjN+
    PC9zdHJpbmc+CgkJPGtleT5GNzBGPC9rZXk+CgkJPHN0cmluZz4bWzI0fjwvc3RyaW5nPgoJCTxrZXk+
    RjcxMDwva2V5PgoJCTxzdHJpbmc+G1syNX48L3N0cmluZz4KCQk8a2V5PkY3MTE8L2tleT4KCQk8c3Ry
    aW5nPhtbMjZ+PC9zdHJpbmc+CgkJPGtleT5GNzEyPC9rZXk+CgkJPHN0cmluZz4bWzI4fjwvc3RyaW5n
    PgoJCTxrZXk+RjcxMzwva2V5PgoJCTxzdHJpbmc+G1syOX48L3N0cmluZz4KCQk8a2V5PkY3MTQ8L2tl
    eT4KCQk8c3RyaW5nPhtbMzF+PC9zdHJpbmc+CgkJPGtleT5GNzE1PC9rZXk+CgkJPHN0cmluZz4bWzMy
    fjwvc3RyaW5nPgoJCTxrZXk+RjcxNjwva2V5PgoJCTxzdHJpbmc+G1szM348L3N0cmluZz4KCQk8a2V5
    PkY3MTc8L2tleT4KCQk8c3RyaW5nPhtbMzR+PC9zdHJpbmc+CgkJPGtleT5GNzI4PC9rZXk+CgkJPHN0
    cmluZz4bWzN+PC9zdHJpbmc+CgkJPGtleT5eRjcwMDwva2V5PgoJCTxzdHJpbmc+G1s1QTwvc3RyaW5n
    PgoJCTxrZXk+XkY3MDI8L2tleT4KCQk8c3RyaW5nPhtbMTs1RDwvc3RyaW5nPgoJCTxrZXk+XkY3MDM8
    L2tleT4KCQk8c3RyaW5nPhtbMTs1Qzwvc3RyaW5nPgoJCTxrZXk+XkY3Mjg8L2tleT4KCQk8c3RyaW5n
    PhtbMzs1fjwvc3RyaW5nPgoJCTxrZXk+fkY3MDI8L2tleT4KCQk8c3RyaW5nPhtiPC9zdHJpbmc+CgkJ
    PGtleT5+RjcwMzwva2V5PgoJCTxzdHJpbmc+G2Y8L3N0cmluZz4KCQk8a2V5Pn5GNzA0PC9rZXk+CgkJ
    PHN0cmluZz4bWzE3fjwvc3RyaW5nPgoJCTxrZXk+fkY3MDU8L2tleT4KCQk8c3RyaW5nPhtbMTh+PC9z
    dHJpbmc+CgkJPGtleT5+RjcwNjwva2V5PgoJCTxzdHJpbmc+G1sxOX48L3N0cmluZz4KCQk8a2V5Pn5G
    NzA3PC9rZXk+CgkJPHN0cmluZz4bWzIwfjwvc3RyaW5nPgoJCTxrZXk+fkY3MDg8L2tleT4KCQk8c3Ry
    aW5nPhtbMjF+PC9zdHJpbmc+CgkJPGtleT5+RjcwOTwva2V5PgoJCTxzdHJpbmc+G1syM348L3N0cmlu
    Zz4KCQk8a2V5Pn5GNzBBPC9rZXk+CgkJPHN0cmluZz4bWzI0fjwvc3RyaW5nPgoJCTxrZXk+fkY3MEI8
    L2tleT4KCQk8c3RyaW5nPhtbMjV+PC9zdHJpbmc+CgkJPGtleT5+RjcwQzwva2V5PgoJCTxzdHJpbmc+
    G1syNn48L3N0cmluZz4KCQk8a2V5Pn5GNzBEPC9rZXk+CgkJPHN0cmluZz4bWzI4fjwvc3RyaW5nPgoJ
    CTxrZXk+fkY3MEU8L2tleT4KCQk8c3RyaW5nPhtbMjl+PC9zdHJpbmc+CgkJPGtleT5+RjcwRjwva2V5
    PgoJCTxzdHJpbmc+G1szMX48L3N0cmluZz4KCQk8a2V5Pn5GNzEwPC9rZXk+CgkJPHN0cmluZz4bWzMy
    fjwvc3RyaW5nPgoJCTxrZXk+fkY3MTE8L2tleT4KCQk8c3RyaW5nPhtbMzN+PC9zdHJpbmc+CgkJPGtl
    eT5+RjcxMjwva2V5PgoJCTxzdHJpbmc+G1szNH48L3N0cmluZz4KCQk8a2V5Pn5eRjcyODwva2V5PgoJ
    CTxzdHJpbmc+GxtbMzs1fjwvc3RyaW5nPgoJPC9kaWN0PgoJPGtleT5uYW1lPC9rZXk+Cgk8c3RyaW5n
    Pk1hcmM8L3N0cmluZz4KCTxrZXk+cm93Q291bnQ8L2tleT4KCTxpbnRlZ2VyPjI1PC9pbnRlZ2VyPgoJ
    PGtleT50eXBlPC9rZXk+Cgk8c3RyaW5nPldpbmRvdyBTZXR0aW5nczwvc3RyaW5nPgoJPGtleT53YXJu
    T25TaGVsbENsb3NlQWN0aW9uPC9rZXk+Cgk8aW50ZWdlcj4wPC9pbnRlZ2VyPgo8L2RpY3Q+CjwvcGxp
    c3Q+Cg==

**Comment by mjarkk** [comment]
Jup this is indeed by default an issue especially on your almost grey background color.  
Because this is quite hard to fix automatically we made a config file we you can change the colors yourself.  
- Go to the status panel and press `e`
- For documentation about the config file see [/docs/Config.md](https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md)

**Comment by aint** [comment]
The default color theme is hard to read even with the default macOS terminal theme. Please see screenshot below
![image](https://user-images.githubusercontent.com/3179252/65833695-952d4d00-e2db-11e9-8246-83de360a2416.png)

**Comment by ddobrinskiy** [comment]
@mjarkk thanks for the advice - worked like a charm.

However I can't figure out how to change the **text color**. what is the config option for that?
![](https://i.imgur.com/sYKETRK.png)

Here is my config:

```yaml
gui:
  # stuff relating to the UI
  scrollHeight: 2 # how many lines you scroll by
  scrollPastBottom: true # enable scrolling past the bottom
  theme:
    activeBorderColor:
      - magenta
      - bold
    inactiveBorderColor:
      - white
    optionsTextColor:
      - blue
  commitLength:
    show: true
git:
  merging:
    # only applicable to unix users
    manualCommit: false
  skipHookPrefix: WIP
  autoFetch: true
update:
  method: prompt # can be: prompt | background | never
  days: 14 # how often an update is checked for
reporting: 'on' # one of: 'on' | 'off' | 'undetermined'
confirmOnQuit: false
os:
  opencommand: code -r {{filename}}
```

**Comment by mjarkk** [comment]
That's wired i thought we have solved this issue somewhat in: https://github.com/jesseduffield/lazygit/issues/17 but it doesn't look like.   Also just tested this myself in the terminal and i have the same result as you in all light themes.  

It might be handy if we add a lightMode to the config that sets the right colors for light terminals.

**Comment by mjarkk** [comment]
I've opened a [pr to fix the issue (#519)](https://github.com/jesseduffield/lazygit/pull/519):  

![Screenshot_2019-10-18_09-45-32](https://user-images.githubusercontent.com/15320763/67076753-17e45200-f18e-11e9-98fe-e6976d450fde.png)

**Comment by mjarkk** [comment]
This issue is now solved once the next release is out.  
In the config file add these config settings and lazygit will work much better on a light theme.
```yaml
  gui:
    theme:
      lightTheme: true
      activeBorderColor:
        - black
        - bold
      inactiveBorderColor:
        - black
```
If you used ‘go get’ to install lazygit you can get the latest changes already using:  
‘go get -u github.com/jesseduffield/lazygit’  
If you use go 1.13 and up add the ‘@master’ to the url

**Comment by liyanage** [comment]
Thanks for the fix! Stupid question, but where does the config file go, and what should its filename be? Is that documented somewhere? I checked but couldn't find it. I looked at the source and it seems it would be something like "lazygit.yml", but where?

**Comment by liyanage** [comment]
Never mind, found it by running opensnoop. It seems to be at ~/Library/Application Support/jesseduffield/lazygit/config.yml.

**Comment by liyanage** [comment]
Verified, looks great now, thanks again!

**Comment by mjarkk** [comment]
The config file can also be opened by going to the `status` panel and pressing `e` to edit the config file.

**Comment by aint** [comment]
@mjarkk It'd be great to have this config file somewhere in `~/.config`. What do you think about it?
Anyway, thanks a lot for your work.

**Comment by mjarkk** [comment]
ya this issue is bought up earlier..  
We could do that but currently we are doing it the way it was intended to be used mixed with some inspiration from how the gopath works.  
So on mac that is `~/Library/Application Support/jesseduffield/lazygit/config.yml.` and on linux `~/.config/jesseduffield/lazygit`.  

I don't think on mac the `~/Library/Application Support/` will ever be changed but the `jesseduffield/` might be removed some day because if you run `ls` in the os config dir it doesn't show lazygit what makes it harder to find and there are only a small amount of applications that use this kind of path to there config.

**Comment by liyanage** [comment]
Good to know about the "e" key in the status panel. That is not very discoverable. I searched for something like "edit config file" in the menu but couldn't find anything. Now that I know it's "e" I went back to look there again and the label is "edit file". There's no way I would guess that means edit the config file.

**Comment by johannesgunnar** [comment]
Note that the config method is not 100% optimal for systems where dark and light theme gets changed automatically depending on the time of the day (or for users that tend to switch between dark and light theme a lot). Best would be to have this automatic, although I do understand that might be tricky to implement.

**Comment by mihar** [comment]
> Note that the config method is not 100% optimal for systems where dark and light theme gets changed automatically depending on the time of the day (or for users that tend to switch between dark and light theme a lot). Best would be to have this automatic, although I do understand that might be tricky to implement.

This is not that hard, there's a command you can run on OS X and branch whether the system theme is dark or light. I wonder if we could make the config setting dynamic somehow, or able to be set by command line args when running `lazygit`.

**Comment by TamasBarta** [comment]
Is there a way to use only the 16 colours my terminal has? That way, it's enough to set my terminal up to follow system settings. I don't know if it would mean usability issues with Lazygit, but I'd definitely prefer that (with every single terminal app).
