### ISSUE TITLE
Failed to fire hook: Rollbar returned 429 Too Many Requests

### ISSUE THREAD

**Issue by thislooksfun** [jesseduffield/lazygit#509]
**Describe the bug**
Sometimes running `lazygit` will, after a second, print the error `Failed to fire hook: Rollbar returned 429 Too Many Requests`, thus shifting the whole lazygit UI up by two lines.

**To Reproduce**
1. Run `lazygit`
2. Wait about a second

**Expected behavior**
It should not print `Failed to fire hook: Rollbar returned 429 Too Many Requests`, or if it does, it should do so in a way that does not interfere with the UI.

**Screenshots**
<img width="984" alt="Screen Shot 2019-09-12 at 12 04 32 PM" src="https://user-images.githubusercontent.com/5367333/64805058-cc6ad280-d555-11e9-8b7a-881fec8bec15.png">
[Video example](https://i.imgur.com/dQaIV9H.mp4)

**Desktop (please complete the following information):**
 - OS: macOS 10.14.6 (18G87)
 - Lazygit Version `commit=c6da4c8a47a45a96beb2de4fbe5b98cfb87446b4, build date=2018-10-23T22:33:44Z, build source=binaryRelease, version=0.5, os=darwin, arch=amd64`

**Additional context**
This happened to me a month or two ago as well, but it eventually went away on it's own before I had a chance to report it.

**Comment by jesseduffield** [comment]
@thislooksfun if you update to the latest version, you should be fine :) I initially did not realise that I might hit rollbar with too many requests, so in version 0.8 (I think) I made it fail gracefully without messing with the UI

**Comment by thislooksfun** [comment]
Ah. Didn't realize I was outdated. Should have checked that first. Thanks!
