### ISSUE TITLE
bash not found on Windows

### ISSUE THREAD

**Issue by ImVexed** [jesseduffield/lazygit#51]
I'm getting: `exec: "bash": executable file not found in %PATH%`

[Screenshot](https://i.ipih.io/QmeVJjvhXiSgB4frCZrAcdCdK3Zo1vQmxcyXQygAUbrGsb)

Fresh pull from master ~ 5 minutes ago

**Comment by ImVexed** [comment]
For anyone else having this issue: https://github.com/jesseduffield/lazygit/pull/53

**Comment by jesseduffield** [comment]
@ImVexed how does that PR go in addressing your issue?

**Comment by ImVexed** [comment]
From powershell I'm getting `exec: "sh": executable file not found in %PATH%` 
[Screenshot](https://i.ipih.io/QmSAU74pfmr3ndAgZnDZ3RmR83CyniEc2qnFwGMZDdRTYn)
From Mingw64 it just stalls and never does anything, this was the same functionality with Master
[Screenshot](https://i.ipih.io/QmYQMoWKhqcV75SUpmbESVPBqcgVsw1qnP7pD4wcHtzNQ8)

**Comment by ImVexed** [comment]
See https://github.com/jesseduffield/lazygit/pull/54

**Comment by ImVexed** [comment]
https://github.com/jesseduffield/lazygit/pull/53 indeed fixes it
