### ISSUE TITLE
Reset individual changed lines

### ISSUE THREAD

**Issue by matthiasroos** [jesseduffield/lazygit#511]
**Is your feature request related to a problem? Please describe.**
Often, I try some changes in my code. In case the new idea does not work out, I want to go back to the original code in a speedy manner and reset only these specific lines. At the same time, I have many more changes I want to leave unchanged. Therefore, I miss an option to reset individual lines. For me it would be a really nice feature and ease my way of working, as I didn't have to close lazygit and go back to git-cola or the command line anymore :) 

**Describe the solution you'd like**
As I really like the option to stage individual lines by pressing 'space' while scrolling through my files, I just want to press some other key to reset the currently selected line.

**Comment by jesseduffield** [comment]
This is something I've wanted for a while as well, I've just never put the time in to make it happen. It seems to me like it should be simple enough: if you want to reset a single line, just grab the associated hunk, apply it in reverse, then apply it again with the selected line missing. I'll see if I can look into this this week.

**Comment by jesseduffield** [comment]
PR is now up: https://github.com/jesseduffield/lazygit/pull/524

**Comment by jesseduffield** [comment]
this has been implemented in the latest release :)
