### ISSUE TITLE
lazygit can not works with editor

### ISSUE THREAD

**Issue by SukkaW** [jesseduffield/lazygit#514]
**Describe the bug**

**To Reproduce**

1. Switch to `Commits` panel
2. <kbd>R</kbd> to reword commit using editor
3.

```
+ git rebase --interactive --autostash [hash]

hint: Waiting for your editor to close the file... 2019/09/29 22:34:25 chdir /path/to/.git/rebase-merge/git-rebase-todo: not a directory
error: There was a problem with the editor '/usr/bin/lazygit'.

Press enter to return to lazygit
```

4. I have tried both `git config --global core.editor $(which vim)` and `git config --global core.editor $(which nano)`, neither of them works.

---

1. Switch to `Commits` panel
2. <kbd>f</kbd> to fixup the commit. <kbd>Enter</kbd> to confirm.
3.

```
┌─Error───────────────────────────────────────────────────────────────────────────────────┐
│2019/09/29 22:38:49 chdir /path/to/.git/rebase-merge/git-rebase-todo: not a directory    │
│error: There was a problem with the editor '/usr/bin/lazygit'.                           │
└─────────────────────────────────────────────────────────────────────────────────────────┘
```

4. I have tried both `git config --global core.editor $(which vim)` and `git config --global core.editor $(which nano)`, neither of them works.

**Expected behavior**

I use nano as default editor for git. lazygit used to works well with nano.

**Desktop (please complete the following information):**
 - OS: Debian 10 WSL1 on Windows 10
 - Lazygit Version: latest daily build from Ubuntu PPA

```bash
$ lazygit -v
commit=95ae806, build date=2019-09-25, build source=debian, version=, os=linux, arch=amd64
```

**Comment by SukkaW** [comment]
https://github.com/jesseduffield/lazygit/commit/95ae806e09380e6c1602a91af6d34e8ffd770274

Maybe the issue is related with this commit.

**Comment by dawidd6** [comment]
Please try setting `EDITOR` environment variable and then run `lazygit`.

Like: `EDITOR=vim lazygit`.

**Comment by SukkaW** [comment]
@dawidd6 I have already set `EDITOR` in my `.zshrc`.

And if I open lazygit using `EDITOR=vim lazygit`, the issue still there.

**Comment by dawidd6** [comment]
@glvr182 seems like more stuff needs tweaking after this https://github.com/jesseduffield/lazygit/pull/414

**Comment by glvr182** [comment]
Looks like flaggy removes the env / totally ignores the flag. I'll do some investigating.

**Comment by glvr182** [comment]
Identified possible bug:
```
if repoPath != "." {
	if err := os.Chdir(repoPath); err != nil {
		log.Fatal(err.Error())
	}
}
``
Seems to have side effects

**Comment by glvr182** [comment]
When calling a subprocess the program calls lazygit back with the following signature:   
`lazygit /home/glenn/Develop/src/github.com/jesseduffield/lazygit/.git/rebase-merge/git-rebase-todo`
This is likely the source of the crash

**Comment by glvr182** [comment]
Can you check if #516 works @SukkaW

**Comment by SukkaW** [comment]
@glvr182 

```bash
$ git clone https://github.com/glvr182/lazygit
$ cd lazygit
$ git checkout hotfix/path-not-positional
$ go build
$ ./lazygit
```

It works.

**Comment by glvr182** [comment]
great! PR is up so when that is accepted / merged it should be pushed to the ppa aswell @SukkaW

**Comment by glvr182** [comment]
Just to be sure, have you tried overwrtiting the editor aswell?

**Comment by SukkaW** [comment]
@glvr182 Yeah. I have changed git `core.editor` config. and it works as expected.

`$EDITOR` in shell enviroment is not effective for lazygit. But I believe it is expected behavior: lazygit should use value from `git config core.editor`.

**Comment by dawidd6** [comment]
lazygit should fallback to `EDITOR` if `git.editor` is not set

**Comment by baptisteArno** [comment]
Impossible to have a different editor than vim I tried setting it up with both EDITOR env var or core.editor git config.

I tried with code, codei, zed editors, nothing works.

Any idea how I can debug that?

**Comment by mark2185** [comment]
> Any idea how I can debug that?

You can fill out the bug report template when you file a new issue on `github` and post your `config.yml` there.

**Comment by rofrol** [comment]
https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md#configuring-file-editing

```
os:
  editPreset: "helix (hx)"
```
