### ISSUE TITLE
Feature request: easy way to merge remote branch

### ISSUE THREAD

**Issue by jonnermut** [jesseduffield/lazygit#52]
Congrats on lazygit, its great.

One of the slowest workflows with git is that to merge develop/master etc into your current branch  you have to stash/commit current, checkout master, pull, switch back to current, then merge. This is awfully slow in SourceTree.

There are two quicker ways on the command line, discussed in the stackoverflow answers here:

https://stackoverflow.com/a/34344502/2102158
`git pull origin master` - this effectively merges the origin version of develop into your branch in one command

https://stackoverflow.com/a/45697574/2102158
```
git fetch origin master:master
git merge master
```
Which updates the local master to the remote without a checkout, then merges it

In lazygit, I reckon the best would be to have a one key command to update a non checkout branch to latest - eg run `git fetch origin master:master` on it

Thanks for consideration.

**Comment by jesseduffield** [comment]
Yeah that sounds like a good idea. Maybe a keybinding like 'f' to fetch from remote on the selected branch. Only caveat I can think of is: if you're trying to merge develop into master, what happens if your local develop has diverged from your remote develop? Is this a command that has error cases?

**Comment by jonnermut** [comment]
Yeah I guess it will error if you have non pushed commits, but thats fine assuming you have the capability to show an error. Or even ignore. 
Do you show behind/infront numbers for the branches (I can't see any on my local working copy at the moment?)
Eg in sourcetree:
![image](https://user-images.githubusercontent.com/1787624/43751361-ebc99a96-9a3f-11e8-9c13-3dc297a98390.png)

**Comment by jonnermut** [comment]
Oh I just noticed it for the current branch, top left

**Comment by jesseduffield** [comment]
this has actually been completed a while ago: you can hit 'f' on branch to fast-forward it to match its upstream ,and then 'r' to rebase onto it or 'M' to merge with it

**Comment by dwainm** [comment]
Here's a great explanation: https://github.com/jesseduffield/lazygit/discussions/1903#discussioncomment-5199677
