### ISSUE TITLE
A lazier way to stash lots of files

### ISSUE THREAD

**Issue by mjarkk** [jesseduffield/lazygit#523]
**Is your feature request related to a problem? Please describe.**
Usually when i'm working on a big change for a large project i write a shitload of code and when i'm dune i commit the changes i think are most important.  

If there are only 20 files changed this can be easily dune using lazygit but when i have more than 100 or more files changed and only 80 of then need to be committed this gets a bit frustrating because the current files panel is quite small and it's frustrating to press 100 times down to get to un-stash 1 file  

**Describe the solution you'd like**
A shortcuts for chaining the files panel to a bigger and easier file selector that also includes folders.  
I imagine it could look something like this:  
```
src/
  controllers/
    users/
      users.go
      edit.go
  helpers/
    database/
      db.go  
```
A user can navigate using the arrow keys, for example when the user is inside controllers and presses down helpers will be selected. If the user presses right from controllers users will be selected. If pressed space on a folder the full folder will be stashed.  
*just supper lazy :)*  

**Describe alternatives you've considered**
I normally just use the terminal if there are so many files to stash but this is also frustrating if there are many nested folders

**Comment by jesseduffield** [comment]
I think this makes complete sense. I'm not sure how easy it would be to implement but I think it would be a good addition to the app

**Comment by mjarkk** [comment]
I'm going to try make this tomorrow and see how far i get

**Comment by jesseduffield** [comment]
I've got a PR up for this now @mjarkk  https://github.com/jesseduffield/lazygit/pull/1197

**Comment by mjarkk** [comment]
Thanks!! it looks amazing!!

**Comment by mjarkk** [comment]
I see #1197 is merged, so this issue can be closed  
I'm going to love this feature!!!

**Comment by jesseduffield** [comment]
@mjarkk I've been testing it out quite a bit, it's pretty rad! Let me know if you come across situations where it could be more polished
