### ISSUE TITLE
Ambiguous short SHA1

### ISSUE THREAD

**Issue by condemil** [jesseduffield/lazygit#525]
**Describe the bug**
It is possible that short (7-char) SHA1 is duplicated between several commits in big repositories
As a solution it is possible to use full SHA1 for git commands

**To Reproduce**
Not sure it is reproducible. I got this error when I was doing rebase and short sha1 of my commit was similar to the one in a tree

**Expected behavior**
No crash during rebase

**Screenshots**

```
*errors.errorString error: short SHA1 d29a7d9 is ambiguous
hint: The candidates are:
hint:   d29a7d972441 commit 2019-10-31 - ********************
hint:   d29a7d910c31 tree
fatal: ambiguous argument 'd29a7d9': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```

**Desktop (please complete the following information):**
 - OS: macOS 10.14.6
 - Lazygit Version: v0.8.2
 - The last commit id if you built project from sources: N/A

**Comment by jesseduffield** [comment]
looks like we might need to revisit how we handle commit SHAs, currently we're not getting the long form SHAs
