### ISSUE TITLE
Set selected branch to current commit

### ISSUE THREAD

**Issue by matejcik** [jesseduffield/lazygit#545]
**Describe the solution you'd like**
An inverse of "reset to commit" - an option for "Point to current commit" on a selected branch. Equivalent of `git branch -f branch-name`

**Describe alternatives you've considered**
The workaround is either to do this (relatively rare) operation from command line, or to delete the branch and create a new one where I want. Not sure if this even should be in lazygit, but it might be nice.

**Comment by jesseduffield** [comment]
Currently you can hard-reset the currently checked out branch onto the selected branch. Does that satisfy the use case?

**Comment by matejcik** [comment]
I'm honestly not sure what I was trying to accomplish anymore. If it's supposed to be what `git branch -f` does, then yes, what you suggest would help. I suspect it was a little more complicated than that, but I'll need to write down more details the next time I try to do it.

**Comment by jesseduffield** [comment]
haha, all good. I'm personally not familiar with what `git branch -f` does

**Comment by matejcik** [comment]
I don't think it's helpful to keep this issue open. Closing, I'll file a better one if/when I figure out what this was supposed to be.

**Comment by matejcik** [comment]
...and reopen. Here's a usecase:

I am on detached HEAD, but I've made a commit. If I checkout anything, the commit is lost.
I need an action on _selected branch_ that resets that branch (not a currently checked-out one) to _current branch_.

Your suggestion works, but it is a kludge: create a new branch off current commit, checkout the branch I want to reset (my commit is disappearing from view), then reset _current_ branch to _selected_, and finally delete the temporary branch.

In several situations I've seen, checking out different branch in order to move it to the previously checked-out is backwards.
The operation I'm actually doing here is `git checkout -B` = create branch off HEAD if it doesn't exist, reset to HEAD if exists, and then set as current
But I could live with `git branch -f` = same thing except does not set as current.

**Comment by jesseduffield** [comment]
Come to think of it this actually sounds straightforward to implement: we'd just be adding a new keybinding on the branches panel to reset the branch to the current head. I think we'd  do `git branch -f` rather than `git checkout  -B`  because it's only a  couple more keypresses to check out the branch after. I've chucked the good-first-issue  label on this cos I reckon anybody could do it :)

**Comment by jesseduffield** [comment]
@matejcik lazygit now supports custom commands! I reckon this should be simple enough to implement based on the docs [here](https://github.com/jesseduffield/lazygit/blob/master/docs/Custom_Command_Keybindings.md). If it ends up being generally useful we can merge it into the lazygit codebase.

**Comment by jesseduffield** [comment]
closing
