### ISSUE TITLE
Add capital V for staging lines multiple lines

### ISSUE THREAD

**Issue by jrwrigh** [jesseduffield/lazygit#546]
**Is your feature request related to a problem? Please describe.**
I use vim a lot and when I want to highlight multiple lines, I use `VISUAL LINE` mode, which is activated via <kbd>Shift</kbd><kbd>v</kbd>. Having both <kbd>Shift</kbd><kbd>v</kbd> and <kbd>v</kbd>. 

**Describe the solution you'd like**
Add <kbd>Shift</kbd><kbd>v</kbd> as a way of doing the multi-line select

**Describe alternatives you've considered**
Sucking it up and just accepting that I'll type <kbd>Shift</kbd><kbd>v</kbd> a couple of times before I realize it's supposed to be lowercase. lol

**Additional context**
Looks like all that needs to be changed is adding another entry to `keybindings.go`: https://github.com/jesseduffield/lazygit/blob/bad06bb634917d0f4f21c4f54823cf5f2cc3c392/pkg/gui/keybindings.go#L899-L906

I'd do the change myself, but don't have a way of verifying that the change worked (ie. no Go experience. It'd probably take me several times longer to build the project than to make the change)

**Comment by jesseduffield** [comment]
sounds like a quick one indeed! I'm chucking a good-first-issue label on this in case anybody wants to have a crack

**Comment by dawidd6** [comment]
So you want to basically make an alias keybinding or completely change it?

**Comment by jesseduffield** [comment]
I think an alias is fine here, I don't think we'll need to use 'v' for anything else
