### ISSUE TITLE
"fatal: unknown refname: format strip=2"

### ISSUE THREAD

**Issue by jrwrigh** [jesseduffield/lazygit#548]
**Describe the bug**
Open lazygit on a repository, and this error comes up
![image](https://user-images.githubusercontent.com/20801821/69498304-ca04ed00-0ea3-11ea-8781-d2a2991d2626.png)

From [eamodio/vscode-gitlens#737](https://github.com/eamodio/vscode-gitlens/issues/737), it looks like it's a git version issue. This computer in particular is running 2.1.4, where as `strip` wasn't included until 2.7.2. Unfortunately I'm not admin on the computer, so I can't just update the git version.

**Desktop (please complete the following information):**
 - OS: Debian (old version)
 - Lazygit Version 0.11.2

**Comment by jrwrigh** [comment]
I can confirm that going to a newer git version (2.12.2 in my case) resolves the issue.

**Comment by jesseduffield** [comment]
Makes sense, I've switched to use `git branch -r` under the hood which works with 2.12 https://github.com/jesseduffield/lazygit/pull/550

**Comment by jesseduffield** [comment]
should be fixed in v0.11.3, let me know otherwise :)
