### ISSUE TITLE
Windows: The term 'lazygit' is not recognized as the name of a cmdlet, function, script file, or operable program.

### ISSUE THREAD

**Issue by vovikdrg** [jesseduffield/lazygit#55]
I just pulled latest version but can't run it

```
PS C:\Users\vovik> go get github.com/jesseduffield/lazygit
PS C:\Users\vovik> lazygit
lazygit : The term 'lazygit' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ lazygit
+ ~~~~~~~
    + CategoryInfo          : ObjectNotFound: (lazygit:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

**Comment by jesseduffield** [comment]
sounds like a path issue to me. Could you ensure that %HOME%\go\bin is in your %PATH%?

**Comment by vovikdrg** [comment]
But I am able to run `go get` and I can see that `C:\Go\bin` is added to my path...

**Comment by vovikdrg** [comment]
Maybe i need to restart my laptop.

**Comment by jesseduffield** [comment]
Alternatively you can just close and re-open the terminal to refresh the path. Try that first :)

**Comment by jesseduffield** [comment]
ah, C:\Go\bin is different to %HOME%\go\bin. The former is for the official go binaries, and the latter is for the binaries of go applications you've downloaded (e.g. lazygit). So you want to have something like C:\Users\Me\go\bin in your path

**Comment by vovikdrg** [comment]
It works :) There is definitely needs for installer for such lazy people like me :)

**Comment by vovikdrg** [comment]
Now there is other problem but I've seen opened issue for 

> exec: "bash": executable file not found

**Comment by jesseduffield** [comment]
I've just been doing some windows fixes so try `git pull`ing from the lazygit repo and see if it resolves the issue :)

**Comment by vovikdrg** [comment]
You can close it. Now after update it works 💯

**Comment by jesseduffield** [comment]
woo! Good to hear 😄
