### ISSUE TITLE
"Unknown option: rebase-merges" (old git compatibility issue)

### ISSUE THREAD

**Issue by jrwrigh** [jesseduffield/lazygit#553]
**Describe the bug**
Attempt to cherry-pick a commit from one branch to another. Error comes up saying `Unknown option: rebase-merges`. This is because the version of git I'm working with (2.12.0) does not have the `--rebase-merges` option available. This option wasn't implemented until [git 2.18.0](https://git-scm.com/docs/git-rebase/2.18.0#git-rebase---rebase-mergesrebase-cousinsno-rebase-cousins)

**Screenshots**
![image](https://user-images.githubusercontent.com/20801821/69680688-da19f980-1068-11ea-91d8-41bbef78aae5.png)

**Desktop (please complete the following information):**
 - OS: Debian 8
 - Lazygit Version v0.11.2

~I'll try it with 0.11.3 when I get a chance, but I figured you probably just changed that it to fix #548.~ Can confirm it also has the same error for 0.11.3.

**Comment by dawidd6** [comment]
Maybe we can use `--preserve-merges` for older git. Seems like these options are similar.

**Comment by mjarkk** [comment]
Maybe it's worth looking into issue as a lot of linux distros do not ship with such a new git version.  

If someone have this problem on a ubuntu based system this can be solved by using the git-core ppa witch allows you to update to the latest git version.  
```sh
sudo add-apt-repository ppa:git-core/ppa
sudo apt-get update
sudo apt-get install git
```

**Comment by fsmiamoto** [comment]
@mjarkk Agree on that, just had this issue on Ubuntu.
Thanks for the pointing out the solution

**Comment by jesseduffield** [comment]
I found out today that the git CLI will, by default, drop merge commits when rebasing i.e.:
>--rebase-merges[=(rebase-cousins|no-rebase-cousins)]
>By default, a rebase will simply drop merge commits from the todo list, and put the rebased commits into a single, linear branch. With --rebase-merges, the rebase will instead try to preserve the branching structure within the commits that are to be rebased, by recreating the merge commits. Any resolved merge conflicts or manual amendments in these merge commits will have to be resolved/re-applied manually.

So I'm going to remove this flag altogether and also drop merge commits. I'll also show the 'drop' action in red to make it obvious that's what's happening

**Comment by jesseduffield** [comment]
see https://github.com/jesseduffield/lazygit/pull/979

**Comment by jesseduffield** [comment]
I've just merged that PR, so I'll close this issue. Let me know if you have any other issues. Also let me know if you think the behaviour of dropping merge conflicts by default makes sense (it's what git CLI does by default)
