### ISSUE TITLE
os.PathError open /dev/null: too many open files

### ISSUE THREAD

**Issue by wendigo** [jesseduffield/lazygit#555]
**Describe the bug**
lazygit returns error while running

**To Reproduce**

```
lazygit                                                                                                                                    
2019/12/03 13:14:54 An error occurred! Please create an issue at https://github.com/jesseduffield/lazygit/issues

*os.PathError open /dev/null: too many open files
/go/src/github.com/jesseduffield/lazygit/pkg/commands/errors.go:13 (0x162347e)
/go/src/github.com/jesseduffield/lazygit/pkg/commands/os.go:160 (0x1623484)
/go/src/github.com/jesseduffield/lazygit/pkg/commands/os.go:74 (0x1622ae2)
/go/src/github.com/jesseduffield/lazygit/pkg/commands/git.go:471 (0x161ba99)
/go/src/github.com/jesseduffield/lazygit/pkg/gui/status_panel.go:139 (0x16726c3)
/go/src/github.com/jesseduffield/lazygit/pkg/gui/files_panel.go:364 (0x1642331)
/go/src/github.com/jesseduffield/lazygit/pkg/gui/files_panel.go:105 (0x1640023)
/go/src/github.com/jesseduffield/lazygit/pkg/gui/view_helpers.go:20 (0x167405a)
/go/src/github.com/jesseduffield/lazygit/pkg/gui/gui.go:669 (0x1649fc1)
/go/src/github.com/jesseduffield/lazygit/pkg/gui/gui.go:659 (0x1649ea2)
/go/src/github.com/jesseduffield/lazygit/pkg/gui/gui.go:599 (0x164825b)
/go/pkg/mod/github.com/jesseduffield/gocui@v0.3.1-0.20191116013947-b13bda319532/gui.go:388 (0x11cc620)
/go/pkg/mod/github.com/jesseduffield/gocui@v0.3.1-0.20191116013947-b13bda319532/gui.go:505 (0x11cd12c)
/go/pkg/mod/github.com/jesseduffield/gocui@v0.3.1-0.20191116013947-b13bda319532/gui.go:413 (0x11cc874)
/go/src/github.com/jesseduffield/lazygit/pkg/gui/gui.go:821 (0x164be57)
/go/src/github.com/jesseduffield/lazygit/pkg/gui/gui.go:830 (0x164c1df)
/go/src/github.com/jesseduffield/lazygit/pkg/app/app.go:166 (0x168cd6b)
/go/src/github.com/jesseduffield/lazygit/main.go:73 (0x168dec8)
/usr/local/go/src/runtime/proc.go:203 (0x102ee9e)
/usr/local/go/src/runtime/asm_amd64.s:1357 (0x105a711)
```

**Expected behavior**
Should not fail while running

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: MacOS 10.15.2 Beta (19C39d)
 - Lazygit Version: commit=339e1b5dcfcdb39d99a5a01f5befb3b90cb1fb32, build date=2019-11-26T10:41:23Z, build source=binaryRelease, version=0.11.3, os=darwin, arch=amd64

**Additional context**
n/a

**Comment by glvr182** [comment]
Can you check if following this guide solves your problem?
https://becomethesolution.com/blogs/mac/increase-open-file-descriptor-limits-fix-too-many-open-files-errors-mac-os-x-10-14

**Comment by wendigo** [comment]
It doesn't

**Comment by jesseduffield** [comment]
does this command on the command line yield the same error? `git status --untracked-files=all`

**Comment by jesseduffield** [comment]
I just got this too actually, but wasn't able to replicate it by retracing my steps. Not sure what's going on

**Comment by jesseduffield** [comment]
looks like it could be due to the stuff in `pkg/gui/file_watching.go`

**Comment by jesseduffield** [comment]
yeah so looks like fsnotify opens each file that it watches according to https://github.com/fsnotify/fsnotify/issues/129

and on MacOS we've only got a max of 256 files allowed per process (you can check the limit with `ulimit -n` and you can set to higher with `ulimit -n 2048`)

Seems like we should find a way of knowing what the limit is and staying under it.

**Comment by mjarkk** [comment]
I think the method for solving that is to retry :),  
I've had this problem meany times with web servers written in go where you need to upper the ulimit otherwise it will tell you constantly this `too many open files; retrying in 1s`.  
From what i can see this is builtin into go's own web library because every web framework seems to have this issue so i don't think there is a good way to solve it aside from just retrying.

**Comment by keksnicoh** [comment]
I came into a situation in which more >600 files where modified. In this state, lazygit crashed with the same error.

**Comment by jesseduffield** [comment]
I'm gonna merge this PR which I believe will fix the issue. I'm arbitrarily setting the cap of watched files to 200 (under the 256 that macs default to) and when we exceed that limit we start unwatching older files.

If there's a demand for it I can make this configurable but for now it's hard-coded

**Comment by jesseduffield** [comment]
closing this issue now but if you still get the issue or want to see a change in the solution please let me know
