### ISSUE TITLE
Commit message character count broken

### ISSUE THREAD

**Issue by thislooksfun** [jesseduffield/lazygit#556]
**Describe the bug**
The character count for commit messages is broken.

**To Reproduce**
1. Stage any file(s)
2. Start the commit
3. Type anything
4. The count remains 0

**Expected behavior**
The count should either reflect the number of characters typed, or should count down from some upper limit, but should not remain 0.

**Screenshots**
<img width="636" alt="Screen Shot 2019-12-04 at 3 23 14 PM" src="https://user-images.githubusercontent.com/5367333/70182716-01e11100-16aa-11ea-80cf-17ed03a57b91.png">

**Desktop (please complete the following information):**
 - OS: macOS 10.14.6 (18G103)
 - Lazygit Version v0.11.3

**Additional context**
This has been a bug for quite a few versions now. I don't remember for sure when it was first introduced, but I think it has been in since at least v0.8.x.

**Comment by jesseduffield** [comment]
good pickup, fixed in https://github.com/jesseduffield/lazygit/pull/558
