### ISSUE TITLE
Not available in path

### ISSUE THREAD

**Issue by grav** [jesseduffield/lazygit#56]
I needed `~/go/bin` added to my `$PATH` in order to use lazygit.

Since I know absolutely nothing about Golang, it took me quite some time to figure out where the heck Go stuffs its binaries installed via `go get`. Maybe you could make a brief note about this in the README?

**Comment by jesseduffield** [comment]
In the installation section, it states `Please note: On MacOS you may have to add ~/go/bin to your $PATH variable`

Nonetheless there is a milestone to get some binaries out there so that installation is easier :)

**Comment by grav** [comment]
Ah, ok. you're right. You can add Linux Antergos to that note, though :-)
