### ISSUE TITLE
Doc about configurations options

### ISSUE THREAD

**Issue by BlueInt32** [jesseduffield/lazygit#565]
**Is your feature request related to a problem? Please describe.**
I am trying to change some of default lazygit behavior, e.g. have a --oneline graph in commits view. I could not find any info about configuring lazygit. The only glimpse of this I had was at [11:20 in the 15 lazygit features youtube video](https://youtu.be/CPLdltN7wgE?t=680).

**Describe the solution you'd like**
I would expect a section describing all the config.yml options in the readme file. 

**Describe alternatives you've considered**
Maybe there could be a defaultconfig.yml with all the defaults, so we could pick and modify some to include in our actual config.yml file. 

**Additional context**
I find it strange that any other issue seems to be related to this documentation, so maybe I am missing something. If it's the case I'm sorry !

**Comment by mjarkk** [comment]
There is actually some documentation about the file located in [docs/Config.md](https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md)  
But where you are searching for doesn't seem to be in there.

**Comment by rayluo** [comment]
Did not realize that the config file is literally at `~/.config/jesseduffield/lazygit/config.yml`. We love your name, bro, but why not just `~/.lazygit/config.yml`? :-)

**Comment by jesseduffield** [comment]
@rayluo the XDG spec (I'm pretty sure that's the relevant spec) requires a vendor name and a package name, so I just picked my name because that's the same structure as the github repo itself

**Comment by OliverJAsh** [comment]
> e.g. have a --oneline graph in commits view

See https://github.com/jesseduffield/lazygit/pull/887#issuecomment-656619560

**Comment by jesseduffield** [comment]
I'll close this  issue in favour of https://github.com/jesseduffield/lazygit/issues/963
