### ISSUE TITLE
Keyboard bindings to cycle through tabs in a pane

### ISSUE THREAD

**Issue by nivv** [jesseduffield/lazygit#566]
**Is your feature request related to a problem? Please describe.**
I want to be able to cycle through `Local branches`, `Remotes` and `Tags` with the keyboard. I'm sure there is a keyboard shortcut but I can't seem to find it. 

**Describe the solution you'd like**
Expose keyboard shortcuts to cycle through the tabs in a section

**Additional context**
![image](https://user-images.githubusercontent.com/4033930/70894232-e69ccc80-1fec-11ea-9fc8-0d0c23dfe6ac.png)

**Comment by mjarkk** [comment]
You can use `[` and `]` to switch between the tabs

**Comment by nivv** [comment]
@mjarkk thanks! 👍
