### ISSUE TITLE
The "reset selection" function in the "Unstaged Changes" section should be removed

### ISSUE THREAD

**Issue by jrwrigh** [jesseduffield/lazygit#568]
... until there's either undo functionality in the system or something else

**Topic**
The "reset selection" (<kbd>d</kbd>) key on the "Unstaged Changes" panel. 

**Your thoughts**
This is a very dangerous key. It'll delete things without any warning and without anyway of getting the contents back. It should either be 
A) removed entirely (maybe not the best)
B) be change to modifier + <kbd>d</kbd>
C) have a dialog alerting the user that they are permanently deleting information.

**Comment by theniceboy** [comment]
I thought of that too, but having a confirm dialog decreases the speed. You will be able to remap keys with PR #557 though if it gets merged.

**Comment by jrwrigh** [comment]
Eh, I'd say the decrease in speed for the dialog box is worth it.

Perspective: I use force push for my dotfiles a ton (I do a lot of moving commits and rebasing). There's a dialog that comes up whenever a standard push isn't possible, and then asks whether you want to do a force push. It does technically decrease speed, but I've done it enough times to to know that I just need to hit <kbd>enter</kbd> to force it.

On the flip side, I'd say modifier + <kbd>d</kbd> would slow me down more than a dialog box that I'm used to rushing past.

**Comment by jesseduffield** [comment]
this is implemented in https://github.com/jesseduffield/lazygit/pull/595
