### ISSUE TITLE
Release builds not getting on PPA

### ISSUE THREAD

**Issue by mastern2k3** [jesseduffield/lazygit#571]
**Topic**
The latest version currently on the [Launchpad Release PPA](https://launchpad.net/~lazygit-team/+archive/ubuntu/release) is `0.8.1`

**Your thoughts**
I know it's possible to install the newer version with `go get` but still having the PPA is nice for my deployments

Could you direct me to the process in charge of pushing the new versions?

**Comment by dawidd6** [comment]
The repo used for building the packages on Launchpad is available here: https://github.com/dawidd6/lazygit-debian.

I already updated it to latest version, but I'm experiencing some issues with Launchpad (can't trigger the build). Will keep trying.

If you want to help maintain this package, please say so and I can give you push access to the repository.

**Comment by dawidd6** [comment]
Latest release is available in the archive.
