### ISSUE TITLE
big files

### ISSUE THREAD

**Issue by nagy135** [jesseduffield/lazygit#585]
Hello, I love this program but I have this issue (i guess I aint the only one). In project I work on I leave giant xmls in the root of project (milions of lines of data to import) ...when I scroll through files in lazygit and i get to it, it blocks execution and waits for it to load ...files like this load few minutes and there is nothing I can do, just kill lazygit. Would it be possible to detect this? I would suggest to show just few hundred lines for user to visually see that it is xml and ignore the rest (I dont think people would browse big files like this anyway).

**Comment by jesseduffield** [comment]
This is a fortunate coincidence because today I'll be starting on this exact problem!. See the (Road to 1.0 Project)[https://github.com/jesseduffield/lazygit/projects/6]

**Comment by nagy135** [comment]
glad to hear that! I might even contribute

**Comment by jesseduffield** [comment]
good to hear! If you want to help on anything and need any pointers let me know :)

**Comment by nagy135** [comment]
been working a lot with rust lately and as a result my go skills are getting ....rusty :D leaving this one open, please comment here when you solve it so that everyone can see :)
