### ISSUE TITLE
Allow commiting directly from the line-wise staging view

### ISSUE THREAD

**Issue by jpfender** [jesseduffield/lazygit#586]
This is a very very minor quibble, but I keep finding myself stumped when I'm staging changes line-wise and want to commit --- intuitively, I would just want to press `c` from the staging view, but instead I have to go back to the file menu with `Esc` and *then* press `c`. A bit unnecessary in my opinion, especially since `c` is not mapped to anything else in the staging view.

So if at all possible, it would be great to have `c` do the same thing in the staging view as it does in the file view.

Not that this will stop me from using lg, thanks very much for this!

**Comment by jesseduffield** [comment]
This makes perfect sense. I'm gonna chuck a 'good first issue' label on this because it should be fairly easy to implement and I'll see if there are any takers
