### ISSUE TITLE
Cut release, so distributions can ship

### ISSUE THREAD

**Issue by dvzrv** [jesseduffield/lazygit#59]
For this software to be shipped somewhere on Linux distributions, you'll need to cut a release! :)

**Comment by jesseduffield** [comment]
How to do binary releases is a topic I am very unfamiliar with. Could I get some pointers (or perhaps @dawidd6 could chip in)

**Comment by dawidd6** [comment]
I think that @dvzrv by release meant just a git tag.

**Comment by dvzrv** [comment]
@jesseduffield Yes, I meant a git tag with that. Downstream distributions will have their own way of packaging your software anyways (maybe even using their very own way of building/packaging go applications).

**Comment by jesseduffield** [comment]
I've hooked up travis CI to deploy tagged releases. Does this fix the original issue? Or is there more work to do?

**Comment by jesseduffield** [comment]
Closing cos it looks like we're good
