### ISSUE TITLE
cmd.ProcessState.ExitCode undefined (type *os.ProcessState has no field or method ExitCode)

### ISSUE THREAD

**Issue by kekbait** [jesseduffield/lazygit#596]
**Describe the bug**

While trying to install lazygit with the 
```
go get github.com.jesseduffield/lazygit
```
an error message appears :
```
/kekbait/scripts/go/src/github.com/jesseduffield/lazygit/pkg/tasks/tasks.go:62:23: cmd.ProcessState.ExitCode undefined (type *os.ProcessState has no field or method ExitCode)
```

**To Reproduce**
1. Run ```go get github.com.jesseduffield/lazygit```
2. See error

**Expected behavior**
Lazygit should install itself

**Desktop (please complete the following information):**
 - OS: Alpine Linux
 - Lazygit Version : latest ?

I've used this method for more than a year now to install or update lazygit, and the message appeared today.
Thanks a lot for your awesome work btw !

**Comment by jesseduffield** [comment]
Thanks for your kind words :) Having a look at [this issue](https://github.com/golang/go/issues/26539)  it seems like it could be related to your go version. Perhaps updating to go 1.12 will resolve your issue?

**Comment by kekbait** [comment]
Indeed, updated to 1.13.4 and it's now working flawlessly.
Thanks a lot!
