### ISSUE TITLE
Pull/push doesn't find remote specified in [branch] config

### ISSUE THREAD

**Issue by peppy** [jesseduffield/lazygit#598]
**Describe the bug**
I use [hub](https://github.com/github/hub) to checkout PRs for review. By issuing `hub checkout <url>` it will checkout from a fork without adding the fork as a remote. This can be handy when managing local mess when checking contributions from tens/hundreds of different contributors.

lazygit doesn't seem to recognise these [branch] configuration entries, prompting for a remote URL when hitting `p` to pull. It would be great if it could understand they are there!

**To Reproduce**
1. Use `hub` to checkout a pull request, or alternative manually add a branch configuration to `.git/confg` for a project:

```
[branch "dropdown_keyboard_support"]
        remote = https://github.com/UselessToucan/osu-framework.git
        merge = refs/heads/dropdown_keyboard_support
```
2. Checkout branch
3. Try to pull within lazygit
4. See prompt for remote URL, even though it should already be known

**Expected behavior**
Expect the pull to run without prompting. This is also applicable to push operations, for what it's worth.

**Screenshots**

![image](https://user-images.githubusercontent.com/191335/72493326-eef25c80-3863-11ea-849b-75db9155cd12.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Lazygit Version `commit=d647a96ed55e134f1464878be8d0be3a464d996f, build date=2020-01-10T04:55:07Z, build source=binaryRelease, version=0.13, os=darwin, arch=amd64`

**Comment by jesseduffield** [comment]
I will have a look in to this first chance I get!

**Comment by jesseduffield** [comment]
@peppy I've chucked up a PR https://github.com/jesseduffield/lazygit/pull/605 for this issue. Would you be able to give it a test?
