### ISSUE TITLE
Branch "last commit" letters not showing

### ISSUE THREAD

**Issue by nivv** [jesseduffield/lazygit#599]
**Describe the bug**
Only numbers are shown for the branches, I guess they are suppose to represent when the last commit was created? Only numbers tells me nothing, since it can be weeks, seconds or hours.

**To Reproduce**
1. Install latest version `brew install jesseduffield/lazygit/lazygit`
2. Open up a repo
3. Check the numbers

**Expected behavior**
I would very much like to have explanations for what the numbers represent

**Screenshots**
![image](https://user-images.githubusercontent.com/4033930/72502681-2ea44e80-383a-11ea-8331-03e55eb2d377.png)

**Desktop (please complete the following information):**
 - OS:  macOS Catalina 10.15.1
 - Lazygit Version [e.g. v0.13]
- iTerm2 Build 3.3.7

**Additional context**
Now when I'm typing this I have small bell ringing that this issue is known on macOS?

Also, thanks for putting time into this! :)

**Comment by jesseduffield** [comment]
I wonder if perhaps there is some duration that lazygit doesn't recognise. Do you get this issue across all your repos?

**Comment by nivv** [comment]
@jesseduffield not that I know of, I cloned this repo and created a new branch. 

![image](https://user-images.githubusercontent.com/4033930/73251130-a8342900-41b8-11ea-9c40-91045b6fe9e7.png)

**Comment by jesseduffield** [comment]
While doing a quick investigation I found that the timestamps were actually based on the reflog commits rather than the reflog events themselves. I've merged this PR https://github.com/jesseduffield/lazygit/pull/606 to switch it. It's possible that resolves your issue, so I'd see how pulling the latest master goes.

Otherwise, would you be able to show me a bit of the results from `git reflog --date=relative --pretty='%gd|%gs' --grep-reflog='checkout: moving' HEAD`?

**Comment by glvr182** [comment]
Is this still an issue?

**Comment by nivv** [comment]
It wasn't working on `0.14.2` either, but then it hit me that maybe my git language was in swedish, and yup, it was. Exported english instead to my `.zshrc` file and now it's working.

```
$ echo "export LANG=en_US.UTF-8" >> ~/.zshrc
```

![image](https://user-images.githubusercontent.com/4033930/73927785-51260680-48d2-11ea-9f3e-7951ca802bc3.png)

**Comment by jesseduffield** [comment]
good to hear :)

**Comment by jlec** [comment]
Same problem here on Xenial which ships git-2.7.4. Upgrading to later git (usign 2.24 now) helped
