### ISSUE TITLE
lazygit: command not found

### ISSUE THREAD

**Issue by Vinzhuo** [jesseduffield/lazygit#6]
Call  command: go get github.com/jesseduffield/lazygit
Execute lazygit command in iTerm2
prompt: -bash: lazygit: command not found

**Comment by andreimc** [comment]
Do you have your $GOBIN in your $PATH

**Comment by Vinzhuo** [comment]
It's work right well after set $GOBIN in my $PATH

**Comment by jesseduffield** [comment]
@Vinzhuo does the issue remain after you close and re-open your terminal? The terminal session may not have the updated path set

**Comment by ssteiger** [comment]
had the same problem
for future ref.: https://github.com/golang/go/wiki/SettingGOPATH#zsh

**Comment by jesseduffield** [comment]
@ssteiger did following those linked steps resolve the issue for you?

**Comment by itsheng** [comment]
I ended up adding these lines in my bash profile file ~/.bash_profile

export GOPATH=$HOME/go
export GOBIN=$GOPATH/bin
export PATH=$PATH:$GOBIN

Now it works and I am ready to remove SourceTree. Thank you! @jesseduffield

**Comment by kirinzer** [comment]
@itsheng it's work for me, I add the same lines in my `.zshrc,` and reboot iTerm2, thx.

**Comment by ssteiger** [comment]
Also important: when adding the lines @itsheng provided, add them at the **bottom** of the `.zshrc` file, not at the top

**Comment by jesseduffield** [comment]
thanks guys! I'm closing this as it looks like the issue is resolved

**Comment by rand-kcs** [comment]
it works for me as well to change from:

export PATH=$PATH:/usr/local/go/bin

to:

export GOBIN=~/go/bin
export PATH=$PATH:$GOBIN

**Comment by Vinzhuo** [comment]
这是来自QQ邮箱自动回复邮件。
 
您好，您的邮件已收到，尽快给您回复。
