### ISSUE TITLE
Crash when discarding changes on MacOS

### ISSUE THREAD

**Issue by vigoux** [jesseduffield/lazygit#601]
**Describe the bug**
Lazygit crashes when discarding changes on a conflict due to a stash.

**To Reproduce**
 - Create a file.
- Commit it.
- Delete it.
- Stash.
- Modify the previously deleted file.
- Commit modifications.
- Pop stash (a warning appears).
- Go on deleted file, then discard changes.
- Crash happens here.

**Expected behavior**
No crash, or an error thrown as usual.

**Screenshots**
Don't have screenshots, but i have the error stack (git messages in french).
```
*errors.errorString error: le chemin 'TEST' n'est pas fusionné

/private/tmp/lazygit-20200110-71233-7u97hi/lazygit-0.13/pkg/commands/os.go:162 (0x164d6a3)
/private/tmp/lazygit-20200110-71233-7u97hi/lazygit-0.13/pkg/commands/os.go:74 (0x164cca2)
/private/tmp/lazygit-20200110-71233-7u97hi/lazygit-0.13/pkg/commands/os.go:128 (0x1645d0f)
/private/tmp/lazygit-20200110-71233-7u97hi/lazygit-0.13/pkg/commands/git.go:515 (0x1645c97)
/private/tmp/lazygit-20200110-71233-7u97hi/lazygit-0.13/pkg/commands/git.go:509 (0x1645ba5)
/private/tmp/lazygit-20200110-71233-7u97hi/lazygit-0.13/pkg/gui/files_panel.go:530 (0x16afec8)
/private/tmp/lazygit-20200110-71233-7u97hi/lazygit-0.13/pkg/gui/files_panel.go:558 (0x16affe5)
/private/tmp/lazygit-20200110-71233-7u97hi/lazygit-0.13/pkg/gui/menu_panel.go:59 (0x16b1791)
/private/tmp/lazygit-20200110-71233-7u97hi/lazygit-0.13/vendor/github.com/jesseduffield/gocui/gui.go:832 (0x11d669f)
/private/tmp/lazygit-20200110-71233-7u97hi/lazygit-0.13/vendor/github.com/jesseduffield/gocui/gui.go:812 (0x11d66af)
/private/tmp/lazygit-20200110-71233-7u97hi/lazygit-0.13/vendor/github.com/jesseduffield/gocui/gui.go:760 (0x11d6451)
/private/tmp/lazygit-20200110-71233-7u97hi/lazygit-0.13/vendor/github.com/jesseduffield/gocui/gui.go:483 (0x11d4cf2)
/private/tmp/lazygit-20200110-71233-7u97hi/lazygit-0.13/vendor/github.com/jesseduffield/gocui/gui.go:443 (0x11d4cfd)
/private/tmp/lazygit-20200110-71233-7u97hi/lazygit-0.13/pkg/gui/gui.go:835 (0x1677996)
/private/tmp/lazygit-20200110-71233-7u97hi/lazygit-0.13/pkg/gui/gui.go:844 (0x1677d1f)
/private/tmp/lazygit-20200110-71233-7u97hi/lazygit-0.13/pkg/app/app.go:166 (0x16c35cb)
/private/tmp/lazygit-20200110-71233-7u97hi/lazygit-0.13/main.go:73 (0x16c4728)
/usr/local/Cellar/go/1.13.6/libexec/src/runtime/proc.go:203 (0x10311be)
/usr/local/Cellar/go/1.13.6/libexec/src/runtime/asm_amd64.s:1357 (0x105ccd1)
```

**Desktop (please complete the following information):**
 - macOS Catalina 10.15.2 (19C57)
 - `commit=, build date=, build source=homebrew, version=0.13, os=darwin, arch=amd64`

**Additional context**
Actually another error happened, but the error was located at the exact same spot and with the exact same backtrace.
I could not reproduce the error though, that's why I report this one instead.

EDIT: Lazygit is a trully awesome program, thank you guys for bringing this to us !

**Comment by jesseduffield** [comment]
Thanks for the kind words @vigoux :)

And thanks for the detailed repro steps, I've actually come across this before but haven't known how to to reproduce it whenever it happened.

I've fixed this in https://github.com/jesseduffield/lazygit/pull/611
