### ISSUE TITLE
Be able to disable mouse support

### ISSUE THREAD

**Issue by baptistebisson** [jesseduffield/lazygit#602]
**Is your feature request related to a problem? Please describe.**
When I click inside my console with lazygit to make the window active, the click is targeted and it change the UI (go to files window or commits/stash ...).

**Describe the solution you'd like**
Be able to fully disable click support (an option in the menu ?)

**Additional context**
I'm using dual screen and to focus on lazygit window I use my mouse a lot. I would like to be able to keep the UI where it was before.

**Comment by mjarkk** [comment]
There is a lazygit config file where you can disable this behavior: https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md  

To open the config file, in lazygit:
1. <kbd>e</kbd>: edit config file

**Comment by baptistebisson** [comment]
Correct.
Sorry, I didn't look hard enough ...

Thanks !
