### ISSUE TITLE
Auto highlight the next item when toggling an item in the Files Panel?

### ISSUE THREAD

**Issue by theniceboy** [jesseduffield/lazygit#607]
Ranger uses this logic, where it automatically selects the next item (if there is one) for you when you press space to toggle an item. I think this will bring some convenience and productivity. Maybe this could be an option that users can turn on/off. What are your thoughts?

**Comment by jesseduffield** [comment]
Interesting suggestion. I'm not sure if this would make for a good user experience in all cases though. For example, when a file is only partially staged, hitting space once will fully stage it, and then a second time will fully unstage it. It would be weird to have the next item selected if you went to double-tap space for the sake of unstaging the file. It would also be weird if lazygit didn't select the next item when you staged it just in case you actually wanted to unstage it afterward.

Is that an edge case that you think would be problematic?

**Comment by theniceboy** [comment]
I see. I have not thought of that problem. One partial solution I came up with is just to stop the behavior of auto-selecting the next item when the current item is partially staged or was partially staged when it was selected. The user may manually move to the next selection, but before then, `space` will only toggle the current selection.

It’s a tough case.

**Comment by jesseduffield** [comment]
@theniceboy I'm gonna close this for now. I think at this point it's sufficient to stay on the same line when staging/unstaging

**Comment by theniceboy** [comment]
That makes sense. I can’t really come up with a better solution right now.

**Comment by d4be4st** [comment]
Could you maybe add a configuration for this? 

I would love if i did not have to do "space j space j space j..." when adding lots of new files

another suggestion i have is to have a new keybinding for "stage and select next item"

**Comment by svdo** [comment]
Just adding my 2 cents: I'd love this feature. My so-far-favorite-git-client does this as well, and it feels so much smoother. I understand that not always this would be desirable; maybe it could be a separate command ("stage and select next" or something) that you could then re-bind to <space> using config? That way you can keep the current behaviour working as-as. Your concern about staging partial files is valid by the way, but I quickly learned to deal with that.

Oh and I learned about lazygit just last week, but I'm very impressed and like to express my gratitude to you for putting in all your hard work!

**Comment by mark2185** [comment]
@jesseduffield are there any plans about creating macros, i.e. a list of key inputs that could be invoked, but _within_ `lazygit`, instead of being in a subshell, like `commands` currently do?

**Comment by jesseduffield** [comment]
I don't have any plans for macros right now, but potentially down the line we could do it. For this issue, I'll make a couple more observations:
* in most git UI's, staged changes are displayed separately to unstaged changes, so it makes more sense to jump to the next file upon staging/unstaging. In lazygit you might need to hit space twice on a file to get it to the desired state e.g. going from half-staged half-unstaged to unstaged. If we separated staged and unstaged changes, we would get this feature for free. That's something that's been suggested elsewhere and I'm open to it as something that can be configured.
* Something we're sorely missing at the moment is the ability to select a range of items in a list panel to then apply some action to all of them. It's annoying to have to hit space down space down etc to stage a list of files, and given that range selections have broad applicability in other contexts, I'm more interested in getting that implemented than having a keybinding to stage and select the next item.

**Comment by svdo** [comment]
Understood @jesseduffield, thanks for the explanation. I agree that the ability to select multiple lines in a list would be valuable and might mitigate this issue as well, or at least a good part of it.
