### ISSUE TITLE
lazygit in Portrait Mode

### ISSUE THREAD

**Issue by surmann** [jesseduffield/lazygit#612]
I use lazygit on a screen in portrait mode instead of the standard landscape mode. Is it possible to arrange the panels for screens in portrait mode in a different way? For example, I would like to have the left panes above the right one. This should be able to configure via a flag in the config file.

What do you think?

**Comment by jesseduffield** [comment]
I'm open to the idea, and it probably wouldn't be too hard to implement. For what it's worth I've recently merged a PR that splits the main panel vertically when the width of the window is sufficiently small:

![image](https://user-images.githubusercontent.com/8456633/73395601-f7529900-4333-11ea-93bb-8053958942ee.png)

Would you be able to provide a brief sketch of how you would like the panels arranged?

**Comment by surmann** [comment]
Currently, it looks like this:
![screenshot01](https://user-images.githubusercontent.com/4048472/73441247-f7ae5c80-4352-11ea-877e-35ab8d131cf6.png)

An idea is, to switch to something like this:
![screenshot02](https://user-images.githubusercontent.com/4048472/73441253-fa10b680-4352-11ea-8ea2-79abb51d864d.png)

Probably, the sizing is not optimal or it makes sense to put "Stash" under "Files". That depends on how much stuff you see in the different panels.

What do you think?

**Comment by jesseduffield** [comment]
I think that looks good. It might be a little awkward for the left/right arrow keys to now flick through the panels both horizontally and vertically but otherwise I think it's fine.

This would actually be a relatively easy change to implement: all the code for laying out the side panels currently lives in the `layout` method in gui.go. It would just need to read the config variable and then change the layout accordingly. Admittedly that layout method is getting a little hairy but I think it shouldn't be too hard to accomodate. Would you be willing to put up a PR for this?

**Comment by surmann** [comment]
I would. Unfortunately, I don't have any glue about Go, which makes it a bit harder for me.
When I find some time, I can give it a try.

**Comment by eproxus** [comment]
Idea: add visual "tabs" for the 1-5 views, and then do two panels one above the other (like the second screen mode except horizontal instead of vertical). The "tabs" could be used in the second and third screen mode too.

I'm using a 80 character wide terminal because of my small screen (editor on the left) and would love a proper portrait mode!

**Comment by jesseduffield** [comment]
@eproxus I'm not quite sure what you were describing, but I've got a PR https://github.com/jesseduffield/lazygit/pull/847 up that looks like this for 80 character width:

![image](https://user-images.githubusercontent.com/8456633/82143539-02e8b200-9888-11ea-9a85-a19d95e601de.png)

**Comment by jesseduffield** [comment]
also @surmann , here's what your design looks like when implemented:
![image](https://user-images.githubusercontent.com/8456633/82145022-2b25e000-988b-11ea-8605-352941617984.png)

The main concern I have with it is that you need the window to be quite wide to fit all the panels at the top there without them being too horizontally squished. Is that how you intend on using portrait mode?

**Comment by surmann** [comment]
@jesseduffield Yes, that looks good. But I share your concerns. Is it possible to test on a rotated screen? Any ideas to handle this?

**Comment by jesseduffield** [comment]
@surmann I myself don't use a rotated screen but if you do, you can clone this repo and checkout the branch `test-portrait-mode` to see how it works on your end. To run it you simply go `go run main.go` in the root directory of the repo

**Comment by jesseduffield** [comment]
Also here is a pick of normal lazygit with a portrait monitor: 
![image](https://user-images.githubusercontent.com/8456633/82204428-32f78a00-9948-11ea-9e12-941bb783740d.png)
Here it is in portrait mode:
![image](https://user-images.githubusercontent.com/8456633/82204583-82d65100-9948-11ea-861d-ff5c571a40e0.png)

tbh I the prefer regular layout

**Comment by surmann** [comment]
When I compare your two screenshots I see it in the same way you do.
I will try it when I am in the office.

**Comment by eproxus** [comment]
@jesseduffield That PR looks close to what I was imagining. I had in mind something like this:
```
┌─[Status] ─ Files ─ Branches ─ Commits ─ Stash ───────────────────────────────┐
│↑0↓0 ...                                                                      │
└──────────────────────────────────────────────────────────────────────────────┘
┌──────────────────────────────────────────────────────────────────────────────┐
│   _                       _ _                                                │
│  | |                     (_) |                                               │
│  | | __ _ _____   _  __ _ _| |_                                              │
│  | |/ _` |_  / | | |/ _` | | __|                                             │
│  | | (_| |/ /| |_| | (_| | | |_                                              │
│  |_|\__,_/___|\__, |\__, |_|\__|                                             │
│                __/ | __/ |                                                   │
│               |___/ |___/                                                    │
│ ...                                                                          │
└──────────────────────────────────────────────────────────────────────────────┘
```
Where the top box would switch between the 1-5 views just like in the existing vertical view today.

**Comment by surmann** [comment]
I would like to have more horizontal space when working on files line by line. In this case the "Changes" pane splits into two panes with half of the horizontal space.

**Comment by jesseduffield** [comment]
@surmann I've added to the above PR the ability to configure how your main panel splits like so:
```
gui:
  mainPanelSplitMode: 'vertical'
```
Let me know if that solves your issue :)

If not, you might find it useful to press + a couple times to get a full-screen view of the currently focused panel.

**Comment by jesseduffield** [comment]
note that I merged https://github.com/jesseduffield/lazygit/pull/847 because I don't want the PR diverging too much from the codebase but I'm happy to keep this  issue open

**Comment by jesseduffield** [comment]
I'm doing an audit of lazygit issues and I'm now thinking I'll close this issue: we effectively enable using lazygit in a portrait mode. Using tabs as @eproxus has suggested would be cool but it would require a bit of work to enable that I don't think would be worth the investment. WIlling to re-open if people disagree though :)

**Comment by laptobbe** [comment]
The tab feature that @eproxus suggested would be really nice when working with files/paths with really long names ie. java. It does work to zoom in and out but the entire experience would be nicer in my opinion.
