### ISSUE TITLE
Lazygit does not execute git commit --amend but CLI does

### ISSUE THREAD

**Issue by miho** [jesseduffield/lazygit#627]
**Describe the bug**
`git commit --amend` serves the purpose of correcting a previous commit. But the CLI command also allows to change the commit message even if no file changes exist. The CLI command and the Lazygit command show different behavior for no obvious reason. 

**To Reproduce**
1. type lazygit in repository folder
2. type `A` for ammend
3. See unexpected message: **there are no staged files to commit**

**Expected behavior**
A user requesting **Amend** (`--amend`) should see a text field with the previous commit message which can be changed/corrected. Then the `--amend` operation should be executed to be compliant with the git CLI.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Lazygit Version [0.8.1]

**Comment by jesseduffield** [comment]
I've decided to separate the concern of renaming commits from amending commits in terms of file changes because there are two ways you might want to rename a commit:
1) by using the in-app editor
2) by using the editor set in your EDITOR env variable (typically vim)

By going to a commit and pressing 'r' you use the in-app editor, whereas by pressing 'R' you use the other editor. In order to facilitate renaming a commit as part of the amend commit command from the files panel, I would need to bring up a menu asking whether the user wants to rename the commit, and if so, whether to do it in the app or in an external editor. This is a bit of a clunky user flow, which is why I've made them two separate things.

**Comment by jesseduffield** [comment]
closing, lemme know if you want this re-opened :)

**Comment by anvandaren** [comment]
Hi,

I've been trying to do the same thing. Is it possible to edit the commit message of the last commit in lazygit? I've not been able to find any entry in Menu that seems to do this.
I'm using lazygit 0.34 on Ubuntu 18.04.

**Comment by jesseduffield** [comment]
@anvandaren pressing 'r' on the commit will do the trick

**Comment by anvandaren** [comment]
Thanks! Found it. When I looked for the option I had accidentally opened the commit and had selected the file. When selecting the entire Commit without opening it the option was there.

**Comment by jesseduffield** [comment]
ah all good

**Comment by DhruvaG2000** [comment]
If I press "e" on a commit and then make some file changes there, save and exit editor, then coming back to lazygit I stage the changes.
I am not able to understand now how do I make those changes part of that commit, ie. equivalent of ``git commit --amend``?
I typed the command manually and it worked for me, but what is the lazy way to do this?

**Comment by stefanhaller** [comment]
Press Shift-A ("Amend last commit").

**Comment by DhruvaG2000** [comment]
I did try that, didn't work for me atleast

**Comment by mark2185** [comment]
What Stefan said, or if it's an older commit (i.e. not `HEAD`) you can select the commit you with to amend to in the `Commits` panel and press `A` ("amend commit with staged changes").

**Comment by DhruvaG2000** [comment]
Here's what I do:
1. click on commit (older than HEAD)
2. press "e"
3. click on file
4. press 'e' to edit file
5. Make change then save n exit
6. press space on my new change and it appears in ``Custom patch``
7. Shift A doesn't work, it doesn't do anything.

**Comment by mark2185** [comment]
Ah, you need to stage it in the `Files` panel and amend the commit you wish.

The `Custom Patch` thingy is not what you're looking for here ([more info](https://github.com/jesseduffield/lazygit/#rebase-magic-custom-patches)).

**Comment by DhruvaG2000** [comment]
Thanks @mark2185, that helped me do exactly what I was trying to do.
