### ISSUE TITLE
Lazygit uses 109% of CPU on MacOS Catalina

### ISSUE THREAD

**Issue by kylepollina** [jesseduffield/lazygit#633]
**Describe the bug**
Running Lazygit on MacOS Catalina starts spinning my fan and using 109% of my CPU

**To Reproduce**
1. Run `lazygit` within a git repository on MacOS Catalina

**Expected behavior**
Lazygit runs quietly and with low impact to my system

**Screenshots**
<img width="695" alt="Screen Shot 2020-02-05 at 9 02 24 AM" src="https://user-images.githubusercontent.com/13981456/73853871-2dda5900-47f7-11ea-9ba9-10597a538543.png">

**Desktop (please complete the following information):**
 - OS: MacOS Catalina Version 10.15.3
 - Lazygit Version v0.14

**Comment by kylepollina** [comment]
EDIT: it's gone back down to normal now, I'm not sure what was causing it but I'll poke around. Maybe it was only in a specific repository. I will update if I find out.

**Comment by jesseduffield** [comment]
my bad: forgot to do a release after I fixed that bug. I'm releasing v0.14.1 now, which should fix the issue

**Comment by kylepollina** [comment]
Awesome, not a problem! Glad to know it's being fixed. Thanks a bunch, I really love this tool

**Comment by jesseduffield** [comment]
thanks, I'm glad you like it! With the new release, has the cpu issue gone away @kylepollina ?

**Comment by kylepollina** [comment]
I haven't seen this problem anymore!

**Comment by jesseduffield** [comment]
awesome! closing
