### ISSUE TITLE
Add an option so that lazygit creates a new upstream branch automatically

### ISSUE THREAD

**Issue by dvdbng** [jesseduffield/lazygit#635]
PR #532 makes it so that you can choose the remote branch when pushing, but depending on your workflow, you might work with a lot of branches and always want to push to a upstream branch named the same as the local branch (and create it if it doesn't exist)

**Describe alternatives you've considered**
- Option 1: Follow the user's .gitconfig, only ask for remote branch depending on what the user has selected there
- Option 2: Add an option to lazygit/config.yml to change the behavior

**Comment by jesseduffield** [comment]
I like option 1 better because it requires less custom configuration, but if it turns out that the git config has many different possible values and it's hard to map that to a decision on whether to show that popup or not, we might need to go for option 2

**Comment by dvdbng** [comment]
Yes, I agree, I can't think of a clear way to map the git.default statuses either
