### ISSUE TITLE
Deleting a branch leaves current branch display in a bad state

### ISSUE THREAD

**Issue by peppy** [jesseduffield/lazygit#637]
After deleting a branch, the main display still attempts to show the just-deleted branch until a reselection is performed (stating `fatal: ambiguous argument 'fix-dialog-popups': unknown revision or path not in the working tree.`)

![image](https://user-images.githubusercontent.com/191335/74129652-79d83400-4c23-11ea-8b43-5f1dcf1ba7f3.gif)

Reproduction:

- Select branch pane
- Delete active branch

Observe right pane shows error instead of new selection

**Comment by jesseduffield** [comment]
good pickup. Should be fixed by https://github.com/jesseduffield/lazygit/pull/638

**Comment by peppy** [comment]
Fixed, thanks!
