### ISSUE TITLE
exec: "cat": executable file not found in %PATH%

### ISSUE THREAD

**Issue by surmann** [jesseduffield/lazygit#640]
I did a merge with lazygit 0.13 where both files of type ´.ism´ are modified and the the error message on the right side:

    exec: "cat": executable file not found in %PATH% 

This is the same on ´.rul´ files.
I use PowerShell 7.0.0-rc2 and the command `cat` works well when I invoke it directly.
Do you have any ideas how to solve this issue?

Is this related to #53 or #54 ?

**Comment by mjarkk** [comment]
Does cat also work in cmd?  
If not it might be that cat is a build in shell function from powershell and those will not work from inside lazygit.

**Comment by surmann** [comment]
You are right, it does not work on `cmd`. Is there a setting to solve this issue?

**Comment by mjarkk** [comment]
i don't know, but i think that lazygit should not call cat in the first on windows.

**Comment by jesseduffield** [comment]
we could fix this by adding a 'catCommand' field to the Platform struct and setting it to "type" for windows. Any takers? :)

**Comment by tydavis** [comment]
- Linux: `cat`
- Windows CMD: `type`
- Windows Powershell: `Get-Content`

**Comment by surmann** [comment]
@tydavis Yes, `type` is an alias of `Get-Content`.

**Comment by jesseduffield** [comment]
My memory is terrible but based on that linked commit I believe this issue is resolved, am I right?

**Comment by jesseduffield** [comment]
I believe this is fixed in the latest release
