### ISSUE TITLE
Ability to reset active branch to tracking

### ISSUE THREAD

**Issue by peppy** [jesseduffield/lazygit#642]
**Is your feature request related to a problem? Please describe.**

One scenario I encounter semi-regularly is completely destroying a local branch tracking `master` or otherwise (ie. merging multiple PRs to do some ad-hoc integration testing) and once done, resetting my local branch to its upstream tracking branch.

On CLI I would do this by issuing something along the lines of `git reset --hard upstream/master`, but this doesn't seem possible currently.

**Describe the solution you'd like**

Either an explicit command in the `Local Branches` area to reset to tracking branch, or the ability to use the "reset" command (usually only available in the `Commits - Reflog`) in the `Remotes` area, just allowing resetting to `HEAD` on any remote.

**Describe alternatives you've considered**

In some cases if you haven't mangled the branch too much, you can already achieve roughly this behaviour by resetting back to an old commit in the commits view, then fast-forwarding back to sane state.

**Comment by jesseduffield** [comment]
This is actually already supported (albeit not in an obvious spot). If you go 'shift+D' in the files panel there's an option to `hard reset to upstream branch` :)

**Comment by peppy** [comment]
Oh wow, so there is. That seems to do exactly what I want, but is definitely in a weird place.

Having full reset options (hard/mixed/soft) against a remote branch would still be a usability improvement, I believe.

**Comment by jesseduffield** [comment]
I wonder what the best design for that would be. I like the idea of keeping the command in the files panel for resetting to the upstream, given it's only affecting the currently checked out branch. I think it also makes sense to have a command for resetting to a remote branch in the remote branch area

**Comment by peppy** [comment]
Currently  (for me at least) when getting used to lazygit it's easy to lose track of where particular keybinds / options are available, so I think a good first step would be making options like reset in all panes they can be used (on branches to reset to HEAD, in this case). 

Now that I know where to find the reset-to-upstream this can potentially be closed, though.

**Comment by jesseduffield** [comment]
sounds good, I'll close this issue and create another one for the more specific use case

**Comment by jesseduffield** [comment]
new issue: https://github.com/jesseduffield/lazygit/issues/644
