### ISSUE TITLE
More ways to reset the current branch

### ISSUE THREAD

**Issue by jesseduffield** [jesseduffield/lazygit#644]
**Is your feature request related to a problem? Please describe.**
We need more ways to reset the current branch to something else. Currently in the files panel, shift+D lets you soft/hard reset to HEAD, as well as hard reset to @{upstream}. You can also soft/hard/mixed reset onto a selected commit by pressing 'g'

It would be good to be able to bring up a menu when any local or remote branch is selected and be able to soft/hard/mixed reset onto the HEAD of that branch.

**Describe the solution you'd like**
given we're not using the 'g' keybinding elsewhere (that I can tell), we should use that for resetting the current branch to the selected item, be it commit, or local/remote branch. resetting to HEAD is a kind of worktree deleting action so I don't have an issue keeping it under the shift+D keybinding, and you'll be able to do it in the local branch panel anyway by selecting the current branch, so I'll keep that as it is. 

I think that pressing 'g' on the files panel should bring up the reset options for the upstream branch. This is the only one that would break the pattern: in that the selected item (a file in this case) is irrelevant to the command. But that doesn't bother me too much

**Describe alternatives you've considered**
none

**Additional context**
we currently have the `git reset --hard @{upstream}` command in the files panel under shift+D, but I only really put it there for myself and I'm happy to remove it once the better solution is made.

**Comment by jesseduffield** [comment]
done in https://github.com/jesseduffield/lazygit/pull/646

**Comment by peppy** [comment]
This is awesome, thanks!

**Comment by jesseduffield** [comment]
no worries :)
