### ISSUE TITLE
Trying to fast-forward current branch doesn't work as expected

### ISSUE THREAD

**Issue by peppy** [jesseduffield/lazygit#647]
When attempting to fast-forward the current branch from the branches pane, it presents an error (`non-bare repository`). Switching to another branch first will allow it to succeed.

![image](https://user-images.githubusercontent.com/191335/74695593-d812a180-5237-11ea-84d3-d048e541ae1e.gif)

**Comment by jesseduffield** [comment]
I've put up a PR for this https://github.com/jesseduffield/lazygit/issues/647 which basically just does a `git pull --ff-only` if you're on the current branch, as opposed to a git fetch. Just doing a git fetch meant that your working tree would include changes that revert the effects of the new commits, which I don't think people would want.

Does that approach fit your use case?

**Comment by peppy** [comment]
yep, sounds about what i'd expect!

**Comment by jesseduffield** [comment]
sweet, merged
