### ISSUE TITLE
Cannot reset cursor position after clicking on the modal

### ISSUE THREAD

**Issue by kristijanhusak** [jesseduffield/lazygit#654]
**Describe the bug**
I'm not sure if this is bug with gocui, but i'll report it here, you'll know better.
When you open a commit message modal, and type few characters, then click with mouse in the middle of the modal, cursor will go to that position. If you continue typing, it will type, but cursor will be at wrong position all the time. Also you cannot delete anything after that happens.

**To Reproduce**
1. Stage some files
2. Open "Commit message" dialog with C
3. Type in few characters
4. Click with mouse in the middle of the commit message dialog
5. Continue typing, notice the behavior of the cursor
6. Try deleting with backspace, nothing happens

**Expected behavior**
I guess either cursor should jump back to the right position or clicking in the middle of modal should not even trigger cursor movement.

**Screenshots**
I'm not able to make a screenshot that shows the cursor for me, i'm probably using bad tool for it.

**Desktop (please complete the following information):**
 - OS: Linux
 - Lazygit Version - Unversioned, using from git
 - Commit: master branch - 205d731d7be974abcece5e02cc351bd26101168c

**Additional context**
restarting lazygit fixes it.

**Comment by jesseduffield** [comment]
Yeah I've seen this as well. I believe over in awesome/gocui work is being done to make the editing experience better wrt cursors: https://github.com/awesome-gocui/gocui/pull/48

**Comment by kristijanhusak** [comment]
@jesseduffield I pulled latest change (via go get), and it's still happening. I also verified that latest gocui vendor vas pulled.

**Comment by jesseduffield** [comment]
my bad, should  be good now on master!

**Comment by kristijanhusak** [comment]
Works now, thanks!

**Comment by jesseduffield** [comment]
no worries :)
