### ISSUE TITLE
Could not compile from source: jibber_jabber not contained

### ISSUE THREAD

**Issue by MoerkerkeLander** [jesseduffield/lazygit#655]
When I try to compile the latest release, I stumble on this error:

```shell
$ [2] ~/Programs/lazygit { tags/v0.14.4 } ❯ go build                                         
go: finding github.com/cloudfoundry/jibber_jabber latest
go: finding github.com/golang-collections/collections latest
go: finding github.com/spkg/bom latest
go: finding github.com/shibukawa/configdir latest
go: finding github.com/jbenet/go-context latest
build github.com/jesseduffield/lazygit: cannot load github.com/cloudfoundry/jibber_jabber: module github.com/cloudfoundry/jibber_jabber@latest found (v0.0.0-20151120183258-bcc4c8345a21), but does not contain package github.com/cloudfoundry/jibber_jabber
```

I also tried compiling from master but without success.. What can I do?

Thanks!

**Desktop (please complete the following information):**
 - OS: Arch 5.4.20-1-lts
 - Lazygit version: v0.14.4

**Comment by glvr182** [comment]
You can use the vendor folder using the following command, `GO111MODULE=off go build`, this should not have to download any packages. As for the error itself, we will have to look into the libraries unavailability.

**Comment by MoerkerkeLander** [comment]
That works! 
Thanks
