### ISSUE TITLE
FRs: a little wishlist...

### ISSUE THREAD

**Issue by prosoitos** [jesseduffield/lazygit#657]
**Is your feature request related to a problem? Please describe.**

No, they are just enhancements.

**Describe the solution you'd like**

I just discovered lazygit and absolutely love it. Very impressive tool which I will adopt for my daily work. I do miss a few features however, which alternative tools offer and which I was not able to find in the doc (maybe I missed something?), so I thought that I would suggest them here in case they might not be too hard to implement:

## 1. search capabilities

See also #407 .

## 2. ability to send git commands directly

(for instance by typing `:` and a command)

## 3. ability to see individual panels in full-screen

[tig](https://github.com/jonas/tig) does a good job with 1. and 2. And [grv](https://github.com/rgburke/grv) with 3 (typing `f` from a panel toggles having it in full-screen or going back to the default layout).

Thank you very much for the great project!!

Note that I could split these in separate issues if this would make more sense. I just didn't want to open too many issues at once.

**Comment by prosoitos** [comment]
1. was implemented by @jesseduffield in #659
2. was already there (by typing `X`)
3. was also already there :confounded: 

Sorry for being blind :hushed:

**Comment by prosoitos** [comment]
**edit**: the full screen functionality was actually just added in #667 :smile: 

That makes me feel better.

Thank you @jesseduffield for all the cool improvements!!!

**Comment by jesseduffield** [comment]
@prosoitos no worries :) glad you like them

**Comment by prosoitos** [comment]
I just realized that the right panels actually never get into full screen (since there are 2 of them, they are both half-screen).

It may be difficult to make them full screen or maybe this is by design (maybe you want to be able to see both of them together at all times).

When doing version control on code, that's fine since nicely formatted code should never have very long lines. But if you do version control on non-programming text files (LaTeX, md, org, etc.), then it is impossible to see the end of the lines and I would prefer to be able to have the unstaged and staged panels in full screen (if possible of course and if like the idea of course. This is obviously only a personal preference).

Alternatively, if you want to always keep the 2 together, maybe the ability to have them stacked vertically instead of horizontally would also allow to see more of the long lines.

**Comment by prosoitos** [comment]
In addition to this, the problem with long lines might also benefit from line-wrapping (that's what tig does).

Note that there might already be line-wrapping options or other ways to see the end of long lines that I missed (if so: apologies for the noise!).
