### ISSUE TITLE
FR: replace `git diff` by `git diff --stat -p` to get summary of changed files at top of Patch panel

### ISSUE THREAD

**Issue by prosoitos** [jesseduffield/lazygit#661]
**Is your feature request related to a problem? Please describe.**

Not a problem, simply an enhancement.

While looking at the diffs of commits, tig displays a list of the files changed in that commit with their summary (number of additions and deletions).

This is another little nicety I am missing in lazygit. I think that it would be extremely convenient to be able to see which files were changed in each commit, simply by going up and down the panel 4, without having to scroll the Patch panel.

**Describe the solution you'd like**

I did not look at what command tig uses, but one git command that does exactly this is:
```sh
git diff --stat -p
```

So I think that replacing `git diff` by this command might be all it takes to achieve this.

**Comment by jesseduffield** [comment]
nice, I didn't realise it would be so easy! implemented in https://github.com/jesseduffield/lazygit/pull/662

**Comment by prosoitos** [comment]
I am not sure how long it takes until I can pull changes from the devel version in the AUR, but I'll test it as soon as I have access to it.

Thanks!!!! :smile:

**Comment by patnr** [comment]
Similar to this issue/PR, I suggest showing the result of `git --diff --stat` (no `-p`) in the main panel when the user goes to [1] "Status". Similar to the "Files" [2] panel it would show the diff for work-tree vs. HEAD, but it details _how much_ change there is (for each file, at a glance).
