### ISSUE TITLE
[Feature request] Smartcase/Ignorecase for Searching in Side Panels

### ISSUE THREAD

**Issue by theniceboy** [jesseduffield/lazygit#672]
As mentioned in #670, I would say that having the ability to enable `smartcase` or `ignorecase` for searching within side panels may provide further improvement to #659. What are your thought? @jesseduffield is it going to be difficult to implement (as the search feature was implemented in your custom `gocui`)?

**Comment by jesseduffield** [comment]
I think this would be pretty straightforward to implement, though I wonder if it would be a performance hit to be converting case as we search. Happy to make a start on this under the assumption that it won't cause any performance issues. 

Did you have an idea on what the UX should be? Having a look at `man less`:
```
   -i or --ignore-case
          Causes searches to ignore case; that is, uppercase  and  lowercase  are  considered
          identical.   This  option  is ignored if any uppercase letters appear in the search
          pattern; in other words, if a pattern contains uppercase letters, then that  search
          does not ignore case.
```
Maybe we should just do that by default? How often does somebody want to do a case-sensitive search on a string that only has lowercase letters?

**Comment by theniceboy** [comment]
Yeah, I think case insensitive should be the default option. It is usually what people use for vim, and it is definitely the standard for 99.9999% of gui applications.

**Comment by jesseduffield** [comment]
sounds good

**Comment by jesseduffield** [comment]
Implemented in https://github.com/jesseduffield/lazygit/pull/703, closing :)

**Comment by theniceboy** [comment]
@jesseduffield Awesome!
