### ISSUE TITLE
Ubuntu throws error

### ISSUE THREAD

**Issue by mpericks** [jesseduffield/lazygit#68]
2018/08/07 10:15:06 invalid argument
panic: invalid argument

goroutine 1 [running]:
log.Panicln(0xc420065f00, 0x1, 0x1)
        /usr/lib/go-1.10/src/log/log.go:340 +0xc0
main.run()
        /build/lazygit-3g32Dt/lazygit-0.0~git20180807.66.4d425de/obj-x86_64-linux-gnu/src/github.com/jesseduffield/lazygit/gui.go:267 +0x8a
main.main()
        /build/lazygit-3g32Dt/lazygit-0.0~git20180807.66.4d425de/obj-x86_64-linux-gnu/src/github.com/jesseduffield/lazygit/main.go:68 +0xf2

**Comment by ponsfrilus** [comment]
@mpericks It would help if you can explain how to reproduce that and also specify version and operating system...

**Comment by Oxicode** [comment]
me too 
![image](https://user-images.githubusercontent.com/1320709/43867339-7f600eea-9b2e-11e8-98be-a80febab0541.png)

**Comment by mpericks** [comment]
I got the daily on the day I posted . Running Ubuntu 16.04.03 LTS

To duplicate:
1. Type 'lazygit' at the command line

**Comment by Sergix** [comment]
I'm also getting this error. Running the same version as @mpericks, in Windows Subsystem for Linux.

**Comment by Sergix** [comment]
Also, `lazygit -v` returns:

 `commit=, build date=, version=unversioned`

And `lazygit -debug` returns

```
panic: open /src/github.com/jesseduffield/lazygit/commands.log: no such file or directory

goroutine 1 [running]:
main.localLog(0x8492b6, 0xc, 0xc42011be20, 0x1, 0x1)
        /build/lazygit-6SHS9a/lazygit-0.0~git20180810.161.f20121c/obj-x86_64-linux-gnu/src/github.com/jesseduffield/lazygit/main.go:61 +0x25c
main.commandLog(0xc42011be20, 0x1, 0x1)
        /build/lazygit-6SHS9a/lazygit-0.0~git20180810.161.f20121c/obj-x86_64-linux-gnu/src/github.com/jesseduffield/lazygit/main.go:52 +0x54
main.runCommand(0x8484b3, 0xa, 0x752ae2, 0xc42002a8d0, 0x2d, 0x0)
        /build/lazygit-6SHS9a/lazygit-0.0~git20180810.161.f20121c/obj-x86_64-linux-gnu/src/github.com/jesseduffield/lazygit/gitcommands.go:222 +0xdc
main.verifyInGitRepo()
        /build/lazygit-6SHS9a/lazygit-0.0~git20180810.161.f20121c/obj-x86_64-linux-gnu/src/github.com/jesseduffield/lazygit/gitcommands.go:296 +0x3a
main.main()
        /build/lazygit-6SHS9a/lazygit-0.0~git20180810.161.f20121c/obj-x86_64-linux-gnu/src/github.com/jesseduffield/lazygit/main.go:114 +0xc8
```

**Comment by swizardlv** [comment]
![image](https://user-images.githubusercontent.com/10117682/44296146-ef8f6800-a2ea-11e8-8ed7-55606e6c777e.png)
I also met this issue in windows 10 linux subsystem

**Comment by glvr182** [comment]
This is likely not relevant anymore. Suggest we close it

**Comment by jesseduffield** [comment]
closing :)
