### ISSUE TITLE
Yet-to-be-pushed (Local) Commits Are Green Instead of Red.

### ISSUE THREAD

**Issue by theniceboy** [jesseduffield/lazygit#680]
**Describe the bug**
This might be just a misunderstanding of mine, but I thought the hash of unpushed local commits should be red, instead of green. What can I do to change this?

**To Reproduce**
1. Install lazygit (I installed it with brew)
2. Go into a repo with the default lazygit config.
3. Commit a change without pushing it.

**Expected behavior**
I was expecting the hash of unpushed (local) commits in the commits panel to be red. 

**Screenshots**
![image](https://i.ibb.co/gt0HWj8/Screenshot-from-2020-02-26-13-10-55.png)

**Desktop (please complete the following information):**
 - OS: Arch Linux (latest)
 - Lazygit Version [e.g. v0.1.5.3]
 - Commit: 8eb0b0f4caee4044acd278eb18c901bc7312dfe3

**Comment by jesseduffield** [comment]
what the hell! So they are. I'm just gonna directly push to master to fix this one. Should be fixed in v0.15.4 :)

**Comment by theniceboy** [comment]
@jesseduffield Awesome! Thank you so much!
