### ISSUE TITLE
Windows_x86_64 build for v0.15.5 missing on release page

### ISSUE THREAD

**Issue by quincunx** [jesseduffield/lazygit#683]
@jesseduffield, though mentionen in `checksums.txt`, the 64 bit build of v0.15.5 for Windows is missing.

https://github.com/jesseduffield/lazygit/releases/tag/v0.15.5

**Comment by dawidd6** [comment]
https://github.com/jesseduffield/lazygit/releases/tag/v0.15.6

There it is.

But now we've lost `armv6` linux tarball.

**Comment by quincunx** [comment]
Thx!
