### ISSUE TITLE
Is it impossible to unstage hunks?

### ISSUE THREAD

**Issue by prosoitos** [jesseduffield/lazygit#687]
Am I missing something or is it impossible to unstage individual hunks?

Since `Space` toggles staging and unstaging files in the Files window, I was expecting to be able to stage/unstage individual hunks in a similar fashion in the right window.

I might have totally missed something, but I was unable to do that and after accidentally staging a hunk, I had to unstage the entire file and re-stage all the other hunks.

**Comment by jesseduffield** [comment]
the 'd' key will unstage hunks. When looking at unstaged changes, it will delete the lines from the file. When looking at staged changes, it will unstage the lines. If that's unintuitive I'm happy to consider alternatives :)

**Comment by prosoitos** [comment]
Oh, I see. I thought from the menu explanation that it was deleting the changes in both cases.

The menu terminology is a little confusing here (particularly since the menu is the same in both cases).

I feel that it would be more intuitive to have the same behaviour in the Files window and in the right-side window.

For instance `Space` staging/unstaging files or hunks respectively.

(And maybe `d` to delete the change).

**Comment by prosoitos** [comment]
I thought that I was probably missing something though :smile: 

It did cross my mind that `d` might be it, but `reset selection` sounded a bit scary and I didn't want to take a chance and loose my edits.

**Comment by jesseduffield** [comment]
I think this makes sense. So the new approach should be:
1) space will stage a line if you're looking at unstaged changes, and unstage a line if you're looking at staged changes
2) 'd' should only apply to when we're looking at unstaged changes, and will delete a change

This has also brought to light a need for better documentation. Whether that's in the form of a better description against the 'd' key ('delete selected changes' perhaps?) or some way of getting good in-app docs, I'm not sure. I do like the idea of having a keybinding for when you're viewing a keybinding in the menu and it brings up another popup that gives more detail or explains the bigger picture. Though I don't want to go too hard on the documentation side of things until I feel like the feature set has had some time to settle (lazygit's almost at v1.0 but I don't think it's quite there yet)

**Comment by prosoitos** [comment]
Great! I think that it will be a lot more intuitive this way.

As for the doc, whether or not you go fancy and add detailed popups, I feel that the best way to describe what a keybinding does in the summary box is to give the Git code being run (for instance here is it `git reset`?).

If you worry that users who are coming to your tool because they don't want to learn all the nitty gritty  technicalities of Git will not understand them, then maybe a simple explanation followed by the function being run in parenthesis might be best? Or would it be too long for your box?

For instance here, that could be something like:

`d           delete change (git reset)`

No? I like having the real Git command being run to know exactly what will happen. And that could have a pedagogical side-effect too :slightly_smiling_face: And if a user want to get more info on that command, then they can google the git command to find info on exactly that.

That said, all these are only suggestions!! Do what you think is best :slightly_smiling_face: 

And I will close this issue. Thank you for being so responsive to feed-back!! (and for being so quick in replying).

I don't know Go and I am extremely busy the coming few weeks. But when I have a bit more time, I will jump into the code and see if I can start contributing through PRs.

**Comment by jesseduffield** [comment]
@prosoitos I've just merged a PR https://github.com/jesseduffield/lazygit/pull/689 that allows space to toggle staged/unstaged. I've also updated the wording on the keybinding. I agree that when possible we should include the git command in brackets as you suggest, I'll certainly keep it in mind for future.

Let me know if there's any more issues in this area :)

**Comment by prosoitos** [comment]
Thank you :slightly_smiling_face:
