### ISSUE TITLE
Add tab and search keybindings in Keybindings_*.md

### ISSUE THREAD

**Issue by hitsuji-no-shippo** [jesseduffield/lazygit#693]
[Keybindings_*.md](https://github.com/jesseduffield/lazygit/blob/master/docs/keybindings/Keybindings_en.md) does not have the following keybindings. 

<pre>
  <kbd>[</kbd>: prev tab
  <kbd>]</kbd>: next tab
  <kbd>/</kbd>: search
</pre>

I tried to make changes using [scripts/generate_cheatsheet.go](https://github.com/jesseduffield/lazygit/blob/master/scripts/generate_cheatsheet.go). However, I have no experience using Golang. Therefore, I decided that I could not do it and gave up. 

Someone please add it.

**Comment by jesseduffield** [comment]
This requires adding a `Description` to the relevant keybindings in `pkg/gui/keybindings.go`, and putting the descriptions in `pkg/i18n/english.go`. Feel like having another crack? :)

**Comment by hitsuji-no-shippo** [comment]
Hi @jesseduffield .

Thank you for teaching me. I'll try.
The result will be commented until 12:00 on March 6 (UTC).

**Comment by jesseduffield** [comment]
actually there is a PR up for the tab stuff here https://github.com/jesseduffield/lazygit/pull/692 so only the search thing is necessary

**Comment by hitsuji-no-shippo** [comment]
Hi @jesseduffield .

I created a pull request (#697).

**Comment by glvr182** [comment]
Since the PR is closed, I assume this issue can be closed aswell?

**Comment by jesseduffield** [comment]
I believe it can :)
