### ISSUE TITLE
Shell Config Nuke

### ISSUE THREAD

**Issue by octobanana** [jesseduffield/lazygit#7]
In the installation part of the README.md, the use of the redirect operator `>` will cause the entire files contents to be overwritten. It should be changed to the append operator `>>`. If someone were to copy and paste it without version controlled dot files, it could lead to a very sad programmer.

`echo "alias lg='lazygit' > ~/.zshrc`
to
`echo "alias lg='lazygit'" >> ~/.zshrc`

**Comment by jesseduffield** [comment]
NICE catch! updating now

**Comment by jesseduffield** [comment]
fixed :)
