### ISSUE TITLE
Can't commit with multiple words commit message

### ISSUE THREAD

**Issue by spandelk** [jesseduffield/lazygit#70]
As in the title.
If the commit message is only one word long, it commits without any problems.
And i can commit with multiple words message from the Command Prompt (using 'git commit -m <message>) also without any problems.

![2018-08-07 18_54_37-windows powershell](https://user-images.githubusercontent.com/8223125/43790641-844298f8-9a73-11e8-9c64-eac4cadd68ff.png)

![2018-08-07 18_54_52-windows powershell](https://user-images.githubusercontent.com/8223125/43790654-8c65ece2-9a73-11e8-964f-e524a88b4b29.png)

Any ideas?

**Comment by spandelk** [comment]
At first it looks like lazygit is executing 'git commit -m aaa bbb ccc'
But i checked the code, and it indeed adds the quotes to the message.

**Comment by ponsfrilus** [comment]
Also see #28

**Comment by martkans** [comment]
I also have this problem

**Comment by jesseduffield** [comment]
I'm going to have a look into this now

**Comment by jesseduffield** [comment]
Just pushed a new release that fixes the problem (at least on my my windows machine). Let me know if there are still any issues :)

**Comment by spandelk** [comment]
Now it's all working, thanks ;) 
Closing.
