### ISSUE TITLE
"new branch" should branch off selected branch, not checked-out branch

### ISSUE THREAD

**Issue by peppy** [jesseduffield/lazygit#700]
Sometimes I want to create a new branch off of master (usually to cherry-pick some commits out of a large branch for PRing separately). Right now, the process involves copying some commits, checkout out master, creating the new branch, pasting commits, pushing.

Allowing creating the new branch from a selected branch in the branches window would reduce these steps by one. I think this would be a good usability change in general (since it's how lazygit works in most other cases – contextual to the current selection).

**Comment by jesseduffield** [comment]
Totally agree. I've got a PR up for this: https://github.com/jesseduffield/lazygit/pull/701, could you give that a try?
