### ISSUE TITLE
Branch appears twice after rename

### ISSUE THREAD

**Issue by prosoitos** [jesseduffield/lazygit#706]
**Describe the bug**

First, a feature request: have a way to rename branches (I did not see anything in the branch menu for this).

Then, for the bug:
After renaming a branch (in Git since I didn't know how to do it in lazygit), that branch appears twice in the "Local Branches" box (twice under its new name).

**To Reproduce**

Rename a branch in Git, then open lazygit.

**Screenshots**

![2020-03-12_21:11:32](https://user-images.githubusercontent.com/4634851/76589078-1ea99380-64a6-11ea-9df4-be22add8e57a.png)

**Desktop (please complete the following information):**

 - OS: Arch Linux (5.5.8-arch1-1)
 - Commit: 7df4b736

**Comment by jesseduffield** [comment]
Regarding your feature request: did you have any thoughts around how we should deal with the remote that the branch is tracking (if any)?

Something I'm considering: if the branch is tracking a remote branch, give a warning before prompting for the new name and tell user which keybinding allows for changing the upstream.

What are your thoughts?

**Comment by jesseduffield** [comment]
I've got a PR up for this now if you want to give it a test :) https://github.com/jesseduffield/lazygit/pull/711

**Comment by jesseduffield** [comment]
I've sinced merged that PR. Let me know if you're issue still persists :) and we can re-open the issue

**Comment by prosoitos** [comment]
Will do! And apologies again for my very slow replies! (very busy right now).

Thank you for looking into this!
