### ISSUE TITLE
GolangCI is closing, what to use now

### ISSUE THREAD

**Issue by glvr182** [jesseduffield/lazygit#708]
**Topic**
A few days ago, GolangCI [announced ](https://medium.com/golangci/golangci-com-is-closing-d1fc1bd30e0e) that it is closing. This is of course very unfortunate as their service was very usefull in PR's. Now the question is, what are we gonna do with the GolangCI test we have running now?

**Your thoughts**
We can
 * Use github actions to check the code
 * Host GolangCI on a server
 * Switch to a different provider

**Comment by dawidd6** [comment]
I would say: Github Actions.

**Comment by jesseduffield** [comment]
I have no idea how github actions works but assuming it DOES work, I'm in favour

**Comment by dawidd6** [comment]
There is also something like this:
https://github.com/marketplace/codefactor

Looks like it supports Go and has a free plan.

**Comment by dawidd6** [comment]
It actually isn't, we still do not have a working replacement.

**Comment by jesseduffield** [comment]
Looks like https://github.com/golangci/golangci-lint-action would  do the trick
