### ISSUE TITLE
apt-secure error

### ISSUE THREAD

**Issue by vsviridov** [jesseduffield/lazygit#71]
After running `sudo apt-get update`

```
E: The repository 'http://ppa.launchpad.net/lazygit-team/daily/ubuntu artful Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

I'm on Ubuntu 17.10 Artful. Guess it's time to upgrade :D

**Comment by jesseduffield** [comment]
Hmm, I'm not fully across the linux side of things. Does this ring a bell @dawidd6 ?

**Comment by vsviridov** [comment]
I think it's because http://ppa.launchpad.net/lazygit-team/daily/ubuntu/dists/artful 404's

**Comment by dawidd6** [comment]
Yes, artful is already EOL, if you don't want to upgrade to bionic, you can just replace 'artful' with 'bionic' or even 'xenial' in lazygit file with urls (if you added PPA with add-apt-repository) located in `/etc/apt/sources.list.d`

**Comment by vsviridov** [comment]
The `README` mentions
> Packages for Ubuntu 16.04 and up are available via Launchpad PPA.

Artful is 17.10

**Comment by dawidd6** [comment]
Okay, so it needs to be more precise then. Will make a PR later.

**Comment by ponsfrilus** [comment]
Ubuntu 17.10 (Artful Aardvark) reaches End of Life on July 19 2018. 

https://lists.ubuntu.com/archives/ubuntu-announce/2018-July/000232.html

**Comment by kescobo** [comment]
This is happening again - I'm on Ubuntu (well, pop!_os) 20.10 groovy. Is it possible to get an update that works on the new release?

Manual installation with `go get` worked fine.

**Comment by dawidd6** [comment]
20.10 and 21.04 will soon get the packages.
