### ISSUE TITLE
Idea for browsing a submodule

### ISSUE THREAD

**Issue by MuratUrsavas** [jesseduffield/lazygit#710]
I'm enjoying lazygit these days but miss a little thing, browse and commit changes in a submodule. I know it could be a hassle to show everything in a low res terminal window. I think I've got an idea while writing this request (wrote my first idea but found a better one and erased most of the message)

So, as far as I can see lazygit is able to understand that folder is a submodule. In this case "b" key could be used for "Browse Submodule" command. In that call lazygit can trigger another lazygit in submodules folder with a command line parameter "--parent_repo=<parent_repo_path>".

If that parameter exists, lazygit also can return to that parent repo via opening another lazygit instance int parent repo path on program exit.

One thing could be an issue: Can a console program close itself and then run another console program at the same time?

For me, executing lazygit in a submodule folder in a new terminal window would be just fine, but then, this could hurt some of the lazygit's advantages as a console software.

Regards,

**Comment by jesseduffield** [comment]
interesting proposal. There's really nothing stopping us from just opening the submodule in the same way that we would open any other git repo, and perhaps then when you press 'esc' it kicks you back to the parent repo. What are your thoughts on that?

**Comment by MuratUrsavas** [comment]
Thinking exactly the same thing. Since lazygit is blazingly fast, it wouldn't be a problem to open a submodule and then open back the parent repo.

**Comment by jesseduffield** [comment]
This is implemented in https://github.com/jesseduffield/lazygit/pull/1026
