### ISSUE TITLE
Achievements

### ISSUE THREAD

**Issue by jesseduffield** [jesseduffield/lazygit#712]
**Describe the solution you'd like**
This is one of those bizarre ideas that I will probably abandon when somebody tells me how bad an idea it is. But what if there were achievements in lazygit? Like, the 1000th time that you push to a repo, a little non-intrusive flash notification shows up in the bottom right where the keybindings appear saying 'Achievement Unlocked: Mountain Mover (push 1000 times)'

**Describe alternatives you've considered**
Not doing this.

**Additional context**
Nope

**Comment by theniceboy** [comment]
sounds interesting, but this goes against the name, right?

LAZYgit

**Comment by jesseduffield** [comment]
Closing this for now, though the idea still interests me. Maybe an opt-in leaderboard or something.
