### ISSUE TITLE
New keys

### ISSUE THREAD

**Issue by axet** [jesseduffield/lazygit#713]
Hello! I like your piece of software very much. But few keys seems not function enough. Two behavior a bit uncomfortable: 'tab' go forward, but shift 'tab' does not go backward. Keys 'left' and 'right' duplicate tab behavior for no reason, using page up and page down not very comfortable on every laptop.

I suggest few solutions:

1) add 'shift+'tab hot key as opposite action to 'tab' what ever it hot keyed to.
2) using page up and page down can be duplicated/replacement by ctrl+up and ctrl+down hotkeys?
3) split similar behavior tab/shift+tab and left and right keys or replace it with scrolling source code window

**Comment by jesseduffield** [comment]
1) shift+tab is not possible on a terminal (or if it is it's not possible with termbox)
2) I don't think ctrl+up and ctrl+down are supported either
3) I'm not sure what you mean here

**Comment by axet** [comment]
ok.

3. duplicate behavior 'tab' and arrow 'right' can be do something else. like scrolling or something.

**Comment by axet** [comment]
@jesseduffield I'm not sure why are you saying 'back tab' is not possible. Simple test gives me a positive result:

```
# showkey -a
	 	  9 0011 0x09
^[[Z 	 27 0033 0x1b
 	 91 0133 0x5b
 	 90 0132 0x5a
```

**Comment by jesseduffield** [comment]
I said it's likely not possible due to termbox, the underlying library used by gocui. There is a PR up in a fork of gocui, https://github.com/awesome-gocui/gocui/pull/45, which switches to tcell. When that's done, we may be able to use shift+tab. I'll keep this issue open until that's resolved

**Comment by jesseduffield** [comment]
@axet the latest release has support for shift+tab now. I believe the other keys you mentioned can be handled via the config. Are we good to close this issue?

**Comment by axet** [comment]
Thanks! Now it feels much more friendly!
