### ISSUE TITLE
Panic error on CentOS 7 x86_64

### ISSUE THREAD

**Issue by kirill-ratkin** [jesseduffield/lazygit#719]
**Describe the bug**
CentOS Linux release 7.7.1908 (Core)
Tool is built from source: go get github.com/jesseduffield/lazygit
Go version: go version go1.13.8 linux/amd64
Git version: git version 1.8.3.1

**To Reproduce**
1. cd /tmp/
2. lazygit
3. press 'y' to create repo

**Expected behavior**
.git created

**Desktop (please complete the following information):**
 - OS: CentOS Linux release 7.7.1908 (Core)
 - Lazygit Version [commit=, build date=, build source=unknown, version=unversioned, os=linux, arch=amd64]
 - The last commit id if you built project from sources (3aab37611a26834af8348441d864ecad3eb15674)

**Additional context**
[builder@build tmp]$ lazygit
Not in a git repository. Create a new git repository? (y/n): y
panic: error: unknown option `format=%(HEAD)|%(refname:short)|%(upstream:short)|%(upstream:track)'
usage: git branch [options] [-r | -a] [--merged | --no-merged]
   or: git branch [options] [-l] [-f] <branchname> [<start-point>]
   or: git branch [options] [-r] (-d | -D) <branchname>...
   or: git branch [options] (-m | -M) [<oldbranch>] <newbranch>

Generic options
    -v, --verbose         show hash and subject, give twice for upstream branch
    -q, --quiet           suppress informational messages
    -t, --track           set up tracking mode (see git-pull(1))
    --set-upstream        change upstream info
    -u, --set-upstream-to <upstream>
                          change the upstream info
    --unset-upstream      Unset the upstream info
    --color[=<when>]      use colored output
    -r, --remotes         act on remote-tracking branches
    --contains <commit>   print only branches that contain the commit
    --abbrev[=<n>]        use <n> digits to display SHA-1s

Specific git-branch actions:
    -a, --all             list both remote-tracking and local branches
    -d, --delete          delete fully merged branch
    -D                    delete branch (even if not merged)
    -m, --move            move/rename a branch and its reflog
    -M                    move/rename a branch, even if target exists
    --list                list branch names
    -l, --create-reflog   create the branch's reflog
    --edit-description    edit the description for the branch
    -f, --force           force creation (when already exists)
    --no-merged <commit>  print only not merged branches
    --merged <commit>     print only merged branches
    --column[=<style>]    list branches in columns

goroutine 1 [running]:
github.com/jesseduffield/lazygit/pkg/commands.(*BranchListBuilder).obtainBranches(0xc000311950, 0xc000027278, 0x6, 0xc0000686b8)
        /home/builder/.gostuff/src/github.com/jesseduffield/lazygit/pkg/commands/branch_list_builder.go:49 +0x541
github.com/jesseduffield/lazygit/pkg/commands.(*BranchListBuilder).Build(0xc000311950, 0xc000311a58, 0xc0000a94a0, 0xc000367b40)
        /home/builder/.gostuff/src/github.com/jesseduffield/lazygit/pkg/commands/branch_list_builder.go:96 +0x6b
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).refreshBranches.func1(0xc0002d0000, 0xc00031199c, 0x3)
        /home/builder/.gostuff/src/github.com/jesseduffield/lazygit/pkg/gui/branches_panel.go:70 +0x52
github.com/jesseduffield/lazygit/vendor/github.com/jesseduffield/gocui.(*Gui).consumeevents(0xc0002d0000, 0x0, 0x0)
        /home/builder/.gostuff/src/github.com/jesseduffield/lazygit/vendor/github.com/jesseduffield/gocui/gui.go:483 +0x1e8
github.com/jesseduffield/lazygit/vendor/github.com/jesseduffield/gocui.(*Gui).MainLoop(0xc0002d0000, 0xc000000003, 0xc000311c88)
        /home/builder/.gostuff/src/github.com/jesseduffield/lazygit/vendor/github.com/jesseduffield/gocui/gui.go:465 +0x215
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).Run(0xc0002aa180, 0x0, 0x0)
        /home/builder/.gostuff/src/github.com/jesseduffield/lazygit/pkg/gui/gui.go:1019 +0x626
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).RunWithSubprocesses(0xc0002aa180, 0x0, 0x0)
        /home/builder/.gostuff/src/github.com/jesseduffield/lazygit/pkg/gui/gui.go:1028 +0x40
github.com/jesseduffield/lazygit/pkg/app.(*App).Run(0xc0001e20e0, 0xc00011aa00, 0xc0001e20e0)
        /home/builder/.gostuff/src/github.com/jesseduffield/lazygit/pkg/app/app.go:158 +0x6b
main.main()
        /home/builder/.gostuff/src/github.com/jesseduffield/lazygit/main.go:67 +0x778

**Comment by kirill-ratkin** [comment]
I tried version 0.17 from repo: https://copr.fedorainfracloud.org/coprs/atim/lazygit/repo/epel-7/atim-lazygit-epel-7.repo

$ lazygit -version
commit=, build date=, build source=unknown, version=0.17.0, os=linux, arch=amd64

Result is the same.

`$ /usr/bin/lazygit
panic: error: unknown option `format=%(refname:short)|%(upstream:short)|%(upstream:track)'
usage: git branch [options] [-r | -a] [--merged | --no-merged]
   or: git branch [options] [-l] [-f] <branchname> [<start-point>]
   or: git branch [options] [-r] (-d | -D) <branchname>...
   or: git branch [options] (-m | -M) [<oldbranch>] <newbranch>

Generic options
    -v, --verbose         show hash and subject, give twice for upstream branch
    -q, --quiet           suppress informational messages
    -t, --track           set up tracking mode (see git-pull(1))
    --set-upstream        change upstream info
    -u, --set-upstream-to <upstream>
                          change the upstream info
    --unset-upstream      Unset the upstream info
    --color[=<when>]      use colored output
    -r, --remotes         act on remote-tracking branches
    --contains <commit>   print only branches that contain the commit
    --abbrev[=<n>]        use <n> digits to display SHA-1s

Specific git-branch actions:
    -a, --all             list both remote-tracking and local branches
    -d, --delete          delete fully merged branch
    -D                    delete branch (even if not merged)
    -m, --move            move/rename a branch and its reflog
    -M                    move/rename a branch, even if target exists
    --list                list branch names
    -l, --create-reflog   create the branch's reflog
    --edit-description    edit the description for the branch
    -f, --force           force creation (when already exists)
    --no-merged <commit>  print only not merged branches
    --merged <commit>     print only merged branches
    --column[=<style>]    list branches in columns



goroutine 1 [running]:
github.com/jesseduffield/lazygit/pkg/commands.(*BranchListBuilder).obtainBranches(0xc0002d3950, 0xc0001dc7e8, 0x6, 0xc0000d0658)
        /builddir/build/BUILD/lazygit-0.17.0/pkg/commands/branch_list_builder.go:49 +0x577
github.com/jesseduffield/lazygit/pkg/commands.(*BranchListBuilder).Build(0xc0002d3950, 0xc0002d3a58, 0xc00035d340, 0xc000335940)
        /builddir/build/BUILD/lazygit-0.17.0/pkg/commands/branch_list_builder.go:98 +0x6b
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).refreshBranches.func1(0xc00027e000, 0xc0002d399c, 0x3)
        /builddir/build/BUILD/lazygit-0.17.0/pkg/gui/branches_panel.go:70 +0x52
github.com/jesseduffield/gocui.(*Gui).consumeevents(0xc00027e000, 0x0, 0x0)
        /builddir/go/pkg/mod/github.com/jesseduffield/gocui@v0.3.1-0.20200309001002-7765949e1c8a/gui.go:483 +0x1e8
github.com/jesseduffield/gocui.(*Gui).MainLoop(0xc00027e000, 0xc000000003, 0xc0002d3c88)
        /builddir/go/pkg/mod/github.com/jesseduffield/gocui@v0.3.1-0.20200309001002-7765949e1c8a/gui.go:465 +0x215
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).Run(0xc0000e8600, 0x0, 0x0)
        /builddir/build/BUILD/lazygit-0.17.0/pkg/gui/gui.go:1010 +0x626
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).RunWithSubprocesses(0xc0000e8600, 0x0, 0x0)
        /builddir/build/BUILD/lazygit-0.17.0/pkg/gui/gui.go:1019 +0x40
github.com/jesseduffield/lazygit/pkg/app.(*App).Run(0xc0001c2070, 0xc000100a00, 0xc0001c2070)
        /builddir/build/BUILD/lazygit-0.17.0/pkg/app/app.go:158 +0x6b
main.main()
        /builddir/build/BUILD/lazygit-0.17.0/main.go:67 +0x778
`

**Comment by jesseduffield** [comment]
Looks like this is due to changing how we fetch branches. Which version of git are you on? I'm using 2.21.0

**Comment by kirill-ratkin** [comment]
Hi.

> Tool is built from source: go get github.com/jesseduffield/lazygit
>Go version: go version go1.13.8 linux/amd64
>Git version: git version 1.8.3.1

This version came with CentOS 7 from base [repo](http://mirror.centos.org/centos/7/os/x86_64/Packages/git-1.8.3.1-20.el7.x86_64.rpm).

**Comment by awiller42** [comment]
I have encountered the same issue when executing lazygit without any arguments inside an existing git repository.
```
10:58 $ git --version
git version 2.11.0
```

```
10:59 $ ~/bin/lazygit --version
commit=91f6630907f25799bf30439d2306a06bdd798df2, build date=2020-03-22T10:36:29Z, build source=binaryRelease, version=0.17.3, os=linux, arch=amd64
```

**Comment by jesseduffield** [comment]
I've done some digging and it turns out that the way we fetch branches now isn't supported in old git versions. I've made a change in this [PR](https://github.com/jesseduffield/lazygit/pull/731) which uses some plumbing commands (as opposed to porcelain) to allow git versions above 2.0.0 to work (meaning it should work for you @awiller42), however even the plumbing commands of earlier versions lack the ability to do certain things we need to do.

Given version 1.8 is over six years old I think it's worth updating it to a later version @kirill-ratkin. Alternatively, an older version of lazygit which doesn't include the new functionality should work (perhaps v1.16 and below). I'm willing to consider the case for being backwards compatible for really old git versions but I don't think it will be easy to maintain the lazygit codebase if there's a heap of switching logic based on git version within the code.

**Comment by kirill-ratkin** [comment]
Ok. I agree with you. Version of 'git' in CentOS 7 is very old. 

I found guy (Artem Polishchuk <ego.cordatus@gmail.com>) who is maintiner of RPM package for CentOS/Fedora.

I'll inform him about issue for CentOS 7. I think he should stop publishing version which doesn't work with git version which is 'standard' for CentOS 7.

Yes. It's old version but RedHat doesn't update it for release 7. 
Release 8 includes newest version.

**Comment by tim77** [comment]
Dowgraded to `0.16.2` for CentOS 7. Please tell is it works for you?

**Comment by kirill-ratkin** [comment]
Thank you, Artem.

Yes. Version 0.16.2 in RPM works perfect!

**Comment by jesseduffield** [comment]
Good to hear you got it running @kirill-ratkin :) I'll close this issue as we now have a proper error message telling the user to update git when the version is under 2.0. We might add more backwards compatibility in the future if there is enough demand for it.
