### ISSUE TITLE
Cherry pick commits from another branch

### ISSUE THREAD

**Issue by durka** [jesseduffield/lazygit#720]
**Is your feature request related to a problem? Please describe.**
I want to be able to cherry-pick commits from another branch into the current one.

**Describe the solution you'd like**
When a branch is selected in the "Local Branches" pane, show *that branch's* commits in the Commits pane. Enable a subset of the keybindings so I'd be able to cherry-pick a commit from that list.

**Describe alternatives you've considered**
I think the only way to do it now would be to check out the other branch, copy the commit, check out back to original branch, and apply. I have like 100 commits to cherry-pick so that's not going to fly.

**Comment by jesseduffield** [comment]
@durka you can select multiple commits to cherry pick at once by pressing 'c' on each of them

**Comment by durka** [comment]
Oh, that's great. So I would only have to switch branches once. Is there a way to see the commit log for a branch that's not checked out?

**Comment by jesseduffield** [comment]
currently not, though I'm open to adding that as a feature. I'm not sure how best we would go about it. I don't want to automatically show all commits for a selected branch in the commits panel because it can be slow to load commits and I can imagine some awkward edge cases. Maybe pressing enter on a branch in the branch panel will take you to a list of its commits, shown in the same panel. That way it's clear that we're not talking about the checked out branch's commits.

**Comment by durka** [comment]
Replacing the branch panel could work, yeah!

**Comment by ceuk** [comment]
@durka @jesseduffield what about when you press enter on a branch name the git log on the right becomes a commit list you can interact with? Seems more consistent with other behaviour (e.g. staging hunks) and you don't lose your context that way either.

**Comment by jesseduffield** [comment]
This is now implemented on master! Hit 'enter' to see another branch's commits, then press 'c' to copy and 'v' back in the local commits context to paste (i.e. cherry-pick)

**Comment by edementyev** [comment]
Feature not working for me, I'm using lazygit 0.24.2 (AUR/stable) on Manjaro Linux
Steps to reproduce:
1) Checkout `master` branch
2) Go to other branch's commits, hit `c`
3) Go to `master` branch's commits and hit `v`
Nothing happens

**Comment by jesseduffield** [comment]
perhaps the commit’s code is already present in the destination graph? If thats the case we should probably notify the user

**Comment by edementyev** [comment]
Got it, I was able to paste selected commit in Commits (3rd) panel. But it doesn't work in Local Branches -> Commits (4th) panel. A bit confusing, but works nonetheless. Trying to get used to a new tool to integrate it into my workflow takes some time :)

**Comment by danielo515** [comment]
> Wasn't the case for me. I was able to paste selected commit in Commits (4th) panel. But it doesn't work in Local Branches -> Commits (3rd) panel. A bit confusing, but works nonetheless. Trying to get used to a new tool to integrate it into my workflow takes some time :)

Is it possible to "paste" commits into a branch that is not checked out? Like, I'm in the source branch, I want to cherry-pick from the last pane, go to the `Branches -> Commits` panel and then paste them there, without checking out.

**Comment by danielo515** [comment]
> I'm pretty sure it's not possible, though if it is possible with cli git it would be easy to implement in lazygit.

I think it is intentionally not possible in git cli

**Comment by jesseduffield** [comment]
doing some googling, you can use a hack of:
* spin up temp worktree
* check out the branch
* cherry pick the commits
* get back to the original worktree
* fast-forward the branch to the one from the worktree

Something like that. I wouldn't want to try doing that until we've got our worktree feature across the line though

**Comment by darkgraycat** [comment]
> Feature not working for me, I'm using lazygit 0.24.2 (AUR/stable) on Manjaro Linux Steps to reproduce:
> 
> 1. Checkout `master` branch
> 2. Go to other branch's commits, hit `c` on one commit, it gets highlighted
> 3. Go to `master` branch's commits and hit `v`
> 4. Nothing happens
> 
> Am I missing something?

Probably. What I did (and was succeeded):

1. Go to "Remotes" (left panel, 2nd window, 2nd tab)
2. Open branch you are looking for (title will change to something like "Commits (origin/feature-0000)")
3. Select commit and copy using "c"
4. Then press "l" to move to the next window (with Commits, Reflog tabs)
5. Press "v" to paste commit.

I hope it will help others.

**Comment by unikitty37** [comment]
It would really help if the README could document these steps. Not everybody learns best from videos, particularly when those videos:

* don't have any explanation (initial state, goals, actions being taken at each step)
* aren't all that clear where the start point is
* are just autoplaying GIFs with no pause button

Some paragraphs with static images would be _much_ easier to follow.
