### ISSUE TITLE
no key when trying to install ppa

### ISSUE THREAD

**Issue by pcause** [jesseduffield/lazygit#721]
On debian buster and tried to add the ppa repository.  Get a message there are no valid openpgp keys.  Can you fix so the app can be installed.  Thanks

**Comment by jesseduffield** [comment]
@dawidd6 would you know what's happening here?

**Comment by dawidd6** [comment]
PPAs are meant for Ubuntu, not for Debian.

**Comment by pcause** [comment]
is it possible to create a debian package you release.  packages seem available for other platforms.  Debian is the linux on chromebooks.

**Comment by dawidd6** [comment]
It is possible, but someone with interest needs to do this first.
