### ISSUE TITLE
Switching tabs in branch section and commits section

### ISSUE THREAD

**Issue by Steph2709** [jesseduffield/lazygit#727]
**Is your feature request related to a problem? Please describe.**
Keybinding to switch tabs isn't listed in keybindings leading users to be confused on how to do so. I only managed to know after reading the comments of another issue.

**Describe the solution you'd like**
List the keybinding on the help dialog or keybindings.

**Comment by jesseduffield** [comment]
there's a PR up for this but the author has been busy and needs to address changes https://github.com/jesseduffield/lazygit/pull/692

**Comment by jesseduffield** [comment]
fixed :)
