### ISSUE TITLE
Missing bold highlighting of selected items

### ISSUE THREAD

**Issue by Gugiman** [jesseduffield/lazygit#734]
**Describe the bug**
Scrolling through all kinds of items (staging, branches, commits etc...) there is no highlighting of the selected element.

**To Reproduce**
1. Open lazygit
2. Scrolling through items by arrowkeys or clicking directly

**Expected behavior**
Selected element should be highlighted by becoming bold.

**Screenshots**
You can see on the bottom right that item 4 of 30 is selected but not highlighted
![image](https://user-images.githubusercontent.com/5836639/77398124-31c23a80-6da7-11ea-913e-8e697d4fd555.png)

**Desktop (please complete the following information):**
 - OS: Kubuntu 18.04
 - Lazygit Version 0.17.4 and i think like 5 to 7 minor versions below

It worked before but at some update it went missing.

**Comment by jesseduffield** [comment]
@Gugiman do you see anything in bold inside lazygit? Also what terminal are you using?

**Comment by Gugiman** [comment]
Actually no
By clicking around a bit i can't find any bolded text.

I'm using /bin/bash/

It seems like bash lost the information how to bold...
Maybe globally so it would not be lazygits fault?

**Comment by jesseduffield** [comment]
that would be a relief on my end! haha. If you can't manage to get bold text in your terminal at all with /bin/bash I think that it is indeed not lazygit's fault

**Comment by Gugiman** [comment]
i tried to reset bash formatting with "tput init" but still no bolding.
Strange...
Any short ideas on this? Otherwise i will close the issue because of no issue of lazgit.

**Comment by jesseduffield** [comment]
sorry man, not too sure. Good luck on finding the solution though!

**Comment by Gugiman** [comment]
thanks :)

**Comment by band-a-prend** [comment]
I have another but slightly related problem.

I always use bold (Dejavu Sans Mono) font in my terminal (konsole) as more convenient style for me. So I can't distinguish selected item from others as they are all initially `bold` in terminal until I change preferences to use `book` font style.

Is it possible to set up specific color highlighting for selected item or for its background?
