### ISSUE TITLE
"amend commit with staged changes" opens rebase todo list

### ISSUE THREAD

**Issue by OliverJAsh** [jesseduffield/lazygit#736]
**Describe the bug**
"amend commit with staged changes" opens rebase todo list

**To Reproduce**
1. Stage some changes
2. In commits panel, activate command "amend commit with staged changes" (shortcut "A")

**Actual behavior**
Rebase todo list is opened in my editor. After I save and close, the commit is amended.

**Expected behavior**
Commit is immediately amended (todo list should not be opened).

It's annoying to have to save and close the todo list, and then refocus my terminal application.

If the todo list is intentionally opened so that users can make other changes, perhaps we could provide a separate command for that?

**Desktop (please complete the following information):**
 - OS: macOS latest
 - Lazygit Version: 0.15.7

**Additional context**
Interestingly, if I use the "amend last commit" command in the _files_ panel, the todo list is not opened.

**Comment by jesseduffield** [comment]
interesting. Which editor does the TODO file open in? Just thinking about how we'd get around this issue.

The reason why the commit amend works on the topmost commit is because we actually don't need to do an interactive rebase in that case, we just do a simple git commit --amend

**Comment by OliverJAsh** [comment]
It opens in VS Code which is the value of my `EDITOR` environment variable.

I just remembered that I have a git alias that does something similar to this:

```
[alias]
	fixit = "!f() { git commit --fixup=$1; GIT_EDITOR=: git rebase -i --autosquash $1~1; }; f"
```

This commands avoids the issue of having to open the editor by temporarily clearing the `GIT_EDITOR` environment variable. Maybe lazygit could do the same?

**Comment by jesseduffield** [comment]
would you be able to give this PR a go? https://github.com/jesseduffield/lazygit/pull/754

**Comment by OliverJAsh** [comment]
How do I build from source? I've currently got `lazygit` installed via Brew.

**Comment by jesseduffield** [comment]
you can clone the repo and at the root level do `go run main.go` or `go install && lazygit`

**Comment by OliverJAsh** [comment]
Hmm I can still reproduce (running against latest `master`).

**Comment by OliverJAsh** [comment]
Ah ignore me, it's because I was still running my global `lazygit` bin. It works now, thank you!

**Comment by jesseduffield** [comment]
no worries :)
