### ISSUE TITLE
fix build on aarch64

### ISSUE THREAD

**Issue by metalefty** [jesseduffield/lazygit#737]
Hi, are you interested in fixing build on aarch64?

A FreeBSD folk provided a patch to fix it:
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=245013

**Comment by dawidd6** [comment]
This patch seems to be taken from upstream `pty` package: https://github.com/creack/pty/pull/87

**Comment by dawidd6** [comment]
In fact I see that the only patch made to `pty` package by @jesseduffield in his fork is now present in upstream repo:

https://github.com/creack/pty/pull/71
https://github.com/jesseduffield/pty/compare/master...creack:master
https://github.com/creack/pty/compare/master...jesseduffield:master

So I guess we can switch to upstream now.
