### ISSUE TITLE
Centos Packages

### ISSUE THREAD

**Issue by jc21** [jesseduffield/lazygit#74]
This isn't an issue but more of an FYI.

I'm so impressed with this tool that I've created RPMs for Centos6 and Centos7 available on my public Yum repo: https://yum.jc21.com

For anyone interested, the RPM Spec file used is:

```
%global gh_commit   bc479a9bf5bee60cd3916b2c6d033ff266dfbd4d
%global gh_short    %(c=%{gh_commit}; echo ${c:0:7})

Name:           lazygit
Version:        0.1.25
Release:        1%{?dist}
Summary:        A simple terminal UI for git commands, written in Go with the gocui library.

Group:          Applications/System
License:        MIT
URL:            https://github.com/jesseduffield/lazygit
Source0:        https://github.com/jesseduffield/lazygit/archive/v%{version}.tar.gz

BuildRequires:  git golang

%description
Are YOU tired of typing every git command directly into the terminal, but you're too stubborn to use Sourcetree because you'll never forgive Atlassian for making Jira? This is the app for you!

%prep
mkdir -p %{_builddir}/src/github.com/lazygit/
cd %{_builddir}/src/github.com/lazygit/
tar -xvzf %{_sourcedir}/v%{version}.tar.gz
mv lazygit-%{version} lazygit
cd lazygit

%build
export GOPATH="%{_builddir}"
export PATH=$PATH:"%{_builddir}"/bin
go get -u github.com/golang/dep/cmd/dep
cd %{_builddir}/src/github.com/lazygit/lazygit
dep ensure
go build -i -v -ldflags "-X main.Rev=%{gh_short} -X main.builddate=`date -u +%Y%m%d.%H%M%S`"
go install

%install
mkdir -p %{buildroot}%{_bindir}

cp %{_builddir}/bin/lazygit %{buildroot}%{_bindir}


%files
%{_bindir}/lazygit

%changelog
* Thu Aug 9 2018 Jamie Curnow <jc@jc21.com> 0.1.25-1
- v0.1.25 with commit hash

* Wed Aug 8 2018 Jamie Curnow <jc@jc21.com> 0.1.11-1
- Initial Spec File
```

Source RPMs are also available on the Yum site. Although I haven't tested, I'm pretty sure this spec file could be used to compile for Fedora too.

UPDATE: spec file with commit hash

**Comment by jesseduffield** [comment]
rad work man! Would it be possible to bake in the git revision and build time into the application at build time? Similar to how we do when making binaries in Travis CI: `gox -os="linux darwin windows" -arch="amd64" -ldflags "-X main.Rev=`git rev-parse --short HEAD` -X main.builddate=`date -u +%Y%m%d.%H%M%S`" -verbose`
I just did some quick googling and it looks like you can send `-ldflags` to `go build` to bake in those variables, but I haven't tested it locally

**Comment by ponsfrilus** [comment]
@jesseduffield I have tested that which works as expected:
<pre>go build -i -v -ldflags "-X main.Rev=`git rev-parse --short HEAD` -X main.builddate=`date -u +%Y%m%d.%H%M%S`"</pre>

Maybe a Makefile will help everyone to use the same command ?

**Comment by jesseduffield** [comment]
@ponsfrilus that sounds like a good idea! As may already be apparent I'm very unfamiliar with the more devops side of things (I think that's the right word). Would you be able to chuck a PR up to that effect, or perhaps give some pointers?

Related to this thread: I'm thinking maybe we should chuck the release version number into those ldflags as well, because I'm currently displaying the git commit sha on the bottom right of the app but I think a version number would be more semantically obvious.

**Comment by ponsfrilus** [comment]
@jesseduffield not sure to have skill for that nor understand the whole taking and ending, especially I do not know how one can integrage the Makefile into a build process. But I've found https://vincent.bernat.im/en/blog/2017-makefile-build-golang and made some [comments](https://github.com/jesseduffield/lazygit/issues/76#issuecomment-411407542) that I hope will help.

It seems to me that the common usage is to generate a `version.go` file with relevant information to be used when automatic ones can not.

**Comment by jc21** [comment]
Is the point of your build command to have the variables of build time and commit available in the application?

Build time is easy but the commit hash isn't provided in the tgz file that Github provides when you create a new release. For now, I can supply the commit hash manually in the spec file and pass that through to the `go build` command

**Comment by jesseduffield** [comment]
@jc21 I've just made some changes to how releases go out, and the commit/version/build date should all appear when you call `lazygit -v` (just tested on my mac)

**Comment by fuero** [comment]
I've made a few adjustments:

```
%global gh_commit   ed6f21ee7437b4305c7048615eb218d2a2edeae2
%global gh_short    %(c=%{gh_commit}; echo ${c:0:7})

# see https://fedoraproject.org/wiki/PackagingDrafts/Go#Build_ID
%global _dwz_low_mem_die_limit 0
%if ! 0%{?gobuild:1}
%define gobuild(o:) go build -ldflags "${LDFLAGS:-} -B 0x$(head -c20 /dev/urandom|od -An -tx1|tr -d ' \\n') " -a -i -v -x %{?**};
%endif

Name:           lazygit
Version:        0.1.48
Release:        1%{?dist}
Summary:        A simple terminal UI for git commands, written in Go with the gocui library

Group:          Applications/System
License:        MIT
URL:            https://github.com/jesseduffield/%{name}
Source0:        https://github.com/jesseduffield/%{name}/archive/v%{version}.tar.gz

BuildRequires:  git golang

%description
Are YOU tired of typing every git command directly into the terminal, but
you're too stubborn to use Sourcetree because you'll never forgive Atlassian
for making Jira? This is the app for you!

%prep
%setup -q -n %{name}-%{version}
mkdir -p %{_builddir}/src/github.com/%{name}/
cd %{_builddir}/src/github.com/%{name}/
ln -snf %{_builddir}/%{name}-%{version} %{name}
cd %{name}

%build
export GOPATH="%{_builddir}"
export PATH=$PATH:"%{_builddir}"/bin
cd %{_builddir}/src/github.com/%{name}/%{name}
export LDFLAGS="${LDFLAGS} -X main.Rev=%{gh_short} -X main.builddate=$(date -u +%Y%m%d.%H%M%%S)"

%gobuild -o %{_builddir}/bin/%{name}

%install
install -Dm0755 %{_builddir}/bin/%{name} %{buildroot}%{_bindir}/%{name}

%files
%{_bindir}/%{name}
%doc LICENSE *.md docs/*.md

%changelog
* Fri Aug 10 2018 Robert Fuehricht <robert.fuehricht@jku.at> 0.1.48-1
- Version bump
- Proper escape of date format string for spec
- Removed dep as deps are vendored
- Adds documentation to package
- Use suggestions from Fedora's Go packaging guide

* Thu Aug 9 2018 Jamie Curnow <jc@jc21.com> 0.1.25-1
- v0.1.25 with commit hash

* Wed Aug 8 2018 Jamie Curnow <jc@jc21.com> 0.1.11-1
- Initial Spec File
```

**Comment by jc21** [comment]
Thanks @fuero, I've added those changes to my build.
There's only 1 minor thing I would suggest for the app, adding a new line to the output for the `-v` command ;)

```bash
[jc21@pc:~]$ lazygit -v
commit=1354885, build date=20180812.222849, version=0.1.55[jc21@pc:~]$
```

**Comment by jesseduffield** [comment]
@jc21 I just pushed a commit https://github.com/jesseduffield/lazygit/commit/1571e6b9623bffec6828319bc020ccf732a720a7 adding a newline :)

**Comment by jesseduffield** [comment]
closing as it looks like this issue is resolved
