### ISSUE TITLE
Slack: "This invite link is no longer active."

### ISSUE THREAD

**Issue by OliverJAsh** [jesseduffield/lazygit#741]
**Describe the bug**

**To Reproduce**
1. Click the Slack link in the `README.md` (https://join.slack.com/t/lazygit/shared_invite/enQtNDE3MjIwNTYyMDA0LTM3Yjk3NzdiYzhhNTA1YjM4Y2M4MWNmNDBkOTI0YTE4YjQ1ZmI2YWRhZTgwNjg2YzhhYjg3NDBlMmQyMTI5N2M)

**Expected behavior**
I can sign up.

**Screenshots**
![image](https://user-images.githubusercontent.com/921609/77536036-965ac380-6e93-11ea-9d4f-04ac76c72d92.png)

**Comment by jesseduffield** [comment]
should be fixed now :)
