### ISSUE TITLE
No changes displayed for files whose filenames contain umlauts

### ISSUE THREAD

**Issue by tagesmutter** [jesseduffield/lazygit#742]
**Describe the bug**
File names containing umlauts and most likely other unicode chars are not properly handled. While lazygit correctly displays them as modified in the "Files" panel, the changes are not displayed in the right panel for the file contents.

**To Reproduce**
Create a file with a german umlaut, french accent etc. and change it

**Expected behavior**
I'd love to see the changes in lazygit. My current workaround is to exit and lazygit and use "git diff" for those files.

**Desktop (please complete the following information):**
commit=c5ff39ba5f1331b45a868dd42bbfda8f972e4586, build date=2020-03-19T06:43:08Z, build source=binaryRelease, version=0.16.2, os=linux, arch=amd64

**Comment by glvr182** [comment]
try ` git config --global core.quotepath off`

**Comment by jesseduffield** [comment]
closing due to staleness but @tagesmutter let me know if you still have the issue
