### ISSUE TITLE
Git log - Full log and custom log formatting

### ISSUE THREAD

**Issue by mwebb387** [jesseduffield/lazygit#752]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to see the full git log somewhere (all branches) and also specify the format like I can in my `.gitconfig`.

**Describe the solution you'd like**
A new tab or option to show the full log in the main window instead of just the log for the current branch.

Also, maybe an option in the lazygit config either for the output formatting of the log or an option to turn on `--oneline` like in `git log` command.

**Describe alternatives you've considered**
I know I can execute a custom command with `:` and typing `git log --all --decorate --oneline --graph` (or related alias), but seeing this in the main UI would be great and much more seamless.

**Comment by OliverJAsh** [comment]
> an option to turn on `--oneline` like in `git log` command.

See https://github.com/jesseduffield/lazygit/pull/887#issuecomment-656619560

**Comment by jesseduffield** [comment]
I've updated the [docs](https://github.com/jesseduffield/lazygit/edit/master/docs/Config.md) to explain how to configure this, closing :)
