### ISSUE TITLE
shift+pgup / shift+pgdown exits lazygit

### ISSUE THREAD

**Issue by pkieltyka** [jesseduffield/lazygit#757]
I was hoping that Shift + PgUp / Shift + PgDown could be used to page scroll within the existing pane, such as paging through index of files.

**To Reproduce**
1. open lazygit
2. go to any pane such as "Files" where there is a large list of files in the pane
3. press shift+pgdown

at this point, lazygit will just exit.

**Expected behavior**
I was hoping it would page down the files, as the Page-Down key default is used to scroll the files contents (which is cool), still would be nice to page through the index.

**Desktop (please complete the following information):**
- OS: linux
- Lazygit commit version d1395b15bb980778b6a77cbc9c3f14775247aa8f

**Comment by pkieltyka** [comment]
after reading the keybinding options in https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md

I think the best would be to add new options as `pageUpItem` and `pageDownItem` similar to `prevItem` and `nextItem`. As well, I think "paging" in the main panel is very useful too, which could be named, `pageUpMain` and `pageDownMain` as a suggestion

**Comment by jesseduffield** [comment]
closing in favour of https://github.com/jesseduffield/lazygit/issues/656 (feel free to join the discussion there)
