### ISSUE TITLE
Ways to handle merge conflicts

### ISSUE THREAD

**Issue by OliverJAsh** [jesseduffield/lazygit#758]
**Is your feature request related to a problem? Please describe.**
When performing a merge and there are conflicts, you're left with a long list of files in the index. Buried within that list are the files with conflicts, but it's sometimes awkward to find them, especially when the list is very long.

**Describe the solution you'd like**
Any of these would be fine:
- Filter list by status (unmerged)
- Sort list by status, with unmerged at the top
- A way to run `git mergetool`

**Describe alternatives you've considered**

**Additional context**

**Comment by jesseduffield** [comment]
Having the unmerged files at the top definitely makes sense, as does the ability to run git merge tool

**Comment by jesseduffield** [comment]
https://github.com/jesseduffield/lazygit/pull/1197 places merge conflicts at the top

**Comment by OliverJAsh** [comment]
Does it do this for the flat list view as well as the tree view?

**Comment by jesseduffield** [comment]
@OliverJAsh nope, I considered that but I think it would be too awkward: we'd effectively need to show two different trees in order to do that. I've been trying it out myself and find it's easy to switch to flat mode when I've got contexts (just requires pressing the backtick key)

**Comment by jesseduffield** [comment]
@OliverJAsh hold up I misread your comment: I should clarify: the sorting _only_ occurs for the flat view, not for the tree view

**Comment by jesseduffield** [comment]
We can also run `git mergetool` now via the shift+M keybinding in the files panel. Closing, but let me know if I need to re-open
