### ISSUE TITLE
Mouse Support Windows Terminal

### ISSUE THREAD

**Issue by ueberBrot** [jesseduffield/lazygit#759]
**Describe the bug**
When trying to use the [basic mouse support](https://github.com/jesseduffield/lazygit/pull/529) with Cmd or Powershell in Windows Terminal it doesn't work. When using Cmd and Powershell as a stand-alone application the support works.

**To Reproduce**
Steps to reproduce the behaviour:
Use lazygit either with Cmd or Powershell inside a git repository from Windows Terminal.

**Expected behavior**
You should be able to use the mouse support the same way inside the Windows Terminal with Powershell or Cmd as with the stand-alone applications.

**Screenshots**
Expected using Powershell:
![Expected](https://user-images.githubusercontent.com/32489486/77770997-669fed00-7046-11ea-8420-6f368a54bd2d.gif)

Actual in Windows Terminal using Powershell:
![Actual](https://user-images.githubusercontent.com/32489486/77771129-964ef500-7046-11ea-93a7-331efd72d516.gif)

**Desktop and program versions:**
 - OS: Windows 10 Version 1909 (Build 18363.720)
 - Lazygit Version v0.18 (installed with scoop)
-  Windows Terminal Version: 0.10.781.0

If the issue is better suited in the Windows Terminal issues, let me know.

**Comment by jesseduffield** [comment]
I suspect this is an issue with the windows terminal itself. Do you have any examples of programs that have mouse support and work fine on windows terminal?

**Comment by ueberBrot** [comment]
> 
> 
> I suspect this is an issue with the windows terminal itself. Do you have any examples of programs that have mouse support and work fine on windows terminal?

I'm afraid not. The only thing I know  works with the mouse in Terminal and that I use is when you use `Ctrl+Mouse scroll`  you can increase or decrease the font size.

I just found out that Microsoft Terminal has only been supporting the mouse since release v0.10.761.0. In the release notes they state that they don't use the traditional Win32 API but instead use virtual terminal input? What ever that is.

From [Microsoft Terminal release page](https://github.com/microsoft/terminal/releases/tag/v0.10.761.0):
> - Mouse Support (for WSL and Windows applications using `ENABLE_VIRTUAL_TERMINAL_INPUT`) 
>    - Applications running in WSL and Windows applications that use VT (instead of the traditional Win32 API) can now request mouse mode (#4848) (#4856) (#4859)
>        - The set of supported encodings and events is identical to that of the traditional console host.

I do not know if that's the problem.

**Comment by ueberBrot** [comment]
Any update on this?

**Comment by billxc** [comment]
+1

**Comment by jesseduffield** [comment]
@ueberBrot sorry for late reply, it seems this is an issue for the windows terminal repo

**Comment by ueberBrot** [comment]
It seems this is a known issue (https://github.com/microsoft/terminal/issues/376)

**Comment by bin101** [comment]
@jesseduffield 
windows terminal currently doesn't support Win32 mouse input but it supports VT mouse input.

Maybe you can consider to support VT as well?

**Comment by bin101** [comment]
To inform you all:

This got fixed with Microsoft Terminal Preview 1.9.14450.0

**Comment by mjarkk** [comment]
Great, does that mean we can now close this issue?

**Comment by bin101** [comment]
Yes
