### ISSUE TITLE
Make it clear which keys open a menu and which do the action

### ISSUE THREAD

**Issue by NN---** [jesseduffield/lazygit#771]
**Is your feature request related to a problem? Please describe.**
```
r  refresh files
D  view reset options
```

It would be nice to add some visual difference between these kinds of commands.

**Describe the solution you'd like**
Suggest to use different colors and to add '...' for options opening menu.

```
r  refresh files
D  view reset options...
```
**Additional context**
Thanks for a great program !

**Comment by jesseduffield** [comment]
really good idea, I totally agree
