### ISSUE TITLE
Ask on quit

### ISSUE THREAD

**Issue by NN---** [jesseduffield/lazygit#772]
**Is your feature request related to a problem? Please describe.**
Escape simply closes lazy git without asking.

**Describe the solution you'd like**
Make it optional.
There is already 'q' to close lazygit.

**Comment by glvr182** [comment]
If i understand correctly, you want only the ESC button to have this behaviour? Not 'q'?

**Comment by NN---** [comment]
I don't mind if 'q' would ask too, but Esc is the most annoying :)

**Comment by glvr182** [comment]
in that case you can just add this to the config: `confirmonquit: true`. It's not nested so you dont have to indent anything / there is no special place for it

**Comment by NN---** [comment]
I’ll try. Thanks.

**Comment by glvr182** [comment]
Did it work? If so, I assume this issue can be closed?

**Comment by NN---** [comment]
Didn't try yet. Where exactly I put the configuration ?

**Comment by glvr182** [comment]
The config file should already be created in one of the following directories.
Windows: `C:\\Users\\<User>\\AppData\\Roaming\jesseduffield\lazygit\config.yaml`
Linux: `${HOME}/.config/jesseduffield/lazygit/config.yaml`
Mac: `${HOME}/Library/Application Support/jesseduffield/lazygit/config.yaml`

We use the following lib for this: [shibukawa/configdir](https://github.com/shibukawa/configdir)

**Comment by NN---** [comment]
In Windows a correct way is to use APPDATA environment.

```%APPDATA%\jesseduffield\lazygit```
Or
```%USERPROFILE%\AppData\Roaming\jesseduffield\lazygit```

Great. Thanx
