### ISSUE TITLE
(German) keyboard layout support

### ISSUE THREAD

**Issue by res1st** [jesseduffield/lazygit#773]
**Topic**
I have to use Windows at work and have a german keyboad layout.
lazy git doesn't werk very well with it, for example only the ] key works, but not [. In order to reach the [] keys, I have to additionally press the AltGr key. 
So I need lazy git with a different key mapping.

I've seen this topic for [Colemak ](https://github.com/jesseduffield/lazygit/pull/613) keyboard layout, but I didn't understand what I have to do to redefine the keys for a German keyboard layout.
Any hints would be helpful (or maybe someone already have a version for Germany keyboard layouts).

Ingo

**Comment by jesseduffield** [comment]
If you check out https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md you'll see the full list of keybindings. If you copy+paste those keybindings into your config file (which you can open via pressing 'o' on the status panel from inside lazygit) you can make whatever changes are necessary.  Lemme know if you need any pointers

**Comment by jesseduffield** [comment]
Closing due to staleness
