### ISSUE TITLE
Create a local branch when checking out remote branches

### ISSUE THREAD

**Issue by adwinying** [jesseduffield/lazygit#774]
**Is your feature request related to a problem? Please describe.**
When checking out remote branches I like to make a local branch to play around with it.

**Describe the solution you'd like**
When a remote branch is selected a single keypress (say `b`) would essentially run `git checkout -b [remote branch]`

**Describe alternatives you've considered**
Technically its possible to achieve the same result by checking out the remote branch and create a new local branch, but that's too much work and we're all lazy ;)

**Comment by jesseduffield** [comment]
This is now possible via the 'n' keybinding in the commit branches context :) closing.

Note to self: make this more obvious in our documentation. We really need a use-case based walkthrough page
