### ISSUE TITLE
Provide an option to pass `--work-tree` to git

### ISSUE THREAD

**Issue by GabrielDuarteM** [jesseduffield/lazygit#778]
**Is your feature request related to a problem? Please describe.**
I have a repo that I use to store my dotfiles, which is essentially a bare repo that I can use from anywhere just passing some arguments: `git --git-dir=$HOME/dotfiles/ --work-tree=$HOME`. `--git-dir` in this case is pointing to the bare repo (in this case, I think I could use the flag `--path` provided by lazygit), and `--work-tree` is pointing to my home folder, which is the root where I store the dotfiles (for more info, it is basically what is described in https://www.atlassian.com/git/tutorials/dotfiles).

So, TL;DR; Apparently, lazygit provides no way of configuring the --work-tree, so I can't use it on this repo.

**Describe the solution you'd like**
It would be nice to have either a specific config for this, like `--work-tree=$HOME` (same as was done on https://github.com/jesseduffield/lazygit/pull/414 with `--git-dir`), which would default to the git dir if you don't pass.
Another solution would be to have a config with a list of arguments to pass to git anytime lazygit calls it, like `--git-args="--work-tree=$HOME"`, and then lazygit would execute `git --work-tree=$HOME"`, instead of just `git`, which would make lazygit a lot more flexible.

**Describe alternatives you've considered**
None that I can think of, other than using just git directly

**Additional context**
N/A

What do you think?

**Comment by glvr182** [comment]
The --git-args flag sounds like a decent idea, this way we can avoid having a bunch of flags while still allowing users to use git's flags

**Comment by glvr182** [comment]
pinging @dawidd6 @jesseduffield @mjarkk for their input

**Comment by dawidd6** [comment]
I'm all in for `--work-tree` option, as I use this dotfiles management approach too, but what other options one would like to pass to every executed git command?

**Comment by glvr182** [comment]
Perhaps --exec-path or --namespace, but I think for now just adding --work-tree would be good enough

**Comment by jesseduffield** [comment]
I'm cool with a `--work-tree` option

**Comment by jesseduffield** [comment]
I've done some more digging and we're going to support the --git-dir and --work-tree args. I want to hold off on a generic --git-args option until we really need it: this particular issue requires some bespoke code and I get the feeling that may also be the case with other git args so supporting any random git args could mislead users.

At any rate I'm working on this feature now: https://github.com/jesseduffield/lazygit/pull/1023

**Comment by jesseduffield** [comment]
@GabrielDuarteM @80KiloMett @micmarty @sebastiangelotte @vbauerster could you give this [PR](https://github.com/jesseduffield/lazygit/pull/1023) a test? Should work fine when invoked like so:
```
lazygit --git-dir=$HOME/.cfg --work-tree=$HOME
```

**Comment by kguidonimartins** [comment]
Is there a way for lazygit to accept or read the local `--git-dir` settings, for example: `showUntrackedFiles = no`?

**Comment by jesseduffield** [comment]
@kguidonimartins that PR specifically checks the `showUntrackedFiles` arg so that should be fine. As for other settings, it might need to work on a case by case basis as often it's not as simple as just passing the arg through to git

**Comment by vbauerster** [comment]
Just tested #1023, looks like it's ok, haven't spot any issue.

**Comment by jesseduffield** [comment]
thanks @vbauerster , I'll close this issue for now and if you come across any issues feel free to comment them here

**Comment by Neurognostic** [comment]
@jesseduffield When using a bare repo the Status does not seem to be displaying correctly. 

1. Instead of the repo name (as defined by `--git-dir`) being displayed the name of the `--work-tree` directory is used.

2. The count of how many commits ahead or behind of origin displays as `↑?↓?` instead of the actual counts.

```shell
lazygit --git-dir=$XDG_DATA_HOME/dotfiles --work-tree=$HOME
```
![image](https://user-images.githubusercontent.com/23530447/97665616-861a5080-1a41-11eb-8bb2-730c212f816f.png)

```console
$ lazygit --version
commit=7c1889cd, build date=20201030.055210, build source=unknown, version=v0.23.6.7c
1889cd, os=linux, arch=amd64
```
