### ISSUE TITLE
Feature request/suggest commitizen friendly or commit message templates

### ISSUE THREAD

**Issue by fabianmoronzirfas** [jesseduffield/lazygit#78]
Great tool. I Really like it. If I had one wish (that had to included lazygit) it would be an integration with commitizen 
[commitizen/cz-cli: The commitizen command line utility.](https://github.com/commitizen/cz-cli). Or some kind of commit message templating to write better and more informative messages.

**Comment by ponsfrilus** [comment]
I think this issue is kind of a duplicate of:
  * Commitizen integration #41
  * Multiline commit messages #28 (for commit templates)

**Comment by fabianmoronzirfas** [comment]
Yes. That's true. I'll close this one
