### ISSUE TITLE
SSH passphrase causes display issue when fetching a remote branch

### ISSUE THREAD

**Issue by dhrrgn** [jesseduffield/lazygit#781]
**Describe the bug**
When your SSH key requires a passphrase, attempting to fetch a remote branch causes everything on the screen to shift up 1 line.

**To Reproduce**
1. Have an SSH key that requires a passphrase
2. Go to Remote Branches
3. Fetch the remote of a branch
4. Enter your passphrase, and press return

**Expected behavior**
After entering the SSH key passphrase, the remote branch is fetched, and the UI updates correctly.

**Screenshots**
![fetch-ssh-bug](https://user-images.githubusercontent.com/149921/78804516-36cddf00-798e-11ea-81ff-6f6e67b6fbf3.gif)

**Desktop (please complete the following information):**
 - OS: macOS 10.15.3
 - Lazygit Version: commit=3e36affa69f2f94fbb779931034b303ecacb1ee2, build date=2020-03-29T22:15:49Z, build source=binaryRelease, version=0.19, os=darwin, arch=amd64

**Additional context**
This may happen in other places, I did not do an exhaustive search

**Comment by jesseduffield** [comment]
@dhrrgn are you able to test https://github.com/jesseduffield/lazygit/pull/812 and verify that it solves your issue? I'm happy to help out if you need pointers for setting it up locally for test

**Comment by dhrrgn** [comment]
@jesseduffield Sorry for the delay. I will give this a shot tomorrow and report back.

**Comment by jesseduffield** [comment]
Should be fixed on master now. Let me know if it's not :) closing
