### ISSUE TITLE
Can we have a no-ff (non-fast forward) merge?

### ISSUE THREAD

**Issue by rayluo** [jesseduffield/lazygit#785]
**Is your feature request related to a problem? Please describe.**
Right now we have `M` to merge a highlighted branch into the checked-out branch, but it does a Fast-Forward. How can we set an option to do `--no-ff` instead?

**Describe the solution you'd like**
Either a configuration setting to go one way or another, or just provide a different key-binding.

**Describe alternatives you've considered**
None.

**Comment by jesseduffield** [comment]
I think this makes sense as a config option. Fixed in https://github.com/jesseduffield/lazygit/pull/797

**Comment by jesseduffield** [comment]
closing :)

**Comment by dancojocaru2000** [comment]
Is there a way to have multiple merge styles (`--no-ff` and `--ff-only`)?
