### ISSUE TITLE
Deleting branch don't have any effect

### ISSUE THREAD

**Issue by ogasimli** [jesseduffield/lazygit#787]
**Describe the bug**
Selecting branch clicking on `d` to delete the branch. After that i get confirmation prompt asking me if i am sure. I press `Enter` and prompt disappears but branch is still there.

**To Reproduce**
1. Go to Local Branches Panel
2. Click on a branch
3. Press `d` from keyboard
4. Press `Enter` after prompt window pops up

**Expected behavior**
Branch should be deleted and removed from Local Branches panel

**Desktop (please complete the following information):**
 - OS: `macOS Catalina 10.15.4`
 - Lazygit Version: `v0.19`

**Comment by glvr182** [comment]
I can't seem to reproduce this. What sort of prompts did you get?

**Comment by ogasimli** [comment]
I just figured out that it was actually removing the branches, but it was taking some time to delete it and reflect it on the UI. I was using lazygit in a very big monorepo.
