### ISSUE TITLE
Support running lazygit in submodules

### ISSUE THREAD

**Issue by vigoux** [jesseduffield/lazygit#789]
**Is your feature request related to a problem? Please describe.**
For now, when running lazy git I get the following :
```
*errors.errorString repository does not exist
/builddir/lazygit-0.17.2/main.go:74 (0xa9c5a9)
/usr/lib/go/src/runtime/proc.go:203 (0x436fe2)
/usr/lib/go/src/runtime/asm_amd64.s:1373 (0x464a61)
```
**Describe the solution you'd like**
Simply being able to use lazygit within a submodule would be great.

**Describe alternatives you've considered**
For now, I use the plain git command but for heavier editing I clone the repo elsewhere and work on it from here.

**Comment by vigoux** [comment]
Oh nevermind, that's actually a bug, I can't open lazygit when *inside* the submodule, but when using `lazygit -p submodule` then lazygit opens.

**Comment by jesseduffield** [comment]
hmm that's strange, I'm able to open lazygit in a submodule on my end. Could you provide an example of a public repo with a submodule for which lazygit won't open?

**Comment by vigoux** [comment]
Oh actually that's not exactly that, the problem is opening lazygit in a symlinked submodule.
It works fine using lazygit in "standard" submodules

**Comment by vigoux** [comment]
I just checked and the issue is still present when using latest version, here is an updated stack :
```
*errors.errorString repository does not exist
/builddir/lazygit-0.20.2/main.go:77 (0xaac002)
/usr/lib/go/src/runtime/proc.go:203 (0x4373c2)
        main: fn()
/usr/lib/go/src/runtime/asm_amd64.s:1373 (0x464c51)
        goexit: BYTE    $0x90   // NOP
```

**Comment by jesseduffield** [comment]
@vigoux (or @matejcik) could you see if https://github.com/jesseduffield/lazygit/pull/1024 fixes the issue on your end? It works for me when following @matejcik 's repro steps

**Comment by matejcik** [comment]
confirming that latest master does not have the issue
