### ISSUE TITLE
pulling from origin

### ISSUE THREAD

**Issue by ehamamrah** [jesseduffield/lazygit#79]
Hello, 

How to pull from the origin in a matter of merging? 
an example a branch hello-world is a branch from master
While I'm on hello-world how I can run git pull origin master?

**Comment by jesseduffield** [comment]
Currently the only way to do this is to checkout master, pull, then go back to your original branch and merge master. There is a feature request https://github.com/jesseduffield/lazygit/issues/52 to make this process easier

**Comment by ehamamrah** [comment]
@jesseduffield it would be great to have this feature.

**Comment by jesseduffield** [comment]
see my last comment here: this has now been implemented (let me know if the solution could be better though)
