### ISSUE TITLE
Problem with windows

### ISSUE THREAD

**Issue by snaildos** [jesseduffield/lazygit#791]
**Topic**
Hey there, So basically, Installed on windows with binary .exe file and put it in path, when running it, It just says: Not a repository, Create one? and then whenever i push y, or enter, It just exits?

**Your thoughts**
Can this be resolved?
Help appreciated :D

**Comment by glvr182** [comment]
What version of lazygit are you using?

**Comment by snaildos** [comment]
I have uninstalled this software due to some antivirus issues.
For your reference, it was the latest version.

**Comment by jesseduffield** [comment]
This is probably still a thing but I'm closing due to inability to reproduce. If somebody else has this issue and is willing to troubleshoot we can reopen

**Comment by snaildos** [comment]
It was interesting, This seemed to be a virus...?

**Comment by trinityzhub** [comment]
My Bitdefender blocked lazygit application in Windows 11,
Last alert happened  when i clicked on git submodule .


Is it just an suspicious activity or  should i careful ?
Can i get any expert opinion on this ? please ?



Last Alert:

```
Malicious behavior blocked
3 minutes ago

Feature:
Advanced Threat Defense

Bitdefender detected potentially malicious behavior and blocked all applications involved.
Detection ID: SuspiciousBehavior.30EFXXXXXXXXD2

```



Third Alert: 
```
Infected item detected
4 minutes ago

Feature:
Antivirus

Bitdefender moved a threat to quarantine. File name: C:\Users\XXXX\AppData\Local\lazygit\state.yml. It is recommended that you run a System Scan to make sure your system is cle

```

Second alert

```
Infected item detected
5 minutes ago

Feature:
Antivirus

Bitdefender moved a threat to quarantine. File name: C:\Users\XXX\AppData\Local\Temp\lazygit-XXXX. It is recommended that you run a System Scan to make sure your system is cle
```

First alert

```
Infected item detected
4 minutes ago

Feature:
Antivirus

Bitdefender moved a threat to quarantine. File name: C:\Users\XXX\AppData\Local\Microsoft\WinGet\Packages\JesseDuffield.lazygit_Microsoft.Winget.Source_8weXXXXXX\lazygit.exe. It is recommended that you run a System Scan to make sure your system is clea

```

**Comment by insane-dreamer** [comment]
Just had this happen to me as well. 

```
❯ lazygit --version
commit=d167063b4f45d044524f3fba97f850d1eec3f95c, build date=2026-04-13T20:06:40Z, build source=binaryRelease, version=0.61.1, os=windows, arch=amd64, git version=2.50.1.windows.1
```
