### ISSUE TITLE
Too easy to accidentally delete work. Add confirm prompt?

### ISSUE THREAD

**Issue by OliverJAsh** [jesseduffield/lazygit#792]
Could we add a confirm prompt to the `d` command (discard changes)? I just lost some work by accidentally pressing it :cry:

**Comment by tmartty** [comment]
+1

**Comment by mjarkk** [comment]
agree, i'v had multiple times where lazygit was focused but i thought it was my text editor and when i started typing lazygit ran all the keybindings

**Comment by OliverJAsh** [comment]
Also I've made the mistake of accidentally popping a stash, which resulted in conflicts with changes in my index, and then there's no way to undo—you're forced to undo the conflicts.

**Comment by jesseduffield** [comment]
We actually had a confirmation prompt already for deleting stuff in the staging panel but the check accidentally was checking for the opposite of the thing we cared about so I've fixed that on master. Wrt unstashing, I think this should be behind a config flag as well, which defaults to the unsafe form

**Comment by jesseduffield** [comment]
got a PR up now: https://github.com/jesseduffield/lazygit/pull/798

I'm willing to consider making it default behaviour to show the warning, but I'm currently thinking not to.

**Comment by jesseduffield** [comment]
this is in release v0.20. I'll close the issue, but if you have any more problems lemme know!
