### ISSUE TITLE
git flow bugfix

### ISSUE THREAD

**Issue by tmartty** [jesseduffield/lazygit#793]
**Is your feature request related to a problem? Please describe.**
Git flow offers the bugfix flow, which is basically the same as a feature branch but with a different prefix I think?

**Describe the solution you'd like**
Possibility to create a bugfix branch from the menu as we do with features and hotfixs

**Describe alternatives you've considered**
Just using a feature branch, but it's less legible and consistent.

**Additional context**
Please? :D

**Comment by jesseduffield** [comment]
@tmartty I've got a PR up now
