### ISSUE TITLE
put a jar file run on it

### ISSUE THREAD

**Issue by happysmile12321** [jesseduffield/lazygit#794]
I just want it manage my java program.So is it a possible for you to develop an application also use gocui,and it can run jar file.I am family with Java,but I also very like this command line tool.But it written with Go,I am hard to hacking it.
Here is my idea.User can put a jar on their own github repository.And this software could pull those jar,using git all features,to run the jar on command line.

**Comment by jesseduffield** [comment]
lazygit compiles to an executable binary. Are you suggesting to rewrite the program in java?

**Comment by happysmile12321** [comment]
lazygit pull jar package from github,then I can press some key to run it on lazygit.

**Comment by jesseduffield** [comment]
I believe jar packages can only be made from java files, but lazygit only uses go files.

**Comment by happysmile12321** [comment]
ok.thanks.

**Comment by jesseduffield** [comment]
closing :)
