### ISSUE TITLE
0.20 on Windows 10 2004: Error on Start

### ISSUE THREAD

**Issue by PGScully** [jesseduffield/lazygit#804]
**Describe the bug**
lazygit fails to start, showing the following message:

> While parsing config: yaml: line 4: found unexpected end of stream

**To Reproduce**
1. Type lazygit at the command line
2. See error

**Expected behavior**
lazygit starts

**Screenshots**
> C:\Users\peter>lazygit
> 2020/04/21 12:52:18 While parsing config: yaml: line 4: found unexpected end of stream

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 2004
 - Lazygit Version:

> C:\Users\peter>lazygit --version
> commit=f05a5e531ee8271e0232db7f3bb7202ea550656e, build date=2020-04-20T09:02:42Z, build source=binaryRelease, version=0.20, os=windows, arch=amd64

**Additional context**
I've updated both windows 10 and lazygit since I last used lazygit on this machine.

It doesn't seem to matter what's in lazygit's config file, or even if it exists at all.  I get the same error message with my normal config file (2 entries/lines), no config file, or the output of lazygit -c copied into the config file.

It doesn't matter if I'm in a git directory or not.

Downgrading back to 0.19 works fine.

**Comment by superudo** [comment]
I confirm this behavior.

**Comment by glvr182** [comment]
There is a yaml error in config_windows.go
```
// GetPlatformDefaultConfig gets the defaults for the platform
func GetPlatformDefaultConfig() []byte {
	return []byte(
		`os:
  openCommand: 'cmd /c "start "" {{filename}}"'
  openLinkCommand: 'cmd /c "start "" {{link}}"'
  copyToClipboardCommand: 'cmd \c "echo -n {{str}} > /dev/clipboard"`)
}

```

**Comment by glvr182** [comment]
PR is up, but you can fix it yourself by creating a config file and adding this:
```
os:
  copyToClipboardCommand: 'cmd \c "echo -n {{str}} > /dev/clipboard"'
```
