### ISSUE TITLE
Error when pushing over HTTPS

### ISSUE THREAD

**Issue by jonesdev** [jesseduffield/lazygit#81]
When attempting to push over HTTPS, lazygit will ask for a Username but will not allow you to input one.

Pressing Esc / Enter does not close the prompt or cancel the push process.

![image](https://user-images.githubusercontent.com/36740276/43834260-656e8f8a-9b05-11e8-8406-754bfb3d018d.png)

**Comment by jesseduffield** [comment]
Looks like a general issue right now is knowing when a subprocess is asking for user input. Do you (or anybody) know if there's some way to know ahead of time that your password will be asked for? If so we can run that push as a subprocess and then switch back to the application afterwards. The next best thing is to just read what's in that panel and if it has the word 'Username' in it, we'll cancel the push, then restart it as a subprocess.

**Comment by 0xphk** [comment]
Same happens here when trying to pull from password protected repository, no way to enter password, killing process is the only way out. So the filter should to look for 'password' as well.

There are different pinentry tools out, some work well for ncurses, maybe this could help solve it.

**Comment by kristijanhusak** [comment]
I think what @glvr182 would work. Basically just check the remote url of the repository, and depending on that prompt for password.

**Comment by mjarkk** [comment]
@jesseduffield This issue can now be closed

**Comment by kristijanhusak** [comment]
@mjarkk great job, this works greate.

**Comment by jesseduffield** [comment]
Big thanks to @mjarkk for the feature! Closing
