### ISSUE TITLE
Are u planing to support 2FA ?

### ISSUE THREAD

**Issue by its0x08** [jesseduffield/lazygit#816]
I tried to use lazygit to manage my repo. Was about to PUSH and it asked me for login creds.
Then it said that my creds were not correct!!

I'd like to for the tool to have 2FA support!
Thank you.

**Comment by its0x08** [comment]
It says  _Password and/or username wrong_ and booth are right because I use password manager which In browser logs me in but in lazygit it doesnt.

**Comment by jesseduffield** [comment]
Could you give a description of what you'd like to see lazygit do in this situation?

**Comment by its0x08** [comment]
Well I have 2FA active on my account therefore I cannot login at all through lazygit!!

**Comment by jesseduffield** [comment]
Apologies for not being well-versed on the 2FA side of things. Would you expect lazygit to open a browser window as well to log you in, in the same way your password manager does?

**Comment by its0x08** [comment]
Sure, not a single problem !
👍🏻
