### ISSUE TITLE
[enhancement] avoid unnecessary refresh when same panel or item clicked

### ISSUE THREAD

**Issue by 52tt** [jesseduffield/lazygit#819]
I realized that when I mouse clicked on same panel or item, the right side panel is refreshed and shows same content. (For example, click "Files" or  "Local Branches" panel blank space, or click an item in the "Local Branches" panel). This seems to be not really necessary and can be optimized to avoid.
Thanks.

**Comment by jesseduffield** [comment]
This is fixed in https://github.com/jesseduffield/lazygit/pull/1217
