### ISSUE TITLE
Homebrew Tap

### ISSUE THREAD

**Issue by jesseduffield** [jesseduffield/lazygit#82]
I switched to using goreleaser, and got the binaries building but I can't get the homebrew tap part working. It looks like I might need to have a separate repo for the homebrew thing? If anybody could have a look at https://github.com/jesseduffield/lazygit/blob/master/.goreleaser.yml and let me know if something looks off that would be fantastic.

Last bit of the log file:

```
   • RELEASING TO GITHUB
      • creating or updating release repo=jesseduffield/lazygit tag=v0.1.25
      • release updated           url=https://github.com/jesseduffield/lazygit/releases/tag/v0.1.25
      • uploading to release      file=dist/checksums.txt name=checksums.txt
      • uploading to release      file=dist/lazygit_0.1.25_Darwin_x86_64.tar.gz name=lazygit_0.1.25_Darwin_x86_64.tar.gz
      • uploading to release      file=dist/lazygit_0.1.25_freebsd_armv6.tar.gz name=lazygit_0.1.25_freebsd_armv6.tar.gz
      • uploading to release      file=dist/lazygit_0.1.25_Linux_x86_64.tar.gz name=lazygit_0.1.25_Linux_x86_64.tar.gz
      • uploading to release      file=dist/lazygit_0.1.25_Linux_armv6.tar.gz name=lazygit_0.1.25_Linux_armv6.tar.gz
      • uploading to release      file=dist/lazygit_0.1.25_freebsd_x86_64.tar.gz name=lazygit_0.1.25_freebsd_x86_64.tar.gz
      • uploading to release      file=dist/lazygit_0.1.25_Windows_x86_64.tar.gz name=lazygit_0.1.25_Windows_x86_64.tar.gz
      • uploading to release      file=dist/lazygit_0.1.25_Linux_arm64.tar.gz name=lazygit_0.1.25_Linux_arm64.tar.gz
   ⨯ release failed after 7.76s error=Post https://uploads.github.com/repos/jesseduffield/lazygit/releases/12309362/assets?name=checksums.txt: dial tcp: lookup uploads.github.com on 192.168.2.1:53: no such host
```

**Comment by jesseduffield** [comment]
@dawidd6 You may be able to help here

**Comment by dawidd6** [comment]
First i would change `brew` to `release`, cause we don't deal with any homebrew stuff here.

**Comment by jesseduffield** [comment]
Nice catch :) I removed the token from my account so it's harmless sitting in the repo's git history. I want to support homebrew because it's our most popular issue https://github.com/jesseduffield/lazygit/issues/14. Goreleaser has native support for homebrew tap stuff so I wanted to use that, and it's easier to specify what you want in the .yml. I think I still want to be using travis CI, but in a way that integrates with goreleaser, so I'll add travis CI back soon.

One of the benefits of goreleaser is that it handles automatic tarballing, zipping etc of the binaries, and packages them with the license and readme which was pretty cool. It also has the lazygit executable as-is, meaning it doesn't need to be renamed as was the case previously with the travis CI script.

My plan is to get goreleaser working with homebrew and then move it into travis CI. But I'm also very tired so I'll probably need to revise the logic of my current thinking haha.

**Comment by dawidd6** [comment]
Ah okay, good plan, but i can't help here as i'm not familiar with homebrew.

**Comment by andrewgy8** [comment]
@jesseduffield  I see you have arm64 declared twice on line 12 + 14. Im not sure if thats whats causing your issue. but perhaps it might be easier to debug this if we start with just one platform, say MacOSx and then moved on from there.

**Comment by jesseduffield** [comment]
Turns out I needed to add a separate repo to host the formula file (at least that's what my research told me). Nonetheless, we now have a homebrew tap!
