### ISSUE TITLE
lazygit exits randomly when scrolling through commit's patch pane

### ISSUE THREAD

**Issue by senotrusov** [jesseduffield/lazygit#820]
**Describe the bug**
lazygit randomly exits when scrolling through commit's patch pane.

**To Reproduce**
1. Select a big enough commit
2. Scroll through commit's patch pane up and down multiple times

**Expected behavior**
lazygit should not exit

**Desktop (please complete the following information):**
 - OS: MacOS Catalina, native terminal
 - Lazygit Version commit=, build date=2020-04-23, build source=debian, version=0.20.2, os=linux, arch=amd64
 - I ssh to a linux box (ubuntu 18.04 LTS) and run lazygit there

**Comment by sballin** [comment]
I was encountering this bug on 0.20.x from Homebrew. Upgraded to 0.22.9. On my Mac with iTerm2 and zsh, it appears to be completely fixed. On a remote server running zsh or bash on Ubuntu, it seems to be a little better for careful scrolling, but if I let the scroll wheel fly, it still crashes and the prompt has output like the following:

    64;85;23M64;85;23M64;85;23M64;85;23M64;85;23M64;85;23M64;85;23M64;85;23M

**Comment by jesseduffield** [comment]
@sballin is the remote server on 0.22.9 as well? If the server has go installed you can try out https://github.com/jesseduffield/lazygit/pull/1035 where I've got some more improvements to the stability of that feature

**Comment by sballin** [comment]
Yes, the one on the remote server is "version=0.22.9, os=linux, arch=amd64". I tried accessing the server with NoMachine (remote desktop program) and lazygit with the Ubuntu terminal was bug-free. But it still happens when running over ssh. I also tried Terminal.app instead of iTerm2 to do the ssh, but it didn't help.

**Comment by jesseduffield** [comment]
snap. Was there any stack trace outputted? I've had the same issue and often after the fact I can't scroll so to get the stack trace (assuming there is one and it continues off-screen) I need to copy everything from the terminal buffer into my editor.

**Comment by sballin** [comment]
I don't see any stack trace... near the top of the terminal, I see the lazygit interface the way it looked right before the crash

**Comment by sballin** [comment]
I think this is related to issue https://github.com/jesseduffield/lazygit/issues/622. When I set `quitOnTopLevelReturn: false` and do a big scroll, it doesn't quit anymore but seems to cycle through the various panes in lazygit and sometimes there's an error popup that says "You cannot merge a branch into itself".

**Comment by jesseduffield** [comment]
@senotrusov  @sballin could you try this again on the latest release?

**Comment by sballin** [comment]
Seems to be fixed! Thanks for the great work!

**Comment by jesseduffield** [comment]
no worries :) closing
