### ISSUE TITLE
Options for non-git folders

### ISSUE THREAD

**Issue by MuratUrsavas** [jesseduffield/lazygit#822]
As of right now, if I run lazygit in a non-git folder, it gives an error like below and exits.

```
2020/04/29 11:23:26 An error occurred! Please create an issue at https://github.com/jesseduffield/lazygit/issues

*errors.errorString fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).

github.com/jesseduffield/lazygit/pkg/commands/os.go:186 (0xa53974)
github.com/jesseduffield/lazygit/pkg/commands/os.go:97 (0xa52f54)
github.com/jesseduffield/lazygit/pkg/commands/os.go:152 (0xadd04e)
github.com/jesseduffield/lazygit/pkg/commands/os.go:152 (0xadd01f)
github.com/jesseduffield/lazygit/pkg/app/app.go:116 (0xadcd49)
github.com/jesseduffield/lazygit/main.go:67 (0xade3e6)
/usr/lib/go-1.12/src/runtime/proc.go:200 (0x42f43c)
/usr/lib/go-1.12/src/runtime/asm_amd64.s:1337 (0x45a521)
```
For me, realizing what I've done is easy. But for a newcomer this could be a little bit scary.

What about changing this behavior to "opening lazygit with default options":
Showing recent repos in addition to "Create new repo at here" and "Clone a repo" options. Wouldn't that be nicer?

Since lazygit already keeps track of recent folders, implementing this feature should be very easy. And it could make this neat piece of software also looking good for newbies.

Regards,

**Comment by jesseduffield** [comment]
Totally agree. Fixed in https://github.com/jesseduffield/lazygit/pull/937
