### ISSUE TITLE
View modifed files on merged commits

### ISSUE THREAD

**Issue by nartc** [jesseduffield/lazygit#824]
![image](https://user-images.githubusercontent.com/25516557/80820039-c59fd700-8b9b-11ea-9919-1a73c5b0eb35.png)
Is it possible to view modified files on merged commits like this one?

**Comment by jesseduffield** [comment]
Closing due to staleness, but let me know if you still have the issue :)

**Comment by apazzolini** [comment]
Hi @jesseduffield - I'm also running into this (version 0.24.2, commit=d7c924). 

When I run `git show some-sha`, I get output similar to nartc's screenshot above. When I run `git show -m some-sha`, the diff of the files in the merge are visible. 

Is there a way to configure lazygit to forward the `-m` flag to `git show`? I didn't see an option in https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md for it.
