### ISSUE TITLE
Support for Chocolatey

### ISSUE THREAD

**Issue by tupaschoal** [jesseduffield/lazygit#827]
**Topic**
Lazygit installation on Windows is currently provided via `scoop`. I wonder if it'd be possible to also have it on [Choco](https://github.com/chocolatey/choco)

**Your thoughts**
Chocolatey is not as starred as `scoop` but it has gained some traction and I think having `lazygit` there as well would expand its usage, if it isn't too much of a hassle

**Comment by jawn** [comment]
It seems there is a Chocolatey package for lazygit. https://chocolatey.org/packages/lazygit

However, the version number seems outdated.

**Comment by jesseduffield** [comment]
@jeremyben is this Chocolatey package automatically version-bumped?

**Comment by nils-a** [comment]
@jesseduffield fyi: I have asked to be made co-maintainer for the package @ chocolatey. When I am added there, I will enable automatic updates for that package as soon as possible.

**Comment by nils-a** [comment]
I am added as a maintainer and are now able to push a new version.
However - I got questions:

## Icon
The current package icon points to [a screenshot](https://rawcdn.githack.com/jesseduffield/lazygit/25c93c678d0c198ef1610ec9d8743d8ae1e81a84/docs/resources/viewing-commit-diffs.png) and look like this:
![image](https://user-images.githubusercontent.com/349188/99513883-66fd4780-298b-11eb-9575-6102da069e75.png)

Is that ok, or should we change that?
Maybe to something like this:
![image](https://user-images.githubusercontent.com/349188/99515387-2e5e6d80-298d-11eb-9ee2-19b971ce18a5.png)
(Quickly pasted together, I'm not an artist. Sorry.)

## Documentation
The current package documentation points to [keybindings](https://github.com/jesseduffield/lazygit/blob/master/docs/keybindings/Keybindings_en.md).

I'd suggest to let it point to the [docs folder](https://github.com/jesseduffield/lazygit/blob/master/docs/) and - as a second step add a `readme.md` to that folder giving some overview on the documentation.

## Description
The current description is as follows:

>Are YOU tired of typing every git command directly into the terminal, but you're
>too stubborn to use Sourcetree because you'll never forgive Atlassian for making
>Jira? This is the app for you!
>
>## Usage
>Call `lazygit` in your terminal inside a git repository.
>
>## Cool features
>* Adding files easily
>* Resolving merge conflicts
>* Easily check out recent branches
>* Scroll through logs/diffs of branches/commits/stash
>* Quick pushing/pulling
>* Squash down and rename commits

Id that ok for you? Or should we update that to something from the `readme`?
Something like:
>A simple terminal UI for git commands, written in Go with the gocui library.
>
>If you're a mere mortal like me and you're tired of hearing how powerful git is when in your daily life it's a powerful pain in your ass, lazygit might be for you.

**Comment by nils-a** [comment]
The new package is submitted, see https://chocolatey.org/packages/lazygit/0.23.7

While the package is still in moderation (and probably for some time) it can still be installed using `choco install lazygit --version=0.23.7`

**Comment by MathiasLui** [comment]
> [@jesseduffield](https://github.com/jesseduffield) fyi: I have asked to be made co-maintainer for the package @ chocolatey. When I am added there, I will enable automatic updates for that package as soon as possible.

Were automatic Chocolatey package updates implemented? Because I fetched the newest version from Chocolatey and got 0.61.1 (~3 months old) and using the built-in update functionality results in this:  

<img width="809" height="87" alt="Image" src="https://github.com/user-attachments/assets/0b2a3653-1921-47f7-8b40-f54469a9a0ef" />
