### ISSUE TITLE
Discarding rename changes

### ISSUE THREAD

**Issue by fsmiamoto** [jesseduffield/lazygit#830]
**Topic**
Currently, whenever a rename change is discarded we get an error:
![Discarding a rename change](https://user-images.githubusercontent.com/20388082/81355843-1769c500-90a6-11ea-8f13-960826a665ac.png)

**Your thoughts**
I think it would be reasonable to revert the rename with something like this:
```sh
$ git mv file.renamed.txt file.txt
```

Any thoughts?

**Comment by jesseduffield** [comment]
Just confirmed locally. Let's see what we can do

**Comment by jesseduffield** [comment]
Should be fixed in https://github.com/jesseduffield/lazygit/pull/915 :)

**Comment by fsmiamoto** [comment]
@jesseduffield Sorry for the late response but thanks for the fix!
