### ISSUE TITLE
Any reason why keybindings wouldn't fully work on OSX?

### ISSUE THREAD

**Issue by colemars** [jesseduffield/lazygit#834]
This is the second Macbook I've had that only supports some of the keybindings.

Can't find any discussions on it.

**Comment by jesseduffield** [comment]
which keybindings are you having trouble with?

**Comment by colemars** [comment]
Sorry for the late response.

I was confused and assumed the keyboard shortcuts would work while the menu was open displaying them. They work just fine with the menu closed.
