### ISSUE TITLE
Banning users to ignore the "gitignore" file?

### ISSUE THREAD

**Issue by theniceboy** [jesseduffield/lazygit#839]
**Topic**
Ignoring the `.gitignore` file is a paradox. Currently, users can ignore the `.gitignore` file (if they have just created it), and this can cause confusion.

**Your thoughts**
I think on the `files` panel, lazygit should check if the cursor is on the `.gitignore` file and prevent the users from pressing `i` (or whatever they have bind it to) to ignore.

This happens very rarely, but it's a possible case.

**Comment by jesseduffield** [comment]
yeah I think that makes sense
