### ISSUE TITLE
Provide option to turn off the full mouse support

### ISSUE THREAD

**Issue by sebi88** [jesseduffield/lazygit#841]
**Is your feature request related to a problem? Please describe.**
A few months ago mouse support was introduced. I can imagine, that it's useful for a lot of people, but I prefer to keep it off for copying text from the console instead

**Describe the solution you'd like**
a property in my home folder would be nice

**Additional context**
Lazygit version: 0.20.3
Linux version: Linux Mint 19.3 Tricia

**Comment by mjarkk** [comment]
Good news this is possible!  
In the status panel press <kbd>e</kbd> to edit the lazygit config,  
Then change this in the config:  
```yaml
  gui:
    mouseEvents: false
```
There are lots more settings that you can find here: [/docs/Config.md](https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md)

**Comment by jesseduffield** [comment]
@mjarkk beat me to it haha

**Comment by sebi88** [comment]
soo cool, thx!
