### ISSUE TITLE
Deleting branches created from a remote doesn't seem to work

### ISSUE THREAD

**Issue by peppy** [jesseduffield/lazygit#848]
Hopefully not something specific to my configuration (I've tested on two repos)

Steps:

- Go to a remote
- Hit space to checkout a branch
- Hit n to create a new tracking branch
- Checkout master
- Try to delete the newly created tracking branch

![image](https://user-images.githubusercontent.com/191335/82149071-1b10ff00-9891-11ea-9381-69f544ca66b7.gif)

**Comment by jesseduffield** [comment]
hmm I'll do some investigation

**Comment by peppy** [comment]
I can confirm this happens on a fresh clone with no local gitconfig, for what it's worth:

```
git clone https://github.com/ppy/osu-framework;
cd osu-framework;
git remote add smoogipoo https://github.com/smoogipoo/osu-framework;
git fetch --all;
```

then repro using above steps.

It seems like it might be related to lazygit showing `heads/smoogipoo/jetbrains-a` in the brnches list while `git branch` shows `smoogipoo/jetbrains-a`.

**Comment by jesseduffield** [comment]
@peppy I've chucked up a PR to resolve this https://github.com/jesseduffield/lazygit/pull/849. Let me know if that fixes the issue for you. I'm also interested in knowing more of the use case: is the intention to be able to make a copy of a remote branch locally, with the intention of then pushing that branch to origin?

**Comment by peppy** [comment]
My intention here was to create a local tracking branch, which I am probably going about incorrectly judging by your question! When pushing, I would hope my changes go to the remote I created the branch from.

**Comment by jesseduffield** [comment]
I suspected that was the case! Yeah, when you create a new branch from the remote it will just copy the name over but it won't have any tracking information pointing it at the remote branch. 
I'm thinking maybe we should, instead of going `git checkout remote/branchname` to checkout the branch in the first place (which leaves us with a detached head), go `git checkout -b remote/branchname remote/branchname) which will leave us with a local branch that tracks the remote branch.

The only question is whether other people were depending on this previous logic. I have a suspicion that they weren't, given I can't really think of any good use case for it.

**Comment by jesseduffield** [comment]
actually I just realised that the 'c' keybinding isn't being used for remote branches, so we could use that, and leave 'space' for checking out the commit in a detached head state. Wonder if that would be intuitive though.

**Comment by jesseduffield** [comment]
the 'n' keybinding could be used to create a new local branch from a remote branch but that's not quite the same as creating a new remote branch (that may actually be impossible in git). But it would be closer in meaning to what we currently do with the 'n' keybinding in the branches panel given that we're going `git checkout -b` either way. I like the idea of the 'n' keybinding.

**Comment by jesseduffield** [comment]
I've added the 'n' keybinding to the PR which will directly create a local branch from the remote one and it'll have tracking setup for you :)

**Comment by peppy** [comment]
Aha, I see. Personally I *do* use space to do a detached checkout (for cases where I don't need the local branch) so I appreciate leaving that intact.

I can see some scenarios where leaving it the way it is (not automatically tracking when performing a `new branch` op from a detached head) may actually be what people want. I will be content as long as there is a defined method to checkout w/local tracking branch directly from the `remote>branches` list.

**Comment by jesseduffield** [comment]
Sweet. I've left the space keybinding alone and I've added the 'n' keybinding for the use case you describe. Feel free to give it a test at https://github.com/jesseduffield/lazygit/pull/849
