### ISSUE TITLE
Scroll location unreliable when selecting conflicting hunks

### ISSUE THREAD

**Issue by peppy** [jesseduffield/lazygit#850]
When the conflict you are trying to select is not on the current screen, using up and down arrows to switch between hunks doesn't correctly scroll them into view always.

![image](https://user-images.githubusercontent.com/191335/82279853-74c81500-99c8-11ea-8e73-05753a309fd2.gif)

Using pagedn confirms that the selection does update correctly, so just seems to be a scroll target issue.

**Comment by jesseduffield** [comment]
I'll take a look at this today

**Comment by jesseduffield** [comment]
@peppy see if the issue is resolved for you on the latest master :)

**Comment by peppy** [comment]
Is indeed fixed 👍
