### ISSUE TITLE
Blink - Please, Stop it

### ISSUE THREAD

**Issue by flourigh** [jesseduffield/lazygit#853]
**Is your feature request related to a problem? Please describe.**
Please, stop blink in active option in panels, this cause distraction

**Describe the solution you'd like**
Roolback in previous version where not blink

**Comment by mdix** [comment]
I also noticed. It's really distracting. Can we at least have a configuration option to disable it? It somehow puts me under pressure, I feel like I have to do something quick. :-)

**Comment by band-a-prend** [comment]
I noticed that after upgrade to 0.20.4 version the blinking is disappeared but I can't distinguish the selected commit from list again (I use bold font in terminal).

It's ok if I add to config file following lines:
```
  gui:
    theme:
      selectedLineBgColor:
        - reverse
```

**Comment by jesseduffield** [comment]
as @band-a-prend said, upgrading to 0.20.4 should resolve the issue. But for those who can't see bolded lines I recommend using the reverse attribute as as above

**Comment by kjhx** [comment]
Yep, `0.20.4` fixed it! Thanks for getting a fix out so quickly, @jesseduffield.

**Comment by jesseduffield** [comment]
no worries :) closing
