### ISSUE TITLE
Retain commit message after pre-commit hook failure

### ISSUE THREAD

**Issue by willbowditch** [jesseduffield/lazygit#854]
**Is your feature request related to a problem? Please describe.**
If [pre-commit](https://pre-commit.com/) modifies a file, such as code formatting, the lazygit interface reloads, but staging the modified file and committing again requires retyping the commit message.  

Specifically this happens with github.com/psf/black plugin, but I guess the issue will apply to any hook that modifies a file and reports a failure.

**Describe the solution you'd like**
It would be good if the commit message was retained in this scenario - so you can quickly stage the reformatted file

**Describe alternatives you've considered**
None.

**Additional context**

This event triggers it:

```
black....................................................................Failed
- hook id: black
- files were modified by this hook
```

**Comment by gwww** [comment]
Additional info, I think related. When pre-commit hooks are in place I do not see any of the output messages from the pre-commit hook. I thought they would show up in the `Command Log`.

**Comment by Ryooooooga** [comment]
It has the same cause as https://github.com/jesseduffield/lazygit/issues/1360.

**Comment by strboul** [comment]
I'm also suffering from this.
