### ISSUE TITLE
Allow disabling of force push

### ISSUE THREAD

**Issue by nahtnam** [jesseduffield/lazygit#855]
**Topic**

So sometimes when I am pushing to a branch and it has diverged from the remote, a little pop up shows up saying would you like to force push. Instinctively I press enter instead of escape which ends up force pushing

**Your thoughts**

I was hoping there would be an option to disable this specific behavior or just disable force pushing all throughout lazygit.

I feel like this makes you look incompetent at work (because it implies you don't know how to merge/rebase) when in reality I'm just lazy 😂

**Comment by lordlycastle** [comment]
You need to force push after a rebase?

**Comment by nahtnam** [comment]
Nope. So lets say I make a commit on the branch develop, but someone pushed a commit to develop before me. When I push, lazy git would give the following error: 'Branch has diverged from remote'.

So then you:
1. Press `esc`
2. Pree `p` to pull (lazygit will auto merge)
3. Press `P` to push

Now if you (out of habit) press `enter` instead of `esc` in step 1, it just immediately force-pushes and overwrites whatever is in the remote which I would say is pretty dangerous behavior.

**Comment by lordlycastle** [comment]
Yeah fair enough. But some would say two people shouldn't be using the same branch; I won't but those people are everywhere!

**Comment by nahtnam** [comment]
I generally agree with that but here are two situations that are pretty common:

1. You made a PR, and at the same time someone else pushes to master, you get a nice little button in the UI that allows you to merge master into your PR. You forget to pull locally and now you end up force pushing
2. You are working directly on the develop branch. Some automated tool like dependabot updates your dependencies for you. You merge the PR, forget to pull and end up force pushing to develop

**Comment by fsmiamoto** [comment]
@jesseduffield I'd really like to tackle this one!

**Comment by jesseduffield** [comment]
go for it @fsmiamoto, lemme know if you need anything!

**Comment by jesseduffield** [comment]
This has now been implemented, closing :)

**Comment by nahtnam** [comment]
Appreciate it a lot, thank you so much!

**Comment by SelaOZ** [comment]
@jesseduffield how can I disable this?
