### ISSUE TITLE
Provide a way to customise colour of copied commits

### ISSUE THREAD

**Issue by OliverJAsh** [jesseduffield/lazygit#856]
![image](https://user-images.githubusercontent.com/921609/82728355-aeaa5b80-9ce7-11ea-8ed5-b41db0880834.png)

**Comment by jesseduffield** [comment]
currently this is hardcoded as `var cherryPickedCommitTextStyle = style.FgCyan.MergeStyle(style.BgBlue)` in `pkg/gui/presentation/commits.go`. We could have the background of a copied commit be configurable as `copiedCommitBgColor` and default it to `cyan` in `pkg/config/user_config.go`

**Comment by jesseduffield** [comment]
fixed in https://github.com/jesseduffield/lazygit/pull/1499, thanks @samburville !
