### ISSUE TITLE
Shortcut shift+tab terminates the lazygit

### ISSUE THREAD

**Issue by waldauf** [jesseduffield/lazygit#859]
**Describe the bug**

**To Reproduce**
1. Go to lazygit
2. Press "tab"
3. Press "shift+tab"
4. Lazygit is terminated (`echo $? = 0`)

**Expected behavior**
Switch to previous part of layzgit is working.

**Desktop (please complete the following information):**
 - OS: Arch LInux
 - Lazygit Version: lazygit 0.20.4-1

**Comment by waldauf** [comment]
I run the lazygit in debug mode with no additional result.

**Comment by jesseduffield** [comment]
I've removed the keybinding, so I'm going to close this issue. If other people continue encountering this issue I'll be happy to re-open, but there's not much I can do
