### ISSUE TITLE
.gitconfig includeIf

### ISSUE THREAD

**Issue by caasi-dev** [jesseduffield/lazygit#862]
**Is your feature request related to a problem? Please describe.**
Lazygit does not seem to be recognising the [includeIf](https://git-scm.com/docs/git-config#_includes) gitconfig property.

For example:
My current `.gitconfig` file is:
```
[user]
	email = main_email_address
	name = user_name
[includeIf "gitdir:/data/dev/WORK/"]
    path = /data/dev/dotfiles/gitconfigwork
[push]
        default = simple
[fetch]
        prune = true
```

**Describe the solution you'd like**
`includeIf` checks if the path exists on the disk and loads additional configuration if the path is found. In my case `/data/dev/dotfiles/gitconfigwork` only specifies different email address for my work projects in WORK folder as below:
```
[user]
	email = work_email_address
```

It would be nice if lazygit would be able to detect if it's in WORK folder and apply additional configs.

**Comment by mark2185** [comment]
@caasi-dev could you try this on `v0.35`? I can't reproduce it, `lazygit` does load up the `/data/dev/dotfiles/gitconfigwork` if I'm in `/data/dev/WORK/`, everything seems to work as expected.

**Comment by caasi-dev** [comment]
yes seems to be working fine, thank you.
