### ISSUE TITLE
Add instructions for building on Linux

### ISSUE THREAD

**Issue by dpacbach** [jesseduffield/lazygit#868]
Can you add instructions for building lazygit on Linux?

**Comment by mjarkk** [comment]
First of all make sure you have installed [golang](https://golang.org/doc/install)

For easy installing see: [readme > #go](https://github.com/jesseduffield/lazygit#go).

If you want build the project binary from inside of a cloned dir run:
```sh
go build
```

**Comment by dpacbach** [comment]
Thank you, should have figured that out myself!
