### ISSUE TITLE
Cannot stage modified renamed file

### ISSUE THREAD

**Issue by mnowotnik** [jesseduffield/lazygit#869]
**Describe the bug**
Trying to stage changes to staged renamed file causes path not found errors.

**To Reproduce**
1. Create a file, commit it
2. Rename the file, stage this change
3. Modify the file, try to stage this change using lazygit

**Expected behavior**
It should be possible to stage changes to renamed file.

**Comment by Lollipopster** [comment]
Same here 
lazygit version
```
commit=, build date=2020-05-19, build source=debian, version=0.20.4, os=linux, arch=amd64
```

**Comment by jesseduffield** [comment]
@mnowotnik or @Lollipopster are you able to provide a bash script that puts us in the state right before the error? I can't replicate on my end. For example:
```bash
echo "this is my file" > a
git add a
git commit -m "adding file a"
mv a b
git add .
echo "creating a again" > a
```

![image](https://user-images.githubusercontent.com/8456633/89629320-f8671300-d8e0-11ea-84ca-076aeaa6b5d4.png)
hit space
![image](https://user-images.githubusercontent.com/8456633/89629334-fe5cf400-d8e0-11ea-983b-ba8b110c9fd2.png)

**Comment by mnowotnik** [comment]
@jesseduffield sure,
commit=6291c539663b8646a3c09bc6e

```sh
git init
printf foo > file
git add file
git commit -m "xyz"
mv file renamed_file
git add -u
git add renamed_file
printf "\nbar" >> renamed_file
lazygit
```

**Comment by jesseduffield** [comment]
@mnowotnik I'm still not able to reproduce:
before pressing space:
![image](https://user-images.githubusercontent.com/8456633/95787680-bf567f00-0d25-11eb-881f-4253f2c83477.png)

after pressing space:
![image](https://user-images.githubusercontent.com/8456633/95787697-c54c6000-0d25-11eb-87e6-c076ef20d089.png)

tested on v0.23.2

**Comment by mnowotnik** [comment]
After pulling the newest lazygit version, I confirm that this bug no longer occurs.

**Comment by strogiyotec** [comment]
@jesseduffield I had the same problem in version
```
commit=, build date=2020-05-19, build source=debian, version=0.20.4, os=linux, arch=amd64
```
I updated lazygit to 
```
commit=, build date=2020-08-26, build source=debian, version=0.22.1, os=linux, arch=amd64
```
Now it works as expected, thank you
