### ISSUE TITLE
Merge resolution doesn't allow sane selection of only the HEAD portion

### ISSUE THREAD

**Issue by peppy** [jesseduffield/lazygit#873]
Quite often, I want to only include the HEAD section (between `<<<` and `|||`) but this is currently not possible. I think a better pattern would allow the user to choose between each of the three conflict sections (lazygit doesn't and probably shouldn't handle more complex merge cases unless a better UX is introduced).

![image](https://user-images.githubusercontent.com/191335/84341384-e5380f80-abdd-11ea-8172-ba460d1cd446.png)

To clarify, the `parent of` section in the above screenshot should not be inserted along with the `HEAD` section (it will leave conflict characters / lines in the resulting file).

**Comment by jesseduffield** [comment]
Interesting, this is the first time I've come across this use case. When I get the time I'll make a start on a fix

**Comment by jesseduffield** [comment]
As per https://github.com/jesseduffield/lazygit/pull/1447 this should now be implemented on master (and on the latest release I believe)
