### ISSUE TITLE
Config does not accept german umlauts for key binding

### ISSUE THREAD

**Issue by chnoack** [jesseduffield/lazygit#876]
**Describe the bug**
On a German keyboard the letters "[" and "]" are difficult to reach `<option-5>`.  It would be good to have another easy to reach key for switching the tabs in a view. I tried "ä" (a-uml) and "ö" (o-uml).  But then layzgit crashes on startup:
`Unrecognized key ä for keybinding universal.nextTab`

**To Reproduce**
1. In config.yml change   `prevtab: '['` to `prevtab: 'ö'`
2. Reopen lazygit

**Expected behavior**
Lazygit should open and navigation through tabs should be possible with new key bindings on "ä" and "ö"

**Desktop (please complete the following information):**
 - OS:  MacOS 10.15.5
 - Lazygit Version  
`commit=cf5cefb2d6bcfd0d403faca5875124eb9b0d7480, build date=2020-05-19T11:41:07Z, build source=binaryRelease, version=0.20.4, os=darwin, arch=amd64`

**Comment by jesseduffield** [comment]
Should be fixed in https://github.com/jesseduffield/lazygit/pull/924 :)

**Comment by jesseduffield** [comment]
included in version v0.21, feel free to reopen if the issue persists :)
