### ISSUE TITLE
Is there a way to checkout a remote branch without typing its full name?

### ISSUE THREAD

**Issue by rubensr-pc** [jesseduffield/lazygit#884]
**Topic**
I use JIRA+bitbucket, so branches are created on the remote first, with pretty long names

**Your thoughts**
I'm just trying to figure out if I am missing something obvious - I'd like to see/search/autocomplete a remote branch name and check it out locally.

Thanks!

**Comment by mjarkk** [comment]
i don't think that's possible but it would be cool if it exists

**Comment by hemenkapadia** [comment]
+1 for this.

Currently the `Remotes` tab in the `Local Branches` area does list the remote branches.

Possible options on Remote branches include 

- space Checkout  (but that puts the repo in a detached head state)

there are rebase (r) and merge (M) options but that would perform the actions on the current local checked out branch which is not correct. 

Is it possible to create an option (say l) that would create a local branch with the same name and set the upstream to the selected remote branch and then issue a pull to get the latest code locally ?

**Comment by hemenkapadia** [comment]
Looks similar to #774 and #833 . All are duplicates asking for the same feature

**Comment by hemenkapadia** [comment]
Solution !

Should have paid more attention to the menu (n) option does what is expected. The workflow is as follows

- Go to Branches Panel
- Press `]` to navigate to remotes. Press `Enter` on line with remote branch count to populate remote branches list.
- Scroll to the remote branch you want to checkout locally and press `n`. Update the name if needed (I prefer removing `origin/` from the name. Press Enter and you have the local branch created

**Comment by jesseduffield** [comment]
Nice work @hemenkapadia investigating! This has caused some confusion so I've now made the space keybinding do the same thing as the 'n' keybinding (for those who really do want a detached head upon hitting space, I apologise)

**Comment by cgebbe** [comment]
Just found this two year old thread via google. It seems now we have the feature "checkout by name", which comes in handy:

- Go to local branches
- `c` for checkout by name
- type in `new_` to find e.g. `remote/new_branch` and checkout that branch
- you now have a detached HEAD. Press `n` to create a new branch here

**Comment by OlivierLDff** [comment]
Hi, I'm using this workflow since quite sometime but I always find myself typing the name of the branch to create new local branch. Is there some wizardery I don't know about that prefil the name with the name of the remote branch?

<img width="509" alt="image" src="https://github.com/jesseduffield/lazygit/assets/17255804/6c782f74-8cda-4fbe-a242-50725ff0eca8">

**Comment by mark2185** [comment]
To be honest I don't know why it isn't prefilled with the upstream's name, I always miss that.

@jesseduffield is that something we might want to have? Seems like a somewhat simple feature.

**Comment by ooloth** [comment]
@OlivierLDff @mark2185 Instead of pressing `enter`, if you press `space` or `n` when checking out a remote branch, the branch name will be pre-filled for you.

**Comment by mark2185** [comment]
But for that you have to go to the `Remotes` tab, select one, find the branch, and then press `n` or `space`, that sounds more like `hardworkingit`, not `lazygit`.

This is for when you press `c` in the `Local Branches` panel, it checks it out in `detached HEAD` state.

**Comment by ooloth** [comment]
Ah right! Sorry about that. Forgot we have that nice `c` option for listing all local and remote branches.

**Comment by OlivierLDff** [comment]
> Nice for the trick I will use that for now . But yes the `c` shortcut was quite nice

**Comment by OlivierLDff** [comment]
Thanks for adding that in 0.41 🎉
