### ISSUE TITLE
Force push on lazygit

### ISSUE THREAD

**Issue by KiteAB** [jesseduffield/lazygit#885]
**Topic**
How does lazygit perform force push

**Your thoughts**
I can only use "git push --force --up-stream origin master" for force push at the moment, and I did not find the item force push in lazygit's menu

**Comment by lordlycastle** [comment]
It asks to force push if remote has diverged from local. Try to do it.

**Comment by KiteAB** [comment]
It only prompts that it cannot be pushed, but does not give a force push option

**Comment by lordlycastle** [comment]
Might be due to some other reason. Can you post a screenshot?

**Comment by KiteAB** [comment]
OK.
![](https://i.loli.net/2020/07/14/Tgbu9lc37DyFEek.png)

**Comment by KiteAB** [comment]
They have no message to remind me need force push

**Comment by jesseduffield** [comment]
Interesting. @KiteAB how did you create this repo? Was it by doing a `git init`?  And are you pushing to an existing repo you've created e.g. on github?

**Comment by KiteAB** [comment]
I created a new folder locally and executed git init when there was a commit record in the remote warehouse, but I didn’t know that there would be such a consequence  /laugh and cry

**Comment by edwinclement08** [comment]
Any update on this?

**Comment by KiteAB** [comment]
nope

**Comment by KiteAB** [comment]
i have no answer now

**Comment by jesseduffield** [comment]
@KiteAB could you try out https://github.com/jesseduffield/lazygit/pull/928 and see if that resolves the issue for you? Apologies that it's taken me a while to get around to this :)

**Comment by KiteAB** [comment]
I'm sorry because i can't try and close this issue now :(
Just because i don't use brew to install the lazygit, Please wait...

**Comment by KiteAB** [comment]
Thx!
