### ISSUE TITLE
Don't quit when "return" binding is hit while nowhere to return to

### ISSUE THREAD

**Issue by peppy** [jesseduffield/lazygit#888]
This is documented behaviour, but for my key bind setup i'd prefer for it not to be the case. Basically I'd like to be able to use 'escape' or another binding and mash it to get back to the main screen without it bringing up the quit dialog ever.

My specific use case is that I have my window manager setup to handle esc-esc to switch modes, which works in most applications: the application handles the first esc and exits its active mode (if any), and the second will be sent to my window manager. Even if the active application is not in a specific mode, esc-esc will have no effect and still work correctly.

I understand this may be too specific to implement.

**Comment by jesseduffield** [comment]
Do you mean that you want to still allow 'q' to quit, but for 'esc' to do nothing once it reaches the top level? I think that's reasonable

**Comment by peppy** [comment]
Yep, that would work great. There may be others which may prefer the opposite (current) behaviour so keep that in mind (maybe have `return_or_quit` and `return` binding options in that case?)

**Comment by jesseduffield** [comment]
I myself have often accidentally exited when I just wanted to exit out of whatever context I was in. I think there was another request to have it ask whether you were sure when quitting at the top level. I wonder if we should simply have two different things: one 'escaping' the current context (esc) and one for quitting the application (q). I might do that and then see if anybody gets mad at me haha

**Comment by jesseduffield** [comment]
though it would be annoying to be in a popup box where you're allowed to type and have to go `esc`, `q` to exit rather than double tapping `esc`. I'll just make it configurable

**Comment by jesseduffield** [comment]
PR is up: https://github.com/jesseduffield/lazygit/pull/904/files
to make this work you'll need to set:
```
quitOnTopLevelReturn: false
```
in your config.

**Comment by peppy** [comment]
amazing, thanks!

**Comment by jesseduffield** [comment]
no worries :)

**Comment by peppy** [comment]
Testing and working as expected, so this should be good to close.
