### ISSUE TITLE
Push to other remote

### ISSUE THREAD

**Issue by SpringHan** [jesseduffield/lazygit#889]
I can't push my commit to the others remotes in lazygit after I set the upstream remote.If I want to do it,I only can execute the push command in command-line.If there are other easier ways?

**Comment by KiteAB** [comment]
You can try select the remote in `remotes` panel and use `P` 2 push? I don't know if this will work.

**Comment by jesseduffield** [comment]
@SpringHan is your desire to set a new upstream for the branch to be used from that point on, or to push to the upstream as a once-off?

If you want to set an upstream for the current branch, you can go to the remote branches section and press 'u'

**Comment by SpringHan** [comment]
Oh, it solved successful.Thanks.

**Comment by manorit2001** [comment]
> @SpringHan is your desire to set a new upstream for the branch to be used from that point on, or to push to the upstream as a once-off?

Is there any way to push it once-off rather than changing the upstream origin?

**Comment by jesseduffield** [comment]
@manorit2001 there's no current way to do it as a once-off. I would raise an issue for that if none currently exists

**Comment by mokeyish** [comment]
@jesseduffield Could you add a menu `Push to` under the `Push`? I don't want to switch vscode to do this operation.

**Comment by mokeyish** [comment]
![图片](https://github.com/jesseduffield/lazygit/assets/16131917/287c6a40-917a-42fe-a4cd-6359e5a05bbf)

**Comment by mark2185** [comment]
> I don't want to switch vscode to do this operation.

You don't have to, you can run a custom command by pressing `:` and typing in `git push <name-of-upstream-origin>` if you don't wish to change the upstream through the menu under `u`.

**Comment by mokeyish** [comment]
> You don't have to, you can run a custom command by pressing `:` and typing in `git push <name-of-upstream-origin>` if you don't with to change the upstream through the menu under `u`.

Thanks, But I'm `lazy`😂. The command push to another remote branch is 

`git push <remote> <local branch>:<remote branch>`

**Comment by RyannDaGreat** [comment]
this feature would be lovely :3 any chance of adding it?

**Comment by arthur-akufen** [comment]
Thanks @mark2185 this is exactly what I wanted
