### ISSUE TITLE
Commit command failure on v0.20.6

### ISSUE THREAD

**Issue by willbowditch** [jesseduffield/lazygit#890]
**Describe the bug**
Committing from lazygit no longer works with latest release.

**To Reproduce**

1. Commit from lazy git

I think this is an issue with quoting ` bash -c "git commit -m 'test'"` works if run in shell but  `bash -c git commit -m 'test'` does not

**Expected behavior**

Same as running `git commit` in shell

**Screenshots**
![image](https://user-images.githubusercontent.com/14288042/87284868-c5eb1580-c4ee-11ea-9b2b-962b40b3d0fe.png)

**Desktop (please complete the following information):**
 - OS: OS X
 - Lazygit Version `commit=fe6d8d62c5c0ef302ae44f95cd13a03600477199, build date=2020-07-12T13:01:48Z, build source=binaryRelease, version=0.20.6, os=darwin, arch=amd64`

**Additional context**

**Comment by jesseduffield** [comment]
Damn, looks like that PR about platform-specific quoting didn't properly handle all cases. I'll take a look into this

**Comment by jesseduffield** [comment]
@willbowditch am I right that you use gpg?

**Comment by jesseduffield** [comment]
@Randshot looks like your changes to the git commit command don't work on OSX when using GPG. Do you know how this could be fixed so that it works on all platforms?

**Comment by Randshot** [comment]
@jesseduffield hm :/ , I will take a look at it.

**Comment by jesseduffield** [comment]
thanks!

**Comment by willbowditch** [comment]
@jesseduffield @Randshot Yep, you're right, GPG by default and using pre-commit (not sure if that's important). Happy to test anything if useful

**Comment by Randshot** [comment]
@jesseduffield I think I found a workaround. It's not ideal, but as far as my testing showed, it should suffice.
Note that I only did *manual* testing on Linux (i.e. running the `bash -c` command manually).

**Comment by jesseduffield** [comment]
fixed in v0.20.7

**Comment by willbowditch** [comment]
@jesseduffield @Randshot thanks for the fix.

I've stumbled across another error, that commits with the `'` character now cause:

```
panic: Starting quote has no ending quote.

goroutine 1 [running]:
github.com/mgutz/str.ToArgv(0xc000472070, 0x6e, 0xc000376200, 0x6e, 0x80)
        /home/runner/work/lazygit/lazygit/vendor/github.com/mgutz/str/funcsPZ.go:377 +0x5a7
github.com/jesseduffield/lazygit/pkg/commands.(*OSCommand).ExecutableFromString(0xc000248300, 0xc000472070, 0x6e, 0x3)
        /home/runner/work/lazygit/lazygit/pkg/commands/os.go:115 +0x39
github.com/jesseduffield/lazygit/pkg/commands.(*OSCommand).ShellCommandFromString(0xc000248300, 0xc0000345b0, 0x64, 0x2)
        /home/runner/work/lazygit/lazygit/pkg/commands/os.go:131 +0x190
github.com/jesseduffield/lazygit/pkg/commands.(*GitCommand).Commit(0xc000297480, 0xc0000fab40, 0x53, 0x0, 0x0, 0xc0004c60c1, 0x181b679, 0xc0006cf9a0)
        /home/runner/work/lazygit/lazygit/pkg/commands/git.go:456 +0x17a
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).handleCommitConfirm(0xc00032b6c0, 0xc000342000, 0xc0003fcc60, 0x2, 0x1000000000000)
        /home/runner/work/lazygit/lazygit/pkg/gui/commit_message_panel.go:38 +0x10c
github.com/jesseduffield/gocui.(*Gui).execKeybinding(...)
        /home/runner/work/lazygit/lazygit/vendor/github.com/jesseduffield/gocui/gui.go:898
github.com/jesseduffield/gocui.(*Gui).execKeybindings(0xc000342000, 0xc0003fcc60, 0xc0006cfb50, 0xc00039e060, 0xc000000208, 0xc0000002b8)
        /home/runner/work/lazygit/lazygit/vendor/github.com/jesseduffield/gocui/gui.go:878 +0x18d
github.com/jesseduffield/gocui.(*Gui).onKey(0xc000342000, 0xc0006cfb50, 0x2, 0x0)
        /home/runner/work/lazygit/lazygit/vendor/github.com/jesseduffield/gocui/gui.go:809 +0x281
github.com/jesseduffield/gocui.(*Gui).handleEvent(...)
        /home/runner/work/lazygit/lazygit/vendor/github.com/jesseduffield/gocui/gui.go:497
github.com/jesseduffield/gocui.(*Gui).MainLoop(0xc000342000, 0xc000000003, 0xc0000f7c98)
        /home/runner/work/lazygit/lazygit/vendor/github.com/jesseduffield/gocui/gui.go:457 +0x1f2
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).Run(0xc00032b6c0, 0x0, 0x0)
        /home/runner/work/lazygit/lazygit/pkg/gui/gui.go:363 +0x63a
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).RunWithSubprocesses(0xc00032b6c0, 0x0, 0x0)
        /home/runner/work/lazygit/lazygit/pkg/gui/gui.go:372 +0x40
github.com/jesseduffield/lazygit/pkg/app.(*App).Run(0xc000257b90, 0xc00018e980, 0x0)
        /home/runner/work/lazygit/lazygit/pkg/app/app.go:165 +0x6b
main.main()
        /home/runner/work/lazygit/lazygit/main.go:70 +0x7f3
```

I'm guessing this is equivalent to running `git commit -m "blah's"` vs `git commit -m 'blah's'`

**Comment by Randshot** [comment]
@willbowditch Ugh, didn't think of that scenario. This is only a problem on non-windows systems, since we don't surround the git command with quotes there.
For now, until I (we) can find a acceptable solution for this, use the `shift+c` (commit with editor) hotkey to commit your changes.

**Comment by Randshot** [comment]
Also, could you open a new issue for this, for tracking purposes.
