### ISSUE TITLE
More documentation

### ISSUE THREAD

**Issue by nagy135** [jesseduffield/lazygit#892]
**Topic**
Place to ask dumb questions

**Your thoughts**
I m using this app for some months now (10/10, loving this app!), and multiple times I felt like i have simple small question that isnt really Issue-worthy and i didnt know where to ask them. I will give you two examples that come to mind but it all comes down to me asking for "more documentation" or at least point me to it if I just didnt see it anywhere (Do we have IRC?)

* How do I focus "staged/unstaged changes" without mouse?
* What color represents what in branch tab?

**Comment by jesseduffield** [comment]
I think a Q/A thread is a good idea, and it's worth thinking about a good way to document this stuff. I've got a few pages on the wiki but it's not very dense.

In answer to your two questions:

1) press enter on the file
2) green is for features, yellow is for bugfixes, red is for hotfixes, white is for everything else

**Comment by nagy135** [comment]
Good, I might create some in future then.

1. Silly that i didnt see that one, I remember seeing it asked somewhere on reddit in past, so I guess I m not the only one lost in help description :) I was expecting some focus-changing bind to "move right" in general.
2. I think you should work on documenting these because sooner or later people will start asking on those

Thanks for quick replies!
