### ISSUE TITLE
Installation via go get doesn't work due to unversioned binary

### ISSUE THREAD

**Issue by pankona** [jesseduffield/lazygit#90]
According to README.md, lazygit can be installed via `go get`.
But lazygit executable binary that is installed via `go get` doesn't include version information. Then lazygit tries to read VERSION file in current directly, if there's not, lazygit goes panic as follows.

```bash
2018/08/09 12:00:59 open VERSION: no such file or directory
panic: open VERSION: no such file or directory


goroutine 1 [running]:
log.Panicln(0xc00009dec8, 0x1, 0x1)
	/home/pankona/work/go/src/log/log.go:340 +0xc0
main.fallbackVersion(0xc00009df48, 0x1)
	/home/pankona/go/src/github.com/jesseduffield/lazygit/main.go:79 +0x11b
main.main()
	/home/pankona/go/src/github.com/jesseduffield/lazygit/main.go:89 +0x2f0
```

lazygit downloaded from binary realeaes doesn't occur this problem. According to comments on `main.go`, Version information is embeded at compling time. I guess binary releases are compiled in appropriate way.

In my opinion, possible solutions for this situation are:
* Update README.md to introduce as "Do not to install via go get"
* Update README.md (and some files) to introduce how to build with embeded version information 
  * I think providing some automation (Makefile or something like easy shell scripting, etc) is better

If you have favorite idea among them (or you have another idea), let me know.
I may send a pull request for you. Thanks!

**Comment by jesseduffield** [comment]
I've just pushed up a fix for this, please let me know if it resolves your issue :)

**Comment by pankona** [comment]
@jesseduffield 
I just confirmed the issue has been resovled!
Thank you so much!

**Comment by pankona** [comment]
Thank you so much, close this issue.
