### ISSUE TITLE
branch -a

### ISSUE THREAD

**Issue by littletwolee** [jesseduffield/lazygit#91]
hi guy,
   i want list all branches from origin, plz tell me which key can i use?
thx a lot.

**Comment by glvr182** [comment]
Waking up this old thread. We currently do not support listing all branches (afaik). We are using go-git to list our branches so we might be able to achieve what you want by changing the way we fetch the branches.

Some links to get the search started:
[go git](https://github.com/src-d/go-git/)
[go-git branches](https://github.com/src-d/go-git/blob/master/_examples/branch/main.go)
[go-git remotes](https://github.com/src-d/go-git/blob/master/_examples/remotes/main.go)

**Comment by littletwolee** [comment]
ok, thx a lot.
