### ISSUE TITLE
Filter with git commands?

### ISSUE THREAD

**Issue by naseer** [jesseduffield/lazygit#914]
Is it possible to filter the commits by author? Another example is to filter with `--no-merges`
This is purely to use lazygit as a browser.

**Comment by jesseduffield** [comment]
Currently not but this is a good feature idea

**Comment by n12o** [comment]
This is indeed a good idea. There's no way to do this with lazygit currently so I have to use command line which is fine but don't have a good workflow to navigate it and ofc it's much nicer to have most basic git features in lazygit

**Comment by jesseduffield** [comment]
Closing in favour of https://github.com/jesseduffield/lazygit/issues/914
