### ISSUE TITLE
Ability to change git pull command

### ISSUE THREAD

**Issue by kristijanhusak** [jesseduffield/lazygit#919]
Same as what you did here https://github.com/jesseduffield/lazygit/pull/797, but for git pull :)

I'm used to doing `git pull --rebase`, which makes me do pulls outside of lazygit because it's not supported.

**Comment by jesseduffield** [comment]
I was thinking about this just the other day. Definitely something we should do

**Comment by kristijanhusak** [comment]
I tried doing this myself, but when I add `--rebase`, it errors out with message `Cannot rebase from multiple branches`. I'm not sure why that happens.

**Comment by jesseduffield** [comment]
@kristijanhusak I've enabled this in https://github.com/jesseduffield/lazygit/pull/921. Please give that branch a go and let me know your thoughts :)

**Comment by kristijanhusak** [comment]
@jesseduffield looks good :)

**Comment by jesseduffield** [comment]
Awesome :) merged
