### ISSUE TITLE
[Feature request] Support rename a branch

### ISSUE THREAD

**Issue by SukkaW** [jesseduffield/lazygit#920]
**Is your feature request related to a problem? Please describe.**

For instance, when I create a new branch, after committing some changes, I might want to change the branch name before push to the remote.

**Describe the solution you'd like**

`git` doesn't support rename a branch, but lazygit could provide a shortcut:

- Create a new branch (with the new branch name) based on the selected branch
- Delete the selected branch
- Checkout the newly created branch (which will have the same HEAD)

**Comment by jesseduffield** [comment]
If I'm reading your message correctly, this is already supported by pressing shift+R on a branch :)

**Comment by SukkaW** [comment]
> If I'm reading your message correctly, this is already supported by pressing shift+R on a branch :)

Oops.
