### ISSUE TITLE
Can't merge remote directly into current branch

### ISSUE THREAD

**Issue by peppy** [jesseduffield/lazygit#922]
I'd expect to be able to merge since the option is there, but it seems to fail with a non-descript error. I have confirmed that merging from git CLI works correctly (`git merge origin/...`).

![2020-08-12 17 02 51](https://user-images.githubusercontent.com/191335/89990899-fc6aaa80-dcbd-11ea-8842-a0b8d6a32f23.gif)

**Comment by jesseduffield** [comment]
I think the culprit is that we're not prepending the name of the remote when merging. Could you give https://github.com/jesseduffield/lazygit/pull/923 a go?

**Comment by peppy** [comment]
Linked PR works perfectly.

**Comment by jesseduffield** [comment]
awesome :) closing
