### ISSUE TITLE
Can't rebase on remote current branch

### ISSUE THREAD

**Issue by peppy** [jesseduffield/lazygit#925]
This may be me misusing the app, but here's the scenario:

- Working on a project with no forks (single `origin`)
- Create local commits on `master`
- Upstream also has commits merged into `master`
- Want to rebase local commits on top of the remote ones

Currently, doing so from the branches window results in the error:

![image](https://user-images.githubusercontent.com/191335/90003660-59bb2780-dccf-11ea-9e48-befd5954bdcc.png)

Likewise, from the remote window:

![2020-08-12 19 11 51](https://user-images.githubusercontent.com/191335/90003933-c504f980-dccf-11ea-9406-7660dea440df.gif)

My current workaround is to copy the new commits, reset to upstream (reset from the commits window) then paste the commits back, but this seems counter-intuitive. From the command line, `git rebase origin/master` will work as expected in such a scenario.

**Comment by jesseduffield** [comment]
Interesting! If this is something you always want to be doing i.e. analogous to `git pull --rebase`, you can do that by setting:
```
git:
  pull:
    mode: 'rebase'
```
in your config.

Otherwise we'll need to think about a good interface for this. I'm not sure that pressing 'r' on the current branch would be expected to rebase onto its upstream branch. Perhaps we could make the 'r' keybinding bring up a menu to rebase on either the branch or the branch's upstream. But then we could potentially want that extended functionality for all kinds of commands, suggesting perhaps we need another way of saying 'I'm talking about the branch's upstream here' like a keybinding that toggles between viewing branches and viewing their upstreams

**Comment by peppy** [comment]
At very least, being able to rebase from the `Remotes` section may be a good starting point, since at that point the user is likely aware they are looking at a remote context?

And yeah, funnily enough the reason I run into this in the first place is due to my global git config:

```
[pull]                                                                                                                 
    ff = only    
```

So the rebase option for pull is probably not an option (seems to conflict with this):

![image](https://user-images.githubusercontent.com/191335/90005587-655c1d80-dcd2-11ea-8035-7c6ed70d94ea.png)

**Comment by jesseduffield** [comment]
Ahh I thought you were attempting to rebase a branch onto itself, sorry for the misunderstanding. Looks like the change I made for merging is also what's required here. I've done a scan of the remote branches code to ensure we haven't missed any other spots this time around :) https://github.com/jesseduffield/lazygit/pull/927

**Comment by peppy** [comment]
That did it, thanks!

**Comment by jesseduffield** [comment]
sweet, closing :)

**Comment by aaronmcadam** [comment]
I've tried to apply the above config, but I still get the default pull command. The docs don't include this command either, has it been removed?

**Comment by mark2185** [comment]
What does the log say, which command is run in the background when you try pulling? 

You can open it by pressing `@` and then choosing `Focus command log`

**Comment by aaronmcadam** [comment]
With the following config:
```yml
git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
  pull:
    mode: 'rebase'
```

The command log says:
```
git pull --no-edit "origin" "main"
```

**Comment by mark2185** [comment]
Yeah, I can't find the option in the `configuration.md` anymore, I guess it's gone?

You could go to the `Remotes` tab (in the branches panel press `]`) and choose the branch you wish to rebase onto.

Or you could configure it through your `gitconfig`:
```
[pull]
	rebase = true
```

**Comment by aaronmcadam** [comment]
Thanks a lot for looking into it @mark2185. I've updated my `gitconfig` instead, which works well for now. Thanks!

**Comment by danielo515** [comment]
In any case, will be cool if this could be configured in lazygit

**Comment by danielo515** [comment]
Will you consider re-opening this issue? It's a bit annoying having to reach to the cli every time I have to pull rebase

**Comment by mark2185** [comment]
@jesseduffield what do you think about [this](https://github.com/jesseduffield/lazygit/pull/2649/files)?

Instead of a _not so helpful error_, maybe a feature? I know I've had times when I needed this.
