### ISSUE TITLE
merge/rebase adds |||||| when resolving conflicts

### ISSUE THREAD

**Issue by cj** [jesseduffield/lazygit#939]
**Describe the bug**
When resolving merge/rebase conflicts it always adds |||||, which never gets deleted and becomes part of that file

**To Reproduce**
create a merge or rebase conflict

**Expected behavior**
It not to have all the pipes

**Screenshots**
![CleanShot 2020-08-19 at 01 26 10](https://user-images.githubusercontent.com/1819/90599878-41f60e80-e1bb-11ea-9ca8-9f5962c76246.png)

**Desktop (please complete the following information):**
 - OS: Mac
 - Lazygit Version 0.20.9

**Comment by jesseduffield** [comment]
@cj I'm not able to reproduce this locally, are you able to provide a repo where you've found this issue for me to test against? Or perhaps a bash script to generate such a repo?

**Comment by cj** [comment]
@jesseduffield it happens with any repo, here is the repo from the screenshot https://github.com/cj/lazygit-rebase-issue.

If you checkout master-3 and then try to rebase onto master-2 you'll get the conflict.

**Comment by cj** [comment]
@cj I found out what it is, it's one of the git global settings I have, give me just a sec to find it and I'll let you know.

**Comment by cj** [comment]
@jesseduffield this was the culprit!

```
[merge]
	conflictstyle = diff3
```

**Comment by jesseduffield** [comment]
Thanks for investigating! I'll raise another issue to ignore the configured `conflictstyle` so that we don't have the same issue for other new users.

**Comment by cj** [comment]
@jesseduffield no problem - thank, YOU, for such an amazing tool!
