### ISSUE TITLE
Display long description of menu items

### ISSUE THREAD

**Issue by jesseduffield** [jesseduffield/lazygit#943]
**Is your feature request related to a problem? Please describe.**
When viewing items in a menu, often it's not clear what the option will do

**Describe the solution you'd like**
We should have a second view sitting underneath the menu view which provides context as to what will happen when you select the menu item.

**Describe alternatives you've considered**
none

**Additional context**
I'm doing a refactor now that should hopefully make this easier

**Comment by mark2185** [comment]
We have this, I think? The second column in the menus?

**Comment by jesseduffield** [comment]
ah yes this is now implemented with the Tooltip option. Closing
