### ISSUE TITLE
add lazygit to git-scm.com/downloads/guis

### ISSUE THREAD

**Issue by mjarkk** [jesseduffield/lazygit#944]
Was surfing the web today and found out about the [GUIs page on git-scm's site](https://git-scm.com/downloads/guis).  
It seems like [GitUI](https://github.com/Extrawurst/gitui) is also added on the list so it might be worth adding lazygit also to it.

**Comment by jesseduffield** [comment]
pull request is up: https://github.com/git/git-scm.com/pulls

**Comment by mjarkk** [comment]
MR seems to be merged in :), i'll close this issue
