### ISSUE TITLE
Always open the editor when squashing

### ISSUE THREAD

**Issue by alexherbo2** [jesseduffield/lazygit#959]

**Comment by jesseduffield** [comment]
Closing due to lack of description. Please use the template provided when creating an issue

**Comment by alexherbo2** [comment]
@jesseduffield The reason for the issue is it is really easy to mess your commit messages without noticing, plus the fact in the log view we do not see the body message.

**Comment by jesseduffield** [comment]
I'm not sure what you mean: when pressing 's' on a commit I get this:
![image](https://user-images.githubusercontent.com/8456633/90991218-d5c84000-e5ea-11ea-8022-ba37af843ea6.png)

When doing it via 'e' I get this:
![image](https://user-images.githubusercontent.com/8456633/90991228-e082d500-e5ea-11ea-9b4d-636024b2a63c.png)


Are you talking about a different situation in which squashing occurs?

**Comment by alexherbo2** [comment]
Yep, the squashing without opening the editor can be misleading.  I had messed my commits without realizing that way.

**Comment by alexherbo2** [comment]
Any update?

I think it is important to confirm the squash not with a simple Ok, but rather by opening a box with the concatenated messages to edit and confirm.

It is important for me to trust what a tool is doing, in addition to #960, as there is currently no way to see the commit message concatenation via the lazygit interface.
