### ISSUE TITLE
Display the current repository name

### ISSUE THREAD

**Issue by dsnoeck** [jesseduffield/lazygit#96]
I might have miss something, but I don't find the current repository name. And since I'm working with lot of them simultaneously, this is annoying.

**Comment by glvr182** [comment]
Maybe the name of the folder you're currently could be placed in front of the current branch, for example:
```
Status 
lazygit -> master
```
Some code to extract the current folder name
```
func GetCurrentProject() string {
	path, err := filepath.Abs(filepath.Dir(os.Args[0]))
	if err != nil {
		log.Fatalln(err.Error())
	}

	dirs := strings.Split(path, "/")
	return dirs[len(dirs)-1]

}

```

**Comment by glvr182** [comment]
@jesseduffield What do you think about this idea?

**Comment by jesseduffield** [comment]
Looks good to me. I'd maybe swap out the `->` for a unicode arrow `→`, and we can utilise the fact that at startup the app navigates up to find the root directory of the repo, so we merely need to obtain the current working directory like so:
```
	pwd, err := os.Getwd()
	if err != nil {
		log.Fatalln(err.Error())
	}
	return filepath.Base(pwd)
```

**Comment by dsnoeck** [comment]
Thanks you very much for this excellent application and such fast answer and resolution. You rocks !
