### ISSUE TITLE
Setctty set but Ctty not valid in child  

### ISSUE THREAD

**Issue by kristijanhusak** [jesseduffield/lazygit#966]
**Describe the bug**
From latest update I started getting this error when trying to push/pull:
```
fork/exec /usr/bin/git: Setctty set but Ctty not valid in child
```

Screenshot:
![screenshot](https://i.imgur.com/W4zUiPe.png)

**To Reproduce**
1. Just try pulling

**Desktop (please complete the following information):**
 - OS: Manjaro Linux i3
 - Lazygit Version - latest master
 - The last commit id if you built project from sources : 7ebb8343d1fd5a736e01d0b358ab3036cf8a8495

Found this issue with googling, probably related:
https://github.com/creack/pty/issues/96

**Comment by jesseduffield** [comment]
@kristijanhusak I wasn't able to reproduce locally, would you be able to give https://github.com/jesseduffield/lazygit/pull/967 a test?

**Comment by jesseduffield** [comment]
in the interests of time I'll auto merge it cos shouldn't make the issue any worse!

**Comment by KouAkitaki** [comment]
I'm experiencing the same issue when trying to push.

OS: Void Linux x86_64
Lazygit Version: Release v0.20.9, installed via XBPS

**Comment by LanderMoerkerke** [comment]
Pulling from master and building it locally again worked for me, thanks @jesseduffield!

**Comment by jesseduffield** [comment]
Good to hear @LanderMoerkerke , I'll close this issue and cut a new release

**Comment by kristijanhusak** [comment]
@jesseduffield I can confirm that latest master works for me now.
