### ISSUE TITLE
Can't scroll in an actual commit

### ISSUE THREAD

**Issue by daften** [jesseduffield/lazygit#97]
When I select a commit, I can't seem to scroll through the contents of that commit. The hints at the bottom of the screen don't indicate that's possible either.

**Comment by jesseduffield** [comment]
the pageup+pagedown keys allow for you to scroll throught, or fn+up/fn+down for mac. I just pushed a commit adding them to the banner at the bottom of the app. It's getting to the point where we need a better way to display the keybindings. I still like the idea of having that banner scroll horizontally after a delay (resetting position each time you switch panels) but I think the longterm solution will be hitting a keybinding hotkey and then getting a panel showing you every keybinding for that panel.

**Comment by daften** [comment]
Aha, thanks. For the quick reply and the explanation.
I'll close this issue, since this should be fixed now. :)
