### ISSUE TITLE
"Error: running subprocess" on execution of external command

### ISSUE THREAD

**Issue by band-a-prend** [jesseduffield/lazygit#974]
**Describe the bug**
Trying to run external command result in "Error: running subprocess"

**To Reproduce**
1. Run lazygit in git repo
2. Enter `Shoft + :` to run external command
3. Enter e.g. `git pull`, `git commit -S` etc.
4. See error "Error: running subprocess"

**Expected behavior**
Execution of requested external command

**Screenshots**
![lazygit_0 22 0_error](https://user-images.githubusercontent.com/18756734/91208193-7ebd8a80-e712-11ea-82a1-daf2a3163998.png)

**Desktop (please complete the following information):**
 - OS: Gentoo LInux
 - Lazygit Version: 0.22.0

**Additional context**
The previous version lazygit-0.20.9 works as expected

**Comment by jesseduffield** [comment]
Thanks for raising this issue @band-a-prend, fixed in 0.22.1 :)

**Comment by band-a-prend** [comment]
Thank you for so quick fix!
