### ISSUE TITLE
Arch Linux (AUR) bin package

### ISSUE THREAD

**Issue by robinhz** [jesseduffield/lazygit#983]
**Describe the solution you'd like**
A lazygit-bin package in the AUR

**Additional context**
A binary package of lazygit (stable) in the AUR would be a great addition. It's a simple alternative to the lazygit (stable) AUR so that the user can choose between compiling it or just using the binary.

**CI/CD**
Also a CI/CD Pipeline with GitHub Actions would make it more efficient to keep the stable lazygit AUR repos up to date:
Release (Create Go Binary) :arrow_right: Generate PKGBUILD :arrow_right: Publish to the AUR

**Example**
An example (without guarantees), can be found at the bottom of this yaml file: [sane-fmt deploy yaml](https://github.com/sane-fmt/sane-fmt/blob/c07ce4f09c0b8dfa902d28753ebb3800268183f5/.github/workflows/deploy.yaml)

**AUR Maintainer Mentions**
@fuero @frealgagu 

Thanks in advance :+1: :blush:

**Comment by jesseduffield** [comment]
@dawidd6 is this something you would be interested in? If not I'm happy to take a look

**Comment by dawidd6** [comment]
@jesseduffield go ahead :+1:

**Comment by jesseduffield** [comment]
I know I said I was happy to take a look but I haven't found the time to tackle this. If anybody else is eager let me know!

**Comment by frealgagu** [comment]
lazygit was included in the official community repo since March 12th. I think it's not necessary to handle a bin AUR anymore.

**Comment by jesseduffield** [comment]
@frealgagu sweet! Do you know how that gets updated? Is it built off of this repo's master branch periodically for example?

**Comment by mark2185** [comment]
@jesseduffield packages have assigned maintainer(s) and it's up to them to keep it up to date. In case it is out of date, any user can mark it so.
```
If you notice that a package is out-of-date (i.e., there is a newer stable release available), then please notify us by using the Flag button in the Package Details screen. This will notify the maintainer(s) responsible for that package so they can update it. If the package is unmaintained, the notification will be sent to a developer mailing list.
```

It currently has 2 maintainers so I presume this issue can be closed.

**Comment by frealgagu** [comment]
lazygit is currently in official ArchLinux repos, so it's not necessary to have an AUR version. This issue can be closed safely.

**Comment by jesseduffield** [comment]
alrighty @frealgagu I'll take your word for it. Closing
