### ISSUE TITLE
Deleting remote branch hangs lazygit

### ISSUE THREAD

**Issue by sebastiangelotte** [jesseduffield/lazygit#986]
**Describe the bug**

When trying to delete a remote branch **that's no longer present on the remote**, lazygit hangs with "deleting" spinner spinning forever.

**To Reproduce**
1. Create remote branch
2. Make sure the Remotes list in lazygit shows the branch
3. Delete branch on remote (in github.com's web interface for example)
4. Press `d` on the remote branch in lazygit

**Expected behavior**

I expected the branch to be pruned, or lazygit to fail more gracefully. No keybindings work, can't quit or change views.

**Screenshots**

Here I pressed `d` on "hotfix/s04e01":
![image](https://user-images.githubusercontent.com/22306228/91656065-ecbcd580-eab5-11ea-8ebb-4a2bccb1af4c.png)

**Desktop (please complete the following information):**

 - OS: Manjaro Linux
 - Lazygit Version: v.0.20.9

**Comment by irateswami** [comment]
I might take a stab at this

**Comment by sebastiangelotte** [comment]
> I might take a stab at this and want to be clear, that while you're running a lazygit session, and then delete the branch remotely, and then try to delete the branch via lg, it freezes?

Yes, correct. The "spinner" in the bottom keeps spinning, so it's not completely frozen, just not responsive to any input.

**Comment by irateswami** [comment]
Interesting, the code does do an exec.Command with a git push, I'm thinking that git does some kind of prompt or whatever and it's not being handled. I'm on it!

**Comment by vaheqelyan** [comment]
Tested on `commit=96f821b84100a75852715d6e4975f3a62cad7fbb, build date=2020-07-22T12:44:46Z, build source=binaryRelease, version=0.20.9, os=linux, arch=amd64` works great

**Comment by jesseduffield** [comment]
As mentioned above we were not checking if git prompted for a password. That's now fixed in https://github.com/jesseduffield/lazygit/pull/1045

**Comment by jesseduffield** [comment]
I'm gonna close this issue but let me know if the issue persists on master and I'll reopen :)
