### ISSUE TITLE
Sort (or Filter) Files by Staged/Not Staged

### ISSUE THREAD

**Issue by fedoranvar** [jesseduffield/lazygit#988]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I need to see only staged files or only not-staged

**Describe the solution you'd like**
I want to be able to sort Files due to them statuses (Staged/Not Staged)

**Describe alternatives you've considered**
Don't have any at the moment

**Additional context**
Haven't found such feature in README or in issues.

**Comment by Yuuki77** [comment]
I will give it a shot 💪

**Comment by Liberatys** [comment]
@jesseduffield I'd work on this if that is okay with you? Has been raised by multiple other people

**Comment by jesseduffield** [comment]
@liberatys sounds good :)

**Comment by Liberatys** [comment]
@jesseduffield Nice :D 👍🏻 Will tackle it over the coming weekend.
