### ISSUE TITLE
Reverse color for selected panel

### ISSUE THREAD

**Issue by AaronGillBraun** [jesseduffield/lazygit#99]
This is entirely opinionated, but I've noticed that sometimes it can be confusing keeping track of the currently selected side-pane.

I think it should be reversed so that all of them are greyed out, until it is selected, rather than them all being "highlighted" until selected. It makes more sense in general, and makes it look more visually pleasing.

This is just to see if other people felt the same, and if thats the case I could always make a PR if someone else doesn't want to.

**Comment by sundarv85** [comment]
If the current file for which the diff is being shown, can also be highlighted it will be great

**Comment by jesseduffield** [comment]
I was doing it like this https://github.com/jesseduffield/lazygit/issues/38 for a bit but it looked broken on too many people's color themes so I reverted it. 

I don't really like the look of reverse, if you're referring to the `reverse` color attribute. If you mean something different please post a screenshot of what you mean. 

We might need to end up having a configurable user option for what to do with active/inactive borders. If people could pick their own border colors to be something like this
![image](https://user-images.githubusercontent.com/8456633/43936598-8fe9395c-9c9c-11e8-9978-389e28584f47.png)

That would be rad. But I'm also a little scared of adding config options given that it means we gotta make stuff backwards compatible

**Comment by AaronGillBraun** [comment]
Ah ok. I wasn’t aware of the term issue. My term is a darker material theme so it’d look fine.

What do you mean make it backward compatible? Wouldn’t we just have a defaults file, and it could be overwritten by a .lzgitrc file or something.

**Comment by glvr182** [comment]
@jesseduffield I think this issue could be marked as "configurable UI" and so it might be possible to close this one.

**Comment by jesseduffield** [comment]
closing
