### ISSUE TITLE
Please add amendment operation loading indicator

### ISSUE THREAD

**Issue by Jagget** [jesseduffield/lazygit#993]
**Is your feature request related to a problem? Please describe.**
Amendment of the current commit is running without any indication

**Describe the solution you'd like**
I'd like to see loading indicator that shows that process is on the go.

**Comment by jesseduffield** [comment]
fixed in https://github.com/jesseduffield/lazygit/pull/1002

**Comment by jesseduffield** [comment]
let me know if you have any issues, closing :)

**Comment by Jagget** [comment]
@jesseduffield works super cool, thank you! would like to have the same indicator for commit operation :D
