### ISSUE TITLE
--config option description ambiguous

### ISSUE THREAD

**Issue by daveriedstra** [jesseduffield/lazygit#997]
**Describe the bug**
lazygit's help output describes the `--config` option as "Print the current default config". At a glance, it's not clear whether this means "the current configuration" or "the default configuration". (In fact, I was in the middle of writing up a bug report describing how `--config` wasn't reporting my configuration changes.) This should be more clear.

**To Reproduce**
1. run `lazygit --help` to discover lazygit options
2. modify lazygit config file
3. run `lazygit --config` to confirm changes are read by lazygit
4. become confused that lazygit isn't recognizing config changes
5. realize that the output of `--config` only reports _default_ configuration, not the _current_ configuration

**Expected behavior**
lazygit should describe the option as "Print the default configuration" (ie, remove the word "current"). (Side note: it would be nice if there was a separate option to show the current configuration as well.)

**Desktop (please complete the following information):**
 - OS: Pop!_OS 20.04
 - Lazygit Version: 0.22.1

**Comment by jesseduffield** [comment]
fixed in https://github.com/jesseduffield/lazygit/pull/1004. Printing the current config would be a little trickier to implement (and it's currently possible to open by going 'o' on the status panel) but feel free to raise a separate ticket for that :)
